[enhancement] Add string information for error
RT-Thread/rt-thread pull request #3186
Opened 2019-11-07 15:44 UTC by a1012112796

## 拉取/合并请求描述：(PR description)

[
   1. add rt_strerror();
   2. add %M %m to rt_kprintf()
  3. chang %03d to %M in list_thread errorno
  test on stm32f427-robomaster-a with mdk5
  result:
       ![图片](https://user-images.githubusercontent.com/25342410/68403738-60ed5c00-01b8-11ea-8de5-25ab7570aed9.png)

]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2019-11-08 22:24 UTC, BernardXiong commented on src/kservice.c
> +    }else if(mode == RT_STRERROR_SHORT)
请保持RTT的代码风格，每个if/else都在一行上，if与`(`间的空格需要留出。

2019-11-08 22:25 UTC, BernardXiong commented on src/kservice.c
> +        case 'M':
不建议加入m/M，这个意义并不那么大，反而引入新的格式。

2019-11-08 22:26 UTC, BernardXiong commented on src/kservice.c
> +const char rt_errno_verbose[][24] =
请加入static修饰，仅限于这个文件使用。

2019-11-08 22:26 UTC, BernardXiong commented on src/kservice.c
> +    "no error",
首字母请大写

2019-11-08 22:26 UTC, BernardXiong commented on src/kservice.c
> +const char rt_errno_short[][7] =
short模式意义相对比较小，请移除吧

2019-11-10 03:29 UTC, a1012112796 commented on src/kservice.c
> +        case 'M':
您好，我觉得引入%m是有意义的，首先可以简化输出错误语句的写法，只需要在rt_kprintf加入一个参数而不是调用一个函数。其次，可以像%s一样用+-号等实现输出格式控制，并且%m是标准c规定的参数格式，也不算新的格式。所以我强烈建议加入%m，谢谢！

2019-11-10 03:30 UTC, a1012112796 commented on src/kservice.c
> +const char rt_errno_short[][7] =
您好，经过仔细分析，我觉得short模式比long模式各有意义，我的理由如下：首先对开发者而言，标准错误只是一个符号，用一个简单的，利于理解的缩写来表示，就已经足够了。输出一句短语固然显得更加友好，但实际意义并不大，其二，short模式占据的存储空间较小，并且在输出时可以方便的放入表格等输出方式中，例如我在list_thread中所做的修改。所以我建议删去long模式保留short模式作为唯一输出格式，并对部分缩写做了扩展。谢谢！

2019-11-10 03:31 UTC, a1012112796 commented
还有一点不知是否必要修改，就是经过修改后rt_strerror函数的逻辑行数只有三行，请问是否可以添加rt_inline参数修饰？谢谢

2019-11-11 04:02 UTC, a1012112796 commented
@BernardXiong 您好，请问方便给个原因吗，谢谢

2022-06-20 21:32 UTC, mysterywolf commented
请采用merge方式合并这个pr https://github.com/a1012112796/rt-thread/pulls

2022-06-22 14:18 UTC, mysterywolf commented
@a1012112796 请修复一下CI的报错

2022-06-23 00:15 UTC, a1012112796 commented on src/kservice.c
> +static const char rt_errno_strs[][] =
```suggestion
static const char rt_errno_strs[][7] =
```

2022-06-23 00:20 UTC, mysterywolf requested changes

2022-06-23 00:32 UTC, mysterywolf approved these changes

2022-06-25 01:34 UTC, mysterywolf requested changes

2022-06-25 01:34 UTC, mysterywolf commented on src/kservice.c
> +                s = va_arg(args, char *);
对于%m的新增内容请予以删除，rt_kprintf的目标是保持小巧，满足32位和64位下基本的整形和字符串输出需求，这种犄角旮旯的功能该舍弃的需要舍弃。

2022-06-25 01:34 UTC, mysterywolf commented on components/finsh/cmd.c
> +                    rt_kprintf(" 0x%08x 0x%08x    %02d%%   0x%08x %m\n",
使用%s + rt_strerror(thread->error) 的方式代替%m输出

2022-06-25 07:17 UTC, mysterywolf approved these changes

2022-06-27 03:32 UTC, Guozhanxin approved these changes

2022-06-29 06:21 UTC, merged