修复STM32的硬件定时器的时钟配置问题
RT-Thread/rt-thread pull request #3846
Opened 2020-08-25 06:58 UTC by ynkan

## 拉取/合并请求描述：(PR description)

[
       修复STM32硬件定时器配置时候可能存在的逻辑问题。例如当 APB1CLKDivider 或 APB2CLKDivider为RCC_HCLK_DIV1的时候，此时旧版本的 drv_hwtimer.c 中仍然会以 PCLKx 频率的2倍计算. 由此造成设置的定时时间变成了原来的2倍。例如定时1S，实际得到的结果是2S。
       由“STM32的硬件定时器在 APBxCLKDivider 为 RCC_HCLK_DIV1 的时候，timer clocks 频率等于外设总线时钟PCLKx， 反之 timer clocks 为 PCLKx 的2倍”规则。在进行定时器计算的时候均先获取当前 APBxCLKDivider 的配置情况，然后再决定是否需要对PCLx的时钟进行倍频计算。

当前已经测试板卡/MCU:STM32F412xx实际运行测试。其他STM32F0xx、STM32F1xx、STM32F2xx、STM32F3xx、STM32F7xx、STM32H7xx、STM32MP15x系列均使用STM32CubeMX进行验证，时钟逻辑均是如此。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-08-25 06:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=3846) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=3846) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=3846) it.</sub>

2020-08-27 01:55 UTC, SummerLife requested changes
感谢提交代码，还可以写的更易读一些呀 😄

2020-08-27 01:55 UTC, SummerLife commented on bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c
> +        uint32_t pclk1_doubler = 1 + ( RCC_ClkInitStruct.APB1CLKDivider != RCC_HCLK_DIV1 );
```
uint32_t pclk1_doubler = 1 + ( RCC_ClkInitStruct.APB1CLKDivider != RCC_HCLK_DIV1 ); 
uint32_t pclk2_doubler = 1 + ( RCC_ClkInitStruct.APB2CLKDivider != RCC_HCLK_DIV1 );
```

这两行需要写的更易读一些，不要出现数字和逻辑真假的数学运算，可以使其默认为 1，如果符合某个条件在赋值为 2 。另外紧挨着括号内不需要加空格，和其他代码风格保持一致。

2020-08-27 02:46 UTC, ynkan commented on bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c
> +        uint32_t pclk1_doubler = 1 + ( RCC_ClkInitStruct.APB1CLKDivider != RCC_HCLK_DIV1 );
好的，已调整。

2020-08-27 06:30 UTC, SummerLife requested changes

2020-08-27 06:30 UTC, SummerLife commented on bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c
> +        uint32_t FLatency = 0;
这样写代码重复了，推荐你将获取倍频值的功能封装成函数，类似这样：

```
static void pclk_doubler_get(uint32_t *pclk1_doubler, uint32_t *pclk2_doubler)
{
    uint32_t flatency = 0;
    RCC_ClkInitTypeDef RCC_ClkInitStruct;
    HAL_RCC_GetClockConfig(&RCC_ClkInitStruct, &flatency);

    *pclk1_doubler = 1;
    *pclk2_doubler = 1;

    if(RCC_ClkInitStruct.APB1CLKDivider != RCC_HCLK_DIV1)
    {
         *pclk1_doubler = 2;
    }

    if(RCC_ClkInitStruct.APB2CLKDivider != RCC_HCLK_DIV1)
    {
         *pclk2_doubler = 2;
    }

    return;
}
```

调用时这样就好，代码显得会更加整洁。


![image](https://user-images.githubusercontent.com/22132180/91400172-cb6ba780-e871-11ea-803d-48ba7fea4114.png)

2020-08-27 07:33 UTC, ynkan commented on bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c
> +        uint32_t pclk1_doubler = 1 + ( RCC_ClkInitStruct.APB1CLKDivider != RCC_HCLK_DIV1 );
好的，这样确实看着精神些，已做调整并提交了。不过在刚刚又遇到了一个新疑问，例如这个位置如果我按照这样，和他们的风格一致。但是严格意义上来说使用的结果都将传递给驱动库中的 HAL_XXXX 函数，他们使用的都是 <stdint.h> 中的类型。直接使用 uint32_t 似乎又有点不太好看，所以我只能把他换个位置。
`
    case HWTIMER_CTRL_FREQ_SET:
    {
        rt_uint32_t freq;
        rt_uint16_t val;
        rt_uint32_t pclk1_doubler, pclk2_doubler;

        pclkx_doubler_get(&pclk1_doubler, &pclk2_doubler);

        /* set timer frequence */
        freq = *((rt_uint32_t *)arg);
`
这些变量有时候函数使用的是 rt_xxx_t，有时候又是使用的 stdint.h 中的定义 xxx_t。似乎 coding_style_cn.md 没有做约定。这种情况有什么好的建议吗

2020-08-27 07:59 UTC, SummerLife commented on bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c
> +        uint32_t pclk1_doubler = 1 + ( RCC_ClkInitStruct.APB1CLKDivider != RCC_HCLK_DIV1 );
写 rt-thread 的驱动都写成 rt_xxx_t 就好了，我先前没注意到这个问题，如果我写的话，会都加上 rt_，另外如果给关键函数加上一句注释就更好了。

2020-08-27 08:55 UTC, SummerLife approved these changes
great 😃

2020-08-27 09:32 UTC, ynkan commented on bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c
> +        uint32_t pclk1_doubler = 1 + ( RCC_ClkInitStruct.APB1CLKDivider != RCC_HCLK_DIV1 );
好的，后面尽量都考虑使用 rt_xxx_t 类型的数值。第一次提交，多谢指点。^_^

2020-08-27 11:43 UTC, merged