add new functions for stm32 drv_gpio(recommit)
RT-Thread/rt-thread pull request #3852
Opened 2020-08-26 16:14 UTC by Forest-Rain

## 拉取/合并请求描述：(PR description)

[
1. 新增GET_GPIO_PORT and GET_GPIO_PIN 宏，用于根据引脚索引号（比如 15）转换为STM32 HAL的GPIOx名(比如GPIOA)与 
    GPIO_PIN_x引脚名（比如GPIO_PIN_15）,有助于rt_hw_spi_device_attach的CS引脚定义
2. 新增stm32_pin_get() 函数用于 通过输入引脚字符串来获取 引脚索引号
 - 比如输入 "A4"  ( GPIOA, GPIO_PIN_4 )-->  4，有助于通过menuconfig来直接定义STM32 GPIO引脚
3. 在nucleo-L476rg平台测试通过
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-09-04 09:55 UTC, SummerLife requested changes
感谢提交代码，有一些细节还需要讨论一下 🌞

2020-09-04 09:55 UTC, SummerLife commented on bsp/stm32/libraries/HAL_Drivers/drv_gpio.h
> +#define GET_GPIO_PORT(pin) (GPIO_TypeDef *)( GPIOA_BASE + (uint32_t) ( pin >> 4 ) * 0x0400UL )
我感觉这个意义不大，直接使用 HAL 里面提供的宏似乎就可以了，或者我没有完全理解用户这个宏有什么额外的好处，能否再解释的更详细一些。另外还请测试其他系列这个两个宏是否可以正常使用。

2020-09-04 09:55 UTC, SummerLife commented on bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
> +    // convert pin name to pin number
注释符号请使用和其他注释一致的 /* */ 来实现

2020-09-04 09:55 UTC, SummerLife commented on bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
> +    char pin_index = strtol(&pin_name[1],0,10);
strtol 这个函数是在各个编译器下都有提供的吗？

2020-09-09 00:17 UTC, closed without merging

2020-09-13 00:46 UTC, Forest-Rain commented on bsp/stm32/libraries/HAL_Drivers/drv_gpio.h
> +#define GET_GPIO_PORT(pin) (GPIO_TypeDef *)( GPIOA_BASE + (uint32_t) ( pin >> 4 ) * 0x0400UL )
当前主要用于rt_hw_spi_device_attach，通过pin来获取MCU的GPIOx与GPIO_PIN_x
比如
rt_hw_spi_device_attach(SPI_BUS_NAME, SPI_DEVICE_NAME, GET_GPIO_PORT(SPI_NSS_PIN),GET_GPIO_PIN(SPI_NSS_PIN));

2020-09-13 00:46 UTC, Forest-Rain commented on bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
> +    // convert pin name to pin number
ok