add rtc device driver for nrf52x
RT-Thread/rt-thread pull request #3911
Opened 2020-09-13 17:12 UTC by chenyingchun0312

Signed-off-by: chenyingchun0312 <chenyingchun0312@163.com>

## 拉取/合并请求描述：(PR description)

[
添加nrf52x rtc设备驱动， 利用nrf52x的RTC(实时计数器模块)， 实现RTC实时时钟设备功能， 已经在青风52832开发板上测试过
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-09-17 12:45 UTC, supperthomas requested changes

2020-09-17 12:45 UTC, supperthomas commented on bsp/nrf5x/libraries/drivers/drv_rtc.c
> +    const nrfx_rtc_t rtc_instance = NRFX_RTC_INSTANCE(2);
Please support RTC0 RTC1 RTC2

2020-09-19 00:10 UTC, supperthomas requested changes

2020-09-19 00:10 UTC, supperthomas commented on bsp/nrf5x/nrf52832/board/Kconfig
> +
Please sync the nrf52840 Kconfig to this config. by the way , add the config to the nrf52840 RTC driver

2020-09-22 04:29 UTC, chenyingchun0312 commented on bsp/nrf5x/libraries/drivers/drv_rtc.c
> +    const nrfx_rtc_t rtc_instance = NRFX_RTC_INSTANCE(2);
好的， 收到

2020-09-23 15:43 UTC, supperthomas approved these changes

2020-09-24 00:04 UTC, merged