[bsp][stm32] add usart3 driver init for stm32l4r5-nucleo
RT-Thread/rt-thread pull request #3914
Opened 2020-09-14 06:26 UTC by luhuadong

## 拉取/合并请求描述：(PR description)

[
经检查发现该 BSP 还没配置好 README 中说明支持的 USART3 外设，而 stm32l4r5-nucleo 的 usart3 对应 Arduino 接口的 D0/Rx 和 D1/Tx 接口，在测试和原型开发中经常用到，因此为其添加初始化配置，避免每次都要用 STM32CubeMX 配置的麻烦。

已在 stm32l4r5-nucleo 开发板中测试通过。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-09-27 00:20 UTC, BernardXiong commented
ping @Guozhanxin

2020-10-11 05:38 UTC, KyleChenjh commented
@luhuadong 这个commit仅上传了CubeMX 生成的stm32l4xx_hal_msp.c 文件，建议把CubeMX 的配置工程等文件也提交上来，不然其他用户再次使用STM32CubeMX 生成工程时，又会回退到之前的配置。

2020-10-13 02:38 UTC, BernardXiong requested changes
commit仅上传了CubeMX 生成的stm32l4xx_hal_msp.c 文件，建议把CubeMX 的配置工程等文件也提交上来，不然其他用户再次使用STM32CubeMX 生成工程时，又会回退到之前的配置。

2020-10-13 14:29 UTC, luhuadong commented
重新用CubeMX配置工程并补充了必要的文件

2020-10-24 03:13 UTC, Guozhanxin commented
@whj4674672 看下这个 pr 吧

2020-10-24 09:29 UTC, KyleChenjh commented
经过验证，没什么问题。 @BernardXiong  @Guozhanxin

2020-10-31 07:55 UTC, luhuadong commented
:heart:

2020-11-03 02:53 UTC, merged