fix bug #3902
RT-Thread/rt-thread pull request #3921
Opened 2020-09-17 06:40 UTC by mysterywolf

## 拉取/合并请求描述：(PR description)

[
fix bug #3902
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-09-18 02:20 UTC, geniusgogo requested changes
我在MDK5环境下测试发现如下问题：
1.采用AC6编译没有问题
2.采用AC5编译勾选GNU模式有问题

另外虽然我们AC6有__CLANG_ARM选项，但是却在MDK的官方文档“B6.2 Predefined macros”中找不到其介绍。更多的是看到这样能用就这样用了。
是不是有更好的选项能直接判断是当前是AC5/AC6的编译器？

2020-09-18 08:34 UTC, mysterywolf commented
这样子可行否 (defined( __GNUC__ ) && !defined(__CLANG_ARM) && !defined (__CC_ARM))

2020-09-18 10:36 UTC, geniusgogo commented
> 这样子可行否 (defined( **GNUC** ) && !defined(__CLANG_ARM) && !defined (__CC_ARM))

太长了丑啊，你看看是否可以用
`__ARMCC_VERSION`或者`__ARMCOMPILER_VERSION`来统一 一下？

2020-09-22 02:05 UTC, geniusgogo reviewed
本地编译测试通过，但是像ARMCC环境下的__attribute__((__packed__))属于隐藏技能。文档公开的指令应该是__attribute__((packed))

2020-10-02 02:29 UTC, closed without merging