[bsp] add sparkfun-redv bsp
RT-Thread/rt-thread pull request #4001
Opened 2020-10-31 07:47 UTC by luhuadong

## 拉取/合并请求描述：(PR description)

[
增加了一个 sparkfun-redv bsp，red-v 的核心 SoC 是 SiFive FE310，已在 red-v 板卡上运行 rt-thread，驱动部分有带完善。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-11-03 00:24 UTC, BernardXiong commented
是否可能合并？e310的bsp多了，也是一件麻烦事

2020-11-03 02:34 UTC, luhuadong commented
> 是否可能合并？e310的bsp多了，也是一件麻烦事

是的，或者单独建个目录，把 e310 的 bsp 放一起，比如 hifive1、hifive-revb 之类的，然后维护同一套 driver 库和 freedom-e-sdk

2020-11-04 15:26 UTC, chenyingchun0312 commented
单独建一个目录，把e310的bsp放在一起，还是比较合适的

2020-11-05 10:33 UTC, luhuadong commented
> 单独建一个目录，把e310的bsp放在一起，还是比较合适的

是呀，看看怎么推进一下？我没有其他 e310 的板子，不好验证 BSP，要不成立个工作小组讨论一下？或者先揉到一起，其他开发者用到发现问题再进一步修改？这块代码现在用的人应该还不多，影响较小。

2021-12-15 22:58 UTC, mysterywolf commented
这个可否先合并？已经挂了一年了，至于整合其他同系列bsp的事情，单独开pr来解决，不能让一个具体型号的bsp贡献者莫名其妙的负责一堆与自己毫无相关的东西。

2021-12-20 07:33 UTC, mysterywolf commented
@luhuadong 请使用formatting脚本把这个提交内容扫一下，准备review了。 https://github.com/mysterywolf/formatting

2021-12-20 08:20 UTC, mysterywolf approved these changes

2021-12-21 08:57 UTC, Guozhanxin commented on bsp/sparkfun-redv/SConstruct
> +	CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
这个改成 CFLAG 吧，参考 https://github.com/RT-Thread/rt-thread/pull/5397

2021-12-23 11:37 UTC, mysterywolf requested changes

2021-12-23 11:37 UTC, mysterywolf commented on bsp/sparkfun-redv/freedom-e-sdk/bsp/env/freedom-e300-hifive1/init.c
> +#include "rtthread.h"
#include <rtthread.h>

2021-12-23 11:43 UTC, mysterywolf approved these changes

2021-12-28 06:41 UTC, merged