[update] add GBE dirver for stm32mp1dk1
RT-Thread/rt-thread pull request #4034
Opened 2020-11-18 07:03 UTC by thread-liu

## 拉取/合并请求描述：(PR description)

[
添加 M4 核千兆以太网驱动代码，已在 DK1 开发板上测试完成。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-12-02 07:44 UTC, Guozhanxin requested changes

2020-12-02 07:44 UTC, Guozhanxin commented on bsp/stm32/libraries/STM32MPxx_HAL/SConscript
> -#    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_qspi.c']
这个为什么要改成默认就添加啊

2020-12-02 07:44 UTC, Guozhanxin commented on bsp/stm32/libraries/STM32MPxx_HAL/SConscript
> -    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_eth.c']
我们是目前还不支持网络吗？

2020-12-02 07:44 UTC, Guozhanxin commented on bsp/stm32/libraries/STM32MPxx_HAL/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_sd.c
> +        loop ++;
这里的修改，跟st官方确认过了吗

2020-12-02 07:44 UTC, Guozhanxin commented on bsp/stm32/stm32mp157a-st-discovery/board/ports/audio/audio_play.c
> +MSH_CMD_EXPORT(wavrecord_sample, record voice to a wav file);
这个是有软件包的吧，为什么要上传一个这个文件

2020-12-02 07:54 UTC, thread-liu commented on bsp/stm32/libraries/STM32MPxx_HAL/SConscript
> -    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_eth.c']
MP1 暂时不支持 ETH hal 库

2020-12-02 07:55 UTC, thread-liu commented on bsp/stm32/libraries/STM32MPxx_HAL/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_sd.c
> +        loop ++;
向 ST 技术提交了 bug, 会在下一版本修复此问题

2020-12-02 07:55 UTC, thread-liu commented on bsp/stm32/stm32mp157a-st-discovery/board/ports/audio/audio_play.c
> +MSH_CMD_EXPORT(wavrecord_sample, record voice to a wav file);
提供简单的测试用例，方便 ST 进行测试

2020-12-02 07:56 UTC, thread-liu commented on bsp/stm32/libraries/STM32MPxx_HAL/SConscript
> -#    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_qspi.c']
删除多余代码

2020-12-02 07:59 UTC, Guozhanxin approved these changes

2020-12-03 00:41 UTC, BernardXiong commented
Please resolve the conflict file.

2020-12-05 01:54 UTC, thread-liu commented
> Please resolve the conflict file.

The Conflict File has been resolved

2020-12-05 02:27 UTC, merged