Rtt ls2k
RT-Thread/rt-thread pull request #4108
Opened 2020-11-30 07:07 UTC by 0xcccccccccccc

## 拉取/合并请求描述：(PR description)

[
添加了LS2K1000的SPI和UART多串口&可调波特率支持。
在龙芯2K教育派和龙芯2K龙芯派上测试可用。
经历了2020全国大学生嵌入式芯片与系统设计竞赛暨全国大学生智能互联创新大赛一整天的烤机考验，工作无异常。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-11-30 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4108) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4108) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=4108) it.</sub>

2020-12-02 02:56 UTC, bigmagic123 commented
注意提交文件中的格式排版，将tab键换成4个空格代替。
uart最好也在KConfig中添加配置项，可以通过宏定义进行选择约束。

2020-12-08 01:03 UTC, BernardXiong requested changes
请多注意代码内容，不必要的代码，注释，空行，请移除掉。

2020-12-08 01:03 UTC, BernardXiong commented on bsp/ls2kdev/README.md
> +维护人：[bernard][4],[0xcccccccccccc][5]
龙芯2K的维护人是bigmagic。 @bigmagic123 后续也帮忙修改下，这个BSP维护人是你这边

2020-12-08 01:03 UTC, BernardXiong commented on bsp/ls2kdev/drivers/drv_spi.c
> +
请保持代码紧凑，整洁，不出现连续的多行空行

2020-12-08 01:03 UTC, BernardXiong commented on bsp/ls2kdev/drivers/drv_spi.c
> +// #define RT_USING_SPI_GPIOCS
不必要的代码、注释 请移除

2020-12-08 01:03 UTC, BernardXiong commented on bsp/ls2kdev/rtconfig.py
> +	EXEC_PATH   = "/home/ma/mips-2015.05/bin/"
请移除这部分的修改

2020-12-09 09:21 UTC, bigmagic123 approved these changes
ok

2020-12-10 08:14 UTC, BernardXiong commented on bsp/ls2kdev/drivers/drv_spi.c
> +#include <stdio.h>
Please add copyright information.

2020-12-10 08:14 UTC, BernardXiong commented on bsp/ls2kdev/drivers/drv_spi.h
> +#ifndef LS2K_DRV_SPI_H
Please add copyright information.

2020-12-11 09:57 UTC, merged