[ioctl] ioctl函数实现设置和获取终端窗口功能
RT-Thread/rt-thread pull request #4118
Opened 2020-12-05 12:19 UTC by mysterywolf

## 拉取/合并请求描述：(PR description)

[
示例代码：
```c
#include <sys/ioctl.h>
#include <unistd.h>

        struct winsize window;
        window.ws_col = 10;
        window.ws_row = 10;
        ioctl(STDOUT_FILENO, TIOCSWINSZ, &window);
```
已经在正点原子潘多拉板子通过测试, 目前可以确保在移植linux设计到获取窗口大小时，可以返回窗口大小数据（目前数据固定为长80宽24，因为我没有找到如何让putty自动返回当前的窗口大小，但是不影响正常使用）。在设置窗口大小是，终端窗口会自动调整至设置的大小。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2020-12-06 16:12 UTC, BernardXiong requested changes

2020-12-06 16:12 UTC, BernardXiong commented on components/drivers/serial/serial.c
> +                p_winsize->ws_col = 80;
please use correct way to get col and row.

2020-12-06 16:12 UTC, BernardXiong commented on components/drivers/serial/serial.c
> +                rt_kprintf("\x1b[8;%d;%dt", p_winsize->ws_col, p_winsize->ws_row);
Why use `rt_kprintf` to dump col and row?

2020-12-06 18:12 UTC, mysterywolf commented on components/drivers/serial/serial.c
> +                rt_kprintf("\x1b[8;%d;%dt", p_winsize->ws_col, p_winsize->ws_row);
这个是终端ANSI命令，需要用rt_kprintf 发送这个指令，类似的还有比如ANSI颜色指令。

2020-12-06 18:14 UTC, mysterywolf commented on components/drivers/serial/serial.c
> +                p_winsize->ws_col = 80;
目前我没有找到有效让终端实时返回其窗口大小的方法，因此先给固定值，长80宽24是所有终端的默认大小。后人如果有方法再予以补充。

2020-12-07 05:54 UTC, BernardXiong commented on components/drivers/serial/serial.c
> +                p_winsize->ws_col = 80;
所以是可以在msh那边来确定row, col？

2020-12-07 08:46 UTC, mysterywolf commented on components/drivers/serial/serial.c
> +                p_winsize->ws_col = 80;
理论上是的，我发送一个指令给putty或者其他终端软件，putty会自动返回给我当前的窗口宽度和长度。但是我目前还没搞明白这个指令是什么，因此暂时先赋值一个固定值，先让这个函数用起来。

2020-12-13 13:40 UTC, closed without merging