add error checks of function rt_event_recv()
RT-Thread/rt-thread pull request #4134
Opened 2020-12-07 14:44 UTC by Hxinrong

2020-12-09 06:44 UTC, Guozhanxin commented on components/dfs/filesystems/jffs2/src/gcthread.c
> +          RT_ASSERT(result == RT_EOK);
这里应该要考虑超时的情况的，直接 ASSERT 是不是不太好

2020-12-09 06:45 UTC, Guozhanxin commented on bsp/nrf5x/libraries/templates/nrf52x/applications/ble_nus_app.c
> +        RT_ASSERT(result == RT_EOK);
这里应该要考虑超时的情况的，直接 ASSERT 是不是不太好

2020-12-09 06:46 UTC, Guozhanxin commented on components/dfs/filesystems/jffs2/src/gcthread.c
> +     RT_ASSERT(result == RT_EOK);
这里是不是也有可能处理下错误，进行下异常处理？

2020-12-13 11:13 UTC, Hxinrong commented
已对错误处理方案做出了修改，不知该修复是否合适？

2020-12-15 02:59 UTC, BernardXiong requested changes
Please take care of code style.

2020-12-15 02:59 UTC, BernardXiong commented on components/dfs/filesystems/jffs2/src/gcthread.c
> +	   rt_uint32_t  e;
Please take care of indentation.

2020-12-15 02:59 UTC, BernardXiong commented on bsp/nrf5x/libraries/templates/nrf52x/applications/ble_nus_app.c
> +        if (result == -RT_ETIMEOUT) {
Please keep code style for `{`.

2020-12-30 05:44 UTC, merged