爲RT1052移植QTMR的PWM
RT-Thread/rt-thread pull request #4335
Opened 2021-02-13 09:57 UTC by LeeChunHei

## 拉取/合并请求描述：(PR description)

[
爲RT1052移植QTMR的PWM
Port QTMR to drv_pwm

已經在自製的imxrt1052 板子進行了對QTMR PWM驅動測試
Had tested QTMR PWM with a custom made imxrt1052 board
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2021-02-13 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4335) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4335) before we can accept your contribution.<br/><hr/>**“LeeChunHei”** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=4335) it.</sub>

2021-02-22 07:58 UTC, xinyigao commented on bsp/imxrt/libraries/drivers/drv_pwm.c
> +            return RT_ERROR;
返回错误添加负号，例：return -RT_ERROR;

2021-02-22 07:59 UTC, xinyigao commented on bsp/imxrt/libraries/drivers/drv_pwm.c
> +        return RT_ERROR;
返回错误添加负号，例：return -RT_ERROR;

2021-02-22 08:10 UTC, xinyigao requested changes
please modify :return -RT_ERROR;

2021-02-22 14:26 UTC, LeeChunHei commented on bsp/imxrt/libraries/drivers/drv_pwm.c
> +        return RT_ERROR;
已修改

2021-02-22 14:26 UTC, LeeChunHei commented on bsp/imxrt/libraries/drivers/drv_pwm.c
> +            return RT_ERROR;
已修改

2021-02-22 14:35 UTC, LeeChunHei commented
> please modify :return -RT_ERROR;

已修改

2021-02-23 01:15 UTC, xinyigao11 approved these changes

2021-02-23 01:41 UTC, merged