[bsp][gd32103c-eval] Add internal rtc driver
RT-Thread/rt-thread pull request #4351
Opened 2021-02-18 10:24 UTC by iysheng

## 拉取/合并请求描述：(PR description)

[
添加 GD32103C 内置 RTC 驱动。
在 GD32103C-EVAL 板卡完成测试。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2021-02-20 05:12 UTC, iysheng commented
@Guozhanxin :hugs:  抽空帮我 review 下啊 :smile: ？

2021-02-20 05:35 UTC, mysterywolf requested changes

2021-02-20 05:35 UTC, mysterywolf commented on bsp/gd32103c-eval/drivers/drv_rtc.c
> +    t_tm = gmtime(&time_stamp);
gmtime是非线程安全函数 需要关调度保护一下 rt_critical_enter/exit

2021-02-20 05:38 UTC, BernardXiong commented on bsp/gd32103c-eval/drivers/drv_rtc.c
> +    t_tm = gmtime(&time_stamp);
对于复杂，未知的代码，不建议使用rt_critical_enter/exit，而是直接关中断的模式

2021-02-20 05:46 UTC, mysterywolf commented on bsp/gd32103c-eval/drivers/drv_rtc.c
> +    t_tm = gmtime(&time_stamp);
其他底层涉及到libc-time非线程安全函数都是采用的rt_critical_enter/exit，https://github.com/RT-Thread/rt-thread/blob/master/components/dfs/filesystems/elmfat/dfs_elm.c#L957

有些驱动对此有保护 有些没有保护，我打算重新摸牌一次，这个是否需要改成关中断？

2021-02-20 05:51 UTC, BernardXiong commented on bsp/gd32103c-eval/drivers/drv_rtc.c
> +    t_tm = gmtime(&time_stamp);
后面这边来修改吧，会和SMP相关的一起修改

2021-02-20 05:54 UTC, mysterywolf commented on bsp/gd32103c-eval/drivers/drv_rtc.c
> +    t_tm = gmtime(&time_stamp);
@BernardXiong 收到。 @iysheng 请忽略此review

2021-02-20 06:03 UTC, iysheng commented on bsp/gd32103c-eval/drivers/drv_rtc.c
> +    t_tm = gmtime(&time_stamp);
@mysterywolf  :handshake:  我会删除这部分代码，我发现调用这个函数部分代码是一个不必要的检查。 :+1:

2021-03-09 02:01 UTC, balanceTWK commented
请解决下冲突。

然后截两个图挂在这个 issue 下，看一下 rtc 的时间准不准吧。（我这边没有对应的板子测。。。）

2021-03-09 04:19 UTC, iysheng commented
> 请解决下冲突。
> 
> 然后截两个图挂在这个 issue 下，看一下 rtc 的时间准不准吧。（我这边没有对应的板子测。。。）@iysheng

@balanceTWK  好的，:smile: 。已经解决冲突，截取了几张测试的图片：
校准之前误差 3S：
[![63CgEt.png](https://s3.ax1x.com/2021/03/09/63CgEt.png)](https://imgtu.com/i/63CgEt)

**date 命令**校准之后，考虑到截图的鼠标延迟和以及设置时间的误差，打印测试在 1s 中，reset 重启后可以正常保存时间：
[![63C4gg.png](https://s3.ax1x.com/2021/03/09/63C4gg.png)](https://imgtu.com/i/63C4gg)

2021-03-09 05:31 UTC, balanceTWK approved these changes
感谢提交 PR

2021-03-09 05:44 UTC, iysheng commented
> 感谢提交 PR
@balanceTWK :handshake:  感谢大佬 review。

2021-03-09 12:59 UTC, merged