[Update] Sync from v4.0.3
RT-Thread/rt-thread pull request #4404
Opened 2021-03-01 02:22 UTC by KyleChenjh

## 拉取/合并请求描述：(PR description)

[
同步v4.0.3版本的代码到 lts3.1.x版本，并更新相关change_log说明。
已经使用 testcase 测试通过，并且该版本已经增加了ci 测试环境并测试通过.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2021-03-01 02:23 UTC, KyleChenjh commented
@Guozhanxin 该pr已经重新提交。

2021-03-01 07:14 UTC, BernardXiong requested changes
其他没什么问题，fatfs建议维持原版本。另外，lwIP v2.1.0也看看是否可以维持。

2021-03-01 07:14 UTC, BernardXiong commented on components/dfs/filesystems/elmfat/00readme.txt
> +FatFs Module Source Files R0.14
不建议更新fatfs

2021-03-01 08:53 UTC, KyleChenjh commented on components/dfs/filesystems/elmfat/00readme.txt
> +FatFs Module Source Files R0.14
好的，fatfs我再看一下。关于lwIP更新问题，有以下几点原因：
1. 我看官网有这句话：它说 2.1.2修复了两个重大bug，并 强烈建议 使用2.1.0的用户更新到2.1.2。
![image](https://user-images.githubusercontent.com/46474992/109472883-a7518300-7aad-11eb-988c-52aa9bdb2158.png)
2. lwIP v2.1.0本身也是一个新分支，也不太稳定，目前用到人也比较少。
3. 我们官方master已经移除了2.1.0版本的支持，暂不维护2.1.0版本了，所以后续统一维护2.1.2是否更合理？

所以考虑更新lwIP到v2.1.2，不知是否合适？

2021-03-01 10:24 UTC, BernardXiong commented on components/dfs/filesystems/elmfat/00readme.txt
> +FatFs Module Source Files R0.14
OK, so please upgrade lwIP to v2.1.2.

2021-03-01 15:55 UTC, mysterywolf commented on components/dfs/filesystems/elmfat/00readme.txt
> +FatFs Module Source Files R0.14
fatfs 0.12官方说中文显示有问题，但是0.14和0.12有一些api有变化，宏定义也有点变化 都加了FF前缀

2021-03-02 03:27 UTC, KyleChenjh commented
相关的 FatFs 版本已经回退到 R0.12a，lwIP 版本已经更新到 v2.1.2

2021-03-02 07:00 UTC, merged