[bsp][ab32vg1] Fix sizeof(time_t) no match with this chip
RT-Thread/rt-thread pull request #4483
Opened 2021-03-19 01:57 UTC by iysheng

## 拉取/合并请求描述：(PR description)

[
修复 sizeof(time_t) 和实际 AB32VG1 的寄存器不匹配问题
修复之前，测试 RTC 驱动
```
 \ | /
- RT -     Thread Operating System
 / | \     4.0.3 build Mar 19 2021
 2006 - 2021 Copyright by rt-thread team
Hello, world a
msh >date
found rtc sizeof time_t=8
111111 time_now=0x10
over found rtc
now=-1
xmsh >
```
修复之后，测试 RTC 驱动
```
 \ | /
- RT -     Thread Operating System
 / | \     4.0.3 build Mar 19 2021
 2006 - 2021 Copyright by rt-thread team
Hello, world a
msh >
msh >date
found rtc sizeof time_t=4
111111 time_now=0x60135001
over found rtc
now=1611878401
Fri Jan 29 00:00:01 2021
msh >
```
在 AB32VG1 板子测试通过
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

2021-03-19 02:06 UTC, iysheng commented
@greedyhao  大佬，抽空帮我 review 下啊，使用我自己编译的工具链在 Linux 下测试 RTC 的时候，发现直接 date 命令会返回 -1， debug 时候发现，sizeof(time_t) = 8，正常寄存器是 4 个字节的，通过查看工具链的头文件，发现添加这个宏可以强制修改 time_t 为 long 型。具体的在文件 ```riscv64-unknown-elf/include/sys/types.h``` :smile:
```
 #if defined(_USE_LONG_TIME_T) || __LONG_MAX__ > 0x7fffffffL
 #define _TIME_T_ long
 #else
 #define _TIME_T_ __int_least64_t
 #endif
 typedef _TIME_T_ __time_t;
```

2021-03-19 06:02 UTC, greedyhao requested changes

2021-03-19 06:02 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
> +    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
这里不需要改吧，这里是设置 32K

2021-03-19 06:24 UTC, iysheng commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
> +    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
@greedyhao  我看原理图外接的是 32.768K 的晶振。
[![6Wljx0.png](https://s4.ax1x.com/2021/03/19/6Wljx0.png)](https://imgtu.com/i/6Wljx0)
看对应的寄存器描述：
[![6W1AR1.png](https://s4.ax1x.com/2021/03/19/6W1AR1.png)](https://imgtu.com/i/6W1AR1)
所以我将这里修改为清零 CON2 寄存器的 BIT(7) 了。
针对这个疑问，我在论坛也提交了一个问题呢？[没有对应的 32.768K 的波形](https://club.rt-thread.org/ask/question/430444.html)

2021-03-19 06:27 UTC, iysheng commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
>          temp &= ~BIT(7);
@greedyhao 好的。 :ok_hand:

2021-03-19 06:50 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
>      temp |= RTC_CON0_EXTERNAL_32K;
这个宏得改成 RTC_CON0_INTERNAL_32K

2021-03-19 06:52 UTC, greedyhao commented
使能外部晶振的代码如下
```
    temp |= RTC_CON0_XOSC32K_ENABLE;
    temp &= ~RTC_CON0_EXTERNAL_32K;
    irtc_sfr_write(RTCCON0_CMD, temp);
    temp = irtc_sfr_read(RTCCON2_CMD);
    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
```
要不做个配置的选项进行选择？

2021-03-19 07:13 UTC, iysheng commented
> 使能外部晶振的代码如下
> 
> ```
>     temp |= RTC_CON0_XOSC32K_ENABLE;
>     temp &= ~BIT(6);
>     irtc_sfr_write(RTCCON0_CMD, temp);
>     temp = irtc_sfr_read(RTCCON2_CMD);
>     irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
> ```
> 
> 要不做个配置的选项进行选择？

可以啊，待会我改下，大佬抽空再帮我 review 下。:smile:

2021-03-23 03:03 UTC, iysheng commented
@greedyhao 大佬，根据我这边的测试，发现
[![6TWvZ9.png](https://z3.ax1x.com/2021/03/23/6TWvZ9.png)](https://imgtu.com/i/6TWvZ9)
### ```X32KEN``` 这个 bit 的确是控制外部晶振是否起振的。
![](https://ftp.bmp.ovh/imgs/2021/03/756736246421fde9.png)
### ```EXT32KS``` 这个 bit 文档描述和代码中都反了。
相关修改内容，我已经再次迭代提交了，修改主要三部分：
* 添加宏 ···_USE_LONG_TIME_··· 保证 time_t 的 size 匹配 ab32vg1
* 修改对是否首次上电的判断，仅在首次上电时重新配置 RTC 的时钟
* 添加 Kconfig 的配置选项，支持选择使用内部晶振还是外部晶振
---
希望大佬抽空再帮我 review 下 😃

2021-03-23 03:10 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
> +    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
这部分改成这样会不会好一点，因为这部分配置是一个整体
```
#if RTC_USING_INTERNAL_CLK
    temp &= ~RTC_CON0_XOSC32K_ENABLE;
    temp |= RTC_CON0_EXTERNAL_32K;
    irtc_sfr_write(RTCCON0_CMD, temp);
    temp = irtc_sfr_read(RTCCON2_CMD);
    irtc_sfr_write(RTCCON2_CMD, temp | RTC_CON2_32K_SELECT);
#else
....
#endif
```

2021-03-23 03:35 UTC, iysheng commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
> +    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
> 
> 
> 这部分改成这样会不会好一点，因为这部分配置是一个整体
> 
> ```
> #if RTC_USING_INTERNAL_CLK
>     temp &= ~RTC_CON0_XOSC32K_ENABLE;
>     temp |= RTC_CON0_EXTERNAL_32K;
>     irtc_sfr_write(RTCCON0_CMD, temp);
>     temp = irtc_sfr_read(RTCCON2_CMD);
>     irtc_sfr_write(RTCCON2_CMD, temp | RTC_CON2_32K_SELECT);
> #else
> ....
> #endif
> ```
这样的话就会出现重复的
``` C
temp = irtc_sfr_read(RTCCON2_CMD);
irtc_sfr_write(RTCCON2_CMD, temp | RTC_CON2_32K_SELECT);
```
不是特别美观，我建议直接剥离这部分配置放到一个函数中，比如：
``` diff
diff --git a/bsp/bluetrum/libraries/hal_drivers/drv_rtc.c b/bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
index 7812d38f4..4f462e904 100644
--- a/bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
+++ b/bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
@@ -96,28 +96,33 @@ uint8_t irtc_sfr_read(uint32_t cmd)
     IRTC_EXIT_CRITICAL();
 }
 
-void hal_rtc_init(void)
+static void _init_rtc_clock(void)
 {
-    time_t sec = 0;
-    struct tm tm_new = {0};
+    uint8_t rtccon0;
+    uint8_t rtccon2;
 
-    uint8_t temp = irtc_sfr_read(RTCCON0_CMD);
+    rtccon0 = irtc_sfr_read(RTCCON0_CMD);
+    rtccon2 = irtc_sfr_read(RTCCON2_CMD);
 #ifdef RTC_USING_INTERNAL_CLK
-    temp &= ~RTC_CON0_XOSC32K_ENABLE;
-    temp |= RTC_CON0_INTERNAL_32K;
+    rtccon0 &= ~RTC_CON0_XOSC32K_ENABLE;
+    rtccon0 |= RTC_CON0_INTERNAL_32K;
+    rtccon2 | RTC_CON2_32K_SELECT;
 #else
-    temp |= RTC_CON0_XOSC32K_ENABLE;
-    temp &= ~RTC_CON0_INTERNAL_32K;
+    rtccon0 |= RTC_CON0_XOSC32K_ENABLE;
+    rtccon0 &= ~RTC_CON0_INTERNAL_32K;
+    rtccon2 & ~RTC_CON2_32K_SELECT;
 #endif
-    irtc_sfr_write(RTCCON0_CMD, temp);
-    temp = irtc_sfr_read(RTCCON2_CMD);
+    irtc_sfr_write(RTCCON0_CMD, rtccon0);
+    irtc_sfr_write(RTCCON2_CMD, rtccon2);
+}
 
-#ifdef RTC_USING_INTERNAL_CLK
-    irtc_sfr_write(RTCCON2_CMD, temp | RTC_CON2_32K_SELECT);
-#else
-    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
-#endif
+void hal_rtc_init(void)
+{
+    time_t sec = 0;
+    struct tm tm_new = {0};
+    uint8_t temp;
 
+    _init_rtc_clock();
     temp = irtc_sfr_read(RTCCON0_CMD);
     if (temp & RTC_CON0_PWRUP_FIRST) {
         temp &= ~RTC_CON0_PWRUP_FIRST;
@@ -129,7 +134,6 @@ void hal_rtc_init(void)
 
         irtc_time_write(RTCCNT_CMD, sec);
     }
-
 }
 /************** HAL End *******************/
 ```
你觉得是否合适呢？

2021-03-23 05:41 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
> +    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
可以

2021-03-23 05:51 UTC, greedyhao approved these changes

2021-03-23 05:52 UTC, iysheng commented on bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
> +    irtc_sfr_write(RTCCON2_CMD, temp & ~RTC_CON2_32K_SELECT);
@greedyhao  好的，已经提交. :grinning:

2021-03-23 12:10 UTC, merged