[Cortex-A]add gic&gtimer interface
RT-Thread/rt-thread pull request #4583
Opened 2021-04-08 07:48 UTC by fenghuijie

## 拉取/合并请求描述：(PR description)

[
add gic&gtimer interface
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-04-08 12:57 UTC, BernardXiong requested changes
Please follow the comments.

2021-04-08 12:57 UTC, BernardXiong commented on libcpu/arm/cortex-a/gic.c
> +#ifdef RT_USING_FINSH
It is not necessary to include this header file.

2021-04-08 12:57 UTC, BernardXiong commented on libcpu/arm/cortex-a/gic.c
> +    old_tgt &= ~(0x0FF << ((irq % 4)*8));
Are you sure, there is no warning?

2021-04-08 12:57 UTC, BernardXiong commented on libcpu/arm/cortex-a/gic.c
> +#ifdef RT_USING_FINSH
It's better to use msh command for debug and MSH_CMD_EXPORT will be defined as empty if not using finsh/msh. Therefore, we can remove the `#ifdef RT_USING_FINSH` condition.

2021-04-08 12:57 UTC, BernardXiong commented on libcpu/arm/cortex-a/interrupt.c
> +    return arm_gic_get_active_irq(0);
Are you sure to remove `GIC_ACK_INTID_MASK`?

2021-04-09 01:34 UTC, fenghuijie commented on libcpu/arm/cortex-a/interrupt.c
> +    return arm_gic_get_active_irq(0);
这个需要改，不然在多核下会影响核间中断响应

2021-04-09 07:46 UTC, merged