fix bluetrum uart1 and uart2 cannot recv data
RT-Thread/rt-thread pull request #4632
Opened 2021-04-23 02:30 UTC by yaoyufan

## 拉取/合并请求描述：(PR description)

[
解决了uart1、uart2无法接收数据的问题，修改了uart_irq_process函数
AB32VG1 RISC-V开发板 测试成功
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [*] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [*] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [*] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [*] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [*] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [*] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [*] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [*] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-04-23 02:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4632) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4632) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=4632) it.</sub>

2021-04-26 01:56 UTC, greedyhao requested changes

2021-04-26 01:56 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
这一段我觉得这样改比较好

```
rt_size_t rx_length;

/* get rx length */
level = rt_hw_interrupt_disable();
rx_length = (rx_fifo->put_index >= rx_fifo->get_index)? (rx_fifo->put_index - rx_fifo->get_index):
    (serial->config.bufsz - (rx_fifo->get_index - rx_fifo->put_index));
rt_hw_interrupt_enable(level);

if ((serial->parent.rx_indicate != RT_NULL) && (rx_length != 0)) {
#ifdef RT_CONSOLE_DEVICE_NAME
    if (serial == &uart_obj[finsh_uart_num].serial) {
        shell_rx_ind();
    } else
#endif
    {
        rt_kprintf("rx_indicate must loacted in the .comm section!\n");
        // serial->parent.rx_indicate(&serial->parent, rx_length);
    }
}
```

`finsh_uart_num` 这个变量可以在文件开头的地方定义

```
#ifdef RT_CONSOLE_DEVICE_NAME
static int finsh_uart_num = *(RT_CONSOLE_DEVICE_NAME + 4) - '0';
#endif
```

2021-04-26 01:58 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
默认先不处理其他串口的 rx_indicate 吧，免得中断里面调用了 flash 的函数

2021-04-26 04:40 UTC, yaoyufan commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
嗯，我也暂时不用串口接收了

2021-04-27 02:34 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
那你改一下吧，直接在这个分支提交一下

2021-04-27 02:47 UTC, yaoyufan commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
> 那你改一下吧，直接在这个分支提交一下
好的

2021-04-27 03:20 UTC, yaoyufan commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
修改了一下，finsh_uart_num 不能放在开头会提示initializer element is not constant，我的想法就是直接修改成下面的样子，就不用finsh_uart_num 

     if ((serial->parent.rx_indicate != RT_NULL) && (rx_length != 0)) {
    #ifdef RT_CONSOLE_DEVICE_NAME
        if (serial == &uart_obj[*(RT_CONSOLE_DEVICE_NAME + 4) - '0'].serial) {
            shell_rx_ind();
        } else
    #endif
        {
            rt_kprintf("rx_indicate must loacted in the .comm section!\n");
            // serial->parent.rx_indicate(&serial->parent, rx_length);
        }
    }

2021-04-27 11:46 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
那这样的话，每次都要重新计算，不划算
给 **finsh_uart_num** 前面加上 const 不行吗

2021-04-27 11:53 UTC, yaoyufan commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
> > 修改了一下，finsh_uart_num 不能放在开头会提示initializer element is not constant，我的想法就是直接修改成下面的样子，就不用finsh_uart_num
> > ```
> >  if ((serial->parent.rx_indicate != RT_NULL) && (rx_length != 0)) {
> > #ifdef RT_CONSOLE_DEVICE_NAME
> >     if (serial == &uart_obj[*(RT_CONSOLE_DEVICE_NAME + 4) - '0'].serial) {
> >         shell_rx_ind();
> >     } else
> > #endif
> >     {
> >         rt_kprintf("rx_indicate must loacted in the .comm section!\n");
> >         // serial->parent.rx_indicate(&serial->parent, rx_length);
> >     }
> > }
> > ```
> 
> 那这样的话，每次都要重新计算，不划算
> 给 **finsh_uart_num** 前面加上 const 不行吗
> 
> ```
> #ifdef RT_CONSOLE_DEVICE_NAME
> static const int finsh_uart_num = *(RT_CONSOLE_DEVICE_NAME + 4) - '0';
> #endif
> ```

不行，还是会提示那个问题，初始化值必须是常量

2021-04-28 00:53 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
那就按你说的改吧，似乎是带了指针，就没办法在一开始就计算好了

2021-04-28 01:14 UTC, yaoyufan commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
好的

2021-04-28 01:31 UTC, greedyhao commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
有测试过吗

2021-04-28 01:34 UTC, yaoyufan commented on bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> +
测试过了，uart0没问题，其他两个会问题，就默认不开启了

2021-04-28 02:10 UTC, greedyhao approved these changes

2021-05-03 13:55 UTC, merged