ft2000/4 开发板BSP完成提交
RT-Thread/rt-thread pull request #4713
Opened 2021-05-21 10:49 UTC by ssd4561

## 拉取/合并请求描述：(PR description)

[飞腾技术ft2000/4 开发板BSP,添加 UART,SPI FLASH,SD,CAN,GMAC等外设，并且支持GIC v3 与 SMP，已在ft2000/4 开发板测试通过。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-05-21 13:36 UTC, mysterywolf commented
https://github.com/mysterywolf/formatting 扫描一下就好了

2021-05-21 15:01 UTC, BernardXiong requested changes

2021-05-21 15:01 UTC, BernardXiong commented on bsp/ft2004/rtconfig.py
> +# header = '''
auto mac是为qemu-vexpress-a9准备的，请移除无效代码。

2021-05-21 15:22 UTC, ssd4561 commented on bsp/ft2004/drivers/secondary_cpu.cold
> +/*
此文件不需要，稍后将会删除。

2021-05-21 15:22 UTC, ssd4561 commented on bsp/ft2004/libraries/drivers/rtthread/drv_usart.c
> +    struct serial_configure config;
目前开发板上只有一个串口，作为终端使用（115200-8-1-N），所以没有响应外部接口的配置，后续提交将会将会加上对于这部分的配置参数的响应。

2021-05-21 15:26 UTC, ssd4561 commented on bsp/ft2004/rtconfig.py
> +# header = '''
下次提交中修改

2021-05-21 15:37 UTC, ssd4561 commented on bsp/ft2004/README.md
> +- FT-2000／4 软件编程手册-V1.4
谢谢您的建议，晚些时候会进行补充

2021-05-21 15:44 UTC, ssd4561 commented on bsp/ft2004/libraries/LICENSE
> +
谢谢您的提醒，我们下周将开会讨论这个问题如何修改

2021-05-22 03:57 UTC, BernardXiong commented on bsp/ft2004/libraries/LICENSE
> +
OK，那这个等你们给出具体结论后再考虑后续合并的事情。

2021-05-25 02:33 UTC, zhouji92 commented
不使用的代码不用提交，提交邮箱检查下，避免cla过不了。

2021-05-26 09:29 UTC, ssd4561 reviewed
@BernardXiong，已经按照要求进行修改，请您再次检查一下。

2021-05-27 09:06 UTC, merged