[kernel] rtthread.h 增加#ifdef RT_USING_HEAP 预编译
RT-Thread/rt-thread pull request #4742
Opened 2021-05-28 14:47 UTC by mysterywolf

## 拉取/合并请求描述：(PR description)

[

]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-05-29 07:37 UTC, BernardXiong requested changes

2021-05-29 07:37 UTC, BernardXiong commented on include/rtthread.h
> +void rt_thread_exit(void);
这个api没必要露出

2021-05-29 07:37 UTC, BernardXiong commented on include/rtthread.h
> +#ifdef RT_USING_HEAP
这些更多的是针对声明，有声明而未有实现，会在最终链接时报错。

2021-05-29 08:38 UTC, mysterywolf commented on include/rtthread.h
> +void rt_thread_exit(void);
revert 回来了

2021-06-28 12:25 UTC, BernardXiong commented
先不考虑吧，等到完善注释时，看看是否加入这块的考虑。

2021-09-27 06:19 UTC, mysterywolf commented
注释完善的差不多喽

2021-09-28 02:20 UTC, Guozhanxin commented
加上之后，看起来更清楚了点。

2021-09-28 14:42 UTC, merged