[kernel][heap] Protect critical area with mutex
RT-Thread/rt-thread pull request #4783
Opened 2021-06-10 07:22 UTC by enkiller

## 拉取/合并请求描述：(PR description)

[
## 背景

内存管理内部使用信号量保护临界区，不是很好，无法防止优先级反转问题。

## 修改方案

将内存管理内部锁更换成互斥锁

## 修改内容

1. 将 sem 更换成 mutex
2. rt_thread_self() 为 RT_NULL 时，不钳锁

]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-06-10 08:35 UTC, mysterywolf requested changes

2021-06-10 08:35 UTC, mysterywolf commented on src/mem.c
> +
不能直接以是否调度器启动作为上锁依据，不排除这种情况：当上锁的时候调度器还没启动，因此没有上锁，但是解锁的时候调度器启动了，因此运行了rt_mutex_release。相当于没有执行rt_mutex_take直接执行了rt_mutex_release。可能还得设计一个标志位来避免这种情况的发生。

2021-06-10 09:42 UTC, mysterywolf approved these changes

2021-06-10 11:01 UTC, mysterywolf commented
请无视大红×，CI机器人下载东西下载失败了

2021-06-10 11:57 UTC, enkiller commented
> 请无视大红×，CI机器人下载东西下载失败了

2021-06-10 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4783) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=4783) before we can accept your contribution.<br/><hr/>**tangyuxin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=4783) it.</sub>

2021-06-10 14:06 UTC, BernardXiong commented
加入一种情况：

如果未使能mutex，可以使用sem的方式来简单处理。

2021-06-10 14:19 UTC, mysterywolf commented
可以再加一种情况，在连sem都没有开启的情况下，直接通过关调度器保护。

2021-06-11 03:07 UTC, mysterywolf commented on src/mem.c
> +#endif
三份相同的代码极容易出现后续维护的时候顾头不顾腚的问题，只改其中一个，剩下两份没有改，是否应该把这些宏函数抽出来，放在rtdef.h里？ @Guozhanxin

2021-06-11 05:08 UTC, mysterywolf commented on src/mem.c
> +#endif
或者提供这一组自动适应的lock函数？放在ipc里边，可以直接暴露给用户的？

2021-06-11 09:04 UTC, Guozhanxin commented on src/mem.c
> +#endif
我是感觉这种写法太方了

2021-06-11 09:07 UTC, Guozhanxin commented on src/mem.c
> +#endif
或者如果感觉内存的临界区保护用 mutex 比较好，是不是直接开启动态内存的时候 select mutex 就好了😂

2021-06-11 10:38 UTC, mysterywolf commented on src/mem.c
> +#endif
我觉得也是 如果追求代码精简的话，直接关调度器就可以了。使用信号量会造成无界优先级反转，WCET无法预计。

2021-06-13 06:29 UTC, enkiller commented on src/mem.c
> +#endif
关调度影响实时性，高优先级任务就绪了，无法调度

2021-06-13 06:54 UTC, mysterywolf commented on src/mem.c
> +#endif
关掉度是有界优先级反转，使用sem是无界优先级反转，有界优先级反转WCET可以预测，无界优先级反转WCET不能预测。有界优先级反转是可以容忍的，无界优先级反转是实时系统无法容忍的。

2021-06-15 09:46 UTC, enkiller commented on src/mem.c
> +#endif
@Guozhanxin 自动 select mutex ？然后解决问题?

2021-06-15 10:53 UTC, Guozhanxin commented on src/mem.c
> +#endif
![image](https://user-images.githubusercontent.com/25633294/122040947-ff1cbb80-ce0a-11eb-9000-4fda03b3506e.png)
这个有啥想法吗

2021-06-15 11:23 UTC, enkiller commented on src/mem.c
> +#endif
放 rtdef.h 更别扭，mem.c 与 memheap.c 中的定义还不一样。而且这个也不是对外的公共通用代码。

2021-06-15 12:57 UTC, mysterywolf commented on src/mem.c
> +#endif
建议用mutex和关中断保护，不要使用sem。

2021-06-16 02:00 UTC, Guozhanxin commented
或者我们把各个内存算法里的api名字改一下，不直接实现 rt_malloc/rt_free 这两个接口，而是实现 rt_malloc_r ? 再在 https://github.com/RT-Thread/rt-thread/blob/master/src/kservice.c 单独定义 rt_malloc/rt_free 专门处理多线程保护，然后由这个函数再调用各个内存算法的非线程安全实现？这个改动就比较大了，但是多线程保护的部分就统一了，也方便做些内存的统计和检查。。。

2021-06-16 02:07 UTC, enkiller commented on src/mem.c
> +#endif
内存管理中涉及到链表查询，可能导致关中断时间过长。直接使用 mutex 进行保护吧。打开了 heap 功能，就自动把 mutex 选择上。这样子是最好的。

2021-06-16 02:11 UTC, mysterywolf commented
好方法！

2021-06-16 02:18 UTC, enkiller commented
1. 重命名各个内存管理算法 API 名字。rt_mem_alloc, rt_memheap_alloc, rt_slab_alloc
2. rt_malloc/rt_free 及 rt_system_heap_init 放到 kservice.c  中实现
3. mem 及 slab 能够多实例化

@Guozhanxin  @mysterywolf @BernardXiong

2021-06-18 14:04 UTC, Guozhanxin commented
> 1. 重命名各个内存管理算法 API 名字。rt_mem_alloc, rt_memheap_alloc, rt_slab_alloc
> 2. rt_malloc/rt_free 及 rt_system_heap_init 放到 kservice.c  中实现
> 3. mem 及 slab 能够多实例化
> 
> @Guozhanxin @mysterywolf @BernardXiong

期待炸弹哥的手艺

2021-06-19 02:35 UTC, enkiller commented
这个样子改动也会有一个问题，`rt_memheap_alloc` 目前是线程安全的，将加锁抽出来后，会改变函数行为，这肯定是不行的。

2021-06-21 10:34 UTC, closed without merging