update board.c in k210 bsp
RT-Thread/rt-thread pull request #4786
Opened 2021-06-10 10:45 UTC by chunyexixiaoyu

…e ,rt_hw_us_delay this function will be called in unistd.c file

## 拉取/合并请求描述：(PR description)

[
add void rt_hw_us_delay(rt_uint32_t usec) funciton in board.c ，the function will delay for some us ,the function can be called in usleep in unistd.c when using POSIX interface

It has been verified in KD233 development board.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-06-10 10:59 UTC, mysterywolf reviewed
implement rt_hw_us_delay

2021-06-10 10:59 UTC, mysterywolf commented on bsp/k210/driver/board.c
> + *2021-06-10      xiaoyu       add the function that will delay for some us ,the function can be called in usleep in unistd.c when using POSIX interface
implement rt_hw_us_delay() 即可

2021-06-10 11:21 UTC, mysterywolf commented on bsp/k210/driver/board.c
> +}
最后一行加一个回车

2021-06-10 11:23 UTC, chunyexixiaoyu commented on bsp/k210/driver/board.c
> +}
谢谢我试下

2021-06-10 11:23 UTC, mysterywolf commented on bsp/k210/driver/board.c
> +}
https://github.com/mysterywolf/formatting

2021-06-10 11:25 UTC, mysterywolf commented on bsp/k210/driver/board.c
> +}
第8行 末尾多了一个空格

2021-06-10 11:31 UTC, mysterywolf commented
顺便请确认一下是否存在这个问题：https://github.com/RT-Thread/rt-thread/issues/4775

2021-06-10 14:16 UTC, mysterywolf requested changes

2021-06-10 14:16 UTC, mysterywolf commented on bsp/k210/driver/board.c
> +                break;
此处缩进不对

2021-06-10 14:18 UTC, mysterywolf requested changes

2021-06-10 14:18 UTC, mysterywolf commented on bsp/k210/driver/board.c
> +    return;
没有必要加return

2021-06-11 03:00 UTC, mysterywolf approved these changes

2021-06-12 11:24 UTC, merged