Add RTC new framework V2.0 to unify and simplify the registration process
RT-Thread/rt-thread pull request #4798
Opened 2021-06-15 15:00 UTC by iysheng

## 拉取/合并请求描述：(PR description)

[
1. 添加 RTC 驱动框架 V2.0,统一并简化 RTC 设备的注册流程
2. 同步修改 STM32 的 RTC 驱动以适应 RTC 驱动框架 V2.0

1. STM32F103RCT6 板卡测试通过
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-06-15 16:38 UTC, mysterywolf requested changes
改都在github上改，最后再搬回到gitee，参加gitee的活动。github的CI机器人比gitee完善。

2021-06-15 16:38 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +    rt_kprintf("Cannot find a RTC device to provide time!\r\n");
这个地方用LOG_W输出
`LOG_W("Cannot find a RTC device to provide time!");` 
注意再不需要加\r\n了

2021-06-15 16:38 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +    rt_kprintf("Cannot find a RTC device to save time!\r\n");
这个地方用LOG_W输出
`LOG_W("Cannot find a RTC device to provide time!");` 
注意再不需要加\r\n了

2021-06-15 16:41 UTC, mysterywolf commented
这个pr审核时间会比较长，改的此处可能比较多，我们还得开会讨论一下函数的命名方面的问题，请耐心等待。

2021-06-15 16:49 UTC, mysterywolf commented
待探讨内容 @Guozhanxin : https://github.com/RT-Thread/rt-thread/pull/4549

2021-06-15 16:50 UTC, iysheng commented
> 这个pr审核时间会比较长，改的次数可能比较多，我们还得开会讨论一下函数的命名方面的问题，请耐心等待。
:ok:

2021-06-15 16:58 UTC, iysheng commented on components/libc/compilers/common/time.c
> +    rt_kprintf("Cannot find a RTC device to save time!\r\n");
以修改并重新提交. :smile:

2021-06-16 01:38 UTC, BernardXiong commented
这个是为了解决什么问题提出的？有设计文档或思路吗？

2021-06-16 01:46 UTC, mysterywolf commented
由于历史原因，目前RT-Thread使用的RTC驱动框架，并没有实际起到驱动框架的作用 - 即隔离底层驱动，抽象设备的功能。导致用户在调用RTC设备相关操作时，直接越过了RTC驱动框架，直接调用的底层驱动的程序。此外，在底层驱动中，框架功能和驱动功能相互交织在一起，没有剥离。因此应当予以重新实现该框架。

2021-06-16 03:51 UTC, iysheng commented
> 这个是为了解决什么问题提出的？有设计文档或思路吗？

熊大，请问是否需要我提供设计思路的文档说明？

2021-06-16 04:40 UTC, mysterywolf commented
暂时先别写，等讨论的差不多了，如果有需要再写，要不还得改来改去

2021-06-16 05:39 UTC, armink commented
> 添加 RTC 驱动框架 V2.0,统一并简化 RTC 设备的注册流程

这方面是否有些介绍说明，有哪些改动？是否兼容？哪些不兼容？

2021-06-16 05:40 UTC, iysheng commented
> 暂时先别写，等讨论的差不多了，如果有需要再写，要不还得改来改去
好的.

2021-06-16 09:14 UTC, iysheng commented
> > 添加 RTC 驱动框架 V2.0,统一并简化 RTC 设备的注册流程
> 
> 这方面是否有些介绍说明，有哪些改动？是否兼容？哪些不兼容？

1. 之前的 RTC 驱动注册的时候还是在 rt_device_t 这个设备层级直接注册到系统,我做的改动是在这一层级之上封装了一层 **rtc_core** ,在 ``rtc_core`` 层对 rt_device 进一步``继承``,具体的 rt_rtc_dev_t 设备类型: 
```C
struct rt_rtc_ops
{
    rt_err_t (*init)(void);
    rt_err_t (*get_secs)(void *arg);
    rt_err_t (*set_secs)(void *arg);
    rt_err_t (*get_alarm)(void *arg);
    rt_err_t (*set_alarm)(void *arg);
};

typedef struct rt_rtc_device
{
    struct rt_device parent;
    const struct rt_rtc_ops *ops;
} rt_rtc_dev_t;
```
通过将对 RTC 设备常用的操作 ``get_secs/set_secs/get_alarm/set_alarm `` 提取出来,以后在注册 RTC 设备的时候,可以重点关注这四个方法的实现,而不用去填充对应 ``RTC 设备在 rt_device_t 这一层的 control`` 函数,这一部分内容的实现因为都是**比较重复的**所以放在 ``rtc_code`` 层完成.
2. 目前兼容性是,从理论上来说这个新的框架并不具有排他性,和之前的 RTC 框架可以并存,实际在提交 CI 编译的时候出现了部分平台编译不过的现象,具体原因,考虑到已经提取出了 rtc_core 层,所以我将对应的 control 函数中的命令的宏
```C
#define RT_DEVICE_CTRL_RTC_GET_TIME     0x10            /**< get second time */
#define RT_DEVICE_CTRL_RTC_SET_TIME     0x11            /**< set second time */
#define RT_DEVICE_CTRL_RTC_GET_TIME_US  0x12            /**< get microsecond time */
#define RT_DEVICE_CTRL_RTC_SET_TIME_US  0x13            /**< set microsecond time */
#define RT_DEVICE_CTRL_RTC_GET_ALARM    0x14            /**< get alarm */
#define RT_DEVICE_CTRL_RTC_SET_ALARM    0x15            /**< set alarm */
```
从 ``rtdef.h`` 头文件提取到了 ``rtc_core.h``.
因为宏定义位置的改变导致部分文件编译的时候没有通过.原因就是缺少对 rtc_code.h 的引用(涉及到平台有:efm32和s3c24x0),通过在这两个平台 RTC 驱动的源文件中添加对 ``rtc_code.h`` 头文件的引用 **#include <drivers/rtc_core.h>** 修复编译错误.**特别地**,对 time.c 编译不成功的现象,原因是在函数 ``static int clock_time_system_init()`` 和 ``int clock_settime(clockid_t clockid, const struct timespec *tp)`` 执行过程中缺少了对宏 RT_USING_RTC 的判断,对应的在 time.c 文件中添加了如下内容:
```C
#ifdef RT_USING_RTC
#include <drivers/rtc_core.h>
#endif
```

2021-07-01 13:38 UTC, mysterywolf approved these changes
结构上没有问题，请 @whj4674672  验证一下功能性

2021-07-02 04:16 UTC, BernardXiong commented on components/libc/compilers/common/time.c
> +#include <drivers/rtc_core.h>
之前的模式是，

当要在devicedrivers中增加一些功能，头文件时，会在rtdevice.h中
```c
#ifdef RT_USING_DEVICE_NNN
#include "drivers/nnn.h"
#endif
```

这样类似的模式。这样的好处是，关心的可以只是rtdevice.h头文件，包含它即可获得相关的定义，声明。同时以`#include "xxx.h"`模式来包含，也让编译器直接去rtdevice.h的当前路径去查找。当然，缺陷是有些没那么清晰。

2021-07-02 06:36 UTC, iysheng commented on components/libc/compilers/common/time.c
> +#include <drivers/rtc_core.h>
已修改对应的 3 个文件:
1. 分别删除 time.c 冗余的`` #include <drivers/rtc_core.h> ``
2. 修改在 efm32 和 s3c24x0 的 rtc 驱动添加使用 rtdevice.h 引用替换直接引用`` #include <drivers/rtc_core.h> ``
3. 已修改 stm32 drv_rtc.c 驱动文件函数部分函数命令不规范的问题,取消部分 rt 开头的函数命令,使用 stm32 替换 @mysterywolf

2021-07-03 10:15 UTC, KyleChenjh commented
@iysheng  你好，我在STM32L4上进行了简单的测试，大体功能是可以用的，但是有以下一些问题需要讨论下：
1.  [在 `drv_rtc.c` 文件中](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L29)，有定义未使用的变量 `static struct rt_device rtc;` 这个应该修掉吧。
2.  [在 `drv_rtc.c` 文件中](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L276-L279)，`static rt_rtc_dev_t stm32_rtc_dev` 的结构体赋值不符合c标准导致编译失败，我开了GNU Extensions才编译通过。
3. [在 `rtc_core.c` 文件中](https://github.com/iysheng/rt-thread/blob/master/components/drivers/rtc/rtc_core.c#L38-L45)，在 `rt_rtc_core_close` 函数中也有未使用变量 `rtc_core`
4. 上次讨论的RTC命名规范中，对驱动初始化的函数名应该不是 `stm32_hw_rtc_init `这个名字吧？我记得应该是 `rt_hw_xx_init`这种的？

2021-07-04 08:13 UTC, iysheng commented
> @iysheng 你好，我在STM32L4上进行了简单的测试，大体功能是可以用的，但是有以下一些问题需要讨论下：
> 
>     1. [在 `drv_rtc.c` 文件中](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L29)，有定义未使用的变量 `static struct rt_device rtc;` 这个应该修掉吧。
> 
>     2. [在 `drv_rtc.c` 文件中](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L276-L279)，`static rt_rtc_dev_t stm32_rtc_dev` 的结构体赋值不符合c标准导致编译失败，我开了GNU Extensions才编译通过。
> 
>     3. [在 `rtc_core.c` 文件中](https://github.com/iysheng/rt-thread/blob/master/components/drivers/rtc/rtc_core.c#L38-L45)，在 `rt_rtc_core_close` 函数中也有未使用变量 `rtc_core`
> 
>     4. 上次讨论的RTC命名规范中，对驱动初始化的函数名应该不是 `stm32_hw_rtc_init `这个名字吧？我记得应该是 `rt_hw_xx_init`这种的？

@KyleChenjh  感谢你的仔细检查,已经修复这几个问题,并重新提交. :handshake:

2021-07-05 02:11 UTC, Guozhanxin commented
我感觉没啥问题了，同步到码云上吧

2021-07-05 02:12 UTC, Guozhanxin commented
我感觉没啥问题了，同步到码云上吧

2021-07-05 02:22 UTC, KyleChenjh commented
还有问题。我发现有两个API名字不对。
[get_sec](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L244-L250)和[set_sec](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L252-L263) 命名应该是secs而不是sesc的吧？

2021-07-05 02:54 UTC, iysheng commented
> 还有问题。我发现有两个API名字不对。
> [get_sec](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L244-L250)和[set_sec](https://github.com/iysheng/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c#L252-L263) 命名应该是secs而不是sesc的吧？
已经修改并重新提交.:relieved:

2021-07-08 18:43 UTC, mysterywolf commented
专由gitee提交 https://gitee.com/rtthread/rt-thread/pulls/253/files

2021-07-08 18:43 UTC, closed without merging