[add] the support of lwip 2.0.3.
RT-Thread/rt-thread pull request #4824
Opened 2021-06-25 08:01 UTC by xiangxistu

## 拉取/合并请求描述：(PR description)

[
 * according the issue, add lwip 2.0.3.
 * have tested on the stm32f407-atk.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-06-25 11:56 UTC, mysterywolf requested changes

2021-06-25 11:56 UTC, mysterywolf commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
可否删除这句话，在Kconfig里边有默认的LWIP选项，否则两个地方设置容易出问题。 顺便请把 Kconfig的默认版本改为2.0.3，2.0.3是最稳定的版本。 https://github.com/RT-Thread/rt-thread/pull/4824/files#diff-f5526c1e9c0e1c6a119a49aaa7df4f015645095cc11d93f989aee74d89b60b5cL117

2021-06-25 11:56 UTC, mysterywolf commented on components/net/lwip-2.0.3/src/arch/include/arch/cc.h
> +//#define SYS_ARCH_UNPROTECT(level)   rt_exit_critical()
请删除无用代码

2021-06-25 15:04 UTC, mysterywolf commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
这个AddDepend和Kconfig里边的默认选项是一个意思吗？

2021-06-28 03:34 UTC, xiangxistu commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
我也感觉这句话没有起到应有的作用，那就把默认的版本改为 lwip2.0.3 了；
我这里逻辑调整一下。

2021-06-28 03:34 UTC, xiangxistu commented on components/net/lwip-2.0.3/src/arch/include/arch/cc.h
> +//#define SYS_ARCH_UNPROTECT(level)   rt_exit_critical()
好的

2021-06-28 04:00 UTC, xiangxistu commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
啊，不太行；貌似有些 BSP 仓库已经很久没有更新了；里面的 ```rtconfig.h``` 文件基本和现在的自动化配置出来的格式不太符合。

这段脚本还是添上吧，我把注释该得明确些。

2021-06-28 04:17 UTC, mysterywolf commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
如果是因为rtconfig无法自动化配置的原因而导致报错，我觉得先等一下，先把rtconfig.h处理一下再说，这个玩意迟早是个问题，拖后腿。

2021-06-28 04:18 UTC, mysterywolf commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
我先看看处理一下rtconfig.h

2021-06-28 04:48 UTC, xiangxistu commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
我感觉，可以另开一个 PR 解决这个问题；

在一些旧的 BSP 中，rtconfig.h 不是自动生成的。里面只定义了 RT_USING_LWIP 而没有定义，RT_LWIP_X.X.X 之类的，所以会在脚本里特意添加一个默认的宏。

2021-06-28 04:48 UTC, mysterywolf commented on components/net/SConscript
>      AddDepend('RT_USING_LWIP202')
好的

2021-06-28 04:49 UTC, mysterywolf approved these changes

2021-06-28 05:32 UTC, merged