优化memheap内存管理：1.自动多块粘合可配置；2.支持自动搜寻更小块以减少碎片.
RT-Thread/rt-thread pull request #4872
Opened 2021-07-14 14:58 UTC by aozima

## 拉取/合并请求描述：(PR description)

[
1. memheap版本的rt_malloc实现中，当主内存堆heap无法分配内存时，之前会自动从其它块分配。现增加一个开关，默认建议关闭，以禁用这种特性，确保分配出来的内存特性可控。
2. 分配内存时，当找可用free内存时，继续搜索以期找到更小块；
2.1 当目标可能不是最小，但已经够小时时，可以提前结束搜索。此差值可通过 RT_MEMHEAP_COMPACT_SIZE 配置
2.2 当继续搜索次数足够多时，也可以提前结束搜索，以避免相对原来降低性能。搜索深度可以通 RT_MEMHEAP_COMPACT_STEP 配置。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-07-20 00:58 UTC, mysterywolf requested changes

2021-07-20 00:58 UTC, mysterywolf commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BONDING
此处应该用binding
![Screenshot_2021-07-20-08-53-43-148_com.android.browser.jpg](https://user-images.githubusercontent.com/34888354/126246285-765143c5-9550-4983-bec9-3c9612c854f5.jpg)

2021-07-20 13:35 UTC, aozima commented
@mysterywolf 大佬改好了！

2021-07-20 13:48 UTC, armink commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BINDING
RT_USING_MEMHEAP_AUTO_BINDING 这个宏默认是 N 。

如果老用户更新了代码，还必须要手动开启一下这个选项，才能保证代码的逻辑与以前版本的一致，会不会兼容性不太好？考虑更换一个反义的宏？

2021-07-20 13:53 UTC, mysterywolf commented
> @mysterywolf 大佬改好了！

熊大发现的 我只不过是个传话筒😂

2021-07-21 06:04 UTC, aozima commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BINDING
从风险上，为N其实更保险。

2021-09-09 02:16 UTC, Guozhanxin commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BINDING
TLSF 算法也是会默认从所有的内存块里分配内存。

2021-09-13 00:19 UTC, BernardXiong commented
这个PR， @armink @Guozhanxin 还请给出你们的意见，合并or不合并？

2021-09-13 00:28 UTC, armink commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BINDING
兼容性建议要考虑好

2021-09-13 01:10 UTC, Guozhanxin commented
> 这个PR， @armink @Guozhanxin 还请给出你们的意见，合并or不合并？

我的意见是默认自动合并也没啥不好，本来就写了会自动合并。所有希望能兼容之前的。

2021-09-18 02:14 UTC, aozima commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BINDING
已修改为 `default y`

2021-09-18 03:35 UTC, armink commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BINDING
deafult y 后还需要所有的 BSP 都刷一遍 menuconfig

2021-09-18 06:18 UTC, mysterywolf commented on src/memheap.c
> +#ifdef RT_USING_MEMHEAP_AUTO_BINDING
没事 本来libc改了之后也得把bsp都刷一遍

2021-09-19 22:15 UTC, Guozhanxin approved these changes

2021-09-27 06:16 UTC, merged