【修改】STM32F4探索者，移植 littlefs 文件系统
RT-Thread/rt-thread pull request #4919
Opened 2021-08-04 11:07 UTC by YJ98

## 拉取/合并请求描述：(PR description)

[
在 STM32F4探索者上移植 littlefs 文件系统
STM32F4探索者开发板 在 MDK5,RT-Thread Studio，Gcc 编译通过，测试正常
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-08-04 14:19 UTC, mysterywolf requested changes

2021-08-04 14:19 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/ports/drv_filesystem.c
> +#ifdef BSP_USING_NOR_MTD_FS
BSP_USING_SPI_FLASH_LITTLEFS

2021-08-04 14:19 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/ports/drv_filesystem.c
>  //  {ROMFS_DIRENT_DIR, "flash", RT_NULL, 0},
请删除这句话

2021-08-04 14:19 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/ports/drv_filesystem.c
> +    onboard_mtd_mount();
onboard_spiflash_mount

2021-08-04 14:19 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/ports/fal_cfg.h
>  }
对于探索者，littlefs只挂载板载spiflash，不挂载片内flash。spiflash的所有空间都分配给littlefs

2021-08-04 14:19 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/ports/dfs_romfs.h
> +
为什么这个要加一个.h文件暴露出来？

2021-08-04 14:19 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/SConscript
> +    src += Glob('ports/dfs_romfs.h')
Glob只能加c或者cpp 不能加.h 请确认dfs_romfs.h是否有存在的意义

2021-08-04 14:19 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/Kconfig
> +            select BSP_USING_ON_CHIP_FLASH
不需要开启片内flash，只有spi-flash挂载littlefs

2021-08-04 14:21 UTC, mysterywolf commented
```
代码质量 Code Quality：
我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

[ x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
[x ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
[x ] 没有垃圾代码，代码尽量精简，不包含#if 0代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
[x ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
[x ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
[x ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
[x ] 本拉取/合并符合RT-Thread代码规范 This PR complies with RT-Thread code specification
```

选项的时候要删除x左右多余的空格`[x]`

2021-08-05 01:09 UTC, Guozhanxin commented
> ```
> 代码质量 Code Quality：
> 我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:
> 
> [ x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
> [x ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
> [x ] 没有垃圾代码，代码尽量精简，不包含#if 0代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
> [x ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
> [x ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
> [x ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
> [x ] 本拉取/合并符合RT-Thread代码规范 This PR complies with RT-Thread code specification
> ```
> 
> 选项的时候要删除x左右多余的空格`[x]`

其实这几个提交的时候不用改，提交pr之后，在网页上点就行了。

2021-08-05 07:06 UTC, mysterywolf commented
如果已经解决的的对话，可以点击左下角的Resolve Conversation来隐藏对话框

2021-08-05 09:31 UTC, mysterywolf commented
https://github.com/mysterywolf/formatting ci报错的格式不合规的文件可以用这个脚本扫描一下

2021-08-05 12:02 UTC, mysterywolf commented
请确认这个pr是否可以编过？实际测试并不能编过貌似没有select FAL

2021-08-05 13:16 UTC, mysterywolf commented
https://github.com/mysterywolf/rt-thread/commit/963cce1e1bd6fbb7c4a2cf7c81812d9fca8d9a70
我已经解决没有选定FAL和littlefs软件包的问题，解决挂载顺序不合理的问题，重命名spiflash设备为spiflash0
但是FAL还有MTD NOR设备已经成功挂载，但是格式化盘符时会显示(sfud_dev) has assert failed at read. 麻烦你看看。

2021-08-06 03:19 UTC, YJ98 commented
自动格式化并挂载
![automatic_mount](https://user-images.githubusercontent.com/58252450/128450599-4cc12e48-e700-4dba-b502-12789826bf2c.png)

手动格式化并挂载
![manual_operation](https://user-images.githubusercontent.com/58252450/128450604-8ad41d35-51d3-4fbd-87c3-3dac9ceadf6b.png)

我测试了一下，没有出现格式化时显示 (sfud_dev) has assert failed at read. ，麻烦您看看，是否是我的操作有什么遗漏。@mysterywolf

2021-08-06 05:51 UTC, mysterywolf commented
你的mtd_test是个什么东东

2021-08-06 05:52 UTC, mysterywolf commented
我初始化的时候没有敲入mtd_test的步骤，直接上来就自动初始化。

2021-08-06 06:34 UTC, YJ98 commented
我那个是我导出的测试用例，不使用自动初始化，等系统起来后，一步一步操作，看是否能复现您出现的那个问题。

2021-08-06 06:47 UTC, YJ98 commented
![change_name](https://user-images.githubusercontent.com/58252450/128468068-51c2a194-7a5f-4982-8bda-d596be73eee0.png)
您出现的那个问题，应该是没有修改这个名字，使用的是默认的 norflash0,而我们使用的是 W25Q128 。

2021-08-06 07:05 UTC, mysterywolf commented
是的 改成w25q128就好了，我一会再给你的仓库提一个pr

2021-08-06 07:17 UTC, mysterywolf commented
https://github.com/YJ98/rt-thread/pull/2 请合并这个pr，我已经测试通过了

2021-08-06 07:22 UTC, mysterywolf approved these changes
已经在STM32F407探索者测试通过，littlefs文件系统挂载正常

2021-08-06 17:17 UTC, mysterywolf commented
麻烦合并一下 https://github.com/YJ98/rt-thread/pull/3   优化FAL相关设置

2021-08-08 12:19 UTC, merged

2021-08-08 12:21 UTC, Guozhanxin commented
好像合并早了