[add] add commets for ringbuffer and workqueue.
RT-Thread/rt-thread pull request #4942
Opened 2021-08-14 05:51 UTC by Jackistang

## 拉取/合并请求描述：(PR description)

[
Add commets for ringbuffer and workqueue.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-08-16 17:55 UTC, mysterywolf requested changes

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/include/ipc/ringbuffer.h
> + * 2021-08-14     Jackistang   add commets for function inferface.
comments 不是 commets;
interfaces 不是 inferfaces

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/include/ipc/workqueue.h
> + * 2021-08-14     Jackistang   add commets for rt_work_init()
comments

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/include/ipc/workqueue.h
> + * @brief Init a work item, and bind it with a callback function.
Init->Initialize 
, binding with a callback function.

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/include/ipc/workqueue.h
> + * @param work          A pointer to work item object.
to the work

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/include/ipc/workqueue.h
> + * @param work_func     A callback function will be called when this work item is being executed.
being去掉

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * 2021-08-14     Jackistang   add commets for function inferface.
comments
interfaces

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @brief Init a ringbuffer object with a given buffer.
Init

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @return Return the size in bytes put into the ringbuffer actually.
Return the size in bytes and put into the ring buffer.

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @brief Get a block of data from the ringbuffer.
get data from the ring buffer
请注意所有的ringbuffer要改成ring buffer，没有ringbuffer这个单词

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @return Return the size of data we read from the ringbuffer actually.
Return the data size that we read from the ring buffer.

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @param ptr       When this function return, *ptr is a pointer to the first character of ringbuffer.
A pointer to the first byte of the ring buffer.

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @brief Put a character into the ringbuffer. If ringbuffer is full, This operation will fail.
This->this

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @param ch        A character to be put into the ringbuffer.
character -> byte

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @return Return the size in bytes put into the ringbuffer. If return 0, it means the ringbuffer if full. If return 1, it means success.
The ring buffer is full if returns 0. Otherwise, it will return 1.

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @brief Put a character into the ringbuffer. If ringbuffer is full, it will discard one old data and put into a new data.
不要使用character 用byte代替

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @param ch        The buffer to store character read from ringbuffer.
character->byte

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/workqueue.c
> + * @return Return a pointer to workqueue object. When the return value is RT_NULL, it means the creation failed.
When the return value is RT_NULL, it means the creation failed. 改成
It will return RT_NULL if failed.

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/workqueue.c
> + * @return -RT_EBUSY    This work item is been executing now.
用主动语态的进行时就可以

2021-08-16 17:55 UTC, mysterywolf commented on components/drivers/src/workqueue.c
> + * @param time      This work item will be delayed by time (unit: an OS tick) before it's been submitted to the work queue.
OS ticks

2021-08-17 14:14 UTC, Jackistang commented on components/drivers/src/ringbuffer.c
> + * @param ptr       When this function return, *ptr is a pointer to the first character of ringbuffer.
这个接口不是获取 ring buffer 里第一个字节的地址，是获取 ring buffer 里第一个可读字节的地址，改成这样是不是好一些呢，
A pointer to the first readable byte of the ring buffer.

2021-08-17 14:27 UTC, Jackistang commented on components/drivers/src/ringbuffer.c
> + * @return Return the size in bytes put into the ringbuffer actually.
这句话的意思是返回实际写入 ring buffer 里的字节数，我改成下面这句了：
Return the byte size of the data actually put into the ring buffer.

2021-08-17 14:41 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @param ptr       When this function return, *ptr is a pointer to the first character of ringbuffer.
可以

2021-08-17 14:44 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @return Return the size in bytes put into the ringbuffer actually.
不要用actually ，actually 是口头用语。直接去掉actually就可以。

2021-08-17 14:45 UTC, Jackistang commented
感谢纠正，已全部修改。

2021-08-17 14:47 UTC, mysterywolf commented
请不要使用actually actually是口头用语 这个副词可以直接移除，或者actual size也可以

2021-08-17 14:52 UTC, mysterywolf requested changes
这里边语法还是有些问题 我得反复review几遍 你先改吧

2021-08-17 14:52 UTC, mysterywolf commented on components/drivers/src/workqueue.c
> + * @param time      This work item will be delayed by time (unit: an OS ticks) before it's been submitted to the work queue.
an OS ticks 去掉an

2021-08-17 14:52 UTC, mysterywolf commented on components/drivers/src/workqueue.c
> + * @param time      This work item will be delayed by time (unit: an OS tick) before it's been submitted to system work queue.
去掉an

2021-08-17 14:55 UTC, mysterywolf requested changes

2021-08-17 14:55 UTC, mysterywolf commented on components/drivers/src/workqueue.c
> + * @brief Cancel a work item in the work queue. If the work item is been executing now, this function will block until it is done.
去掉been 主动语态就可以

2021-08-18 01:45 UTC, Jackistang commented
我重新改了遍，尽可能地修改了语法错误，让语句变得更通顺，麻烦再帮忙检查下。

2021-08-18 04:09 UTC, mysterywolf requested changes

2021-08-18 04:09 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @brief Initialize the ring buffer object with the given buffer.
去掉 with the given buffer

2021-08-18 04:09 UTC, mysterywolf commented on components/drivers/src/ringbuffer.c
> + * @return Return a pointer to ring buffer object. When the return value is RT_NULL, it means the creation failed.
the creation 改成 this creation

2021-08-18 04:09 UTC, mysterywolf commented on components/drivers/src/workqueue.c
> + * @brief Submit a work item to the work queue without delay. This work item will be executed after the current work item is executed.
去掉末尾的is executed

2021-08-18 15:26 UTC, mysterywolf approved these changes

2021-08-19 01:51 UTC, Guozhanxin approved these changes

2021-08-19 01:51 UTC, merged