【doc】add the annotation of device-ipc completion
RT-Thread/rt-thread pull request #4943
Opened 2021-08-15 13:32 UTC by chenyingchun0312

## 拉取/合并请求描述：(PR description)

[
添加completion注释
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-08-17 21:51 UTC, mysterywolf requested changes

2021-08-17 21:51 UTC, mysterywolf commented on components/drivers/src/completion.c
> + * @brief initialize the completion object
请检查：句子开头是大写，结束有句号

2021-08-17 21:51 UTC, mysterywolf commented on components/drivers/src/completion.c
> + *        NOTE: We should not use this api when
fragment，when什么？

2021-08-17 21:51 UTC, mysterywolf commented on components/drivers/src/completion.c
> + * @param timeout    is a timeout period (unit: an OS tick). If the completion is unavailable, the thread will wait for
OS ticks

2021-08-17 21:51 UTC, mysterywolf commented on components/drivers/src/completion.c
> + * @return Return the operation status. ONLY When the return value is RT_EOK, the operation is successful.
When 小写

2021-08-17 21:51 UTC, mysterywolf commented on components/drivers/src/completion.c
> + *         If the return value is any other values, it means that the completion wait failed.
it means that waiting for the completion failed.

2021-08-18 04:52 UTC, chenyingchun0312 commented on components/drivers/src/completion.c
> + * @brief initialize the completion object
好的，收到，请问下，哪里有比较规范的注释要求，说明文档？

2021-08-18 04:53 UTC, chenyingchun0312 commented on components/drivers/src/completion.c
> + * @param timeout    is a timeout period (unit: an OS tick). If the completion is unavailable, the thread will wait for
谢谢满老师这么细心的审核

2021-08-18 12:13 UTC, mysterywolf requested changes

2021-08-18 12:13 UTC, mysterywolf commented on components/drivers/src/completion.c
> + * @param timeout is a timeout period (unit: an OS ticks). If the completion is unavailable, the thread will wait for
不不，这个是OS ticks 没有an了

2021-08-18 12:13 UTC, mysterywolf requested changes

2021-08-18 12:13 UTC, mysterywolf commented on components/drivers/src/completion.c
> + * @return Return the operation status. ONLY When the return value is RT_EOK, the operation is successful.
when小写没改过来

2021-08-18 12:14 UTC, mysterywolf requested changes
其他没啥问题了

2021-08-18 12:14 UTC, mysterywolf commented on components/drivers/src/completion.c
> + * @warning This function can ONLY be called in the thread context. It MUST NOT BE called in interrupt context.
It MUST NOT be，be不用大写

2021-08-18 12:14 UTC, mysterywolf commented on components/drivers/src/completion.c
> + * @brief This function indicate a completion has done.
indicates

2021-08-23 05:20 UTC, chenyingchun0312 commented
> 其他没啥问题了

好的，我修改下，再提交下

2021-08-23 12:06 UTC, mysterywolf approved these changes

2021-08-24 01:57 UTC, merged