[utest][kernel_irq] add the utest of irq
RT-Thread/rt-thread pull request #4951
Opened 2021-08-17 14:18 UTC by supperthomas

## 拉取/合并请求描述：(PR description)

[add the utest of irq.c]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-08-18 01:45 UTC, Guozhanxin commented on examples/utest/testcases/kernel/irq_tc.c
> +    LOG_D("%s test irq_test! irq_count %d  max_get_nest_count %d\n",UTEST_NAME,irq_count,max_get_nest_count);
, 后面要加空格的

2021-08-18 01:48 UTC, Guozhanxin commented on examples/utest/testcases/kernel/irq_tc.c
> +static uint32_t irq_count=0;
= 左右也要有空格的

2021-08-18 01:48 UTC, Guozhanxin commented on examples/utest/testcases/kernel/irq_tc.c
> +    irq_count++;
++ 左边要加空格

2021-08-18 01:50 UTC, Guozhanxin requested changes
再检查一下代码格式吧

2021-08-18 13:11 UTC, supperthomas commented
@Guozhanxin

2021-08-18 22:36 UTC, Guozhanxin approved these changes

2021-08-18 22:41 UTC, Guozhanxin commented
涛哥，我看你这个里面只测试了sethook和获取嵌套层数。开关中断是不是也想办法加两个测试项上来啊

2021-08-19 01:32 UTC, supperthomas commented
> 涛哥，我看你这个里面只测试了sethook和获取嵌套层数。开关中断是不是也想办法加两个测试项上来啊？还是说再单独提个pr？

发现个小问题：你们只有sethook，没有unsethook。感觉测试之后恢复不到之前的状态。这个不知道有么有solution？

开关总中断，这个要怎么测试呢？想不到怎么测。提供如何测试，后面可以考虑再提个PR。

2021-08-19 01:33 UTC, Guozhanxin commented
> > 涛哥，我看你这个里面只测试了sethook和获取嵌套层数。开关中断是不是也想办法加两个测试项上来啊？还是说再单独提个pr？
> 
> 发现个小问题：你们只有sethook，没有unsethook。感觉测试之后恢复不到之前的状态。这个不知道有么有solution？
> 
> 开关总中断，这个要怎么测试呢？想不到怎么测。提供如何测试，后面可以考虑再提个PR。

sethook为空就好了啊

2021-08-19 01:39 UTC, supperthomas commented
> > > 涛哥，我看你这个里面只测试了sethook和获取嵌套层数。开关中断是不是也想办法加两个测试项上来啊？还是说再单独提个pr？
> > 
> > 
> > 发现个小问题：你们只有sethook，没有unsethook。感觉测试之后恢复不到之前的状态。这个不知道有么有solution？
> > 开关总中断，这个要怎么测试呢？想不到怎么测。提供如何测试，后面可以考虑再提个PR。
> 
> sethook为空就好了啊

哦

2021-08-19 03:06 UTC, Guozhanxin commented
涛哥，合并event之后这个冲突了，你再改一下吧

2021-08-19 05:12 UTC, supperthomas commented
> 涛哥，合并event之后这个冲突了，你再改一下吧

好的

2021-08-19 14:30 UTC, merged