support ch32f10x family, add ch32f103c8-core bsp
RT-Thread/rt-thread pull request #4993
Opened 2021-08-31 07:28 UTC by charlown

## 拉取/合并请求描述：(PR description)

[
支持ch32f103c8-core bsp，实现pin, uart1/2/3, spi1/2, 硬件i2c1/2(仅实现支持7位地址外设), rtc(内部或外部低速晶振), wdt，上述驱动已自行验证测试。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ x] 本拉取/合并符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-08-31 15:52 UTC, mysterywolf commented
https://github.com/mysterywolf/formatting 可以使用这个扫描一下就不报错了 欢迎star

2021-09-01 11:52 UTC, Guozhanxin commented on bsp/Copyright_Notice.md
> +License: 未注明
这个是不是可以跟官方人员确认下，万一license有冲突就很麻烦了

2021-09-01 13:09 UTC, charlown commented on bsp/Copyright_Notice.md
> +License: 未注明
要不这样吧，Copyright_Notice这块暂时先不填写，等后面沁恒的risc-v芯片支持后再一并写好了

2021-09-07 07:15 UTC, Guozhanxin commented on bsp/wch/arm/ch32f103c8-core/board/Kconfig
> +		config BSP_USING_UART1
Kconfig 里的 Tab 要改成 空格

2021-09-07 07:17 UTC, Guozhanxin commented on bsp/wch/arm/ch32f103c8-core/README.md
> +
readme 里的多余的空行删一下吧

2021-09-07 07:20 UTC, Guozhanxin commented on bsp/wch/arm/Libraries/Kconfig
> +config SOC_ARM_SERIES_CH32F103
这里的定义和board里的重复了，所以board里面就不要用这个名字了，直接select这个 SOC_ARM_SERIES_CH32F103 就行

2021-09-07 07:20 UTC, Guozhanxin commented on bsp/wch/arm/ch32f103c8-core/board/Kconfig
> +config SOC_ARM_SERIES_CH32F103
这里换一个名字，然后 select SOC_ARM_SERIES_CH32F103

2021-09-07 07:21 UTC, Guozhanxin requested changes
看起来基本问题不大，把上面写的一些问题改了就好了

2021-09-07 08:12 UTC, charlown commented
似乎mysterywolf的formatting并不能format其他文件.

2021-09-07 10:50 UTC, mysterywolf commented
formatting默认是format .c .cpp .h .hpp的 readme有写，ci也只检查上述四种格式



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 7, 2021 04:12 AM
To: ***@***.***&gt;;
Cc: "Meco Jianting ***@***.******@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] support ch32f10x family, add ch32f103c8-core bsp (#4993)




 
似乎mysterywolf的formatting并不能format其他文件.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-09-09 09:36 UTC, Guozhanxin approved these changes

2021-09-11 01:19 UTC, merged