remove rtlibc
RT-Thread/rt-thread pull request #5003
Opened 2021-09-02 06:48 UTC by mysterywolf

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-09-03 09:23 UTC, Guozhanxin commented
满老师，ci已经编过了，再优化下代码吧，现在改动的太多了。

2021-09-03 14:17 UTC, mysterywolf commented
> 满老师，ci已经编过了，再优化下代码吧，现在改动的太多了。

郭老师yyds！

2021-09-03 14:22 UTC, mysterywolf commented
> 满老师，ci已经编过了，再优化下代码吧，现在改动的太多了。

优化我会放在下个pr进行，这个pr只负责移除和移除相关的操作。我已经有具体的优化方案了。要不然混在一起太不好识别别了，本身这个pr修改的文件已经很多了。

2021-09-04 19:51 UTC, BernardXiong requested changes
need to discuss.

2021-09-04 19:51 UTC, BernardXiong commented on bsp/tm4c123bsp/libraries/Drivers/drv_pwm.c
> +        configuration->pulse = PWMPulseWidthGet(PWM0_BASE, PWM_OUT_0 + (rt_uint32_t)(configuration->channel - 1));
这些修改感觉每必要

2021-09-04 19:51 UTC, BernardXiong commented on bsp/tm4c123bsp/libraries/Drivers/drv_pwm.h
> +    rt_uint32_t   counterMode;
这些也没必要

2021-09-04 19:51 UTC, BernardXiong commented on bsp/tm4c123bsp/libraries/Drivers/drv_spi.c
> +    rt_uint32_t ui32Protocol, ui32Mode;
这些也没必要

2021-09-04 19:51 UTC, BernardXiong commented on components/dfs/include/dfs_posix.h
> -int open(const char *file, int flags, ...);
如果这些不进行声明，应该很多都可以不用去声明了。

2021-09-04 19:51 UTC, BernardXiong commented on components/libc/compilers/common/fcntl.h
> +#ifndef __FCNTL_H__
这个文件有些讨厌的，类似newlib这样的libc，这个头文件是存在的。这里有同名文件存在，容易出现问题。

2021-09-04 19:54 UTC, mysterywolf commented on components/libc/compilers/common/fcntl.h
> +#ifndef __FCNTL_H__
在gcc里边 这个头文件可以直接覆盖，类似的还有sys/time.h。

2021-09-04 19:55 UTC, mysterywolf commented on components/dfs/include/dfs_posix.h
> -int open(const char *file, int flags, ...);
这个虽然被移除了 但是在dfs_posix.h里边依然保留了对open所在头文件的引用。
所以用户想要通过引用dfs_posix.h 来使用open函数依然是可以的

2021-09-04 19:57 UTC, mysterywolf commented on bsp/tm4c123bsp/libraries/Drivers/drv_spi.c
> +    rt_uint32_t ui32Protocol, ui32Mode;
这里先不纠结rt_uint32_t还是uint32_t 应为该文件大部分都是在引用rt_xxx的结构类型，只有uint32_t是个例外因此就跟随该文件都改成了rt_uint32_t
这个pr不强调rt_uint32_t还是uint32_t，如果想要规范，单独提一个pr，因为有很多文件都存在不规范的问题，一起改。

2021-09-11 12:00 UTC, closed without merging