[update] support armclang and c++11.
RT-Thread/rt-thread pull request #5008
Opened 2021-09-03 03:39 UTC by liukangcc

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-09-03 07:17 UTC, Guozhanxin commented on components/cplusplus/cpp11/atomic_8.c
> +// override gcc builtin atomic function for std::atomic<int64_t>, std::atomic<uint64_t>
文件头都加上啊，也看下版权相关的，是否有不合规的。

2021-09-03 07:19 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/README.md
> +[Documents](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.100073_0610_00_en/wip1493208196925.html)
这个readme要重写或者删掉

2021-09-03 08:18 UTC, Guozhanxin commented on components/libc/compilers/common/sys/time.h
> +#include <sys/_timeval.h>
@mysterywolf 满老师，这个问题帮忙看看吧，之前的time在gcc下有问题，工具链里的 timeval 结构体定义和这里的不一样。这么修复的话，龙芯的工具链里没有这个文件。。。帮忙看看怎么搞啊

2021-09-03 09:35 UTC, Guozhanxin commented on components/cplusplus/cpp11/README.md
> +# C++ 11 support for RT-Thread
写一下，具体支持了哪些特性吧，支持了哪些类
可以有个简单的示例。

2021-09-03 09:35 UTC, Guozhanxin commented on components/cplusplus/cpp11/README_ZH.md
> +这是 RT-Thread 中的 c++ 11 组件。 为了支持c++语言，此组件实现一个基本的环境，比如 new/delete 操作符。
这里很明显不对啊，支持我们支持的特性更多了啊。

2021-09-03 09:36 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/clock.cpp
> +#endif
这一部分可以移除掉

2021-09-03 09:38 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/clock.cpp
> +  __ts->tv_nsec = (t %RT_TICK_PER_SECOND) * NANOSECOND_PER_TICK  ;//TODO
代码都格式化一下吧，这里的格式看着不对劲

2021-09-03 09:38 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/clock.cpp
> +  __ts->tv_nsec = (t %RT_TICK_PER_SECOND) * NANOSECOND_PER_TICK  ;//TODO
todo可以删除

2021-09-03 09:40 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/condvar.cpp
> +                toBeReturned = -1;
命名规则检查下吧，这个不符合我们的命名规范

2021-09-03 09:42 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/thread.cpp
> +extern "C" int pthread_setspecific(pthread_key_t key, const void *value);
这一部分应该可以删掉

2021-09-03 09:43 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/thread.cpp
> +        __rem->tv_nsec = 0;
这里改一下吧，改成调用我们的nanosleep函数

2021-09-03 09:47 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/thread.cpp
> +    pthread_t *pid = (pthread_t *)rt_malloc(sizeof(pthread_t));
这里存在内存泄漏，可以直接把pid存到 __t->data里。不用把pid的地址存进去

2021-09-03 09:50 UTC, Guozhanxin commented on components/cplusplus/cpp11/atomic_8.c
> +// override gcc builtin atomic function for std::atomic<int64_t>, std::atomic<uint64_t>
注释方法不对，不能用 // 来注释

2021-09-03 09:51 UTC, Guozhanxin commented on components/cplusplus/cpp11/emutls.c
> +typedef struct emutls_address_array {
格式化一下这个文件吧

2021-09-03 09:52 UTC, Guozhanxin commented on components/cplusplus/cpp11/gcc/__utils.h
> +    typedef std::chrono::time_point<tick_clock> time_point;
这些文件都格式化下吧

2021-09-03 09:52 UTC, Guozhanxin commented on components/cplusplus/cpp11/gcc/condition_variable
> +//#if defined(RT_USING_LIBC) && defined(RT_USING_PTHREADS)
这部分代码删除吧

2021-09-03 09:53 UTC, Guozhanxin commented on components/cplusplus/cpp11/gcc/condition_variable
> +//#endif // (RT_USING_LIBC) && (RT_USING_PTHREADS)
还有这行也删掉

2021-09-03 09:54 UTC, Guozhanxin commented on components/cplusplus/cpp11/gcc/thread
> +
有多余的空行

2021-09-03 09:56 UTC, Guozhanxin commented on components/cplusplus/cpp11/gcc/thread.cpp
> +    return __n;
看下这个api到底啥意思，armclang上这里返回的 1

2021-09-03 15:30 UTC, mysterywolf commented on components/libc/compilers/common/sys/time.h
> +#include <sys/_timeval.h>
这个问题我半年前就注意到了，整完rtlibc，开会说。

2021-09-05 18:29 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/issues/3388

2021-09-07 02:49 UTC, mysterywolf requested changes

2021-09-07 02:49 UTC, mysterywolf commented on components/cplusplus/cpp11/armclang/clock.cpp
> +#include "rtthread.h"
<rtthread.h>

2021-09-07 02:49 UTC, mysterywolf commented on components/cplusplus/cpp11/armclang/tpl.h
> +#include "rtthread.h"
<>

2021-09-07 02:49 UTC, mysterywolf commented on components/cplusplus/cpp11/gcc/utils.cpp
> +#include "sys/time.h"
<>

2021-09-07 02:49 UTC, mysterywolf commented on components/libc/compilers/common/sys/time.h
> +#endif
这个删掉

2021-09-07 05:41 UTC, Guozhanxin commented on components/cplusplus/cpp11/README.md
> +
多个空行

2021-09-07 05:41 UTC, Guozhanxin commented on components/cplusplus/README.md
> -This is the C++ component in RT-Thread RTOS. In order to support C++ language, this component
这个文件为啥要删掉

2021-09-07 05:42 UTC, Guozhanxin commented on components/cplusplus/cpp11/README_ZH.md
> +
多个空行

2021-09-07 05:42 UTC, Guozhanxin commented on components/cplusplus/cpp11/README_ZH.md
> +   CXXFLAGS = CFLAGS  + ' -std=c++14 -fabi-version=0 -MMD -MP -MF'
这里改成 c++11 吧

2021-09-07 05:43 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/clock.cpp
> +#include "rtthread.h"
对啊，这里要用 <>

2021-09-07 05:44 UTC, Guozhanxin commented on components/cplusplus/cpp11/armclang/condvar.cpp
> +    x = rt_mutex_create("mutx", RT_IPC_FLAG_PRIO);// xSemaphoreCreateMutex();
注释删掉呀

2021-09-07 05:51 UTC, Guozhanxin commented on components/libc/pthreads/pthread_attr.c
> +#define DEFAULT_STACK_SIZE  8192
这个就不要改了，还原吧

2021-09-07 11:51 UTC, mysterywolf requested changes

2021-09-07 11:51 UTC, mysterywolf commented on components/cplusplus/cpp11/armclang/tpl.h
> +#include "rtthread.h"
这个没改过来

2021-09-08 04:46 UTC, mysterywolf commented
等待https://github.com/RT-Thread/rt-thread/pull/5003这个pr合并之后 再重新启动一次ci 如果ci没有问题就可以合并了

2021-09-11 12:04 UTC, BernardXiong commented
Please rebase it.

2021-09-11 12:27 UTC, mysterywolf commented
remove libc已经合并，将重启CI检查一下

2021-09-11 12:44 UTC, mysterywolf approved these changes

2021-09-14 12:03 UTC, Guozhanxin commented on bsp/stm32/stm32f103-atk-warshipv3/rtconfig.py
> +if os.getenv('RTT_PLATFORM'):
那就把这个环境变量去掉吧，不添加 mdk-ac6 的命令了

2021-09-14 12:03 UTC, Guozhanxin requested changes
那就把这个环境变量去掉吧，不添加 mdk-ac6 的命令了

2021-09-15 08:23 UTC, closed without merging