[netdev] ping cmd with specified netif in lwip-2.1.2
RT-Thread/rt-thread pull request #5024
Opened 2021-09-07 03:02 UTC by yukelab

using LWIP_HOOK_IP4_ROUTE_SRC hook find specified netif route, using
cmd `ping 192.168.xx.xx e0`, ping dest using e0 netif. if not found
netif, using default netif, the effect is same as the cmd `ping 192.168.xx.xx` that only ping with default netif.

## 拉取/合并请求描述：(PR description)

[
解决 netdev 无法通过指定网卡进行ping 操作。

通过增加 lwip 2.1.2 下的 钩子函数 LWIP_HOOK_IP4_ROUTE_SRC  区分指定的网卡。

已经测试
在 art-pi 下多网卡 （wifi，eth）过协议栈 lwip2.1.2，进行测试；
在 qemu-vexpress-a9 单网卡下通过指定 网卡，进行测试；
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-09-07 03:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=5024) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=5024) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=5024) it.</sub>

2021-09-07 03:13 UTC, mysterywolf commented
俺觉得，这个应该是sal层的问题，sal层应该自动根据ip的网段选择对应的网卡。而不是去改lwip，如果要是用esp8266的话就不好使了。比如esp8266作为esp0网卡绑定192.168.1.xx网段，有线网卡作为默认网卡绑定192.168.2.xxx网段，在用户ping192.168.1.1的时候就应该由sal自动选择从esp8266走，而不是一条道走到黑的只采用默认网卡ping。

2021-09-07 05:13 UTC, yukelab commented
> 
> 
> 俺觉得，这个应该是sal层的问题，sal层应该自动根据ip的网段选择对应的网卡。而不是去改lwip，要是改lwip的话，如果要是用esp8266的话就不好使了。比如esp8266作为esp0网卡绑定192.168.1.xx网段，有线网卡作为默认网卡绑定192.168.2.xxx网段，在用户ping192.168.1.1的时候就应该由sal自动选择从esp8266走，而不是一条道走到黑的只采用默认网卡ping。
> 而且建议sal层应该增加一个回环网卡，127网段，用于（特别是）at模块的回环测试使用。
> @Guozhanxin

1.  走外网，sal层没有办法自动根据ip的网段选择对应的网卡， 如多网卡下 ping www.rt-thread.org，需要选哪个网卡？
2.   SAL 中需要判断走的是 AT，WIZ，LWIP 中的哪一个，同时也要进行 route，不然走外网，同样会牵扯到用哪一个网卡；所以，需要在 SAL 定位到 协议栈种类，然后在对应协议栈的接口中选择对应的网卡；

2021-09-07 12:03 UTC, mysterywolf commented
在多网卡ping外网的情况下按照linux的行为走。

2021-09-08 01:51 UTC, xiangxistu commented
> 在多网卡ping外网的情况下应该按照linux的行为走。

我感觉，这块整体没有问题；在没有指定网卡 ping 时走一个默认网卡，在指定网卡时，走指定的网卡。

2021-09-08 01:53 UTC, xiangxistu reviewed
改动相当于对 ping 命令进行扩展，之前的方法还是可能兼容。

2021-09-08 07:10 UTC, xiangxistu commented on components/net/netdev/src/netdev.c
>          rt_kprintf("Please input: ping <host address>\n");
对了，这里添加一个使用说明吧； ``ping <host address> <netdev_name>`` 之类的

2021-09-09 01:46 UTC, Guozhanxin commented on components/net/lwip-2.1.2/src/arch/sys_arch.c
> +    }
格式不对，缩进都是四个空格的

2021-09-19 22:13 UTC, Guozhanxin requested changes
请按照评审要求修改

2021-09-28 04:12 UTC, mysterywolf commented
用这个把不符合格式的源码文件扫描一下https://github.com/mysterywolf/formatting

2021-11-15 01:09 UTC, Guozhanxin commented
@xiangxistu 你把这个pr改成重新提交一下吧

2021-11-15 01:22 UTC, xiangxistu commented
> @xiangxistu 你把这个pr改下，重新提交一下吧

OK，我还以为早就合并了

2021-11-15 10:48 UTC, closed without merging