[update] src/thread.c function description.
RT-Thread/rt-thread pull request #5038
Opened 2021-09-10 07:36 UTC by liukangcc

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-09-10 08:00 UTC, Guozhanxin commented on src/thread.c
> + */
参考这个pr的注释修改，https://github.com/RT-Thread/rt-thread/pull/5039/files

- static 的函数就不要写注释了。
- 公开的函数，写清楚用法和每个参数的意义以及注意事项。

2021-09-10 10:14 UTC, Guozhanxin commented on src/thread.c
> + * @return   Return the operation status. When the return value is RT_EOK, the function is successfully executed.
这个跟上面没对齐，把上面的再缩进一个空格吧

2021-09-10 10:15 UTC, Guozhanxin commented on src/thread.c
> + *          RT_THREAD_CTRL_STARTUP for starting a thread;
这些参数，向后缩进两个空格。

2021-09-10 10:16 UTC, Guozhanxin commented on src/thread.c
> + * @param   name the name of thread finding.
这个时态感觉不太对啊

2021-09-10 10:36 UTC, Guozhanxin approved these changes

2021-09-10 16:34 UTC, mysterywolf requested changes

2021-09-10 16:34 UTC, mysterywolf commented on src/thread.c
> + * @param   hook the specified hook function.
缺少be动词 hook is the specified hook function 下面的param参数也存在这个问题

2021-09-10 16:34 UTC, mysterywolf commented on src/thread.c
> + * @note    the hook function must be simple and never be blocked or suspend.
The大写

2021-09-11 02:52 UTC, mysterywolf requested changes

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + * @brief   This function will initialize a thread, normally it's used to initialize a
normally 去掉
逗号改句号，It大写

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + * @param   tick the time slice if there are same priority thread.
param缺be动词 都得需要加一下 不光是这里

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + *          thread queue and detached/deleted from system object management.
from the system object management.

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + *        choose a highest thread to run. After yield processor, the current thread
the highest thread

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + * @return  Return the operation status. When the return value is RT_EOK, the function is successfully executed.
When 改成if

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + *          When the return value is any other values, it means this operation failed.
When改成if
汉语的当有如果的意思，英语里没有。

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + * @return  Return the operation status. When the return value is RT_EOK, the function is successfully executed.
When 改 if 好多地方是这个问题 需要筛一下 这个会导致英语母语者的费解

2021-09-11 02:52 UTC, mysterywolf commented on src/thread.c
> + * @return  Return the operation status. When the return value is RT_EOK, the function is successfully executed.
if

2021-09-11 02:55 UTC, mysterywolf requested changes

2021-09-11 02:55 UTC, mysterywolf commented on src/thread.c
> + * @param   name the name of thread finding.
name is the name of expected thread.

2021-09-11 02:55 UTC, mysterywolf commented on src/thread.c
> + * @return  the found thread.
the expected thread 然后介绍一下如果找不到返回的是什么

2021-09-11 02:55 UTC, mysterywolf commented on src/thread.c
> + *          When the return value is any other values, it means this operation failed.
if

2021-09-11 12:21 UTC, mysterywolf commented on src/thread.c
> + * @param   thread the specified thread to be controlled.
be动词缺失

2021-09-13 06:21 UTC, mysterywolf approved these changes

2021-09-13 23:25 UTC, merged