[kernel]Normalized kernel API annotation
RT-Thread/rt-thread pull request #5040
Opened 2021-09-10 07:57 UTC by yangjie11

## 拉取/合并请求描述：(PR description)

[
device.c
idle.c
mem.c
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-09-10 16:28 UTC, mysterywolf requested changes

2021-09-10 16:28 UTC, mysterywolf commented on src/device.c
> + * @param dev the specific device object.
dev is a specific device object.

2021-09-10 16:28 UTC, mysterywolf commented on src/device.c
> + * @param dev the pointer of device driver structure.
dev is the pointer of device driver structure.

2021-09-10 16:28 UTC, mysterywolf commented on src/device.c
> + * @param dev the pointer of device driver structure.
缺be动词 param的都存在这个问题。

2021-09-11 02:44 UTC, mysterywolf requested changes

2021-09-11 02:44 UTC, mysterywolf commented on src/device.c
> + * @brief This function registers a device driver with specified name.
with a specified name.

2021-09-11 02:44 UTC, mysterywolf commented on src/device.c
> + * @return RT_EOK.
这个不用加句号 不是一个句子

2021-09-11 02:44 UTC, mysterywolf commented on src/device.c
> + * @return RT_EOK.
不用加句号

2021-09-11 02:44 UTC, mysterywolf commented on src/scheduler.c
> + * @brief This function will perform one schedule. It will select one thread
scheduling

2021-09-11 02:44 UTC, mysterywolf commented on src/scheduler.c
> + *        thread will be set as READY and remove from suspend queue.
remove from the suspend queue.
冠词这个审查的比较松，因为冠词的缺失不会造成英语母语者的阅读困难，但是也要注意冠词的问题。

2021-09-11 12:18 UTC, mysterywolf approved these changes

2021-09-11 14:00 UTC, BernardXiong commented
@Guozhanxin Please check it and whether +2.

2021-09-13 23:26 UTC, Guozhanxin approved these changes

2021-09-14 14:32 UTC, merged