Verify the SPI, SPI_FLASH and SPI_FS drivers in the BSP of the art-pi main branch of rtthread.
RT-Thread/rt-thread pull request #5048
Opened 2021-09-11 08:48 UTC by Rbb666

## 拉取/合并请求描述：(PR description)

[
Verify the SPI, SPI_FLASH and SPI_FS drivers in the BSP of the art-pi main branch of rtthread. The corresponding configuration is added in kconfig. In sconscript, add the script to generate the. C file in the port folder, and add the driver options of peripherals in cubemx.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-09-13 01:15 UTC, Guozhanxin commented
你本地scons编译下试试，看是不是编不过

2021-09-13 23:22 UTC, Guozhanxin commented on bsp/stm32/stm32h750-artpi-h750/board/port/drv_sdio.c
> +//#ifndef SDIO_USING_1_BIT
注释的代码删掉吧

2021-09-13 23:23 UTC, Guozhanxin commented on bsp/stm32/stm32h750-artpi-h750/board/port/drv_sdio.c
> +    struct stm32_sdio_des sdio_des2;
这部分和通用驱动差别很大是吗

2021-09-14 00:05 UTC, Rbb666 commented on bsp/stm32/stm32h750-artpi-h750/board/port/drv_sdio.c
> +    struct stm32_sdio_des sdio_des2;
是的，差别很大，ART-PI有两个SDIO，驱动有所增加和更改。

2021-09-15 15:30 UTC, Guozhanxin requested changes
FTP-lib和otalib就不要加进来了，

2021-09-26 00:07 UTC, Guozhanxin commented on bsp/stm32/stm32h750-artpi-h750/board/port/wlan_wiced_lib/SConscript
> +    LIBS += ['libwifi_6212_armcm7_2.1.2_armcc']
库文件没有提交上来

2021-09-26 04:01 UTC, Guozhanxin approved these changes

2021-09-27 10:05 UTC, merged