Add dataqueue.c function annotation
RT-Thread/rt-thread pull request #5295
Opened 2021-11-23 08:09 UTC by ousugo

## 拉取/合并请求描述：(PR description)

[
Add dataqueue.c function annotatio
增加 components\drivers\src\dataqueue.c 函数注释
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-11-24 03:46 UTC, mysterywolf requested changes
请注意类似的问题，我只是挑了一个评论

2021-11-24 03:46 UTC, mysterywolf commented on components/drivers/src/dataqueue.c
> + * @param queue The data queue object
https://github.com/RT-Thread/rt-thread/blob/master/src/ipc.c#L85 请参考这里，参数名称+is+介绍

2021-11-24 03:46 UTC, mysterywolf commented on components/drivers/src/dataqueue.c
> + * @param lwm  Low water mark, when the number of data in the data queue is less than this value,
When大写，逗号改句号

2021-11-24 07:00 UTC, mysterywolf requested changes

2021-11-24 07:00 UTC, mysterywolf commented on components/drivers/src/dataqueue.c
> + *           When the number of data in the data queue is less than this value,will
逗号后面加空格，主句缺主语 什么will

2021-11-24 13:14 UTC, mysterywolf approved these changes

2021-11-24 13:23 UTC, ousugo commented
谢谢😄

2021-11-24 13:25 UTC, mysterywolf commented
@ousugo  感谢贡献pr，
@Guozhanxin 语法上没啥问题了 但是没有检查注释的功能描述是否正确，请确认功能性正确。

2021-11-26 10:10 UTC, Guozhanxin commented
> @ousugo 感谢贡献pr， @Guozhanxin 语法上没啥问题了 但是没有检查注释的功能描述是否正确，请确认功能性正确。

@liukangcc

2021-11-30 08:03 UTC, liukangcc commented on components/drivers/src/dataqueue.c
> + * @return   Return the operation status. When the return value is RT_EOK, the operation is successful.
失败的返回值

2021-11-30 08:03 UTC, liukangcc commented on components/drivers/src/dataqueue.c
> + * @return   Return the operation status. When the return value is RT_EOK, the operation is successful.
失败的返回值

2021-11-30 08:03 UTC, liukangcc commented on components/drivers/src/dataqueue.c
> + * @return   Return the operation status. When the return value is RT_EOK, the operation is successful.
失败的返回值

2021-11-30 15:00 UTC, mysterywolf commented on components/drivers/src/dataqueue.c
> + * @return   Return the operation status. When the return value is RT_EOK, the operation is successful.
是否可以直接写 如果<0 则为失败，因为RT-Thread的错误值类型比较少，没有必要把每一种都在注释里列出来

2021-12-01 10:01 UTC, merged