Add annotation
RT-Thread/rt-thread pull request #5343
Opened 2021-12-07 08:11 UTC by ousugo

## 拉取/合并请求描述：(PR description)

[
Add pipe.c function annotatio
增加 components\drivers\src\pipe.c 函数注释
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-12-08 00:22 UTC, mysterywolf commented
感谢提交pr，目前pipe源码在进行一些整理工作，源码和之前没有改动，但是可能会和你先在的pr造成冲突。现在先不合并此pr，等pipe源码调整完后，麻烦再重新提交或者解决一下冲突。

2021-12-14 02:16 UTC, mysterywolf commented
你好 请重新处理一下冲突

2021-12-14 04:10 UTC, mysterywolf requested changes

2021-12-14 04:10 UTC, mysterywolf commented on components/drivers/src/pipe.c
> + *           POLLHUP means there is no thread that has the pipe open for writing.
has? 你是想说持有占有吗？occupied the pipe to open for writing.
下同

2021-12-14 04:10 UTC, mysterywolf commented on components/drivers/src/pipe.c
> + * @return   Always return RT_EOK yet.
这行yet删掉

2021-12-14 04:10 UTC, mysterywolf commented on components/drivers/src/pipe.c
> + * @return   Return the operation status, 0 on successful.
Return the operation status.
0 is successful.
分成两句话，英语不能随意使用逗号，除非有连接词fanboys（参见：coordinating conjunctions）
其他位置也有类似的问题，不一一列举了

2021-12-14 06:18 UTC, mysterywolf approved these changes

2021-12-15 02:17 UTC, yangjie11 commented
可以
@Guozhanxin

2021-12-15 04:00 UTC, merged