reload timeout_tick with absolute base value
RT-Thread/rt-thread pull request #5402
Opened 2021-12-20 08:25 UTC by thewon86

## 拉取/合并请求描述：(PR description)

[
1. 分离出一个 `_timer_start` 局部接口，可以指定定时器启动时间。
2. 梳理了 timer_check 过程，把周期定时器再次启动开始时间设定为 `timer->timeout_tick`。
3. 删除了 TIMER_IDLE TIMER_BUSY 等相关代码。

修改后的特性：
1. 软定时器超时回调函数里支持执行长时间操作（大于 systick 小于定时器定时间隔）。
2. 可以避免因长时间操作引起的定时器 timeout 漂移问题。
3. 删掉 IDLE BUSY 等部分代码，是因为 timeout 的回调函数里可以对当前线程进行任何操作，不避讳 rt_timer_start rt_timer_stop rt_timer_control ，既不会引入意外问题，也不影响后续工作。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2022-01-02 00:47 UTC, enkiller commented on src/timer.c
> -            need_schedule = RT_TRUE;
need_schedule 标记是防止 A 定时器回调中 sleep 等操作导致线程挂起。B 定时器启动时，意外将 timer 线程唤醒。导致 A 定时器意外唤醒

2022-01-02 01:04 UTC, enkiller commented
timer 定时器的周期，指的是回调执行完成，下一次执行需要等待的时间。回调函数执行的时间，并不算在周期内

2022-01-04 01:32 UTC, thewon86 commented on src/timer.c
> -            need_schedule = RT_TRUE;
need_schedule 这个变量的作用不是你说那样，跟你说的那个没联系，rt_timer_start 最后有两种情况，一种是需要进行任务调度切换到 timer 线程，一种是不需要。
需要任务调度的流程是： 开中断；调用`rt_schedule`；`return` 返回。
不需要任务调度的流程是： 开中断；`return` 返回。
之前就是把上述两种流程合并到一起，用 `need_schedule` 变量控制中间 `rt_schedule` 是否被执行的开关。这样的用法在多处有 return 返回的情况下使用比较合适，但是这里只在函数最后紧挨着的地方有两个返回点，分开写代码语义比较清晰。
你可能想说的是 `_soft_timer_status` 这个变量，用来限制“某些”情况下任务调度，关于这个 pr 的详细说明，请移步论坛，那里有更全面的理论分析。

2022-01-04 01:34 UTC, thewon86 commented
> timer 定时器的周期，指的是回调执行完成，下一次执行需要等待的时间。回调函数执行的时间，并不算在周期内

第一次听到这种说法。

2022-01-05 05:54 UTC, Guozhanxin commented
> timer 定时器的周期，指的是回调执行完成，下一次执行需要等待的时间。回调函数执行的时间，并不算在周期内

我理解的定时器的周期，跟回调函数执行时间没关系，表示的是在一个固定周期内调用回调函数

比如：如果在10s的时候启动了一个周期是3s的周期性定时器A，那就是要在时刻，13、16、19、22、25、28... 的时刻去调用回调函数。

2022-01-09 00:12 UTC, enkiller commented on src/timer.c
> -            need_schedule = RT_TRUE;
能否贴一下论坛链接？

2022-01-09 00:38 UTC, enkiller commented
> > timer 定时器的周期，指的是回调执行完成，下一次执行需要等待的时间。回调函数执行的时间，并不算在周期内
> 
> 我理解的定时器的周期，跟回调函数执行时间没关系，表示的是在一个固定周期内调用回调函数
> 
> 比如：如果在10s的时候启动了一个周期是3s的周期性定时器A，那就是要在时刻，13、16、19、22、25、28... 的时刻去调用回调函数。

不能单纯从周期这个词上理解。定时器的周期，可以理解为自动调用 start 函数。

2022-01-10 03:28 UTC, Guozhanxin commented
> > > timer 定时器的周期，指的是回调执行完成，下一次执行需要等待的时间。回调函数执行的时间，并不算在周期内
> > 
> > 
> > 我理解的定时器的周期，跟回调函数执行时间没关系，表示的是在一个固定周期内调用回调函数
> > 比如：如果在10s的时候启动了一个周期是3s的周期性定时器A，那就是要在时刻，13、16、19、22、25、28... 的时刻去调用回调函数。
> 
> 不能单纯从周期这个词上理解。定时器的周期，可以理解为自动调用 start 函数。

但是，我感觉大家应该都认为，周期就是周期的意思。。。你这种说法，我也是第一次听说

2022-01-12 20:35 UTC, mysterywolf commented
不必在周期这个概念上过于纠结，实际上一个完备的定时器是有多种不同的周期模式的， @thewon86 出出提到的是一种， @enkiller 炸弹哥提到的也是一种，怎么理解都对。
RT-Thread的定时器没有提供多种周期模式，因此我们只需要规定好我们rtt的timer的周期指的是什么意思就好，不需要纠结这一点。
比如uCOS的定时器周期就可以设置2个还是3种我忘了，相对的绝对的都可以设定。
MATLAB的定时器也可以同时支持炸弹哥和出出说的这种情况。

2022-01-18 08:12 UTC, thewon86 commented
> 

最后一种没理解啥意思，sigleShot rtt 是支持的，我修改后的是 fixedRate 模式。如果想实现 fixedDelay ，当初我想着是在 timeout 回调函数执行结束返回前应用主动执行一次 rt_timer_start。

这样不限制在 timeout 回调里调用 rt_timer_start ，而且可以由应用决定是否重新计时。

2022-01-20 03:55 UTC, mysterywolf commented
>我修改后的是 fixedSpacing 模式

我觉得OK！ 其他的fixedRate fixedDelay可以不用实现，或者以后再实现都可以。我们只需要准确的明确，周期性定时器到底是从什么时候开始算起就好。

2022-01-20 04:07 UTC, mysterywolf approved these changes

2022-01-20 12:59 UTC, BernardXiong commented
@mysterywolf 合并你的PR后，这个变成冲突了

2022-01-21 01:11 UTC, mysterywolf requested changes

2022-01-21 01:11 UTC, mysterywolf commented on src/timer.c
> +     */
这个注释应该删掉 这个是给之前那个assert的说明

2022-01-21 01:11 UTC, mysterywolf commented on src/timer.c
> +    RT_ASSERT(timer->init_tick < RT_TICK_MAX / 2);
这个assert可以删掉了，在pr #5533 中，我已经把这个参数有效性的判断放在了init和create函数，上来就判断有效性。
https://github.com/RT-Thread/rt-thread/pull/5533/files#diff-340e9ee0d7971fa052b504957c48a3a313f76cb85490ff00afb3e9293d09f53aR335
https://github.com/RT-Thread/rt-thread/pull/5533/files#diff-340e9ee0d7971fa052b504957c48a3a313f76cb85490ff00afb3e9293d09f53aR266
https://github.com/RT-Thread/rt-thread/pull/5533/files#diff-340e9ee0d7971fa052b504957c48a3a313f76cb85490ff00afb3e9293d09f53aL404-L409

2022-01-21 03:23 UTC, mysterywolf approved these changes

2022-01-24 01:18 UTC, BernardXiong commented
除了 @mysterywolf ，其他人是否搭成一致？ @Guozhanxin @enkiller ？Please provide your comments, thank you.

2022-01-24 03:01 UTC, Guozhanxin commented
> 除了 @mysterywolf ，其他人是否搭成一致？ @Guozhanxin @enkiller ？Please provide your comments, thank you.

我对代码更改没意见，我是期望有更多的测试用例和测试结果给出来

2022-01-25 02:59 UTC, enkiller commented
这次定时器修改后，需要在文档中定义好定时器的行为。

2022-01-25 05:58 UTC, enkiller commented on src/timer.c
> -            need_schedule = RT_TRUE;
`_soft_timer_status` 变量去掉后，timer 线程被异常唤醒的问题，这个问题是咋解决的？

2022-01-25 18:32 UTC, mysterywolf commented
> 这次定时器修改后，需要在文档中定义好定时器的行为。

是的 这个在文档中心可以清楚的明确出来

2022-01-30 01:14 UTC, BernardXiong commented on src/timer.c
> -            need_schedule = RT_TRUE;
是的，这问题是怎么解决的？

2024-12-05 00:26 UTC, closed without merging