[bsp] stm32/stm32f407-atk-explorer add LLVM for Arm support.
RT-Thread/rt-thread pull request #5414
Opened 2021-12-22 10:37 UTC by Guozhanxin

## 拉取/合并请求描述：(PR description)

[
已在正点原子探索者开发板测试完成。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-12-22 13:22 UTC, Guozhanxin commented
满老师，你试一试，文件系统、网络都是好用的。

2021-12-22 14:32 UTC, mysterywolf requested changes

2021-12-22 14:32 UTC, mysterywolf commented on components/libc/compilers/gcc/partial/mips/SConscript
>      try:
请删除对此文件的修改

2021-12-22 14:32 UTC, mysterywolf commented on components/libc/compilers/gcc/partial/mips/sys/select.h
请删除对此文件的修改

2021-12-22 14:34 UTC, mysterywolf requested changes

2021-12-22 14:34 UTC, mysterywolf commented on bsp/stm32/stm32f407-atk-explorer/board/SConscript
> +if rtconfig.CROSS_TOOL == 'gcc' or rtconfig.CROSS_TOOL == 'clang':
clang可否有更好的名字，clang和armclang太相近了，很容易被人误解

2021-12-29 02:31 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/pull/5418

2022-01-13 11:55 UTC, enkiller commented
env 工具链中，携带了 LLVM 没？

2022-01-14 07:18 UTC, Guozhanxin commented
> env 工具链中，携带了 LLVM 没？

目前，windows版本的工具链好像还有点问题

2022-01-22 18:30 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/issues/5551
暂时先关闭，在此处统一整理，后续统一重新提交

2022-01-22 18:30 UTC, closed without merging