Improving Hooking method
RT-Thread/rt-thread pull request #5425
Opened 2021-12-23 23:25 UTC by GorgonMeducer

## 拉取/合并请求描述：(PR description)

[
过去的HOOK方式要么全开，要么全关，缺乏精细控制能力。同时，原有的HOOK方式在开启的状态下，强迫用户使用函数指针来进行HOOK。函数指针只在运行时刻需要动态修改HOOK内容时才有好处，其余时刻只会增大调用开销。实际上，大部分时候，HOOK的对象在编译时刻就已经确定了，因此强迫用户使用运行时刻的Hook方式是不妥的。
新的方式主体是“插入宏”，它允许用户精细的决定对应的HOOK究竟实现成什么形式。

以上内容在Cortex-M3 FVP上测试通过。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-12-27 12:52 UTC, Guozhanxin commented
system_view 测了，没啥影响
![1640609459(1)](https://user-images.githubusercontent.com/25633294/147473424-efca57e0-3c76-4f48-9086-ce42c83c2711.png)

2021-12-27 14:57 UTC, aozima commented on include/rtdef.h
> +#undef RT_OBJECT_HOOK_CALL
直接undef我记得有些编译器会报警告。

2021-12-27 21:29 UTC, GorgonMeducer commented on include/rtdef.h
> +#undef RT_OBJECT_HOOK_CALL
我已经根据你说的情况做了修改。但很好奇，哪些编译器会对直接undef进行报警？能列举一些么？

2021-12-29 17:37 UTC, BernardXiong commented
so strange code... Please let's discuss it.

2021-12-29 23:12 UTC, GorgonMeducer commented
Finger crossed

2021-12-30 03:54 UTC, BernardXiong commented
🤞

2021-12-30 16:17 UTC, BernardXiong commented
```c
/**
 * The hook function call macro
 */
#ifdef RT_USING_HOOK
#define RT_OBJECT_HOOK_CALL(func, argv)    __on_##func argv

#ifndef __on_rt_interrupt_enter_hook
#   define __on_rt_interrupt_enter_hook()                                       \
            do {                                                                \
                if ((rt_interrupt_enter_hook) != RT_NULL)                       \
                    rt_interrupt_enter_hook();                                  \
            } while (0)
#endif
#ifndef __on_rt_interrupt_leave_hook
#   define __on_rt_interrupt_leave_hook()                                       \
            do {                                                                \
                if ((rt_interrupt_leave_hook) != RT_NULL)                       \
                    rt_interrupt_leave_hook();                                  \
            } while (0)
#endif
#ifndef __on_rt_malloc_hook
#   define __on_rt_malloc_hook(addr, size)                                      \
            do {                                                                \
                if ((rt_malloc_hook) != RT_NULL)                                \
                    rt_malloc_hook(addr, size);                                 \
            } while (0)
#endif
#ifndef __on_rt_free_hook
#   define __on_rt_free_hook(rmem)                                              \
            do {                                                                \
                if ((rt_free_hook) != RT_NULL)                                  \
                    rt_free_hook(rmem);                                         \
            } while (0)
#endif
#ifndef __on_rt_object_trytake_hook
#   define __on_rt_object_trytake_hook(parent)                                  \
            do {                                                                \
                if ((rt_object_trytake_hook) != RT_NULL)                        \
                    rt_object_trytake_hook(parent);                             \
            } while (0)
#endif
#ifndef __on_rt_object_take_hook
#   define __on_rt_object_take_hook(parent)                                     \
            do {                                                                \
                if ((rt_object_take_hook) != RT_NULL)                           \
                    rt_object_take_hook(parent);                                \
            } while (0)
#endif
#ifndef __on_rt_object_put_hook
#   define __on_rt_object_put_hook(parent)                                      \
            do {                                                                \
                if ((rt_object_put_hook) != RT_NULL)                            \
                    rt_object_put_hook(parent);                                 \
            } while (0)
#endif
#ifndef __on_rt_scheduler_hook
#   define __on_rt_scheduler_hook(from, to)                                     \
            do {                                                                \
                if ((rt_scheduler_hook) != RT_NULL)                             \
                    rt_scheduler_hook(from, to);                                \
            } while (0)
#endif
#ifndef __on_rt_object_attach_hook
#   define __on_rt_object_attach_hook(obj)                                      \
            do {                                                                \
                if ((rt_object_attach_hook) != RT_NULL)                         \
                    rt_object_attach_hook(obj);                                 \
            } while (0)
#endif
#ifndef __on_rt_object_detach_hook
#   define __on_rt_object_detach_hook(obj)                                      \
            do {                                                                \
                if ((rt_object_detach_hook) != RT_NULL)                         \
                    rt_object_detach_hook(obj);                                 \
            } while (0)
#endif
#ifndef __on_rt_thread_inited_hook
#   define __on_rt_thread_inited_hook(thread)                                   \
            do {                                                                \
                if ((rt_thread_inited_hook) != RT_NULL)                         \
                    rt_thread_inited_hook(thread);                              \
            } while (0)
#endif
#ifndef __on_rt_thread_suspend_hook
#   define __on_rt_thread_suspend_hook(thread)                                  \
            do {                                                                \
                if ((rt_thread_suspend_hook) != RT_NULL)                        \
                    rt_thread_suspend_hook(thread);                             \
            } while (0)
#endif
#ifndef __on_rt_thread_resume_hook
#   define __on_rt_thread_resume_hook(thread)                                   \
            do {                                                                \
                if ((rt_thread_resume_hook) != RT_NULL)                         \
                    rt_thread_resume_hook(thread);                              \
            } while (0)
#endif
#ifndef __on_rt_timer_enter_hook
#   define __on_rt_timer_enter_hook(t)                                          \
            do {                                                                \
                if ((rt_timer_enter_hook) != RT_NULL)                           \
                    rt_timer_enter_hook(t);                                     \
            } while (0)
#endif
#ifndef __on_rt_timer_exit_hook
#   define __on_rt_timer_exit_hook(t)                                           \
            do {                                                                \
                if ((rt_timer_exit_hook) != RT_NULL)                            \
                    rt_timer_exit_hook(t);                                      \
            } while (0)
#endif
#else

#define RT_OBJECT_HOOK_CALL(func, argv)

#endif
```

One of implemention but not the best.

2021-12-30 17:48 UTC, GorgonMeducer commented
对宏的做了一些缩写。

2021-12-30 18:00 UTC, GorgonMeducer commented
又更进一步减少了53行，总计减少了123行。

2021-12-31 13:07 UTC, mysterywolf requested changes

2021-12-31 13:07 UTC, mysterywolf commented on include/rtdef.h
> +    #define __on_rt_interrupt_enter_hook()          __ON_HOOK_ARGS0(rt_interrupt_enter_hook)
![image](https://user-images.githubusercontent.com/34888354/147824983-2868b006-552f-4f88-addf-5fe48bfabcd3.png)

2021-12-31 13:56 UTC, GorgonMeducer commented on include/rtdef.h
> +    #define __on_rt_interrupt_enter_hook()          __ON_HOOK_ARGS0(rt_interrupt_enter_hook)
满头大汗……确实错了。已经解决

2021-12-31 15:37 UTC, mysterywolf approved these changes

2022-01-01 15:58 UTC, BernardXiong commented
```c
/**
 * The hook function call macro
 */
#ifndef RT_USING_HOOK
    #define __ON_HOOK_ARGS(__hook, argv)
    #define RT_OBJECT_HOOK_CALL(func, argv)
#else
    #define __ON_HOOK_ARGS(__hook, argv)            do {if ((__hook) != RT_NULL) __hook argv; } while (0)
    #define RT_OBJECT_HOOK_CALL(func, argv)         __on_##func argv
#endif

#ifndef __on_rt_interrupt_enter_hook
    #define __on_rt_interrupt_enter_hook()          __ON_HOOK_ARGS(rt_interrupt_enter_hook, ())
#endif
#ifndef __on_rt_interrupt_leave_hook
    #define __on_rt_interrupt_leave_hook()          __ON_HOOK_ARGS(rt_interrupt_leave_hook, ())
#endif
#ifndef __on_rt_interrupt_switch_hook
    #define __on_rt_interrupt_switch_hook()         __ON_HOOK_ARGS(rt_interrupt_switch_hook, ())
#endif
#ifndef __on_rt_malloc_hook
    #define __on_rt_malloc_hook(addr, size)         __ON_HOOK_ARGS(rt_malloc_hook, (addr, size))
#endif
#ifndef __on_rt_free_hook
    #define __on_rt_free_hook(rmem)                 __ON_HOOK_ARGS(rt_free_hook, (rmem))
#endif
#ifndef __on_rt_mp_alloc_hook
    #define __on_rt_mp_alloc_hook(mp, block)        __ON_HOOK_ARGS(rt_mp_alloc_hook, (mp, block))
#endif
#ifndef __on_rt_mp_free_hook
    #define __on_rt_mp_free_hook(mp, block)         __ON_HOOK_ARGS(rt_mp_free_hook, (mp, block))
#endif
#ifndef __on_rt_object_trytake_hook
    #define __on_rt_object_trytake_hook(parent)     __ON_HOOK_ARGS(rt_object_trytake_hook, (parent))
#endif
#ifndef __on_rt_object_take_hook
    #define __on_rt_object_take_hook(parent)        __ON_HOOK_ARGS(rt_object_take_hook, (parent))
#endif
#ifndef __on_rt_object_put_hook
    #define __on_rt_object_put_hook(parent)         __ON_HOOK_ARGS(rt_object_put_hook, (parent))
#endif
#ifndef __on_rt_scheduler_hook
    #define __on_rt_scheduler_hook(from, to)        __ON_HOOK_ARGS(rt_scheduler_hook, (from, to))
#endif
#ifndef __on_rt_scheduler_switch_hook
    #define __on_rt_scheduler_switch_hook(tid)      __ON_HOOK_ARGS(rt_scheduler_switch_hook, (tid))
#endif
#ifndef __on_rt_object_attach_hook
    #define __on_rt_object_attach_hook(obj)         __ON_HOOK_ARGS(rt_object_attach_hook, (obj))
#endif
#ifndef __on_rt_object_detach_hook
    #define __on_rt_object_detach_hook(obj)         __ON_HOOK_ARGS(rt_object_detach_hook, (obj))
#endif
#ifndef __on_rt_thread_inited_hook
    #define __on_rt_thread_inited_hook(thread)      __ON_HOOK_ARGS(rt_thread_inited_hook, (thread))
#endif
#ifndef __on_rt_thread_suspend_hook
    #define __on_rt_thread_suspend_hook(thread)     __ON_HOOK_ARGS(rt_thread_suspend_hook, (thread))
#endif
#ifndef __on_rt_thread_resume_hook
    #define __on_rt_thread_resume_hook(thread)      __ON_HOOK_ARGS(rt_thread_resume_hook, (thread))
#endif
#ifndef __on_rt_timer_enter_hook
    #define __on_rt_timer_enter_hook(t)             __ON_HOOK_ARGS(rt_timer_enter_hook, (t))
#endif
#ifndef __on_rt_timer_exit_hook
    #define __on_rt_timer_exit_hook(t)              __ON_HOOK_ARGS(rt_timer_exit_hook, (t))
#endif
```

Simplify the code as above way...

2022-01-01 16:24 UTC, closed without merging