Refresh using dma2d,screen refresh average 25fps
RT-Thread/rt-thread pull request #5426
Opened 2021-12-24 03:05 UTC by Rbb666

## 拉取/合并请求描述：(PR description)

[
   使用 DMA2D 外设 1/4面积来刷新屏幕，buffer 采用内部RAM，帧率达到平均25fps
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2021-12-24 03:23 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
> +    lv_disp_draw_buf_init(&disp_buf, lv_disp_buf1, 0x00, info.width * info.height / 4);
大佬，6666，这个地方为啥就用了一个buffer？

2021-12-24 03:29 UTC, Rbb666 commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
> +    lv_disp_draw_buf_init(&disp_buf, lv_disp_buf1, 0x00, info.width * info.height / 4);
我测试发现单buffer和双buffer效果差别不大，而且使用的是静态RAM，开两个buffer会导致RAM不够用

2021-12-24 03:32 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
> +    lv_disp_draw_buf_init(&disp_buf, lv_disp_buf1, 0x00, info.width * info.height / 4);
这个是一个demo，demo的内存空间可以469内部空间剩多少用多少，不必考虑给其他任务留下空间，到时候可以让用户自己去缩小空间，我们的demo保证最大性能。

2021-12-24 03:41 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
> +    lv_disp_draw_buf_init(&disp_buf, lv_disp_buf1, 0x00, info.width * info.height / 4);
另外，请看一下这个buffer的内存分配是否是必须的https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_lcd_mipi.c#L174
我建议跨过lcd驱动框架层，直接怼lvgl的底层接口。从qemu对接的经验来看，lcd驱动框架反倒拖慢了显示速度

2021-12-24 03:49 UTC, Rbb666 commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
> +    lv_disp_draw_buf_init(&disp_buf, lv_disp_buf1, 0x00, info.width * info.height / 4);
好的，我看一下

2021-12-24 04:30 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
> +    lv_disp_draw_buf_init(&disp_buf, lv_disp_buf1, 0x00, info.width * info.height / 4);
另外，LVGL那边这两天把代码改崩了，如果跑着跑着死机或者编译出错是正常的，这个pr可以先挂着晚两天再推进也可。我已经反馈给lvgl那边了。😂

2021-12-27 13:15 UTC, Guozhanxin approved these changes

2021-12-28 03:27 UTC, mysterywolf commented
@Rbb666 大佬可以继续搞了，我把软件包版本退回到8.1发布版了，底层移植不受影响。

2021-12-29 03:49 UTC, mysterywolf requested changes

2021-12-29 03:49 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
> +    #define LV_THREAD_PRIO (RT_THREAD_PRIORITY_MAX * 2 / 8)
此处不需要改

2021-12-29 03:49 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
> + * 2021-12-24     	Rb         Refresh using dma2d
注意一下缩进的问题

2021-12-29 06:02 UTC, nongxiaoming commented
其实这里不应该这样对接的，这里lvgl的buffer可以直接通过lcd的control函数拿到lcd的framebuffer给到lvgl，然后lvgl的这个flush函数直接调用lcd的control函数进行update操作就好了，这样针对lcd带有framebuffer的话可以节省内存，同时减少了一次数据拷贝，速度会非常的快。同时lvgl的这个刷新区域也直接传给control函数，里面根据参数可以进行局部刷新。但是对于mipi来说，刷新是很快的，所以是可以直接全部刷新的，因为局部刷新也会先给lcd发送指令设置刷新区域，会消耗时间，直接全部刷一屏还快

2021-12-29 07:54 UTC, mysterywolf commented
> 另外，请看一下这个buffer的内存分配是否是必须的https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_lcd_mipi.c#L174
我建议跨过lcd驱动框架层，直接怼lvgl的底层接口。从qemu对接的经验来看，lcd驱动框架反倒拖慢了显示速度

请忽略这句话

2022-01-12 20:15 UTC, mysterywolf commented
文件没了😂

2022-01-13 02:23 UTC, Rbb666 commented
> 文件没了😂

我重新提交了，现在好了 ：）

2022-01-13 02:48 UTC, mysterywolf approved these changes

2022-01-14 03:40 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
> +    rt_thread_startup(&lvgl_thread);
这个地方为啥要改呀，感觉之前的写法就可以呀

2022-01-14 03:40 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
> +static void lvgl_entry(void *parameter)
此处改的同下，没有实际意义吧

2022-01-14 03:45 UTC, Rbb666 commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
> +    rt_thread_startup(&lvgl_thread);
我测了一下，改成静态的线程帧率能提升1fps

2022-01-14 03:46 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
> +    rt_thread_startup(&lvgl_thread);
6666666666😂

2022-01-14 03:57 UTC, balanceTWK commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
> +    rt_thread_startup(&lvgl_thread);
线程栈放到片内内存了么？
这也可以提升速度？

2022-01-14 04:00 UTC, Rbb666 commented on bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
> +    rt_thread_startup(&lvgl_thread);
> 线程栈放到片内内存了么？ 这也可以提升速度？

是的，我测了一下片内比是比片外快一点

2022-01-14 14:51 UTC, merged