避免警告，变量可能未初始化就使用
RT-Thread/rt-thread pull request #5527
Opened 2022-01-15 04:56 UTC by diskwu

避免警告，变量dma_config,DMA_Handle可能未初始化就使用

2022-01-15 04:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=5527) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=5527) before we can accept your contribution.<br/><hr/>**diskwu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=5527) it.</sub>

2022-01-15 17:49 UTC, mysterywolf commented
请按照楼上的评论签署一下CLA

2022-01-16 17:26 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
> +    else
@Guozhanxin  郭老师是否需要 在上面
RT_ASSERT(serial != RT_NULL);
这句话后面增加一句
RT_ASSERT(flag == RT_DEVICE_FLAG_DMA_TX  || flag == RT_DEVICE_FLAG_DMA_RX);
两个文件均如此处理

2022-01-17 13:25 UTC, Guozhanxin commented on bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
> +    else
嗯，最好根据功能看下，需不需要加断言。

2022-01-17 13:25 UTC, Guozhanxin commented
这里会有警告吗

2022-01-17 22:54 UTC, diskwu commented
> 这里会有警告吗

警告有的，毕竟上面只有if，并没有else。但是实际使用中，不会走到else分支。

2022-01-20 06:15 UTC, mysterywolf requested changes
不用加else分支，请直接在

```
RT_ASSERT(serial != RT_NULL);
```

后面增加：

```suggestion
RT_ASSERT(flag == RT_DEVICE_FLAG_DMA_TX || flag == RT_DEVICE_FLAG_DMA_RX);
```

2022-01-20 08:05 UTC, Guozhanxin commented
是的，如果增加一个永远也执行不到的分支，也挺怪的。代码覆盖率也上不去

2022-01-20 12:28 UTC, diskwu commented
> RT_ASSERT(flag == RT_DEVICE_FLAG_DMA_TX || flag == RT_DEVICE_FLAG_DMA_RX);

![image](https://user-images.githubusercontent.com/4935081/150338511-cc2067df-e551-4c4a-af66-ccd104189f08.png)
不行，加了还是报警告。

另外的修改方法是，去掉后面的if，这样可以保证代码覆盖率。
![image](https://user-images.githubusercontent.com/4935081/150338700-d9ec428a-2e4d-4136-846d-a6565bc5b28b.png)

2022-01-20 13:19 UTC, mysterywolf commented
哦 我想起来了 keil有的时候也报，在-O2情况下会报这个问题

2022-01-20 13:20 UTC, mysterywolf commented
![image](https://user-images.githubusercontent.com/34888354/150346434-dda90206-5e54-4ebe-9b7c-21ac488ccb3e.png)
我觉得如图的这种修改方法可以
上面增加一个assert来判断flag的合法性
然后改成if else结构

2022-01-20 14:06 UTC, diskwu commented
> ![image](https://user-images.githubusercontent.com/34888354/150346434-dda90206-5e54-4ebe-9b7c-21ac488ccb3e.png) 我觉得如图的这种修改方法可以 上面增加一个assert来判断flag的合法性 然后改成if else结构

按这方法修改后重新提交。

2022-01-20 14:06 UTC, closed without merging