the support for PSE51
RT-Thread/rt-thread pull request #5534
Opened 2022-01-17 05:59 UTC by xiangxistu

## 拉取/合并请求描述：(PR description)

[
* tested base on gcc 10.2.1
* tested base on armclang

]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2022-01-17 06:04 UTC, mysterywolf requested changes

2022-01-17 06:04 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +        rt_timer_init(&timer->timer, timername, RT_NULL, RT_NULL, 0, RT_TIMER_FLAG_ONE_SHOT);
这个应该使用软定时器，不要默认放在中断里执行

2022-01-17 06:04 UTC, mysterywolf commented on components/libc/posix/Kconfig
> +    default n
select rtt的定时器宏 还有软件定时器宏

2022-01-17 06:05 UTC, xiangxistu commented on components/libc/posix/Kconfig
> +    default n
选用软件定时器这个宏，我们这个实现也是用得我们的软件定时器

2022-01-17 06:08 UTC, mysterywolf requested changes

2022-01-17 06:08 UTC, mysterywolf commented on components/libc/compilers/common/sys/signal.h
> +#include <sys/time.h>
应该是 #include "time.h"

2022-01-17 06:08 UTC, mysterywolf commented on components/libc/compilers/common/sys/time.h
> +struct itimerspec {
花括号的位置
{


}

2022-01-17 06:08 UTC, mysterywolf commented on components/libc/compilers/common/sys/time.h
> +#include <sys/signal.h>
#include "signal.h"

2022-01-17 06:10 UTC, mysterywolf commented on components/libc/posix/Kconfig
> +    default n
select RT_USING_TIMER_SOFT

2022-01-17 06:11 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +        rt_timer_init(&timer->timer, timername, RT_NULL, RT_NULL, 0, RT_TIMER_FLAG_ONE_SHOT);
RT_TIMER_FLAG_SOFT_TIMER

2022-01-17 06:11 UTC, xiangxistu commented on components/libc/compilers/common/sys/signal.h
> +#include <sys/time.h>
gcc 下可以，但是 keil 下就会缺失一些定义。

2022-01-17 06:13 UTC, mysterywolf commented on components/libc/compilers/common/sys/signal.h
> +#include <sys/time.h>
不可能的 这是同级引用 是"time.h" 不是 <time.h>

2022-01-17 06:19 UTC, xiangxistu commented on components/libc/compilers/common/sys/signal.h
> +#include <sys/time.h>
行吧，" ” 默认当前路径下先搜索。

2022-01-17 06:19 UTC, xiangxistu commented on components/libc/compilers/common/sys/time.h
> +#include <sys/signal.h>
OK

2022-01-17 06:47 UTC, mysterywolf requested changes

2022-01-17 06:47 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +        rt_timer_init(&timer->timer, timername, RT_NULL, RT_NULL, 0, RT_TIMER_FLAG_ONE_SHOT|RT_TIMER_FLAG_SOFT_TIMER);
| 左右有空格

2022-01-17 06:47 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +        rt_timer_init(&timer->timer, timername, rtthread_timer_wrapper, timer, 0, RT_TIMER_FLAG_ONE_SHOT|RT_TIMER_FLAG_SOFT_TIMER);
| 左右有空格

2022-01-17 06:47 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +        rt_timer_init(&timer->timer, timername, RT_NULL, RT_NULL, 0, RT_TIMER_FLAG_ONE_SHOT|RT_TIMER_FLAG_SOFT_TIMER);
我不太确定 你问问郭老师这个

2022-01-17 06:47 UTC, mysterywolf commented on components/libc/compilers/common/extension/sys/unistd.h
> +unsigned  alarm (unsigned __secs);
函数名字左边一个空格 右边没有空格

2022-01-17 07:51 UTC, mysterywolf commented on components/libc/compilers/common/extension/sys/unistd.h
> +unsigned  alarm (unsigned __secs);
格式这个问问郭老师吧

2022-01-17 12:51 UTC, Guozhanxin commented on components/libc/compilers/common/extension/sys/unistd.h
> +int pause (void);
后面不要加空格

2022-01-17 12:52 UTC, Guozhanxin commented on components/libc/compilers/common/extension/sys/unistd.h
> +long sysconf (int __name);
这里

2022-01-17 12:52 UTC, Guozhanxin commented on components/libc/compilers/common/sys/signal.h
> +int sigqueue (pid_t pid, int signo, const union sigval value);
还有这里

2022-01-17 12:55 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +    (timer->sigev_notify_function)(timer->val);
这里要加容错吧，断言或者判断下非空

2022-01-17 12:59 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +    timer->sigev_notify_function = evp->sigev_notify_function;
evp->sigev_notify_function 这个参数允许为空吗？如果不允许的话，开头要加参数检查

2022-01-17 13:02 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +        rt_timer_stop(&timer->timer);
这两行代码执行中间，如果被抢断，或者在中间的时候，timer时间到了，会有异常出现吗？

2022-01-17 13:06 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +            remaining = remaining - now;
remaining 这个要求是个负数吗？

2022-01-17 13:06 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +            remaining = remaining + (0xffffffff - now);
0xffffffff  这个值对于64位系统来说，是否一样适用

2022-01-17 13:09 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +        value->it_value.tv_nsec >= RT_TICK_PER_SECOND)
返回 EINVAL 错误，用户能得到这个信息吗？

2022-01-17 13:17 UTC, Guozhanxin commented on components/libc/posix-info.txt
> +- confstr()
这个文件不应该放在 posix目录下吗

2022-01-17 13:19 UTC, Guozhanxin commented on components/libc/posix/signal/posix_signal.c
> +int sigqueue (pid_t pid, int signo, const union sigval value)
函数和括号之间不要加空格

2022-01-17 13:20 UTC, Guozhanxin commented on include/rtdef.h
> +#define RT_TIMER_CTRL_GET_REMAIN_TIME   0x5             /**< get the remaining hang time */
这部分内核里的代码没提上来吗

2022-01-18 01:50 UTC, mysterywolf requested changes

2022-01-18 01:50 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +    rt_set_errno(-ENOSYS);
这个地方不应该是负的，返回值是负的 设置errno应为正值

2022-01-18 02:26 UTC, xiangxistu commented on include/rtdef.h
> +#define RT_TIMER_CTRL_GET_REMAIN_TIME   0x5             /**< get the remaining hang time */
提了，就新加了一个宏；都在这了

2022-01-18 02:27 UTC, xiangxistu commented on components/libc/posix-info.txt
> +- confstr()
这些函数包含 libc 的内容，所以就放在这里了

2022-01-18 03:28 UTC, xiangxistu commented on components/libc/compilers/common/time.c
> +    rt_set_errno(-ENOSYS);
errno 为正值，返回的值为负值。好的

2022-01-18 03:30 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +    rt_set_errno(-ENOSYS);
对的 返回值为负是-RT_Exxx, errno为正 是ENOSYS这种unix那边的，别返回-ENOSYS

2022-01-18 05:47 UTC, xiangxistu commented on components/libc/compilers/common/time.c
> +    (timer->sigev_notify_function)(timer->val);
加个非空吧，这里理论上不会出现这个状况

2022-01-18 06:02 UTC, mysterywolf requested changes

2022-01-18 06:02 UTC, mysterywolf commented on components/libc/compilers/common/sys/signal.h
> +  void     *ss_sp;    /* Stack base or pointer.  */
注意此处的括号
{


}

2022-01-18 06:10 UTC, xiangxistu commented on components/libc/compilers/common/time.c
> +        rt_timer_stop(&timer->timer);
不会有异常，这里不需要再加临界保护了；
这个规则相对松散，貌似函数的描述也没有具体描述这个问题；

2022-01-18 06:11 UTC, xiangxistu commented on components/libc/compilers/common/time.c
> +    (timer->sigev_notify_function)(timer->val);
还是非空好，应用层可以在删除定时器前先清空这个回调，会出现逻辑错误。

2022-01-18 06:47 UTC, xiangxistu commented on components/libc/compilers/common/time.c
> +            remaining = remaining - now;
本质上，remaining 就是 tick 的值，是一个正值，不应为负数。

这里的设计，是考虑到 rt_tick_t 溢出的问题。
-----
要不然，定义为 rt_uint32_t ，让编译器自己计算这里的差值。这样就不用考虑溢出的问题了，也不用怀疑 remianing 是否为负数。😁

2022-01-18 06:48 UTC, xiangxistu commented on components/libc/compilers/common/time.c
> +        value->it_value.tv_nsec >= RT_TICK_PER_SECOND)
这种写法也可以，不过和满老师商量过后，准备统一写成 rt_set_errno() 的形式。

2022-01-18 06:50 UTC, xiangxistu commented on components/libc/compilers/common/time.c
> +RTM_EXPORT(timer_gettime);
这个后续放在 example 中是否可行？

2022-01-18 12:14 UTC, Guozhanxin approved these changes

2022-01-18 15:18 UTC, mysterywolf commented on components/libc/compilers/common/sys/time.h
> -#ifdef RT_USING_POSIX_CLOCK
这个地方是timer用到了吗

2022-01-18 15:19 UTC, mysterywolf requested changes

2022-01-18 15:19 UTC, mysterywolf commented on components/libc/compilers/common/sys/time.h
> -#ifdef RT_USING_POSIX_CLOCK
#if defined(RT_USING_POSIX_CLOCK) || defined (RT_USING_POSIX_TIMER)

2022-01-18 15:29 UTC, mysterywolf requested changes

2022-01-18 15:29 UTC, mysterywolf commented on components/libc/compilers/common/time.c
> +    if (timer == NULL)
timer == RT_NULL || its == RT_NULL

2022-01-18 15:29 UTC, mysterywolf commented on components/libc/compilers/common/sys/signal.h
>  /* #define SIGUSR2     26 */
下个pr可以考虑把这个宏定义重新整理一下 各个编译器重复的太多了 有些乱套

2022-01-19 01:45 UTC, xiangxistu commented on components/libc/compilers/common/sys/time.h
> -#ifdef RT_USING_POSIX_CLOCK
这块是宏定义，是否能放开？
-----------
确实是 timer 用到了一些。

2022-01-19 01:48 UTC, xiangxistu commented on components/libc/compilers/common/sys/signal.h
>  /* #define SIGUSR2     26 */
有些信号类型，在 keil 或者 iar 下没有定义；
我增加的这些信号类型，是在 Linux 的 Test suite 里看到的常用的信号类型；看到 keil 与 iar 下缺失，就添上来了。

2022-01-19 01:57 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +    if (timer == NULL)
![image](https://user-images.githubusercontent.com/25633294/150049166-82b3f8b6-2536-481b-bb69-87a782166724.png)

2022-01-19 01:58 UTC, Guozhanxin commented on components/libc/compilers/common/time.c
> +    if (timer == NULL)
哦哦，看到了，这里的意思是，指针非法应该返回 EFAULT

2022-01-19 04:23 UTC, mysterywolf approved these changes

2022-01-19 05:00 UTC, mysterywolf requested changes

2022-01-19 05:00 UTC, mysterywolf commented on components/libc/compilers/common/extension/sys/unistd.h
> +extern char **environ;
这个环境变量我们貌似没有支持上，搞这么一个东西也没啥用的 建议删掉
现在getenv putenv这类的函数 在不同的编译器下使用都存在一些限制 我们还没有专门对环境变量这一块做出有效的统一和支持
环境变量这块极有可能需要与底层的非易失性存储设备配合才可以用。

2022-01-19 05:41 UTC, BernardXiong commented on components/libc/compilers/common/extension/sys/unistd.h
> +extern char **environ;
有用的啊，可以用的；不过不同的工具链，方式应该是不一样的

2022-01-19 05:43 UTC, mysterywolf commented on components/libc/compilers/common/extension/sys/unistd.h
> +extern char **environ;
是的 现在还没有统一 这个应该是放在编译器配平层里的 keil iar gcc下能用的函数 使用的方法都不一样

2022-01-19 06:36 UTC, xiangxistu commented on components/libc/compilers/common/extension/sys/unistd.h
> +extern char **environ;
郭老师的意思是，前期在 RAM 里用也行。
---------
要不然先保留一下

2022-01-19 07:20 UTC, mysterywolf commented on components/libc/compilers/common/extension/sys/unistd.h
> +extern char **environ;
我查了一下资料 
environ这个变量不应该在头文件中extern
这个是用户自己在所需的应用.c中自己extern
https://stackoverflow.com/questions/10649273/where-is-the-definition-of-extern-char-environ

![8489794359b1fdfc6a2214f4a9684f8](https://user-images.githubusercontent.com/34888354/150082884-7c753ff8-a488-45d2-bec1-fab5cb55a1bd.jpg)
![35e757ce350f09258188a004f942ce9](https://user-images.githubusercontent.com/34888354/150082900-f7755456-5ed3-4d3f-84f9-6b2b795aa6f9.jpg)

2022-01-20 02:14 UTC, mysterywolf approved these changes

2022-01-20 12:53 UTC, merged