[bsp/n32g45x] Add UART support and menuconfig.
RT-Thread/rt-thread pull request #5538
Opened 2022-01-18 09:10 UTC by Blues-Jiang

## 拉取/合并请求描述：(PR description)

[
1. Add UART 4/5/6/7 support. Add pin remap choice in kconfig file.
2. Add JTAG Port init function.
3. Fix bugs in rt_pwm.c. When enable pwm channel after initialization, there is a possibility that some pin configuration will be reset.
4. Fix bug in rt_adc.c: When enable ADC1_CH16 or ADC1_CH18, it cannot get the value correctly.
5. Add pin support of LQFP64/LQFP80/LQFP100/LQFP128. According to the datasheet of N32G45X, there are no package for LQFP144. Add define N32G45X_PIN_NUMBERS in menuconfig.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2022-01-19 09:34 UTC, Guozhanxin approved these changes

2022-01-19 09:35 UTC, Guozhanxin commented on bsp/n32g452xx/n32g452xx-mini-system/rtconfig.h
> +#define BSP_USING_TIM5_CH3
bsp默认需要开启这么多功能吗？

2022-01-19 09:35 UTC, Guozhanxin commented on bsp/n32g452xx/n32g452xx-mini-system/rtconfig.h
> +#define RT_USING_SIGNALS
感觉这里的选项可以少开一点，用户需要再自己开就行吧

2022-01-19 09:38 UTC, Blues-Jiang commented on bsp/n32g452xx/n32g452xx-mini-system/rtconfig.h
> +#define BSP_USING_TIM5_CH3
不用 不过kconfig里默认配置是对的 那我关掉一些默认不需要的

2022-01-20 01:52 UTC, mysterywolf requested changes
@Guozhanxin  郭老师，这个rtconfig.h得注意一下，之前遇到过一些bsp默认情况下呼啦啦开了一堆非必须的选项。这些硬件选项应该是做成BSP_USING_xxx 放在 Hardware Drivers Config中供用户选择，但是并非默认就选定，默认选定的一般只含有pin和uart

2022-01-20 01:52 UTC, mysterywolf commented on bsp/n32g452xx/n32g452xx-mini-system/rtconfig.h
> +#define RT_USING_I2C_BITOPS
这部分默认关闭，包括下面的adc pwm什么的也帮忙关闭一下 只开启gpio(pin) 和 终端所需的uart就可以了
RT_USING_I2C是RTT这边驱动框架的宏开关，在不开启bsp这边对应的i2c驱动的情况下，光开这么一个框架没有任何意义。

2022-01-20 01:52 UTC, mysterywolf commented on bsp/n32g452xx/n32g452xx-mini-system/rtconfig.h
> -#define RT_USING_MESSAGEQUEUE
这些需要开启，只是signal不用开

2022-01-20 02:00 UTC, Blues-Jiang commented on bsp/n32g452xx/n32g452xx-mini-system/rtconfig.h
> +#define RT_USING_I2C_BITOPS
我把.config删掉 重新生成了一下 都是按默认的了

2022-01-20 02:45 UTC, merged