add:air105 bsp
RT-Thread/rt-thread pull request #5607
Opened 2022-02-22 04:03 UTC by Dozingfiretruck

## 拉取/合并请求描述：(PR description)

[
提交air105 bsp 仅支持GCC环境开发
已在air105上进行过测试
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2022-02-22 04:06 UTC, mysterywolf commented
https://github.com/mysterywolf/formatting 请用这个把提交的代码扫描一遍，否则ci不会过

2022-02-22 04:11 UTC, mysterywolf reviewed
~~@Guozhanxin 郭老师看看呗，这个BSP只支持GCC，Keil IAR咋处理？~~

2022-02-22 04:11 UTC, mysterywolf commented on bsp/airm2m/air105/SConstruct
> +
如果只支持GCC的话这个地方是否还需要写，我不太清楚，让郭老师再看看吧

2022-02-22 04:11 UTC, mysterywolf commented on bsp/airm2m/air105/board/SConscript
> +    src += [startup_path_prefix + '/HAL_Driver/Startup/iar/startup_gcc.s']
此处是否需要保留

2022-02-22 04:11 UTC, mysterywolf commented on bsp/airm2m/air105/rtconfig.py
> +    POST_ACTION += 'python ./makesoc.py'
同上 是否需要删除掉

2022-02-22 04:41 UTC, mysterywolf commented on bsp/airm2m/air105/libraries/HAL_Driver/Inc/air105_dcmi.h
> +#define IS_DCMI_DMAREQUESTFIFO_SIZE(SIZE) (((SIZE) == DCMI_DMARequestFIFOSize_1Word) ||\
乱码了 
中文注释这一点需要注意，统一使用UTF-8编码 通过formatting脚本会自动转的 转完之后也要人工确认一下是否有乱码

2022-02-22 09:20 UTC, mysterywolf approved these changes

2022-02-22 09:41 UTC, BernardXiong commented
no bin no exe files, thanks.

2022-02-22 09:42 UTC, Dozingfiretruck commented
> no bin no exe files, thanks.

熊大，这两个是一定要有的，一个是下载工具一个是bl

2022-02-22 11:48 UTC, BernardXiong commented
> > no bin no exe files, thanks.
> 
> 熊大，这两个是一定要有的，一个是下载工具一个是bl

Please mention them in README.md.

2022-02-27 01:00 UTC, BernardXiong commented
请移除bin文件，exec文件，而在README.md中说明这部分的情况。

2022-02-27 05:08 UTC, Dozingfiretruck commented
> 请移除bin文件，exec文件，而在README.md中说明这部分的情况。

收到，已经移除了exe和bin

2022-02-27 14:05 UTC, BernardXiong commented
Please fix all of code with some `stm32` string. For example, `struct stm32_adc` in `airm2m/air105/libraries/rt_drivers/drv_adc.c`.

2022-02-27 14:39 UTC, Dozingfiretruck commented
> Please fix all of code with some `stm32` string. For example, `struct stm32_adc` in `airm2m/air105/libraries/rt_drivers/drv_adc.c`.

非常抱歉，之前按照stm32为范例制作adc未完成，此文件忘记删除，现已删除

2022-02-28 01:27 UTC, BernardXiong requested changes

2022-02-28 01:27 UTC, BernardXiong commented on bsp/airm2m/air105/board/board.h
> +
Please add license and your copyright information.

2022-02-28 01:35 UTC, Dozingfiretruck commented on bsp/airm2m/air105/board/board.h
> +
收到，已添加

2022-03-05 03:37 UTC, Dozingfiretruck commented
@BernardXiong 熊大，请问还有哪里是不合格的地方么😃

2022-03-07 04:07 UTC, BernardXiong approved these changes

2022-03-08 04:04 UTC, merged