[components][drivers][spi]: 基于SPI总线驱动框架添加模拟SPI总线扩展
RT-Thread/rt-thread pull request #5656
Opened 2022-03-10 08:09 UTC by kylepengchn

## 拉取/合并请求描述：(PR description)

[
基于SPI总线驱动框架添加模拟SPI总线扩展，已在GD32F303x系列MCU上验证，本次一并提供了drv_soft_spi驱动参考
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2022-03-10 08:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=5656) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=5656) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=5656) it.</sub>

2022-03-11 22:58 UTC, Guozhanxin commented
😄

2022-03-16 22:36 UTC, mysterywolf requested changes
请使用脚本 https://github.com/mysterywolf/formatting 对你提交的代码进行格式化扫描

2022-03-16 22:36 UTC, mysterywolf commented on bsp/gd32303e-eval/drivers/drv_soft_spi.c
> +#define GPIO_BIT_RESET(port, pin)         gpio_bit_reset(port, pin)
请不要含有#if0代码，保留最优解即可

2022-03-16 22:36 UTC, mysterywolf commented on bsp/gd32303e-eval/drivers/drv_soft_spi.c
> +#else /* 使用内联减少函数调用耗时 */
GD32有一部分外国人在用，尽量使用英文注释

2022-03-16 22:36 UTC, mysterywolf commented on bsp/gd32303e-eval/drivers/drv_soft_spi.c
> +//    }
这段代码如果是无用的 请删除，如果是示例，请用注释标明

2022-03-16 22:36 UTC, mysterywolf commented on bsp/gd32303e-eval/drivers/drv_soft_spi.h
> + */
该声明头部已过时，请参见https://github.com/RT-Thread/rt-thread/blob/master/components/libc/compilers/newlib/syscalls.c 复制一份声明头部

2022-03-21 06:40 UTC, mysterywolf approved these changes

2022-03-22 01:33 UTC, Guozhanxin approved these changes

2022-03-23 03:00 UTC, mysterywolf commented
请使用脚本 https://github.com/mysterywolf/formatting 对你提交的代码进行格式化扫描

2022-03-23 06:16 UTC, merged

2022-04-19 07:59 UTC, mysterywolf commented
可否有时间再提供一份stm32的SPI软件模拟驱动？
参见stm32 I2C 软件模拟驱动：
https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c