[update] add fal component.
RT-Thread/rt-thread pull request #5662
Opened 2022-03-11 05:59 UTC by liukangcc

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/coding_style_en.txt)

2022-03-11 06:11 UTC, mysterywolf commented
1. PKG_USING_FAL 应该改成 RT_USING_FAL了吧
2. FAL的版本号还需要保留吗？FAL_SW_VERSION
@armink 龙哥麻烦看一眼吧

2022-03-11 06:20 UTC, mysterywolf requested changes

2022-03-11 06:20 UTC, mysterywolf commented on components/fal/Kconfig
> +    select RT_USING_LIBC
这个RT_USING_LIBC需要干掉

2022-03-11 06:24 UTC, mysterywolf requested changes

2022-03-11 06:24 UTC, mysterywolf commented on components/fal/SConscript
> +LOCAL_CCFLAGS = ''
这个LOCAL_CCFLAGS可以删掉了

2022-03-11 06:24 UTC, mysterywolf commented on components/fal/SConscript
> +group = DefineGroup('Fal', src, depend = ['PKG_USING_FAL'], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)
PKG_USING_FAL -》 RT_USING_FAL

2022-03-11 06:24 UTC, mysterywolf commented on components/fal/inc/fal_def.h
> +#endif
此处可以删掉了

2022-03-11 06:24 UTC, mysterywolf commented on components/fal/inc/fal_def.h
> +#ifdef __RTTHREAD__ /* for RT-Thread platform */
这个#ifdef endif对可以删掉了，现在肯定是在rtthread环境下了

2022-03-11 06:24 UTC, mysterywolf commented on components/fal/inc/fal_def.h
> +#include <rtthread.h>
把这个头文件可以调整到上面去

2022-03-11 17:51 UTC, mysterywolf commented on bsp/nuvoton/numaker-pfm-m487/rtconfig.h
>  #define PKG_FAL_VER_NUM 0x99999
这两个东西其实已经没有意义了 不过也不用管 下次刷project的时候自己就没了

2022-03-11 17:53 UTC, mysterywolf requested changes

2022-03-11 17:53 UTC, mysterywolf commented on components/fal/Kconfig
> +    depends on RT_VER_NUM >= 0x40100
这里不需要加depends on，版本肯定是大于4.1.0的
是在pacakges仓库的Kconfig里加
depends on RT_VER_NUM < 0x40100

2022-03-12 01:30 UTC, armink commented
> AL的版本号还需要保留吗？FAL_SW_VERSION

是可以去掉的

2022-03-15 01:07 UTC, mysterywolf commented
FAL_SW_VERSION @liukangcc 版本号宏可以干掉了

2022-03-15 01:18 UTC, mysterywolf approved these changes

2022-03-15 01:48 UTC, merged