[bsp/stm32] select the input clk of spi based on SPI instances
RT-Thread/rt-thread pull request #5707
Opened 2022-03-24 13:14 UTC by blta

## 拉取/合并请求描述：(PR description)

[
1.在STM32F4上使用SPI2时发现CLK与设置的一直不一样，查看数据手册发现，SPI2使用APB1作为输入时钟
另外，我查看了STM32G，STM32F1, STM32F4, STM32L4, STM32H7发现SPI输入CLK是有规律的：
默认 SPI1, SPI4, SPI5挂在APB2上，一般是高速SPI；SPI2, SPI3挂在APB1上 ,一般属于低速SPI; SPI6(目前只在高系列H7上看到)挂到APB4上。STM32G0，STM32F比较特殊，只有一个APB。
2.另外为了兼容多个SPI 总线，根据spi_drv->config->Instance选择APB
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-03-25 16:47 UTC, mysterywolf commented
@Guozhanxin 郭老师请批准一下CI

2022-03-26 02:50 UTC, blta commented
[file_check.py 163 ERROR] [bsp/at32/Libraries/AT32_Std_Driver/AT32F4xx_StdPeriph_Driver/inc/at32f4xx_eth.h]: encoding not utf-8, please format it. 
这个好像不是我的提交导致的，中间新增提交不是检查过了吗？

2022-03-26 02:59 UTC, mysterywolf commented
恩是的 一会我处理一下

2022-03-26 03:24 UTC, mysterywolf requested changes

2022-03-26 03:24 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_spi.c
> +/* SPI2 and SPI3 on APB1 */
这几个注释缩进4个格 别顶格写

2022-03-26 03:34 UTC, blta commented on bsp/stm32/libraries/HAL_Drivers/drv_spi.c
> +/* SPI2 and SPI3 on APB1 */
好了

2022-04-06 03:28 UTC, Guozhanxin approved these changes

2022-04-11 09:33 UTC, merged

2022-04-25 04:50 UTC, mysterywolf commented
这个在L4中报错了 bsp: l475潘多拉
![1650862177(1)](https://user-images.githubusercontent.com/34888354/165022825-83bfa4e9-1af5-465e-b4c1-f9f52cb7ff4c.png)

2022-04-25 05:21 UTC, blta commented
@mysterywolf 我手上有这个board，上次因为st-link估计太低，没法下载测试，下午我再看下

2022-04-25 05:24 UTC, mysterywolf commented
也不用实际测试，主要是编译问题，只要编译过就没事，我测了。

2022-04-25 05:45 UTC, blta commented
我重新检测了L475的datasheet， 只有SP1, SP2，SPI3没有SPI4,SPI5
除了SPI1外，使用#ifdefine SPI# 先判断一下，我下午改一下，谢谢提醒！