[libcpu/aarch64] add gicv3 support and bsp/rockchip/rk3568
RT-Thread/rt-thread pull request #5722
Opened 2022-03-28 02:06 UTC by GuEe-GUI

## 拉取/合并请求描述：(PR description)

[
AArch64平台：
1.添加GICv3支持
2.不再限制只能从core0启动
3.添加rockchip/rk3568平台
4.完善QEMU-VIRT平台VIRTIO驱动框架以支持其他VIRTIO驱动实现。

主要针对GICv3支持，在rk3568物理平台、QEMU-VIRT平台验证通过。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-03-28 02:27 UTC, GuEe-GUI commented
@BernardXiong

2022-03-28 15:27 UTC, BernardXiong commented
Whether put it under v4.1.0? @mysterywolf

2022-03-28 22:26 UTC, mysterywolf commented on bsp/qemu-virt64-aarch64/driver/board.h
>   */
这块为啥删掉了

2022-03-29 01:23 UTC, GuEe-GUI commented on bsp/qemu-virt64-aarch64/driver/board.h
>   */
相关代码已移交至`bsp/qemu-virt64-aarch64/driver/virt.h`新文件中，在该文件中对此部分的修改记录已无效。

2022-03-29 01:41 UTC, mysterywolf commented
@Guozhanxin  郭老师麻烦review一下吧

2022-03-29 02:01 UTC, mysterywolf requested changes

2022-03-29 02:01 UTC, mysterywolf commented on bsp/rockchip/rk3568/rtconfig.h
> +
请确认文件系统是否需要开启，我没有看到文件系统相关的驱动代码，一般bsp只默认开启一路uart供终端显示，和GPIO即可。
如果想要整合sd卡等，可以参见这个https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/board/Kconfig#L87 默认为关闭，如果用户需要，一键可以开启所有需要的依赖项，不需要来回选来选去

2022-03-29 02:04 UTC, GuEe-GUI commented on bsp/rockchip/rk3568/rtconfig.h
> +
好的，尚不支持MMC驱动，将关闭相关选项

2022-03-29 02:24 UTC, mysterywolf approved these changes

2022-03-29 02:54 UTC, Guozhanxin commented
会不会影响之前 64位架构 bsp的稳定性呀？

2022-03-29 02:59 UTC, GuEe-GUI commented
> 会不会影响之前 64位架构 bsp的稳定性呀？

主要对支持GICv3的BSP有影响，目前只有QEMU-VIRT版本可选择支持GICv3，其余部分代码只是增加feature，目前其他BSP并未使用，不影响稳定性。

2022-03-29 03:07 UTC, Guozhanxin approved these changes

2022-03-29 03:08 UTC, merged