Fix some compilation warning
RT-Thread/rt-thread pull request #5744
Opened 2022-03-30 04:26 UTC by dongly

## 拉取/合并请求描述：(PR description)

[
### 修复 gcc 带参数 " -k" 编译出现一些警告 

* 编译环境: ARM GCC V10.2.1
* BSP: STM32F407
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-03-30 06:11 UTC, Guozhanxin commented on bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f4.c
> +                == HAL_OK)
这是什么规范，RT-Thread好像没有这种规范

2022-03-30 06:13 UTC, Guozhanxin commented on bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
> +    rt_int32_t i;
i的取值范围只有 0 ~ 32 有必要 32 位吗？

2022-03-30 09:18 UTC, dongly commented
格式化规范的问题已经解决,我自己定义的clang-format,不小心用在这了
(另,在vscode用astyle总觉得不顺手 :-) )

2022-03-30 14:02 UTC, mysterywolf commented
https://github.com/mysterywolf/formatting 用这个格式化 这个是专门设计给rtt格式化用的

2022-03-30 14:04 UTC, mysterywolf requested changes

2022-04-04 07:48 UTC, BernardXiong commented on components/drivers/serial/serial.c
> +    rt_uint8_t index;
这里是没必要的，对于32位处理器来说。一个寄存器是32位的，这里以8位操作，反而可能降低性能<需要看具体的指令情况>。

这里使用和芯片位宽一致的变量是比较合适的，针对这块是size_t或ssize_t（无符号和有符号）

2022-04-06 01:01 UTC, dongly commented
已更新

2022-04-29 21:01 UTC, mysterywolf commented
麻烦再 解决一下冲突 我们再review一下

2022-04-30 08:49 UTC, dongly commented
已更新

2022-07-07 02:13 UTC, dongly commented
冲突已经再次解决,请review @mysterywolf

2022-07-07 03:32 UTC, mysterywolf commented
请ping我的邮箱 [meco@rt-thread.org](mailto:meco@rt-thread.org) 我拉你进群

2022-07-30 19:09 UTC, mysterywolf commented
这份PR开会时再讨论一下细节，期望在4.1.1发布之前合进去 @Guozhanxin

2022-07-30 21:44 UTC, mysterywolf commented
@dongly 请再耐心等待一下，冲突的问题目前先不需要解决。

2022-08-02 02:16 UTC, Guozhanxin commented on bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c
> +    for (rt_size_t i = 0; i < sizeof(i2c_obj) / sizeof(struct stm32_i2c); i++)
这里为啥要合并起来呀，感觉可读性还不如之前

2022-08-02 02:19 UTC, Guozhanxin commented on components/dfs/filesystems/romfs/romfs.c
> +static const struct romfs_dirent _dummy[] =
这部分代码是脚本自动生成的，如果要修改，后面最好把tool目录下的脚本也修改了。要不然下次生成又被还原了。

2022-08-02 02:19 UTC, Guozhanxin commented on components/dfs/filesystems/romfs/romfs.c
> +static const struct romfs_dirent _dummy[] =
这就是下一个pr了

2022-08-02 02:41 UTC, mysterywolf commented on components/dfs/filesystems/romfs/romfs.c
> +static const struct romfs_dirent _dummy[] =
这块应该是要改一下脚本吧 脚本生成的有问题 确实应该是static关键字在前 const在后

2022-08-02 02:41 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c
> +    for (rt_size_t i = 0; i < sizeof(i2c_obj) / sizeof(struct stm32_i2c); i++)
节省一个内部变量

2022-08-02 16:09 UTC, merged

2022-08-02 16:19 UTC, mysterywolf commented on components/dfs/filesystems/romfs/romfs.c
> +static const struct romfs_dirent _dummy[] =
缺人了 脚本没啥问题