[dfs][romfs]支持相对地址模式
RT-Thread/rt-thread pull request #5768
Opened 2022-04-02 14:18 UTC by enkiller

## 拉取/合并请求描述：(PR description)

[
ROMFS 支持相对地址模式，相对地址与绝对地址自动适配
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-04-03 06:40 UTC, BernardXiong commented
Please provide more description.

2022-04-03 13:26 UTC, enkiller commented
> Please provide more description.

已经更新

ROMFS 打包时指定绝对地址，实际使用中有些不便，不能将一个 ROMFS.bin 在多个平台上进行使用。所以这块进行了调整

2022-04-04 07:41 UTC, BernardXiong commented
> > Please provide more description.
> 
> 已经更新
> 
> ROMFS 打包时指定绝对地址，实际使用中有些不便，不能将一个 ROMFS.bin 在多个平台上进行使用。所以这块进行了调整

打包的python脚本是否也需要更改？如果更改，需要提交更新（`tools/mkromfs.py`）。

2022-04-04 12:50 UTC, enkiller commented
> > > Please provide more description.
> > 
> > 
> > 已经更新
> > ROMFS 打包时指定绝对地址，实际使用中有些不便，不能将一个 ROMFS.bin 在多个平台上进行使用。所以这块进行了调整
> 
> 打包的python脚本是否也需要更改？如果更改，需要提交更新（`tools/mkromfs.py`）。

不需要更新打包脚本，打包脚本指定任意地址，都能运行

2022-04-06 02:38 UTC, Guozhanxin commented on components/dfs/filesystems/romfs/dfs_romfs.c
> +void *dfs_romfs_get(struct dfs_fd *file)
加了这样一个api，之前romfs的使用方式，会有影响吗？这个api怎么用呢，也没有注释说明

2022-04-06 02:39 UTC, Guozhanxin commented on components/dfs/filesystems/romfs/dfs_romfs.c
> +void *dfs_romfs_get(struct dfs_fd *file)
看起来这个api也是要开放给用户的。

2022-04-06 02:39 UTC, Guozhanxin requested changes
看下是不是需要修改

2022-04-06 03:11 UTC, enkiller commented on components/dfs/filesystems/romfs/dfs_romfs.c
> +void *dfs_romfs_get(struct dfs_fd *file)
romfs 特殊 API，获取文件的地址

之前的 romfs 不会有影响

2022-04-06 03:20 UTC, Guozhanxin approved these changes

2022-04-06 13:13 UTC, merged