[drivers][rtc] Adjust ops function input parameters
RT-Thread/rt-thread pull request #5772
Opened 2022-04-04 15:00 UTC by enkiller

## 拉取/合并请求描述：(PR description)

[
调整 RTC ops 参数，void * 形式不直观
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-04-04 20:00 UTC, mysterywolf requested changes
检查了一下 代码中没有混淆本地时间和UTC时间，但是需要修改两个细节：
1. 注释中UTC要大写
2. rtc.c/.h文件的头注释日志中请增加本次修改的描述

2022-04-05 01:44 UTC, iysheng commented on components/drivers/rtc/alarm.c
> +                if (sec_now == sec_alarm)
这个地方将之前用到的一个 RT_ALARM_DELAY 舍弃掉了，是否合适呢？

2022-04-05 03:00 UTC, enkiller commented on components/drivers/rtc/alarm.c
> +                if (sec_now == sec_alarm)
这个地方舍弃掉的原因是啥？

2022-04-05 05:01 UTC, zhangsz0516 approved these changes

2022-04-05 05:19 UTC, zhangsz0516 commented on components/drivers/rtc/alarm.c
> +                if (sec_now == sec_alarm)
影响不大，有了 RT_ALARM_DELAY，容易触发两次唤醒

2022-04-05 07:47 UTC, mysterywolf requested changes
注释中UTC要大写
rtc.c/.h文件的头注释日志中请增加本次修改的描述

2022-04-05 14:42 UTC, mysterywolf approved these changes

2022-04-06 02:26 UTC, merged