[kconfig] add 64bit default value for stack size. set tick HZ as 1000 by default
RT-Thread/rt-thread pull request #5778
Opened 2022-04-06 18:39 UTC by mysterywolf

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-04-07 01:44 UTC, Guozhanxin commented on components/libc/compilers/common/stdlib.c
> -    char *cmd = rt_strdup(command);
满老师，他之前这么写，肯定是有原因的。。。

2022-04-07 02:11 UTC, mysterywolf commented on components/libc/compilers/common/stdlib.c
> -    char *cmd = rt_strdup(command);
没原因，因为他就是我😂 这个函数是我加上去的 我验证了 没有问题的

2022-04-07 03:26 UTC, armink commented on src/Kconfig
> +    default 1000
这个改动比较赞同

2022-04-08 01:06 UTC, BernardXiong commented on include/rtthread.h
> +#ifdef RT_KSERVICE_USING_STDLIB_MEMXXX
MEMXXX, what does it mean? 很无厘头呐

2022-04-08 01:07 UTC, BernardXiong requested changes
请给出有意义的名称，而不是无厘头的定义。

2022-04-08 01:15 UTC, mysterywolf commented on include/rtthread.h
> +#ifdef RT_KSERVICE_USING_STDLIB_MEMXXX
RT_KSERVICE_USING_STDLIB_MEMORY? 谁帮忙起个好名字呀

2022-04-08 08:46 UTC, mysterywolf commented
改成了 RT_KSERVICE_USING_STDLIB_MEMORY

2022-04-08 16:40 UTC, merged