[simulator]fix gcc11.2 build error.
RT-Thread/rt-thread pull request #5791
Opened 2022-04-08 20:22 UTC by Guozhanxin

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-04-08 21:28 UTC, mysterywolf commented
我刚刚解决完gcc10的报错 这怎么还有gcc11？😱

2022-04-08 21:34 UTC, mysterywolf reviewed
我现在主要担心就是这两点

2022-04-08 21:34 UTC, mysterywolf commented on components/libc/compilers/newlib/SConscript
> -if rtconfig.PLATFORM == 'gcc':
这个可能会搞出问题来，因为在studio下面，不知道为什么，如果是自己增加工具链的话，明明使用的是newlib，但是却获取不到结果，newlib版本返回的是unknown

2022-04-08 21:34 UTC, mysterywolf commented on components/libc/compilers/common/SConscript
> +    group = DefineGroup('Compiler', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
if rtconfig.CPU != 'posix':
这个玩意是啥，能稍微科普一下嘛

2022-04-09 00:33 UTC, BernardXiong commented on components/libc/compilers/common/SConscript
> +    group = DefineGroup('Compiler', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
rtconfig.CPU是由rtconfig.py中设置的，linux下这个被设置成了`posix`

2022-04-09 03:07 UTC, mysterywolf commented on components/dfs/filesystems/elmfat/dfs_elm.c
> +#include <time.h>
这个不需要加

2022-04-11 03:06 UTC, Guozhanxin commented on components/dfs/filesystems/elmfat/dfs_elm.c
> +#include <time.h>
可是不加就报错了，或者下面的 <sys/time.h> 写死是用我们的libc目录下的，要不然找不到结构体定义 struct tm

2022-07-02 18:25 UTC, mysterywolf requested changes

2022-07-02 18:25 UTC, mysterywolf commented on bsp/simulator/drivers/sd_sim.c
> -#define DBG_LVL    DBG_INFO
此处没有必要修改

2022-07-02 18:27 UTC, mysterywolf commented
这个PR中的一部分内容可以在4.1.1中合并

2022-08-01 04:56 UTC, mysterywolf commented on components/libc/compilers/common/dirent.h
> +void           seekdir(DIR *d, off_t offset);
https://man7.org/linux/man-pages/man3/seekdir.3.html

2022-08-13 23:15 UTC, closed without merging

2022-08-13 23:15 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/pull/6209