uniform code writing-disable interrupt
RT-Thread/rt-thread pull request #5800
Opened 2022-04-11 08:47 UTC by thewon86

## 拉取/合并请求描述：(PR description)

[
将多处（bsp 中的除外）关中断级别统一使用相同的代码写法
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-04-11 17:46 UTC, mysterywolf approved these changes

2022-04-13 08:22 UTC, Guozhanxin commented
是不是用无符号的类型好一点呀？

2022-04-13 14:59 UTC, mysterywolf commented
> 是不是用无符号的类型好一点呀？应该都一样，反正也不会拿来做运算。。。

我们貌似一直都在用有符号的
![image](https://user-images.githubusercontent.com/34888354/163209965-cb9c8a27-4fd6-4de5-8d9c-3235d244c578.png)

2022-04-14 09:31 UTC, Guozhanxin commented on libcpu/arm/sep4020/cpu.c
> +    while (level)
这的修改好像没啥意义，level 这个返回值，本身的值好像不能作为是否已经关闭中断的判断依据。要看具体的移植实现。不知道这里这么写有什么意义。

2022-04-14 12:59 UTC, BernardXiong commented
都加个register？具体意义是？

2022-04-15 07:16 UTC, Guozhanxin commented
https://zhuanlan.zhihu.com/p/263575137

2022-04-15 09:11 UTC, BernardXiong commented
现代的编译器，基本上不用那么指定register关键字了，能用register的都会用。

2022-04-15 21:12 UTC, mysterywolf commented
如果加了register没有副作用，建议加上。不要为所有编译器背书，因为无法确定用户使用编译器的行为具体是什么样子的。保持底线思维：假设编译器是个傻子。libc这块已经吃过亏了，我们假设所有编译器的libc都好用，结果他们行为并不一致。。。

2022-04-16 03:27 UTC, BernardXiong commented
> 如果加了register没有副作用，建议加上。不要为所有编译器背书，因为无法确定用户使用编译器的行为具体是什么样子的。保持底线思维：假设编译器是个傻子。libc这块已经吃过亏了，我们假设所有编译器的libc都好用，结果他们行为并不一致。。。
> 
> 如果要去掉register，请整体移除，不要一半用register，一半不用register

如果是这样，建议移除掉。如果是要支持8位，16位芯片，可以考虑留着。

2022-04-16 05:41 UTC, mysterywolf commented
@thewon86 麻烦把所有的register关键字都干掉吧

2022-04-16 06:59 UTC, mysterywolf requested changes
还有多处register没有被移除掉，建议全局搜索一下

2022-04-16 06:59 UTC, mysterywolf commented on components/drivers/usb/usbdevice/class/rndis.c
> +        register rt_base_t level = rt_hw_interrupt_disable();
这个位置没有剔除干净

2022-04-16 06:59 UTC, mysterywolf commented on components/drivers/usb/usbdevice/class/rndis.c
> +        register rt_base_t level = rt_hw_interrupt_disable();
此处

2022-04-16 06:59 UTC, mysterywolf commented on components/vbus/vbus.c
> +            register rt_base_t level = rt_hw_interrupt_disable();
此处

2022-04-16 06:59 UTC, mysterywolf commented on components/vbus/watermark_queue.h
> +    register rt_base_t level;
此处

2022-04-16 06:59 UTC, mysterywolf commented on components/vbus/watermark_queue.h
> +    register rt_base_t level;
此处

2022-04-16 07:02 UTC, thewon86 commented on components/drivers/usb/usbdevice/class/rndis.c
> +        register rt_base_t level = rt_hw_interrupt_disable();
是，搜索多加了个分号，漏了

2022-04-16 07:02 UTC, mysterywolf approved these changes

2022-04-18 02:54 UTC, Guozhanxin approved these changes

2022-04-18 02:54 UTC, Guozhanxin commented
这样更改确实少了很多😀

2022-04-18 03:04 UTC, Guozhanxin commented on include/rtdebug.h
> +    rt_base_t level;                                                 \
这里有点细节问题，后面没对齐

2022-04-18 03:04 UTC, Guozhanxin commented on include/rtdebug.h
> +    rt_base_t level;                                                 \
这里有点细节问题，后面没对齐

2022-04-18 03:04 UTC, Guozhanxin commented on include/rtdebug.h
> +        rt_base_t level;                                             \
这里有点细节问题，后面没对齐

2022-04-20 02:57 UTC, mysterywolf approved these changes

2022-04-20 06:22 UTC, merged