[bsp/n32g45x] drv_spi.c中添加超时检测避免卡死
RT-Thread/rt-thread pull request #5820
Opened 2022-04-16 08:21 UTC by wolfJane

## 拉取/合并请求描述：(PR description)

[
在N32G45x的BSP中drv_spi.c中的spixfer函数，添加超时检测功能，避免读写数据中发生异常造成卡死现象。
本代码已有N32G455REL7芯片上测试通过。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-04-17 03:23 UTC, mysterywolf approved these changes

2022-04-18 02:02 UTC, Guozhanxin commented on bsp/n32g452xx/Libraries/rt_drivers/drv_spi.c
> +static int HAL_SPI_TransmitReceive(SPI_Module *hspi,
这个函数命名，感觉像是驱动库里的函数😅，这个文件是对接RTT的部分，所以是不是换个名字好一点。

2022-04-19 03:23 UTC, Guozhanxin requested changes
改下API名字吧

2022-04-19 03:37 UTC, mysterywolf commented
_spi_recv 这个名字怎么样 因为这是一个static函数 所以最好是前面有个_，根据rt-thread的命名规则，是小写+下划线的方式

2022-04-20 01:19 UTC, mysterywolf approved these changes

2022-04-20 01:20 UTC, mysterywolf commented
@Guozhanxin 请采用squash合并

2022-04-20 01:22 UTC, wolfJane commented
已完成函数名修改，变更为 _spi_recv

2022-04-20 02:28 UTC, Guozhanxin approved these changes

2022-04-20 02:28 UTC, merged