Decouple the addition of command line arguments
RT-Thread/rt-thread pull request #5848
Opened 2022-04-20 06:01 UTC by wugensheng-code

## 拉取/合并请求描述：(PR description)

[
原因:
scons附加的命令行参数散落在python文件各处,不是很清晰
方案:
新建一份python文件集中汇总命令行参数
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-04-20 06:19 UTC, mysterywolf requested changes

2022-04-20 06:19 UTC, mysterywolf commented on tools/options.py
> +#
Change Log 需要改一下

2022-04-20 06:19 UTC, mysterywolf commented on tools/options.py
> +                help = 'print verbose information during build')
加一个回车

2022-04-20 06:49 UTC, Guozhanxin commented on tools/options.py
> +                      action = 'store_true',
这些 action不在一个文件里也没关系吗

2022-04-20 06:49 UTC, Guozhanxin commented on tools/options.py
> +# File      : building.py
文件名不对

2022-04-20 06:55 UTC, wugensheng-code commented on tools/options.py
> +# File      : building.py
已修改

2022-04-20 06:55 UTC, wugensheng-code commented on tools/options.py
> +                      action = 'store_true',
我这里测试没问题

2022-04-20 06:58 UTC, wugensheng-code commented on tools/options.py
> +                      action = 'store_true',
在building.py里的PrepareBuilding函数中统一把options加入了

2022-04-21 06:39 UTC, Guozhanxin approved these changes

2022-04-21 20:34 UTC, mysterywolf approved these changes

2022-04-22 00:23 UTC, merged

2022-04-22 02:13 UTC, thewon86 commented
py 是OO编程思维，继承和进化的被破坏了。

2022-05-04 17:09 UTC, chenyingchun0312 commented
@wugensheng-code 你好，有关这次修改，我在测试dlmodule时，发现有点问题

编译时，有如下报错
```
scons: Reading SConscript files ...                                                                                                                    
AttributeError: Values instance has no attribute 'cleanlib':                                                                                           
  File "E:\02_community\03_RT-Thread\02_rt_thread\chenyingchun\dlmodule\rtthread-apps\SConstruct", line 56:                                            
    BuildApplication(app + '/' + app + '.mo', app +'/SConscript')                                                                                      
  File "E:\02_community\03_RT-Thread\02_rt_thread\chenyingchun\dlmodule\rtthread-apps\tools\ua.py", line 193:                                          
    objs = SConscript(SConscriptFile)                                                                                                                  
  File "D:\software\env_released_1.2.0\env\tools\ConEmu\ConEmu\..\..\..\tools\Python27\Lib\site-packages\scons\SCons\Script\SConscript.py", line 668:  
    return method(*args, **kw)                                                                                                                         
  File "D:\software\env_released_1.2.0\env\tools\ConEmu\ConEmu\..\..\..\tools\Python27\Lib\site-packages\scons\SCons\Script\SConscript.py", line 605:  
    return _SConscript(self.fs, *files, **subst_kw)                                                                                                    
  File "D:\software\env_released_1.2.0\env\tools\ConEmu\ConEmu\..\..\..\tools\Python27\Lib\site-packages\scons\SCons\Script\SConscript.py", line 286:  
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)                                                                              
  File "E:\02_community\03_RT-Thread\02_rt_thread\chenyingchun\dlmodule\rtthread-apps\hello\SConscript", line 7:                                       
    group = DefineGroup('', src, depend = [''], CPPPATH=CPPPATH)                                                                                       
  File "E:\02_community\03_RT-Thread\02_rt_thread\chenyingchun\rt-thread\tools\building.py", line 624:                                                 
    if GetOption('cleanlib') and os.path.exists(os.path.join(group['path'], GroupLibFullName(name, Env))):                                             
  File "D:\software\env_released_1.2.0\env\tools\ConEmu\ConEmu\..\..\..\tools\Python27\Lib\site-packages\scons\SCons\Script\Main.py", line 487:        
    return getattr(OptionsParser.values, name)                                                                                                         
  File "D:\software\env_released_1.2.0\env\tools\ConEmu\ConEmu\..\..\..\tools\Python27\Lib\site-packages\scons\SCons\Script\SConsOptions.py", line 118:
    return getattr(self.__dict__['__defaults__'], attr)                                                                                                
```

经过调查，发现是在building.py中，PrepareModuleBuilding 这个函数，之前的AddOption被删除了，添加上就可以正常编译，我不太清楚是直接使用你提供的新接口AddOptions来修复，还是直接在该文件中，加上AddOption更好一些，从结构上看，使用你新添加的接口可能会好一些，但是，你新添加的接口中，AddOption 有很多，可能会导致，本来不需要依赖的一些Option也被强制变得可以使用