add adc_get_vref
RT-Thread/rt-thread pull request #5988
Opened 2022-05-23 19:38 UTC by byte-me-stan

add stm32_adc_get_vref

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-05-25 01:56 UTC, mysterywolf requested changes

2022-05-25 01:56 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_adc.c
> +}
There should add a blank line between next function

2022-05-25 01:56 UTC, mysterywolf commented on components/drivers/include/drivers/adc.h
> +    RT_ADC_CMD_GET_VREF = RT_DEVICE_CTRL_BASE(ADC) + 4,
```suggestion
    RT_ADC_CMD_GET_VREF = RT_DEVICE_CTRL_BASE(ADC) + 4, /* get reference voltage */
```

2022-05-25 01:56 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +        result = adc->ops->get_vref(adc);
we cannot directly return the voltage value, the result is rt_err_t type.
```suggestion
    else if (cmd == RT_ADC_CMD_GET_VREF && adc->ops->get_vref && args)
    {
        rt_int16_t value;

        value= adc->ops->get_vref(adc);
        *((rt_int16_t*)args) = value;
        if (value == 0)
        {
            result = -RT_ENOSYS;
        }
        else
        {
            result = RT_EOK;
        }
```

2022-05-25 01:56 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +        vref = _adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, RT_NULL );
Use adc->ops->get_vref to instead.

2022-05-25 01:58 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +        result = adc->ops->get_vref(adc);
Please help me to add arg check in adc->ops->get_resolution branch

2022-05-25 02:01 UTC, mysterywolf requested changes

2022-05-25 02:01 UTC, mysterywolf commented on components/drivers/misc/adc.c
> -        voltage = value * REFER_VOLTAGE / (1 << resolution);
Need to change:
1. use _adc_control to instead dev->ops->get_resolution and dev->ops->convert, which can give you a clear error code.
2. need to fill in the `arg` parameter

2022-05-25 02:03 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +        result = adc->ops->get_vref(adc);
I think rt_int16_t , not rt_uint16_t or rt_uint32_t

2022-05-25 02:50 UTC, mysterywolf commented on components/drivers/include/drivers/adc.h
> +    RT_ADC_CMD_GET_VREF = RT_DEVICE_CTRL_BASE(ADC) + 4,
/* get the resolution in bits */

2022-05-25 02:52 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +        result = adc->ops->get_vref(adc);
all of the value of reference voltage changes from  rt_uint32_t to rt_int16_t

2022-05-25 03:22 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +        vref = _adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, RT_NULL );
if (_adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, &vref) != RT_EOK)
{
    return 0;
}

2022-05-25 03:27 UTC, mysterywolf commented on components/drivers/misc/adc.c
>          rt_uint8_t resolution = dev->ops->get_resolution(dev);
if (_adc_control((rt_device_t) dev, RT_ADC_CMD_GET_RESOLUTION , &xxxx) != RT_EOK)
{
return 0;
}

2022-05-28 17:10 UTC, mysterywolf requested changes

2022-05-28 17:10 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +    _adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, &vref);
Please check the error code

2022-05-28 22:08 UTC, mysterywolf requested changes
Please carefully crossing check with the file that I sent to you.

2022-05-28 22:08 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +    if(_adc_control((rt_device_t) dev, RT_ADC_CMD_GET_RESOLUTION, &resolution) != RT_EOK)
if blank space (  xxxx)

2022-05-28 22:08 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +   if( _adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, &vref) != RT_EOK)
```suggestion
   if ( _adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, &vref) != RT_EOK)
```

2022-05-28 22:08 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +    if(resolution != RT_NULL && vref != RT_NULL)
we don't need that if branch any more

2022-05-28 22:13 UTC, mysterywolf requested changes

2022-05-28 22:13 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +   if( _adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, &vref) != RT_EOK)
Please care about the format. 4 spaces rather than 3 spaces. if + a blank space + (

2022-05-28 22:18 UTC, mysterywolf requested changes
Please help me to add and delete these two lines

2022-05-28 22:18 UTC, mysterywolf commented on components/drivers/misc/adc.c
```suggestion
```

2022-05-28 22:18 UTC, mysterywolf commented on components/drivers/misc/adc.c
>  }
```suggestion
}

```

2022-05-28 22:54 UTC, mysterywolf requested changes

2022-05-28 22:54 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +       goto _voltage_exit;
3 spaces

2022-05-28 22:57 UTC, mysterywolf requested changes

2022-05-28 22:57 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +    /*get the convert bits*/
```suggestion
    /*get the resolution in bits*/
```

2022-05-28 22:57 UTC, mysterywolf commented on components/drivers/misc/adc.c
> +    if( _adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, &vref) != RT_EOK)
```suggestion
    if(_adc_control((rt_device_t) dev, RT_ADC_CMD_GET_VREF, &vref) != RT_EOK)
```

2022-05-28 23:08 UTC, mysterywolf approved these changes

2022-05-28 23:10 UTC, mysterywolf commented
请Squash合并

2022-05-29 02:20 UTC, Guozhanxin approved these changes

2022-05-29 02:22 UTC, merged