[bsp][stm32][drv_adc.c]: change the bsp name of 100ask to be consistent with other bsp and commit a bug for drv_adc,c
RT-Thread/rt-thread pull request #6068
Opened 2022-06-10 09:28 UTC by 100ask-Alen

## 拉取/合并请求描述：(PR description)

[
1. 修改了下100ask的bsp的名字和stm32的其它bsp保持一致；
2. 在测试adc的时候发现drv_adc.c中关于采样有效位的判定使用的是ADC_HandleTypeDef中的成员Resolution，但是我观察了STM32的HAL库文件，这个结构体中好像都没有这个成员，实际上是放到了ADC_InitTypeDef这个结构体中的；
3. 另外，对于STM32F1系列和STM32F3系列的HAL库，ADC_InitTypeDef或者ADC_HandleTypeDef结构体均没有Resolution这个成员，这两个系列的ADC采样位数都是只有12bit一个选项，所以我将其单独列出来直接return 12;
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-06-10 15:59 UTC, mysterywolf commented
麻烦在这里也增加一下 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/README.md

2022-06-13 16:54 UTC, mysterywolf requested changes

2022-06-13 16:54 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_adc.c
> +    ADC_InitTypeDef *stm32_adc_handler;
![1655139166551](https://user-images.githubusercontent.com/34888354/173405212-0e1e99df-ef9a-4279-9345-ed7db871d1c5.png)
这个位置 在L4下报错 ， F1是没有这个结构体嘛

2022-06-13 16:58 UTC, mysterywolf requested changes
尝试一下这样改？

2022-06-13 16:58 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_adc.c
>      stm32_adc_handler = device->parent.user_data;
```suggestion

```

2022-06-13 16:58 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_adc.c
> +    ADC_InitTypeDef *stm32_adc_handler;
```suggestion
#ifdef SOC_SERIES_STM32F1 || SOC_SERIES_STM32F3
    ADC_HandleTypeDef *stm32_adc_handler = = device->parent.user_data;
#endif
```

2022-06-13 17:04 UTC, mysterywolf commented
你直接用我的这份代码看看, 帮你改好了：
```c
static rt_uint8_t stm32_adc_get_resolution(struct rt_adc_device *device)
{
#if defined(SOC_SERIES_STM32F1) || defined(SOC_SERIES_STM32F3)
    return 12;
#else
    ADC_HandleTypeDef *stm32_adc_handler = device->parent.user_data;

    RT_ASSERT(device != RT_NULL);

    switch(stm32_adc_handler->Init.Resolution)
    {
        case ADC_RESOLUTION_12B:
            return 12;
        case ADC_RESOLUTION_10B:
            return 10;
        case ADC_RESOLUTION_8B:
            return 8;
        case ADC_RESOLUTION_6B:
            return 6;
        default:
            return 0;
    }
#endif /* defined(SOC_SERIES_STM32F1) || defined(SOC_SERIES_STM32F3) */
}
```

2022-06-13 23:35 UTC, 100ask-Alen commented
> 你直接用我的这份代码看看, 帮你改好了：
> 
> ```c
> static rt_uint8_t stm32_adc_get_resolution(struct rt_adc_device *device)
> {
> #if defined(SOC_SERIES_STM32F1) || defined(SOC_SERIES_STM32F3)
>     return 12;
> #else
>     ADC_HandleTypeDef *stm32_adc_handler = device->parent.user_data;
> 
>     RT_ASSERT(device != RT_NULL);
> 
>     switch(stm32_adc_handler->Init.Resolution)
>     {
>         case ADC_RESOLUTION_12B:
>             return 12;
>         case ADC_RESOLUTION_10B:
>             return 10;
>         case ADC_RESOLUTION_8B:
>             return 8;
>         case ADC_RESOLUTION_6B:
>             return 6;
>         default:
>             return 0;
>     }
> #endif /* defined(SOC_SERIES_STM32F1) || defined(SOC_SERIES_STM32F3) */
> }
> ```

确认了下，F1和F3的ADC_InitTypeDef中是没有Resolution这个成员的，其它处理器都有。L1下编译不过应该是语法错误了。已经按照建议修改代码上传了。

2022-06-14 02:31 UTC, mysterywolf approved these changes

2022-06-14 06:13 UTC, Guozhanxin approved these changes

2022-06-14 06:17 UTC, merged