添加HC32F460系列RTC外设驱动
RT-Thread/rt-thread pull request #6069
Opened 2022-06-10 15:05 UTC by xiaoxiaolisunny

## 拉取/合并请求描述：(PR description)

[
【ev_hc32f460_lqfp100_v2】BSP中添加RTC驱动。
1.hc32\libraries\hc32_drivers中添加drv_rtc.c文件；
2.修改hc32\libraries\hc32_drivers中sconscript文件；
3.修改board文件夹下Kconfig文件，增加RTC选项；
本次PR代码已在ev_hc32f460_lqfp100_v2开发板测试通过。
![image](https://user-images.githubusercontent.com/88809599/173093012-c78c0b3b-7be0-4830-89e0-588d0b6110e7.png)

]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-06-10 15:18 UTC, mysterywolf requested changes

2022-06-10 15:18 UTC, mysterywolf commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +    }
https://github.com/RT-Thread/rt-thread/pull/6012 这个位置参见这个pr改一下gmtime不是线程安全函数

2022-06-11 05:49 UTC, xiaoxiaolisunny commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +    }
比较奇怪，换成gmtime_r后，时间也能设置成功，但是设置为立马会重启，或者hardfault。暂时还未找出来问题

2022-06-11 06:10 UTC, mysterywolf commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +    }
那就先合并这个吧

2022-06-11 06:10 UTC, mysterywolf approved these changes

2022-06-12 22:18 UTC, mysterywolf approved these changes

2022-06-13 02:11 UTC, JamieTx commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +#include <drivers/adc.h>
这里不需要包含这个头文件。

2022-06-13 02:20 UTC, JamieTx commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +    tm_new.tm_mday = stcRtcDate.u8Day + 1;
参考下time_t结构变量的取值范围。

2022-06-13 02:21 UTC, JamieTx commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +    stcRtcDate.u8Day     = p_tm->tm_mday + 1;
参考下time_t结构变量的取值范围。

2022-06-13 07:38 UTC, xiaoxiaolisunny commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +    stcRtcDate.u8Day     = p_tm->tm_mday + 1;
已修改

2022-06-13 08:27 UTC, JamieTx commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
>      stcRtcDate.u8Weekday = p_tm.tm_wday + 1;
这里不需要+1

2022-06-13 08:45 UTC, JamieTx commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +            stcRtcInit.u8IntPeriod    = RTC_INT_PERIOD_PER_SEC;
不需要配周期中断，虽然中断没有开不会产生实际中断

2022-06-13 09:27 UTC, xiaoxiaolisunny commented on bsp/hc32/libraries/hc32_drivers/drv_rtc.c
> +            stcRtcInit.u8IntPeriod    = RTC_INT_PERIOD_PER_SEC;
已修改

2022-06-13 16:47 UTC, mysterywolf commented
请解决一下冲突

2022-06-14 11:06 UTC, JamieTx commented
+1

2022-06-15 02:38 UTC, merged