[compoenets][driver][usb] fix usbhost hid issues.
RT-Thread/rt-thread pull request #6116
Opened 2022-06-28 03:00 UTC by Dengguiling

1.Set idle function should receive an empty package.
2.Fix uinst_t reference error in hid enable function.

Signed-off-by: dengguiling <greens9@163.com>

## 拉取/合并请求描述：(PR description)

[
近日在RT-Thread上调试USB鼠标时，发现以下问题：
1.通过USB抓包PC连接鼠标，以及查询USB HID相关资料，发现HID set idle时，发送setup之后，Host需要接收一个空包。
[HID协议SET_IDLE请求的解释说明](http://www.usbzh.com/article/detail-825.html)

2.rt_usbh_hid_enable()函数里面，调用rt_usb_hcd_alloc_pipe()的传参存在错误，应为intf->device。
在mass.c中发现有正确使用，猜测为以前重构遗留问题。[mass.c#L572](https://github.com/RT-Thread/rt-thread/blob/2a8e92b8ee8bfe3b6984603cd8a2c444dc4d3039/components/drivers/usb/usbhost/class/mass.c#L572)

测试：在与STM32F4相同USB IP的开发板上测试，且修改问题比较简单，相关资料和抓包也佐证了修改。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-06-28 03:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6116) it.</sub>

2022-06-28 03:21 UTC, mysterywolf requested changes

2022-06-28 03:21 UTC, mysterywolf commented on components/drivers/usb/usbhost/class/hid.c
> +            return RT_EOK;
这个地方的缩进有问题

2022-06-28 04:30 UTC, Dengguiling commented
已使用formatting工具对hid.c进行检查，并重新上传。麻烦查看一下缩进问题是否有解决，如果问题还存在的话，麻烦告知一下如何更好地解决这个问题，谢谢。

2022-07-04 02:46 UTC, Guozhanxin approved these changes

2022-07-07 08:10 UTC, merged