Docking lvgl for stm32f469-st-disco bsp using ft6336 touch chip
RT-Thread/rt-thread pull request #6121
Opened 2022-06-29 05:45 UTC by solar-li

## 拉取/合并请求描述：(PR description)

[
由于stm32f469-st-disco这款bsp有两种触摸芯片(ft6206和ft6336)，本次主要是为其对接ft6336的驱动，并且将ft6336的bsp对接到lvgl，再者就是目前在对接lvgl大部分bsp中，都将touch驱动塞在bsp的ports目录，这个应该是rtt touch框架没有出来前的实现方法，现在touch框架已经相对比较完善，并且大部分触摸驱动都有相应的软件包做支持，所以本次我对lvgl对接触摸芯片的主要实现方法就是对接软件包，这样可能会使源码变得更加整洁。

本功能已在对应的bsp完成测试

触摸驱动测试：

![image](https://user-images.githubusercontent.com/64183082/176358714-f01f6584-d01e-48af-9dda-b370fd5038b7.png)

LVGl测试：

https://user-images.githubusercontent.com/64183082/176360281-c9d81e6d-f808-4185-b816-39aeebcd90d8.mp4

]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-06-29 06:02 UTC, mysterywolf requested changes

2022-06-29 06:02 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/board/ports/touch/SConscript
>  CPPPATH = [cwd, str(Dir('#'))]
```suggestion
CPPPATH = [cwd]
```

2022-06-29 06:02 UTC, mysterywolf approved these changes

2022-06-29 06:08 UTC, mysterywolf approved these changes

2022-06-29 18:12 UTC, mysterywolf requested changes

2022-06-29 18:12 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/board/Kconfig
> +            endchoice
把这个选项放在BSP_USING_TOUCH下边吧

2022-06-29 18:15 UTC, mysterywolf commented on bsp/stm32/stm32f469-st-disco/board/Kconfig
> +            endchoice
BSP_USING_TOUCH里边是两个选项，BSP_USING_TOUCH_FT6X36或者BSP_USING_TOUCH_FT6206，这两个选项里边select软件包什么的

2022-06-30 02:23 UTC, mysterywolf approved these changes

2022-06-30 02:25 UTC, Guozhanxin approved these changes

2022-06-30 02:27 UTC, merged