[bsp][essemi] Adapt es32f369x for RTduino
RT-Thread/rt-thread pull request #6144
Opened 2022-07-06 07:18 UTC by a876565

## 拉取/合并请求描述：(PR description)

[
为ES32F369X BSP添加了RTduino的支持，目前支持GPIO、PWM、I2C、SPI、串口等功能
按照RTduino的要求添加了applications/arduino_main.cpp和applications/arduino_pinout
arduino_main.cpp中包含一系列的宏定义用于测试各项功能
在keil下和RT-Thread Studio下已经测试编译通过，功能正常
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-07-06 07:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6144) it.</sub>

2022-07-06 08:07 UTC, mysterywolf commented
你好，感谢贡献RTduino适配PR。

RTduino目前还差SPI目前我还没有调试完毕（因为我现在搞到一个SPI传感器很费劲），你已经测试成功啦？
有什么问题也欢迎向RTduino仓库提交PR https://github.com/RTduino/RTduino

2022-07-06 08:08 UTC, mysterywolf approved these changes

2022-07-06 12:31 UTC, mysterywolf requested changes

2022-07-06 12:31 UTC, mysterywolf commented on bsp/essemi/es32f369x/applications/arduino_pinout/pins_arduino.c
> +
pinout映射表必须是从0开始连续的，不可以跳着的

2022-07-06 12:31 UTC, mysterywolf commented on bsp/essemi/es32f369x/applications/arduino_main.cpp
> + * 2021-12-10     Meco Man     first version
请修改为正确的人名，这个文件很显然不是我写的😂

arduino_main.cpp 请保持简单，参见 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/applications/arduino_main.cpp
闪烁一颗与main.c中不同的LED

这个文件建议在arduino_pinout文件夹中创建一个example文件夹，放进去，不需要将Sconscript脚本指向这个example文件夹，用户需要可以手动参考。

2022-07-07 02:31 UTC, mysterywolf approved these changes

2022-07-07 03:31 UTC, mysterywolf commented on bsp/essemi/es32f369x/drivers/drv_i2c.c
> +    //LOG_E("send stop condition\n");
这个地方可以考虑改成LOG_D

2022-07-07 03:32 UTC, mysterywolf commented
请ping我的邮箱 meco@rt-thread.org 我拉你进群

2022-07-08 05:52 UTC, Guozhanxin approved these changes

2022-07-08 05:53 UTC, merged