[bsp/raspi3-32] fix some bug of funtion '__rt_ffs'
RT-Thread/rt-thread pull request #6170
Opened 2022-07-16 08:40 UTC by hipeanut

## 拉取/合并请求描述：(PR description)

[
    树莓派3B中的__rtt_ffs接口存在问题，导致寻找最高优先级线程不对。
    demo板代码中最高优先级线程main_thread_entry的优先级为10，但是该接口获取highest_ready_priority为9。
    启动时优先级为9的线程队列为空，导致代码跑飞报undefined instruction 异常。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-07-16 08:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6170) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6170) it.</sub>

2022-07-16 09:19 UTC, hipeanut commented
/check-cla

2022-07-20 03:16 UTC, pinxue requested changes
根据 src/kservice.c, __rt_ffs(0) 应返回 0，这里并没有使用处理器的专门指令，因此没必要重新实现一次，直接用 kservice.c 里的为宜。

2022-07-20 03:55 UTC, whj4674672 commented
当前 PR 当传入参数是 `0` 的时候，返回的结果为 `31`. 并不符合预期。这里可能需要顺手再修一下。

2022-07-20 03:59 UTC, whj4674672 commented
> 根据 src/kservice.c, __rt_ffs(0) 应返回 0，这里并没有使用处理器的专门指令，因此没必要重新实现一次，直接用 kservice.c 里的为宜。

在 RT-THREAD 中支持 `RT_USING_CPU_FFS` 当开启这个宏之后，可以使用 BSP 或者用户自己的 FFS ，这个 BSP 里面的 ffs 实现是可以节省一些 ROM 空间的

2022-07-23 14:08 UTC, hipeanut commented
感谢大佬们意见 传入为0确实没考虑到这里 我顺手再改一下

2022-07-23 14:08 UTC, closed without merging