Improve the connection of RTdunio PWM(stm32f401-st-nucleo)
RT-Thread/rt-thread pull request #6192
Opened 2022-07-26 05:19 UTC by liYony

## 拉取/合并请求描述：(PR description)

[
完善RTdunio的PWM部分的对接，并且在README.md文件中添加注意事项。所有PWM已经在BSP上完成测试。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-07-26 15:54 UTC, mysterywolf requested changes

2022-07-26 15:54 UTC, mysterywolf commented on bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md
> +| 11 (D11)        | PA7           | 是     | PWM反相位（定时器1发生） |
这个位置不用提反相位

2022-07-26 15:54 UTC, mysterywolf commented on bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md
> +> 4. D11引脚是PWM反相位引脚(也就是常说的互补输出引脚CHxN)。这里不用考虑到占空比互补问题（CHx-20%，CHxN-80%），直接正常使用就行。
```suggestion
> 4. D11引脚是PWM反相位引脚(也就是常说的互补输出引脚CHxN)。但是这里不用考虑到占空比互补问题（CHx-20%，CHxN-80%），直接正常使用即可。
```

2022-07-26 16:06 UTC, mysterywolf requested changes

2022-07-26 16:06 UTC, mysterywolf commented on bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md
> +| 11 (D11)        | PA7           | 是     | PWM反相位（定时器1发生） |
```suggestion
| 11 (D11)        | PA7           | 是     | PWM（定时器1发生） |
```

2022-07-26 16:06 UTC, mysterywolf approved these changes

2022-07-27 03:43 UTC, Guozhanxin approved these changes

2022-07-27 03:44 UTC, merged