[bsp/qemu-virt64-aarch64] Update drivers' code
RT-Thread/rt-thread pull request #6194
Opened 2022-07-27 08:24 UTC by GuEe-GUI

## 拉取/合并请求描述：(PR description)

[
1.RTC补充硬件alarm功能。
2.VirtIO-GPU修复因cpu乱序执行导致buffer没有正确初始化的问题。
3.VirtIO-NET修改发送网络包时包分离代码，防止丢失包数据；更新代码到VirtIO v1.0版本；支持tap模式访问外网。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-07-28 08:58 UTC, Guozhanxin approved these changes

2022-07-30 01:29 UTC, GuEe-GUI commented
@mysterywolf 请问这K210一直失败咋处理呀？

2022-07-30 01:58 UTC, mysterywolf commented
Hi, 这个问题不用理，这个是我的问题，已经修复好了

2022-07-30 01:59 UTC, mysterywolf requested changes

2022-07-30 01:59 UTC, mysterywolf commented on bsp/qemu-virt64-aarch64/driver/drv_rtc.c
> +    return RT_EINVAL;
如果是rtt的错误码的话，除了RT_EOK，剩下的都需要返回负数例如：-RT_EINVAL
请仔细检查一下这个pr，以及该bsp其他类似的问题。

2022-07-30 02:07 UTC, GuEe-GUI commented on bsp/qemu-virt64-aarch64/driver/drv_rtc.c
> +    return RT_EINVAL;
已修改

2022-07-30 02:10 UTC, mysterywolf commented on bsp/qemu-virt64-aarch64/driver/drv_rtc.c
> +    return RT_EINVAL;
感谢

2022-07-30 02:10 UTC, mysterywolf approved these changes

2022-07-30 06:04 UTC, merged