Esp32 C3 UART driver
RT-Thread/rt-thread pull request #6214
Opened 2022-08-03 08:45 UTC by tangzz98

## 拉取/合并请求描述：(PR description)

[
添加ESP32_C3 UART驱动，msh可以正常运行
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-08-03 08:51 UTC, tangzz98 commented
#5941

2022-08-03 09:02 UTC, supperthomas requested changes

2022-08-03 09:02 UTC, supperthomas commented on bsp/ESP32_C3/main/drv_uart.c
> + */
please add author name

2022-08-03 09:02 UTC, supperthomas commented on bsp/ESP32_C3/main/drv_uart.h
> + * SPDX-License-Identifier: Apache-2.0
add author name

2022-08-03 09:02 UTC, supperthomas commented on bsp/ESP32_C3/rtconfig.h
> +#define RT_USING_FINSH
please add . config file changes for menuconfig.

2022-08-03 12:57 UTC, supperthomas requested changes

2022-08-03 12:57 UTC, supperthomas commented on bsp/ESP32_C3/sdkconfig
>  #
readme.md  里面把IDF仓库整理一下，可以改patch，如果patch太大，可以换成仓库地址，直接让开发者自己去下载。

2022-08-04 06:23 UTC, supperthomas requested changes

2022-08-04 06:23 UTC, supperthomas commented on bsp/ESP32_C3/main/drv_uart.c
> + * 2022-06-03     tangzz98     first version
6.3?

2022-08-04 07:27 UTC, supperthomas approved these changes

2022-08-04 15:35 UTC, mysterywolf requested changes

2022-08-04 15:35 UTC, mysterywolf commented on bsp/ESP32_C3/main/board.c
> +    rt_hw_uart_init();
串口初始化应该是放在rt_hw_board_init里边的，可以看一下stm32 的 board.c

2022-08-05 08:39 UTC, tangzz98 commented on bsp/ESP32_C3/main/board.c
> +    rt_hw_uart_init();
串口初始化用INIT_BOARD_EXPORT(rt_hw_uart_init)标记了，在rt_hw_board_init->rt_components_board_init里面调用。编译以后发现如果不在代码里直接调用这个函数，它就被编译器优化掉了，不在最后生成的镜像里。所以把它放在rt_system_scheduler_start后面，确保被编译到镜像里，因为rt_system_scheduler_start不返回，实际不会执行到这里。

2022-08-05 17:35 UTC, mysterywolf approved these changes

2022-08-05 17:35 UTC, merged