[bsp] update esp32 and k210 Kconfig
RT-Thread/rt-thread pull request #6218
Opened 2022-08-03 18:05 UTC by mysterywolf

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-08-03 23:33 UTC, supperthomas commented
@tangzz98

2022-08-04 00:01 UTC, supperthomas requested changes

2022-08-04 00:01 UTC, supperthomas commented on bsp/ESP32_C3/.config
> +CONFIG_PKG_USING_ESP_IDF_LATEST_VERSION=y
建议先将目前能用的一版放出来，让大家可以用console，吸引一些感兴趣的小伙伴。后续再迭代新的架构，目前来看。新的架构实现起来可能会有难度。建议先保留前面的工作。

2022-08-04 00:27 UTC, mysterywolf commented on bsp/ESP32_C3/.config
> +CONFIG_PKG_USING_ESP_IDF_LATEST_VERSION=y
建议一开始就按照正规的去走，不急于出版本，路线对了，后面都好搞。

2022-08-06 10:26 UTC, BernardXiong approved these changes

2022-08-22 17:40 UTC, merged

2022-08-23 02:05 UTC, supperthomas commented
@tangzz98   请帮忙测试一下，谢谢。当前代码可以编译，正常运行即可。

2022-08-24 01:30 UTC, tangzz98 commented
> @tangzz98 请帮忙测试一下，谢谢。当前代码可以编译，正常运行即可。

可以正常运行