[renesas/ra2l1-cpk] add Captouch板载触摸按键配置说明.md
RT-Thread/rt-thread pull request #6227
Opened 2022-08-05 02:16 UTC by ShermanShao

## 拉取/合并请求描述：(PR description)

[
添加ra2l1-cpk板的CapTouch功能支持。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-08-05 02:45 UTC, mysterywolf approved these changes

2022-08-05 02:48 UTC, mysterywolf requested changes

2022-08-05 02:48 UTC, mysterywolf commented on bsp/renesas/ra2l1-cpk/QE-Touch/qe_sample_rtthread.c
> +INIT_APP_EXPORT(touch_init);
这个触摸初始化不建议放在最后一层

2022-08-05 02:48 UTC, mysterywolf commented on bsp/renesas/ra2l1-cpk/QE-Touch/SConscript
> +
这块写的稍微有些复杂，是否能在IAR中执行，是在rtconfig.py定义的，如果rtconfig.py中没有定义IAR，根本生成不了IAR，这里无需提醒。

2022-08-05 02:55 UTC, ShermanShao commented on bsp/renesas/ra2l1-cpk/QE-Touch/SConscript
> +
好的 目前不支持IAR。我把这里的提醒去掉吧

2022-08-05 02:58 UTC, ShermanShao commented on bsp/renesas/ra2l1-cpk/QE-Touch/qe_sample_rtthread.c
> +INIT_APP_EXPORT(touch_init);
官方的文档说明是将初始化代码放在 main() 函数里，所以在APP层初始化应该也可以吧？
![image](https://user-images.githubusercontent.com/56910863/182992181-d65db4d9-b2a1-4984-8e2f-41c12ebde27a.png)

2022-08-05 03:00 UTC, mysterywolf commented on bsp/renesas/ra2l1-cpk/QE-Touch/qe_sample_rtthread.c
> +INIT_APP_EXPORT(touch_init);
如果降一级可以运行的话最好降一或两级，否则用户的相关任务放在APP层级去初始化，这个时候触摸还没初始化就惨了，之前遇到过这种情况。

2022-08-05 03:09 UTC, ShermanShao commented on bsp/renesas/ra2l1-cpk/QE-Touch/qe_sample_rtthread.c
> +INIT_APP_EXPORT(touch_init);
好的 我试试看吧

2022-08-08 02:54 UTC, Guozhanxin commented on bsp/renesas/ra2l1-cpk/docs/Captouch板载触摸按键配置说明.md
> +# LPM低功耗配置说明
这个标题不对吧

2022-08-14 00:53 UTC, mysterywolf approved these changes

2022-08-14 00:53 UTC, merged