add hwtimer device
RT-Thread/rt-thread pull request #6230
Opened 2022-08-05 11:02 UTC by qipingqiu

## 拉取/合并请求描述：(PR description)

[
 add hwtimer device
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-08-05 11:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6230) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6230) before we can accept your contribution.<br/><hr/>**qiuqiping** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6230) it.</sub>

2022-08-05 13:53 UTC, mysterywolf requested changes

2022-08-05 13:53 UTC, mysterywolf commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +        if (result != CY_RSLT_SUCCESS)
这个位置的错误码在混用 一会是 CY_RSLT_SUCCESS 一会是rtt的RT_ERROR，请单独使用一个rt_err_t类型的变量来处理。

2022-08-05 13:53 UTC, mysterywolf commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +            return result;
同理  这里处理的有些问题，貌似直接把cy这侧的错误码返回回去了 不是rtt的错误码

2022-08-05 13:53 UTC, mysterywolf commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +    {
请注意缩进

2022-08-05 13:53 UTC, mysterywolf commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +            };
这个放在外边就可以了，放在里边有些编译器不认const，直接放在函数栈空间中

2022-08-07 21:25 UTC, mysterywolf requested changes

2022-08-07 21:25 UTC, mysterywolf commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +        result = cyhal_timer_set_frequency(tim, freq);
这个函数的返回值是cy_rslt_t数据类型，但是你用一个rt_err_t 类型的变量去承接。如果是故意这么做的话，那就没啥问题。如果是无意间混用，请更正。

2022-08-07 21:26 UTC, mysterywolf commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +        result = cyhal_timer_set_frequency(tim, freq);
此处最好应该是单独创建一个cy_rslt_t类型的变量去接收这个函数的返回值

2022-08-08 00:44 UTC, mysterywolf requested changes

2022-08-08 00:44 UTC, mysterywolf commented on bsp/cypress/pr test.txt
> +这是一个pr测试
这个文件咋提交上来了 😂

2022-08-08 01:29 UTC, qipingqiu commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +        result = cyhal_timer_set_frequency(tim, freq);
这里测试没有问题，如果单独创建一个cy_rslt_t的变量去接收函数返回值，不是会和rt_err_t的变量冲突吗

2022-08-08 01:33 UTC, qipingqiu commented on bsp/cypress/pr test.txt
> +这是一个pr测试
已经删除

2022-08-08 02:37 UTC, mysterywolf approved these changes

2022-08-08 02:37 UTC, mysterywolf commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +        result = cyhal_timer_set_frequency(tim, freq);
OK 没有问题就行

2022-08-08 02:49 UTC, Guozhanxin commented on bsp/cypress/libraries/HAL_Drivers/drv_hwtimer.c
> +    {
这里缩进也有问题呢

2022-08-08 02:50 UTC, Guozhanxin commented on bsp/cypress/psoc6-cy8cproto-4343w/board/Kconfig
> +    endif
这里缩进有问题

2022-08-08 02:50 UTC, Guozhanxin commented on bsp/cypress/psoc6-cy8cproto-4343w/board/Kconfig
> +                default n
这里少一个endif吧

2022-08-08 03:06 UTC, mysterywolf commented
不能用TAB，RT-Thread源码不使用TAB，一律使用4空格代替

2022-08-08 04:05 UTC, mysterywolf approved these changes

2022-08-09 08:57 UTC, Guozhanxin approved these changes

2022-08-09 16:18 UTC, merged