ch569w-evt : add pwm driver, and spi_xfer bug fix
RT-Thread/rt-thread pull request #6240
Opened 2022-08-08 08:14 UTC by emuzit

## 拉取/合并请求描述：(PR description)

[
* add PWM driver, output checked with logic analyzer
* spi_xfer() bug fix for cs_pin and message looping
* uart pin_mode init moved to uart driver
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-08-08 12:47 UTC, mysterywolf commented on bsp/wch/risc-v/ch569w-evt/rtconfig.h
>  #define RT_USING_WDT
对不起 之前没有注意到，一般来说rt-thread的bsp默认只使能GPIO和一个串口作为Console，其他的外设全部关闭掉，通过readme来告诉用户哪些外设已经可以用了，用户可以自己去使能，而不是默认就使能好。

请把这些看门狗、pwm spi都关掉吧 只留PIn和uart

2022-08-08 13:22 UTC, mysterywolf requested changes

2022-08-08 13:22 UTC, mysterywolf commented on bsp/wch/risc-v/ch569w-evt/board/Kconfig
> -    endif
SPI的Kconfig设置不需要删除呀，只是不是能而已，用户想用自己使能即可

2022-08-08 13:27 UTC, emuzit commented on bsp/wch/risc-v/ch569w-evt/rtconfig.h
>  #define RT_USING_WDT
已修正。

最近才开始学习RT，还很多地方弄不明白，请多指教。

2022-08-08 13:30 UTC, mysterywolf commented on bsp/wch/risc-v/ch569w-evt/board/Kconfig
> +            bool "using UART2"
虽然这么写也可以，但是default n要加上

2022-08-08 13:30 UTC, emuzit commented on bsp/wch/risc-v/ch569w-evt/board/Kconfig
> -    endif
merge时不小心多出来的，故删除。

2022-08-08 13:31 UTC, mysterywolf commented on bsp/wch/risc-v/ch569w-evt/board/Kconfig
> +            default y
这个地方如果不是必须应该是n 用户需要自己去开，除非是必须依赖（例如程序运行在片外spiflash上之类）

2022-08-08 13:43 UTC, emuzit commented on bsp/wch/risc-v/ch569w-evt/board/Kconfig
> +            default y
已修正。

2022-08-08 13:54 UTC, mysterywolf requested changes

2022-08-08 13:54 UTC, mysterywolf commented on bsp/wch/risc-v/ch569w-evt/applications/main.c
> +        rt_tick_sethook(pwm_tick_hook);
这个main.c写的太冗长了，直接保留一个闪烁led就可以了，可以参见一个STM32的任意bsp的main.c
如果这个main.c 可以改成test.c 然后不用加到sconscript中，用来你私下测试使用

2022-08-08 13:54 UTC, mysterywolf commented on bsp/wch/risc-v/ch569w-evt/applications/main.c
> +        rt_tick_sethook(pwm_tick_hook);
除了这个其他我没有问题了

2022-08-08 14:13 UTC, mysterywolf approved these changes

2022-08-09 08:55 UTC, Guozhanxin approved these changes

2022-08-09 16:18 UTC, merged