Fix compile ti
RT-Thread/rt-thread pull request #6254
Opened 2022-08-11 20:11 UTC by CuttySark1869

## 拉取/合并请求描述：(PR description)

[
解决 tms320f28379d bsp 与最新内核不兼容问题。主要改动如下。
1. 在bsp\tms320f28379d\.cproject中更新了编译器以避免CCS编译时出现segmentation fault；
2. 用menuconfig更新了.config：select FINSH_USING_SYMTAB，并修改2837x_FLASH_lnk_cpu1.cmd，为FSymTab分配内存段；
3. 修改了bsp\tms320f28379d\drivers\board.c，允许中断嵌套，并且防止由于interrupt_leave_hook在rt_interrupt_nest --之前被调用（src\irq.c）导致在context switch的时候程序误以为仍处在中断context（rt_interrupt_nest > 0）。这个问题在旧版内核中不存在因为旧版interrupt_leave_hook是在rt_interrupt_nest --之后才被调用的。
4. 修改了kservice.c中的rt_memset和rt_vsnprintf两个函数，使之同时适应不同的word size和argument alignment。

以上改动在LAUNCHXL-F28379D 和 STM32F407硬件均通过了测试。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-08-11 20:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6254) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6254) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: QY7<br/>:x: CuttySark1869<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6254) it.</sub>

2022-08-11 20:16 UTC, mysterywolf commented
感谢提交PR

related: https://github.com/RT-Thread/rt-thread/issues/6093

2022-08-14 02:26 UTC, mysterywolf requested changes

2022-08-14 02:26 UTC, mysterywolf commented on src/kservice.c
>          else
不可以通过else，需要写成else if(LBLOCKSIZE == xxx)

2022-08-14 02:27 UTC, mysterywolf commented
请问rt_memcpy rt_memcmp 有类似的问题吗 可否帮忙一起顺带改正 谢谢~

2022-08-16 13:56 UTC, CuttySark1869 commented on src/kservice.c
>          else
感谢，已经更改

2022-08-16 13:58 UTC, CuttySark1869 commented on src/kservice.c
>          else
刚刚查过 rt_memcpy 和 rt_memcmp 都没有这个问题

2022-08-16 14:01 UTC, CuttySark1869 commented on src/kservice.c
>          else
对于rt_vsnprintf()的修改是有一点tricky的，不知道对其他的架构是不是有影响，因为依赖于stack alignment和参数传递机制。不是道是不是用编译开关区分一下更稳妥一点？

2022-08-17 04:59 UTC, mysterywolf commented
你好请ping我一下邮箱 meco@rt-thread.org 拉你进群

2022-08-18 01:45 UTC, mysterywolf commented
你好，本PR中其他代码没有问题，kservice.c文件的修改还需要再讨论，可否将kservice.c的修改从这个PR中抽出去，单独开个PR。这样这个PR就不会耽搁太久，其他reviewer没啥问题就可以合并了。

2022-08-18 12:23 UTC, CuttySark1869 commented
好的。kservice.c中对rt_memset的修改是否保留，还是彻底退回到原来的版本？


> 你好，本PR中其他代码没有问题，kservice.c文件的修改还需要再讨论，可否将kservice.c的修改从这个PR中抽出去，单独开个PR。这样这个PR就不会耽搁太久，其他reviewer没啥问题就可以合并了。

2022-08-18 20:51 UTC, mysterywolf approved these changes

2022-08-20 17:16 UTC, merged