Update kservice.c
RT-Thread/rt-thread pull request #6305
Opened 2022-08-18 21:40 UTC by CuttySark1869

For compatibility with 16bit addressing 32bit CPU (e.g. Ti C28x).

## 拉取/合并请求描述：(PR description)

[
1. 修改了rt_memset 使其 word size independent.
2. 修改了rt_vsnprintf 使其适应于 16bit 和 32bit stack alignment. This is a bit tricking by using "va_arg(args, int)".
3. Further discussion is needed on whether or nor shall we create separate memory-related service functions for 16-bit addressing CPUs. From my point of view, I think rt_memset can be kept like this (independent of addressing mode), but rt_vsnprintf should be dealt with carefully since va_arg(args, int) may corrupt the argument passing mechanism if the size of int is not the default stack alignment size.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-08-18 21:43 UTC, mysterywolf commented
related: https://github.com/RT-Thread/rt-thread/pull/6254

2022-08-22 01:41 UTC, Guozhanxin commented on src/kservice.c
> +        else if (LBLOCKSIZE == 2)
这个只有2和4两种情况吗？有没有可能是8？

2022-08-22 12:21 UTC, CuttySark1869 commented on src/kservice.c
> +        else if (LBLOCKSIZE == 2)
之前的代码只区分了2和4两种情况，这里是继承下来的。LBLOCKSIZE = sizeof(long)。一般long=int=32bit，64位的整型一般是long long。但是有可能有编译器把long编译成64位的。保险起见可以加一个8的情况。

2022-08-24 04:40 UTC, mysterywolf requested changes

2022-08-24 04:40 UTC, mysterywolf commented on src/kservice.c
```suggestion
else
{
    RT_DEBUG_LOG(RT_TRUE, ("rt_memcpy cannot handle this case, please enable RT_KSERVICE_USING_TINY_SIZE\n"));
    ASSERT(0);
}
```

2022-08-24 05:43 UTC, mysterywolf commented on src/kservice.c
@CuttySark1869 先不要按照此建议修改
@Guozhanxin 郭老师你觉得是else这么写好，还是上来assert LBLOCKSIZE比较好？
```c
RT_ASSERT(LBLOCKSIZE == 2 || LBLOCKSIZE == 4 || LBLOCKSIZE == 8);
```

2022-08-24 08:14 UTC, Guozhanxin commented on src/kservice.c
我感觉都可以吧，

2022-08-24 08:14 UTC, Guozhanxin approved these changes

2022-08-24 18:38 UTC, mysterywolf requested changes

2022-08-24 18:38 UTC, mysterywolf commented on src/kservice.c
```suggestion
RT_ASSERT(LBLOCKSIZE == 2 || LBLOCKSIZE == 4 || LBLOCKSIZE == 8);
```

2022-08-24 18:38 UTC, mysterywolf commented on src/kservice.c
请把这句话加到第156行

2022-08-24 18:56 UTC, CuttySark1869 commented on src/kservice.c
done

2022-08-24 21:10 UTC, mysterywolf approved these changes

2022-08-24 21:12 UTC, merged

2022-08-24 21:13 UTC, mysterywolf commented
已合并 感谢提交PR！