[fix] Fix simulator compilation warnings
RT-Thread/rt-thread pull request #6438
Opened 2022-09-16 08:44 UTC by enkiller

## 拉取/合并请求描述：(PR description)

[
修复 VS 模拟器编译警告
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-09-16 12:11 UTC, mysterywolf requested changes

2022-09-16 12:11 UTC, mysterywolf commented on bsp/simulator/rtconfig_project.h
> +#pragma warning(disable:4103)   /* structure packing changed by including file */
```suggestion
// #pragma warning(disable:4103)   /* structure packing changed by including file */
```
建议改成这种方式，可以提示但是不要直接disable掉，因为这个并没有实际解决问题，只是在自欺欺人。

2022-09-16 12:11 UTC, mysterywolf commented on components/dfs/filesystems/romfs/dfs_romfs.c
> -    if (offset <= file->size)
建议用rt_size_t

2022-09-16 12:11 UTC, mysterywolf commented on components/dfs/filesystems/romfs/dfs_romfs.c
> +    for (index = 0; index < count && (size_t)file->pos < file->size; index ++)
rt_size_t

2022-09-16 12:11 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
>          if (work >= k)
这块把time_t改成int也是因为给出警告了嘛

2022-09-16 21:31 UTC, mysterywolf requested changes

2022-09-16 21:31 UTC, mysterywolf commented on components/dfs/filesystems/romfs/dfs_romfs.c
> +    if (offset >= 0 && (size_t)offset <= file->size)
```suggestion
    if (offset >= 0 && (rt_size_t)offset <= file->size)
```

2022-09-16 21:31 UTC, mysterywolf commented on components/dfs/filesystems/romfs/dfs_romfs.c
> +    for (index = 0; index < count && (size_t)file->pos < file->size; index ++)
```suggestion
    for (index = 0; index < count && (rt_size_t)file->pos < file->size; index ++)
```

2022-09-19 02:08 UTC, mysterywolf approved these changes

2022-09-20 09:02 UTC, Guozhanxin approved these changes

2022-09-20 14:31 UTC, merged