添加了dac驱动
RT-Thread/rt-thread pull request #6440
Opened 2022-09-17 13:04 UTC by hg0720

## 拉取/合并请求描述：(PR description)

[添加了 dac 的驱动，加入了 drv_dac.c 和 drv_dac.h 文件；
修改了 E:\rt\rt_github\rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 SConscript 文件；
修改了 E:\rt\rt_github\rt-thread\bsp\wch\risc-v\ch32v307v-r1\board 目录下的 Kconfig 文件；
已在 ch32v307 评估板进行测试。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-09-17 13:11 UTC, mysterywolf requested changes

2022-09-17 13:11 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
> +                depends on BSP_USING_DAC
这句话可以删掉 if 和depnds on有一个就行，这种情况用if处理更合适

2022-09-17 13:33 UTC, hg0720 commented
已修改

2022-09-17 13:34 UTC, mysterywolf commented
感谢提交PR!

2022-09-17 13:34 UTC, mysterywolf approved these changes

2022-09-17 14:28 UTC, mysterywolf commented
@liYony 请review一下 谢谢

2022-09-17 15:20 UTC, mysterywolf requested changes

2022-09-17 15:20 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_dac.h
> + * 2021-09-09     WCH          the first version
这个日期顺序搞反了，早的日期在前，新的日期在后

2022-09-17 15:20 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_dac.c
> + * 2021-09-09     WCH          the first version
同理

2022-09-17 15:20 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_dac.c
> +
```suggestion
```
这个不需要加空格

2022-09-17 15:20 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_dac.c
> +#if defined(BSP_USING_DAC_CHANNEL1) || defined(BSP_USING_DAC_CHANNEL2)
此处 直接使用 BSP_USING_DAC即可

2022-09-18 02:15 UTC, hg0720 commented
已更正

2022-09-18 11:45 UTC, liYony approved these changes

2022-09-18 13:32 UTC, mysterywolf approved these changes

2022-09-18 13:32 UTC, merged