bsp beaglebone: add IAR support
RT-Thread/rt-thread pull request #6443
Opened 2022-09-18 07:09 UTC by newworker

## 拉取/合并请求描述：(PR description)

增加beaglebone AM335x的IAR工程

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-09-18 07:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6443) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6443) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6443) it.</sub>

2022-09-18 19:49 UTC, mysterywolf requested changes

2022-09-18 19:49 UTC, mysterywolf commented on libcpu/arm/am335x/mmu.c
>      rt_hw_cpu_dcache_enable();
麻烦把`rt_cpu_icache_enable` 和 `rt_cpu_dcache_enable`, 统一改成 `rt_hw_cpu_icache_enable` 和  `rt_hw_cpu_dcache_enable`

2022-09-19 09:35 UTC, newworker commented on libcpu/arm/am335x/mmu.c
>      rt_hw_cpu_dcache_enable();
好的，晚上回去改一下。

另外，我看 mmu.c 这个文件里面其他地方都是用的 rt_cpu_* ，并且这些 rt_cpu_ 开头的函数在GCC和IAR里面都已经有相关汇编代码，是不是把 rt_hw_cpu_* 都删了才更合适？

2022-09-19 15:01 UTC, mysterywolf commented on libcpu/arm/am335x/mmu.c
>      rt_hw_cpu_dcache_enable();
rt_hw_cpu_icache_enable  和 rt_hw_cpu_dcache_enable 是其他bsp也是这么命名的 这是个命名统一的函数

2022-09-19 15:01 UTC, mysterywolf commented on libcpu/arm/am335x/mmu.c
>      rt_hw_cpu_dcache_enable();
如果 rt_hw_cpu_icache_enable 和 rt_hw_cpu_dcache_enable 没有用的话 可以删除掉

2022-09-20 14:10 UTC, newworker commented on libcpu/arm/am335x/mmu.c
>      rt_hw_cpu_dcache_enable();
GCC和MDK还是用到了rt_hw_cpu_*等函数，还是不能删。已经仿照GCC方式实现了cp15_rd()、cache_enable()、cache_disable()的IAR汇编，请重新审查

2022-09-22 01:48 UTC, Guozhanxin approved these changes

2022-09-22 06:13 UTC, merged

2022-09-25 05:42 UTC, newworker commented on libcpu/arm/am335x/mmu.c
> -    volatile int i,nSec;
那里加 volatile 确实没有意义，去掉它是因为 IAR 报了如下警告：
Warning[Pa082]: undefined behavior: the order of volatile accesses is undefined in this statement