[TMS320F28379] implement PWM driver
RT-Thread/rt-thread pull request #6457
Opened 2022-09-21 14:35 UTC by QY7

## 拉取/合并请求描述：(PR description)

[
增加c28x芯片的pwm驱动
已经在TMS320F28379中通过测试
pwm设备框架增加如下方法：
#define PWM_CMD_SET_DEAD_TIME  (RT_DEVICE_CTRL_BASE(PWM) + 8)
#define PWM_CMD_SET_PHASE   (RT_DEVICE_CTRL_BASE(PWM) + 9)
#define PWM_CMD_ENABLE_IRQ  (RT_DEVICE_CTRL_BASE(PWM) + 10)
#define PWM_CMD_DISABLE_IRQ  (RT_DEVICE_CTRL_BASE(PWM) + 11)
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-09-21 15:20 UTC, mysterywolf requested changes

2022-09-21 15:20 UTC, mysterywolf commented on bsp/tms320f28379d/drivers/drv_pwm.c
> + *  Created on: 2022��6��10��
这里编码有问题 请使用formatting脚本扫描一下：https://github.com/mysterywolf/formatting

2022-09-21 15:20 UTC, mysterywolf commented on components/drivers/include/drivers/rt_drv_pwm.h
> +    rt_uint32_t phase;
这两个新增加的成员变量请给出注释 类似于上面的

2022-09-21 18:45 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/misc/rt_drv_pwm.c#L216
https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/misc/rt_drv_pwm.c#L233
请仿照上面两个函数实现一下rt_pwm_set_dead_time 和rt_pwm_set_phase，否则设备框架中定义了这两个成员变量和命令 但是缺没有任何使用很奇怪。

2022-09-21 18:48 UTC, mysterywolf commented
PWM_CMD_ENABLE_IRQ  和DISABLE_IRQ是做什么用的？使能失能pwm中断？

2022-09-22 14:24 UTC, QY7 commented
是的，就是拿来使能中断和关闭中断的。方便调试用。

2022-09-22 14:25 UTC, QY7 commented
已经按照需求增加了phase和dead_time的设置api

2022-09-24 00:57 UTC, QY7 commented
已经按照设备框架来重新改了驱动部分

2022-09-24 03:02 UTC, mysterywolf approved these changes

2022-09-26 02:37 UTC, Guozhanxin approved these changes

2022-09-26 02:41 UTC, merged

2022-09-26 02:41 UTC, mysterywolf commented
感谢贡献PR！