Modified   bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h
RT-Thread/rt-thread pull request #6471
Opened 2022-09-26 03:34 UTC by myshowtogo

Modified   bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h
Modified   bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
修复f4的dma配置，修改v2串口驱动dma接收不响应半满和全满

## 拉取/合并请求描述：(PR description)

[
解决的问题：
串口接收数据错误，应用层接收的数据被截断成两个。

解决方案：
按照stm32f4的数据手册修改dma_config.h，drv_usart_v2.c中stm32_uart_get_config添加缺失的串口，屏蔽dma接收的半满和全满的处理，不然应用层触发时那一帧数据会被截取成两段。
![image](https://user-images.githubusercontent.com/28536570/192188681-35011f6a-c6d9-4217-be27-c2507b315fab.png)
![image](https://user-images.githubusercontent.com/28536570/192188600-ffd114d7-0813-48cc-b326-b078bcb28626.png)

测试环境：
f429系列的开发板
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-10-08 06:24 UTC, armink requested changes

2022-10-08 06:24 UTC, armink commented on bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
> +//        break;
> 屏蔽dma接收的半满和全满的处理，不然应用层触发时那一帧数据会被截取成两段。

这里不建议去掉

- 1、报文的完整性处理应该是在协议内部来完成，不应该依赖于底层驱动
- 2、如果去掉，接收到的数据超过缓冲区大小时，是没法通知到上层来取数据，不够安全

2022-10-09 00:42 UTC, myshowtogo commented on bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
> +//        break;
1.应用层无需关心dma缓冲是否已满，这个处理应该是驱动层的事情
2.驱动中已经将数据放置在环形缓冲区，不存在数据丢失
3.驱动层这一块的通知平白的增加了应用层的复杂度

2022-10-09 00:54 UTC, armink commented on bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
> +//        break;
> 1.应用层无需关心dma缓冲是否已满，这个处理应该是驱动层的事情

通知应用层的语义只是告诉应用层有数据可以取，而不是让应用层关心缓存区是否已满

> 2.驱动中已经将数据放置在环形缓冲区，不存在数据丢失

一次性接收超过 DMA buf 数据时就会丢失的

> 3.驱动层这一块的通知平白的增加了应用层的复杂度

- 1、软件分层设计本来就应该职责分明。如果要提升可靠性，必要的帧完整性处理逻辑少不了的，这块可以看下 erpc 、TinyFrame 等软件包
- 2、另外，IDLE 中断我觉得也是不靠谱的，因为受限于发送端的发送时序，如果发送端使用每个字节发送不及时或者每帧数据发送间隔较小，同样会造成 短帧 或 粘帧 的问题

2022-10-13 14:25 UTC, armink commented
485 的支持要不要独立一个 PR 呢？

2022-10-13 22:38 UTC, mysterywolf commented
> 485 的支持要不要独立一个 PR 呢？

可先不用麻烦再提一个PR，合并的时候可以重新整理日志，龙哥，你看看从实现上还有什么问题没有。😁

2022-10-13 22:39 UTC, mysterywolf commented
麻烦处理一下代码分支冲突~

2022-10-16 04:43 UTC, armink commented
> > 485 的支持要不要独立一个 PR 呢？
> 
> 可先不用麻烦再提一个PR，合并的时候可以重新整理日志，龙哥，你看看从实现上还有什么问题没有。😁

@mysterywolf 我感觉设计上还得再斟酌一下

2022-10-23 16:40 UTC, mysterywolf commented
@myshowtogo 你好可否把485的部分抽出去？单独提交一个PR？

2022-10-26 03:47 UTC, mysterywolf approved these changes

2022-10-26 03:48 UTC, mysterywolf commented
@armink 龙哥 请再review一下这个PR 谢谢！

2022-10-31 01:18 UTC, armink approved these changes

2022-10-31 01:19 UTC, merged