[ch32v307][bsp]添加了看门狗驱动
RT-Thread/rt-thread pull request #6474
Opened 2022-09-27 09:46 UTC by hg0720

## 拉取/合并请求描述：(PR description)

[
添加了 ch32v307 看门狗驱动，已在 ch32v307评估板验证；
修改了 rt-thread\bsp\wch\risc-v\ch32v307v-r1\board 目录下的 Kconfig 文件；
修改了 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 SConscript 文件；
添加了 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 drv_iwdt.c 文件；
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-09-27 16:32 UTC, mysterywolf requested changes

2022-09-27 16:32 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_iwdt.c
> +    rt_uint32_t Prescaler;
用小写字母，rt-thread不采用驼峰式，采用全小写+下划线

2022-09-28 06:02 UTC, hg0720 commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_iwdt.c
> +    rt_uint32_t Prescaler;
这是 ch32 底层库里面的

2022-09-28 06:07 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_iwdt.c
> +    rt_uint32_t Prescaler;
我指的是Prescaler和Reload

2022-09-28 06:21 UTC, mysterywolf approved these changes
@liYony 请review一下

2022-09-29 00:44 UTC, liYony approved these changes

2022-09-29 00:59 UTC, mysterywolf requested changes

2022-09-29 00:59 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_iwdt.c
> +#endif
这个没有必要检查两遍可以，下面又检查一遍，可以直接放在文件开头，包含头文件的下面的位置

2022-09-29 01:02 UTC, liYony commented
我感觉这段代码在考虑LSI_VALUE等于0的情况留着吧



---原始邮件---
发件人: "Man, Jianting ***@***.***&gt;
发送时间: 2022年9月29日(周四) 上午8:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RT-Thread/rt-thread] [ch32v307][bsp]添加了看门狗驱动 (PR #6474)




 
@mysterywolf requested changes on this pull request.
 
 
In bsp/wch/risc-v/Libraries/ch32_drivers/drv_iwdt.c:
 &gt; +#if defined(LSI_VALUE) +        if (LSI_VALUE) +        { +            wdt_dev-&gt;reload = (*((rt_uint32_t *)arg)) * LSI_VALUE / 256; +        } +        else +        { +            LOG_E("Please define the value of LSI_VALUE!"); +        } +        if (wdt_dev-&gt;reload &gt; 0xFFF) +        { +            LOG_E("wdg set timeout parameter too large, please less than %ds", 0xFFF * 256 / LSI_VALUE); +            return -RT_EINVAL; +        } +#else +#error "Please define the value of LSI_VALUE!" +#endif  
这个没有必要检查两遍可以，下面又检查一遍，可以直接放在文件开头，包含头文件的下面的位置
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-09-29 01:07 UTC, mysterywolf commented
额不是 我没有说清楚 我是说#error  这个检查写了两遍

2022-09-29 01:09 UTC, mysterywolf commented
我改了一下 把#error 放在上面了 这部分没有必要写两遍

2022-09-29 01:09 UTC, liYony commented
如果是你说的这样，我觉得那个log_e里面的内容应该是value错误相关的



---原始邮件---
发件人: "Man, Jianting ***@***.***&gt;
发送时间: 2022年9月29日(周四) 上午9:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RT-Thread/rt-thread] [ch32v307][bsp]添加了看门狗驱动 (PR #6474)




 
额不是 我没有说清楚 我是说#error  这个检查写了两遍
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-09-29 01:09 UTC, mysterywolf approved these changes

2022-09-29 01:09 UTC, merged

2022-09-29 01:10 UTC, mysterywolf commented
感谢提交PR！