[bsp][RA6M4]Add segger rtt function
RT-Thread/rt-thread pull request #6508
Opened 2022-10-11 15:46 UTC by kurisaW

## 拉取/合并请求描述：(PR description)

[ 添加segger rtt 为console的Kconfig]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-10-11 15:56 UTC, kurisaW reviewed
[modify] 格式对齐修改

2022-10-11 22:42 UTC, mysterywolf approved these changes

2022-10-11 23:09 UTC, mysterywolf requested changes

2022-10-11 23:09 UTC, mysterywolf commented on bsp/renesas/libraries/HAL_Drivers/drv_common.c
>  #if defined(RT_USING_CONSOLE) && defined(RT_USING_DEVICE)
```suggestion
#elif defined(RT_USING_CONSOLE) && defined(RT_USING_DEVICE)
```

2022-10-11 23:17 UTC, kurisaW reviewed
[modify]

2022-10-11 23:25 UTC, kurisaW reviewed
[modify]

2022-10-11 23:33 UTC, kurisaW reviewed
[modify]

2022-10-11 23:41 UTC, mysterywolf approved these changes

2022-10-12 00:29 UTC, supperthomas requested changes

2022-10-12 00:29 UTC, supperthomas commented on bsp/renesas/libraries/HAL_Drivers/drv_common.c
> +#if defined(SEGGER_RTT_ENABLE)
这里可以这样用了？试过了么？可以打印启动的log么？如果有问题这里可以先不加。

2022-10-12 03:05 UTC, kurisaW reviewed
[modify]

2022-10-12 03:05 UTC, kurisaW commented on bsp/renesas/libraries/HAL_Drivers/drv_common.c
> +#if defined(SEGGER_RTT_ENABLE)
测试过不能使用，已经将此处删除，能正常运行

2022-10-12 03:07 UTC, supperthomas approved these changes

2022-10-12 03:10 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/blob/fc55785e70fbf8d117b7f713f67131f640e9fe3d/bsp/nrf5x/nrf52840/board/board.c
这个是否也需要删除？ @supperthomas

2022-10-12 03:44 UTC, supperthomas commented
> https://github.com/RT-Thread/rt-thread/blob/fc55785e70fbf8d117b7f713f67131f640e9fe3d/bsp/nrf5x/nrf52840/board/board.c
> 这个是否也需要删除？ @supperthomas 

不用，两个串口框架不一样，那个可以用，这个用不了

2022-10-12 03:49 UTC, merged

2022-12-02 07:19 UTC, supperthomas commented
https://github.com/RT-Thread/rt-thread/issues/6062