[device] 添加总线设备
RT-Thread/rt-thread pull request #6514
Opened 2022-10-13 11:54 UTC by Guozhanxin

## 拉取/合并请求描述：(PR description)

[
已在qemu上做了验证。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-10-13 22:32 UTC, mysterywolf requested changes

2022-10-13 22:32 UTC, mysterywolf commented on components/drivers/misc/rt_dev_bus.c
> +#define DBG_TAG "adc"
```suggestion
#define DBG_TAG "adc"
```
这个有问题 名字应该改掉

2022-10-13 22:32 UTC, mysterywolf commented on components/dfs/filesystems/devfs/devfs.c
> +            return -ENOSYS;
存在rtt错误码和posix错误码混用的问题，应使用rtt错误码

2022-10-17 03:30 UTC, mysterywolf commented
5.0.0开始规范设备框架的文件命名和结构体命名了 觉得是 rt_dev_xxx.c比较好 还是dev_xxx.c比较好？

2022-11-23 16:32 UTC, i-jaffer commented
> > 5.0.0开始规范设备框架的文件命名和结构体命名了 觉得是 rt_dev_xxx.c比较好 还是dev_xxx.c比较好？
> 
> 需要把device和driver分离了，device是最轻量级的外在表像，内部还得看driver的驱动。 ![image](https://user-images.githubusercontent.com/1241087/196782149-3aede26f-6fa9-413b-8598-2dac6ccdf8bd.png)

请问能否分享一下图中使用的此款软件名，通过此软件可直观描述程序拓扑，能为rtt开源社区开发者们分析代码提供有力帮助，望分享 感谢! @BernardXiong

2022-12-06 02:18 UTC, closed without merging