提交stm32 bsp drv_pwm.c里面的一个小建议
RT-Thread/rt-thread pull request #6517
Opened 2022-10-14 02:31 UTC by 100ask-Alen

## 拉取/合并请求描述：(PR description)

[
 在使用stm32的pwm驱动时，发现其初始化channel的时候是根据device->channel这个值去初始化的，device->channel这个值是在pwm_configh.h里面定义设置的，又根据rtt的pwm例程，和常规习惯，应该大多数人会更喜欢设置channel=1/2/3/4，而不是在pwm_configh.h中将channel设置为TIM_CHANNEL_1/2/3/4，因此建议drv_pwm.c做出PR中的修改。

在实际开发中，因pwm_configh.h的示例均是.channel=0，又没有做出解释说明要让.channel=TIM_CHANNEL_1/2/3/4的值，容易误操作导致没有成功输出PWM，这是我在实际开发中遇到的现实问题，因而提出此建议。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-10-24 02:47 UTC, Guozhanxin commented
感觉是可以的，只要hal库里的定义不改的话。
![image](https://user-images.githubusercontent.com/25633294/197438475-44b43bdd-10ab-4113-8383-0f68cf19b4fa.png)
还有是不是需要在代码里加个判断，安全一点 
```
#if (TIM_CHANNEL_4 != 0x0000000CU ) 
#error “xxx”
#endif
```

2022-10-24 02:47 UTC, Guozhanxin approved these changes

2022-10-24 02:56 UTC, 100ask-Alen commented
channel = 0x04 * (device->channel - 1)
这个算式我是抄的原drv_pwm.c里面一个函数里面的，原来的drv_pwm.c支持这样的算式的话，应该影响不大？
我不是很清楚原来的stm32的drv_pwm.c是谁写的。

2022-10-24 02:58 UTC, 100ask-Alen commented
源文件的

2022-10-24 02:59 UTC, 100ask-Alen commented
源文件的
static rt_err_t drv_pwm_enable(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration, rt_bool_t enable)
static rt_err_t drv_pwm_get(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration)
static rt_err_t drv_pwm_set(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration)
static rt_err_t drv_pwm_set_pulse(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration)
这些函数都是这样换算的通道值。

2022-10-24 03:05 UTC, Guozhanxin commented
> 源文件的 static rt_err_t drv_pwm_enable(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration, rt_bool_t enable) static rt_err_t drv_pwm_get(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration) static rt_err_t drv_pwm_set(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration) static rt_err_t drv_pwm_set_pulse(TIM_HandleTypeDef *htim, struct rt_pwm_configuration *configuration) 这些函数都是这样换算的通道值。

嗯，感觉应该没啥问题

2022-10-24 03:09 UTC, 100ask-Alen commented
建议在pwm_config.h里面加点注释，说明下那个结构体的几个成员该如何设置值，合法范围是多少。

2022-10-24 03:55 UTC, mysterywolf commented
嗯嗯 可以增加注释 说实话 我都不知道那个channel成员变量是干啥的 看都设置为0 我也没管它 ，但是需要注意下 rt-thread的注释是用/**/ 而不是//

2022-10-24 09:59 UTC, 100ask-Alen commented
其它系列的pwm通道数，不是全都了解各有多少个，现在不确定是否都是每个定时器只有4个通道， 其它系列的pwm_config.h也需要改一改才行，我找个时间改改看，先不忙合并吧。

2022-10-26 03:42 UTC, mysterywolf requested changes

2022-10-26 03:42 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
> +		LOG_E("%s pwm channel %d is invalid, failed to init", device->name, device->channel);
请注意缩进问题 rt-thread使用4空格 而不是tab键

2022-10-26 03:43 UTC, mysterywolf commented
https://github.com/mysterywolf/formatting 可以用这个脚本扫描一下

2022-10-26 03:52 UTC, mysterywolf commented
如果PR 已经准备好 请告知

2022-10-26 03:53 UTC, mysterywolf requested changes

2022-10-26 03:53 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
> +    if(channel<1 || channel >4)
这个位置细节, 下面还有类似的 请修改一下：
```suggestion
    if(channel <1 || channel > 4)
```

2022-10-26 03:58 UTC, 100ask-Alen commented on bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
> +    if(channel<1 || channel >4)
这个已经改了，其他系列有pwm的看了下资料，基本都是支持4路pwm，所以这个算式应该还是通用的，可以合并。

2022-10-26 03:58 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
> +    if(channel<1 || channel >4)
好的 感谢提交PR！

2022-10-26 03:59 UTC, mysterywolf approved these changes

2022-10-28 22:38 UTC, merged