[Kernel] Add nested mutex feature
RT-Thread/rt-thread pull request #6523
Opened 2022-10-15 08:31 UTC by BernardXiong

## 拉取/合并请求描述：(PR description)

[Kernel] Add nested mutex feature.

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

2022-10-16 23:50 UTC, mysterywolf commented on src/ipc.c
> +    return ;
```suggestion

```

2022-10-16 23:51 UTC, mysterywolf requested changes

2022-10-16 23:51 UTC, mysterywolf commented on src/ipc.c
> +#define RT_USING_MUTEX
这个宏应该删除掉

2022-10-19 04:21 UTC, mysterywolf commented on src/ipc.c
> +    return ;
熊大 这个return ; 是有什么特殊用意嘛？

2022-10-24 12:49 UTC, BernardXiong commented on src/ipc.c
> +    return ;
这里加或不加关系不大，或者只是习惯的问题。

2022-10-24 12:50 UTC, BernardXiong commented on src/thread.c
> +        rt_mutex_drop_thread(mutex, thread);
`rt_mutex_drop_thread` 这个API只内部使用，但是这些函数不能给以extern方式乱引用。

2022-10-26 03:37 UTC, mysterywolf commented on src/ipc.c
> +    return ;
那这个应该拿掉，因为只有这一个函数莫名地出现了return ;

2022-10-26 03:39 UTC, mysterywolf approved these changes

2022-10-26 03:41 UTC, mysterywolf requested changes

2022-10-26 03:41 UTC, mysterywolf commented on include/rtdef.h
> +    rt_uint8_t           reserv;
这个地方最好和上面的sem统一：
reserved; /**< reserved field */

2022-10-26 03:45 UTC, mysterywolf approved these changes

2022-11-06 00:59 UTC, merged