[bsp/phytium] add phytium bsp to support e2000 bootup with smp
RT-Thread/rt-thread pull request #6566
Opened 2022-10-27 03:33 UTC by zhugengyu

## 拉取/合并请求描述：(PR description)

[
- add phytium board (E2000) bsp
- support usart
- support SMP with demo
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-10-27 03:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6566) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6566) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6566) it.</sub>

2022-11-06 01:17 UTC, BernardXiong requested changes
感谢提交，请注意一些细节格式。另外关于aarch32/64，按理说是可以合并，而通过menuconfig来进行选择配置的，以及不同核的的情况也可以使用设备树来进行支持（默认开启SMP，但这个是1个核还是4个核，由设备树确定）

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/aarch32/boot/aarch32_boot.S
> +	orr	    r1,r1, #FPEXC_EN	/* set VFP enable bit, leave the others in orig state */
这里的缩进是存在问题的，请确保格式检查机器人在这些地方都是干活的。

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/aarch32/boot/aarch32_boot.S
> +	mov      r1, #0
缩进问题……

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/aarch32/boot/SConscript
> +src	+= Glob('*.c')
请梳理下格式，做些对齐，或在前面写成

`src = Glob('*.S') + Glob('*.c')`

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/aarch32/SConscript
> +for d in list:
这个是一个桥方式的SConscript (桥：可以通过它打通到其他的路上)，可以使用`rt-thread/tools/wizard.py`来进行生成，生成的SConscript不会是这样的。

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/aarch32/make.sh
> +scons && cp rtthread_a32.bin D:\tftboot\rtthread_a32.bin && ls D:\tftboot\rtthread_a32.bin
不建议提交这份脚本，因为太个性化了

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/aarch32/rtconfig.py
> +    CFLAGS = DEVICE
可以考虑加入 `-fdiagnostics-color=always` 选项

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/aarch64/SConscript
> +cwd = str(Dir('#'))
同32位的情况

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/board/secondary_cpu.c
> +        // rt_hw_ipi_send(RT_SCHEDULE_IPI, cpu_mask);
一些无关代码请移除

2022-11-06 01:17 UTC, BernardXiong commented on bsp/phytium/board/secondary_cpu.c
> +// #if defined(TARGET_ARMV8_AARCH64)
无关代码请移除

2022-11-07 03:00 UTC, zhugengyu commented on bsp/phytium/aarch32/boot/aarch32_boot.S
> +	orr	    r1,r1, #FPEXC_EN	/* set VFP enable bit, leave the others in orig state */
已经使用 AStyle 工具检查了修复缩进问题

2022-11-07 03:00 UTC, zhugengyu commented on bsp/phytium/aarch32/boot/SConscript
> +src	+= Glob('*.c')
已修改

2022-11-07 03:01 UTC, zhugengyu commented on bsp/phytium/aarch32/SConscript
> +for d in list:
已经使用 wizard.py 重新生成 bridge 用的 SConscript

2022-11-07 03:01 UTC, zhugengyu commented on bsp/phytium/aarch32/make.sh
> +scons && cp rtthread_a32.bin D:\tftboot\rtthread_a32.bin && ls D:\tftboot\rtthread_a32.bin
已删除 aarch32 和 aarch64 的 make.sh

2022-11-07 03:01 UTC, zhugengyu commented on bsp/phytium/aarch32/rtconfig.py
> +    CFLAGS = DEVICE
已添加此选项

2022-11-07 03:02 UTC, zhugengyu commented on bsp/phytium/board/secondary_cpu.c
> +        // rt_hw_ipi_send(RT_SCHEDULE_IPI, cpu_mask);
已移除注释代码

2022-11-07 03:07 UTC, zhugengyu commented
>  我们没有找到一个合适的合并 aarch32 和 aarch64 的办法，因为rtconfig.py 里不能引用 Kconfig 的配置选择 32/64 位，而 aarch32 和 aarch64 依赖不同的编译链， 从而 aarch32 和 aarch64 难以合并，注意到 rasp 的 32/64 位也是分开实现的。后续迭代版本时，如果有合适的办法，我们会设法合并

2022-11-07 03:09 UTC, zhugengyu commented on bsp/phytium/board/secondary_cpu.c
> +// #if defined(TARGET_ARMV8_AARCH64)
已经移除

2022-11-07 03:09 UTC, zhugengyu commented on bsp/phytium/aarch64/SConscript
> +cwd = str(Dir('#'))
已经参照 32 位修改

2022-11-08 00:41 UTC, zhugengyu commented on bsp/phytium/aarch32/boot/aarch32_boot.S
> +	mov      r1, #0
已修复

2022-11-09 13:46 UTC, supperthomas commented
standalone/doc里面文档相关的太多。建议删除

2022-11-09 23:43 UTC, mysterywolf commented
> standalone/doc里面文档相关的太多。建议删除

看了一下 不建议删除，都是精心编写过的

2022-11-09 23:48 UTC, mysterywolf approved these changes

2022-11-10 01:01 UTC, zhugengyu commented
> > standalone/doc里面文档相关的太多。建议删除
> 
> 看了一下 不建议删除，都是精心编写过的

是的，我们后续更新 phytium bsp 的时候也会更新这里面的文档

2022-11-10 03:07 UTC, mysterywolf approved these changes

2022-11-10 09:21 UTC, BernardXiong commented
> > 我们没有找到一个合适的合并 aarch32 和 aarch64 的办法，因为rtconfig.py 里不能引用 Kconfig 的配置选择 32/64 位，而 aarch32 和 aarch64 依赖不同的编译链， 从而 aarch32 和 aarch64 难以合并，注意到 rasp 的 32/64 位也是分开实现的。后续迭代版本时，如果有合适的办法，我们会设法合并

aarch32/64融合的事，可以未来一起来探讨

2022-11-10 09:21 UTC, BernardXiong approved these changes

2022-11-10 14:22 UTC, merged