[components][ulog]添加控制台滤波函数
RT-Thread/rt-thread pull request #6577
Opened 2022-11-01 02:44 UTC by wdfk-prog

## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-11-01 03:25 UTC, armink requested changes

2022-11-01 03:25 UTC, armink commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
- 问题1：总感觉这里的语义不太对，你的意图是使能或者失能 ulog 日志在 console 上的输出吧？好像用户不用关心过滤器这些细节，就不用增加过滤器的字样了。
- 问题2：如果用户想关心过滤器细节，是不是被过滤的字符串可以设置？
- 问题3：这里是不是少了个 #endif ？

2022-11-01 03:35 UTC, wdfk-prog commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
- 问题1：我的意图不是整个ulog日志都不输出或者都输出。
   而是用户先去实现滤波函数ulog_console_backend_filter。然后可以通过这个MSH命令来进行显示本来被滤波的内容或者禁用显示。
  比如我实现了特定标签不在控制台输出。但是有时候我又需要在控制台显示，通过这个命令就可以了。
- 问题2：这方面我没考虑，没去写。
   先放大概上去吧。主要还是加入个ulog_console_backend_filter给用户调用就好了。
   这个MSH命令是我用着想看日志不方便，顺便写的。
- 问题3：这个是我疏忽了。。。

2022-11-01 03:46 UTC, wdfk-prog commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
> * 问题1：总感觉这里的语义不太对，你的意图是使能或者失能 ulog 日志在 console 上的输出吧？好像用户不用关心过滤器这些细节，就不用增加过滤器的字样了。
> * 问题2：如果用户想关心过滤器细节，是不是被过滤的字符串可以设置？
> * 问题3：这里是不是少了个 #endif ？

我想了一下这个设置过滤字符串实现，如果想和ulog_console_backend_filter函数一样的使用的话，实现不了吧？
除非是ulog_console_backend_filter函数内部已经做好了实现，MSH命令只是把滤波的字符串给替换掉。这样得整一个全部变量

2022-11-01 03:54 UTC, armink commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
我感觉增加一个空的 WEAK 函数，让 ulog 的用法变复杂了，如果用户想设置后端过滤器，直接使用 ulog 自带的 ulog_backend_set_filter 函数即可，毕竟用法比较简单。重新实现一个 WEAK ，相当于还得让用户学习新接口，把事情搞复杂了。

2022-11-01 05:17 UTC, wdfk-prog commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
> 我感觉增加一个空的 WEAK 函数，让 ulog 的用法变复杂了，如果用户想设置后端过滤器，直接使用 ulog 自带的 ulog_backend_set_filter 函数即可，毕竟用法比较简单。重新实现一个 WEAK ，相当于还得让用户学习新接口，把事情搞复杂了。

- 如果是用户自己使用的文件后端，直接用ulog_backend_set_filter函数是方便的。
  但是控制台的文件后端是RTT自带的，ulog_backend console这个结构体是静态的。用户在外部无法使用ulog_backend_set_filter函数挂钩自己的滤波函数。
- 我加入这个WEAK就是想方便用户编写，一来不需要改动console_be.c文件。二来其实与使用ulog_backend_set_filter是一样的效果。我只是把用户自己添加ulog_backend_set_filter这个函数的步骤省了。不管使用ulog_backend_set_filter还是我这个WEAK，其实实现是一样的。
- 如果不想用WEAK函数，用户得这样写
```
rt_bool_t ulog_console_backend_filter(struct ulog_backend *backend, rt_uint32_t level, const char *tag, rt_bool_t is_raw, 
                                      const char *log, rt_size_t len)
{
    if (rt_strncmp(tag,MOTION_TAG, sizeof(MOTION_TAG)) == 0)//排除带有"MOVE"标签输出
      return RT_FALSE;
    else
      return RT_TRUE;
}
void test()
{
  ulog_backend_t file_be = ulog_backend_find("console");
  file_be->filter = ulog_console_backend_filter;
}
```
- 这样也用不了ulog_backend_set_filter函数。我是觉得定义一个WEAK函数比较方便。按我上述写法，失去了ulog_backend_set_filter函数的意义了。

2022-11-01 05:20 UTC, wdfk-prog commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
其实吧，ulog_backend_filter_t这个函数该如何实现，实际上没有注释也没有文档说明的。
只能靠自己看ulog源码才明白该做什么。T_T

2022-11-01 05:44 UTC, armink commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
是的，这个可能是本质的原因 ;>

缺少：
- 后端过滤器的使用文档
- 文件后端的使用文档

2022-11-09 03:11 UTC, wdfk-prog commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
> 是的，这个可能是本质的原因 ;>
> 
> 缺少：
> 
> * 后端过滤器的使用文档
> * 文件后端的使用文档

请问这个PR可以合并吗？不行的话我关闭了

2022-11-09 06:14 UTC, armink commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
先关闭吧，后面文档事情可以独立一个议题记录一下

2022-11-09 06:15 UTC, wdfk-prog commented on components/utilities/ulog/backend/console_be.c
> +MSH_CMD_EXPORT_ALIAS(ulog_console_backend_filter_set,console_filter,console filter [option] optino:enable or disable);
> 先关闭吧，后面文档事情可以独立一个议题记录一下

OK

2022-11-09 06:15 UTC, closed without merging

2022-11-09 06:26 UTC, mysterywolf commented
https://gitee.com/rtthread/docs-online/issues 文档的问题可以在这里记录一下 提个issue

2022-11-09 06:31 UTC, wdfk-prog commented
>https://gitee.com/rtthread/docs-online/issues/I609KK

2022-11-09 06:31 UTC, wdfk-prog commented
> https://gitee.com/rtthread/docs-online/issues 文档的问题可以在这里记录一下 提个issue

> https://gitee.com/rtthread/docs-online/issues/I609KK