[fix][dfs]修复list_fd导致系统卡死问题
RT-Thread/rt-thread pull request #6578
Opened 2022-11-01 03:08 UTC by wdfk-prog

## 拉取/合并请求描述：(PR description)

[
### 为什么提交这份PR；
- list_fd导致系统卡死问题
> https://club.rt-thread.org/ask/question/74e15e3e942102fc.html
> https://club.rt-thread.org/ask/question/97ed3d005d24ecc7.html
### 你的解决方案是什么；
- 进入临界段后, 先将信息打印到buff, 退出临界段后, 将buff中的信息进行进行rt_kprintf. 
### 并确认并列出已经在什么情况或板卡上进行了测试。
- STM32F429IGT6
- RTT V4.1.1
![image](https://user-images.githubusercontent.com/66928464/199150137-41efb5e5-ba96-4a61-8b86-6d86111cc447.png)
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-11-01 03:15 UTC, mysterywolf requested changes

2022-11-01 03:15 UTC, mysterywolf commented on components/dfs/src/dfs.c
> +            else if (fd->type == FT_DEVICE)   buff += rt_sprintf(buff,"%-7.7s ", "device");
请注意逗号之后空一个格

2022-11-01 03:15 UTC, mysterywolf commented on components/dfs/src/dfs.c
> +    char *buff = rt_malloc(1024);
malloc空间，但是没有free掉。此外这个1024是经过一些计算得到的，还是随便分配的。太大了...

2022-11-01 03:18 UTC, wdfk-prog commented on components/dfs/src/dfs.c
> +    char *buff = rt_malloc(1024);
> malloc空间，但是没有free掉。此外这个1024是经过一些计算得到的，还是随便分配的。太大了...

随便分配的。

2022-11-01 03:24 UTC, wdfk-prog commented on components/dfs/src/dfs.c
> +    char *buff = rt_malloc(1024);
> malloc空间，但是没有free掉。此外这个1024是经过一些计算得到的，还是随便分配的。太大了...

这个只算临时的解决办法。起码不会卡死系统了。

2022-11-01 03:24 UTC, mysterywolf commented on components/dfs/src/dfs.c
> +    char *buff = rt_malloc(1024);
嗯 确实是，这块如果内存不够就直接越界gg了。

2022-11-01 13:16 UTC, BernardXiong commented
这么简单修不是办法的，可以多看看其他方式。整体也会包括，rt-thread中系列的list_object合理的模式是什么样的才好

2022-11-10 03:41 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/pull/6606
感谢提交PR 该问题已经在此处得到解决。

2022-11-10 03:41 UTC, closed without merging