[bsp][ch32v307]适配RT-duino框架
RT-Thread/rt-thread pull request #6669
Opened 2022-11-29 10:03 UTC by hg0720

## 拉取/合并请求描述：(PR description)

[
为ch32v307适配rt-duino，支持pwm、gpio、uart、iic，暂不支持 spi。
已在ch32v307评估板测试。
测试内容包括串口打印、呼吸灯、AHT10温湿度读取等。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-11-30 08:19 UTC, liYony commented
如果功能都测试通过的话，可以试着写一份readme上来

2022-12-01 00:34 UTC, mysterywolf requested changes

2022-12-01 00:34 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/pins_arduino.h
> +/* i2c1 : xxx-SDA xxx-SCL */
这个位置需要把xxx替换成ch32引脚编号

2022-12-01 00:35 UTC, mysterywolf commented
有时间麻烦微信叫我一下 这个需要拉个会议一起review一下

2022-12-04 00:26 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/applications/arduino_main.cpp
> +    pinMode(LED_BUILTIN, OUTPUT);
这个LED是不是被主线程占住了，如果被用了的话，就用Serial.print('Hello RTduino' ) 的例子吧

2022-12-04 00:26 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/Sconscript
> +group = DefineGroup('Arduino', src, depend = ['PKG_USING_RTDUINO'], CPPPATH = inc)
```suggestion
group = DefineGroup('RTduino', src, depend = ['PKG_USING_RTDUINO'], CPPPATH = inc)
```

2022-12-04 00:26 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
> -                    comment "Notice: PC7 --> 39; PC6 --> 38"
这原来是哪个位置的？

2022-12-04 03:51 UTC, hg0720 commented on bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
> -                    comment "Notice: PC7 --> 39; PC6 --> 38"
这地方是kconfig里面模拟iic的默认引脚，现在改成了arduino接口上的iic引脚

2022-12-04 03:51 UTC, hg0720 commented on bsp/wch/risc-v/ch32v307v-r1/applications/arduino_main.cpp
> +    pinMode(LED_BUILTIN, OUTPUT);
主线程使用的rt_kprintf("Hello RT-Thread!\n");

2022-12-27 07:44 UTC, mysterywolf approved these changes

2022-12-27 07:45 UTC, merged