[risc-v/libcpu] port rv64 cpu code
RT-Thread/rt-thread pull request #6704
Opened 2022-12-07 09:55 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

merge rt-thread/rt-smart virt64 libcpu code

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-12-07 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6704) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6704) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6704) it.</sub>

2022-12-08 01:46 UTC, Guozhanxin commented
现在开不开lwp，bsp都可以用了吗

2022-12-08 03:23 UTC, polarvid commented
通过如下选项 开启/关闭 smart 特性

* RT_USING_SMART
* RT_USING_USERSPACE
* RT_USING_LWP

2022-12-08 04:19 UTC, BernardXiong commented
尽可能不使用RT_USING_USERSPACE吧，这个宏指的是：启用应用程序的独立用户态内存空间。而对于smart来说，目前有MMU的芯片都会以独立用户态内存空间方式而存在。也就是说，RT_USING_SMART + ARCH_MM_MMU就一定会开启独立用户态内存空间。

2022-12-08 05:44 UTC, BernardXiong commented
```bash
/home/runner/work/rt-thread/rt-thread/libcpu/risc-v/virt64/trap.c: In function 'handle_trap':
/home/runner/work/rt-thread/rt-thread/libcpu/risc-v/virt64/trap.c:295:17: warning: implicit declaration of function 'handle_user' [-Wimplicit-function-declaration]
  295 |                 handle_user(scause, stval, sepc, sp);
      |                 ^~~~~~~~~~~
/home/runner/work/rt-thread/rt-thread/libcpu/risc-v/virt64/trap.c:299:2: error: #endif without #if
  299 | #endif /* RT_USING_USERSPACE */
      |  ^~~~~
scons: *** [build/kernel/libcpu/risc-v/virt64/trap.o] Error 1
```

2022-12-08 06:48 UTC, polarvid commented
已更换为检查 `RT_USING_SMART` 方式

2022-12-08 08:36 UTC, Guozhanxin commented
![image](https://user-images.githubusercontent.com/25633294/206398505-2662b829-982a-452f-b1d0-ad5d5c26514f.png)

2022-12-08 10:52 UTC, polarvid commented
修复一处 uart 和 plic 的问题 [https://github.com/polarvid/rt-thread/commit/af92164e88afccd9f9f31fc54dd003b823ff1ab8](https://github.com/polarvid/rt-thread/commit/af92164e88afccd9f9f31fc54dd003b823ff1ab8)

2022-12-08 12:19 UTC, BernardXiong requested changes

2022-12-08 12:19 UTC, BernardXiong commented on include/rtdef.h
> +    #define rt_using_smart (1)
为什么会定义这个宏？

2022-12-08 12:19 UTC, BernardXiong commented on libcpu/risc-v/virt64/trap.c
> +    if (rt_using_smart)
仅这里使用？感觉不需要，或者使用宏的方式？

2022-12-08 12:35 UTC, polarvid commented on libcpu/risc-v/virt64/trap.c
> +    if (rt_using_smart)
希望能够减小函数里面使用的条件编译宏。条件编译用在整个函数外面或者不使用会让代码可读性提高很多。不过如果能调整一下Kconfig，用类似方式实现就不用定义这些了 [https://github.com/RT-Thread/rt-thread/issues/6335](https://github.com/RT-Thread/rt-thread/issues/6335)

2022-12-09 06:41 UTC, Guozhanxin commented on libcpu/risc-v/virt64/trap.c
> +    if (rt_using_smart)
这个pr什么时候可以合并啊

2022-12-09 06:57 UTC, polarvid commented
已从redef移除相关定义

2022-12-10 14:16 UTC, BernardXiong approved these changes

2022-12-10 14:16 UTC, merged