add nrf5340 bsp,add uarte and gpio drv for 5340
RT-Thread/rt-thread pull request #6709
Opened 2022-12-08 06:58 UTC by guangli2015

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
增加 NORDIC NRF5340 bsp ,以及uarte 和 GPIO driver

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)
在 nRF5340-PCA10095 NORDIC 官方开发板(https://www.nordicsemi.com/Products/Development-hardware/nRF5340-DK)测试通过
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-12-08 06:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6709) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6709) it.</sub>

2022-12-08 07:47 UTC, supperthomas requested changes

2022-12-08 07:47 UTC, supperthomas commented on bsp/nrf5x/nrf5340/README.md
> +| 支持开发板型号                                               | 开发板上外设                | 备注                                |
readme 还是NRF52840.
可以更新一下，联系人可以写自己

2022-12-08 07:47 UTC, supperthomas commented on bsp/nrf5x/nrf5340/board/board.c
> + * 2020-04-29     supperthomas fix component init
这里新建的文件，change log 作者可以改成第一个提交的。

2022-12-08 07:47 UTC, supperthomas commented on bsp/nrf5x/nrf5340/project.uvguix.andrewli
> +<ProjectGui xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project_guix.xsd">
一些不用的文件可以清理掉。参考其他bsp/nrf5x/nrf52840

2022-12-09 02:42 UTC, supperthomas requested changes

2022-12-09 02:42 UTC, supperthomas commented on bsp/nrf5x/nrf5340/applications/application - Copy.cccc
> +
这个文件名？copy.ccc

2022-12-09 02:42 UTC, supperthomas commented on bsp/nrf5x/nrf5340/flash.bat
> +::url = https://gitee.com/andrewliNordic/rt_thread_porting_to_nrf5340.git
这个文件flash.bat 需要用么？需要的话，readme里面可以加一下如何使用。

2022-12-09 02:46 UTC, supperthomas commented
@guangli2015 感谢贡献，请帮忙签一下CLA。

https://github.com/mysterywolf/formatting
如果不需要格式化的可以用.ignore_format.yml
参考：
https://github.com/RT-Thread/rt-thread/tree/master/bsp/lpc55sxx/Libraries

2022-12-09 06:40 UTC, guangli2015 commented on bsp/nrf5x/nrf5340/applications/application - Copy.cccc
> +
deleted

2022-12-09 06:41 UTC, guangli2015 commented
> @guangli2015 感谢贡献，请帮忙签一下CLA。
> 
> 需要格式化代码。 https://github.com/mysterywolf/formatting 如果不需要格式化的可以用.ignore_format.yml 参考： https://github.com/RT-Thread/rt-thread/tree/master/bsp/lpc55sxx/Libraries

已完成

2022-12-09 06:42 UTC, guangli2015 commented
> > @guangli2015 感谢贡献，请帮忙签一下CLA。
CLA签完了
> > 需要格式化代码。 https://github.com/mysterywolf/formatting 如果不需要格式化的可以用.ignore_format.yml 参考： https://github.com/RT-Thread/rt-thread/tree/master/bsp/lpc55sxx/Libraries
> 
> 已完成

2022-12-09 06:46 UTC, supperthomas approved these changes

2022-12-09 10:52 UTC, supperthomas commented
我这边没太大问题了。

2022-12-09 12:55 UTC, merged