[bsp][nrf5340]add 5340 define for 1000000 baud rate;change RTC driver for 5340
RT-Thread/rt-thread pull request #6754
Opened 2022-12-19 02:26 UTC by guangli2015

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
add 5340 define for 1000000 baud rate;change RTC driver for 5340

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)
[PCA10095](https://www.nordicsemi.com/Products/Development-hardware/nRF5340-DK)
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-12-19 02:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6754) it.</sub>

2022-12-19 12:53 UTC, supperthomas approved these changes

2022-12-20 02:00 UTC, supperthomas commented
@guangli2015

2022-12-20 02:11 UTC, supperthomas requested changes

2022-12-20 02:58 UTC, supperthomas requested changes

2022-12-20 02:58 UTC, supperthomas commented on bsp/nrf5x/nrf5340/.config
>  #
.config project.uvoptx project.uvprojx rtconfig.h 这几个文件如果没有特殊需要，可以不用提交。让用户自己生成就好了。

2022-12-20 05:11 UTC, guangli2015 commented
> 



> CI 问题解决一下。adc可以先默认不打开。
pwm rtc saadc wdt timer qspi 都可以工作了

2022-12-20 09:41 UTC, supperthomas approved these changes

2022-12-20 11:46 UTC, guangli2015 commented
CLA 签过了 怎么还pending？@supperthomas

2022-12-21 00:48 UTC, supperthomas commented
@guangli2015 CLA 问题检查一下以下邮箱和用户名是否都一致：
1. github登录使用的邮箱和用户名。和`git config --global --list` 里面的邮箱和用户名是否都一致
你可以找下github的邮箱和用户名。
git config --global --list下面的用户名。
如果不一样，需要本地执行下面命令，修改一下，然后push
git commit --amend --no-edit --author="User Name <user@exmaple.com>"
以后提交也需要两个一致，CLA才能判定同一个人。

2022-12-21 01:02 UTC, mysterywolf commented
CLA的问题不用解决，应该是git提交的邮箱和github的邮箱不是一个导致的. 涛哥，如果没有啥问题请+1

2022-12-21 01:07 UTC, supperthomas commented
+1

2022-12-21 01:11 UTC, mysterywolf approved these changes

2022-12-21 01:11 UTC, merged