[BSP][smart] fix link script for smart in vexpress-a9
RT-Thread/rt-thread pull request #6764
Opened 2022-12-21 01:18 UTC by BernardXiong

## 拉取/合并请求描述：(PR description)

Fix smart link script for vexpress a9.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2022-12-21 01:34 UTC, mysterywolf requested changes

2022-12-21 01:34 UTC, mysterywolf commented on bsp/qemu-vexpress-a9/rtconfig.py
> +    PREFIX  = os.getenv('RTT_CC_PREFIX') or 'arm-none-eabi-'
```suggestion
    PREFIX  = os.getenv('RTT_CC_PREFIX') or os.getenv('RTT_EXEC_PREFIX') or 'arm-none-eabi-'
```

2022-12-21 01:34 UTC, mysterywolf commented on bsp/qemu-vexpress-a9/rtconfig.py
> +    PREFIX  = os.getenv('RTT_CC_PREFIX') or 'arm-none-eabi-'
这个名字一会RTT_EXEC开头例如RTT_EXEC_PATH 一会RTT_CC_xxx 名字太随意了

2022-12-21 01:37 UTC, mysterywolf requested changes

2022-12-21 01:37 UTC, mysterywolf commented on components/libc/compilers/common/include/sys/time.h
> +struct itimerspec;
这个应该在.h定义完整的struct结构
```c
struct itimerspec
{
	struct timespec	it_interval;
	struct timespec	it_value;
};
```

2022-12-21 06:12 UTC, BernardXiong commented on components/libc/compilers/common/include/sys/time.h
> +struct itimerspec;
不是，这里是前向结构体声明，不是定义。定义有些场合由工具链给出，有些场合在本文件中给出。

2022-12-21 06:14 UTC, BernardXiong commented on bsp/qemu-vexpress-a9/rtconfig.py
> +    PREFIX  = os.getenv('RTT_CC_PREFIX') or 'arm-none-eabi-'
因为有RTT_CC=gcc，所以这里的RTT_CC_PREFIX是指的工具链前缀，另外两个架构BSP应该都是这个名字。然后RTT_EXEC_PATH，更改成RTT_CC_PATH也可以，不过改的地方就有些多了，特别有些还是外部工具。

2022-12-21 20:56 UTC, mysterywolf commented on bsp/qemu-vexpress-a9/rtconfig.py
> +    PREFIX  = os.getenv('RTT_CC_PREFIX') or 'arm-none-eabi-'
哇 这就痛苦了

2022-12-21 20:56 UTC, mysterywolf commented on components/libc/compilers/common/include/sys/time.h
> +struct itimerspec;
OK~

2022-12-22 02:08 UTC, mysterywolf commented on bsp/qemu-vexpress-a9/rtconfig.py
> +    PREFIX  = os.getenv('RTT_CC_PREFIX') or 'arm-none-eabi-'
要不就像我给出的suggestion一样 RTT_CC_ 和RTT_EXEC_等效 作为别名？

2022-12-28 07:52 UTC, BernardXiong commented on bsp/qemu-vexpress-a9/rtconfig.py
> +    PREFIX  = os.getenv('RTT_CC_PREFIX') or 'arm-none-eabi-'
要做别名就加RTT_CC_PATH吧，然后暂时保留RTT_EXEC_PATH

2022-12-29 02:30 UTC, mysterywolf commented on bsp/qemu-vexpress-a9/rtconfig.py
> +    PREFIX  = os.getenv('RTT_CC_PREFIX') or 'arm-none-eabi-'
好

2022-12-29 03:12 UTC, mysterywolf approved these changes

2022-12-29 07:18 UTC, merged