更新ch32v307的RTduino的readme文件
RT-Thread/rt-thread pull request #6827
Opened 2023-01-08 08:22 UTC by Harrypotter-zhs

## 拉取/合并请求描述：(PR description)

[
请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;
：更新ch32v307的rtduino的readme文件，暂时之后中文，随后更新英文版本

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested. -->

#### 为什么提交这份PR (why to submit this PR)
更新ch32v307的rtduino的readme文件

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-01-08 17:10 UTC, mysterywolf requested changes

2023-01-08 17:10 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/README.md
> +该BSP遵照Arduino UNO板的引脚排列方式，并扩展增加了潘多拉自身的板载资源功能引脚。详见 `pins_arduino.c`
潘多拉貌似没有删掉

2023-01-08 17:10 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/README.md
> +该BSP遵照Arduino UNO板的引脚排列方式，并扩展增加了潘多拉自身的板载资源功能引脚。详见 `pins_arduino.c`
需要补充一份引脚布局图 参见：https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README_zh.md

2023-01-09 13:54 UTC, Harrypotter-zhs commented on bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/README.md
> +该BSP遵照Arduino UNO板的引脚排列方式，并扩展增加了潘多拉自身的板载资源功能引脚。详见 `pins_arduino.c`
嗯啊，我查查怎么制作这个引脚布局图，稍后再改

2023-01-10 02:41 UTC, mysterywolf approved these changes

2023-01-10 02:41 UTC, merged