[rt-smart] porting c906 and BSPs to mm
RT-Thread/rt-thread pull request #6848
Opened 2023-01-12 09:11 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

Porting rv64 c906 and BSPs to mm

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-01-12 09:40 UTC, polarvid commented
[https://github.com/RT-Thread/rt-thread/pull/6847](https://github.com/RT-Thread/rt-thread/pull/6847)

2023-01-13 00:56 UTC, BernardXiong requested changes

2023-01-13 00:56 UTC, BernardXiong commented on components/mm/mm_page.c
> +        while (1) ;
如果`while(1);`出错，请调整成`ASSERT(0);`吧。

2023-01-13 00:56 UTC, BernardXiong commented on libcpu/risc-v/t-head/c906/tlb.h
> +        rt_kprintf("%s failed\n", __FUNCTION__);
感觉还是LOG_W或LOG_E更合适

2023-01-13 01:28 UTC, polarvid commented on components/mm/mm_page.c
> +        while (1) ;
因为这个函数是比串口设备更早的初始化阶段，所以用`ASSERT(0)`有个比较尴尬的点是出错了能得到的信息很少。看寄存器的话，定位到的pc在handler里面。这样反而还要想办法找到真正的出错pc，比较麻烦。

2023-01-14 03:02 UTC, BernardXiong commented on components/mm/mm_page.c
> +        while (1) ;
有可能是这样，但在这里`while(1);`一样不会有什么输出信息呀

2023-01-14 03:03 UTC, BernardXiong commented on components/mm/mm_page.c
> +        while (1) ;
ASSERT最终也是`while(1);`，所以如果可以栈回溯或带调试器，这里也一样的会看出来

2023-01-16 00:23 UTC, BernardXiong approved these changes

2023-01-16 00:24 UTC, merged