[bsp&bug fix] wch ch32v307v-r1
RT-Thread/rt-thread pull request #6849
Opened 2023-01-12 10:10 UTC by gaojingqi23

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
- 修复ch32v307v-r1 board.h 中变量_stack_size为声明BUG
- 提供ch32v307v-r1动态堆内存分配代码

#### 你的解决方案是什么 (what is your solution)
- 已测试通过

#### 在什么测试环境下测试通过 (what is the test environment)
- 开发工具: RT-Thread Studio
- 测试板卡：ch32v307v-r1评估板
- 烧录工具：WCHISPStudio
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-01-12 10:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6849) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6849) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6849) it.</sub>

2023-01-12 10:52 UTC, gaojingqi23 reviewed
新增烧录方式，作为烧录后无运行结果的替代方案

2023-01-12 16:05 UTC, mysterywolf requested changes

2023-01-12 16:05 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/board/board.h
> + // <<< Use Configuration Wizard in Context Menu >>>
这里请删除掉空格，另外请顺便将//改为/**/

2023-01-12 16:06 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/board/board.h
> + // <<< Use Configuration Wizard in Context Menu >>>
直接继续push commits就可以了，不需要关闭PR重新提交

2023-01-12 16:06 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/board/board.h
> + // <<< Use Configuration Wizard in Context Menu >>>
CI 报错不需要理会

2023-01-12 16:09 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v307v-r1/board/board.c
> +static uint32_t rt_heap[RT_HEAP_SIZE];     // heap default size: 16K(4096 * 4)
请使用/**/注释

2023-01-13 07:00 UTC, gaojingqi23 commented on bsp/wch/risc-v/ch32v307v-r1/README.md
> -CH32V307V-R1 is a RISC-V core-based development board with a maximum main frequency of 144Mhz. It delivers the best value for developers to try and get started with RISC-V architecture.
这些空格是代码格式化自动添加的，下次尽量不会出现这些问题

2023-01-13 11:59 UTC, gaojingqi23 commented
先关闭了，master没同步

2023-01-13 14:27 UTC, mysterywolf approved these changes

2023-01-13 18:05 UTC, mysterywolf commented
RT_HEAP_SIZE USING_MAX_HEAP_SIZE  这个可以删掉了 直接保持heap最大化即可。

2023-01-13 19:10 UTC, mysterywolf commented
可以参考STM32的写法：https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f103-100ask-mini/board/board.h#L39

2023-01-14 01:13 UTC, mysterywolf approved these changes

2023-01-14 01:50 UTC, merged

2023-01-14 01:50 UTC, mysterywolf commented
感谢贡献PR!