[bsp/bl808] add: drv_gpio
RT-Thread/rt-thread pull request #6856
Opened 2023-01-15 05:48 UTC by Z8MAN8

## 拉取/合并请求描述：(PR description)

[

在bl808开发板上进行测试
#### 为什么提交这份PR (why to submit this PR)
添加gpio驱动

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-01-15 12:02 UTC, mysterywolf commented
请刷一下格式 https://github.com/mysterywolf/formatting

2023-01-15 16:05 UTC, Z8MAN8 commented
> 请刷一下格式 https://github.com/mysterywolf/formatting

已格式化

2023-01-15 18:44 UTC, mysterywolf approved these changes

2023-01-16 00:28 UTC, BernardXiong commented
可以增加忽略，bl808的库代码可以排除在外。这样库代码后续跟着官方一起更新即可

2023-01-16 00:37 UTC, mysterywolf commented
忽略已经加了，只不过他扩大了format的范围，format多了，但是没有什么大问题。

2023-01-16 02:07 UTC, mysterywolf requested changes

2023-01-16 02:07 UTC, mysterywolf commented on bsp/bl808/m0/drivers/drv_gpio.c
> +#define LOG_TAG                "drv.gpio"
```suggestion
#define DBG_TAG              "drv.gpio"
#define DBG_LVL               DBG_INFO
#include <rtdbg.h>
```

2023-01-16 02:08 UTC, mysterywolf requested changes

2023-01-16 02:08 UTC, mysterywolf commented on bsp/bl808/m0/drivers/drv_gpio.c
> +            } else if (mode == GPIO_SYNC_RISING_TRIGER_INT_MODE) {
rt-thread的代码风格是
{

}

2023-01-16 02:08 UTC, mysterywolf commented on bsp/bl808/m0/drivers/drv_gpio.c
> +
删除无用空行

2023-01-16 02:08 UTC, mysterywolf commented on bsp/bl808/m0/drivers/drv_gpio.c
> +//irq handle
注释使用/**/

2023-01-16 04:30 UTC, mysterywolf requested changes

2023-01-16 04:30 UTC, mysterywolf commented on bsp/bl808/m0/drivers/drv_gpio.c
> +struct gpio_int_cfg_private {
格式还是有问题，我没有表达清楚，这个花括号要放下来
```suggestion
struct gpio_int_cfg_private
{
```

整个文件都是同理，花括号要独占一行

2023-01-16 04:30 UTC, mysterywolf commented on bsp/bl808/m0/drivers/drv_gpio.c
> +        GLB_GPIO_Cfg_Type gpio_cfg;
这里缩进有问题

2023-01-16 04:39 UTC, mysterywolf approved these changes

2023-01-16 04:41 UTC, merged