[BSP][nrf5340] add spi twi drv for nrf5340
RT-Thread/rt-thread pull request #6880
Opened 2023-01-28 09:56 UTC by guangli2015

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
add spi twi drv for nrf5340

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)
Nordic nrf 5340 DK (PCA10095)
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [X] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [X] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [X] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [X] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [X] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [X] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [X] 代码是高质量的 Code in this PR is of high quality
- [X] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-01-28 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6880) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=6880) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=6880) it.</sub>

2023-01-29 06:39 UTC, supperthomas requested changes

2023-01-29 06:39 UTC, supperthomas commented on bsp/nrf5x/libraries/drivers/drv_spi.c
> +    nrfx_spim_config_t config = NRFX_SPIM_DEFAULT_CONFIG(bsp_spi_pin[index].sck_pin,
这里的drv_spi.c 很多都没有共用，建议加两个drv_spim.c drv_spim.h 区分开来，这样便于管理。在nrf5340那里通过kconfig区分开来。这样是否可行？

2023-01-29 09:27 UTC, supperthomas approved these changes

2023-01-30 02:30 UTC, mysterywolf approved these changes

2023-01-30 02:30 UTC, merged