Improve timer accuracy and realize
RT-Thread/rt-thread pull request #6926
Opened 2023-02-11 03:25 UTC by zhkag

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-02-11 09:14 UTC, BernardXiong commented on include/rtthread.h
> +#ifdef RT_USING_CPUTIME
为什么加在这里？

2023-02-13 02:21 UTC, zhkag commented on include/rtthread.h
> +#ifdef RT_USING_CPUTIME
已经改了

2023-02-13 03:01 UTC, heyuanjie87 commented
cputime的初始化可以先放在bsp

2023-02-13 03:01 UTC, heyuanjie87 commented
cputime的初始化可以先放在bsp

2023-02-13 03:02 UTC, heyuanjie87 commented
cputime的初始化可以先放在bsp

2023-02-13 05:33 UTC, Guozhanxin commented on src/timer.c
> +#ifdef RT_USING_CPUTIME
在源码那里，自动初始化好了

2023-02-13 05:36 UTC, Guozhanxin commented on components/drivers/cputime/cputime.c
> +    return RT_NULL;
这个返回值不太对啊，是返回真假？还是成功失败？

2023-02-13 06:10 UTC, Guozhanxin commented
对了，cputimer 的文档也需要写一份。提交到文档中心

2023-02-13 07:49 UTC, Guozhanxin approved these changes

2023-02-13 08:25 UTC, BernardXiong commented
cputime，cputimer？好具备迷惑性，或者cputime_timer？

2023-02-13 08:56 UTC, zhkag commented
> cputime，cputimer？好具备迷惑性，或者cputime_timer？

改完之后也挺迷惑的

![image](https://user-images.githubusercontent.com/62738223/218413567-ce454f99-30fd-4451-945e-85e77145baed.png)

2023-02-14 15:03 UTC, BernardXiong commented
@mysterywolf 对名字这块有洁癖，有建议的吗？

2023-02-14 16:37 UTC, mysterywolf commented
好  我晚上看一下

2023-02-14 22:35 UTC, mysterywolf commented
@zhkag 请稍微写一下PR的描述

2023-02-14 22:38 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +        uint64_t cpu_tick_old = clock_cpu_gettime();
除非POSIX或者ISO-ANSI兼容，建议用rt_uint64_t 其会自动匹配libc的数据类型或使用自己独立的类型
```suggestion
        rt_uint64_t cpu_tick_old = clock_cpu_gettime();
```

2023-02-14 22:40 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +            nanoseconds = (((remaining % RT_TICK_PER_SECOND) * MILLISECOND_PER_SECOND) * MICROSECOND_PER_SECOND) / RT_TICK_PER_SECOND ;
```suggestion
            nanoseconds = (((remaining % RT_TICK_PER_SECOND) * MILLISECOND_PER_SECOND) * MICROSECOND_PER_SECOND) / RT_TICK_PER_SECOND;
```

2023-02-14 22:42 UTC, mysterywolf commented
我个人建议cputime_timer 直接缩写成cputimer即可，rt_cputimer_create 。这个与cputime之前没有太多的迷惑性，rt_cputime_timer有些啰嗦。

2023-02-14 22:44 UTC, mysterywolf commented
后续rt_hw_delay_us可否直接调用cputime框架 或者说 rt_hw_delay_us的内容可以整合作为cputime的驱动

2023-02-15 03:13 UTC, mysterywolf approved these changes

2023-02-15 05:39 UTC, BernardXiong commented on components/drivers/cputime/cputimer.c
> +    rt_list_init(&_cputimer_list);
可以直接初始化，而不需要用函数初始化

2023-02-15 06:49 UTC, BernardXiong requested changes

2023-02-15 06:53 UTC, zhkag commented on components/drivers/cputime/cputimer.c
> +#ifdef RT_USING_CPUTIME
依赖于 CPUTIME 的

2023-02-15 07:39 UTC, BernardXiong commented on components/drivers/cputime/cputimer.c
> +#ifdef RT_USING_CPUTIME
我的理解是完全依赖，这样的话，这个`#ifdef RT_USING_CPUTIME`就不仅仅是头文件包含的事情，而是整体的依赖关系。

2023-02-15 07:44 UTC, zhkag commented on components/drivers/cputime/cputimer.c
> +#ifdef RT_USING_CPUTIME
这里是赘余了，不定义 RT_USING_CPUTIME 整个文件都不会编译

2023-02-15 09:26 UTC, heyuanjie87 commented
里面tick的含义不太清晰，它到底表示ns us等时间单位还是定时器硬件计数器的值。
这里建议定义成时间

2023-02-15 09:32 UTC, zhkag commented
> 里面tick的含义不太清晰，它到底表示ns us等时间单位还是定时器硬件计数器的值。 这里建议定义成时间

tick 表示的是 定时器硬件计数器的值 时间相关的都是使用的 ns us ms 等变量表示的

2023-02-15 09:44 UTC, heyuanjie87 commented
rt_cputimer_create并没申请内存，不如叫init

2023-02-15 09:50 UTC, heyuanjie87 commented
void rt_cputimer_create(rt_cputimer_t timer,
                             const char *name,
                             void (*timeout)(void *parameter),
                             void *parameter,
                             rt_uint64_t time,
                             rt_uint8_t flag)

这个time 也改成tick统一点

2023-02-15 12:46 UTC, BernardXiong approved these changes

2023-02-15 12:46 UTC, merged