[修改pin数据类型]
RT-Thread/rt-thread pull request #6934
Opened 2023-02-17 05:55 UTC by ZosCat1

## 拉取/合并请求描述：(PR description)

[

STM32
#### 为什么提交这份PR (why to submit this PR)
[修改pin数据类型]

#### 你的解决方案是什么 (what is your solution)
[修改pin数据类型]

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-02-18 08:34 UTC, mysterywolf requested changes

2023-02-18 08:34 UTC, mysterywolf commented on components/drivers/include/drivers/pin.h
>      rt_err_t (*pin_irq_enable)(struct rt_device *device, rt_base_t pin, rt_uint32_t enabled);
enabled的这个也是8位就够了，我只指出来一处，后面应该还有

```suggestion
    rt_err_t (*pin_irq_enable)(struct rt_device *device, rt_base_t pin, rt_uint8_t enabled);
```

2023-02-18 08:34 UTC, mysterywolf commented on components/drivers/include/drivers/pin.h
>  rt_base_t rt_pin_get(const char *name);
/* Get pin number by name, such as PA.0, P0.12 */ 这个注释放到.c这个函数的脑袋顶上就可以了

```suggestion
rt_base_t rt_pin_get(const char *name);
```

2023-02-18 08:34 UTC, mysterywolf commented on components/drivers/include/drivers/pin.h
>  struct rt_pin_irq_hdr
```c
struct rt_device_pin_value
{
    rt_base_t pin;
    rt_uint8_t value; /* PIN_LOW or PIN_HIGH */
};
```

2023-02-18 08:34 UTC, mysterywolf commented on components/drivers/include/drivers/pin.h
> +    rt_uint8_t mode;
```suggestion
    rt_uint8_t mode; /* e.g. PIN_MODE_OUTPUT */
```

2023-02-18 08:34 UTC, mysterywolf commented on components/drivers/include/drivers/pin.h
> +    rt_uint8_t       mode;
```suggestion
    rt_uint8_t       mode; /* e.g. PIN_IRQ_MODE_RISING */
```

2023-02-18 19:26 UTC, mysterywolf commented on components/drivers/include/drivers/pin.h
>      int (*pin_read)(struct rt_device *device, rt_base_t pin);
```suggestion
    rt_int8_t (*pin_read)(struct rt_device *device, rt_base_t pin);
```

2023-02-18 19:26 UTC, mysterywolf commented on components/drivers/include/drivers/pin.h
>      int (*pin_read)(struct rt_device *device, rt_base_t pin);
int rt_pin_read(rt_base_t pin) -> rt_int8_t rt_pin_read(rt_base_t pin) rt_int8_t有符号类型，>=0返回高低状态 <0返回错误码

2023-02-21 01:46 UTC, Guozhanxin commented
有没有什么好处，没好处的话，这么改，感觉没必要。

1. 解决了什么问题？
2. 兼容性，向前兼容，向后兼容？

2023-02-21 01:48 UTC, mysterywolf commented
解决了数据类型混乱的问题，历史问题。5.0.0不考虑向前兼容性。但是本修改对前向兼容影响不大。

2023-02-21 03:03 UTC, Guozhanxin commented
> 解决了数据类型混乱的问题，历史问题。5.0.0不考虑向前兼容性。但是本修改对前向兼容影响不大，都是本仓库自己内部的问题。

数据类型混乱是什么问题？会造成什么后果吗？

2023-02-21 03:08 UTC, mysterywolf commented
问题主要为：
1. pin的数据类型有些采用uint16 有些使用rt_bsse_t, 还有些采用int16_t，这个之前和你讨论过，应该统一为rt_base_t，因为有些bsp是按照顺序排下来的，还有一些是采用位域的方式处理的比如英飞凌。
2. 部分变量使用的数据类型明显超过其所需，例如enabled变量使用的是一个rt_uint32_t，但是这个变量只需要存储enable/disable二值即可，结果搞了个32位的整形。
修改均是一些非重大影响，但是看起来非常难受的问题。影响到sensor框架重构。

2023-02-21 03:59 UTC, Guozhanxin commented on components/drivers/include/drivers/pin.h
> -struct rt_device_pin_status
这个变量名感觉还是之前的比较好理解，引脚的状态，比引脚的值，更清晰一点吧。返回值也是高低电平这种的。

或者说，为什么要改成值的表述，读回来的数据不能代表引脚输出电平的高低吗？

2023-02-23 18:43 UTC, mysterywolf requested changes

2023-02-23 18:43 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
>      uint16_t gpio_pin;
这个数据类型不对

2023-02-24 06:30 UTC, mysterywolf approved these changes

2023-02-27 01:57 UTC, Guozhanxin approved these changes

2023-02-27 02:17 UTC, merged