[spi] 优化SPI设备框架中，对函数返回值类型使用不恰当的情况
RT-Thread/rt-thread pull request #6937
Opened 2023-02-18 05:24 UTC by liYony

## 拉取/合并请求描述：(PR description)

[

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-02-18 08:26 UTC, mysterywolf requested changes

2023-02-18 08:26 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> +        return -RT_ERROR;
```suggestion
        return result;
```

2023-02-18 08:26 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> +        return -RT_ERROR;
```suggestion
        return (rt_err_t)result;
```

2023-02-18 08:26 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> +        return -RT_ERROR;
```suggestion
        return (rt_err_t)result;
```

2023-02-21 01:33 UTC, Guozhanxin commented on components/drivers/spi/spi_core.c
> -            rt_set_errno(-RT_EIO);
如果把设置错误码的地方删掉了，要注意有没有给返回值设置正确的错误吗，比如：result = -RT_EIO;

2023-02-21 03:12 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> -            rt_set_errno(-RT_EIO);
这块应该不需要对result 做额外处理，result 已经拿到错误码了

2023-02-23 00:37 UTC, mysterywolf approved these changes

2023-02-24 06:18 UTC, Guozhanxin commented on components/drivers/spi/spi_core.c
> +        if (result < 0)
这里应该写个兼容处理，当return 0时，应该也认为出错了

2023-02-24 06:21 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> +        if (result < 0)
此处不建议处理兼容问题，这个可以留给用户自己去判断

2023-02-27 01:55 UTC, Guozhanxin approved these changes

2023-02-27 02:09 UTC, merged