[libcpu][riscv]rv32移植文件整合第一次提交
RT-Thread/rt-thread pull request #6941
Opened 2023-02-20 02:51 UTC by Yaochenger

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
整合libcpu/riscv中的移植文件 提供一份公共代码于common 

#### 你的解决方案是什么 (what is your solution)
(1) commo中包含一份公共的上下文切换代码
(2)移植时需实现cpuport.c中预留的俩个函数接口即可
  1.rt_trigger_software_interrupt
  2.rt_hw_do_after_save_above
(3）在libcpu/riscv有详细移植流程的readme
#### 在什么测试环境下测试通过 (what is the test environment)
1.CH32V307V-R1-R0
2.CH32V208W-R0-1V4
3.HPM6750EVKMINI
4.GD32VF103V-0EVAL
5.qemu(CORE-V-MCU )
与上述开发板使用的芯片一致的BSP均已测试
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-02-20 03:31 UTC, mysterywolf requested changes

2023-02-20 03:31 UTC, mysterywolf commented on libcpu/risc-v/common/trap_common.c
> + * @param mcause 中断异常ID
readme 可以用中文，但是注释最好用英文

2023-02-20 03:31 UTC, mysterywolf commented on bsp/rv32m1_vega/ri5cy/rtconfig.py
> +#     EXEC_PATH = os.getenv('RTT_EXEC_PATH')
这个修改应该revert回去，这个应该是临时自己加的

2023-02-20 03:31 UTC, mysterywolf commented on bsp/rv32m1_vega/ri5cy/rtconfig.py
> +    EXEC_PATH   = r'D:/opt/unknown-gcc/bin'
需要revert

2023-02-20 03:31 UTC, mysterywolf commented on bsp/hpmicro/hpm6750evk/rtconfig.py
> +        EXEC_PATH   = r'D:\RT-ThreadStudio\repo\Extract\ToolChain_Support_Packages\RISC-V\RISC-V-GCC-RV32\2022-04-12\bin'
revert

2023-02-20 03:31 UTC, mysterywolf commented on bsp/hifive1/rtconfig.py
> +#     EXEC_PATH = os.getenv('RTT_EXEC_PATH')
revert

2023-02-20 03:31 UTC, mysterywolf commented on bsp/gd32/risc-v/gd32vf103r-start/rtconfig.py
> +   EXEC_PATH = os.getenv('RTT_EXEC_PATH')
revert

2023-02-21 01:06 UTC, mysterywolf approved these changes
我关心的部分已经修正 looks good for me +1

@Guozhanxin  请review

@Yaochenger 功在当时 利在千秋😍

2023-02-21 01:07 UTC, mysterywolf commented
related: https://github.com/RT-Thread/rt-thread/issues/6726

务必使用squash合并

2023-02-21 02:21 UTC, Guozhanxin commented on bsp/core-v-mcu/Libraries/core_v_hal_libraries/bmsis/core-v-mcu/source/core-v-mcu.c
> +    rt_hw_interrupt_init();
格式还是有问题

2023-02-21 02:22 UTC, Guozhanxin commented on bsp/core-v-mcu/Libraries/core_v_hal_libraries/bmsis/core-v-mcu/source/crt0.S
> +    csrw mscratch,t0
这个是需要对厂家的库文件做侵入式修改吗？或者这个是必须的吗

2023-02-21 02:24 UTC, Guozhanxin commented on bsp/gd32/risc-v/gd32vf103v-eval/rtconfig.py
> +    PREFIX = 'riscv-nuclei-elf-'
这个修改不要改吧

2023-02-21 02:24 UTC, Guozhanxin commented on bsp/gd32/risc-v/libraries/GD32VF103_Firmware_Library/RISCV/env_Eclipse/start.S
> +    csrw mscratch,t0
格式问题，没对齐

2023-02-21 02:25 UTC, Guozhanxin commented on bsp/hifive1/rtconfig.py
> +    PREFIX = 'riscv32-unknown-elf-'
还有这种

2023-02-21 02:25 UTC, Guozhanxin commented on bsp/hpmicro/hpm6750evk/startup/HPM6750/toolchains/gcc/vectors.S
> +    .set default_isr_trap, SW_handler
这部分，感觉怪怪的，可能要确认一下

2023-02-23 09:10 UTC, Yaochenger commented
抱歉，点错了，不小心把Reviewers移除了

2023-03-01 03:13 UTC, Guozhanxin approved these changes

2023-03-01 03:14 UTC, Guozhanxin approved these changes

2023-03-01 03:30 UTC, mysterywolf commented
@Yaochenger 麻烦给出一份合并时的commit消息内容，我合并的时候会填写进去，本次PR修改了什么等等。

2023-03-01 06:09 UTC, Yaochenger commented
#### 为什么提交这份pr

整合libcpu/riscv中的移植文件 提供一份公共代码于common

#### 解决方案(commit合集)

> 在提交本pr时，除hpmicro的内核，rv32内核bsp已完成去除大部分的冗余，大部分代码采用common中的实现。本pr的作用是进一步统一common中的文件，从而提供一份公用代码，新移植的RV32内核的BSP可以全部使用common代码。

#### commits整合

- 在common中提供一份公用文件：interrupt_gcc.S
- 修改原有的文件，将原有的中断中上下文切换代码替换为interrupt_gcc.S
- 基于上述修改，修改仓库中risc-v内核的BSP与移植相关的部分 (主要包含中断入口函数 中断栈等)
- 在common中提供一份公用文件：trap_common.c；提供统一中断入口函数，中断入口函数初始化，中断入口注册等函数，并完善异常时的信息输出

- 在common中提供一份公用文件：rt_hw_stack_frame.h；将栈帧结构体剥离，供用户使用

- 在上述工作完成后，在上述工作的基础上测试仓库中risc-v内核的BSP

- 完善函数中的命名，完善中断栈的获取

- 提供一份详细的基于现有common文件的移植指南

  #### 在什么测试环境下测试通过 

- 1.CH32V307V-R1-R0
- 2.CH32V208W-R0-1V4
- 3.HPM6750EVKMINI
- 4.GD32VF103V-EVAL
- 5.qemu(CORE-V-MCU )

> 与上述开发板使用同样芯片的BSP均测试通过

在CH32V307V-R1-R0与HPM6750EVKMINI上基于现有移植文件进行多线程复杂场景下的长时间测试，测试过程系统运行正常。

2023-03-01 06:10 UTC, Yaochenger commented
> @Yaochenger 麻烦给出一份合并时的commit消息内容，我合并的时候会填写进去，本次PR修改了什么等等。放在评论区即可

已提交

2023-03-01 06:32 UTC, merged