[rt-smart] fix `timer_create` bug
RT-Thread/rt-thread pull request #6962
Opened 2023-02-23 03:34 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

* [fix] kernel overwrites ustack data in timer create by writing incompatible timer_id type
* [feature] support synchronous signal handling syscall `rt_sigtimedwait`

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-02-28 02:31 UTC, zhkag requested changes

2023-02-28 02:31 UTC, zhkag commented on components/lwp/lwp_syscall.c
> +        (old_value && !lwp_get_from_user(&old_value_k, (void *)timerid, sizeof old_value_k)))
这里的 old_value 应该是可以为空的，用户不关心上一次的设置的值时，会传入 0 测试用例里好多传入的都是 NULL 或 0

2023-02-28 02:33 UTC, polarvid commented on components/lwp/lwp_syscall.c
> +        (old_value && !lwp_get_from_user(&old_value_k, (void *)timerid, sizeof old_value_k)))
所以条件里面有个 `(old_value && ****)`

2023-02-28 02:39 UTC, zhkag commented on components/lwp/lwp_syscall.c
> +        (old_value && !lwp_get_from_user(&old_value_k, (void *)timerid, sizeof old_value_k)))
不清楚 lwp_get_from_user(&old_value_k, (void *)timerid, sizeof old_value_k) 是什么意思，所以刚才想的时候没把他们关联起来
为什么会把 timerid 和 old_value_k 做映射

2023-02-28 02:42 UTC, polarvid commented on components/lwp/lwp_syscall.c
> +        (old_value && !lwp_get_from_user(&old_value_k, (void *)timerid, sizeof old_value_k)))
嗯，这里写错了

2023-02-28 02:46 UTC, zhkag commented on components/lwp/lwp_syscall.c
> +        (old_value && !lwp_get_from_user(&old_value_k, (void *)timerid, sizeof old_value_k)))
pse51中定时器相关的测试用例跑一下吧，没有之前能过，现在过不了的，应该就没啥大问题

2023-02-28 02:56 UTC, polarvid commented on components/lwp/lwp_syscall.c
> +        (old_value && !lwp_get_from_user(&old_value_k, (void *)timerid, sizeof old_value_k)))
好~

2023-02-28 16:38 UTC, Guozhanxin approved these changes

2023-02-28 23:04 UTC, mysterywolf commented
CI卡住了 重启一下

2023-03-01 01:18 UTC, polarvid commented
先去做pse51的测试

2023-03-01 10:44 UTC, polarvid commented
2-17日测试通过率：86.32%
基于本分支测试通过率：88.93%

2023-03-02 07:48 UTC, merged