Signal doc
RT-Thread/rt-thread pull request #7042
Opened 2023-03-13 02:49 UTC by prcups

## 拉取/合并请求描述：(PR description)

[
add dlog for memory management
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-03-13 02:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7042) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7042) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7042) it.</sub>

2023-03-13 02:52 UTC, prcups commented
@BernardXiong @polarvid

2023-03-13 10:35 UTC, BernardXiong requested changes
最好也包括在examples下有部分入口代码，这样可以通过输入命令的方式就来复现几个典型场景。

2023-03-13 10:35 UTC, BernardXiong commented on components/lwp/lwp_syscall.c
>      int err;
这些都需要放到变量定义后面，函数局部变量定义都放在起始位置，否则一些`落后`的编译器会直接报错的。

2023-03-13 10:35 UTC, BernardXiong commented on components/lwp/lwp_user_mm.c
> +    DLOG(msg, "lwp_aspace", "varea", DLOG_MSG, "call rt_aspace_load_page, prefetch pages");
名字部分做好安排，例如统一使用`aspace`，`libcpu_mmu`，`user_mm`等。

2023-03-13 10:35 UTC, BernardXiong commented on components/mm/mm_aspace.c
> +    "varea", DLOG_MSG, "varea open");
这个`varea open`，最好更直接使用代码中的方式，例如`varea->mem_obj->on_varea_open(varea)`，包括其中的参数也可以携带，甚至说可以是参数值。

2023-03-16 06:32 UTC, polarvid commented on components/mm/mm_aspace.c
> +    "varea", DLOG_MSG, "varea open");
赞同！既然都是运行时生成的logging，带上参数值能更确切地反映出系统的状态

2023-03-19 06:58 UTC, polarvid commented on components/lwp/lwp_user_mm.c
> +            DLOG(msg, "user_mm", "aspace", DLOG_MSG, "rt_aspace_map(lwp->aspace, &addr, \
这里可以直接换成参数值 `log` 出来吗？

2023-03-19 06:58 UTC, polarvid commented on components/lwp/lwp_user_mm.c
> +        DLOG(msg, "user_mm", "user_mm", DLOG_MSG, "user_space_init");
最好也在 `arch_user_space_init` 加一些 `log`，现在这样写看不太明白

2023-03-19 06:58 UTC, polarvid commented on components/lwp/lwp_user_mm.c
> +                DLOG(msg, "lwp_aspace", "varea", DLOG_MSG, "_dup_varea");
这里再多加一些注释吧

2023-03-19 07:21 UTC, BernardXiong commented
这个需要在最新代码上修改还是什么怎么的，代码检查出错了，很多是非这次PR涉及到的文件：

https://github.com/RT-Thread/rt-thread/actions/runs/4434215791/jobs/7803919835?pr=7042

2023-03-24 02:33 UTC, prcups commented
> 这个需要在最新代码上修改还是什么怎么的，代码检查出错了，很多是非这次PR涉及到的文件：
> 
> https://github.com/RT-Thread/rt-thread/actions/runs/4434215791/jobs/7803919835?pr=7042

这个机制我也不太懂......

从files changed看，pr里貌似只包含我改动的这几个文件？

2023-03-30 01:51 UTC, closed without merging