[atomic]添加arm与risc-v下的常用原子操作函数
RT-Thread/rt-thread pull request #7053
Opened 2023-03-16 02:57 UTC by Yaochenger

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
提交一份ARM与RISC-V架构下的常用原子操作函数
- 在不开启 RT_USING_ATOMIC宏时 使用开关全局中断方式软实现提供的API
- 开启RT_USING_ATOMIC RT_USING_HW_ATOMIC - 使用hardware层实现的atomic
- 开启RT_USING_ATOMIC RT_USING_STD_ATOMIC - 使用stdatomic.h中实现的atomic
##### 实现的API如下：
-  rt_atomic_load(ptr)
-  rt_atomic_load(ptr) 
-  rt_atomic_store(ptr, v) 
-  rt_atomic_add(ptr, v) 
-  rt_atomic_sub(ptr, v)
-  rt_atomic_and(ptr, v)
-  rt_atomic_or(ptr, v) 
-  rt_atomic_xor(ptr, v) 
-  rt_atomic_exchange(ptr, v)
-  rt_atomic_flag_clear(ptr) 
-  rt_atomic_flag_test_and_set(ptr) 
-  rt_atomic_compare_exchange_strong(ptr, v,des)
##### 此PR基于
https://github.com/RT-Thread/rt-thread/pull/6931
https://github.com/RT-Thread/rt-thread/pull/6197
https://github.com/RT-Thread/rt-thread/issues/7012

#### 你的解决方案是什么 (what is your solution)
- ARM使用保留加载与条件存储实现
- RISC-V使用原子内存操作实现
- 软原子操作使用开关全局中断实现
#### 在什么测试环境下测试通过 (what is the test environment)
- [ ] STM32L475
- [ ] HPM6750
- [ ] CH32V307
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-03-16 03:54 UTC, mysterywolf commented on libcpu/risc-v/common/atomic_port.c
> +    return(result);
```suggestion
    return result;
```

2023-03-16 06:09 UTC, BernardXiong commented on include/rtatomic.h
> +__attribute__((always_inline)) static inline  rt_atomic_t rt_isr_atomic_exchange(rt_atomic_t *ptr, rt_atomic_t val)
为什么这个名称是叫`rt_isr_` ?

2023-03-16 06:10 UTC, BernardXiong requested changes
多测试

2023-03-16 06:10 UTC, BernardXiong commented on include/rtatomic.h
> + #include <rthw.h>
顶格有空格。

2023-03-16 06:10 UTC, BernardXiong commented on include/rtatomic.h
> +    rt_hw_interrupt_enable(level);
这里明显问题，`rt_hw_interrupt_enable`在return后面

2023-03-16 06:50 UTC, Yaochenger commented on include/rtatomic.h
> +__attribute__((always_inline)) static inline  rt_atomic_t rt_isr_atomic_exchange(rt_atomic_t *ptr, rt_atomic_t val)
这是使用开关中断的方式实现的原子操作所以暂时起了这么名字，这是一个草稿版本先提上来看一下整体的结构是否可行

2023-03-16 09:28 UTC, Yaochenger commented on include/rtatomic.h
> + #include <rthw.h>
已修正

2023-03-16 09:28 UTC, Yaochenger commented on include/rtatomic.h
> +    rt_hw_interrupt_enable(level);
已修正

2023-03-16 09:53 UTC, BernardXiong commented on include/rtatomic.h
> +    rt_atomic_t temp = *ptr;
建议函数局部变量定义放前面，或者紧随`{`大括号后面。

2023-03-16 09:56 UTC, BernardXiong commented on src/Kconfig
> +        config RT_USING_STD_ATOMIC
这两者是并列关系，也就是两者都可以打开。

2023-03-17 00:13 UTC, Guozhanxin commented on src/Kconfig
> +        config RT_USING_STD_ATOMIC
是的需要改成choice

2023-03-17 07:11 UTC, BernardXiong commented on include/rtatomic.h
> +__attribute__((always_inline)) static inline  rt_atomic_t rt_isr_atomic_exchange(rt_atomic_t *ptr, rt_atomic_t val)
从语义上来说，使用这样方式名字不太合理：
ISR指的是中断服务程序（Interrupt Service Routine），在计算机系统中，当发生硬件中断或异常时，处理器会暂停当前正在执行的程序，转而执行预先定义好的中断服务程序来处理该中断或异常。中断服务程序通常是由操作系统或设备驱动程序编写的，并且需要快速地响应中断并执行必要的操作，以确保系统的稳定性和可靠性。

2023-03-17 08:03 UTC, BernardXiong commented on include/rtatomic.h
> +    if(*ptr==0){
代码格式化。

另外，`__attribute__((always_inline))` 在不同的工具链上都可以通过吗？

2023-03-17 08:04 UTC, BernardXiong commented on include/rtatomic.h
> +extern rt_base_t rt_hw_interrupt_disable(void);
`rt_hw_interrupt_enable/disable` 应该是在rthw.h中定义。在头文件或.c文件中，不应该使用`extern`方式重新声明函数。

2023-03-17 08:05 UTC, BernardXiong requested changes
移除额外的`extern`函数声明

2023-03-17 08:36 UTC, Guozhanxin commented on include/rtatomic.h
> +    if(*ptr==0){
改成RTT的API吧

2023-03-17 11:57 UTC, Yaochenger commented on include/rtatomic.h
> +__attribute__((always_inline)) static inline  rt_atomic_t rt_isr_atomic_exchange(rt_atomic_t *ptr, rt_atomic_t val)
这里使用开关中断的方式实现类似的原子操作 这里是否可以用soft替换,例如：
rt_isr_atomic_exchange -> rt_soft_atomic_exchange

2023-03-17 12:27 UTC, Yaochenger commented on include/rtatomic.h
> +extern rt_base_t rt_hw_interrupt_disable(void);
![image](https://user-images.githubusercontent.com/75192526/225904009-8b6ee5d2-ff38-4a51-b684-fa95459ddb68.png)
这里当时也很奇怪，开始是未加声明的，虽已包含头文件，但不声明会出现上述问题，

2023-03-19 02:58 UTC, mysterywolf commented on include/rtatomic.h
> +    if(*ptr==0){
这个需要改成rt_always_inline

2023-03-19 03:00 UTC, mysterywolf commented on src/Kconfig
> +    endif
不建议用choice语法块，否则其他kconfig选项在select的时候，choice里边的config是没有办法被select的，未来依赖会成问题的。

2023-03-19 03:02 UTC, mysterywolf commented on src/Kconfig
> +    endif
没有理解，HW和STD为什么是互斥关系，STD应该是HW的一层封装才对，这两个是可以共存的。

2023-03-19 03:05 UTC, mysterywolf commented on src/Kconfig
> +    endif
另外，RT_USING_HW_ATOMIC 应该不需要用户自行选定，如果当前架构提供硬件原子操作，直接就支持上去，如果没有提供原子操作，默认走软件模拟关中断的方式，这个应该是由Kconfig自动判定的，用户无需介入，用户唯一在使能RT_USING_ATOMIC后需要关心的就是是否使用C标准库版本的原子操作，即是否使能RT_USING_STDC_ATOMIC（建议用RT_USING_STDC_ATOMIC，而不是RT_USING_STD_ATOMIC）

应该是这样，甚至都不需要menu语法块，

```
  config RT_USING_ATOMIC
      bool "Enable Atomic"
      default n
      help
          e.g. If defined RT_USING_HW_ATOMIC,atomic implemented using hardware layer,
          if defined RT_USING_STD_ATOMIC,Using atomic implemented in stdatomic.h,
          else realize by using switch global interrupt.

  if RT_USING_ATOMIC
          config RT_USING_STDC_ATOMIC
              bool "Using atomic implemented in stdatomic.h"
              default n
  endif
```

2023-03-19 07:15 UTC, BernardXiong commented on src/Kconfig
> +    endif
`RT_USING_ATOMIC` 这个是不存在的，因为后续会默认都携带这部分的支持。

2023-03-19 07:18 UTC, BernardXiong commented on src/Kconfig
> +    endif
> 没有理解，HW和STD为什么是互斥关系，STD应该是HW的一层封装才对，这两个是可以共存的。

`RT_USING_STD_ATOMIC =>` 使用libc中的C11 atomic实现；

当使用C11 libc，并且没有定义`__STDC_NO_ATOMICS__`时，就代表有atomic的支持。

2023-03-19 10:48 UTC, mysterywolf commented on src/Kconfig
> +    endif
噢噢 我明白啥意思了

2023-03-19 10:49 UTC, mysterywolf commented on include/rtatomic.h
> +__attribute__((always_inline)) static inline  rt_atomic_t rt_isr_atomic_exchange(rt_atomic_t *ptr, rt_atomic_t val)
赞同soft这个命令

2023-03-19 10:51 UTC, mysterywolf commented on libcpu/arm/common/atomic_port.c
> +    }while((__STREXW(val, ptr)) != 0U);
```suggestion
    } while((__STREXW(val, ptr)) != 0U);
```
多处这个问题

2023-03-19 10:52 UTC, mysterywolf commented on libcpu/arm/common/SConscript
> +if rtconfig.CPU in ['cortex-m0','cortex-m0-dual','arm926', 'lpc214x', 'lpc24xx', 's3c24x0', 'AT91SAM7X']:
直接判断ARCH_ARM_CORTEX_M0就可以了呀

2023-03-19 10:53 UTC, mysterywolf commented on libcpu/risc-v/common/SConscript
> +if rtconfig.CPU in ['cv32e40p', 'rv32m1','juicevm']:
判断宏 ARCH_RISCV32 ARCH_RISCV64 ARCH_RISCV或者其他类似的，
不要这么判断

2023-03-21 02:18 UTC, mysterywolf commented on libcpu/arm/common/atomic_port.c
> +    return(result);
```suggestion
    return result;
```

2023-03-21 02:20 UTC, mysterywolf commented on include/rtatomic.h
> +#endif
```suggestion
#else
#error "the standard library C doesn't support the atomic operation"
#endif
```

2023-03-21 14:39 UTC, BernardXiong commented on include/rtatomic.h
> +    if (*ptr == 0) {
代码风格不对的，用`tools/as.sh`格式化下代码吧

2023-03-22 06:04 UTC, Guozhanxin commented
c11的原子操作还包括内存同步顺序相关的。这些需要考虑支持吗？
![image](https://user-images.githubusercontent.com/25633294/226815170-950622cf-752a-48de-a5de-7537e881e97d.png)

以下是一个使用内存同步顺序的示例代码：
```
#include <stdatomic.h>
#include <stdio.h>
#include <threads.h>

atomic_int x = 0; // shared global variable
atomic_int y = 0; // shared global variable

int thread_1(void* arg)
{
    x.store(42, memory_order_relaxed); // write x
    y.store(24, memory_order_release); // write y
    return 0;
}

int thread_2(void* arg)
{
    int a = y.load(memory_order_acquire); // read y
    int b = x.load(memory_order_relaxed); // read x
    printf("a=%d, b=%d\n", a, b);
    return 0;
}

int main()
{
    thrd_t t1, t2;
    thrd_create(&t1, thread_1, NULL);
    thrd_create(&t2, thread_2, NULL);
    thrd_join(t1);
    thrd_join(t2);
}
```
这个代码中，线程1先写x再写y，线程2先读y再读x。由于y的写操作和读操作都使用了memory_order_release和memory_order_acquire，它们之间建立了同步关系。这意味着线程1的写操作不会被重排序到y之后，线程2的读操作不会被重排序到y之前。因此，线程2打印的结果一定是a=24，b=42或者a=0，b=任意值。如果没有使用内存同步顺序，那么可能出现a=24，b=0的情况。

2023-03-22 13:42 UTC, Guozhanxin approved these changes

2023-03-23 02:12 UTC, polarvid commented on libcpu/risc-v/virt64/SConscript
> +src     = src + ['../common/atomic_riscv.c']
这个放在上一级目录里会不会好点。现在这样不容易注意到这个依赖。逻辑上也很怪，当前目录的脚本就处理当前目录下好了，扯到其它文件夹就乱了。

2023-03-23 02:36 UTC, mysterywolf commented on libcpu/risc-v/virt64/SConscript
> +src     = src + ['../common/atomic_riscv.c']
是的 这里确实有些奇怪 我看一下

2023-03-23 02:45 UTC, Yaochenger commented on libcpu/risc-v/virt64/SConscript
> +src     = src + ['../common/atomic_riscv.c']
现在atomic_riscv.c支持RV32 RV64 ,在common文件中提供RV32通用移植文件，上述添加文件的方式是个暂时的方式，在RV64建立通用移植文件后会移除

2023-03-23 03:12 UTC, mysterywolf commented on libcpu/risc-v/virt64/SConscript
> +src     = src + ['../common/atomic_riscv.c']
OK 那没问题了

2023-03-23 03:16 UTC, mysterywolf approved these changes

2023-03-23 06:51 UTC, Yaochenger commented
Next PR TODO:
- 1 细化riscv的Kconfig  使后续再支持一些特性时更方便
- 2 支持内存屏障
- 3 当前目录引用上级目录的问题 例：src  = src + ['../common/atomic_riscv.c']

2023-03-23 12:05 UTC, BernardXiong approved these changes

2023-03-23 12:06 UTC, merged