add drv_adc
RT-Thread/rt-thread pull request #7061
Opened 2023-03-17 11:46 UTC by Letian-stu

## 拉取/合并请求描述：(PR description)

[

你好这是我第一次提交PR，我也不知道这样能不能成功通过，就是先试试，如果有操作不当，请见谅！
#### 为什么提交这份PR (why to submit this PR)
使用mm32f327x的bsp时想通过rtt的adc driver使用adc。
#### 你的解决方案是什么 (what is your solution)
所以从mm32官方的adc代码移植过来。
#### 在什么测试环境下测试通过 (what is the test environment)
在keil下已经测试过adc1 和adc2 可以正常使用。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-03-17 11:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7061) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7061) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7061) it.</sub>

2023-03-18 01:57 UTC, mysterywolf requested changes

2023-03-18 01:57 UTC, mysterywolf commented on bsp/mm32f327x/drivers/Kconfig
> +                default y
默认为n 下面空一格

2023-03-18 05:15 UTC, Letian-stu commented on bsp/mm32f327x/drivers/Kconfig
> +                default y
你好，我已经修改过了，不知道这样子格式是否正确，以及代码有没有其他问题，第一次发布pr，怕出错

2023-03-18 18:08 UTC, mysterywolf requested changes
其他没有什么问题了

2023-03-18 18:08 UTC, mysterywolf commented on bsp/mm32f327x/drivers/Kconfig
> +        menu "ADC Drivers"
这个位置建议用menuconfig语法块，这样在sconscript里就不用BSP_USING_ADC1 BSP_USING_ADC2一个一个的去判断，直接判断BSP_USING_ADC即可，然后再.c里用预编译来具体区分是ADC1还是ADC2

https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f103-blue-pill/board/Kconfig#L182

2023-03-18 18:08 UTC, mysterywolf commented on bsp/mm32f327x/drivers/SConscript
> +if  GetDepend(['BSP_USING_ADC1']) or GetDepend('BSP_USING_ADC2'):
```suggestion
if  GetDepend(['BSP_USING_ADC']:
```

2023-03-18 18:08 UTC, mysterywolf commented on bsp/mm32f327x/drivers/drv_adc.c
> +    .convert = mm32_get_adc_value,
https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_adc.c#L360

adc还有获取参考电压和分辨率的函数，如果可以实现也可以实现一下

2023-03-19 03:17 UTC, mysterywolf commented on bsp/mm32f327x/drivers/Kconfig
> +                default y
没有事情  大胆改

2023-03-19 10:36 UTC, mysterywolf commented on bsp/mm32f327x/drivers/drv_adc.c
> +// #define BSP_USING_ADC2
改的还有有点问题，可能是我没有描述清楚：

Kconfig里应该这么写，去掉这两个#define 
```c
#define BSP_USING_ADC1
// #define BSP_USING_ADC2
```

```
     menuconfig BSP_USING_ADC
        bool "Enable ADC"
        default n
        select RT_USING_ADC
        if BSP_USING_ADC
            config BSP_USING_ADC1
                bool "Enable ADC1"
                default n

            config BSP_USING_ADC1
                bool "Enable ADC1"
                default n
        endif
```

2023-03-19 11:16 UTC, mysterywolf approved these changes

2023-03-19 13:06 UTC, merged

2023-03-19 13:06 UTC, mysterywolf commented
感谢贡献PR！