[bsp/lpc55sxx] add drv_i2s, [bsp/k210] add drv_i2c
RT-Thread/rt-thread pull request #7126
Opened 2023-03-29 15:27 UTC by Vandoul

lpc55sxx 增加i2s驱动及wm8904驱动，还未测试，近期会测试完善；
k210增加i2c驱动，为了测试i2c-tools增加的，并修改了drv_io_config.c的字符串，因为使用io命令时输出是乱码

2023-03-30 00:07 UTC, mysterywolf requested changes

2023-03-30 00:07 UTC, mysterywolf commented on bsp/k210/drivers/drv_i2c.c
> +static rt_size_t _i2c_mst_xfer(struct rt_i2c_bus_device *bus,
5.0.0更改了iic的transfer函数返回值为rt_ssize_t，而不再是rt_size_t.  rt_ssize_t是有符号类型，返回值>=是实际传输长度，<0 返回-RT_Exxx错误码，表示出现了错误（例如硬件错误，或者参数不正确等等）

2023-03-30 02:27 UTC, Vandoul commented on bsp/k210/drivers/drv_i2c.c
> +static rt_size_t _i2c_mst_xfer(struct rt_i2c_bus_device *bus,
已经修改了rt_size_t为rt_ssize_t。

2023-03-30 03:50 UTC, mysterywolf commented
请格式化一下你提交的代码 https://github.com/mysterywolf/formatting

2023-03-30 12:51 UTC, Vandoul commented
已经使用工具格式化了

2023-03-31 00:34 UTC, mysterywolf commented on bsp/k210/drivers/drv_i2c.c
> +        if (status != 0)
这个地方是不是出错了，如果出错可以考虑返回RT错误码例如 return -RT_ERROR;

2023-03-31 01:32 UTC, mysterywolf approved these changes

2023-03-31 03:38 UTC, merged