[bsp] fix Force TypeCast to pointer dereference
RT-Thread/rt-thread pull request #7139
Opened 2023-03-31 08:34 UTC by dingiso

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

在通过 arg 作为参数传输数据时，直接把地址赋值给了一个 uint32_t 的变量，不合理，

#### 你的解决方案是什么 (what is your solution)

应该改为转换为对应类型的指针，在进行解引用，获得其中包含的数据

#### 在什么测试环境下测试通过 (what is the test environment)

* CAN es32f0654

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-03-31 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7139) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7139) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7139) it.</sub>

2023-03-31 10:03 UTC, Guozhanxin commented on bsp/at32/libraries/rt_drivers/drv_can.c
> +        argval = *(rt_uint32_t *) arg;
但是，框架好像就这么设计的。。。这里改了，框架那边会不会出现异常

2023-03-31 12:12 UTC, dingiso commented on bsp/at32/libraries/rt_drivers/drv_can.c
> +        argval = *(rt_uint32_t *) arg;
好的，我看一下框架的问题

2023-04-02 08:15 UTC, dingiso commented
我看rt-thread的club 好像也提到了这个问题 https://club.rt-thread.org/ask/question/f8ebd10c34db506a.html 还有哪里需要更改的么

2023-04-04 04:49 UTC, mysterywolf commented on bsp/synwit/swm341/drivers/drv_can.c
这个文件的修改请说明一下原因~ 貌似是在格式化文件格式？

2023-04-04 09:22 UTC, dingiso commented on bsp/synwit/swm341/drivers/drv_can.c
抱歉 ide 保存自动格式化了 我重新提交了一下

2023-04-05 05:20 UTC, mysterywolf approved these changes

2023-04-06 04:11 UTC, Guozhanxin commented on bsp/at32/libraries/rt_drivers/drv_can.c
> +        argval = *(rt_uint32_t *) arg;
https://github.com/RT-Thread/rt-thread/blob/00a6d1a1c5ac87f5ccbbb6986e6c1be9d67ee214/components/drivers/can/can.c#L416 

框架指的是这个文件里的内容。看起来，这里不能改的

2023-04-06 22:24 UTC, mysterywolf commented on bsp/at32/libraries/rt_drivers/drv_can.c
> +        argval = *(rt_uint32_t *) arg;
翻了一下，郭老师说的没错 这里不需要改，设备框架里，是直接传RT_DEVICE_FLAG_INT_RX进来的。

2023-04-06 23:54 UTC, mysterywolf commented on bsp/at32/libraries/rt_drivers/drv_can.c
> +        argval = *(rt_uint32_t *) arg;
@Guozhanxin 是否考虑采用取地址传址？直接指针空间传下来有些粗鲁

2023-04-07 04:14 UTC, supperthomas requested changes
这个接口不能这样轻易改动，得提一些议案和分析过程。还得看看哪些相关的example会有影响，用户影响程度和使用场景。综合考虑。-1

2023-04-07 20:22 UTC, closed without merging