[bsp][rtduino] support for STM32G474 Nucleo in RTduino
RT-Thread/rt-thread pull request #7151
Opened 2023-04-01 10:25 UTC by kurisaW

## 拉取/合并请求描述：(PR description)

[
新增RTduino对STM32G474 Nucleo开发板的支持
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-01 12:29 UTC, kurisaW commented
已通过基础测试
![image](https://user-images.githubusercontent.com/98592772/229288716-a82393f6-ba63-464f-a803-4ed4149fed0c.png)

2023-04-02 02:55 UTC, mysterywolf requested changes

2023-04-02 02:55 UTC, mysterywolf commented on bsp/stm32/stm32g474-st-nucleo/board/Kconfig
> +                    default 112
这个引脚有问题 两个编号一样

2023-04-02 02:55 UTC, mysterywolf commented on bsp/stm32/stm32g474-st-nucleo/applications/arduino_pinout/pins_arduino.h
> +#define F_CPU          170000000L  /* CPU:170MHz */
好古怪的频率

2023-04-02 02:55 UTC, mysterywolf commented on bsp/stm32/stm32g474-st-nucleo/applications/arduino_pinout/pins_arduino.h
> +/* i2c2 : P(,9-SDA P(,8-SCL */
注释有问题

2023-04-02 02:55 UTC, mysterywolf commented on bsp/stm32/stm32g474-st-nucleo/board/Kconfig
> +    config BSP_USING_ARDUINO
参考一下其他stm32 bsp，上面补一个BSP_USING_STLINK_TO_USART 的config，这个不是你的问题，是最开始提交这个BSP的时候就没有写。

2023-04-02 06:23 UTC, kurisaW reviewed
已完成修改要求

2023-04-02 06:29 UTC, mysterywolf commented on bsp/stm32/stm32g474-st-nucleo/board/Kconfig
>              endif
这个地方还是有问题，你声明的是I2C2，但是有些地方写的是i2c1

2023-04-02 06:51 UTC, kurisaW reviewed
modify

2023-04-02 08:08 UTC, kurisaW reviewed
modify

2023-04-02 11:30 UTC, kurisaW reviewed
modify

2023-04-08 01:56 UTC, mysterywolf approved these changes

2023-04-08 01:57 UTC, merged