[HUST CSE IoTS&P Lab] [fix] check rt_mutex_create return value
RT-Thread/rt-thread pull request #7169
Opened 2023-04-03 11:52 UTC by Sparks-Pion

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
发现 rt_mutex_create 函数调用后可能出现指针为空的情况

#### 你的解决方案是什么 (what is your solution)
对返回值进行判断是否为 RT_NULL

#### 在什么测试环境下测试通过 (what is the test environment)
all
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-03 15:08 UTC, BernardXiong commented on bsp/nuvoton/libraries/nu_packages/Demo/smp_demo.c
> +     git logif(sem != RT_NULL)
这里弄错了吧

2023-04-03 16:08 UTC, Sparks-Pion commented on bsp/nuvoton/libraries/nu_packages/Demo/smp_demo.c
> +     git logif(sem != RT_NULL)
对不起，已修改

2023-04-04 00:16 UTC, mysterywolf requested changes

2023-04-04 00:16 UTC, mysterywolf commented on bsp/nuvoton/libraries/m031/rtt_port/drv_fmc.c
> +    RT_ASSERT(g_mutex_fmc != RT_NULL);
assert是一种比较凶残的方式，直接让系统crash掉。有些不致命的问题可以直接返回错误和错误信息。

```suggestion
    if(g_mutex_fmc == RT_NULL)
    {
        LOG_E("mutex created failure");
        return (int)-RT_ERROR;
    }
```

在使用LOG_xxx时，该文件最上面也要定义LOG标签，参见：https://github.com/RT-Thread/rt-thread/blob/master/components/libc/compilers/common/ctime.c#L39-L41

2023-04-04 00:16 UTC, mysterywolf commented on bsp/nuvoton/libraries/nu_packages/Demo/smp_demo.c
> +    if(sem != RT_NULL)
这样一层层嵌套不优雅，如果条件不满足 直接退出就可以了

```suggestion
    if(sem == RT_NULL)
    {
        LOG_E();
        return (int)-RT_ERROR;
    }
```

2023-04-04 04:32 UTC, mysterywolf approved these changes

2023-04-04 04:33 UTC, merged

2023-04-04 04:33 UTC, mysterywolf commented
感谢贡献PR！