Merge pull request #1 from RT-Thread/master
RT-Thread/rt-thread pull request #7182
Opened 2023-04-06 07:30 UTC by songw4232

update2023/4/4

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-06 10:08 UTC, songw4232 commented
[add]bsp/stm32/stm32u575-st-nucleo中添加相关外设驱动

2023-04-06 10:35 UTC, songw4232 commented
[add]bsp/stm32/stm32u575-st-nucleo中添加相关外设驱动

2023-04-06 15:44 UTC, supperthomas requested changes
Please clean the useless file. like CubeMX_Config fold etc.

2023-04-06 15:48 UTC, supperthomas requested changes

2023-04-06 15:48 UTC, supperthomas commented on bsp/stm32/libraries/HAL_Drivers/drv_spi.c
> +					#if 0
请注意格式。

2023-04-06 15:48 UTC, supperthomas commented on bsp/stm32/stm32u575-st-nucleo/startup_stm32u575xx.lst
> +
自动生成的文件，不需要放到仓库里，可以参考其他stm32文件夹，提交相关代码

2023-04-07 07:15 UTC, mysterywolf commented
此PR需要 +2后才能合并，有一些不符合规范的地方需要仔细review @supperthomas @Guozhanxin

2023-04-07 10:30 UTC, songw4232 commented
[add]添加stm32u575相关外设

2023-04-07 10:37 UTC, songw4232 commented
[delete]删除一些不必要文件

2023-04-07 10:48 UTC, Guozhanxin commented on bsp/stm32/stm32u575-st-nucleo/board/ports/drv_spi_flash.c
> +    /* ������ spi1 �Ϲ���һ�� spi10 ���豸 */
注释不能有中文

2023-04-07 11:00 UTC, songw4232 commented
[fix]修改错误代码及相关中文注释

2023-04-07 11:29 UTC, songw4232 commented
[fix]修改STM32U5系列BUG

2023-04-07 11:39 UTC, songw4232 commented
[fix]修改stm32u5系列BUG

2023-04-07 11:40 UTC, Guozhanxin approved these changes

2023-04-07 11:48 UTC, supperthomas requested changes

2023-04-07 11:48 UTC, supperthomas commented on bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/README.md
> +# xxx 开发板的Arduino生态兼容说明
xxx?

2023-04-07 11:48 UTC, supperthomas commented on bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/README.md
> +> 2. xxxxxxxxx
xxx?

2023-04-07 11:48 UTC, supperthomas commented on bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/pins_arduino.c
> + * 2023-04-04     default      first version
default？

2023-04-10 05:58 UTC, songw4232 commented
[add]补充arduino_pinout/README文档

2023-04-10 06:36 UTC, supperthomas approved these changes

2023-04-10 22:43 UTC, mysterywolf requested changes

2023-04-10 22:43 UTC, mysterywolf commented on bsp/stm32/libraries/STM32U5xx_HAL/SConscript
> +    src += ['STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_ospi.c']
这里貌似有问题

2023-04-10 22:43 UTC, mysterywolf commented on bsp/stm32/stm32u575-st-nucleo/board/Kconfig
> +        bool "Enable SPI FLASH"
注意缩进，是4空格，而不是tab，可以用formatting扫描一下不会可以问问王顺

2023-04-10 22:43 UTC, mysterywolf commented on bsp/stm32/stm32u575-st-nucleo/rtconfig.h
> +#define RT_USING_SPI
这些功能默认不开启，默认只开启串口和PIN

2023-04-10 22:43 UTC, mysterywolf commented on bsp/stm32/stm32u575-st-nucleo/rtconfig.h
> +#define RT_USING_CPLUSPLUS
默认不开启

2023-04-11 23:02 UTC, mysterywolf commented
请处理冲突

2023-04-12 12:50 UTC, closed without merging