[bsp][lpc55s69]add softi2c
RT-Thread/rt-thread pull request #7221
Opened 2023-04-12 01:51 UTC by linshire

## 拉取/合并请求描述：(PR description)

[
添加了软件i2c 驱动，并在ubuntu上编译并测试通过，移植来自于stm32
修改了bsp/Kconfig中错误的路径，该bug会导致scons --menuconfig打不开，在ubuntu下测试通过
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-12 01:58 UTC, mysterywolf requested changes

2023-04-12 01:58 UTC, mysterywolf commented on bsp/lpc55sxx/lpc55s69_nxp_evk/Kconfig
> +source "./Libraries/Kconfig"
这个地方为什么改了？

2023-04-12 11:29 UTC, linshire commented on bsp/lpc55sxx/lpc55s69_nxp_evk/Kconfig
> +source "./Libraries/Kconfig"
这个问题已经解决了，Kconfig已经更改回来了

2023-04-13 23:20 UTC, mysterywolf requested changes

2023-04-13 23:20 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_soft_i2c.c
> +// #include "drv_config.h"
这个头文件是否需要删除？

2023-04-14 01:41 UTC, mysterywolf approved these changes

2023-04-14 01:41 UTC, merged