[change]修正stm32f401-st-nucleo英文上手指南
RT-Thread/rt-thread pull request #7227
Opened 2023-04-12 09:43 UTC by Yaochenger

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
- [ ]修正stm32f401-st-nucleo英文上手指南

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-12 12:00 UTC, supperthomas requested changes

2023-04-12 23:38 UTC, mysterywolf commented on bsp/stm32/stm32f401-st-nucleo/How to create a new project.md
> +### 1.1 Go to File -> Import.
先放在stm32下面的docs就可以

2023-04-12 23:39 UTC, mysterywolf commented
注意图片可以标注一些有意义的英文名字，不要用乱码

2023-04-13 02:19 UTC, mysterywolf commented on bsp/stm32/docs/STM32系列如何创建新项目.md
> +### 1.1 Go to File -> Import.
这个位置没有翻译

2023-04-13 02:21 UTC, mysterywolf commented
所有图片应当放到figures_en文件夹下，但是可以供中文文档使用，无需截图对应的中文版本。

2023-04-13 02:45 UTC, Yaochenger commented on bsp/stm32/docs/STM32系列如何创建新项目.md
> +### 1.1 Go to File -> Import.
已修正，这里当时是感觉那句英文相比中文更直观一些，就未翻译

2023-04-13 06:39 UTC, supperthomas commented
bsp/stm32/stm32f401-st-nucleo/How to create a new project.md 
这个可以放到bsp/stm32/docs下面。

2023-04-13 08:17 UTC, Yaochenger commented
> 
嗯呢，这个文档是有个竞赛需要为这个板子提供支持 我咨询一下满老师的意见

2023-04-13 08:23 UTC, supperthomas approved these changes

2023-04-13 16:29 UTC, merged