[HUST CSE] [document] Fix some invalid grouping commands and warnings in Doxygen.
RT-Thread/rt-thread pull request #7229
Opened 2023-04-12 10:25 UTC by BIIIANG

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
#6857 ，很多文件中存在的Doxygen分组指令由于[Doxygen的更新](https://github.com/doxygen/doxygen/commit/ef5af7618fbec3ac240e7a1099607d9ff2b3cc4f)已经失效，且Doxygen配置没有跟随代码修改而修改，导致生成中存在警告、生成的文档有非常多空白页面。

#### 你的解决方案是什么 (what is your solution)
1. 将Doxygen输入文件（由Doxyfile中的INPUT定义）中的失效Doxygen分组指令（如`/*@*/`和`/*@}*/`）更改为有效的分组指令（如`/**@*/`和`/**@}*/`）；（此处只对INPUT中的文件做了修改，bsp目录下和libcpu目录下存在近万个失效的Doxygen分组指令，但由于不作为文档的输入文件且这些文件过于庞大老旧，没有对这些文件中的无效指令做修改）
2. 将图片文件统一放入了images目录下；
3. 修改了Doxyfile和部分Doxygen注释，使得Doxyfile能够定位到新的代码路径且不受重复实现的影响。

#### 在什么测试环境下测试通过 (what is the test environment)
在Doxygen GUI 1.9.6（Windows）下测试，修复了除dot.exe不存在的其他所有警告，能够生成结构正确、内容充实的文档。

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-12 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7229) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7229) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7229) it.</sub>

2023-04-14 04:37 UTC, supperthomas commented
下次可以尝试慢慢修复，将任务切成一小份一小份的提交。每次PR 修复 一个功能。

2023-04-14 04:38 UTC, supperthomas commented
有生成好的html吗？压缩成zip上传看看。或者截图看下生成后的效果。

2023-04-14 04:42 UTC, supperthomas requested changes

2023-04-14 04:42 UTC, supperthomas commented on documentation/doxygen/systeminit.h
> + * rt_system_heap_init();
这里为什么要改？

2023-04-14 04:42 UTC, supperthomas commented on src/components.c
> + * @return 0, but never return.
这边可以写，如果返回0 ，说明调度失败。

2023-04-14 04:43 UTC, supperthomas commented
[documentation/doxygen/images/.gitkeep](https://github.com/RT-Thread/rt-thread/pull/7229/files#diff-407e7302260f32c530c9a4545fb67b27632af8f46df536b30e1936390578db2d)   这个文件，删了？

2023-04-14 04:49 UTC, supperthomas commented
还是非常感谢帮忙pr修复的

2023-04-14 09:13 UTC, BIIIANG commented
> 有生成好的html吗？压缩成zip上传看看。或者截图看下生成后的效果。

OK 我等下上传以下前后对比

2023-04-14 09:35 UTC, BIIIANG commented on documentation/doxygen/systeminit.h
> + * rt_system_heap_init();
这里是我少考虑了，我以为他的目的是和上下几个其他函数一样为了能够生成一个链接，但是我现在看发现上下几个都是无参函数只有他有参数，所以这里的确不应该改。

2023-04-14 09:38 UTC, BIIIANG commented
[html-before.zip](https://github.com/RT-Thread/rt-thread/files/11231318/html-before.zip)
[html-after.zip](https://github.com/RT-Thread/rt-thread/files/11231319/html-after.zip)
解压缩之后打开html/index.html进入文档。

下面是几处比较大的更改：
![diff-1](https://user-images.githubusercontent.com/65029905/232007908-dd921d2b-8c83-4e7e-98ed-4c9c2ebf51a5.png)
![diff-2](https://user-images.githubusercontent.com/65029905/232007926-52728f14-f1c1-4704-ae14-419f0ad22aea.png)
![diff-3](https://user-images.githubusercontent.com/65029905/232007931-50545d8c-651f-4d7d-8c62-a43786454bdc.png)
![diff-4](https://user-images.githubusercontent.com/65029905/232007957-bcea0197-3295-42a3-888d-4aad637720f9.png)

2023-04-14 09:40 UTC, BIIIANG commented
> [documentation/doxygen/images/.gitkeep](https://github.com/RT-Thread/rt-thread/pull/7229/files#diff-407e7302260f32c530c9a4545fb67b27632af8f46df536b30e1936390578db2d) 这个文件，删了？

因为把图片移到了这个目录里，目录里不为空了，所以我就把.gitkeep删掉了，这会有什么副作用吗？

2023-04-14 09:49 UTC, BIIIANG commented on src/components.c
> + * @return 0, but never return.
OK

2023-04-14 09:49 UTC, BIIIANG commented on src/components.c
> + * @return 0, but never return.
> 这边可以写，如果返回0 ，说明调度失败。

OK

2023-04-14 09:49 UTC, BIIIANG commented on documentation/doxygen/systeminit.h
> + * rt_system_heap_init();
> 这里为什么要改？

这里是我少考虑了，我以为他的目的是和上下几个其他函数一样为了能够生成一个链接，但是我现在看发现上下几个都是无参函数只有他有参数，所以这里的确不应该改。

2023-04-14 10:07 UTC, supperthomas commented
> > [documentation/doxygen/images/.gitkeep](https://github.com/RT-Thread/rt-thread/pull/7229/files#diff-407e7302260f32c530c9a4545fb67b27632af8f46df536b30e1936390578db2d) 这个文件，删了？
> 
> 因为把图片移到了这个目录里，目录里不为空了，所以我就把.gitkeep删掉了，这会有什么副作用吗？

没事，可以的。

2023-04-14 10:14 UTC, BIIIANG commented
> > > [documentation/doxygen/images/.gitkeep](https://github.com/RT-Thread/rt-thread/pull/7229/files#diff-407e7302260f32c530c9a4545fb67b27632af8f46df536b30e1936390578db2d) 这个文件，删了？
> > 
> > 
> > 因为把图片移到了这个目录里，目录里不为空了，所以我就把.gitkeep删掉了，这会有什么副作用吗？
> 
> 没事，可以的。其他的修改提交下，即可。

OK，已经按照Changes requested里的建议做了修改。

2023-04-14 10:41 UTC, supperthomas approved these changes

2023-04-14 10:42 UTC, supperthomas commented
> > > > [documentation/doxygen/images/.gitkeep](https://github.com/RT-Thread/rt-thread/pull/7229/files#diff-407e7302260f32c530c9a4545fb67b27632af8f46df536b30e1936390578db2d) 这个文件，删了？
> > > 
> > > 
> > > 因为把图片移到了这个目录里，目录里不为空了，所以我就把.gitkeep删掉了，这会有什么副作用吗？
> > 
> > 没事，可以的。其他的修改提交下，即可。
> 
> OK，已经按照Changes requested里的建议做了修改。

做的很棒👍🏻

2023-04-14 16:31 UTC, mysterywolf approved these changes

2023-04-14 16:33 UTC, merged

2023-04-14 16:50 UTC, mysterywolf commented
感谢提交pr