[add]添加bsp/stm32/stm32u575-st-nucleo外设
RT-Thread/rt-thread pull request #7237
Opened 2023-04-13 06:45 UTC by songw4232

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-13 08:32 UTC, songw4232 commented
[add]添加bsp/stm32/stm32u575-st-nucleo外设

2023-04-13 09:29 UTC, Guozhanxin commented on bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/README.md
> +# xxx 开发板的Arduino生态兼容说明
这里还没改嘛

2023-04-13 09:29 UTC, Guozhanxin commented on bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/README.md
> +xxx 开发板已经完整适配了[RTduino软件包](https://github.com/RTduino/RTduino)，即RT-Thread的Arduino生态兼容层。用户可以按照Arduino的编程习惯来操作该BSP，并且可以使用大量Arduino社区丰富的库，是对RT-Thread生态的极大增强。更多信息，请参见[RTduino软件包说明文档](https://github.com/R
xxx 要换成具体的开发板型号

2023-04-13 09:29 UTC, Guozhanxin commented on bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/README.md
> +> 1. xxxxxxxxx
这里没有可以删了

2023-04-13 10:27 UTC, songw4232 commented on bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/README.md
> +> 1. xxxxxxxxx
今天重新提的PR，这个之前改过了，没注意没有用最新版的

2023-04-13 23:17 UTC, mysterywolf requested changes

2023-04-13 23:17 UTC, mysterywolf commented on bsp/stm32/stm32u575-st-nucleo/board/ports/drv_key.c
> +        //user_button[USER_BUTTON_2].cb = (flex_button_response_callback)btn_2_cb;
```suggestion
    //user_button[USER_BUTTON_2].cb = (flex_button_response_callback)btn_2_cb;
```

2023-04-13 23:17 UTC, mysterywolf commented on bsp/stm32/stm32u575-st-nucleo/board/ports/drv_key.c
> +    //user_button[USER_BUTTON_0].cb = (flex_button_response_callback)btn_0_cb;
请问这个代码是否保留，如果废弃请删除

2023-04-14 02:06 UTC, mysterywolf approved these changes

2023-04-14 06:07 UTC, merged

2023-06-10 18:39 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_spi.c
> +    static uint32_t SPI_CLOCK;
这块为什么要加个static呢？

2023-06-10 19:29 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_spi.c
> +    static uint32_t SPI_CLOCK;
revert it in https://github.com/RT-Thread/rt-thread/pull/7652

2023-06-11 02:15 UTC, songw4232 commented on bsp/stm32/libraries/HAL_Drivers/drv_spi.c
> +    static uint32_t SPI_CLOCK;
这个当时因为提交时SPI_CLOCK变量会报错，所以添加静态的定义。感觉应该是编译器的问题，这个地方的static可以不需要加。

2023-06-11 02:16 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_spi.c
> +    static uint32_t SPI_CLOCK;
是因为这个变量没有被初始化