[HUST_CSE]:设计新的消息接收函数，可以返回消息的实际大小
RT-Thread/rt-thread pull request #7256
Opened 2023-04-15 15:51 UTC by xin-zheqi

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
消息队列接口设计不合理，rt_mq_recv不能传出消息的实际大小

#### 你的解决方案是什么 (what is your solution)
编写一个新的函数可以返回消息的实际大小

#### 在什么测试环境下测试通过 (what is the test environment)
ALL
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-16 02:45 UTC, mysterywolf commented
直接用rt_mq_recv函数即可，返回值改成rt_ssize_t >=0表示正确并返回实际长度， <0返回错误码

2023-04-16 03:13 UTC, xin-zheqi commented
> 
rt_size_t 是 unsigned long 类型
rt_err_t 是long类型
可以继续沿用  rt_err_t

2023-04-16 03:36 UTC, mysterywolf commented
不是rt_size_t 是rt_ssize_t rt_ssize_t是有符号类型，在4.1.1版本之后新加的一个，就是为了这种即返回长度又可能返回错误码的情况准备的

2023-04-16 03:47 UTC, mysterywolf requested changes

2023-04-16 03:47 UTC, mysterywolf commented on components/libc/posix/ipc/mqueue.c
> +    if (result > 0)
```suggestion
    if (result >= 0)
```

2023-04-16 03:47 UTC, mysterywolf commented on src/ipc.c
> +rt_base_t rt_mq_recv(rt_mq_t    mq,
```suggestion
rt_ssize_t rt_mq_recv(rt_mq_t    mq,
```

2023-04-16 03:49 UTC, xin-zheqi commented on src/ipc.c
> +rt_base_t rt_mq_recv(rt_mq_t    mq,
好的👌

2023-04-16 03:53 UTC, mysterywolf commented
请往我的邮箱里随便发点什么 meco@rt-thread.org

2023-04-16 04:37 UTC, mysterywolf commented on src/ipc.c
> +    len = size > mq->msg_size ? mq->msg_size : size;
msg_size 保存的并不是真实接到的数据长度

2023-04-16 04:38 UTC, mysterywolf commented on src/ipc.c
> +    len = size > mq->msg_size ? mq->msg_size : size;
msg_size 保存的并不是每则消息的真实大小

2023-04-16 05:57 UTC, xin-zheqi commented on src/ipc.c
> +    len = size > mq->msg_size ? mq->msg_size : size;
改了一下 在每个发送的报文前面添加了一个四字节的报文长度
接收的时候先取出报文长度在取出报文

2023-04-18 02:49 UTC, mysterywolf commented
感谢PR 由于设计到内核修改，review会比较慢

2023-04-22 20:49 UTC, mysterywolf commented
你好 请补充一个测试例程到：https://github.com/RT-Thread/rt-thread/tree/master/examples 例程暂时扔在这里就可以

2023-04-23 07:42 UTC, xin-zheqi commented
> 

按照操作手册上的例程编写了一个差不多的

2023-04-29 05:13 UTC, mysterywolf commented
@Guozhanxin 郭老师麻烦review一下这个PR呗  我觉得没啥问题了

2023-05-24 03:43 UTC, mysterywolf requested changes

2023-05-24 03:43 UTC, mysterywolf commented on examples/message_queue/messagequeue_tc.c
> +ALIGN(RT_ALIGN_SIZE)
```suggestion
rt_align(RT_ALIGN_SIZE)
```

2023-05-24 03:43 UTC, mysterywolf commented on examples/message_queue/messagequeue_tc.c
> +ALIGN(RT_ALIGN_SIZE)
```suggestion
rt_align(RT_ALIGN_SIZE)
```

2023-05-24 03:43 UTC, mysterywolf commented on src/ipc.c
> + *           rt_mb_recv(),      rt_mq_recv(),       rt_mq_send_wait()
这块revert一下

2023-05-24 03:44 UTC, mysterywolf commented
请往我邮箱里随便发点什么 meco@rt-thread.org

2023-05-24 03:56 UTC, Guozhanxin commented on src/ipc.c
> +    rt_memcpy(((rt_size_t *)(msg + 1)) + 1, buffer, size);
这一段太难理解了。。。

要不加个专门算偏移的宏咋样

2023-06-04 00:21 UTC, Guozhanxin approved these changes

2023-06-05 05:54 UTC, mysterywolf approved these changes

2023-06-06 17:54 UTC, mysterywolf requested changes

2023-06-06 17:54 UTC, mysterywolf commented on src/ipc.c
> +#endif
```suggestion
#define GET_MESSAGEBYTE_ADDR(msg)               (((rt_size_t *)((msg) + 1)) + 1)          /* The first block is message head and the next four bytes are message's length, thus this is the first byte of the real message */
```

2023-06-06 17:55 UTC, mysterywolf commented on src/ipc.c
> + *           The front four Bytes are the length of the message
```suggestion
 *           The front four bytes are the length of the message
```

2023-06-21 12:54 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/commit/33f550cb65c950068ff04c331daeeda3547d2e50

2023-06-21 12:54 UTC, closed without merging