解决了dist复制不全的问题，以及mdkdist.py中的问题
RT-Thread/rt-thread pull request #7278
Opened 2023-04-17 08:38 UTC by linshire

## 拉取/合并请求描述：(PR description)

[
在bl808的m0中，dist复制不全
添加并修改了一些脚本文件，修改了mkdist.py，这似乎是个bug
在ubuntu22下能够正常打包，且打包的工程中能够正常编译，正常使用menuconfig配置

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-17 17:28 UTC, mysterywolf approved these changes

2023-04-19 01:37 UTC, mysterywolf commented on tools/mkdist.py
> +            found = 0
此处为啥放在这里了呀

2023-04-23 02:51 UTC, flyingcys commented
本地测试，脚本可正常运行

2023-04-29 04:50 UTC, Guozhanxin commented on tools/mkdist.py
> +            found = 0
这个修改看起来确实有点怪

2023-04-29 04:51 UTC, Guozhanxin requested changes
这个文件不修改的话，之前的问题是什么，可以贴几张截图看看吗？

2023-04-29 04:53 UTC, mysterywolf commented
这个PR会上讨论一下

2023-05-04 00:55 UTC, supperthomas approved these changes

2023-05-04 14:54 UTC, supperthomas commented
@linshire 可以把這個src部分單獨PR出來，BSP部分另外建一個PR, src部分用這個一個PR。

2023-05-12 04:12 UTC, mysterywolf commented on tools/mkdist.py
> +            found = 0
```suggestion
                found = 0
```

2023-05-12 04:13 UTC, mysterywolf approved these changes

2023-05-12 04:14 UTC, merged