[HUST CSE]Modify invalid links
RT-Thread/rt-thread pull request #7279
Opened 2023-04-17 10:29 UTC by arche8

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
README 里有许多文档对应的官网链接已经失效，点击会直接跳转主页，需要替换。

#### 你的解决方案是什么 (what is your solution)
找到真实的链接，对相应的失效链接进行替换。

#### 在什么测试环境下测试通过 (what is the test environment)
只是对链接进行替换，不影响编译运行。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-17 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7279) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7279) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7279) it.</sub>

2023-04-17 16:55 UTC, mysterywolf approved these changes

2023-04-18 01:50 UTC, Guozhanxin commented on bsp/imxrt/docs/IMXRT系列驱动介绍.md
> +| 1    | [GPIO](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/device/pin/pin.md) | 操作 GPIO 管脚                                   |
这里不用加.md

2023-04-18 04:25 UTC, arche8 commented on bsp/imxrt/docs/IMXRT系列驱动介绍.md
> +| 1    | [GPIO](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/device/pin/pin.md) | 操作 GPIO 管脚                                   |
已经修改

2023-04-18 05:26 UTC, shandianchengzi requested changes
change req

2023-04-18 05:26 UTC, shandianchengzi commented on bsp/renesas/docs/Introduction_to_RA_Series_Drives.md
> +| [QSPI](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/device/spi/spi) | Send and receive data via SPI (1, 2, 4-wire).                   |
缺少锚点：https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/device/spi/spi?id=配置 QSPI 设备

2023-04-18 05:33 UTC, shandianchengzi commented on bsp/renesas/docs/Introduction_to_RA_Series_Drives.md
> +| [QSPI](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/device/spi/spi) | Send and receive data via SPI (1, 2, 4-wire).                   |
https://github.com/RT-Thread/rt-thread/issues/7270

2023-04-18 06:11 UTC, arche8 commented
已经进行了修改

2023-04-18 11:12 UTC, Guozhanxin approved these changes

2023-04-18 11:13 UTC, shandianchengzi approved these changes

2023-04-18 11:13 UTC, merged