[Doxygen][components][net]Fix some comments
RT-Thread/rt-thread pull request #7280
Opened 2023-04-17 12:40 UTC by Hustrookies

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

修改了doxygen所报告的一些注释中的问题

#### 你的解决方案是什么 (what is your solution)

Fix the comments

#### 在什么测试环境下测试通过 (what is the test environment)

no need

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-17 12:53 UTC, Hustrookies commented
在修改 components/net/netdev/src/netdev.c 这个文件的过程中，我发现所有的含有dns_num参数的函数都缺少这一个参数注释。本来我以为是dns的数目的意思，但理解程序后发现这个地方是dns的序号的意思，感觉命名为dns_id可能会更好？

2023-04-18 00:52 UTC, Hustrookies commented on components/net/lwip-dhcpd/dhcp_server_raw.c
> +
`/**
* Find a dhcp client node by ip address
*
* @param dhcpserver The dhcp server
* @param chaddr Mac address
* @param hlen   Mac address length
* @return dhcp client node
*/
static struct dhcp_client_node *
dhcp_client_find(struct dhcp_server *dhcpserver, struct dhcp_msg *msg,
                 u8_t *opt_buf, u16_t len)`
删去的原因是这部分注释直接复制了前面函数的注释，这里需要改成正确的吗？我看类似的函数没有写注释，就直接删去了

2023-04-18 14:16 UTC, supperthomas requested changes

2023-04-18 14:16 UTC, supperthomas commented on components/net/lwip-dhcpd/dhcp_server_raw.c
> +
这里可以尝试修复一下。如果不会修复，可以保留原样，提issue。

2023-04-18 15:50 UTC, supperthomas commented
还有这个commit太多了。把它合成一个吧

2023-04-18 17:10 UTC, Hustrookies commented
好的，我尽快修改

2023-04-19 01:17 UTC, Hustrookies commented on components/net/lwip-dhcpd/dhcp_server_raw.c
> +
已经尝试修复了，您看看有没有问题？

2023-04-19 01:26 UTC, supperthomas approved these changes

2023-04-19 01:51 UTC, mysterywolf commented
> 还有这个commit太多了。把它合成一个吧

没关系 我们合并的时候可以压成一个，如果不会rebase可以不用压成一个commit

2023-04-19 01:53 UTC, mysterywolf requested changes

2023-04-19 01:53 UTC, mysterywolf commented on components/net/lwip-dhcpd/dhcp_server_raw.c
> +}
此处格式有问题，此处不应该被修改。

2023-04-19 06:39 UTC, Hustrookies commented on components/net/lwip-dhcpd/dhcp_server_raw.c
> +}
已经修复

2023-04-21 05:25 UTC, mysterywolf approved these changes

2023-04-21 05:25 UTC, merged

2023-04-21 05:26 UTC, mysterywolf commented
感谢提交PR