合并ch32v208与RT1060的readme
RT-Thread/rt-thread pull request #7297
Opened 2023-04-18 03:37 UTC by Yaochenger

2023-04-18 03:48 UTC, aozima commented
标题党，我还以为2个芯片合并了。。

2023-04-18 03:50 UTC, mysterywolf commented
人家说的就是合并readme😓

2023-04-18 03:55 UTC, mysterywolf requested changes

2023-04-18 03:55 UTC, mysterywolf commented on bsp/wch/risc-v/ch32v208w-r0/README_ZN.md
> +**中文**|[英文](README.md)
```suggestion
**中文** | [英文](README.md) 
```

2023-04-18 03:55 UTC, mysterywolf commented on bsp/imxrt/imxrt1060-nxp-evk/README_zh.md
> +**中文**|[英文](README.md)
```suggestion
**中文** | [英文](README.md) 
```

2023-04-18 03:55 UTC, mysterywolf commented on bsp/imxrt/imxrt1060-nxp-evk/README.md
> +**英文**|[中文](README_zh.md)
```suggestion
**英文** | [中文](README_zh.md) 
```

2023-04-18 11:47 UTC, mysterywolf approved these changes

2023-04-18 15:08 UTC, closed without merging

2023-04-19 01:34 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/pull/7307