[HUST CSE][bsp] fix some documents link error
RT-Thread/rt-thread pull request #7335
Opened 2023-04-21 06:24 UTC by wsxk

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
bsp目录下的若干子目录中的README.md 文档中的某些链接存在问题，需要修补

#### 你的解决方案是什么 (what is your solution)
1. bsp/allwinner_tina/README.md 中的 https://github.com/uestczyh222/tina-spl.git 链接已经失效，更改为 https://github.com/lymzzyh/tina-spl.git

2. bsp/nuclei/gd32vf103_rvstar/README.md中的env工具下载链接 https://www.rt-thread.org/document/site/tutorial/env-video
已经失效，更换为新的下载地址 https://www.rt-thread.org/download.html#download-rt-thread-env-tool

3. bsp/nuclei/nuclei_fpga_eval/README.md中的env工具下载链接 https://www.rt-thread.org/document/site/tutorial/env-video
已经失效，更换为新的下载地址 https://www.rt-thread.org/download.html#download-rt-thread-env-tool

4. bsp/smartfusion2/README.md中的链接 https://www.rt-thread.org/document/site/ 虽然可以重定向到https://www.rt-thread.org/document/site/#/ ，但是观察到重定向访问目标站点需要耗费更长时间，故提出此修改

5. bsp/synwit/swm320/README.md中的链接 https://www.rt-thread.org/document/site/ 虽然可以重定向到https://www.rt-thread.org/document/site/#/ ，但是观察到重定向访问目标站点需要耗费更长时间，故提出此修改

6. bsp/synwit/swm341/README.md中的链接 https://www.rt-thread.org/document/site/ 虽然可以重定向到https://www.rt-thread.org/document/site/#/ ，但是观察到重定向访问目标站点需要耗费更长时间，故提出此修改

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-21 06:30 UTC, shandianchengzi approved these changes

2023-04-21 06:30 UTC, shandianchengzi commented on bsp/smartfusion2/README.md
> +- [学习路线 - RT-Thread 文档中心](https://www.rt-thread.org/document/site/#/)
这个可以不改

2023-04-21 10:36 UTC, shandianchengzi commented
https://github.com/RT-Thread/rt-thread/issues/7270

2023-04-22 04:25 UTC, mysterywolf requested changes

2023-04-22 04:25 UTC, mysterywolf commented on bsp/smartfusion2/README.md
> +- [学习路线 - RT-Thread 文档中心](https://www.rt-thread.org/document/site/#/)
此处不需要改

2023-04-22 04:25 UTC, mysterywolf commented on bsp/synwit/swm320/README.md
> +* [RT-Thread 文档中心](https://www.rt-thread.org/document/site/#/)
此处不需要改

2023-04-22 04:25 UTC, mysterywolf commented on bsp/synwit/swm341/README.md
> +* [RT-Thread 文档中心](https://www.rt-thread.org/document/site/#/)
此处不需要改

2023-04-22 05:06 UTC, wsxk commented on bsp/smartfusion2/README.md
> +- [学习路线 - RT-Thread 文档中心](https://www.rt-thread.org/document/site/#/)
已经修改

2023-04-22 05:06 UTC, wsxk commented on bsp/synwit/swm320/README.md
> +* [RT-Thread 文档中心](https://www.rt-thread.org/document/site/#/)
已改正

2023-04-22 05:07 UTC, wsxk commented on bsp/synwit/swm341/README.md
> +* [RT-Thread 文档中心](https://www.rt-thread.org/document/site/#/)
已更改

2023-04-22 05:28 UTC, mysterywolf approved these changes

2023-04-22 10:11 UTC, CuttySark1869 approved these changes

2023-04-22 11:23 UTC, shandianchengzi approved these changes

2023-04-22 18:18 UTC, merged