fix ipv6 compatibility issues
RT-Thread/rt-thread pull request #7339
Opened 2023-04-21 08:55 UTC by xiaoniaoyou6hua

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
在使用2.1.2版本lwip组件中，开启ipv6从编译到运行都遇到了问题，提供该修改策略。

#### 你的解决方案是什么 (what is your solution)
首先声明，这不是一个充分解决```ipv6```问题的```pr```，算是一份必要不充分的修改。
```
- #define IP6_FRAG_HLEN    8
+ #define IP6_FRAG_HLEN    12
```
这里的修改是为了应对不同架构硬件平台指针大小```size```差异，出现```ip6_frag.c line 115```断言。
```
//components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.c line 115

#if !IPV6_FRAG_COPYHEADER
  LWIP_ASSERT("sizeof(struct ip6_reass_helper) <= IP6_FRAG_HLEN, set IPV6_FRAG_COPYHEADER to 1",
    sizeof(struct ip6_reass_helper) <= IP6_FRAG_HLEN);
#endif /* !IPV6_FRAG_COPYHEADER */
```
其余说明可以参考issues #6985 中我个人的评论。
如果想让ipv6功能跑起来，还需要在```components/net/lwip/port/lwipopts.h```考量下面这两行代码的处理方式，这边的问题同样在上述 issues #6985 中提及，鉴于还没来得及找到比较好的处理方式，暂未处理。

```c
//components/net/lwip/port/lwipopts.h line 645

#include "lwip/ip_addr.h"
struct netif *lwip_ip4_route_src(const ip4_addr_t *dest, const ip4_addr_t *src);
```
#### 在什么测试环境下测试通过 (what is the test environment)
将上述`components/net/lwip/port/lwipopts.h`中提及的两行代码注释掉，编译会出现警告，但是功能可以正常运行。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-21 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7339) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7339) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7339) it.</sub>

2023-04-22 05:39 UTC, geniusgogo requested changes
将头文件包含引入的ipv6地址结构体不统一的问题一起考虑修复吧

2023-04-24 04:05 UTC, xiaoniaoyou6hua commented
现在将```components/net/lwip/port/lwipopts.h```中引起率先隐式包含造成宏缺失的关键两句做处理。

这里为了声明

```
struct netif *lwip_ip4_route_src(const ip4_addr_t *dest, const ip4_addr_t *src);
```

需要```ip4_addr_t```结构体定义包含了```lwip/ip_addr.h```头文件，现将声明直接放置到```lwip/ip_addr.h```头文件下，虽然在```components/net/lwip/port/lwipopts.h```中宏替换

```
#define LWIP_HOOK_IP4_ROUTE_SRC(src, dest)  lwip_ip4_route_src(dest, src)
```

拿不到接口声明，但是在具体的```.c```调用中是拿得到的。

经编译烧录上板测试功能正常。

2023-04-25 09:29 UTC, geniusgogo approved these changes

2023-04-26 01:19 UTC, BernardXiong approved these changes

2023-04-26 01:19 UTC, merged