修复失效链接https://github.com/TanekLiang
RT-Thread/rt-thread pull request #7355
Opened 2023-04-23 09:52 UTC by Sseven731

修复失效链接https://github.com/TanekLiang、xfwangqiang (xfwangqiang) - Gitee.com

2023-04-23 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7355) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7355) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7355) it.</sub>

2023-04-23 23:45 UTC, mysterywolf requested changes

2023-04-23 23:45 UTC, mysterywolf commented on components/drivers/spi/sfud/README.md
> +|[GD25Q16B](http://www.gigadevice.com/product/detail/5/410.html)|GigaDevice|16Mb|120Mhz|不支持|未测试| by [TanekLiang](https://github.com/liangyongxiang) |
```suggestion
|[GD25Q16B](http://www.gigadevice.com/product/detail/5/410.html)|GigaDevice|16Mb|120Mhz|不支持|未测试| by [Liang Yongxiang](https://github.com/liangyongxiang) |
```

2023-04-24 04:46 UTC, mysterywolf approved these changes

2023-04-24 04:47 UTC, merged

2023-04-25 03:57 UTC, shandianchengzi commented
https://github.com/RT-Thread/rt-thread/issues/7270