消息队列支持优先级
RT-Thread/rt-thread pull request #7382
Opened 2023-04-26 09:20 UTC by zhkag

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-26 13:20 UTC, mysterywolf commented
这种关键性内核改动需要在PR里详细介绍一下 包括目的 方法和测试结果 并配套测试例程

2023-04-26 13:35 UTC, zhkag commented
> 这种关键性内核改动需要在PR里详细介绍一下 包括目的（为什么要改） 方法（怎么改）和测试结果 并配套测试例程

好的

2023-06-19 03:48 UTC, Guozhanxin commented on src/ipc.c
> +        prevNode = node;
变量命名需要符合规范

2023-06-19 03:50 UTC, Guozhanxin commented on src/ipc.c
> +    struct rt_mq_message *node, *prevNode = RT_NULL;
变量命名

2023-06-26 02:38 UTC, Guozhanxin approved these changes

2023-06-26 03:36 UTC, mysterywolf requested changes

2023-06-26 03:36 UTC, mysterywolf commented on src/Kconfig
> +    menuconfig RT_USING_MESSAGEQUEUE
只有一个子选项，目前没必要做成menuconfig，
```
config RT_USING_MESSAGEQUEUE_PRIORITY
    bool "Enable message queue priority"
    depends on RT_USING_MESSAGEQUEUE
    default n
```

2023-06-26 03:58 UTC, mysterywolf approved these changes

2023-06-26 04:06 UTC, merged