<pin>更新pin num命令
RT-Thread/rt-thread pull request #7390
Opened 2023-04-26 12:47 UTC by HelloByeAll

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
pin num 命令输入的GPIO字符串不合理， 不同平台GPIO命令不一致，示例命令应该由驱动层输出提供。例如rockchip GPIO格式为GPIO0_A0, STM32为PA0

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-26 23:49 UTC, mysterywolf requested changes

2023-04-26 23:49 UTC, mysterywolf commented on bsp/airm2m/air32f103/libraries/rt_drivers/drv_gpio.c
> +    rt_kprintf("Px.y   x:A~Z  y:0~15\n");
```suggestion
    rt_kprintf("Px.y   x:A~Z  y:0~15, e.g. PA.0\n");
```

2023-04-26 23:49 UTC, mysterywolf commented on bsp/synwit/swm341/drivers/drv_gpio.c
> +    rt_kprintf("Px.y  x:A/B/C/D/E/M/N  y:0~15\n");
像这种xy的，都麻烦给个例子

2023-04-27 01:29 UTC, thewon86 commented
不要应用层可移植性了？

2023-04-27 01:35 UTC, mysterywolf commented
> 不要应用层可移植性了？

引脚这个东西没有什么可移植性吧，不同的板卡引脚不可能完全一致，完全由任务决定，我认为只要引脚的名字符合厂商的规定习惯即可，非要按照STM32的命名方式给其他厂商的MCU引脚命名也是不可取的。

2023-04-27 02:04 UTC, HelloByeAll commented on bsp/synwit/swm341/drivers/drv_gpio.c
> +    rt_kprintf("Px.y  x:A/B/C/D/E/M/N  y:0~15\n");
> 像这种xy的，都麻烦给个例子

已添加，还有这个麻烦处理一下
https://github.com/RT-Thread/rt-thread/pull/7304

2023-04-27 03:14 UTC, mysterywolf commented on components/drivers/misc/pin.c
> +    rt_kprintf("GPIO e.g.:");
这个位置貌似没写全

2023-04-27 05:07 UTC, thewon86 commented
> > 不要应用层可移植性了？
> 
> 引脚这个东西没有什么可移植性吧，不同的板卡引脚不可能完全一致，完全由任务决定，我认为只要引脚的名字符合厂商的规定习惯即可，非要按照STM32的命名方式给其他厂商的MCU引脚命名也是不可取的。

所以，系统封装一遍以后，使用stm32系列的时候用 “PA0”，使用 rockchip 的时候用 “GPIO0_A0” 格式？封装了个寂寞

2023-04-27 05:31 UTC, HelloByeAll commented on components/drivers/misc/pin.c
> +    rt_kprintf("GPIO e.g.:");
> 这个位置貌似没写全

这里向驱动层调用了一个无效的名字触发打印底层的提示

2023-04-27 05:32 UTC, HelloByeAll commented
> > > 不要应用层可移植性了？
> > 
> > 
> > 引脚这个东西没有什么可移植性吧，不同的板卡引脚不可能完全一致，完全由任务决定，我认为只要引脚的名字符合厂商的规定习惯即可，非要按照STM32的命名方式给其他厂商的MCU引脚命名也是不可取的。
> 
> 所以，系统封装一遍以后，使用stm32系列的时候用 “PA0”，使用 rockchip 的时候用 “GPIO0_A0” 格式？封装了个寂寞

你没有能力去约束芯片厂的定义规范，就只能去兼容他的规范

2023-04-27 07:17 UTC, Guozhanxin commented
之前的字符串抽象是基于 PORT + PIN 的格式抽象的，并以 `.` 来分割。之前调研过，应该所有的芯片都有 PORT 的概念的。只不过，有的是数字，有的是 A-Z，所以这里说清楚，RTT对PIN的抽象就好了吧

2023-04-27 11:37 UTC, HelloByeAll commented
> 之前的字符串抽象是基于 PORT + PIN 的格式抽象的，并以 `.` 来分割。之前调研过，应该所有的芯片都有 PORT 的概念的。只不过，有的是数字，有的是 A-Z，所以这里说清楚，RTT对PIN的抽象就好了吧
> 
> ![image](https://user-images.githubusercontent.com/25633294/234789501-d0064870-af0b-465a-ab5b-9d24c11dfc00.png)

这里例子是Px.y x是字母，y是数字，并且pin框架中也是按这个格式过滤的。NXP “IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B0_03” 、ROCK “GPIO3_A5”这种命令如何操作呢？而且既然ops中设计了get_pin，那就是输入的名字格式是由驱动层判断的，否则和之前的宏GET_PIN有什么区别呢？

2023-04-28 05:28 UTC, thewon86 commented
> > 之前的字符串抽象是基于 PORT + PIN 的格式抽象的，并以 `.` 来分割。之前调研过，应该所有的芯片都有 PORT 的概念的。只不过，有的是数字，有的是 A-Z，所以这里说清楚，RTT对PIN的抽象就好了吧
> > ![image](https://user-images.githubusercontent.com/25633294/234789501-d0064870-af0b-465a-ab5b-9d24c11dfc00.png)
> 
> 这里例子是Px.y x是字母，y是数字，并且pin框架中也是按这个格式过滤的。NXP “IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B0_03” 、ROCK “GPIO3_A5”这种命令如何操作呢？而且既然ops中设计了get_pin，那就是输入的名字格式是由驱动层判断的，否则和之前的宏GET_PIN有什么区别呢？

因为是在pin框架里，所有底层驱动应该按照框架定义的规范填写接口，交给应用层的是一个有固定确定明确定义的一套api，而不是根据使用的芯片不同重新定义框架api的定义。这是框架存在的最基本的特征

2023-04-28 11:03 UTC, HelloByeAll commented
> > > 之前的字符串抽象是基于 PORT + PIN 的格式抽象的，并以 `.` 来分割。之前调研过，应该所有的芯片都有 PORT 的概念的。只不过，有的是数字，有的是 A-Z，所以这里说清楚，RTT对PIN的抽象就好了吧
> > > ![image](https://user-images.githubusercontent.com/25633294/234789501-d0064870-af0b-465a-ab5b-9d24c11dfc00.png)
> > 
> > 这里例子是Px.y x是字母，y是数字，并且pin框架中也是按这个格式过滤的。NXP “IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_B0_03” 、ROCK “GPIO3_A5”这种命令如何操作呢？而且既然ops中设计了get_pin，那就是输入的名字格式是由驱动层判断的，否则和之前的宏GET_PIN有什么区别呢？
> 
> 因为是在pin框架里，所有底层驱动应该按照框架定义的规范填写接口，交给应用层的是一个有固定确定明确定义的一套api，而不是根据使用的芯片不同重新定义框架api的定义。这是框架存在的最基本的特征

那现在补丁修改以后api的定义发生变化了吗？没变呀

2023-07-08 00:14 UTC, mysterywolf approved these changes

2023-07-19 22:45 UTC, merged