修复serial_v2.c中可能产生的死循环
RT-Thread/rt-thread pull request #7394
Opened 2023-04-27 02:14 UTC by 7YZ7

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
uart设置为RT_DEVICE_FLAG_TX_BLOCKING时，程序会死循环。

#### 你的解决方案是什么 (what is your solution)
在第693行后添加语句rt_memset(&tx_fifo->rb, RT_NULL, sizeof(tx_fifo->rb));

#### 在什么测试环境下测试通过 (what is the test environment)
在任何测试环境下都可通过
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-28 02:20 UTC, mysterywolf commented
related: https://github.com/RT-Thread/rt-thread/issues/7331

2023-04-28 02:21 UTC, supperthomas approved these changes

2023-05-14 15:50 UTC, BernardXiong commented on components/drivers/serial/serial_v2.c
> +                                rt_memset(&tx_fifo->rb, RT_NULL, sizeof(tx_fifo->rb));
这里对齐有问题吧，是向serial对齐。

2023-05-15 04:01 UTC, mysterywolf requested changes

2023-05-15 04:01 UTC, mysterywolf commented on components/drivers/serial/serial_v2.c
> +                                rt_memset(&tx_fifo->rb, RT_NULL, sizeof(tx_fifo->rb));
```suggestion
            rt_memset(&tx_fifo->rb, RT_NULL, sizeof(tx_fifo->rb));
```

2023-05-15 04:02 UTC, mysterywolf approved these changes

2023-05-15 06:42 UTC, Guozhanxin approved these changes

2023-05-15 06:42 UTC, merged