[Infineon]Add RTduino support and fix i2c init error
RT-Thread/rt-thread pull request #7396
Opened 2023-04-27 02:50 UTC by Rbb666

## 拉取/合并请求描述：(PR description)

[
请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；

并确认并列出已经在什么情况或板卡上进行了测试。

#### 为什么提交这份PR (why to submit this PR)
psoc6-evaluationkit-062S2 开发板添加 RTduino 适配，并解决硬件I2C初始化失败不直接返回继续运行的问题。

#### 在什么测试环境下测试通过 (what is the test environment)
psoc6-evaluationkit-062S2
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-27 03:07 UTC, mysterywolf requested changes

2023-04-27 03:07 UTC, mysterywolf commented on bsp/Infineon/psoc6-evaluationkit-062S2/applications/arduino_pinout/pins_arduino.c
> +    {D0, GET_PIN(8,0), "i2c4"},                        /* I2C-SCL (Wire) */
请参照这个https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.c 重新调整一下引脚布局，这个引脚分布不是Arduino的标准分布，板子插上Arduino扩展板是无法工作的。除非特殊需要，Arduino标准插槽不对接SPI，对接PWM。

2023-04-27 03:10 UTC, Rbb666 commented on bsp/Infineon/psoc6-evaluationkit-062S2/applications/arduino_pinout/pins_arduino.c
> +    {D0, GET_PIN(8,0), "i2c4"},                        /* I2C-SCL (Wire) */
好的，稍后修改

2023-06-21 05:35 UTC, mysterywolf commented
这个PR拆成两个PR吧，I2C先拆出来合并掉吧

2023-07-29 04:14 UTC, closed without merging