Update the use of 'realloc','malloc','calloc'
RT-Thread/rt-thread pull request #7400
Opened 2023-04-27 11:58 UTC by zouziyu2002

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
存在realloc函数，malloc函数，calloc函数使用后未重新定义的情况

#### 你的解决方案是什么 (what is your solution)
重新定义一次

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-04-27 11:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7400) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7400) it.</sub>

2023-04-27 12:27 UTC, fly1ngpengu1ns commented
这份pr只修改了rtt本身的文件中，缺少类型转换的问题，而没有修改其它厂商文件中的问题。如果您认为其它厂商的文件也需要修改的话，我们后续也会安排修改，谢谢

2023-04-28 00:18 UTC, mysterywolf approved these changes

2023-04-28 00:19 UTC, mysterywolf commented
> 这份pr只修改了rtt本身的文件中，缺少类型转换的问题，而没有修改其它厂商文件中的问题。如果您认为其它厂商的文件也需要修改的话，我们后续也会安排修改，谢谢

RT-Thread很欢迎这种修改，只要是让代码更优雅、符合逻辑、且利于阅读的修改都是欢迎的。

这种非致命性错误就不用改其他第三方的代码了，否则我们报上去人家可能不认为是什么问题。

2023-04-28 02:02 UTC, fly1ngpengu1ns commented
> > 这份pr只修改了rtt本身的文件中，缺少类型转换的问题，而没有修改其它厂商文件中的问题。如果您认为其它厂商的文件也需要修改的话，我们后续也会安排修改，谢谢
> 
> 感谢提交PR！RT-Thread很欢迎这种修改，只要是让代码更优雅、符合逻辑、且利于阅读的修改都是欢迎的。
> 
> 但是这种非致命性错误就不用改其他第三方的代码了，否则我们报上去人家可能不认为是什么问题。

好的，感谢您的支持！

2023-04-28 04:11 UTC, mysterywolf requested changes

2023-04-28 04:11 UTC, mysterywolf commented on bsp/loongson/ls2kdev/drivers/ata/dwc_ahsata.c
> +    uc_priv = (struct ahci_uc_priv*)malloc(sizeof(struct ahci_uc_priv));
突然发现一个问题，麻烦改一下 字母和星号之间要有个空格
```suggestion
    uc_priv = (struct ahci_uc_priv *)malloc(sizeof(struct ahci_uc_priv));
```

2023-04-28 04:24 UTC, zouziyu2002 commented on bsp/loongson/ls2kdev/drivers/ata/dwc_ahsata.c
> +    uc_priv = (struct ahci_uc_priv*)malloc(sizeof(struct ahci_uc_priv));
收到，现在就修改

2023-04-28 04:50 UTC, zouziyu2002 commented on bsp/loongson/ls2kdev/drivers/ata/dwc_ahsata.c
> +    uc_priv = (struct ahci_uc_priv*)malloc(sizeof(struct ahci_uc_priv));
已经完成修改，麻烦查看一下

2023-04-28 04:52 UTC, mysterywolf approved these changes

2023-04-28 04:52 UTC, mysterywolf commented on components/drivers/fdt/src/dtb_get.c
> +            ((struct dtb_header*)dtb_node_head->header)->memreserve = (struct dtb_memreserve *)malloc(sizeof(struct dtb_memreserve) * memreserve_sz);
```suggestion
            ((struct dtb_header *)dtb_node_head->header)->memreserve = (struct dtb_memreserve *)malloc(sizeof(struct dtb_memreserve) * memreserve_sz);
```

2023-04-28 04:54 UTC, mysterywolf requested changes

2023-04-28 04:54 UTC, mysterywolf commented on bsp/simulator/drivers/dfs_win32.c
> +        wdirp = (WINDIR *)rt_malloc(sizeof(WINDIR));
请确认一下这里

2023-04-28 04:54 UTC, mysterywolf commented on components/libc/cplusplus/cpp11/emutls.c
> +        array = (emutls_address_array *)calloc(new_size + 1, sizeof(void*));
```suggestion
        array = (emutls_address_array *)calloc(new_size + 1, sizeof(void *));
```

2023-04-28 04:54 UTC, mysterywolf commented on components/libc/cplusplus/cpp11/emutls.c
> +        array = (emutls_address_array *)realloc(array, (new_size + 1) * sizeof(void*));
```suggestion
        array = (emutls_address_array *)realloc(array, (new_size + 1) * sizeof(void *));
```

2023-04-28 04:55 UTC, zouziyu2002 commented on bsp/simulator/drivers/dfs_win32.c
> +        wdirp = (WINDIR *)rt_malloc(sizeof(WINDIR));
好的

2023-04-28 05:42 UTC, zouziyu2002 commented on components/libc/cplusplus/cpp11/emutls.c
> +        array = (emutls_address_array *)realloc(array, (new_size + 1) * sizeof(void*));
非常抱歉，好像直接把github的代码复制到vs上打开会直接导致那个*号前移，所以有两次commit不小心把所有的*位置全部改了。，现在重新用dev处理了一遍，修改了wdirp = (WINDIR *)rt_malloc(sizeof(WINDIR));此处的问题，同时后面两个void的*也已经加了空格，麻烦再检查一遍改动可以吗？操作失误搞得很乱，很抱歉。

2023-04-28 06:01 UTC, mysterywolf commented on components/libc/cplusplus/cpp11/emutls.c
> +        array = (emutls_address_array *)realloc(array, (new_size + 1) * sizeof(void*));
感谢提交pr 没关系 只要注意不要引入问题就好

2023-04-28 14:55 UTC, merged