[bsp][imxrt1021]新增野火rt1021evk的bsp
RT-Thread/rt-thread pull request #7434
Opened 2023-05-02 14:40 UTC by xym-ee

## 拉取/合并请求描述：(PR description)

- rt1021 armcc 启动文件替换 #6455
- 新增第一阶段野火 rt1021evk 的 bsp

#### 为什么提交这份PR (why to submit this PR)

关于 #6455 里启动文件的问题：nxp 官方新版本的 sdk 里 keil 使用的是 armcc v6，启动文件为 gnu 汇编，目前 1020 系列芯片 keil 工程使用的是 armcc v5，使用 gnu 汇编会报错，替换为早期版本的 armasm 汇编启动文件。

新增了野火 rt1021 evk，并在此板上测试通过。rt1021nxp官方evk重新生成项目后编译通过(一些小改动后面再提PR)

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-04 14:05 UTC, supperthomas requested changes

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/.cproject
> +			<storageModule buildSystemId="org.eclipse.cdt.managedbuilder.core.configurationDataProvider" id="ilg.gnuarmeclipse.managedbuild.cross.config.elf.debug.553091094" moduleId="org.eclipse.cdt.core.set
Please delete the auto-generate file . ref https://github.com/RT-Thread/rt-thread/tree/master/bsp/imxrt/imxrt1052-nxp-evk

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/applications/main.c
> + * 2019-04-29     tyustli      first version
Please change the change log.

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/board/board.c
> + * 2009-01-05     Bernard      first implementation
changelog

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/board/board.h
> + * 2009-09-22     Bernard      add board.h to this bsp
changelog

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/makefile.targets
> +	-$(RM) $(OBJS) *.elf
useless?

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/JLinkSettings.ini
> +EnableFlashBP = 2
useless?

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/EventRecorderStub.scvd
> +<component name="EventRecorderStub" version="1.0.0"/>       <!--name and version of the component-->
useless?

2023-05-04 14:05 UTC, supperthomas commented on bsp/imxrt/imxrt1021-fire-evk/.project
> +    <buildCommand>
useless?

2023-05-04 22:18 UTC, supperthomas approved these changes

2023-05-05 01:29 UTC, supperthomas commented
action ci  https://github.com/RT-Thread/rt-thread/blob/master/.github/workflows/action.yml  .
add the board

2023-05-05 23:32 UTC, mysterywolf commented
你好请把 rt1021 armcc 启动文件替换 这个单独拆出一个PR  这个我需要让NXP的人看一下，到底是维持在AC5还是升级到AC6

2023-05-06 04:48 UTC, xym-ee commented
好的，我关掉这个 pr ，分开提一下

2023-05-06 04:48 UTC, closed without merging