[Renesas]Modifying some script files
RT-Thread/rt-thread pull request #7445
Opened 2023-05-05 05:40 UTC by Rbb666

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
修改konfig,sconscript脚本，添加demo宏控制

#### 在什么测试环境下测试通过 (what is the test environment)
HMI-Board
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-05 05:47 UTC, supperthomas approved these changes

2023-05-12 04:18 UTC, mysterywolf requested changes

2023-05-12 04:18 UTC, mysterywolf commented on bsp/renesas/ra6m3-hmi-board/board/Kconfig
> +                            default y
choice语法块没有default y/n 这个表达式，这行可以删掉
choice主要是看 default 或者是 if 以及config的顺序

2023-05-12 04:18 UTC, mysterywolf commented on bsp/renesas/ra6m3-hmi-board/board/Kconfig
> +                            default y
这个地方改了我就没啥问题了

2023-05-13 06:35 UTC, mysterywolf requested changes

2023-05-13 06:35 UTC, mysterywolf commented on bsp/renesas/ra6m3-hmi-board/board/Kconfig
> +                            default y
```suggestion
```

2023-05-13 06:35 UTC, mysterywolf commented on bsp/renesas/ra6m3-hmi-board/board/Kconfig
> +                            default n
```suggestion
```

2023-05-13 06:36 UTC, mysterywolf requested changes

2023-05-13 06:36 UTC, mysterywolf commented on bsp/renesas/ra6m3-hmi-board/board/Kconfig
> +                            select PKG_USING_LV_MUSIC_DEMO
```suggestion
                            select PKG_USING_LV_MUSIC_DEMO

```

2023-05-13 06:37 UTC, mysterywolf approved these changes

2023-05-13 06:37 UTC, merged