[CI] Added feature to filter out files that do not require cppcheck
RT-Thread/rt-thread pull request #7469
Opened 2023-05-09 18:24 UTC by dejavudwh

## 拉取/合并请求描述：(PR description)

添加了根据ignore_format.yml的ignore_files属性过滤掉不需要cppcheck的文件。

#### 为什么提交这份PR (why to submit this PR)

#7462 
#7458 

#### 你的解决方案是什么 (what is your solution)

1. 遍历整个目录获得所有.ignore_format.yml文件
1.1 读取yml文件
1.2 如果是目录则添加整个目录的文件，否则添加yml的描述文件
1.3 输出一个要过滤的文件列表
2. git diff 列出修改文件
2.1 对比要过滤的文件列表
2.2 筛选之后再进行cppcheck

#### 在什么测试环境下测试通过 (what is the test environment)

Local env & CI

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-10 15:00 UTC, supperthomas requested changes
请添加.c 和log验证正确性~

2023-05-11 08:45 UTC, supperthomas commented
https://github.com/RT-Thread/rt-thread/blob/50a4e8c6625694eedfc2f4db20951daed754c4a3/tools/file_check.py#L46

建议参考一下这里的做法。

2023-05-11 08:51 UTC, supperthomas commented
或者可以在
https://github.com/RT-Thread/rt-thread/blob/master/.github/workflows/file_check.yml
里面通过file_check.py 里面添加cppcheck来检查.c文件。

2023-05-12 04:21 UTC, mysterywolf commented
可以忽视第一个CI检查报错 这个只是提供参考

2023-05-12 04:22 UTC, mysterywolf commented
可以忽视第一个CI报错

2023-05-12 08:02 UTC, dejavudwh commented
> 可以忽视第一个CI报错

@mysterywolf 当前的代码应该是可以验证功能了。

第一个case：没有加入.ignore_format.yml但是不能通过cppcheck的文件，会直接在CI中报错。[https://github.com/dejavudwh/rt-thread/actions/runs/4947656454/jobs/8847331088](case1 workflow)

第二个case：将上述文件加入.ignore_format.yml，可以通过CI。[https://github.com/RT-Thread/rt-thread/actions/runs/4954875899/jobs/8863764103](case2 workflow)

但是和 @supperthomas 讨论之后，发现这个功能加入file_check当中会比较合适，后续可以再提一个pr，对比一下这两种方式。

2023-05-14 03:59 UTC, supperthomas commented
尝试修改了这个文件components/libc/posix/ipc/mqueue.c
从log来看是检查了，但是这里cppcheck应该是反馈失败才对（mqueue.c里有地方cppcheck是会报错的）
但是从CI上看似乎没有报错？这个cppcheck里面的log从哪里可以看到？
https://github.com/RT-Thread/rt-thread/actions/runs/4970409901/jobs/8894260612?pr=7469
```
modified files include c|cpp|cc|cxx:
['bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c', 'components/libc/posix/ipc/mqueue.c']
is determining whether this modified file should ignore cppcheck...
files that need to be checked:
['components/libc/posix/ipc/mqueue.c']
cd /home/runner/work/rt-thread/rt-thread
start cppcheck execution
Checking components/libc/posix/ipc/mqueue.c ...
```

2023-05-14 04:04 UTC, dejavudwh commented
> 尝试修改了这个文件components/libc/posix/ipc/mqueue.c 从log来看是检查了，但是这里cppcheck应该是反馈失败才对（mqueue.c里有地方cppcheck是会报错的） 但是从CI上看似乎没有报错？这个cppcheck里面的log从哪里可以看到？ https://github.com/RT-Thread/rt-thread/actions/runs/4970409901/jobs/8894260612?pr=7469
> 
> ```
> modified files include c|cpp|cc|cxx:
> ['bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c', 'components/libc/posix/ipc/mqueue.c']
> is determining whether this modified file should ignore cppcheck...
> files that need to be checked:
> ['components/libc/posix/ipc/mqueue.c']
> cd /home/runner/work/rt-thread/rt-thread
> start cppcheck execution
> Checking components/libc/posix/ipc/mqueue.c ...
> ```

@supperthomas 我在Python脚本里捕获了cppcheck的stderr，正常来说，如果报错的话会直接sys.exit(1)

```python
for file in file_list_filtered:
    result = subprocess.run(['cppcheck', '--enable=warning', 'performance', 'portability', '--inline-suppr', '--error-exitcode=1', '--force', file], stdout = subprocess.PIPE, stderr = subprocess.PIPE)
    print(result.stdout.decode())
    if result.stderr:
	sys.exit(1)
```

2023-05-14 04:18 UTC, supperthomas commented
> > 尝试修改了这个文件components/libc/posix/ipc/mqueue.c 从log来看是检查了，但是这里cppcheck应该是反馈失败才对（mqueue.c里有地方cppcheck是会报错的） 但是从CI上看似乎没有报错？这个cppcheck里面的log从哪里可以看到？ https://github.com/RT-Thread/rt-thread/actions/runs/4970409901/jobs/8894260612?pr=7469
> > ```
> > modified files include c|cpp|cc|cxx:
> > ['bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c', 'components/libc/posix/ipc/mqueue.c']
> > is determining whether this modified file should ignore cppcheck...
> > files that need to be checked:
> > ['components/libc/posix/ipc/mqueue.c']
> > cd /home/runner/work/rt-thread/rt-thread
> > start cppcheck execution
> > Checking components/libc/posix/ipc/mqueue.c ...
> > ```
> 
> @supperthomas 我在Python脚本里捕获了cppcheck的stderr，正常来说，如果报错的话会直接sys.exit(1)
> 
> ```python
> for file in file_list_filtered:
>     result = subprocess.run(['cppcheck', '--enable=warning', 'performance', 'portability', '--inline-suppr', '--error-exitcode=1', '--force', file], stdout = subprocess.PIPE, stderr = subprocess.PIPE)
>     print(result.stdout.decode())
>     if result.stderr:
> 	sys.exit(1)
> ```



> > 尝试修改了这个文件components/libc/posix/ipc/mqueue.c 从log来看是检查了，但是这里cppcheck应该是反馈失败才对（mqueue.c里有地方cppcheck是会报错的） 但是从CI上看似乎没有报错？这个cppcheck里面的log从哪里可以看到？ https://github.com/RT-Thread/rt-thread/actions/runs/4970409901/jobs/8894260612?pr=7469
> > ```
> > modified files include c|cpp|cc|cxx:
> > ['bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c', 'components/libc/posix/ipc/mqueue.c']
> > is determining whether this modified file should ignore cppcheck...
> > files that need to be checked:
> > ['components/libc/posix/ipc/mqueue.c']
> > cd /home/runner/work/rt-thread/rt-thread
> > start cppcheck execution
> > Checking components/libc/posix/ipc/mqueue.c ...
> > ```
> 
> @supperthomas 我在Python脚本里捕获了cppcheck的stderr，正常来说，如果报错的话会直接sys.exit(1)
> 
> ```python
> for file in file_list_filtered:
>     result = subprocess.run(['cppcheck', '--enable=warning', 'performance', 'portability', '--inline-suppr', '--error-exitcode=1', '--force', file], stdout = subprocess.PIPE, stderr = subprocess.PIPE)
>     print(result.stdout.decode())
>     if result.stderr:
> 	sys.exit(1)
> ```

嗯，你这个分支rebase了？好像 有些乱了，现在CI相关的py可以放到tools/ci 下面。

2023-05-14 04:23 UTC, mysterywolf commented
建议重新开一个PR，将脚本放到tools/ci/文件夹下

2023-05-14 04:24 UTC, supperthomas requested changes

2023-05-14 04:26 UTC, dejavudwh commented
> 嗯，你这个分支rebase了？好像 有些乱了，现在CI相关的py可以放到tools/ci 下面。找一个cppcheck检查会出错的，看看哪里会报错。

@supperthomas 对的，刚刚rebase了一下。之前选用的是bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c这个文件。

一般报错如下：
```shell
start cppcheck execution
Checking bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c ...
Checking bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c: SOC_CH567;SOC_CH568;SOC_SERIES_CH569...
Checking bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c: SOC_SERIES_CH569...
```

2023-05-14 04:26 UTC, dejavudwh commented on bsp/wch/risc-v/.ignore_format.yml
> +- Libraries/ch56x_drivers/ch56x_gpio.c
好的

2023-05-14 04:26 UTC, dejavudwh commented
> 建议重新开一个PR，将脚本放到tools/ci/文件夹下

好的

2023-05-14 04:38 UTC, closed without merging