add result check for configure in `rt_spi_configure`
RT-Thread/rt-thread pull request #7474
Opened 2023-05-11 03:28 UTC by a1012112796

## 拉取/合并请求描述：(PR description)

#### 为什么提交这份PR (why to submit this PR)

- 在 rt_spi_configure 中没有对配置结果做检查，建议补充上
- 偶然发现有人不是很明白这里为何，何时需要执行配置 (ref : https://blog.csdn.net/lilijianqun/article/details/103061547) , 故增加了一行注释说明一下
```DIFF
            if (device->bus->owner == device)
            {
+               /* current device is using, re-configure SPI bus */
                result = device->bus->ops->configure(device, &device->config);

                if (result != RT_EOK)
```

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-11 03:48 UTC, mysterywolf commented
注释可以多写点 不要吝啬😁

2023-05-11 03:50 UTC, mysterywolf requested changes
这个函数最上面的    rt_err_t result;
麻烦帮忙改成
    rt_err_t result = -RT_ERROR;
虽然实际写不写都没有什么区别，但是为了防止后续代码迭代的时候埋坑

2023-05-11 03:50 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> +                if (result != RT_EOK)
```suggestion
                result = device->bus->ops->configure(device, &device->config);
                if (result != RT_EOK)
```

2023-05-11 13:15 UTC, mysterywolf approved these changes

2023-05-11 21:25 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> +    }
这个位置应该让错误码为正确嘛

2023-05-11 22:53 UTC, mysterywolf commented on components/drivers/spi/spi_core.c
> +    }
这个地方不应该加else

2023-05-12 00:31 UTC, a1012112796 commented on components/drivers/spi/spi_core.c
> +    }
这个 `else` 对应的是 `if` 是 `device->bus != RT_NULL` (第 110 行), 意味着此时 device 还没有与总线设备关联,所以无法也无需立即尝试配置总线，但配置参数已经被保存在 `device->config` 了，当传输数据时会使用此配置参数。因此个人认为可以判定为配置成功. @mysterywolf

2023-05-12 04:08 UTC, mysterywolf approved these changes

2023-05-12 04:10 UTC, Guozhanxin approved these changes

2023-05-12 04:11 UTC, merged