[HUST CSE][components][udisk.c] add two checkout procedures after malloc to make sure allocating successfully
RT-Thread/rt-thread pull request #7475
Opened 2023-05-11 03:41 UTC by kunpHust

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

components/drivers/usb/usbhost/class/udisk.c文件中的rt_udisk_run函数中第313行和第351行分别调用了rt_malloc函数进行内存分配，但是没有对分配结果进行检查就继续调用了rt_memset函数。作为对比，同样在rt_udisk_run函数中的第284行的指针sector也调用rt_malloc函数进行了内存分配，但先进行了空指针检查，随后才继续调用rt_memset函数。因此认为第313行和第351行的内存分配行为存在潜在的风险。

#### 你的解决方案是什么 (what is your solution)

参考第284行调用rt_malloc函数后的处理步骤，对第313行和第351行的rt_malloc函数分配内存的行为分别检查rt_malloc函数的结果，并在分配失败时打印日志。

#### 在什么测试环境下测试通过 (what is the test environment)
通过进行流程分析，并且只添加一个检查分支，不会导致测试不通过。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-11 03:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7475) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7475) it.</sub>

2023-05-11 03:53 UTC, mysterywolf commented
感谢提交PR 
请使用LOG_E  LOG_W LOG_I 等方式增加提示信息 参见：https://github.com/RT-Thread/rt-thread/pull/7474/files

只要不是和用户终端直接交互的，仅仅是单方面输出提示信息的，不建议用rt_kprintf

同时，使用LOG_xxx的文件，开头的位置也要声明LOG的tag，参见：https://github.com/RT-Thread/rt-thread/blob/master/components/libc/compilers/common/ctime.c#L39-L41

```c
#define DBG_TAG    "time"
#define DBG_LVL    DBG_INFO
#include <rtdbg.h>

```

2023-05-11 03:54 UTC, mysterywolf commented
另外我注意到 这里的文件大量使用rt_kprintf来输出信息其实是错误的，请有时间再提提PR 帮忙把这部分修正一下~

2023-05-11 23:05 UTC, mysterywolf requested changes

2023-05-11 23:05 UTC, mysterywolf commented on components/drivers/usb/usbhost/class/udisk.c
> +#define DBG_TAG    "udisk"
```suggestion
#define DBG_TAG    "usbhost.udisk"
```

2023-05-11 23:05 UTC, mysterywolf commented on components/drivers/usb/usbhost/class/udisk.c
> +                LOG_E("ERROR: Allocate partition data buffer failed.");
```suggestion
                LOG_E("Allocate partition data buffer failed.");
```

2023-05-11 23:05 UTC, mysterywolf commented on components/drivers/usb/usbhost/class/udisk.c
> +                    LOG_E("ERROR: Allocate partition data buffer failed.");
```suggestion
                    LOG_E("Allocate partition data buffer failed.");
```

2023-05-11 23:05 UTC, mysterywolf commented on components/drivers/usb/usbhost/class/udisk.c
> +                    LOG_E("ERROR: Allocate partition data buffer failed.");
LOG_E不需要加ERROR关键字，输出的时候会自动加的

2023-05-11 23:05 UTC, mysterywolf commented on components/drivers/usb/usbhost/class/udisk.c
> +                    break;
为何此处使用break 而上面用continue?

2023-05-12 02:30 UTC, kunpHust commented on components/drivers/usb/usbhost/class/udisk.c
> +                    break;
因为我看在我修改之前的代码里if(ret==RT_EOK)语句内部执行完后会继续执行for循环，而else语句中末尾会执行break

2023-05-12 06:38 UTC, kunpHust commented on components/drivers/usb/usbhost/class/udisk.c
> +                    break;
> 为何此处使用break 而上面用continue?

因为我看在我修改之前的代码里if(ret==RT_EOK)语句内部执行完后会继续执行for循环，而else语句中末尾会执行break

2023-05-14 04:07 UTC, mysterywolf approved these changes

2023-05-15 06:35 UTC, Guozhanxin approved these changes

2023-05-15 06:35 UTC, merged