Ci filecheck format ignore
RT-Thread/rt-thread pull request #7499
Opened 2023-05-14 10:57 UTC by dejavudwh

## 拉取/合并请求描述：(PR description)

添加了根据ignore_format.yml的ignore_files属性过滤掉不需要cppcheck的文件。

#### 为什么提交这份PR (why to submit this PR)

#7458 

#### 你的解决方案是什么 (what is your solution)

根据file_check.py中原先过滤出的new_file，再次过滤出C/C++文件，筛选之后再进行cppcheck。

#7497 的另一种方法，这个方法可以提高代码复用性，静态代码分析也属于file check，所以功能上也合理。所以这个版本应该会更好一点。

#### 在什么测试环境下测试通过 (what is the test environment)

fork后repo中的github action测试通过。

修改cppcheck会出现错误的文件：

- [case 1](https://github.com/dejavudwh/rt-thread/actions/runs/4971727577)：不将文件加入.ignore_format.yml，CI报错
- [case 2](https://github.com/dejavudwh/rt-thread/actions/runs/4971968380)：将文件加入.ignore_format.yml的file_path，CI不报错
- [case 3](https://github.com/dejavudwh/rt-thread/actions/runs/4971864633)：将文件加入.ignore_format.yml的dir_path，CI不报错

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-14 14:08 UTC, supperthomas commented
尝试了一下，确实报错。但是好像并没有输出哪里报错了，看下图。
![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/aaf0388f-47d0-4008-a2a8-e3e5d9255d5f)

2023-05-14 14:25 UTC, supperthomas commented
![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/d7f15447-efe6-445a-b857-786c6ae2ec7a)

你改的这个函数看起来也没有正确显示cppcheck里面的错误内容。

这个错误内容可以从哪里看到吗？

![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/8735ff4b-045d-415d-8c9d-1f0b59f6fd86)

2023-05-14 14:34 UTC, dejavudwh commented
> ![图片](https://user-images.githubusercontent.com/60349489/238192011-d7f15447-efe6-445a-b857-786c6ae2ec7a.png)
> 
> 你改的这个函数看起来也没有正确显示cppcheck里面的错误内容。
> 
> 这个错误内容可以从哪里看到吗？下图是我本地的cppcheck检查
> 
> ![图片](https://user-images.githubusercontent.com/60349489/238192054-8735ff4b-045d-415d-8c9d-1f0b59f6fd86.png)

@supperthomas 忘记打stderr了，已经改好了

![image](https://github.com/RT-Thread/rt-thread/assets/47321059/89bc8d11-4969-4925-ab57-af93bf322793)

2023-05-15 15:49 UTC, supperthomas requested changes

2023-05-15 15:49 UTC, supperthomas commented on tools/ci/cpp_check.py
> +# 2021-04-01     LiuKang      the first version
注释改下。

2023-05-15 15:49 UTC, supperthomas commented on tools/ci/format_ignore.py
> +import yaml
头文件注释LICENSE

2023-05-15 15:49 UTC, supperthomas commented on tools/ci/format_ignore.py
> +    def get_new_file(self):
这里是git diff, cpp_check.py里面多余的东西。

2023-05-15 15:49 UTC, supperthomas commented on tools/ci/cpp_check.py
> +    type=click.STRING,
去掉

2023-05-15 15:57 UTC, supperthomas requested changes

2023-05-15 15:57 UTC, supperthomas commented on .github/workflows/static_code_analysis.yml
> +#     branches:
去掉

2023-05-15 16:17 UTC, supperthomas requested changes

2023-05-15 16:17 UTC, supperthomas commented on tools/ci/file_check.py
> +# Copyright (c) 2006-2023, RT-Thread Development Team
这个文件不用改

2023-05-15 16:45 UTC, supperthomas requested changes

2023-05-15 22:06 UTC, mysterywolf commented
@supperthomas 涛哥，这个PR你认为没啥问题之后可以直接合并掉

2023-05-15 22:41 UTC, supperthomas approved these changes

2023-05-15 23:48 UTC, supperthomas approved these changes

2023-05-15 23:50 UTC, supperthomas commented
![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/b535ecd9-c2da-4b1e-9960-79211d5e66e1)

2023-05-15 23:51 UTC, supperthomas commented
感谢PR。

2023-05-15 23:51 UTC, merged