[include][src] Add API to get object name and thread name
RT-Thread/rt-thread pull request #7507
Opened 2023-05-15 12:37 UTC by helloeagleyang

- Added rt_thread_get_name() API
- Added rt_object_get_name() API

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

需要接口去获取 rt-thread中对应object和thread 的name

#### 你的解决方案是什么 (what is your solution)

增加相应的两个API
- rt_object_get_name
- rt_thread_get_name

#### 在什么测试环境下测试通过 (what is the test environment)
HPM6750EVKMINI上添加API测试代码

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-15 12:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7507) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7507) before we can accept your contribution.<br/><hr/>**Fan YANG** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7507) it.</sub>

2023-05-15 23:14 UTC, BernardXiong commented on src/thread.c
> +    return (thread == RT_NULL) ? RT_NULL : rt_object_get_name(&thread->parent);
既然rt_object_get_name有对参数的检查，那么这里可以直接返回即可。

2023-05-16 00:59 UTC, helloeagleyang commented on src/thread.c
> +    return (thread == RT_NULL) ? RT_NULL : rt_object_get_name(&thread->parent);
> 既然rt_object_get_name有对参数的检查，那么这里可以直接返回即可。

我的理解是：这个按目前的的struct rt_thread 结构体的设计的确是可以保证的，但是如果未来对这一块有改动，可能会引发非预期的后果。

2023-05-16 02:01 UTC, mysterywolf commented on src/thread.c
> +    return (thread == RT_NULL) ? RT_NULL : rt_object_get_name(&thread->parent);
这个地方是否考虑成：rt_err_t rt_object_get_name(char *pname, rt_uint8_t len)

因为rt-thread的name字段默认是8个字节，这八个字节全部存储字符，如果直接返回用户直接访问的话，很有可能因为没有\0而越界，如果是API的话是否可以给一个更安全的方式来获取name，即让用户提供一个buffer，这个函数负责将name拷贝到buffer里

2023-05-16 10:45 UTC, BernardXiong commented on include/rtthread.h
> +rt_err_t rt_object_get_name(rt_object_t object, char *pbuf, rt_uint8_t buf_size);
命名方式感觉没必要太绕，可以是

`rt_err_t rt_object_get_name(rt_object_t object, char *name, int name_size);`

2023-05-17 03:26 UTC, mysterywolf requested changes

2023-05-17 03:26 UTC, mysterywolf commented on src/object.c
> +rt_err_t rt_object_get_name(rt_object_t object, char *name, rt_size_t name_size)
```suggestion
rt_err_t rt_object_get_name(rt_object_t object, char *name, rt_uint8_t name_size)
```

2023-05-17 03:28 UTC, mysterywolf commented on src/object.c
> +        (void) rt_strncpy(name, obj_name, name_size);
如果我没记错的话，rt_strncpy/strncpy 这个函数本身也是不安全的，如果长度超过name_size，是强行截断，不会后面加\0

2023-05-17 03:32 UTC, mysterywolf commented on src/object.c
> +        (void) rt_strncpy(name, obj_name, name_size);
我删除了刚才的评论，这么写没啥问题。

2023-05-17 03:34 UTC, mysterywolf requested changes

2023-05-17 03:34 UTC, mysterywolf commented on include/rtthread.h
> +rt_err_t rt_object_get_name(rt_object_t object, char *name, rt_size_t name_size);
```suggestion
rt_err_t rt_object_get_name(rt_object_t object, char *name, rt_uint8_t name_size);
```

2023-05-17 03:34 UTC, mysterywolf commented on include/rtthread.h
> +rt_err_t rt_thread_get_name(rt_thread_t thread, char *name, rt_size_t name_size);
```suggestion
rt_err_t rt_thread_get_name(rt_thread_t thread, char *name, rt_uint8_t name_size);
```

2023-05-17 03:34 UTC, mysterywolf commented on src/thread.c
> +rt_err_t rt_thread_get_name(rt_thread_t thread, char *name, rt_size_t name_size)
```suggestion
rt_err_t rt_thread_get_name(rt_thread_t thread, char *name, rt_uint8_t name_size)
```

2023-05-17 03:34 UTC, helloeagleyang commented on src/object.c
> +rt_err_t rt_object_get_name(rt_object_t object, char *name, rt_size_t name_size)
> 用 rt_size_t 主要是底层用了rt_strncpy, 保持参数数据类型的一致，在后续需要做严格类型检查的时候，这一块就不会被报warning

2023-05-17 03:35 UTC, mysterywolf requested changes

2023-05-17 03:35 UTC, mysterywolf commented on src/object.c
> +        (void) rt_strncpy(name, obj_name, name_size);
```suggestion
        (void) rt_strncpy(name, obj_name, (rt_size_t)name_size);
```

2023-05-17 03:37 UTC, mysterywolf approved these changes

2023-05-17 03:40 UTC, mysterywolf commented on src/object.c
> + *        container
```suggestion
 * @brief This function will return the name of the specified object container
```

2023-05-17 09:40 UTC, BernardXiong approved these changes

2023-05-17 09:40 UTC, merged