add sys_mount&umount2
RT-Thread/rt-thread pull request #7516
Opened 2023-05-16 09:16 UTC by xiao-mang

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

在用户态使用系统调用侧mount、umount，挂载、卸载失败

#### 你的解决方案是什么 (what is your solution)

在内核里加入对系统调用侧mount的对接代码

#### 在什么测试环境下测试通过 (what is the test environment)

qemu环境，使用busybox mount、umount命令可成功对tmp、ext文件系统进行挂载与卸载

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-16 12:27 UTC, geniusgogo requested changes
用户态传下来的地址空间数据最好是先检查再拷贝到内核态来使用。

2023-05-16 13:38 UTC, BernardXiong commented on components/lwp/lwp_syscall.c
> +    if(strcmp(filesystemtype, "ext") == 0)
为什么是专门针对这两个文件系统的mount？应该是通用性的才是

2023-05-17 08:08 UTC, geniusgogo approved these changes

2023-05-17 08:28 UTC, Guozhanxin approved these changes

2023-05-17 08:30 UTC, merged