[bsp][yichip] add yc3122-pos
RT-Thread/rt-thread pull request #7526
Opened 2023-05-18 08:06 UTC by zhiqiandeng

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
添加 yc3122 rt-thread 示例
#### 你的解决方案是什么 (what is your solution)
基本yc3122 搭建

#### 在什么测试环境下测试通过 (what is the test environment)
yc3122-pos
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-18 09:22 UTC, Guozhanxin commented on bsp/yichip/yc3122-pos/drivers/ports/fal/fal_flash_stm32l4_port.c
> +#ifdef FAL_FLASH_PORT_DRIVER_STM32L4
这个fal的文件夹，要删了

2023-05-18 09:24 UTC, Guozhanxin commented on bsp/yichip/yc3122-pos/rtconfig.h
> +#define PKG_USING_LITTLEFS
初始版本不用开这么多配置，一般默认的配置是个比较简单的初始配置

2023-05-18 09:25 UTC, Guozhanxin commented
没有readme文件啊，加一个吧，还有下面这个文件不需要吧，删了吧

![image](https://github.com/RT-Thread/rt-thread/assets/25633294/246fb85d-8a6e-465c-9855-0e30f76c78b7)

2023-05-19 03:34 UTC, BernardXiong commented
这颗芯片是否太小众，太专业化了？如果是这样，是否有不必须提交上来？

2023-05-19 03:48 UTC, Guozhanxin commented on bsp/yichip/yc3122-pos/README.md
> +![YC3122-pos](figures/YC3122-pos.jpg "YC3122-pos")
这个图片路径不对，应该是  `![YC3122-pos](figures/YC3122-pos.png)` 吧

2023-05-19 03:49 UTC, Guozhanxin commented on bsp/yichip/yc3122-pos/README.md
> +- MCU：YC3122  ARM 32-bit Cortex-M0和RISC V 双核处理器，RISC V支持浮点算法主频 192MHz，512KB/1MB/4MB FLASH ，320KB SRAM
看起来，芯片还挺强呀

2023-05-19 06:28 UTC, zhiqiandeng commented on bsp/yichip/yc3122-pos/README.md
> +![YC3122-pos](figures/YC3122-pos.jpg "YC3122-pos")
已修改

2023-05-19 06:28 UTC, zhiqiandeng commented on bsp/yichip/yc3122-pos/rtconfig.h
> +#define PKG_USING_LITTLEFS
已去除

2023-05-19 06:33 UTC, zhiqiandeng commented on bsp/yichip/yc3122-pos/README.md
> +- MCU：YC3122  ARM 32-bit Cortex-M0和RISC V 双核处理器，RISC V支持浮点算法主频 192MHz，512KB/1MB/4MB FLASH ，320KB SRAM
> 芯片是否太小众，太专业化了？如果是这样，是否有不必须提交上来？

可作为通用mcu使用，各个功能都有，后期可以把相应设备补全

2023-05-19 10:33 UTC, Guozhanxin approved these changes

2023-05-20 05:31 UTC, mysterywolf commented on bsp/yichip/yc3122-pos/rtconfig.h
> +#define RT_SFUD_SPI_MAX_HZ 50000000
这块涉及到SPI FLash的可否设计一个开关，用户可以选择打开或者关闭？
参考：https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/board/Kconfig#L65

2023-05-20 05:32 UTC, mysterywolf commented on bsp/yichip/yc3122-pos/rtconfig.h
> +#define RT_SFUD_SPI_MAX_HZ 50000000
后续可以考虑提交一个PR来完善

2023-05-20 05:33 UTC, mysterywolf commented on bsp/yichip/yc3122-pos/rtconfig.h
> +#define RT_SFUD_SPI_MAX_HZ 50000000
只要不是核心功能，尽可能在board/Kconfig里采用开关的方式实现，默认为n，用户需要的时候才会开启。一般外设默认只开启控制台串口和GPIO

2023-05-22 03:16 UTC, supperthomas commented
![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/5321be44-9975-43d7-9b6b-06f7467b1655)

https://github.com/RT-Thread/rt-thread/actions/runs/5041305416/jobs/9040879639

请看下编译log，确认需要提交的文件都已经提交。

2023-05-22 11:50 UTC, zhiqiandeng commented on bsp/yichip/yc3122-pos/Libraries/SConscript
> +	src += ['sdk/libyc_qspi.a']
已添加

2023-05-22 11:57 UTC, zhiqiandeng commented
这个错误是我提交的这个bsp吗？

2023-05-22 12:02 UTC, zhiqiandeng commented
RT-Thread BSP build check / riscv64-unknown (pull_request) 
这个错误编的不是我提的这个bsp吧

2023-05-22 13:33 UTC, supperthomas commented
> RT-Thread BSP build check / riscv64-unknown (pull_request) 这个错误编的不是我提的这个bsp吧

https://github.com/RT-Thread/rt-thread/actions/runs/5046383085/jobs/9051816950?pr=7526   现在再看下，出错的地方。

2023-05-22 13:44 UTC, supperthomas commented
.config 文件可以加一下。

2023-05-22 23:02 UTC, mysterywolf commented
> RT-Thread BSP build check / riscv64-unknown (pull_request) 这个错误编的不是我提的这个bsp吧

这个错误无需理会

2023-05-22 23:05 UTC, mysterywolf commented
.config是一个很重要的文件，它保存了menuconfig的默认设置情况，这个文件需要提交一下。在menuconfig的时候就会自动生成的。这个文件不需要手动修改什么。

2023-05-23 02:21 UTC, zhiqiandeng commented
> .config是一个很重要的文件，它保存了menuconfig的默认设置情况，这个文件需要提交一下。在menuconfig的时候就会自动生成的。这个文件不需要手动修改什么。

已提交

2023-05-23 02:31 UTC, supperthomas approved these changes

2023-05-23 02:35 UTC, mysterywolf approved these changes

2023-05-23 02:35 UTC, mysterywolf approved these changes

2023-05-23 02:36 UTC, supperthomas requested changes

2023-05-23 02:36 UTC, supperthomas commented on bsp/yichip/yc3122-pos/Libraries/SConscript
> +CPPPATH = [cwd + '/sdk', cwd + '/core',cwd + '\CMSIS\Include',cwd + '\CMSIS\Device\YICHIP\YC3122\Include',cwd]
这里左斜杠和右斜杠混用，可以统一一下。

2023-05-23 02:38 UTC, mysterywolf commented on bsp/yichip/yc3122-pos/Libraries/SConscript
> +CPPPATH = [cwd + '/sdk', cwd + '/core',cwd + '\CMSIS\Include',cwd + '\CMSIS\Device\YICHIP\YC3122\Include',cwd]
这块建议用os.path.join来链接，否则在不同操作系统下可能要出问题
os.path.join(cwd, 'CMSIS', 'Include') 这样子

2023-05-23 06:32 UTC, zhiqiandeng commented on bsp/yichip/yc3122-pos/Libraries/SConscript
> +CPPPATH = [cwd + '/sdk', cwd + '/core',cwd + '\CMSIS\Include',cwd + '\CMSIS\Device\YICHIP\YC3122\Include',cwd]
> 这块建议用os.path.join来链接，否则在不同操作系统下可能要出问题 os.path.join(cwd, 'CMSIS', 'Include') 这样子

已修改

2023-05-23 07:32 UTC, supperthomas approved these changes

2023-05-23 07:32 UTC, supperthomas commented
感谢贡献。

2023-05-23 08:07 UTC, merged