Add .config Kconfig file to some old bsp
RT-Thread/rt-thread pull request #7552
Opened 2023-05-23 08:02 UTC by IcyFeather233

## 拉取/合并请求描述：(PR description)

#### 为什么提交这份PR (why to submit this PR)

一些旧的 bsp 没有 Kconfig .config 文件，不方便使用 menuconfig，详见 [这个 issue](一些bsp添加Kconfig .config等文件，方便menuconfig)

#### 你的解决方案是什么 (what is your solution)

我为上述 issue 中缺少 .config 文件的 bsp 添加了 Kconfig 以及 .config 文件

#### 在什么测试环境下测试通过 (what is the test environment)

- OS: Windows10
- RT-Thread Version: master branch
- RT-Thread Env Version: v1.3.5

在上述环境下能正常使用 menuconfig

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-23 08:48 UTC, supperthomas requested changes
https://github.com/RT-Thread/rt-thread/actions/runs/5054836480/jobs/9070253333

CI中的问题尝试处理下。

2023-05-23 08:57 UTC, BernardXiong commented on .github/workflows/action.yml
> +                #- "bluetrum/ab32vg1-ab-prougen"
这个是需要保留的，这个是因为env最近一个更新出问题了

2023-05-23 09:12 UTC, supperthomas commented on .github/workflows/action.yml
> +                #- "bluetrum/ab32vg1-ab-prougen"
嗯，临时测试改下。

2023-05-24 06:52 UTC, IcyFeather233 commented
这个PR的详细说明：
https://club.rt-thread.org/ask/article/f28fc6edf3877f4b.html

2023-05-24 08:11 UTC, supperthomas commented
https://github.com/RT-Thread/rt-thread/actions/runs/5065424527/jobs/9094198457
action 添加menuconfig验证ok.

2023-05-25 01:45 UTC, supperthomas approved these changes

2023-05-25 01:58 UTC, mysterywolf requested changes

2023-05-25 01:58 UTC, mysterywolf commented on bsp/lpc2148/Kconfig
> +# default 中的内容要灵活更改
```suggestion
```

2023-05-25 01:58 UTC, mysterywolf commented on bsp/lpc178x/rtconfig.h
> +#define RT_USING_DFS_DEVFS
这个板子支持fatfs嘛 如果支持的话，请不要默认开启，
在board/Kconfig里的选项里 "Onboard Peripheral Drivers" 增加：https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f469-st-disco/board/Kconfig#L76

如果板子不支持fatfs，请关闭所有和dfs相关的东西。

其他板子也是同理

2023-05-25 05:33 UTC, IcyFeather233 commented on bsp/lpc178x/rtconfig.h
> +#define RT_USING_DFS_DEVFS
想问一下是这样吗：

1.板子支持 fatfs
不要默认开启 fatfs，具体做法如下：
在 board/Kconfig 里的选项里 "Onboard Peripheral Drivers" 增加：https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f469-st-disco/board/Kconfig#L76 中的这一段内容：

```
  config BSP_USING_SDCARD
      bool "Enable SDCARD (sdio)"
      select BSP_USING_SDIO
      select RT_USING_DFS
      select RT_USING_DFS_ELMFAT
      select RT_USING_PIN
      default n
```

比如说这个没有的话就新建这个目录和文件，以 lpc178x 为例，根本没有 board 目录，于是我需要先创建 board/Kconfig，然后 Kconfig 中填写以下内容：

```
menu "Hardware Drivers Config"

menu "Onboard Peripheral Drivers"
    config BSP_USING_SDCARD
        bool "Enable SDCARD (sdio)"
        select BSP_USING_SDIO
        select RT_USING_DFS
        select RT_USING_DFS_ELMFAT
        select RT_USING_PIN
        default n
```
然后在 bsp 目录中的 Kconfig 里面添加一条 source "board/Kconfig"


2.板子不支持 fatfs
关闭所有和 dfs 有关的东西，具体做法为把所有和 DFS 有关的宏删掉/注释掉

---

最后想请教一下，为什么不支持 fatfs 的话，就要把 dfs 有关的都关闭呢？我搜了一下，DFS是 RT-Thread 提供的虚拟文件系统组件，而 fatfs 是 dfs 支持的一种文件系统，还是不太明白为什么要这样做

2023-05-25 05:38 UTC, mysterywolf commented on bsp/lpc178x/rtconfig.h
> +#define RT_USING_DFS_DEVFS
1.
是的，您需要在仿照我给你的那个例子 创建一个board/Kconfig文件，塞进去。也别忘了在上一级的Kconfig里增加board/Kconfig的索引：https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f469-st-disco/Kconfig#L21

2. DFS不是必须组件，用户根据是否需要自行开启，我们不强迫用户一定非得使用文件系统。一般来说 RT-Thread的外设默认只开启GPIO和用于终端交互的串口。其他的都是用户需要的时候才会开启，我们可以在board/Kconfig里都为用户配置好，用户需要就一键化开启即可。

2023-05-25 05:39 UTC, mysterywolf commented on bsp/lpc178x/rtconfig.h
> +#define RT_USING_DFS_DEVFS
> 1.板子支持 fatfs

但是我并没有看到这个bsp有底层存储介质相关的驱动

2023-05-25 05:46 UTC, IcyFeather233 commented on bsp/lpc178x/rtconfig.h
> +#define RT_USING_DFS_DEVFS
> 这个一键化配置你可以看一下我给你发的BSP示例，board/Kconfig里都帮用户准备好了，但是default n，只有用户想用的时候才会开启。

想请教一下我是只用添加 menu "Onboard Peripheral Drivers" 中的 config BSP_USING_SDCARD 配置项，还是直接把整个示例中的 menu "Onboard Peripheral Drivers" 配置都添加上？

> 但是我并没有看到这个bsp有底层存储介质相关的驱动

还有就是想请教一下如何判断板子是否支持 fatfs 呢？我现在会的判断方法是 bing 搜索一下，就像这样：

![image](https://github.com/RT-Thread/rt-thread/assets/56245435/f8d68904-60b9-4145-b708-63b2e8bea13b)

如果有相关资料我就觉得应该是支持的，但是感觉这个方法不靠谱，还请赐教~

2023-05-25 05:58 UTC, mysterywolf commented on bsp/lpc178x/rtconfig.h
> +#define RT_USING_DFS_DEVFS
呕吼 支持的 我看走眼了 在这里有驱动：https://github.com/RT-Thread/rt-thread/blob/master/bsp/lpc176x/drivers/sd.c

2023-05-25 15:55 UTC, merged