Add files such as "Kconfig"、".config" to the bsp of lpc178x to surppo…
RT-Thread/rt-thread pull request #7556
Opened 2023-05-23 13:23 UTC by alteracd

…rt menuconfig

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
尝试给lpc178x的bsp添加Kconfig .config等文件，方便menuconfig 

#### 你的解决方案是什么 (what is your solution)
根据其他更新了menuconfig的bsp，添加Kconfig等文件，对比前后的rtconfig.h, 添加需要的额外宏配置，解决重定义的内容。
最后scons编译检验

#### 在什么测试环境下测试通过 (what is the test environment)
env1.3.5下  menuconfig正常可用，scons编译通过
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [√] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [√] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [√] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [√] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [√] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [√] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [√] 代码是高质量的 Code in this PR is of high quality
- [√] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-23 18:02 UTC, supperthomas commented
请问这个开发板你手上有吗？可以验证代码是否运行正常吗？

2023-05-24 02:01 UTC, alteracd commented
> 请问这个开发板你手上有吗？可以验证代码是否运行正常吗？因为看起来改了很多源代码结构
我手里没有这个开发板 修改Application下的两个文件是因为scons编译的时候报了重定义的问题 我检查了一下发现lpc系列的Application下还都是之前的startup.c的形式，个人感觉应该能直接使用空的main.c 但是手里没板子就只是把重定义的部分删除了，删除的两个部分是启动的函数 新版的RTthread已经将这些统一放到源码里去了

2023-05-24 02:02 UTC, alteracd commented
> 请问这个开发板你手上有吗？可以验证代码是否运行正常吗？因为看起来改了很多源代码结构
单纯添加Kconfig和 .config的话 scons编译是过不了的

2023-05-24 02:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7556) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7556) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: try1<br/>:x: alteracd<br/><hr/>**try1** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7556) it.</sub>

2023-05-24 02:11 UTC, supperthomas commented
额，不改可以过的。感谢PR， 这个后续可以关注这个PR：

https://github.com/RT-Thread/rt-thread/pull/7552

2023-05-24 04:01 UTC, Guozhanxin approved these changes

2023-05-24 04:14 UTC, supperthomas requested changes
这个有问题

2023-05-24 04:42 UTC, IcyFeather233 commented
可以看下我这篇分享：https://club.rt-thread.org/ask/article/f28fc6edf3877f4b.html，里面有你这个lpx178x编译不通过的解决方法

2023-05-24 07:28 UTC, alteracd commented
> 可以看下我这篇分享：https://club.rt-thread.org/ask/article/f28fc6edf3877f4b.html ，里面有你这个lpx178x编译不通过的解决方法
受教了

2023-05-24 08:30 UTC, supperthomas commented
> > 可以看下我这篇分享：https://club.rt-thread.org/ask/article/f28fc6edf3877f4b.html ，里面有你这个lpx178x编译不通过的解决方法
> > 受教了

其中缺少 config 的 bsp 至少还有：

others_at32_hc32 中的 mm32/mm32f3270-100ask-pitaya
mips 中的 loongson/ls1cdev

欢迎PR。

2023-05-24 10:44 UTC, closed without merging