[bsp] support menuconfig for lm4f232、rm48x50、mm32
RT-Thread/rt-thread pull request #7561
Opened 2023-05-24 13:56 UTC by alteracd

…f3270-100ask-pitaya to support menuconfig

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)

尝试给旧bsp添加Kconfig .config等文件，方便menuconfig

#### 你的解决方案是什么 (what is your solution)

给lm4f232、rm48x50、mm32f3270-100ask-pitaya的bsp添加Kconfig等文件，对比前后的rtconfig.h, 修改menuconfig

#### 在什么测试环境下测试通过 (what is the test environment)

env1.3.5下 menuconfig正常可用，scons编译通过

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [√] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [√] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [√] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [√] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [√] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [√] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [√] 代码是高质量的 Code in this PR is of high quality
- [√] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-24 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7561) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7561) before we can accept your contribution.<br/><hr/>**try1** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7561) it.</sub>

2023-05-25 01:55 UTC, supperthomas requested changes

2023-05-25 01:55 UTC, supperthomas commented on bsp/rm48x50/.config
rm48x50这个没办法验证正确性，建议先不改

2023-05-26 01:39 UTC, supperthomas commented
https://github.com/RT-Thread/rt-thread/issues/7530

2023-05-26 03:50 UTC, alteracd commented on bsp/rm48x50/.config
因为rm48x50被sam7x卡住了？
那rm48x50改回原来那个吗

2023-05-26 05:49 UTC, supperthomas commented on bsp/rm48x50/.config
嗯rm48x50， 这个action.yml里面没有，建议先不改，可以尝试把sam7x改下。

2023-05-29 02:16 UTC, supperthomas approved these changes

2023-05-29 02:17 UTC, supperthomas requested changes

2023-05-29 02:17 UTC, supperthomas commented on bsp/lm4f232/Kconfig
> +# you can change the RTT_ROOT default "../.." to your rtthread_root,
这里多余的东西请去掉。

2023-05-29 02:17 UTC, supperthomas approved these changes

2023-05-29 02:18 UTC, supperthomas commented
感谢PR

2023-05-29 05:59 UTC, mysterywolf approved these changes

2023-05-29 06:00 UTC, merged