[bsp][lpc55sxx]add: drv_lcd and drv_touch
RT-Thread/rt-thread pull request #7569
Opened 2023-05-26 10:27 UTC by Z8MAN8

1.update DMA CH of I2C1
2.add spi drv_lcd
3.add GT911 drv_touch
4.add drv_spi.h

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-29 04:19 UTC, mysterywolf requested changes

2023-05-29 04:19 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_gt911.h
> +    gt911_int_mode_t int_mode;
如非HAL库限制否则使用rt_uintxxx

2023-05-29 04:19 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_spi.h
> +#include "rtdevice.h"
这两个留<rtdevice.h> 就可以了 注意是尖括号

2023-05-29 04:19 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.h
> +void nxp_lcd_load(rt_uint16_t x_start, rt_uint16_t x_end, rt_uint16_t y_start, rt_uint16_t y_end, void *data);
这个名字改一下

2023-05-29 04:21 UTC, mysterywolf requested changes

2023-05-29 04:21 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +    if (st7796_lcd_display(lcd, 1) != RT_EOK) return -RT_ERROR;
这里直接返回该函数的错误码就可以了呀 没有必要统一成RT_ERROR

2023-05-29 04:21 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +    0x03, 0xB6, 0x8A, 0x07, 0x3B,                                // Display function control
rt-thread使用/**/注释

2023-05-29 04:21 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +    rt_uint16_t x_offset, y_offset;
```suggestion
    rt_uint16_t x_offset, y_offset;

```

2023-05-29 04:21 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +
这种无意义的空行可以删去，一般是变量声明和代码主题之间有空行就可以了

2023-05-29 04:21 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +    // Write inversion command.
/**/

2023-05-29 13:35 UTC, mysterywolf approved these changes

2023-05-29 13:47 UTC, supperthomas requested changes

2023-05-29 13:47 UTC, supperthomas commented on bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
> +    menuconfig BSP_USING_LCD
这个LCD外设有告诉用户如何使用和获取吗？或者型号吗？

2023-05-29 13:52 UTC, Z8MAN8 commented on bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
> +    menuconfig BSP_USING_LCD
显示芯片是st7796，触摸芯片是gt911，整体模块是NXP_LCDM_S

2023-05-29 14:06 UTC, supperthomas commented on bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
> +    menuconfig BSP_USING_LCD
可以在readme里面提供下驱动信息，和模块购买链接。

2023-05-29 14:58 UTC, supperthomas approved these changes

2023-05-29 16:44 UTC, mysterywolf commented on bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
> +    menuconfig BSP_USING_LCD
涛哥说的对  可以在readme里补充一下这个lcd模块的信息，例如官网资料，从哪里能搞到之类

2023-05-30 00:28 UTC, mysterywolf commented on bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
> +    menuconfig BSP_USING_LCD
nxp这个模块还没正式上架 后续补充readme

2023-05-30 00:32 UTC, mysterywolf requested changes

2023-05-30 00:32 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +        rt_kprintf("lcd init run failed! can't find %s device!\n", LCD_DEVICE_NAME);
rt_kprintf仅用于在终端命令行交互场景， 错误、警告、信息提示 使用LOG_E LOG_W LOG_I

https://github.com/RT-Thread/rt-thread/blob/master/components/libc/compilers/common/ctime.c#L126

2023-05-30 00:32 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +int drv_nxplcd_init(void)
```suggestion
int drv_st7796_init(void)
```

2023-05-30 00:32 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/sample/lcd_sample.c
> +#include <rtdevice.h>
```suggestion
#include <rtdevice.h>
```

2023-05-30 00:33 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/SConscript
>  path =  [cwd,cwd + '/config']
这个目录下有config文件夹嘛？

2023-05-30 02:20 UTC, Z8MAN8 commented on bsp/lpc55sxx/Libraries/drivers/SConscript
>  path =  [cwd,cwd + '/config']
没有，我直接去掉吗

2023-05-30 03:08 UTC, mysterywolf requested changes

2023-05-30 03:08 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.h
> +#define LCD_DEVICE_NAME  "spi_lcd"
```suggestion
#define LCD_DEVICE_NAME  "st7796"
```

2023-05-30 03:08 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.h
> +#include <rtdevice.h>
以此类推 多处需要修改
```suggestion
#include <rtdevice.h>
```

2023-05-30 03:08 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_st7796.c
> +INIT_ENV_EXPORT(drv_st7796_init);
```suggestion
}
INIT_ENV_EXPORT(drv_st7796_init);

```

2023-05-30 03:08 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_spi.h
> +
```suggestion

```

2023-05-30 03:08 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/drv_gt911.c
> +
```suggestion
}
INIT_COMPONENT_EXPORT(drv_capt_hw_init);

```

2023-05-30 16:39 UTC, mysterywolf requested changes

2023-05-30 19:33 UTC, mysterywolf requested changes

2023-05-30 19:33 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/sample/lcd_touch_sample.c
> +        for (uint8_t i = 0; i < ctp_input.num_pos; i++)
这个位置再举一反三检查一下
```suggestion
        for (rt_uint8_t i = 0; i < ctp_input.num_pos; i++)
```

2023-05-30 19:33 UTC, mysterywolf commented on bsp/lpc55sxx/Libraries/drivers/sample/lcd_touch_sample.c
> +    static rt_uint16_t white[319*2];
这块很危险，很容易把栈搞炸了 可以改成rt_malloc分配
一般栈数据大于32个字节就要小心了

2023-05-31 03:13 UTC, mysterywolf approved these changes

2023-05-31 03:40 UTC, merged