[ctime]解决clock_gettime计算出来的nsec超过1sec的问题
RT-Thread/rt-thread pull request #7588
Opened 2023-05-31 08:37 UTC by guoguozi123456

## 拉取/合并请求描述：(PR description)

[
解决clock_gettime计算出来的nsec超过1sec的问题

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-05-31 21:52 UTC, mysterywolf requested changes

2023-05-31 21:52 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +            }
这个应该放在 rt_hw_interrupt_enable(level); 之前吧

2023-06-01 01:18 UTC, guoguozi123456 commented on components/libc/compilers/common/ctime.c
> +            }
是的，原来是怕把中断关太久影响性能，但是放后面确实导致时间不准了，已进行修改

2023-06-01 01:35 UTC, mysterywolf requested changes

2023-06-01 01:35 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +                tp->tv_nsec %= 1000000000;
```suggestion
                tp->tv_nsec %= 1000000000ULL;
```

2023-06-01 01:35 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +            if(tp->tv_nsec>1000000000)
```suggestion
            if(tp->tv_nsec > 1000000000ULL)
```

2023-06-01 01:35 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
>              tp->tv_nsec = (_timevalue.tv_usec + (tick % RT_TICK_PER_SECOND) * MICROSECOND_PER_TICK) * 1000;
```suggestion
            tp->tv_nsec = (_timevalue.tv_usec + (tick % RT_TICK_PER_SECOND) * MICROSECOND_PER_TICK) * 1000U;
```

2023-06-01 01:44 UTC, aozima commented on components/libc/compilers/common/ctime.c
> +            }
这里参与运算的tv_nsec和tv_sec，在开中断前，已确定其值了，所以放在前面还是后面，结果都是一样的吧？

而且放在开中断后可能更好些？因为这类之前锁中断的操作，以后可能也要尽量逐步优化成原子访问，以减少关中断（虽然不支持原子访问的平台也是关中断）

2023-06-01 01:51 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +            }
老吴说的对 最近太累了 不适合review PR了😅

2023-06-01 01:53 UTC, mysterywolf requested changes

2023-06-01 01:53 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
>              rt_hw_interrupt_enable(level);
```suggestion
            rt_hw_interrupt_enable(level);
            if(tp->tv_nsec > 1000000000ULL)
            {
                tp->tv_nsec %= 1000000000ULL;
                tp->tv_sec += 1;
            }
```

2023-06-01 01:54 UTC, mysterywolf approved these changes

2023-06-01 01:55 UTC, supperthomas approved these changes

2023-06-01 01:55 UTC, mysterywolf approved these changes

2023-06-01 01:55 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +            if(tp->tv_nsec > 1000000000ULL)
```suggestion
            if (tp->tv_nsec > 1000000000ULL)
```

2023-06-01 02:52 UTC, merged