增加变量 mask 提高效率
RT-Thread/rt-thread pull request #7597
Opened 2023-06-03 03:25 UTC by winfenggao

## 拉取/合并请求描述：(PR description)

[
增加一个变量mask，不用每收到一个字节都调用stm32_uart_get_mask函数，mask在每次设置串口后调用stm32_uart_get_mask计算。
STM32H750VBT6用finseh测试通过8n1；（其他格式如8e1等没测试）
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [*] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-03 06:01 UTC, mysterywolf commented
这个前后有什么速度上的提升数据嘛？

2023-06-03 07:16 UTC, winfenggao commented
> 这个前后有什么速度上的提升数据嘛？
原stm32_getc中，每读取一个字节都要调用stm32_uart_get_mask函数获取掩码，然后载“与”读取到的串口接收数据寄存器的数据；
修改后，直接“与”一个变量，避免频繁调用stm32_uart_get_mask函数；效率当然提高了。

2023-06-03 15:46 UTC, mysterywolf commented
我的意思是有没有实际数据支撑提高了多少，而不是理论上提高。我理解理论上会有提高的。

2023-06-03 18:02 UTC, supperthomas approved these changes
感谢PR，这里感觉确实有一些性能提升

2023-06-04 02:01 UTC, winfenggao commented
STM32H750 @240M usart2 ，115200，8n1
引脚电平测试函数执行时间，示波器设定上升沿捕捉脉冲：
修改前每个字节函数执行时间（不包含RT_ASSERT）590ns，修改后执行时间364ns；

static int stm32_getc(struct rt_serial_device *serial)
{
    int ch;
    struct stm32_uart *uart;
    RT_ASSERT(serial != RT_NULL);
    
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_2, GPIO_PIN_SET); 
    
    uart = rt_container_of(serial, struct stm32_uart, serial);
    
    ch = -1;
    if (__HAL_UART_GET_FLAG(&(uart->handle), UART_FLAG_RXNE) != RESET)
    {
#if defined(SOC_SERIES_STM32L4) || defined(SOC_SERIES_STM32WL) || defined(SOC_SERIES_STM32F7) || defined(SOC_SERIES_STM32F0) \
    || defined(SOC_SERIES_STM32L0) || defined(SOC_SERIES_STM32G0) || defined(SOC_SERIES_STM32H7) || defined(SOC_SERIES_STM32L5) \
    || defined(SOC_SERIES_STM32G4) || defined(SOC_SERIES_STM32MP1) || defined(SOC_SERIES_STM32WB)|| defined(SOC_SERIES_STM32F3) \
    || defined(SOC_SERIES_STM32U5)
        ch = uart->handle.Instance->RDR & uart->mask;//stm32_uart_get_mask(uart->handle.Init.WordLength, uart->handle.Init.Parity);
#else
        ch = uart->handle.Instance->DR & uart->mask);
#endif
    }
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_2, GPIO_PIN_RESET); 
    return ch;
}

2023-06-04 03:09 UTC, mysterywolf approved these changes

2023-06-04 03:09 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_usart.h
> +    rt_uint32_t mask;
```suggestion
    rt_uint32_t DR_mask;
```

2023-06-04 03:09 UTC, mysterywolf approved these changes

2023-06-04 03:10 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drv_usart.h
> +    rt_uint32_t mask;
建议改成DR_mask, 后面维护的时候可以清晰知道这个mask在mask谁

2023-06-04 03:15 UTC, mysterywolf requested changes
RT-Thread BSP build check / stm32_f2_f4 (pull_request) 

stm32的CI没有编过

2023-06-04 03:41 UTC, winfenggao commented on bsp/stm32/libraries/HAL_Drivers/drv_usart.h
> +    rt_uint32_t mask;
同意，就是DR是大写的，整个结构体其他变量都是小写；不过从mask是用于外设寄存器的角度解释也能接受。

2023-06-04 05:12 UTC, winfenggao commented on bsp/stm32/libraries/HAL_Drivers/drv_usart.h
> +    rt_uint32_t mask;
改成DR_mask了

2023-06-04 17:45 UTC, mysterywolf commented
你好 请确认一下你的这个修改是否能在其他stm32上跑起来，CI显示在F2 F4系列的芯片上编译不通过

2023-06-04 23:27 UTC, winfenggao commented
> 你好 请确认一下你的这个修改是否能在其他stm32上跑起来，CI显示在F2 F4系列的芯片上编译不通过

STM32 Done

2023-06-04 23:28 UTC, mysterywolf approved these changes

2023-06-06 02:03 UTC, winfenggao commented
就剩一项check 错误了，这个应该和我的改动无关了吧
AutoTestCI / kernel/atomic

2023-06-06 02:03 UTC, mysterywolf commented
恩是的 请无视这个错误

2023-06-06 04:18 UTC, merged