STM32F334 NUCLEO BSP
RT-Thread/rt-thread pull request #7600
Opened 2023-06-03 20:47 UTC by tangzz98

## 拉取/合并请求描述：(PR description)

[
为rt-thread添加stm32F334 NUCLEO开发板的BSP
在开发板上通过测试
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-04 17:43 UTC, mysterywolf commented
你好，感谢提交PR，可否仿照其他stm32bsp 提交一份readme上来？谢谢！

2023-06-04 21:53 UTC, tangzz98 commented
> 你好，感谢提交PR，可否仿照其他stm32bsp 提交一份readme上来？谢谢！
已经提交了 [readme](https://github.com/RT-Thread/rt-thread/blob/54d6bf1882514df131f46e1a65bc5da70abe2390/bsp/stm32/stm32f334-st-nucleo/README.md)

2023-06-04 22:02 UTC, mysterywolf approved these changes

2023-06-05 04:42 UTC, supperthomas requested changes

2023-06-05 04:42 UTC, supperthomas commented on bsp/stm32/stm32f334-st-nucleo/.project
> +	</projects>
看下需不需要。

2023-06-05 04:42 UTC, supperthomas commented on bsp/stm32/stm32f334-st-nucleo/board/board.c
> + * 2018-11-06     SummerGift   first version
改下备注

2023-06-05 04:42 UTC, supperthomas commented on bsp/stm32/stm32f334-st-nucleo/board/board.h
> + * 2018-11-5      SummerGift   first version
这里改下

2023-06-05 04:42 UTC, supperthomas commented on bsp/stm32/stm32f334-st-nucleo/makefile.targets
> +	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
看下需不需要

2023-06-05 05:49 UTC, tangzz98 commented on bsp/stm32/stm32f334-st-nucleo/board/CubeMX_Config/.mxproject
> +[PreviousLibFiles]
这个好像是要的 https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/tutorial/make-bsp/stm32-bsp/STM32%E7%B3%BB%E5%88%97BSP%E5%88%B6%E4%BD%9C%E6%95%99%E7%A8%8B?id=_1-bsp-%e6%a1%86%e6%9e%b6%e4%bb%8b%e7%bb%8d:~:text=%E6%9C%80%E7%BB%88%20CubeMX%20%E7%94%9F%E6%88%90%E7%9A%84%E5%B7%A5%E7%A8%8B%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E5%A6%82%E4%B8%8B%E5%9B%BE%E6%89%80%E7%A4%BA%EF%BC%9A

2023-06-05 05:50 UTC, supperthomas commented on bsp/stm32/stm32f334-st-nucleo/board/CubeMX_Config/.mxproject
> +[PreviousLibFiles]
好的，这个保留

2023-06-05 05:56 UTC, supperthomas approved these changes

2023-06-05 05:57 UTC, mysterywolf commented
已经解决掉的请点一下resolve conversation @tangzz98

2023-06-06 01:22 UTC, merged