[simulator] 修复 linux simulator 编译运行失败
RT-Thread/rt-thread pull request #7609
Opened 2023-06-05 02:16 UTC by zhkag

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-05 03:43 UTC, mysterywolf requested changes

2023-06-05 03:43 UTC, mysterywolf commented on bsp/simulator/rtconfig.py
> +    # CFLAGS += ' -Wall -g -O0 -fsanitize=address -fsanitize-recover=address,all -fno-omit-frame-pointer -fsanitize=leak -fsanitize=undefined -fdiagnostics-color'
这个是否也应该加上' # open this when build 64bit target

2023-06-05 03:43 UTC, mysterywolf commented on components/libc/compilers/common/include/sys/time.h
> +#endif
```suggestion
#endif /* defined(_GNU_SOURCE) && !defined(RT_USING_SMART) */
```

2023-06-05 03:43 UTC, mysterywolf commented on bsp/simulator/rtconfig.h
> -#define RT_USING_POSIX_SOCKET
这三个别关，虽然目前没啥用，但是用于检查libc配平层对此平台的兼容能力的

2023-06-05 03:43 UTC, mysterywolf commented on bsp/simulator/rtconfig.py
> +CROSS_TOOL='gcc'
默认还是windows吧

或者这个可以自动做个判断，检查一下当前python的运行环境是windows还是linux?

2023-06-05 22:12 UTC, mysterywolf requested changes

2023-06-05 22:12 UTC, mysterywolf commented on bsp/simulator/rtconfig.h
> -#define BSP_USING_RTC
RTC默认开启吧

2023-06-05 22:12 UTC, mysterywolf commented on bsp/simulator/rtconfig.py
> +    # CFLAGS += ' -Wall -g -O0 -fsanitize=address -fsanitize-recover=address,all -fno-omit-frame-pointer -fsanitize=leak -fsanitize=undefined -fdiagnostics-color'
这个麻烦给个注释

2023-06-07 03:39 UTC, mysterywolf approved these changes

2023-06-07 06:38 UTC, Guozhanxin approved these changes

2023-06-07 12:52 UTC, merged

2023-06-07 21:09 UTC, mysterywolf commented
@Guozhanxin 这个可否放在CI里守护起来？