【新增】LPC4088在IAR环境的支持
RT-Thread/rt-thread pull request #7611
Opened 2023-06-05 06:51 UTC by meng-plus

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

解决完善 RTT对LPC4088版本的支持问题

#### 你的解决方案是什么 (what is your solution)

1. 清理掉project.*垃圾文件
2. rtconfig,py中增加IAR配置的支持，可以使用“scons --target=iar”配置IAR环境
3. 默认关闭DFS_USING_POSIX
4. 更新了汇编启动文件，使其更友好的 支持更高版本的IAR编译器，避免了warning[25]警告
5. template.ewp中，增加了若干默认配置
  6. c/c++ Compiler->Extra Options 增加--no_path_in_file_macros
  7. c/c++ Compiler->Diagnostics 增加Pa050,Pa082 屏蔽警告
  8. Linker->List增加 Generate linker map file
9. .config 中关闭了默认的POSIX支持
   Signed-off-by: meng-plus <[chengmeng_2@outlook.com](mailto:chengmeng_2@outlook.com)>

#### 在什么测试环境下测试通过 (what is the test environment)

IAR8_40.2中编译运行测试通过
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[[formatting](https://github.com/mysterywolf/formatting)](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md)](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [[RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-05 06:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7611) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7611) it.</sub>

2023-06-06 01:48 UTC, mysterywolf requested changes
为什么要将keil工程的文件删除呀

不需要删除的 更新一下Keil工程提交上来就好

2023-06-06 02:49 UTC, meng-plus commented
> 

那我不动keil部分了 不是我关心的部分

2023-06-06 03:19 UTC, supperthomas approved these changes

2023-06-06 03:35 UTC, mysterywolf approved these changes

2023-06-06 04:02 UTC, merged