[bsp][gd32]添加 GD32F303 的 pwm 驱动
RT-Thread/rt-thread pull request #7615
Opened 2023-06-05 15:28 UTC by zengjianwei

## 拉取/合并请求描述：(PR description)

[在使用 RT-Thread Studio 构建  GD32F303 项目的时候，发现没有 PWD 驱动，然后自己写了一个，并在实际项目上稳定使用了半年有余的时间，现在开源出来给其他有需要的人，免得大家重复造轮子]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-06 01:27 UTC, mysterywolf requested changes
也请修改一下和他同级的sconscript构建脚本

2023-06-06 01:27 UTC, mysterywolf commented on bsp/gd32/arm/libraries/gd32_drivers/drv_pwm.c
> + * 2022-07-15     zengjianwei         	first version
这个改成你的名字和正确的日期，first version和Note对齐

2023-06-06 04:19 UTC, mysterywolf commented
不需要关闭此PR，只需要继续提交commit push即可，如果不会，后续我们来处理也可以

2023-06-06 17:05 UTC, mysterywolf approved these changes

2023-06-06 17:10 UTC, mysterywolf commented
感谢提交PR！

2023-06-07 01:01 UTC, supperthomas approved these changes

2023-06-07 01:06 UTC, merged

2023-06-07 01:06 UTC, mysterywolf commented
感谢提交PR！

2023-06-07 01:24 UTC, mysterywolf commented
你好，请往我的邮箱里随便发些什么 我拉你进gd32的群 meco@rt-thread.org