[bsp][essemi]es32vf2264更新部分库函数和驱动，添加RTduino支持
RT-Thread/rt-thread pull request #7619
Opened 2023-06-06 05:08 UTC by a876565

## 拉取/合并请求描述：(PR description)

[
ESSEMI BSP ES32VF2264更新
1. 更新驱动和库函数修复部分bug，完善c++支持
2. 为该BSP添加RTduino支持和测试例程

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-06 17:37 UTC, mysterywolf requested changes

2023-06-06 17:37 UTC, mysterywolf commented on bsp/essemi/es32vf2264/applications/arduino_pinout/pins_arduino.c
> +    {D28, GET_PIN(B,12)},        /* GPIO/SPI1_NSS */
需要将D放在A的上面 不要把模拟插在数字引脚中间，否则索引会出问题

2023-06-06 17:37 UTC, mysterywolf commented on bsp/essemi/es32vf2264/applications/SConscript
> +Return('group')
```suggestion
Return('group')

```

2023-06-06 17:37 UTC, mysterywolf commented on bsp/essemi/es32vf2264/applications/arduino_pinout/pins_arduino.h
> +#define A5   (30)
貌似没有这么多模拟引脚只到A1

2023-06-06 17:37 UTC, mysterywolf commented on bsp/essemi/es32vf2264/drivers/SConscript
> +CCFLAGS='-fno-exceptions'
https://github.com/RTduino/RTduino/blob/master/core/SConscript#LL16C30-L16C30

这块在rtduino里已经支持了

2023-06-06 17:37 UTC, mysterywolf commented on bsp/essemi/es32vf2264/applications/arduino_pinout/README.md
> +若使用RTTI(运行时类型识别)，会需要额外的stdc++库支持，需要在CDK的Linker页面中，在Library Name中添加"stdc++"，可通过在编译参数中加入-fno-rtti禁用，但由于CDK不区分C和C++的编译参数，会导致编译C文件时产生警告"warning: command-line option '-fno-rtti' is valid for C++/D/ObjC++
这块已经在rtduino上支持上了：https://github.com/RTduino/RTduino/blob/master/core/SConscript#LL16C30-L16C30

2023-06-07 05:48 UTC, a876565 commented on bsp/essemi/es32vf2264/applications/arduino_pinout/README.md
> +若使用RTTI(运行时类型识别)，会需要额外的stdc++库支持，需要在CDK的Linker页面中，在Library Name中添加"stdc++"，可通过在编译参数中加入-fno-rtti禁用，但由于CDK不区分C和C++的编译参数，会导致编译C文件时产生警告"warning: command-line option '-fno-rtti' is valid for C++/D/ObjC++
这一块的话因为CDK没有区分c++和c的编译参数，cdk的工程生成脚本没有处理CXXFLAGS，只处理了CCFLAGS，仅仅处理了c的选项，只有加在c的编译选项里的内容才能被识别。RTduino里加入的那部分编译参数实际上没有被加入到cdk的编译参数里，因此在这里用这种方式添加了这个参数。

2023-06-07 05:51 UTC, a876565 commented on bsp/essemi/es32vf2264/applications/arduino_pinout/pins_arduino.h
> +#define ARCH_RISCV
目前的编译器和SDK似乎都没有这个宏，在这里补充一下

2023-06-08 04:08 UTC, mysterywolf commented on bsp/essemi/es32vf2264/applications/arduino_pinout/pins_arduino.h
> +#define ARCH_RISCV
这个宏不是rtduino一级需要支持的，应该是rt-thread来支持的，应该在这里select 对应的CPU架构宏
https://github.com/a876565/rt-thread/blob/es32vf2264_rtduino/bsp/essemi/es32vf2264/Kconfig#L23
https://github.com/RT-Thread/rt-thread/blob/master/libcpu/Kconfig
这几个BSP都需要补充一下。

2023-06-08 06:11 UTC, mysterywolf approved these changes

2023-06-08 06:13 UTC, merged