为c++增加 rt-thread 多线程支持的子开关
RT-Thread/rt-thread pull request #7660
Opened 2023-06-12 06:35 UTC by yangjie11

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-12 12:01 UTC, BernardXiong commented on components/libc/cplusplus/SConscript
> +    src = Glob('*.cpp') + Glob('*.c')
如果没定义 `RT_USING_CPP_MULTITHREAD`，那么基本上这个cplusplus下所有的特性都没了？

2023-06-14 02:42 UTC, mysterywolf requested changes
https://github.com/RTduino/RTduino/blob/master/core/SConscript#L16

把这一行放进来，可以有效减低开启C++的资源开销

2023-06-14 02:42 UTC, mysterywolf commented on components/libc/cplusplus/Kconfig
> +        bool "Enable RT-Thread C++ thread feature support"
```suggestion
        bool "Enable RT-Thread C++ multi-threads feature support"
```

2023-06-14 02:42 UTC, mysterywolf commented on components/libc/cplusplus/SConscript
> +''')
```suggestion
src     = ['cxx_crt_init.c']
```

2023-06-14 02:46 UTC, mysterywolf commented
我来改吧。

2023-06-14 04:05 UTC, mysterywolf approved these changes
RTduino下编译通过

2023-06-14 05:31 UTC, Guozhanxin approved these changes

2023-06-14 05:32 UTC, Guozhanxin approved these changes

2023-06-14 05:32 UTC, Guozhanxin commented on bsp/k210/drivers/SConscript
> +group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=['NNCASE_NO_EXCEPTIONS'])
这个是啥，怎么在这个pr里

2023-06-14 12:49 UTC, mysterywolf commented on bsp/k210/drivers/SConscript
> +group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=['NNCASE_NO_EXCEPTIONS'])
不使用c++ exception 降低资源开销

2023-06-14 12:49 UTC, merged