enable art-pi spi flash use elmfatfs
RT-Thread/rt-thread pull request #7690
Opened 2023-06-16 09:56 UTC by IcyFeather233

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

为 ART-PI 开发板添加如下功能：ART-Pi 外部 SPI Flash 使用 elmfatfs 文件系统

#### 你的解决方案是什么 (what is your solution)

原代码是先用 romfs 文件系统挂 /flash 和 /sdcard 两个目录，然后再用 littlefs 系统挂 flash 到 /flash下面

我想这样改：通过 RT_USING_DFS_ROMFS 和 RT_USING_DFS_ELMFAT 控制代码，如果开了elmfat，则会使 ART-Pi 外部 SPI Flash 使用 elmfatfs 文件系统，反之则功能和原代码相同，不影响原功能

修改后代码食用指南：

开启 DFS 以及 elmfatfs 文件系统，并将扇区改成 4096 （artpi 的板载外部 spi flash 的 sector 大小就是4096）。

![image](https://github.com/RT-Thread/rt-thread/assets/56245435/e572eec3-26bf-4aa8-b9ee-cd3c9a20a953)

开启 SPI Flash filesystem：

![image](https://github.com/RT-Thread/rt-thread/assets/56245435/23e3e1fe-14f5-4dff-b09d-d936154e2d62)

然后保存编译下载，即成功让外部 SPI Flash 使用 elmfatfs 文件系统：

![image](https://github.com/RT-Thread/rt-thread/assets/56245435/f845100a-6d70-40d4-8009-5b78b9a390bc)

#### 在什么测试环境下测试通过 (what is the test environment)
RT-Thread Version: latest
RT-Thread Env Version: 1.3.5
OS: Windows 10
IDE: Keil5

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-17 01:24 UTC, mysterywolf commented
spi flash 不适合用fat文件系统 更适合用littlefs

2023-06-17 01:32 UTC, IcyFeather233 commented
啊(T＿T)为什么不适合呢 请赐教

2023-06-17 01:33 UTC, mysterywolf commented
虽然不合适 但是放进来作为一个小demo是没问题的😁

2023-06-17 01:34 UTC, mysterywolf requested changes

2023-06-17 01:34 UTC, mysterywolf commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> -        select RT_USING_DFS_ROMFS
这个ROMFS为啥移除了呀 这个是根文件系统

2023-06-17 05:21 UTC, IcyFeather233 commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> -        select RT_USING_DFS_ROMFS
开了ROMFS似乎就没法挂载，[参考文章链接](https://blog.csdn.net/tcjy1000/article/details/123887126)
![image](https://github.com/RT-Thread/rt-thread/assets/56245435/883b17b8-bced-4c56-bcda-43d60f82d395)
如果不修改这个地方 但是把这个elmfs的demo加进来，要怎么修改比较好呢？

2023-06-19 02:58 UTC, Guozhanxin commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> -        select RT_USING_DFS_ROMFS
可以改挂载的路径
```
dfs_mount(flash_dev->parent.name, "/", "elm", 0, 0) 
```

2023-11-22 08:13 UTC, mysterywolf approved these changes

2023-11-22 08:19 UTC, Guozhanxin approved these changes

2023-11-22 08:19 UTC, merged