[bsp] Add more Kconfig configuration support for stm32l496-st-nucleo
RT-Thread/rt-thread pull request #7696
Opened 2023-06-18 09:03 UTC by dejavudwh

## 拉取/合并请求描述：(PR description)

为 stm32l496-st-nucleo 添加更多 Kconfig 配置的支持

#### 为什么提交这份PR (why to submit this PR)

#7530

#### 你的解决方案是什么 (what is your solution)

添加相应的Kconfig以及通过 CubeMX 生成一些必须的初始化配置，并且修改编译错误

#### 在什么测试环境下测试通过 (what is the test environment)

Scons 编译通过

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-18 12:57 UTC, supperthomas requested changes

2023-06-18 12:57 UTC, supperthomas commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_common.h
> + * Date           Author       Notes
? 怎么会改到这里？

2023-06-18 12:59 UTC, supperthomas requested changes

2023-06-18 12:59 UTC, supperthomas commented on bsp/stm32/stm32l496-st-nucleo/board/mnt.c
> - * 2022-06-08     supperthomas first version
这里为什么要删除呢？

2023-06-18 13:00 UTC, supperthomas requested changes

2023-06-18 13:00 UTC, supperthomas commented on bsp/stm32/stm32l496-st-nucleo/board/CubeMX_Config/Src/main.c
> +  ******************************************************************************
这个文件需要添加吗？

2023-06-18 13:00 UTC, supperthomas commented on bsp/stm32/stm32l496-st-nucleo/board/CubeMX_Config/Src/stm32l4xx_hal_timebase_tim.c
> +  * All rights reserved.</center></h2>
这个文件会编译进去吗？

2023-06-18 13:27 UTC, supperthomas approved these changes

2023-06-18 13:27 UTC, supperthomas commented on bsp/stm32/stm32l496-st-nucleo/.config
> +CONFIG_RT_USING_DFS=y
.config 保留默认配置

2023-06-18 13:28 UTC, supperthomas requested changes

2023-06-18 13:28 UTC, supperthomas commented on bsp/stm32/stm32l496-st-nucleo/board/CubeMX_Config/Src/stm32l4xx_it.c
> +/*           Cortex-M4 Processor Interruption and Exception Handlers          */
这里改动非必要不需要提交。

2023-06-18 16:12 UTC, mysterywolf requested changes

2023-06-18 16:12 UTC, mysterywolf commented on bsp/stm32/stm32l496-st-nucleo/board/Kconfig
> +            BSP_USING_SDIO use drv_sdio.c
这块我觉得可否将这个软件包并入到主仓stm32的驱动library里呀，stm32的sdio相关驱动为啥会被拆成一个软件包😂。参考一下stm32f407探索者的bsp是怎么写的sdio这块。感觉有些怪。要不 这个先去掉，下个PR单独提？

2023-06-18 22:28 UTC, supperthomas approved these changes

2023-06-19 02:04 UTC, dejavudwh commented on bsp/stm32/stm32l496-st-nucleo/board/Kconfig
> +            BSP_USING_SDIO use drv_sdio.c
好的

2023-06-19 02:05 UTC, mysterywolf commented on bsp/stm32/stm32l496-st-nucleo/board/Kconfig
> +            BSP_USING_SDIO use drv_sdio.c
把这个去掉 然后等这个PR合并之后单独提一个Draf，可能不会被合并，需要和郭老师讨论一下。 顺便看看这个软件包是否可以并入到stm32的 library 驱动里

2023-06-19 06:35 UTC, dejavudwh commented on bsp/stm32/stm32l496-st-nucleo/board/Kconfig
> +            BSP_USING_SDIO use drv_sdio.c
好的

2023-06-19 06:35 UTC, dejavudwh commented on bsp/stm32/stm32l496-st-nucleo/board/Kconfig
> +            BSP_USING_SDIO use drv_sdio.c
谢谢满老师

2023-06-19 13:41 UTC, mysterywolf approved these changes

2023-06-19 13:42 UTC, merged