[kernel]add api rt_hw_interrupt_is_disabled
RT-Thread/rt-thread pull request #7706
Opened 2023-06-20 08:42 UTC by Guozhanxin

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-20 10:21 UTC, aozima commented on bsp/stm32/stm32f103-dofly-lyc8/rtconfig.py
> +# BUILD = 'debug'
这个好像和本次没关系？

2023-06-20 17:25 UTC, mysterywolf requested changes

2023-06-20 17:25 UTC, mysterywolf commented on include/rthw.h
>  #endif /*RT_USING_SMP*/
这俩没有必要写两遍吧

2023-06-21 02:53 UTC, Guozhanxin commented on bsp/stm32/stm32f103-dofly-lyc8/rtconfig.py
> +# BUILD = 'debug'
不改，ci过不了。。。

2023-06-21 02:54 UTC, Guozhanxin commented on include/rthw.h
>  #endif /*RT_USING_SMP*/
写到SMP宏外面也怪怪的

2023-06-21 02:59 UTC, mysterywolf commented on bsp/stm32/stm32f103-dofly-lyc8/rtconfig.py
> +# BUILD = 'debug'
不能为了ci过而ci过呀 为啥debug就过不了呀

2023-06-21 03:25 UTC, supperthomas commented on bsp/stm32/stm32f103-dofly-lyc8/rtconfig.py
> +# BUILD = 'debug'
code size 超了吧？

2023-06-21 06:51 UTC, Guozhanxin commented on bsp/stm32/stm32f103-dofly-lyc8/rtconfig.py
> +# BUILD = 'debug'
是的

2023-06-21 07:17 UTC, supperthomas approved these changes

2023-06-21 13:44 UTC, mysterywolf approved these changes

2023-06-21 13:47 UTC, armink commented
下次还会有个 PR 把 ARM-Cortex M 系列的 rt_hw_interrupt_is_disabled 都实现一遍吗？

2023-06-21 14:42 UTC, merged