add:同步lib修改,包括sram加锁、修复获取rtc频率错误等
RT-Thread/rt-thread pull request #7718
Opened 2023-06-25 03:16 UTC by Dozingfiretruck

## 拉取/合并请求描述：(PR description)

[
add:同步lib修改,包括sram加锁、修复获取rtc频率错误等
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-25 03:18 UTC, mysterywolf approved these changes

2023-06-25 04:30 UTC, mysterywolf requested changes

2023-06-25 04:30 UTC, mysterywolf commented on bsp/airm2m/air32f103/libraries/AIR32F10xLib/src/air32f10x_flash.c
> +  *         - For other devices, it clears Bank1�s pending flags.
此处有乱码

2023-06-25 04:30 UTC, mysterywolf commented on bsp/airm2m/air32f103/libraries/Startup/arm/startup_air32f10x.s
> +				LDR R2,=0x400210F0
此处格式有问题

2023-06-26 10:21 UTC, Dozingfiretruck commented on bsp/airm2m/air32f103/libraries/Startup/arm/startup_air32f10x.s
> +				LDR R2,=0x400210F0
此处格式有什么问题？

2023-06-26 10:26 UTC, Dozingfiretruck commented on bsp/airm2m/air32f103/libraries/AIR32F10xLib/src/air32f10x_flash.c
> +  *         - For other devices, it clears Bank1�s pending flags.
已修复

2023-06-26 23:20 UTC, mysterywolf commented on bsp/airm2m/air32f103/libraries/Startup/arm/startup_air32f10x.s
> +				LDR R2,=0x400210F0
不使用tab 用4空格代替

2023-06-27 02:11 UTC, mysterywolf approved these changes

2023-06-27 02:11 UTC, Dozingfiretruck commented on bsp/airm2m/air32f103/libraries/Startup/arm/startup_air32f10x.s
> +				LDR R2,=0x400210F0
确实，formatting没格式化这部分，已经改了

2023-06-27 02:15 UTC, supperthomas approved these changes

2023-06-27 02:42 UTC, merged