[CI][bsp] Added CI to compile more drivers for the changed BSP
RT-Thread/rt-thread pull request #7738
Opened 2023-06-27 10:54 UTC by dejavudwh

## 拉取/合并请求描述：(PR description)

#### 为什么提交这份PR (why to submit this PR)

原先 CI 编译 BSP 都是根据默认的 Kconfig (rtconfig.h)，无法对更多驱动的编译进行测试

#### 你的解决方案是什么 (what is your solution)

1. 查看当前 PR 修改到的 BSP
2. 根据该 BSP 当前外设驱动的支持情况（Kconfig/.config），直接修改rtconfig.h，然后重新编译

#### 在什么测试环境下测试通过 (what is the test environment)

[CI 测试](https://github.com/dejavudwh/rt-thread/actions/runs/5388857781/jobs/9782043321)

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-06-27 10:59 UTC, dejavudwh commented
@supperthomas

2023-06-27 22:44 UTC, mysterywolf requested changes

2023-06-27 22:44 UTC, mysterywolf commented on bsp/stm32/stm32l496-st-nucleo/board/board.c
> +
这里多余空行请删掉，只保留一行空行即可

2023-06-27 22:44 UTC, mysterywolf commented on bsp/stm32/stm32l475-atk-pandora/board/board.c
> +
删除更改

2023-06-27 22:47 UTC, mysterywolf commented
@supperthomas 请不要随意替提交PR者修改PR内容，除非确认后续他将不会更改。替他修改内容，在对方不知情的情况下，他本地继续修改push commit会导致push不上去。除非提醒PR提交者 需要先pull一下 (而且有可能还会和提交PR者本地的修改形成冲突)。

2023-06-27 23:55 UTC, supperthomas commented on bsp/stm32/stm32l496-st-nucleo/board/board.c
> +
CI 测试

2023-06-27 23:55 UTC, supperthomas commented on bsp/stm32/stm32l475-atk-pandora/board/board.c
> +
ci 测试

2023-06-27 23:56 UTC, supperthomas commented
> @supperthomas 请不要随意替提交PR者修改PR内容，除非确认后续他将不会更改。替他修改内容，在对方不知情的情况下，他本地继续修改push commit会导致push不上去。除非提醒PR提交者 需要先pull一下 (而且有可能还会和提交PR者本地的修改形成冲突)。

CI 测试

2023-06-27 23:56 UTC, supperthomas commented
其他内容有问题吗？ @mysterywolf

2023-06-27 23:57 UTC, mysterywolf commented
其他内容没有问题

2023-06-28 00:05 UTC, supperthomas requested changes

2023-06-28 00:05 UTC, supperthomas commented on bsp/stm32/stm32l496-st-nucleo/board/board.c
> +
@dejavudwh 空格删了

2023-06-29 01:19 UTC, supperthomas approved these changes

2023-06-29 01:30 UTC, mysterywolf commented
请移除对bsp文件的修改，这两处修改无明显意义

2023-06-29 02:06 UTC, mysterywolf approved these changes

2023-06-29 02:07 UTC, merged

2023-06-29 02:27 UTC, supperthomas commented
感谢PR， 后续官方可以关注CI 情况， https://github.com/RT-Thread/rt-thread/actions/workflows/compile_bsp_with_drivers.yml