B u585i iot
RT-Thread/rt-thread pull request #7778
Opened 2023-07-04 13:57 UTC by Zheng-Bicheng

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
为`B-U585I-IOT02A`板卡添加第一阶段的BSP

#### 你的解决方案是什么 (what is your solution)
`B-U585I-IOT02A`芯片为STM32U585AIIxQ，与`stm32u575-st-nucleo`板卡接近，因此参考`stm32u575-st-nucleo`对`B-U585I-IOT02A`板卡的BSP进行了实现

#### 在什么测试环境下测试通过 (what is the test environment)
`B-U585I-IOT02A`板卡
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-04 13:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7778) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7778) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7778) it.</sub>

2023-07-04 14:01 UTC, Zheng-Bicheng commented
目前代码已经跑通，但是仍然有一个奇怪的问题还没有解决：

`bsp/stm32/stm32u585-b-u585i-iot02a/board/Kconfig`中，我只开启了GPIO和USRT，但是在生成的`rtconfig.h`文件中却多了一些外设，比如ADC、PWM、SPI，我要如何解决这个问题。

2023-07-05 02:49 UTC, supperthomas requested changes

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/EventRecorderStub.scvd
> +
这个文件他bsp没有，应该没有用，建议删除

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/applications/main.c
> + * 2018-11-06     SummerGift   first version
请修改license， 新加文件，要修改license署名为自己。

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/applications/arduino_main.cpp
> + * 2023-04-13     songw4232    first version
license

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/applications/arduino_pinout/pins_arduino.c
> + * 2023-04-13     songw4232    first version
license

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/applications/arduino_pinout/pins_arduino.h
> + * 2023-04-13     songw4232    first version
license

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/board/board.c
> + * 2018-11-06     SummerGift   first version
license

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/board/board.h
> + * 2019-04-24     yangjie      Use the end of ZI as HEAP_BEGIN
license

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/board/ports/drv_key.c
> +
这个文件有用到吗？如果没用到建议删除。

2023-07-05 02:49 UTC, supperthomas commented on bsp/stm32/stm32u585-b-u585i-iot02a/board/ports/drv_spi_flash.c
> +    }
这个文件有用到吗？没有用到建议删除

2023-07-08 13:34 UTC, supperthomas approved these changes

2023-07-09 16:21 UTC, mysterywolf requested changes

2023-07-09 16:21 UTC, mysterywolf commented on bsp/stm32/stm32u585-b-u585i-iot02a/rtconfig.h
> +#define RT_USING_SPI
请移除掉I2C ADC PWM和SPI的宏

2023-07-11 04:39 UTC, mysterywolf approved these changes

2023-07-11 04:39 UTC, merged

2023-07-11 04:39 UTC, mysterywolf commented
感谢贡献PR！