【dd2.0】Support Open Firmware API
RT-Thread/rt-thread pull request #7788
Opened 2023-07-06 02:31 UTC by ErikChanHub

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-06 02:52 UTC, mysterywolf commented
请使用 https://github.com/mysterywolf/formatting 格式化一下格式

2023-07-06 05:10 UTC, zhkag commented
#7789 这个合并了之后 CI就能过了，到时候重新提交一下

2023-07-06 05:35 UTC, mysterywolf commented
> #7789 这个合并了之后 CI就能过了，到时候重新提交一下

已合并

2023-07-06 07:23 UTC, Guozhanxin commented on bsp/nuvoton/nk-n9h30/.config
> +CONFIG_RT_USING_ADT_AVL=y
这么多都需要改这个吗，必须的？

2023-07-06 07:25 UTC, Guozhanxin commented on components/drivers/ofw/libfdt/fdt_addresses.c
> +// SPDX-License-Identifier: (GPL-2.0-or-later OR BSD-2-Clause)
这个版权是什么意思？

2023-07-06 07:35 UTC, ErikChanHub commented on bsp/nuvoton/nk-n9h30/.config
> +CONFIG_RT_USING_ADT_AVL=y
是必须的， adt现在不只是avl了，还加了其他工具

2023-07-06 07:39 UTC, zhkag commented on bsp/nuvoton/nk-n9h30/.config
> +CONFIG_RT_USING_ADT_AVL=y
menuconfig 保存可以自动生成吗？如果可以的话，就没必要改了

2023-07-06 07:40 UTC, ErikChanHub commented on components/drivers/ofw/libfdt/fdt_addresses.c
> +// SPDX-License-Identifier: (GPL-2.0-or-later OR BSD-2-Clause)
libfdt是 linux 开源的, 这个注释的意思是符合 GPL-2.0-or-later 或者 BSD-2-Clause 即可, 我们Apache-2.0的协议符合 BSD-2 的

2023-07-06 07:42 UTC, ErikChanHub commented on bsp/nuvoton/nk-n9h30/.config
> +CONFIG_RT_USING_ADT_AVL=y
要有MMU的平台才会自动选中这个宏

2023-07-06 07:49 UTC, Guozhanxin approved these changes

2023-07-06 07:50 UTC, zhkag commented on bsp/nuvoton/nk-n9h30/.config
> +CONFIG_RT_USING_ADT_AVL=y
你提交的这些都有 ARCH_MM_MMU 吧，都会自动选

2023-07-06 08:52 UTC, merged

2023-07-06 09:23 UTC, geniusgogo requested changes

2023-07-06 09:23 UTC, geniusgogo commented on components/drivers/ofw/fdt.c
> +struct rt_fdt_earlycon fdt_earlycon rt_section(".bss.noclean.earlycon");
看了一下没被外部引用加static

2023-07-06 09:23 UTC, geniusgogo commented on components/drivers/ofw/fdt.c
> +    return rt_fdt_commit_memregion_early(&(rt_region_t)
不建议写这种偷懒的代码

2023-07-06 09:23 UTC, geniusgogo commented on components/drivers/ofw/ofw_internal.h
> +    char name[sizeof("/")];
用sizeof定义数组只在C99标准并且支持可变长度数组规范下才支持吧？
换编译器会翻车？

2023-07-06 14:39 UTC, ErikChanHub commented on components/drivers/core/dm.c
> +    while (len --> 0)
是的, 这两天会把这些建议优化一次

2023-07-07 01:11 UTC, GuEe-GUI commented on components/drivers/include/drivers/core/rtdm.h
> +#ifndef RT_CPUS_NR
是的，因为有些渠道对资源的配置是根据CPU数量来的

2023-07-07 01:12 UTC, GuEe-GUI commented on components/drivers/include/drivers/misc.h
> +#define RT_DIV_ROUND_UP(n, d)   (((n) + (d) - 1) / (d))
可以考虑额外提供RT_DIV_ROUND_UP_ULL

2023-07-07 01:17 UTC, GuEe-GUI commented on components/drivers/ofw/fdt.c
> +struct rt_fdt_earlycon fdt_earlycon rt_section(".bss.noclean.earlycon");
此处后续如果 earlycon 框架确实没用到会加上 static

2023-07-07 01:17 UTC, GuEe-GUI commented on components/drivers/ofw/base.c
> +static rt_int32_t ofw_strcmp(const char *cs, const char *ct)
此处是由于调用ofw_prop_index_of_string的第二个参数需要传入 比较函数 的指针，所以没使用 inline，而 rt_strcmp，rt_strncmp 和 strcmp，strncmp 这些函数由于 rtthread.h 宏干扰不能直接找到定义（有未定义函数警告），所以独立设置了个函数用于间接跳转。

2023-07-07 01:18 UTC, GuEe-GUI commented on components/drivers/ofw/base.c
> +static rt_int32_t ofw_strcmp(const char *cs, const char *ct)
此处是由于调用ofw_prop_index_of_string的第二个参数需要传入 比较函数 的指针，所以没使用 inline，而 rt_strcmp，rt_strncmp 和 strcmp，strncmp 这些函数由于 rtthread.h 宏干扰不能直接找到定义（有未定义函数警告），所以独立设置了个函数用于间接跳转。

2023-07-07 01:20 UTC, GuEe-GUI commented on components/drivers/ofw/ofw_internal.h
> +    char name[sizeof("/")];
C98 已经 out 了吧，但是此处其实只要有 2 字节就够了，不会翻车的

2023-07-07 01:23 UTC, GuEe-GUI commented on components/drivers/ofw/fdt.c
> +    return rt_fdt_commit_memregion_early(&(rt_region_t)
这种写法确实少见，如果存在安全隐患会后续可以改成声明局部变量的方式。

2023-07-07 01:28 UTC, GuEe-GUI commented on components/drivers/include/drivers/byteorder.h
> +#define rt_cpu_to_be16(x) __builtin_bswap16(x)
这个符号目前只有 gcc，但是 DM 平台目前支持的平台芯片基本使用 GCC 和 Clang，这两种编译器都支持这个扩展。

2023-07-07 01:32 UTC, GuEe-GUI commented on components/drivers/core/dm.c
> +        if (*name < '0' || *name > '9')
这个函数就是为了获取 dm 的注册的设备名称，名称只能是 rtc 或者 rtc0，rtc123 这种格式，当我们从字符串末尾向前开始扫描到非数字的字符的时候，再继续向后 +1 后开始读取数字，如果是 rtc 这种格式,自然不会扫描到数字，返回的就是 0 了。

2023-07-07 01:33 UTC, GuEe-GUI commented on components/drivers/include/drivers/core/rtdm.h
> +extern int rt_hw_cpu_id(void);
这么改的话还需要 rtt 官方解释这个接口到底是 cpu 的索引还是 smp 的 id