【dd2.0】Support the Core API for dd2.0
RT-Thread/rt-thread pull request #7791
Opened 2023-07-06 09:07 UTC by ErikChanHub

## 拉取/合并请求描述：(PR description)

[
[【dd2.0】Support the Core API for dd2.0](https://github.com/RT-Thread/rt-thread/commit/fa18d03e33e483cd7f85f8e8af70881a76935c29)
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-06 12:19 UTC, BernardXiong commented on components/drivers/include/core/rtdm.h
> +/*
这个文件是否不需要，合并到其他头文件即可。而且这个头文件命名是rtxx的方式，而其他的并不是。

2023-07-06 12:56 UTC, ErikChanHub commented on components/drivers/include/core/rtdm.h
> +/*
这个文件中的数据都是给设备驱动用的,  松杰也觉得独立出来应该更合适一点

2023-07-07 01:46 UTC, BernardXiong commented on components/drivers/include/core/rtdm.h
> +/*
文件名会显得很不协调的。然后一些INIT_EXPORT，也可以放到rtdef.h中，放的地方多了，也不容易找

2023-07-07 01:53 UTC, GuEe-GUI commented on components/drivers/include/core/rtdm.h
> +/*
这个符号导出的话，只能在DM模式下使用，放 rtdef.h 不太合适耶，可以考虑把 rtdm.h 改成 dm.h。

2023-07-07 01:54 UTC, GuEe-GUI commented on components/drivers/include/core/rtdm.h
> +/*
> 文件名会显得很不协调的。然后一些INIT_EXPORT，也可以放到rtdef.h中，放的地方多了，也不容易找

这个符号导出的话，只能在DM模式下使用，放 rtdef.h 不太合适耶，可以考虑把 rtdm.h 改成 dm.h。

2023-07-07 02:03 UTC, ErikChanHub commented on components/drivers/include/core/rtdm.h
> +/*
> 文件名会显得很不协调的。然后一些INIT_EXPORT，也可以放到rtdef.h中，放的地方多了，也不容易找

rtdef.h 中的定义应该是适应所有平台的,   DM 中的这些显然是不适应的

2023-07-07 03:15 UTC, ErikChanHub commented on components/drivers/include/core/rtdm.h
> +/*
> 这个文件是否不需要，合并到其他头文件即可。而且这个头文件命名是rtxx的方式，而其他的并不是。
rtdm.h 已修改成 dm.h

2023-07-07 03:51 UTC, ErikChanHub commented
@geniusgogo @Guozhanxin  帮忙 review 一下哈

2023-07-07 06:21 UTC, geniusgogo approved these changes

2023-07-07 06:21 UTC, geniusgogo commented on components/drivers/core/bus.c
> +rt_err_t rt_bus_register(rt_bus_t bus)
貌似没有对bus的spinlock进行初始化，即使现在都是全局的并是0，最好还是进行这样的初始化

2023-07-07 06:33 UTC, ErikChanHub commented on components/drivers/core/bus.c
> +rt_err_t rt_bus_register(rt_bus_t bus)
已解决

2023-07-07 07:14 UTC, geniusgogo commented on components/drivers/core/bus.c
> +    rt_spin_lock_init(&bus->spinlock);
先初始化，再add吧？

2023-07-07 07:20 UTC, ErikChanHub commented on components/drivers/core/bus.c
> +    rt_spin_lock_init(&bus->spinlock);
嗯，刚看错了，已修改

2023-07-08 09:14 UTC, BernardXiong requested changes

2023-07-08 09:14 UTC, BernardXiong commented on components/drivers/pic/pic.c
> +#define _pirq_parent_call_helper(ppic, pirq, fn, ret, after, ...) \
这个宏感觉好妖，有必要一定按照这样方式定义吗？或者说，每个展开来写也没什么关系

2023-07-08 09:14 UTC, BernardXiong commented on components/drivers/include/core/dm.h
> +#define INIT_CORE_EXPORT(fn)            INIT_EXPORT(fn, "1.0")
这个点主要也包括，如果在rtdef.h那边修改了，增加了，而没看到这边的文件，这部分就被冲掉了。而且这类只是宏定义，没有DM存在时也应该这样定义的，否则做了调整，一些以库方式提供的，整体就不能使用，需要重新打库。

2023-07-08 15:07 UTC, ErikChanHub commented on components/drivers/include/core/dm.h
> +#define INIT_CORE_EXPORT(fn)            INIT_EXPORT(fn, "1.0")
这块确实没考虑好,  应该把 INIT_xxx_EXPORT  相关的宏都放到一起

2023-07-10 01:01 UTC, GuEe-GUI commented on components/drivers/pic/pic.c
> +#define _pirq_parent_call_helper(ppic, pirq, fn, ret, after, ...) \
写成宏的目的是为了统一参数检查和返回值设置操作，因为是基础接口，如果还是要展开的话就建议不对参数做检查了（改成 RT_ASSERT）

2023-07-10 02:57 UTC, ErikChanHub commented on components/drivers/include/core/dm.h
> +#define INIT_CORE_EXPORT(fn)            INIT_EXPORT(fn, "1.0")
> 这个点主要也包括，如果在rtdef.h那边修改了，增加了，而没看到这边的文件，这部分就被冲掉了。而且这类只是宏定义，没有DM存在时也应该这样定义的，否则做了调整，一些以库方式提供的，整体就不能使用，需要重新打库。

 @BernardXiong  INIT_xxx_EXPORT 相关宏, 已调整到 rtdef

2023-07-11 02:26 UTC, GuEe-GUI commented on components/drivers/pic/pic.c
> +#define _pirq_parent_call_helper(ppic, pirq, fn, ret, after, ...) \
> 这个宏感觉好妖，有必要一定按照这样方式定义吗？或者说，每个展开来写也没什么关系

已修改为展开。

2023-07-13 06:49 UTC, BernardXiong approved these changes

2023-07-13 06:49 UTC, merged

2023-09-22 09:39 UTC, zmshahaha commented
新增的components下的rt_device和rtdef.h下的rt_device重复，如何保证只include到一个？