Time dev
RT-Thread/rt-thread pull request #7794
Opened 2023-07-07 09:18 UTC by xqyjlj

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)

1. 添加ktime时间框架
2. 添加ns级rtc时间
3. 重构ctime模块
4. 添加ns级posix 定时器

**注：**：ns级rtc时间需要使用软件rtc作为默认rtc，如果有硬件RTC，请将硬件RTC注册为rtc0设备（详情请参考qemu-virt64-aarch64 rtc驱动）

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)
qemu，树莓派
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-08 10:38 UTC, BernardXiong commented
需要考虑几个点：
* mcu上使用64位会如何，还是说基本上和mcu无关；
* 是否会存在计算溢出的问题；
* 一些新的文件存在，没有文件头，代码缺少注释。

2023-07-10 03:02 UTC, xqyjlj commented
> 需要考虑几个点：
> 
> * MCU上使用64位会如何，还是说基本上和MCU无关;
> * 是否会存在计算溢出的问题；
> * 一些新的文件存在，没有文件头，代码缺少注释。

1. mcu 上现在可以使用，已经使用long类型来区别了，64位平台为64位，32位的mcu就是32位
2. 计算溢出问题是存在的（64位平台几乎不会遇到溢出问题，32位平台可能性还是有的），由于rtc走的是rt-tick，所以在几十天后，rtc时间也会异常

2023-07-12 07:39 UTC, sp-cai commented
对于一些日志信息建议不要直接 rt_kprintf，应该用 LOG_D、LOG_I、LOG_W、LOG_E。

2023-07-12 15:47 UTC, armink requested changes
目前改动是否兼容旧的驱动，之前的为了支持毫秒时间戳的 timeval 是否还继续具备

2023-07-12 15:47 UTC, armink commented on components/drivers/rtc/soft_rtc.c
> -#endif
这块代码为啥要移除？

2023-07-12 15:47 UTC, armink commented on components/libc/compilers/common/ctime.c
> +    if ((t != RT_NULL) && (_control_rtc(RT_DEVICE_CTRL_RTC_SET_TIME, (void *)t) == RT_EOK))
这里看着缺少对于 RT_DEVICE_CTRL_RTC_SET_TIMEVAL 支持

2023-07-13 01:54 UTC, xqyjlj commented
> 目前改动是否兼容旧的驱动，之前的为了支持毫秒时间戳的 timeval 是否还继续具备

兼容，而且还将原有的timeval 提升至了us精度，除此之外，还引入了timespec的ns精度

注：需要重写rt_ktime_cputimer_getfrq等函数，不然默认的精度就只有系统心跳的频率了

2023-07-14 15:12 UTC, BernardXiong commented
@armink 帮忙review下

2023-07-15 00:05 UTC, mysterywolf commented
请在STM32上测试一下，确保MCU也可以正确工作。

2023-07-15 00:09 UTC, mysterywolf commented
麻烦git rebase 一下吧 51个commit太恐怖了。这个PR没法squash合并，修改的地方太多了 不能一个commit直接压一起。麻烦拆成多个有意义的commit提交上来吧。

2023-07-15 04:41 UTC, armink commented on components/drivers/rtc/soft_rtc.c
> -#endif
ping

2023-07-15 04:43 UTC, armink commented on components/drivers/rtc/soft_rtc.c
> +        _source_device_control(RT_DEVICE_CTRL_RTC_SET_TIME, &(tv->tv_sec));
这里传入的还是秒级，上层没法获取到毫秒，甚至微秒的时间单位吧

2023-07-15 11:56 UTC, armink approved these changes

2023-07-17 06:32 UTC, xqyjlj commented
@mysterywolf 

> 请在STM32上测试一下，确保MCU也可以正确工作。

在星火一号上测了rtc与rt_ktime_hrtimer_mdelay

> 麻烦git rebase 一下吧 51个commit太恐怖了。这个PR没法squash合并，修改的地方太多了 不能一个commit直接压一起。麻烦拆成多个有意义的commit提交上来吧。

已

2023-07-17 07:50 UTC, polarvid commented on libcpu/risc-v/virt64/tick.c
> +#define FREQUENCY (10000000UL)
这个有个宏：`CPUTIME_TIMER_FREQ` 参考 `https://github.com/RT-Thread/rt-thread/blob/b424169e1742c1b19d039f9871dd3c672ea7b729/components/drivers/Kconfig#L110`

2023-07-17 12:11 UTC, merged