[components][i2c] 优化 controt 接口格式，增加可用命令
RT-Thread/rt-thread pull request #7806
Opened 2023-07-10 04:54 UTC by sp-cai

## 拉取/合并请求描述：(PR description)
原来 rt_i2c_control 只能执行 RT_I2C_DEV_CTRL_CLK 单一命令，通过此修改可以支持更多可用命令

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-10 09:22 UTC, supperthomas requested changes
这个改动，需要bsp修改吗？会涉及到所有bsp和example吗？

2023-07-10 09:34 UTC, sp-cai commented
> 请问这个改动，需要bsp的driver配合修改吗？会涉及到所有bsp和example吗？

由于 bsp 和 example 太多，只抽检过部分，都没有影响的。

2023-07-10 09:38 UTC, supperthomas commented
> > 请问这个改动，需要bsp的driver配合修改吗？会涉及到所有bsp和example吗？
> 
> 由于 bsp 和 example 太多，只抽检过部分，都没有影响的。

哦，你这改的是内部的，没有改外部API。

2023-07-10 09:41 UTC, supperthomas commented
> > 请问这个改动，需要bsp的driver配合修改吗？会涉及到所有bsp和example吗？
> 
> 由于 bsp 和 example 太多，只抽检过部分，都没有影响的。

那你是基于那个bsp来进行测试的呢？

2023-07-10 11:12 UTC, supperthomas commented
嗯，这个改动是挺好的。所以我想问下你在哪个bsp上测试通过的？有没有一些example之类的。

2023-07-10 12:39 UTC, sp-cai commented
> 嗯，这个改动是挺好的。所以我想问下你在哪个bsp上测试通过的？有没有一些example之类的。

HC32F460 使用自己写的 I2C 驱动，在项目开发中测试的

2023-07-10 15:03 UTC, supperthomas commented
> 晚上花了点时间筛查到以下文件受影响的： https://github.com/RT-Thread/rt-thread/tree/master/bsp/airm2m/air105/libraries/rt_drivers/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/apollo2/board/i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/ESP32_C3/drivers/drv_hw_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/imxrt/libraries/drivers/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/loongson/ls1cdev/drivers/hw_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/lpc54114-lite/drivers/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/microchip/common/board/sam_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/m031/rtt_port/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/m2354/rtt_port/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/m460/rtt_port/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/m460/rtt_port/drv_ui2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/m480/rtt_port/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/ma35/rtt_port/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/n9h30/rtt_port/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/libraries/nuc980/rtt_port/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/raspberry-pi/raspi3-32/driver/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/raspberry-pi/raspi3-64/driver/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/raspberry-pi/raspi4-32/driver/drv_i2c.c https://github.com/RT-Thread/rt-thread/tree/master/bsp/w60x/drivers/drv_i2c.c 现在已全部修改好了

好的，非常感谢PR。这个改动比较大，需要其他reviewer 查看，谢谢。

2023-07-10 22:49 UTC, mysterywolf approved these changes

2023-07-14 01:55 UTC, Guozhanxin approved these changes

2023-07-14 01:57 UTC, merged