[bsp][esp32-c3] Preliminary realization of scons compilation of ESP32-C3 | 初步实现ESP32-C3的scons编译
RT-Thread/rt-thread pull request #7821
Opened 2023-07-16 12:47 UTC by WCX1024979076

…-C3 | 初步实现ESP32-C3的scons编译

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

更改`bsp/ESP32C3`代码引入scons编译支持，目前可以直接使用`scons`来编译`bsp/ESP32-C3`

#### 你的解决方案是什么 (what is your solution)

修改`bsp/ESP32C3`中`SConstruct`和`SConscript`代码，使得可以直接使用`scons`命令来编译`bsp`而无需使用`idf.py`来进行编译

#### 在什么测试环境下测试通过 (what is the test environment)

在一个新的系统环境中完成了工具链下载和配置，并成功用`scons`编译出`rtthread.bin`并烧录运行。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-16 13:19 UTC, WCX1024979076 commented
上面自动化测试不通过是由于网络问题导致`build bouffalo_lab/bl70x`和`bouffalo_lab/bl60x`检查不通过，我查看了一下日志是从`gitee.com`上下载失败。

2023-07-16 22:51 UTC, supperthomas commented
> 

可以尝试添加esp32c3的toolchain，放到action.yml中。这个看下难不难。

2023-07-16 23:02 UTC, supperthomas approved these changes

2023-07-17 01:42 UTC, WCX1024979076 commented
好的，我去试一下

2023-07-17 15:53 UTC, supperthomas approved these changes

2023-07-18 00:45 UTC, supperthomas commented
> 好的，我去试一下

麻烦吗？要不我们先把这个合进去？

2023-07-18 01:42 UTC, WCX1024979076 commented
这个昨天写了一下试了一下，发现`packages`的PR还没通过，`scons`检查没通过，要不这个代码先合并了吧，下一次我写驱动的时候顺带实现了那个`action.xml`。

2023-07-18 11:22 UTC, supperthomas requested changes

2023-07-18 11:22 UTC, supperthomas commented on bsp/ESP32_C3/README.md
> -git checkout 5c1044d84d625219eafa18c24758d9f0e4006b2c
这一步需要吗？https://github.com/RT-Thread-packages/esp-idf 你是直接用的这个仓库吗？

2023-07-18 11:27 UTC, supperthomas commented
> 这个昨天写了一下试了一下，发现`packages`的PR还没通过，`scons`检查没通过，要不这个代码先合并了吧，下一次我写驱动的时候顺带实现了那个`action.xml`。

packages 已经合进去了，试下加下action.yml.需要我帮你写一些吗？

2023-07-18 11:38 UTC, WCX1024979076 commented
还依赖于一个package，是`FreeRTOS-Wrapper`，目前已和负责人联系并且商议合并，地址在 https://github.com/RT-Thread-packages/FreeRTOS-Wrapper/pull/36

2023-07-18 11:42 UTC, WCX1024979076 commented
还有一个下载的压缩包是tat.xz，解压命令有误，这样写就可以了：
```sh
wget -q https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1-RC1/riscv32-esp-elf-gcc11_2_0-esp-2022r1-RC1-linux-amd64.tar.xz
 sudo tar xf riscv32-esp-elf-gcc11_2_0-esp-2022r1-RC1-linux-amd64.tar.xz -C /opt
/opt/riscv32-esp-elf/bin/riscv32-esp-elf-gcc --version
echo "RTT_EXEC_PATH=/opt/riscv32-esp-elf/bin" >> $GITHUB_ENV
pip install esptool
```

2023-07-18 11:44 UTC, supperthomas commented
> 还有一个下载的压缩包是tat.xz，解压命令有误，这样写就可以了：
> 
> ```shell
> wget -q https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1-RC1/riscv32-esp-elf-gcc11_2_0-esp-2022r1-RC1-linux-amd64.tar.xz
>  sudo tar xf riscv32-esp-elf-gcc11_2_0-esp-2022r1-RC1-linux-amd64.tar.xz -C /opt
> /opt/riscv32-esp-elf/bin/riscv32-esp-elf-gcc --version
> echo "RTT_EXEC_PATH=/opt/riscv32-esp-elf/bin" >> $GITHUB_ENV
> pip install esptool
> ```

你自己把代码拉下来改下吧，或者直接仓库里面改，应该不难了吧？CI？

2023-07-18 11:52 UTC, WCX1024979076 commented
好的

2023-07-25 02:18 UTC, supperthomas approved these changes

2023-07-25 02:26 UTC, WCX1024979076 commented
GitHub action 报错，`scons`编译过程中提示`esptool`没找到，我看了一下编译日志`scons`是使用的独立的缓存的`python`环境，`LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.17/x64/lib`，我在尝试解决但是没有查到合适的方法。 @supperthomas

2023-07-25 02:32 UTC, WCX1024979076 commented
我有个想法，`/opt/hostedtoolcache/Python/3.8.17/x64/bin/pip install esptool`这样来写命令安装`esptool`，不知道可行不可行了

2023-07-25 02:58 UTC, supperthomas commented
> 我有个想法，`/opt/hostedtoolcache/Python/3.8.17/x64/bin/pip install esptool`这样来写命令安装`esptool`，不知道可行不可行了

试试呗。

2023-07-25 02:59 UTC, supperthomas commented
https://club.rt-thread.org/ask/article/d25fb0a88165f166.html


试试用下这个黑科技。

2023-07-25 03:03 UTC, WCX1024979076 commented
Github codespace 我正在用，感觉还可以，用了一段时间了

2023-07-25 03:10 UTC, WCX1024979076 commented
还是报相同的错误，我再想想办法

2023-07-25 03:11 UTC, supperthomas commented
> Github codespace 我正在用，感觉还可以，用了一段时间了

在codespace里面先试试命令，会报错吗？

2023-07-25 03:15 UTC, WCX1024979076 commented
在codespace中运行`pip install esptool`并且导入`esptool`没问题

2023-07-25 03:19 UTC, supperthomas commented
pip3 install esptool 试试

2023-07-25 03:30 UTC, WCX1024979076 commented
还是报错，我新开一个codespace重新配置一下试试

2023-07-25 03:42 UTC, mysterywolf approved these changes

2023-07-25 03:50 UTC, WCX1024979076 commented
问题解决了，通过`apt-get`安装的`scons`使用的`python`环境是系统默认自带的`python`环境，通过`/usr/bin/pip install esptool`就可以了。另一个测试`/ kernel/atomic `没过我就不知道具体原因了。 @supperthomas

2023-07-25 05:42 UTC, merged

2023-07-26 02:36 UTC, supperthomas commented
可否帮忙在论坛里面发一篇如何使用ESP32的文章？

2023-07-26 03:23 UTC, WCX1024979076 commented
可以的，我去整理一下材料写一下