[bsp] [msp43] add msp432e401y-LaunchPad BSP v0.1
RT-Thread/rt-thread pull request #7823
Opened 2023-07-16 14:15 UTC by yby-oy

## 拉取/合并请求描述：(PR description)

[    
#### 为什么提交这份PR (why to submit this PR)   
添加msp432e401y-LaunchPad的BSP包    

#### 你的解决方案是什么 (what is your solution)    
添加bsp并通过测试，并支持最基本的功能：uart 控制台，pin 设备     

#### 在什么测试环境下测试通过 (what is the test environment)    
在keil5中，使用msp432e401y-LaunchPad开发板进行闪灯demo测试    
]

### 当前拉取/合并请求的状态 Intent for your PR   

必须选择一项 Choose one (Mandatory):   

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-16 14:25 UTC, yby-oy commented
@Guozhanxin 郭老师，帮忙看看

2023-07-16 23:09 UTC, supperthomas commented
新增bsp目录可否在https://github.com/RT-Thread/rt-thread/blob/master/bsp/README.md 这边对应的厂商下面添加以下？这个好像是TI的。

2023-07-16 23:14 UTC, supperthomas requested changes

2023-07-16 23:14 UTC, supperthomas commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/CMSIS/DSP_Lib/lib/ccs/m4f/Makefile
> +AR = "$(CCS_ARMCOMPILER)/bin/armar"
这个文件有用到吗？如果一直用不到，可以尝试删了，README里面写下sdk的下载路径即可。

2023-07-16 23:14 UTC, supperthomas commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.c
> + * -------------------------------------------------------------------- */
这些文件需要用到吗？

2023-07-16 23:14 UTC, supperthomas commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c
> + *
可以尝试将bsp轻量化。需要用到的文件保留即可。暂时不需要，以后也不需要的文件可以删除，删除之后，尽量将几个commit合并成一个commit（不然删不干净）。

2023-07-16 23:16 UTC, supperthomas commented
![image](https://github.com/RT-Thread/rt-thread/assets/60349489/8ffb778c-d5b0-42dc-ac81-28cb9b633ffd)


https://github.com/RT-Thread/rt-thread/actions/runs/5568134570/jobs/10174165147?pr=7823

CI 编译有报错。

2023-07-17 00:32 UTC, supperthomas commented
请删除bsp中编译用不到的文件，需要用到的文件可以保留路径。如果需要提供SDK可以在readme中提供sdk下载链接，其他人可以获取到即可。

2023-07-17 03:02 UTC, yby-oy commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/CMSIS/DSP_Lib/lib/ccs/m4f/Makefile
> +AR = "$(CCS_ARMCOMPILER)/bin/armar"
已处理

2023-07-17 03:02 UTC, yby-oy commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.c
> + * -------------------------------------------------------------------- */
dsp的库都删掉了

2023-07-17 03:02 UTC, yby-oy commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c
> + *
dsp的库都删掉了

2023-07-17 03:36 UTC, yby-oy commented
@supperthomas 都改好了，新的bsp的ci我加不上去，其他都没问题。

2023-07-17 06:44 UTC, supperthomas commented
> @supperthomas 都改好了，新的bsp的ci我加不上去，其他都没问题。

CI 放上去，我来看下。

2023-07-17 06:55 UTC, yby-oy commented
> 

windows上gcc和armcc都没问题，linux上找不到路径,ci加进来了

2023-07-17 07:33 UTC, supperthomas requested changes

2023-07-17 07:33 UTC, supperthomas commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/SConscript
> +         cwd + '/CMSIS/include']
这里include大小写check一下，按照实际大小写。

2023-07-17 08:12 UTC, yby-oy commented on bsp/msp432e401y-LaunchPad/libraries/Drivers/SConscript
> +         cwd + '/CMSIS/include']
已修改，linux下路径可以找到了

2023-07-17 09:20 UTC, yby-oy commented
@supperthomas 能再跑一下ci吗，现在应该没啥问题了

2023-07-17 09:33 UTC, supperthomas approved these changes

2023-07-18 00:38 UTC, mysterywolf approved these changes

2023-07-18 00:39 UTC, merged

2023-07-18 03:24 UTC, mcuxthomas commented
感谢PR。