AArch64: support public linker scripts
RT-Thread/rt-thread pull request #7831
Opened 2023-07-20 05:39 UTC by GuEe-GUI

## 拉取/合并请求描述：(PR description)

[
1. 为 AArch64 libcpu 独立添加 Kconfig。
2. 支持以设备树引导的 ARM64 kernel 启动头部。
3. 支持 AArch64 使用公共链接脚本。

目前只在 QEMU 环境下使用相关功能，测试 RTOS/RT-Smart 版本通过。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-20 07:02 UTC, BernardXiong requested changes

2023-07-20 07:02 UTC, BernardXiong commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
统一成一份link.lds.S，目的是什么？在Windows上是否依然有效？

2023-07-20 07:02 UTC, BernardXiong commented on libcpu/aarch64/Kconfig
> +    int "Armv8-A extensions"
是否按choose类型会更合适些，直接数字方式，并不能比较好的代表其中的意义

2023-07-20 07:04 UTC, GuEe-GUI commented on tools/building.py
> +        os.system(CPP + inc + ' ' + path + input + ' -o ' + path + output)
Windows 下环境测试过 RTOS 和 RT-Smart 都可以

2023-07-20 07:05 UTC, GuEe-GUI commented on libcpu/aarch64/Kconfig
> +    int "Armv8-A extensions"
这里起初的考虑是 ARMv8 的特性是递增的，直接判断数字会简洁很多。

2023-07-20 07:29 UTC, polarvid commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
如果有通用的链接脚本，后面加一些特殊的section会方便一些。比如 KASAN、ftrace 都有数据要链接到镜像里面。这部分和硬件无关，如果还要一个一个bsp改就有点麻烦

2023-07-20 09:25 UTC, BernardXiong commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
好像在gcc上，一些section可以通过一些方式比较好的直接在代码中就处理好了。不知道kasan，ftrace是否可以这样

2023-07-20 09:31 UTC, GuEe-GUI commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
统一是必要的，有些段和符号是要单独加的；使用公共链接脚本不是强制的，只有 BSP 目录没有链接脚本的时候才会使用。

2023-07-21 01:34 UTC, geniusgogo commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
链接脚本是不是也支持include另一个链接脚本？这样bsp自己的链接脚本可以通过include这份公共的进来？

2023-07-21 01:36 UTC, GuEe-GUI commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
理论上可以，前提是 BSP 的维护者会好好用

2023-07-21 01:57 UTC, polarvid commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
> 好像在gcc上，一些section可以通过一些方式比较好的直接在代码中就处理好了。不知道kasan，ftrace是否可以这样

这些 section 是编译器生成的，在二进制里面固定的，有点像 .stab、DWARF 那些。不改链接脚本的话，ld 生成的镜像里面就没有了。

2023-07-22 02:33 UTC, BernardXiong commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
针对msh的命令section，实际上是可以不需要的。只要代码中有`__attribute__((section(x)))` 的修饰，就可以获得。

2023-07-24 00:53 UTC, GuEe-GUI commented on libcpu/aarch64/link.lds.S
> +#ifndef ARCH_TEXT_OFFSET
> 针对msh的命令section，实际上是可以不需要的。只要代码中有`__attribute__((section(x)))` 的修饰，就可以获得。

可以，如果 RT-Thread 有对这种行为做规范的话。

2023-07-25 01:03 UTC, BernardXiong requested changes

2023-07-25 01:03 UTC, BernardXiong commented on libcpu/aarch64/Kconfig
> +    int "Armv8-A extensions"
建议还是用choose吧，同时给出简要介绍；否则这部分具体填多少数值，这个是未知的。

2023-07-25 01:03 UTC, BernardXiong commented on bsp/qemu-virt64-aarch64/SConstruct
> -env['LINKCOM'] = '$LINK -o $TARGET $LINKFLAGS $__RPATH $SOURCES $_LIBDIRFLAGS -Wl,--start-group $_LIBFLAGS -Wl,--end-group'
这句为什么移除掉？因为有的时候会出现链接顺序不一致，导致找不到符号的问题。所以这里是前后加了group，这样可以循环查找。

2023-07-25 01:11 UTC, GuEe-GUI commented on bsp/qemu-virt64-aarch64/SConstruct
> -env['LINKCOM'] = '$LINK -o $TARGET $LINKFLAGS $__RPATH $SOURCES $_LIBDIRFLAGS -Wl,--start-group $_LIBFLAGS -Wl,--end-group'
这句可以不移除，一会更新，但是链接顺序出现问题应该是系统构建时没处理好依赖关系导致的。

2023-07-25 01:12 UTC, GuEe-GUI commented on bsp/qemu-virt64-aarch64/SConstruct
> -env['LINKCOM'] = '$LINK -o $TARGET $LINKFLAGS $__RPATH $SOURCES $_LIBDIRFLAGS -Wl,--start-group $_LIBFLAGS -Wl,--end-group'
> 这句为什么移除掉？因为有的时候会出现链接顺序不一致，导致找不到符号的问题。所以这里是前后加了group，这样可以循环查找。

这句可以不移除，一会更新，但是链接顺序出现问题应该是系统构建时没处理好依赖关系导致的。

2023-07-25 01:12 UTC, GuEe-GUI commented on libcpu/aarch64/Kconfig
> +    int "Armv8-A extensions"
> 建议还是用choose吧，同时给出简要介绍；否则这部分具体填多少数值，这个是未知的。

好的

2023-07-25 13:31 UTC, BernardXiong approved these changes

2023-07-25 13:31 UTC, merged

2023-07-29 20:07 UTC, mysterywolf commented
新增加的Kconfig导致MCU这边会出现空白
![ba1c616227077d20c632405a5896025](https://github.com/RT-Thread/rt-thread/assets/34888354/e51780b2-9852-4c53-8179-d3ced0410f10)

2023-07-29 20:07 UTC, mysterywolf commented
为什么要把architecture这个kconfig暴露给用户呀，这个一般是BSP直接选定的，用户是不需要介入选择的

2023-07-30 05:53 UTC, GuEe-GUI commented
> 新增加的Kconfig导致MCU这边会出现空白 ![ba1c616227077d20c632405a5896025](https://user-images.githubusercontent.com/34888354/257008071-e51780b2-9852-4c53-8179-d3ced0410f10.png)

后面修复会修复为 libcpu 有独立的Kconfig才会显示

2023-07-30 05:58 UTC, GuEe-GUI commented
> 为什么要把architecture这个kconfig暴露给用户呀，这个一般是BSP直接选定的，用户是不需要介入选择的

是这样，在 ARM64，x86 这些系统级芯片上，有很多 CPU feature 以及 CPU 设计勘误代码，CPU 寻址能力等配置是存在交叉，互斥的情况（与具体 BSP 无关），这些选项是不能直接 select 的，需要用户自己排除或者选择需要的场景。

2023-07-30 06:02 UTC, mysterywolf commented
OK 了解了