Add the system call eventfd
RT-Thread/rt-thread pull request #7835
Opened 2023-07-20 07:24 UTC by zmq810150896

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
Add the eventfd system call API

#### 在什么测试环境下测试通过 (what is the test environment)
qemu-virt64-aarch64
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-20 07:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7835) before we can accept your contribution.<br/><hr/>**zmq810150896** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7835) it.</sub>

2023-07-20 07:59 UTC, BernardXiong requested changes

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +    .lseek      = noop_lseek,
这部分是否直接给NULL更合适？直接返回一个pos，意义也不大（应该恒定是0吧）。

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +        rt_kprintf("%u \n", ucnt);
这里输出rt_kprintf的意义是？

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +
空行……

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_u64 count;
哪里出了份`rt_u64`的定义？

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_u64 ucnt = 0;
`ucnt` 当使用缩写时，请给出全称的注释。

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +        return -ENOMEM;
最好是给出统一的出口。

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +    free(ctx);
这部分再多仔细想想，是否还需要释放更多的资源。也包括确认下，vnode是在哪里释放的

2023-07-20 07:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +static resource_id_t id_mgr = RESOURCE_ID_INIT(RT_UNAMED_PIPE_NUMBER, resoure_id);
这部分相当于多了个id号，这部分会在哪个环节体系出来？

2023-07-20 08:23 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +static resource_id_t id_mgr = RESOURCE_ID_INIT(RT_UNAMED_PIPE_NUMBER, resoure_id);
会在 互斥量初始化的时候用到，每次初始化 互斥量，目的是为了初始化互斥量的名字不同
rt_mutex_init(&ctx->lock, name, RT_IPC_FLAG_FIFO);

2023-07-20 09:26 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +static resource_id_t id_mgr = RESOURCE_ID_INIT(RT_UNAMED_PIPE_NUMBER, resoure_id);
有的时候，名字相同也没关系的。所以除了这些mutex init，还有其他地方吗

2023-07-20 09:36 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +    .lseek      = noop_lseek,
直接给NULL的话，如果有人调用lseek，会出问题的

2023-07-20 09:37 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +static resource_id_t id_mgr = RESOURCE_ID_INIT(RT_UNAMED_PIPE_NUMBER, resoure_id);
没有其他地方了，那我把这一部分删除掉

2023-07-20 12:00 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.c
> +void eventfd_ctx_do_read(struct eventfd_ctx *ctx, rt_ubase_t *cnt)
static inline?

2023-07-20 12:01 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_poll_add(&ctx->reader_queue, req);
这里是逻辑代码，要与变量定义隔一空行，然后下面那些变量定义要挪上来。

2023-07-20 12:01 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.c
> +    if(ctx->count == 0)
if要跟空格

2023-07-20 12:03 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_mutex_take(&ctx->lock, RT_WAITING_FOREVER);
整个函数的拿锁逻辑有点乱，应该可以代码梳理优化一下。

2023-07-20 12:04 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.c
> +        rt_kprintf("aaaaa %d \n", file->flags & O_NONBLOCK);
调试打印？应该去掉

2023-07-20 12:05 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_ubase_t ucnt = *(rt_ubase_t *)buf;
拿地址值？ 这种意图是啥？离翻车不远了。

2023-07-20 12:07 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.c
> +            free(ctx);
为什么rt_malloc和free混合使用？不应该是rt_free?

2023-07-20 12:08 UTC, geniusgogo commented on components/libc/posix/io/eventfd/eventfd.h
> +#define ULLONG_MAX  (~0ULL)
这种宏定义除非多个地方使用，否则不要放到头文件中。而且容易引起冲突。

2023-07-20 12:09 UTC, geniusgogo commented on components/lwp/lwp_syscall.c
> +    ret = eventfd2(count, flags);
功能代码和变量定义隔一个空行

2023-07-20 12:09 UTC, geniusgogo commented on components/lwp/lwp_syscall.c
> +    ret = eventfd(count);
功能代码和变量定义隔一个空行

2023-07-20 13:01 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_mutex_take(&ctx->lock, RT_WAITING_FOREVER);
这个拿锁，当数据以阻塞模式读取时，当ctx->计数为0时，需要释放互斥量并等待写入，在rt_wqueue_wait函数调用之前，必须释放锁，让eventfd_write函数可以写。当数据非堵塞方式读的时候，在ctx->count为0时，在return 前直接释放锁，并return。
这里区分堵塞和不堵塞方式，简而言之，就是堵塞的时候释放锁，当工作队列就绪的时候拿锁。不堵塞的时候直接释放锁，并返回。

2023-07-20 13:23 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +    free(ctx);
这里存在一个问题，是有关dfs v1 的， 在dfs v1 里 没有fs_vnode_destroy(struct dfs_vnode* vnode); 释放函数，在dfs v2 里是有的。
在调用eventfd 时，会rt_malloc 一个 file->vnode 的空间， 然后会调用 int dfs_vnode_init(struct dfs_vnode *vnode, int type, const struct dfs_file_ops *fops) 初始化 vnode，释放的时候不能调用rt_free 释放，不然会挂掉，应该先调用fs_vnode_destroy 这个函数。但是在dfs v1 里没有

2023-07-20 13:38 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_ubase_t ucnt = *(rt_ubase_t *)buf;
这个是拿值，不是拿地址，用户态那边传过来是一个unsigned long 的值，到这个函数里，变成了 void * 类型， 然后就是 先转成unsigned long * 类型， 最后再* 取值。

2023-07-22 02:20 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +    .lseek      = noop_lseek,
会返回错误或没实现，应该不会有问题。本身也没有谁会对eventfd来做seek，如果做了seek返回错误，也正常。

2023-07-22 02:24 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +        res = sizeof(ucnt);
这里加括号吧

2023-07-22 02:28 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +            rt_free(ctx);
:bug: 前面的mutex需要detach

2023-07-22 03:24 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +            rt_free(ctx);
加上了

2023-07-22 03:24 UTC, zmq810150896 commented on components/libc/posix/io/eventfd/eventfd.c
> +        res = sizeof(ucnt);
好的，已经加上

2023-07-22 13:59 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +    rt_ubase_t ucnt = *(rt_ubase_t *)buf;
如果是`unsigned long`的，那么这里也应该是转换成这个值。

2023-07-22 14:00 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.c
> +            rt_free(ctx);
为什么是前面free，后面mutex_detach？这个顺序有问题。

2023-07-22 14:01 UTC, BernardXiong commented on components/libc/posix/io/eventfd/eventfd.h
> +#include <rtthread.h>
后面的函数声明似乎都是完全标准的，那么这里不需要加入这些头文件包含。

2023-07-25 00:56 UTC, BernardXiong approved these changes

2023-07-27 01:50 UTC, geniusgogo approved these changes

2023-07-27 03:13 UTC, Guozhanxin approved these changes

2023-07-27 09:24 UTC, merged