[smart] 修复用户态 mq_receive 不能阻塞
RT-Thread/rt-thread pull request #7836
Opened 2023-07-20 09:24 UTC by zhkag

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-20 09:28 UTC, BernardXiong approved these changes

2023-07-20 11:42 UTC, geniusgogo requested changes
```c
if (abs_timeout != RT_NULL)
    tick = rt_timespec_to_tick(abs_timeout);
else
    tick = RT_WAITING_FOREVER;
```

2023-07-20 11:42 UTC, geniusgogo commented on components/libc/posix/ipc/mqueue.c
> +    if (-1 == (rt_ubase_t)abs_timeout )
不能用-1，而是保持用NULL（0）代表forever

2023-07-20 12:15 UTC, geniusgogo requested changes

2023-07-20 12:15 UTC, geniusgogo commented on components/libc/posix/ipc/mqueue.c
> +    if (abs_timeout == RT_NULL)
不要改已有的逻辑，只需要添加你的修改代码即可

2023-07-22 22:31 UTC, BernardXiong commented
在dfsv2中的dfs_mqueue.c还存在编译问题，mqueue请在qemu-vexpress-a9中打开吧（包括使用dfsv2），这样可以在ci中持续集成；

2023-07-23 02:01 UTC, zhkag commented
> 在dfsv2中的dfs_mqueue.c还存在编译问题（还有代码风格），mqueue请在qemu-vexpress-a9中打开吧（包括使用dfsv2），这样可以在ci中持续集成；

熊大 我推了 你看一下

2023-07-24 03:30 UTC, geniusgogo approved these changes

2023-07-24 09:01 UTC, merged