[components][i2c]增加通用的软件模拟 I2C
RT-Thread/rt-thread pull request #7850
Opened 2023-07-23 12:35 UTC by sp-cai

实现无需直接操作任何底层硬件的通用软件 I2C ，并提级到设备框架层，用于替代所有 BSP 的软件模拟 I2C 。

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
使用 pin 设备和软延时就可以实现软件模拟 I2C ，没必要每一个BSP都要实现一次。
#7725 

#### 你的解决方案是什么 (what is your solution)
1. 使用 pin 设备实现 SCL 线和 SDA 线电平。
2. 使用 rt_hw_us_delay 实现时序延时。
3. 实现了比较完善的总线错误检测和报告。
4. 实现通过串口调试接口就可以读写各种 I2C 设备。

#### 在什么测试环境下测试通过 (what is the test environment)
使用 HK32F030 和 HC32F460 通过本软件模拟 I2C 读写 24C02 和 KT06XX 等。
由于手头只有 7bit 地址的设备，因此没有测试 10bit 地址的。

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-26 15:04 UTC, supperthomas requested changes

2023-07-26 15:04 UTC, supperthomas commented on components/drivers/i2c/soft_i2c.c
> +#define SET_SCL(cfg, val)   rt_pin_write((cfg)->scl_pin, val)
https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c

请参考STM32这里的soft_i2c.c 实现相应的函数。

2023-07-27 01:09 UTC, sp-cai commented on components/drivers/Kconfig
> +config RT_USING_UDELAY
用于开关 rt_hw_us_delay 使用的，这里没用，可以删除了

2023-07-27 01:20 UTC, sp-cai commented on components/drivers/i2c/soft_i2c.c
> +#define SET_SCL(cfg, val)   rt_pin_write((cfg)->scl_pin, val)
改用 drv_soft_i2c.c 的方式是不是太臃肿了？

2023-07-27 01:46 UTC, sp-cai commented on components/drivers/Kconfig
> +config RT_USING_UDELAY
需要删吗？

2023-07-27 02:17 UTC, supperthomas commented on components/drivers/Kconfig
> +config RT_USING_UDELAY
删除吧

2023-07-27 02:18 UTC, supperthomas commented on components/drivers/Kconfig
> +config RT_USING_UDELAY
如果没实现，需要显示出来，看下会显示吗？

2023-07-27 02:18 UTC, supperthomas commented on components/drivers/i2c/soft_i2c.c
> +#define SET_SCL(cfg, val)   rt_pin_write((cfg)->scl_pin, val)
详细讲讲，哪里臃肿？

2023-07-27 04:52 UTC, sp-cai commented on components/drivers/i2c/soft_i2c.c
> +#define SET_SCL(cfg, val)   rt_pin_write((cfg)->scl_pin, val)
i2c-bit-ops.c + drv_soft_i2c.c：drv_soft_i2c.c 由 BSP 实现，i2c-bit-ops.c 共用。
由于实现通用 I2C 后就没必要再分开两层了，两层结构增加了没必要的消耗。
所以 i2c-bit-ops.c 和 drv_soft_i2c.c 下一步是要清理的。

2023-07-29 12:04 UTC, supperthomas requested changes
建议还是保留之前的分层结构，这样维护代码会方便一些~，也可以解一些耦合~

2023-07-30 08:09 UTC, sp-cai commented
> 



> 建议还是保留之前的分层结构，这样维护代码会方便一些~，也可以解一些耦合~也便于维护

好的，我再改一下

2023-07-31 14:23 UTC, sp-cai commented
> 建议还是保留之前的分层结构，这样维护代码会方便一些~，也可以解一些耦合~也便于维护

已改好

2023-08-15 11:11 UTC, supperthomas requested changes

2023-08-15 11:11 UTC, supperthomas commented on components/drivers/i2c/soft_i2c.c
> +    #ifdef RT_USING_SOFT_I2C5
这里为什么从I2C5开始？

2023-08-15 11:11 UTC, supperthomas commented on components/drivers/include/drivers/i2c.h
> +    rt_uint16_t  retries;
i2c.h 修改理由？

2023-08-15 11:11 UTC, supperthomas commented on components/drivers/Kconfig
> +		config RT_USING_SOFT_I2C5
RT_USING_SOFT_I2C5？ 
请提供一个当前测试的bsp的修改。

2023-08-15 11:12 UTC, supperthomas requested changes

2023-08-15 11:12 UTC, supperthomas commented on components/drivers/Kconfig
> +				comment "Notice: PA00 --> 0x00; PA01 --> 0x01"
这个需要考虑所有bsp平台，有些不叫PA00 ，可以全部用数字代替。

2023-08-16 01:51 UTC, sp-cai commented on components/drivers/Kconfig
> +				comment "Notice: PA00 --> 0x00; PA01 --> 0x01"
10进制与16进制比较都是数字，对于程序员来说16进制用起来更方便，
注释写 PA00 对于有些BSP平台是不对，也不知道怎样改，没有完美的方案，我认为应该删除。

2023-08-16 01:56 UTC, supperthomas commented on components/drivers/Kconfig
> +				comment "Notice: PA00 --> 0x00; PA01 --> 0x01"
嗯，删除就好了，建议用十进制，大部分人用十进制，应该尽量降低使用门槛。

2023-08-16 02:05 UTC, sp-cai commented on components/drivers/i2c/soft_i2c.c
> +    #ifdef RT_USING_SOFT_I2C5
考虑到硬件是从 I2C1 开始的，所以就这样设定了，这个名字是可以在 menuconfig 中修改的，
如果这样不好，说一下我马上改。

2023-08-16 02:16 UTC, sp-cai commented on components/drivers/include/drivers/i2c.h
> +    rt_uint16_t  retries;
一个操作的重试次数没必要用32位数值，16位数值更有利于字节对齐。
这个修改探讨一下

2023-08-16 02:17 UTC, supperthomas requested changes

2023-08-16 02:17 UTC, supperthomas commented on components/drivers/include/drivers/i2c.h
> +    rt_uint16_t  retries;
你在哪里用到这个变量了？

2023-08-16 02:22 UTC, sp-cai commented on components/drivers/include/drivers/i2c.h
> +    rt_uint16_t  retries;
见 i2c-bit-ops.c 这个文件用到的

2023-08-16 02:23 UTC, sp-cai commented on components/drivers/Kconfig
> +				comment "Notice: PA00 --> 0x00; PA01 --> 0x01"
已删除了

2023-08-16 02:26 UTC, sp-cai commented on components/drivers/Kconfig
> +		config RT_USING_SOFT_I2C5
不用修改 BSP，直接可用

2023-08-16 02:26 UTC, supperthomas commented on components/drivers/include/drivers/i2c.h
> +    rt_uint16_t  retries;
哦，你改了下位置。

2023-08-16 02:36 UTC, sp-cai commented on components/drivers/include/drivers/i2c.h
> +    rt_uint16_t  retries;
是的

2023-08-16 02:39 UTC, supperthomas commented on components/drivers/i2c/soft_i2c.c
> +    #ifdef RT_USING_SOFT_I2C5
RT_USING_SOFT 有这个前缀，bsp可以自行选择，可以把所有I2C1-4都加上，

2023-08-16 02:40 UTC, supperthomas requested changes

2023-08-16 02:40 UTC, supperthomas commented on components/drivers/Kconfig
> +					range 0x00 0xFF
这里还是建议用十进制的。方便书写。

2023-08-16 02:43 UTC, supperthomas commented on components/drivers/include/drivers/i2c.h
> +    rt_uint32_t len;
这里改的目的是？

2023-08-16 02:49 UTC, sp-cai commented on components/drivers/include/drivers/i2c.h
> +    rt_uint32_t len;
16位最大只能读写64KB数据，有时是不够用的

2023-08-16 02:50 UTC, sp-cai commented on components/drivers/i2c/soft_i2c.c
> +    #ifdef RT_USING_SOFT_I2C5
已经加上

2023-08-16 03:15 UTC, sp-cai commented on components/drivers/Kconfig
> +					range 0x00 0xFF
已改好

2023-08-16 03:24 UTC, supperthomas approved these changes

2023-08-16 04:29 UTC, supperthomas requested changes

2023-08-16 04:29 UTC, supperthomas commented on components/drivers/i2c/soft_i2c.c
> +#if defined(RT_USING_SOFT_I2C5) || defined(RT_USING_SOFT_I2C6)||\
RT_USING_SOFT_I2C1?

2023-08-16 04:31 UTC, supperthomas commented
请参考 https://club.rt-thread.org/ask/article/419a30e57384a239.html 。 验证打下开宏的权限和各个bsp编译情况。
https://club.rt-thread.org/ask/article/8e019d0e64e1ab31.html
或者也可以在你的仓库中添加权限，supperthomas。我可以帮你操作。
如何添加参考：https://club.rt-thread.org/ask/article/248b674840ae736a.html

2023-08-16 04:36 UTC, sp-cai commented on components/drivers/i2c/soft_i2c.c
> +#if defined(RT_USING_SOFT_I2C5) || defined(RT_USING_SOFT_I2C6)||\
已更正

2023-08-16 06:37 UTC, supperthomas requested changes

2023-08-16 06:37 UTC, supperthomas commented on components/drivers/Kconfig
> +            default n
这里可以加一个default y 默认至少加一个。

2023-08-16 06:42 UTC, sp-cai commented on components/drivers/Kconfig
> +            default n
已加，另外仓库已开放权限

2023-08-16 06:55 UTC, supperthomas approved these changes

2023-08-16 07:28 UTC, supperthomas requested changes

2023-08-16 07:28 UTC, supperthomas commented on components/drivers/include/drivers/i2c.h
> +rt_inline rt_err_t rt_i2c_bus_lock(struct rt_i2c_bus_device *bus, rt_int32_t timeout)
这里为什么改？

2023-08-16 07:59 UTC, sp-cai commented on components/drivers/include/drivers/i2c.h
> +rt_inline rt_err_t rt_i2c_bus_lock(struct rt_i2c_bus_device *bus, rt_int32_t timeout)
保持与 rt_mutex_take 一致，支持 RT_WAITING_FOREVER

2023-08-16 08:16 UTC, supperthomas approved these changes

2023-08-16 08:17 UTC, supperthomas commented
i2c.h 不建议修改。

2023-08-17 01:29 UTC, sp-cai commented
> 

文件 i2c.h 的更改是很谨慎的，已检索过所有代码确认是完全兼容的且无不良影响才改的。
其实此修改与本 PR 主题无关，可以独立 PR，要不要撤销此文件的修改，然后重开一个 PR 讨论？
请回复我马上改

2023-08-17 09:25 UTC, supperthomas commented
i2c.h可以另外提PR

2023-08-17 09:38 UTC, sp-cai commented
> i2c.h可以另外提PR

好的，已改好

2023-08-22 04:16 UTC, supperthomas commented
@Guozhanxin

2023-08-24 01:29 UTC, sp-cai commented
@mysterywolf @Guozhanxin

2023-08-24 22:32 UTC, mysterywolf commented
请耐心等待一下 这个PR还在决策怎么合入比较好

2023-10-17 15:24 UTC, mysterywolf approved these changes

2023-10-17 15:24 UTC, merged

2023-10-21 16:31 UTC, meng-plus commented
kconfig 处使用问题反馈与建议
https://github.com/RT-Thread/rt-thread/blob/feature/air32f103cct6/components/drivers/Kconfig#L146-L163
``` python
config RT_SOFT_I2C1_SCL_PIN
                    int "SCL pin number"
                    range 0 32767
                    default 1
                config RT_SOFT_I2C1_SDA_PIN
                    int "SDA pin number"
                    range 0 32767
                    default 2
```
pin引脚配置项采用的 int 类型 这样不方便引脚标号写入，建议更换为hex 方式更加友好
```python
config RT_SOFT_I2C1_SCL_PIN
                    hex "SCL pin number"
                    range 0x00 0xFF
                    default 1
                config RT_SOFT_I2C1_SDA_PIN
                    hex "SDA pin number"
                    range 0x00 0xFF
                    default 2
```

2023-10-22 11:55 UTC, sp-cai commented
> kconfig 处使用问题反馈与建议 https://github.com/RT-Thread/rt-thread/blob/feature/air32f103cct6/components/drivers/Kconfig#L146-L163
> 
> ```python
> config RT_SOFT_I2C1_SCL_PIN
>                     int "SCL pin number"
>                     range 0 32767
>                     default 1
>                 config RT_SOFT_I2C1_SDA_PIN
>                     int "SDA pin number"
>                     range 0 32767
>                     default 2
> ```
> 
> pin引脚配置项采用的 int 类型 这样不方便引脚标号写入，建议更换为hex 方式更加友好
> 
> ```python
> config RT_SOFT_I2C1_SCL_PIN
>                     hex "SCL pin number"
>                     range 0x00 0xFF
>                     default 1
>                 config RT_SOFT_I2C1_SDA_PIN
>                     hex "SDA pin number"
>                     range 0x00 0xFF
>                     default 2
> ```

这个问题已讨论过，见上面有关 components/drivers/Kconfig 的讨论记录。