[ktime] fix wrong time
RT-Thread/rt-thread pull request #7870
Opened 2023-07-26 07:25 UTC by xqyjlj

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

1. 因为tick从中断到设置中间的时延特别大，在1Ghz的平台上每2小时就有差不多5s的误差，因此暂不采用tick做基准时间，直接取gtime的cnt做基准时间，
2. 修复hdtime在smart场景ctrlc异常的bug

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-26 14:19 UTC, mysterywolf commented
ktime可否加个readme?

2023-07-27 02:18 UTC, xqyjlj commented
> ktime可否加个readme?

已

2023-07-27 02:29 UTC, mysterywolf requested changes

2023-07-27 02:29 UTC, mysterywolf commented on components/ktime/src/aarch64/cputimer.c
> +static unsigned long _init_cnt = 0;
```suggestion
static volatile unsigned long _init_cnt = 0;
```

2023-07-27 02:30 UTC, mysterywolf commented
可否以函数注册的方式代替弱函数，并不是所有工具链都支持弱函数的方式的。 @Guozhanxin 郭老师意见如何

2023-07-27 02:39 UTC, xqyjlj commented
> 可否以函数注册的方式代替弱函数，并不是所有工具链都支持弱函数的方式的。

目前这个组件几乎只有smart场景才能用到，smart的工具链都是支持weak的，改成ops之后还得增加一些NULL的判断

2023-07-27 03:09 UTC, mysterywolf commented
我还是建议是用.函数指针的方式：
1. 一个是因为weak工具链支持的问题，这个组件已经触碰到RTC以及libc/time了，不只是服务于smart这么简单，文档中也写了，可以服务于除smart之外的bsp，比如stm32.
2. 还有用户对接的问题，使用weak函数会让用户感觉莫名其妙，因为我看这个readme我并不理解我需要对接哪些函数上去。

另外是不需要判断为空的，默认函数指针对接的就是你写好的weak函数，用户在重新设置函数指针（即根据bsp进行适配的时候）的时候会在设置阶段就判空，如果用户将函数指针指向了一个NULL，设置直接失败。也就是确保函数指针永远指向一个可用的函数。

2023-07-27 03:22 UTC, geniusgogo commented
> 我还是建议是用.函数指针的方式：
> 
> 1. 一个是因为weak工具链支持的问题，这个组件已经触碰到RTC以及libc/time了，不只是服务于smart这么简单，文档中也写了，可以服务于除smart之外的bsp，比如stm32.
> 2. 还有用户对接的问题，使用weak函数会让用户感觉莫名其妙，因为我看这个readme我并不理解我需要对接哪些函数上去。
> 3. 不符合rt-thread的组件/设备框架的设计思想，如果后续组件借鉴采用weak函数方案蹦来蹦去的话就麻烦了。
> 
> 另外是不需要判断为空的，默认函数指针对接的就是你写好的weak函数，用户在重新设置函数指针（即根据bsp进行适配的时候）的时候会在设置阶段就判空，如果用户将函数指针指向了一个NULL，设置直接失败。也就是确保函数指针永远指向一个可用的函数。
> 
> 当然，我没有实际以你实际实现的角度来考虑，如果在实现过程中，函数指针的方式如果并不适用，请指出。一家之言。@Guozhanxin 郭老师也看看

还是挺有道理的，这块是可以抽象层一套通用的object出来的。
不过目前能从0到1已经很不错了，可以计划1.1再优化一下。

2023-07-27 03:25 UTC, mysterywolf commented
> 不过目前能从0到1已经很不错了，可以计划1.1再优化一下。

如果后续考虑抽象成函数指针的方式那我这个PR没有问题的。

2023-07-27 03:25 UTC, mysterywolf approved these changes

2023-07-27 03:34 UTC, Guozhanxin approved these changes

2023-07-27 03:35 UTC, merged