Add the system call epoll
RT-Thread/rt-thread pull request #7893
Opened 2023-07-30 12:34 UTC by zmq810150896

## 拉取/合并请求描述：(PR description)

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-31 15:56 UTC, BernardXiong requested changes

2023-07-31 15:56 UTC, BernardXiong commented on components/libc/posix/io/epoll/epoll.c
> +struct rt_rdllist
这个的全称是？需要给出全称的注释

2023-07-31 15:56 UTC, BernardXiong commented on components/libc/posix/io/epoll/epoll.c
> +static int epoll_epf_init(int fd)
epf的全称是？

2023-07-31 15:56 UTC, BernardXiong commented on components/libc/posix/io/epoll/epoll.c
> +    level = rt_hw_interrupt_disable();
不再建议使用`rt_hw_interrupt_disable`函数了，可以使用mutex显式的锁，或者使用`rt_spin_lock_irqsave/rt_spin_unlock_irqrestore`函数。

2023-07-31 15:56 UTC, BernardXiong commented on components/libc/posix/io/epoll/epoll.c
> +    return do_epoll_wait(epfd, events, maxevents, timeout, ss);
几个函数更建议改成：
* epoll_do_wait
* epoll_do_ctrl
* epoll_do_create

2023-07-31 15:56 UTC, BernardXiong commented on components/libc/posix/io/epoll/epoll.c
> +    struct rt_rdllist *next;
是否`rt_ready_list`更合理？

2023-07-31 15:56 UTC, BernardXiong commented on components/libc/posix/io/epoll/epoll.c
> +        return -1;
尽可能单出口：
```c
static int epoll_ctl_mod(struct dfs_file *df ,struct epoll_event *event)
{
    rt_err_t ret = 0;
    struct rt_fd_list *fdlist;
    struct rt_eventpoll *ep = RT_NULL;

    if (df->vnode && df->vnode->data)
    {
        ep = df->vnode->data;

        fdlist = ep->fdlist;
        while (fdlist->next != RT_NULL)
        {
            if (fdlist->next->epev.data.fd == event->data.fd)
            {
                fdlist->next->epev.events = event->events;
                fdlist->next->revents = event->events;
                rt_wqueue_remove(&fdlist->next->wqn);
                epoll_ctl_install(fdlist->next, ep);
                break;
            }
    
            fdlist = fdlist->next;
        }
    }
    else
    {
        ret = -1;
    }

    return ret;
}
```

2023-07-31 22:12 UTC, mysterywolf commented
这个可以在mcu下面跑起来吗？这个配置项MCU即不开启smart也是可以选择开启的

2023-08-01 01:29 UTC, zmq810150896 commented on components/libc/posix/io/epoll/epoll.c
> +    level = rt_hw_interrupt_disable();
那使用 rt_spin_lock_irqsave/rt_spin_unlock_irqrestore 。 mutex 的话，如果被高优先级进行中断，可能会造成问题。

2023-08-01 01:34 UTC, zmq810150896 commented on components/libc/posix/io/epoll/epoll.c
> +    return do_epoll_wait(epfd, events, maxevents, timeout, ss);
好的

2023-08-01 01:35 UTC, zmq810150896 commented
>

2023-08-01 01:35 UTC, closed without merging

2023-08-01 01:54 UTC, zmq810150896 commented on components/libc/posix/io/epoll/epoll.c
> +static int epoll_epf_init(int fd)
eventpoll file

2023-08-01 09:09 UTC, BernardXiong approved these changes