Prepare some api for DM
RT-Thread/rt-thread pull request #7894
Opened 2023-07-31 03:51 UTC by GuEe-GUI

## 拉取/合并请求描述：(PR description)

[
1. Fixup:Arch Kconfig empty in MCU
2. AArch64:cpuport:replace rt_inline with macros
3. Components:MM:add early map api
4. Kernel:service add some STDC string ops

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-07-31 06:20 UTC, GuEe-GUI commented
@mysterywolf

2023-07-31 16:11 UTC, BernardXiong commented on include/rtthread.h
> +char *rt_strchr(const char *s, int c);
不建议无限期的扩大化了

2023-07-31 22:01 UTC, mysterywolf commented on include/rtthread.h
> +char *rt_strchr(const char *s, int c);
可以考虑加上，有RT_KSERVICE_USING_STDLIB罩着，这个宏正常情况都是关闭的

2023-07-31 22:11 UTC, mysterywolf commented on include/rtthread.h
> +char *rt_strchr(const char *s, int c);
确实，这块很容易可能无限扩充下去，这个本应该是libc的责任。

@GuEe-GUI 如果这些函数标准C库可以直接使用的话，直接#include <string.h>吧

2023-08-01 01:31 UTC, mysterywolf requested changes

2023-08-01 01:31 UTC, mysterywolf commented on libcpu/aarch64/Kconfig
> +menu "RT-Thread Architecture"
```suggestion
menu "AArch64 Architecture Configuration"
```

2023-08-01 01:32 UTC, mysterywolf commented on components/drivers/ofw/irq.c
> +     * In fact, amost no SoC will be use multi ic to implemented INTx.
单词拼写有误

2023-08-01 01:33 UTC, GuEe-GUI commented on components/drivers/ofw/irq.c
> +     * In fact, amost no SoC will be use multi ic to implemented INTx.
almost？

2023-08-01 01:37 UTC, mysterywolf approved these changes

2023-08-01 03:54 UTC, GuEe-GUI commented
@BernardXiong

2023-08-02 01:44 UTC, mysterywolf approved these changes

2023-08-02 04:48 UTC, BernardXiong approved these changes

2023-08-02 04:48 UTC, merged