[bsp][stm32][rt-spark] 更新 cubemx ports
RT-Thread/rt-thread pull request #7939
Opened 2023-08-10 07:02 UTC by zhkag

## 拉取/合并请求描述：(PR description)

[
测试 温湿度 光线传感器 网络 LCD 开启即可使用，无需其他配置（修改引脚等）
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-10 07:06 UTC, Guozhanxin commented on bsp/stm32/stm32f407-rt-spark/Kconfig
> -source "$PKGS_DIR/Kconfig"
这里为啥要改，这样软件包就变到最底部了吧

2023-08-10 07:14 UTC, supperthomas requested changes

2023-08-10 07:14 UTC, supperthomas commented on bsp/stm32/stm32f407-rt-spark/board/Kconfig
> +    config BSP_USING_COM2
BSP_USING_COM2？

2023-08-10 07:14 UTC, supperthomas commented on bsp/stm32/stm32f407-rt-spark/board/Kconfig
> +    config BSP_USING_COM3
BSP_USING_COM2
？

2023-08-10 07:14 UTC, supperthomas commented on bsp/stm32/stm32f407-rt-spark/board/ports/pm/drv_pm.c
> + * Date           Author       Notes
license

2023-08-10 07:14 UTC, supperthomas commented on bsp/stm32/stm32f407-rt-spark/board/ports/rs485/drv_rs485.c
> + * 2023-05-05     yuanjie           add test method
license

2023-08-10 07:14 UTC, supperthomas commented on bsp/stm32/stm32f407-rt-spark/board/ports/audio/drv_es8388.c
> + * 2019-07-31     Zero-Free    first implementation
license

2023-08-10 07:17 UTC, zhkag commented on bsp/stm32/stm32f407-rt-spark/Kconfig
> -source "$PKGS_DIR/Kconfig"
是的，这样改的好处是 bsp 中的配置可以覆盖到软件包里的配置
例如 下面的这里 就会直接覆盖 rw007 中的默认参数，这样的话 用户在使用的时候 无需重新配置 spi 的参数 可以直接打开 BSP_USING_RW007_WLAN 就可以使用了
![image](https://github.com/RT-Thread/rt-thread/assets/62738223/5ad812fb-a72e-4226-b026-43ccc58bb4f2)

2023-08-10 07:18 UTC, zhkag commented on bsp/stm32/stm32f407-rt-spark/board/ports/pm/drv_pm.c
> + * Date           Author       Notes
我改一下 这里都是直接复制的 studio 里的

2023-08-10 07:18 UTC, zhkag commented on bsp/stm32/stm32f407-rt-spark/board/Kconfig
> +    config BSP_USING_COM2
复制的 studio 里的配置

2023-08-10 07:25 UTC, zhkag commented on bsp/stm32/stm32f407-rt-spark/board/ports/pm/drv_pm.c
> + * Date           Author       Notes
许可证是对的啊

2023-08-10 07:41 UTC, supperthomas approved these changes

2023-08-11 01:43 UTC, Guozhanxin commented on bsp/stm32/stm32f407-rt-spark/Kconfig
> -source "$PKGS_DIR/Kconfig"
但是，这么会报错吧。有警告没

2023-08-14 01:21 UTC, zhkag commented on bsp/stm32/stm32f407-rt-spark/Kconfig
> -source "$PKGS_DIR/Kconfig"
没啥警告，Kconfig 支持这种写法

2023-08-14 05:55 UTC, merged