[smart] Replace irq disable/enable codes in futex
RT-Thread/rt-thread pull request #7941
Opened 2023-08-11 02:22 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-12 03:00 UTC, BernardXiong requested changes

2023-08-12 03:00 UTC, BernardXiong commented on src/kservice.c
> +            rt_backtrace();
建议加hook吧

2023-08-12 03:14 UTC, polarvid commented on src/kservice.c
> +            rt_backtrace();
就是用 weak 实现一个类似 hook 的东西。因为原先 arm/aarch64 都有实现 `rt_backtrace()`，感觉可以作为一个可选的 rt_service。这样通用的代码也可以调用，但是也可以不选择实现。

2023-08-12 06:15 UTC, mysterywolf commented on src/kservice.c
> +            rt_backtrace();
rt_hw_backtrace

2023-08-12 06:18 UTC, mysterywolf commented on include/rtthread.h
> +void rt_backtrace(void);
@polarvid 可以放在rt_hw_cpu_shutdown声明的旁边，建议放在rtthread.h里否则包含头文件可能会出现问题

2023-08-12 06:21 UTC, polarvid commented on src/kservice.c
> +            rt_backtrace();
rt_hw_backtrace 这个原先已经存在了一个非 compatible 定义的在 rtdef.h 里

2023-08-12 16:42 UTC, mysterywolf commented on src/kservice.c
> +            rt_backtrace();
可否统一一下这两个函数，到时候会搞乱的，最后统一使用rt_hw_backtrace

2023-08-14 01:17 UTC, polarvid commented on src/kservice.c
> +            rt_backtrace();
这两个 API 语义还是有区别的。一个是对指定栈帧的 backtrace 操作，另一个是对当前的。感觉还有得有一个 rt_backtrace 提供架构无关的 backtrace 服务。

2023-08-17 02:28 UTC, polarvid commented on src/kservice.c
> +            rt_backtrace();
现在给了两个 API：`rt_hw_backtrace()` & `rt_hw_backtrace_self()`。self 只是包装了一下 `rt_hw_backtrace()`。提供self是考虑到实现的简便性。因为打印当前调用栈 backtrace 的场景还是比较普遍的，每个都写一串这种代码反而很乱。

2023-08-17 02:32 UTC, mysterywolf commented on src/kservice.c
> +            rt_backtrace();
嗷嗷

2023-08-17 02:34 UTC, mysterywolf commented on libcpu/aarch64/common/backtrace.c
> +int rt_hw_backtrace_uthread(rt_thread_t thread)
rt_hw_xxx 一般是通用的，在kservice.c中声明一个weak函数，在rthw.h中对外暴露。属于rthw层级的，不要在libcpu层级也搞一堆rt_hw_xxx的定义出来，libcpu层级一般是为了覆盖kservice的弱函数

2023-08-17 02:35 UTC, mysterywolf commented on src/kservice.c
> +    LOG_D("%s() doesn't support for this architecture", __func__);
```suggestion
    LOG_W("%s() doesn't support for this architecture", __func__);
```

2023-08-17 02:44 UTC, polarvid commented on libcpu/aarch64/common/backtrace.c
> +int rt_hw_backtrace_uthread(rt_thread_t thread)
libcpu 下面有一些独有的 API, 这些之前都是加了 rt_hw_ 前缀的。如果考虑说 rt_hw 只出现在 rthw.h，那么还是要规定一下 libcpu 私有 API 的命名的。

2023-08-17 02:46 UTC, mysterywolf commented on libcpu/aarch64/common/backtrace.c
> +int rt_hw_backtrace_uthread(rt_thread_t thread)
是的 现在是注意到有这类问题了，所以最好规范一下接口，做成通用的.

2023-08-17 02:48 UTC, polarvid commented on libcpu/aarch64/common/backtrace.c
> +int rt_hw_backtrace_uthread(rt_thread_t thread)
好的。单说这里的话，也考虑搞成通用的吧

2023-08-17 02:51 UTC, mysterywolf commented on libcpu/aarch64/common/backtrace.c
> +int rt_hw_backtrace_uthread(rt_thread_t thread)
是的 最好是能搞成通用的，能通用就通用 命名能统一就统一。否则随着时间的流逝，世间万物都逃不过熵增定律。过几年之后，如果没有统一的接口，就会冒出来五花八门的接口。软件的可持续演进也是现在需要提前构思的。

2023-08-17 02:52 UTC, polarvid commented on libcpu/aarch64/common/backtrace.c
> +int rt_hw_backtrace_uthread(rt_thread_t thread)
赞同

2023-08-20 01:37 UTC, BernardXiong requested changes

2023-08-20 01:37 UTC, BernardXiong commented on components/lwp/lwp_internal.c
> +#define DBG_LVL DBG_LOG
这里默认就是`DBG_LOG` 级别的，是否应该默认关闭这部分的？

2023-08-20 01:37 UTC, BernardXiong commented on components/lwp/lwp_internal.c
> +            rt_hw_backtrace_self();
这里需要直接进行backtrace吗？或者这类属于BUG了？

2023-08-20 01:37 UTC, BernardXiong commented on components/lwp/lwp_internal.h
> +#ifndef RT_USING_DEBUG
感觉是否单独有份LWP_DEBUG的定义会更好些，这样不会受限于全局的RT_USING_DEBUG？

2023-08-20 01:37 UTC, BernardXiong commented on components/lwp/lwp_pmutex.c
> +#include "lwp_internal.h"
这里的`lwp_internal.h` 本身又是和`RT_USING_DEBUG`相关的，这样的话在internal.h中的定义就不见得起作用了。

2023-08-23 06:09 UTC, geniusgogo commented on components/lwp/lwp_futex.c
> +                    time = 0;
小于0的情况应该是一个非常大的数？ 

我看Linux上针对这种情况都是当成forever来处理？

2023-09-03 13:49 UTC, BernardXiong commented
这个PR能把它结掉吧， @geniusgogo @polarvid

2023-09-25 08:50 UTC, polarvid commented
关联 PR #8084 

本 PR 中除 futex 的修改已经拆分，分别包含如下 PR

- backtrace [todo]
- mutex #7972 
- signal #7998

2023-09-25 09:09 UTC, polarvid commented on components/lwp/lwp_internal.c
> +            rt_hw_backtrace_self();
属于 bug。这里加 backtrace 是因为 bug 是后面的逻辑里面，在 `_rt_mutex_take()` 里面检查的。但是检查后就直接异常了，没有 backtrace 信息，所以提前打出来。

不过后续在 backtrace PR 打算换成在 assert 通过配置开启 backtrace

2023-10-12 02:36 UTC, polarvid commented on components/lwp/lwp_futex.c
> +                    time = 0;
按照手册，小于 0 需要返回错误。

另外这个 timeout 设置也有问题。这里的算法把 timeout 当作绝对值，但是手册上说明是相对值。不过这个 PR 先不改逻辑了。下个 PR 处理。

2023-10-12 09:33 UTC, geniusgogo approved these changes

2023-10-13 07:58 UTC, polarvid commented on components/lwp/lwp_pmutex.c
> +#include "lwp_internal.h"
增加了一个 LWP_DEBUG 配置项

2023-10-14 05:07 UTC, BernardXiong approved these changes

2023-10-14 05:07 UTC, merged