[components][i2c]add general soft i2c
RT-Thread/rt-thread pull request #7953
Opened 2023-08-14 16:54 UTC by Z8MAN8

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-14 23:21 UTC, supperthomas commented
https://club.rt-thread.org/ask/article/419a30e57384a239.html

请用CI 手动检查下该配置，
提供链接。

2023-08-14 23:21 UTC, supperthomas requested changes

2023-08-14 23:21 UTC, supperthomas commented on components/drivers/i2c/i2c_soft.c
> +int rt_hw_i2c_init(void)
这个函数名字可以和soft稍微关联一下。

2023-08-15 06:44 UTC, supperthomas requested changes

2023-08-15 06:44 UTC, supperthomas commented on bsp/raspberry-pico/libraries/Kconfig
> +        if RT_USING_SOFT_I2C
感觉这个KCONFIG 开关可以放在components/drivers/kconfig里面。 引脚范围可以宽一点
个数可以多一些，I2C1-I2C4

2023-08-15 06:45 UTC, supperthomas requested changes

2023-08-15 06:45 UTC, supperthomas commented on bsp/raspberry-pico/libraries/Kconfig
>                  default n
这边可以加一个default y 默认打开第一个。

2023-08-16 00:30 UTC, mysterywolf commented on bsp/raspberry-pico/libraries/Kconfig
>                  default n
不赞成 这个是有BSP那侧的Kconfig 来select的 例如BSP_USING_SOFT_I2C宏会select 这个宏

2023-08-16 00:31 UTC, mysterywolf commented on components/drivers/i2c/i2c_soft.c
> +int rt_hw_i2c_init(void)
赞成

2023-08-16 00:31 UTC, mysterywolf commented on bsp/raspberry-pico/libraries/Kconfig
> +        if RT_USING_SOFT_I2C
这个地方的宏用BSP_USING_ ，  BSP_USING 再选 RT_USING 软件模拟驱动

2023-08-16 00:33 UTC, mysterywolf commented on components/drivers/i2c/i2c_soft.c
> +    .udelay   = rt_hw_us_delay, //TODO: use rt us delay
把.udelay这个方法去掉，直接用rt_hw_us_delay就行

2023-08-16 01:52 UTC, supperthomas commented on bsp/raspberry-pico/libraries/Kconfig
>                  default n
> 不赞成 这个是有BSP那侧的Kconfig 来select的 例如BSP_USING_SOFT_I2C宏会select 这个宏

这个不是bsp那侧吗？

2023-10-18 01:36 UTC, Guozhanxin commented
这个是不是可以关闭了？

2023-10-18 03:44 UTC, closed without merging