[bsp][gd32]添加 立创开发板 GD32F470 的 SDRAM驱动，从STM32的drv_sdram.c修改而来
RT-Thread/rt-thread pull request #7965
Opened 2023-08-20 14:32 UTC by zihao-yuan

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

增加立创 梁山派开发板的SDRAM驱动

#### 你的解决方案是什么 (what is your solution)

从仿造ART-PI的SDRAM驱动添加SDRAM驱动

#### 在什么测试环境下测试通过 (what is the test environment)

实际开发板测试通过
![image](https://github.com/RT-Thread/rt-thread/assets/41323019/fd186db5-c85f-4c87-a4ea-32a48186d1a3)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-20 16:31 UTC, mysterywolf requested changes

2023-08-20 16:31 UTC, mysterywolf commented on bsp/gd32/arm/gd32470z-lckfb/board/board.c
> +#if defined(RT_USING_HEAP)
这个位置使用BSP_USING_SDRAM 不用改

2023-08-20 16:31 UTC, mysterywolf commented on bsp/gd32/arm/gd32470z-lckfb/board/board.c
> +#if defined(RT_USING_HEAP)
bsp使用BPS_USING一级的宏，如果stm32 有这个问题 请麻烦改一下

2023-08-20 17:03 UTC, zihao-yuan commented on bsp/gd32/arm/gd32470z-lckfb/board/board.c
> +#if defined(RT_USING_HEAP)
原先的宏定义是如果定义了外部sdram那么堆就使用外部的，我觉得堆还是要优先使用内部的。
`#if defined(RT_USING_HEAP)`使用这个是因为我看artpi和最近新出的星火一号在`void rt_hw_board_init(void)`中都是用这个宏定义的。感觉应该不用改，毕竟这个堆的初始化也算得上RT_USING 级别的吧。
![image](https://github.com/RT-Thread/rt-thread/assets/41323019/32f19cab-569b-447f-b469-93598bb1cd45)

2023-08-20 17:04 UTC, mysterywolf commented on bsp/gd32/arm/gd32470z-lckfb/board/board.c
> +#if defined(RT_USING_HEAP)
嗯嗯 有道理

2023-08-20 17:04 UTC, mysterywolf approved these changes

2023-08-21 03:35 UTC, mysterywolf approved these changes

2023-08-21 03:47 UTC, merged