[bsp][stm32][driver] Add bsp support for stm32f405zgtx series, and add the drv_i2c.c for stm32
RT-Thread/rt-thread pull request #7971
Opened 2023-08-22 18:51 UTC by Donocean

## 拉取/合并请求描述：(PR description)

[

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
并确认并列出已经在什么情况或板卡上进行了测试。

#### 为什么提交这份PR (why to submit this PR)

添加了 stm32f405zgtx 系列 bsp的支持，**初步实现（无dma）**了硬件i2c驱动

- [x] 提交BSP开发板
- [x] 提交SPI IIC 修复和验证
- [x] i2c: 目前i2c 还没有和stm32的硬件I2C对接上rt-thread的驱动，添加drv_i2c.c

https://github.com/RT-Thread/rt-thread/issues/5968

#### 你的解决方案是什么 (what is your solution)

根据教程制作bsp，并在板子上测试通过，添加了关于硬件i2c的驱动程序，并测试驱动eeprom和oled成功

#### 在什么测试环境下测试通过 (what is the test environment)
在自己个人的板子上即 `stm32f405zgt6` 测试通过
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-22 18:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7971) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=7971) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=7971) it.</sub>

2023-08-22 22:08 UTC, mysterywolf commented
感谢提交PR  请将对IIC的改动都拆出来 作为一个独立的PR 谢谢

2023-08-23 05:14 UTC, Donocean commented
> 感谢提交PR 请将对IIC的改动都拆出来 作为一个独立的PR 谢谢

已暂时删除对i2c的改动

2023-08-23 22:48 UTC, supperthomas requested changes

2023-08-23 22:48 UTC, supperthomas commented on bsp/stm32/stm32f405zgtx/board/CubeMX_Config/Src/stm32f4xx_it.c
> +  HAL_UART_IRQHandler(&huart1);
这个也可以删了

2023-08-24 02:06 UTC, mysterywolf commented
非常棒 感谢提交PR
@Guozhanxin @supperthomas 麻烦看一下bsp的名字有没有什么修改意见，我觉得有些不妥，但是这个bsp属于自己设计的最小系统，没有官方名称。但是另一方面，这个最小系统也有参考意义，可以方便用户基于此bsp魔改出自己的bsp。建议收录 但是名字需要考虑一下。

@Donocean 关于名字你有什么好想法，可以参考一下stm32其他bsp的命名规则

2023-08-24 02:39 UTC, Donocean commented
> @Guozhanxin @supperthomas 麻烦看一下bsp的名字有没有什么修改意见，我觉得有些不妥，但是这个bsp属于自己设计的最小系统，没有官方名称。但是另一方面，这个最小系统也有参考意义，可以方便用户基于此bsp魔改出自己的bsp。建议收录 但是名字需要考虑一下。

参考其他stm32的命名规则，改名为stm32f405zgtx-template怎么样

2023-08-24 02:59 UTC, mysterywolf commented
@Guozhanxin @supperthomas stm32f405zg-mini-template 这个名字怎么样

2023-08-24 05:43 UTC, Guozhanxin commented
> 

我感觉这个不错

2023-08-24 06:23 UTC, supperthomas commented
可以

2023-08-24 07:48 UTC, Donocean commented
好的，那我这边就更改bsp名称提交了

2023-08-24 16:56 UTC, mysterywolf approved these changes

2023-08-24 16:57 UTC, merged

2023-08-24 20:53 UTC, mysterywolf commented
感谢提交PR