[bsp][stm32] 为BearPi支持lpuart1外设
RT-Thread/rt-thread pull request #7975
Opened 2023-08-23 14:04 UTC by liYony

## 拉取/合并请求描述：(PR description)

[
为stm32l431-BearPi开发板支持lpuart1外设。为后续实现stm32l431-BearPi连接华为云做准备。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-23 22:32 UTC, supperthomas requested changes

2023-08-23 22:32 UTC, supperthomas commented on bsp/stm32/stm32l431-BearPi/board/CubeMX_Config/Inc/main.h
> +
?

2023-08-24 00:21 UTC, liYony commented
cubemx 直接生成的





------------------ 原始邮件 ------------------
发件人: Supper Thomas ***@***.***&gt;
发送时间: 2023年8月24日 06:33
收件人: RT-Thread/rt-thread ***@***.***&gt;
抄送: liYangYang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [RT-Thread/rt-thread] [bsp][stm32] 为BearPi支持lpuart1外设 (PR #7975)





 
@supperthomas requested changes on this pull request.
 
 
In bsp/stm32/stm32l431-BearPi/board/CubeMX_Config/Inc/main.h:
 &gt; @@ -60,6 +60,7 @@ void Error_Handler(void);  /* USER CODE END EFP */    /* Private defines -----------------------------------------------------------*/ +  
?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-08-24 00:34 UTC, supperthomas commented
请提交你需要修改的文件即可。自动生成的不影响使用的，可以不用提交。

2023-08-24 00:35 UTC, liYony commented
好的





------------------ 原始邮件 ------------------
发件人: Supper Thomas ***@***.***&gt;
发送时间: 2023年8月24日 08:34
收件人: RT-Thread/rt-thread ***@***.***&gt;
抄送: liYangYang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [RT-Thread/rt-thread] [bsp][stm32] 为BearPi支持lpuart1外设 (PR #7975)

2023-08-24 02:07 UTC, mysterywolf commented on bsp/stm32/stm32l431-BearPi/board/CubeMX_Config/Inc/main.h
> +
这个应该是cubemx自动生成的吧 @liYony 检查一下 如果是自动生成的就直接提交上来就行，不必删除

2023-08-24 02:08 UTC, mysterywolf approved these changes

2023-08-24 02:09 UTC, merged