Add zynq7000 bsp
RT-Thread/rt-thread pull request #7976
Opened 2023-08-23 14:57 UTC by a1012112796

## 拉取/合并请求描述：(PR description)

基于之前 zynq7000 的bsp, 用 vivado 生成的驱动库重新适配一版 bsp, 测试效果:

![image](https://github.com/RT-Thread/rt-thread/assets/25342410/1b44e75b-8fed-4f4f-9ee2-8fa92593b9df)

----

![image](https://github.com/RT-Thread/rt-thread/assets/25342410/04c1f77a-240c-4a62-bbf2-51ecb5ea6e2f)

https://github.com/RT-Thread/rt-thread/assets/25342410/04feaba8-ffdc-4606-b6d1-277eccf68e75

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-24 02:11 UTC, mysterywolf commented
考虑创建个文件夹 别直接放在bsp根目录下 早年因为没有想到现在bsp数量这么多 有些直接散在bsp根目录下了。现在得用子文件夹控制一下，顺便也可以吧其他同类的都放在同一个子文件夹下。

2023-08-26 12:11 UTC, a1012112796 commented
> 考虑创建个文件夹 别直接放在bsp根目录下 早年因为没有想到现在bsp数量这么多 有些直接散在bsp根目录下了。现在得用子文件夹控制一下，顺便也可以吧其他同类的都放在同一个子文件夹下。

好像没有同类的吧。。。zynq7000系列芯片估计不需要再加别的bsp了，差异在 pl 上，bsp 是可以通用的。

2023-08-26 15:48 UTC, mysterywolf requested changes

2023-08-26 15:48 UTC, mysterywolf commented on bsp/zynq7000/drivers/zynq7000.h
> + */
此处信息不对

2023-08-26 15:48 UTC, mysterywolf commented on bsp/zynq7000/applications/app.c
> +#include "rtthread.h"
增加注释头

2023-08-26 15:48 UTC, mysterywolf commented
创建zynq文件夹 bsp位于：zynq/zynq7000

2023-08-30 01:51 UTC, Guozhanxin commented on bsp/zynq7000/drivers/zynq7000.h
> + *  You should have received a copy of the GNU General Public License along
GPL版权的不能合进来啊😂，这是从哪里拷贝过来的啊，可能要重构一下。

2023-08-30 05:47 UTC, BernardXiong commented on bsp/zynq7000/drivers/zynq7000.h
> + */
这个是要把商业版本的BSP转变成Apache许可版本的吗？ :cry:

2023-08-30 06:20 UTC, a1012112796 commented on bsp/zynq7000/drivers/zynq7000.h
> + *  You should have received a copy of the GNU General Public License along
Hmm, 是基于这个 bsp 的基础上做的 https://github.com/RT-Thread/rt-thread/blob/stable-v3.0.x/bsp/zynq7000/drivers/zynq7000.h, 后面我再看看吧，看看我能不能不依赖他，否则只能关pr 了。

2023-08-30 16:55 UTC, mysterywolf commented on bsp/zynq7000/drivers/zynq7000.h
> + *  You should have received a copy of the GNU General Public License along
我觉得这个可以直接改成阿帕奇吧  因为这个当时老的rtt 用的gpl 现在都转到阿帕奇了

2023-09-01 02:20 UTC, Guozhanxin commented on bsp/zynq7000/drivers/zynq7000.h
> + *  You should have received a copy of the GNU General Public License along
看起来这个BSP是之前迁移到公司仓库下的那套部分商业BSP里的：https://github.com/Real-Thread/bsp_zynq7000
所有这部分没有改为阿帕奇。

2023-09-01 12:48 UTC, a1012112796 commented on bsp/zynq7000/drivers/zynq7000.h
> + *  You should have received a copy of the GNU General Public License along
目前只有定时器驱动沿用了旧的逻辑代码，其余都是基于 vivado sdk 新写的，等我把定时器驱动重写一下，应该就和这个旧bsp 再无任何关系了。

2023-09-03 13:45 UTC, BernardXiong commented
还请提交正确的zynq bsp

2023-09-03 13:45 UTC, closed without merging

2023-09-05 11:33 UTC, a1012112796 commented on bsp/zynq7000/drivers/zynq7000.h
> + *  You should have received a copy of the GNU General Public License along
@BernardXiong @mysterywolf @Guozhanxin 已修改，具体变更任如下: https://github.com/a1012112796/rt-thread/commit/cd7d6dbdb4fff962752e4ec7c0bf2584c381845c