[msh]Optimize list_thread display
RT-Thread/rt-thread pull request #7977
Opened 2023-08-24 03:16 UTC by Guozhanxin

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-24 03:34 UTC, mysterywolf approved these changes

2023-08-24 23:34 UTC, BernardXiong commented
address，是什么？或者给个全一些的，sp addr？

2023-08-25 08:00 UTC, supperthomas approved these changes

2023-08-25 14:25 UTC, Guozhanxin commented
> address，是什么？或者给个全一些的，sp addr？

就是tcb的地址

2023-08-25 22:00 UTC, mysterywolf commented
我觉得叫addr可以的 如果多引入一个tcb 用户会蒙 因为rt-thread并没有直接提起过TCB这个概念。

2023-08-25 23:40 UTC, BernardXiong commented
> > address，是什么？或者给个全一些的，sp addr？
> 
> 就是tcb的地址

为什么会有TCB的地址？如果确实需要这样，可以直接写tcb addr

2023-08-25 23:40 UTC, BernardXiong commented
> 我觉得叫addr可以的 如果多引入一个tcb 用户会蒙 因为rt-thread并没有直接提起过TCB这个概念。

直接addr太懵了，addr可以是一切

2023-08-26 03:08 UTC, armink commented
是，支持 tcb addr

另外

- 堆栈大小能不能搞成 10 机制，比如：16KB，512B ，看着更加直观
- 堆栈大小放在 max used 左右，用户一般从左往右阅读，期望先看到最大使用
- SP 也移动到最右边去，不常用

2023-08-28 03:04 UTC, Guozhanxin commented
> 

堆栈大小显示为xxKB，xxB，这个可能不太好调整。就怕有不对齐的情况。不好显示，比如1.05KB这种情况

其他的我支持。

2023-08-28 03:05 UTC, mysterywolf commented
> > 
> 
> 堆栈大小显示为xxKB，xxB，这个可能不太好调整。就怕有不对齐的情况。不好显示，比如1.05KB这种情况
> 
> 其他的我支持。

rt_kprintf默认不支持小数点 小数点可能得通过取余的方式人工处理一下

2023-09-03 13:47 UTC, BernardXiong commented
> 堆栈大小显示为xxKB，xxB，这个可能不太好调整。就怕有不对齐的情况。不好显示，比如1.05KB这种情况

可以是这样的：
* <1kB的，按字节；
* <1MB的，按kB；
* <1GB的，按MB；

这个时候也不需要按小数点方式了。

2023-09-07 10:21 UTC, xqyjlj commented
是不是也要适配一下64位的情况，64位地址长一些，打出来不能对齐有些难看

2023-10-21 12:18 UTC, BernardXiong commented
@Guozhanxin 做个调整，把`address` -> `tcb addr`；这样更清晰些。如果是其他相关的，能够更合理清晰些也都做份调整吧

2023-10-21 12:19 UTC, BernardXiong requested changes
`address` -> `tcb addr`;

2023-10-25 02:17 UTC, Guozhanxin commented
@BernardXiong 改好了

2023-10-27 02:52 UTC, BernardXiong approved these changes

2023-10-27 02:52 UTC, merged