[bsp][phytium] Add Phytium PI support
RT-Thread/rt-thread pull request #7984
Opened 2023-08-25 08:05 UTC by zhugengyu

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-08-25 08:43 UTC, supperthomas requested changes

2023-08-25 08:43 UTC, supperthomas commented on bsp/phytium/aarch64/.config
> +CONFIG_RT_USING_LWP=y
LWP 之前版本没用开，这个版本需要默认开吗？

2023-08-25 21:45 UTC, mysterywolf requested changes

2023-08-25 21:45 UTC, mysterywolf commented on include/rtatomic.h
> +//#include <rthw.h>
请确认这里

2023-08-25 23:37 UTC, BernardXiong commented on include/rtatomic.h
> +//#include <rthw.h>
需要给出理由，同时如果确实涉及到这里，请单独来PR，而不是混在BSP的PR中提交

2023-08-25 23:38 UTC, BernardXiong requested changes
非BSP相关的代码不要混合一起提交

2023-08-28 01:53 UTC, mysterywolf commented
建议是功能做到最小集，用户需要其他功能的时候再打开 而不是就直接全打开了。例如某功能可以在Kconfig里做好一键化开启开关，用户选择后会自动依赖相关功能。但是最好不要上来就把所有的功能都选上 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/board/Kconfig#L22

2023-08-28 01:57 UTC, zhugengyu commented
> 建议是功能做到最小集，用户需要其他功能的时候再打开 而不是就直接全打开了。例如某功能可以在Kconfig里做好一键化开启开关，用户选择后会自动依赖相关功能。但是最好不要上来就把所有的功能都选上 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/board/Kconfig#L22

2023-08-28 01:59 UTC, mysterywolf commented
> 建议是功能做到最小集，用户需要其他功能的时候再打开 而不是就直接全打开了。例如某功能可以在Kconfig里做好一键化开启开关，用户选择后会自动依赖相关功能。但是最好不要上来就把所有的功能都选上 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/board/Kconfig#L22

这个只是个建议  不是强制要求 你根据你自己bsp的实际情况来进行选择 是否采取我的建议

2023-08-28 01:59 UTC, zhugengyu commented
> 建议是功能做到最小集，用户需要其他功能的时候再打开 而不是就直接全打开了。例如某功能可以在Kconfig里做好一键化开启开关，用户选择后会自动依赖相关功能。但是最好不要上来就把所有的功能都选上 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/board/Kconfig#L22

后续有这个计划，Phytium Standalone SDK 正在按板子做最小功能集合，等那边发布了，再同步到 RT-Thread BSP 来

2023-08-28 02:00 UTC, mysterywolf commented
OK

2023-08-28 03:02 UTC, mysterywolf approved these changes

2023-08-29 02:23 UTC, BernardXiong commented
从新提交下吧，`-f`方式提交还是什么的，不希望留下`rtatomic.h`修改的记录。

2023-08-29 02:25 UTC, mysterywolf commented
这个我来处理就好了

2023-08-29 02:27 UTC, merged