[BSP/rockchip/rk3568] fixup heapmem init flow
RT-Thread/rt-thread pull request #8038
Opened 2023-09-15 01:59 UTC by GuEe-GUI

## 拉取/合并请求描述：(PR description)

[
In RT-Smart, `rt_hw_interrupt_init` will call `rt_ioremap` to map GIC's MMIO registers. There is a `rt_malloc` called in rt_ioremap, that will fail if we not init the mem heap yet.
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-16 04:27 UTC, mysterywolf requested changes

2023-09-16 04:27 UTC, mysterywolf commented on bsp/rockchip/rk3568/driver/board.c
>      rt_kprintf("heap: [0x%08x - 0x%08x]\n", RT_HW_HEAP_BEGIN, RT_HW_HEAP_END);
为啥不把这个printf也移上去呀，建议用LOG_I代替rt_kprintf, rt_kprintf仅用于用户交互场景

2023-09-16 10:01 UTC, BernardXiong approved these changes

2023-09-19 02:13 UTC, GuEe-GUI commented on bsp/rockchip/rk3568/driver/board.c
>      rt_kprintf("heap: [0x%08x - 0x%08x]\n", RT_HW_HEAP_BEGIN, RT_HW_HEAP_END);
因为串口还没初始化

2023-09-19 02:27 UTC, mysterywolf approved these changes

2023-09-19 02:27 UTC, merged