🎈 perf: perf rt_hw_interrupt_disable/enable
RT-Thread/rt-thread pull request #8042
Opened 2023-09-15 08:13 UTC by xqyjlj

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
优化调度器，优化大量大锁代码, RT_USING_SIGNALS 由于环境原因，目前暂未优化

#### 你的解决方案是什么 (what is your solution)
 

#### 在什么测试环境下测试通过 (what is the test environment)
arm64
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-16 01:20 UTC, mysterywolf commented
需要rebase一下代码 有冲突

2023-09-16 10:40 UTC, BernardXiong requested changes

2023-09-25 02:57 UTC, xqyjlj commented on include/rtdef.h
> +    rt_atomic_t                 counter;
引用计数，一种调试手段，目前先放这里吧，怕后面出现死锁故障不方便调试。后面可以删掉

2023-09-25 03:33 UTC, xqyjlj commented on components/drivers/include/drivers/serial.h
> +    struct rt_spinlock spinlock;
目前字段名都是统一叫spinlock的

2023-09-28 03:08 UTC, xqyjlj commented
要合并这个的话得先把shell那几个lwp的先合并了，这个得最后合并

2023-10-12 09:27 UTC, geniusgogo commented on components/drivers/include/drivers/serial.h
> +    struct rt_spinlock spinlock;
违背了rtt代码风格哲学——简单不失优雅

2023-10-14 05:05 UTC, BernardXiong commented
> 要合并这个的话得先把shell那几个lwp的先合并了，这个得最后合并

一个是需要解决代码冲突，另外前向需要合并的关联PR也列出来吧

2023-10-18 09:30 UTC, xqyjlj commented
> > 要合并这个的话得先把shell那几个lwp的先合并了，这个得最后合并
> 
> 一个是需要解决代码冲突，另外前向需要合并的关联PR也列出来吧

可以合并了

2023-10-19 08:36 UTC, Guozhanxin commented on components/drivers/ipc/waitqueue.c
> +    __wait.wqueue = queue;
这里是修复了什么bug吗

2023-10-19 08:38 UTC, xqyjlj commented on components/drivers/ipc/waitqueue.c
> +    __wait.wqueue = queue;
添加了一个queue专用的spinlock

2023-10-19 08:46 UTC, Guozhanxin commented on components/libc/compilers/common/ctime.c
>      _current_tz_offset_sec = offset_sec;
这种全局变量，不要保护了吗？

2023-10-19 08:48 UTC, xqyjlj commented on components/libc/compilers/common/ctime.c
>      _current_tz_offset_sec = offset_sec;
int32 数据赋值在对齐时本来就是原子的

2023-10-19 09:02 UTC, Guozhanxin commented on src/cpu.c
> +    lock->pc = (void *)0xbeafdead;
这里和下面的rt_spin_unlock_irqrestore实现正好是相反的，没问题吧？

2023-10-19 09:02 UTC, Guozhanxin commented on src/cpu.c
> +    lock->pc = (void *)0;
这里，和上面正好反着

2023-10-19 09:05 UTC, Guozhanxin commented on src/idle.c
> -    level = rt_hw_interrupt_disable();
这里的全局变量读写，不用保护了吗？

2023-10-19 09:05 UTC, xqyjlj commented on src/cpu.c
> +    lock->pc = (void *)0xbeafdead;
没问题的

2023-10-19 09:12 UTC, xqyjlj commented on src/idle.c
> -    level = rt_hw_interrupt_disable();
这个可能有点问题，下一个补丁修一下

2023-10-19 09:19 UTC, aozima commented on src/cpu.c
> +    lock->pc = (void *)0;
设置为 0xdeadbeaf 和 0的区别是什么？0xdeadbeaf 应该不会是个有效的owner，但最好能有个注释说明下。

2023-10-19 09:53 UTC, Guozhanxin commented on components/libc/compilers/common/ctime.c
>      _current_tz_offset_sec = offset_sec;
嗯，好像是的(๑•̀ㅂ•́)و✧

2023-10-19 09:54 UTC, Guozhanxin approved these changes

2023-10-20 05:23 UTC, BernardXiong requested changes
对于一些情况做些说明；对于counter的，希望都过一遍，大多数场合应该是atomic方式的，另外是名称，单独的counter意义比较单薄，是否有更好的名称，例如ref_count。

2023-10-20 05:23 UTC, BernardXiong commented on include/rtdef.h
>  #ifdef RT_USING_SMART
这地方不应该和smart相关联起来，而是单独的cpu统计

2023-10-20 05:23 UTC, BernardXiong commented on include/rtdef.h
> +
多余的空行

2023-10-20 05:23 UTC, BernardXiong commented on include/rtdef.h
>      rt_ubase_t                  init_tick;              /**< thread's initialized tick */
如果tick统一是atomic的，那么init_tick应该也是。

2023-10-20 05:23 UTC, BernardXiong commented on include/rtdef.h
> +    int                         tid_ref;                /**< reference of tid */
是refcount？如果是这样，建议名称上反馈出来，同时应该也是atomic的吧

2023-10-20 05:23 UTC, BernardXiong commented on include/rtdef.h
> +    rt_atomic_t                 counter;
那么应该给出清晰的注释，或在名称上也反映出来。

2023-10-20 05:23 UTC, BernardXiong commented on include/rtdef.h
> +    struct rt_spinlock   spinlock;
似乎前面每个object中会有一个spinlock，那么这里的是？还是两边可以共用一份？

2023-10-20 05:23 UTC, BernardXiong commented on include/rthw.h
> +    rt_ubase_t       cpu_counter[RT_CPUS_NR];
这部分代表的意义是？

2023-10-20 09:36 UTC, xqyjlj commented on include/rtdef.h
>  #ifdef RT_USING_SMART
这是牛头提的代码了，只是rebase的时候对齐了一下了，下一个版本可以考虑重新归类

2023-10-20 09:51 UTC, xqyjlj commented on include/rtdef.h
> +    struct rt_spinlock   spinlock;
rt_ipc_object 与 rt_object的结构体都没有内置spinlock，每个种类的ipc结构体都只有一个spinlock

2023-10-20 09:52 UTC, xqyjlj commented on include/rthw.h
> +    rt_ubase_t       cpu_counter[RT_CPUS_NR];
用来统计每个核下面单独的中断次数，前面的counter就不是很敢删，涉及到的bsp太多了

2023-10-20 09:53 UTC, xqyjlj commented on include/rtdef.h
>      rt_ubase_t                  init_tick;              /**< thread's initialized tick */
已

2023-10-20 09:54 UTC, xqyjlj commented on include/rtdef.h
> +    int                         tid_ref;                /**< reference of tid */
名称已修改，但是引用计数的修改已经是线程安全的了，没必要为了原子而原子

2023-10-21 06:20 UTC, xqyjlj commented
关于c++的原子类型，如果在c++中启用原子类型，那么

```c
#ifdef __cplusplus
#include <atomic> // atomic 要在extern "C" {前面，导致rtdef.h也不能被extern "C"包含
extern "C" {
#endif

typedef std::atomic<size_t> rt_atomic_t;
```

还有一种是c++的原子操作用硬件原子或者软件模拟原子替换，这样就是和c语言的一样的实现了

2023-10-22 14:44 UTC, xqyjlj commented
还有一种c++的原子类型兼容是把c++的原子通过宏重定向到软件原子或者硬件原子，undef 掉RT_USING_STDC_ATOMIC，这样就不会包含stdatomic.h引起编译报错了

2023-10-24 06:57 UTC, xqyjlj commented on src/cpu.c
> +    lock->pc = (void *)0;
owner在多核里面取的是current_thread，是有概率是NULL的，所以幻数不能是0

2023-10-24 07:25 UTC, skychen123 approved these changes

2023-10-24 07:27 UTC, skychen123 commented on include/rtdef.h
>  #ifdef RT_USING_SMART
已按意见修改

2023-10-25 11:42 UTC, BernardXiong approved these changes

2023-10-25 12:31 UTC, merged

2023-11-14 02:28 UTC, a1012112796 commented on src/timer.c
>              t->timeout_func(t->parameter);
个人还是不是很理解 `timeout_func` 前后恢复中断状态的方案，虽然它确实在理论上对提升实时性有很大帮助。个人理解，在遍历 `_timer_list` 的前后关中断，不就是为了确保其它线程或者中断环境不会对 `_timer_list` 做任何修改吗? 而此处开启中断， 但不出现问题，是否意味着其它线程或者中断环境可以在此阶段修改 `timer_list`, 遍历 `_timer_list` 的逻辑不会被影响? 那在这个函数中关中断的意义何在?

2023-11-16 09:11 UTC, xqyjlj commented on src/timer.c
>              t->timeout_func(t->parameter);
如果中断中使用了timer相关的api，是会修改timer_list，而且可能会插到链表前面去，造成漏掉一个时钟节拍。这个确实需要考虑。