Adapt rt_channel, increase the generality of some rt_channel functionality on dfs v2, and standardize signalfd
RT-Thread/rt-thread pull request #8047
Opened 2023-09-16 12:01 UTC by zmq810150896

#### 为什么提交这份PR (why to submit this PR)
适配 rt_channel 、 增加 rt_channel 在 dfs v2上一些功能的通用性，以及标准化 signalfd

#### 在什么测试环境下测试通过 (what is the test environment)
qemu-virt64-aarch64
### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-16 12:31 UTC, BernardXiong requested changes

2023-09-16 12:31 UTC, BernardXiong commented on components/libc/posix/io/signalfd/signalfd.c
> +#define SIGINFO_MAX 10
这些是否应该是Kconfig配置的

2023-09-16 12:31 UTC, BernardXiong commented on components/lwp/lwp_ipc.c
> +    return (void *)d;
建议对这个做一个完整的review，在dfsv2下是否还需要做更进一步适配。

2023-09-18 01:36 UTC, zmq810150896 commented on components/libc/posix/io/signalfd/signalfd.c
> +#define SIGINFO_MAX 10
这个是当一个进程同时触发了多个 signal 时，保存 signal 贡 read 的最大数量， 那我在 Kconfig 里加一下

2023-09-18 03:01 UTC, zmq810150896 commented on components/lwp/lwp_ipc.c
> +    return (void *)d;
fd 就 struct dfs_file 结构体的东西，只需要适配 struct dfs_file 结构体里的内容就行了。

2023-09-18 06:35 UTC, zmq810150896 commented on components/libc/posix/io/signalfd/signalfd.c
> +#define SIGINFO_MAX 10
我已经在Kconfig 里添加了，你再 review 一下

2023-09-19 02:19 UTC, geniusgogo approved these changes

2023-09-19 23:54 UTC, BernardXiong approved these changes

2023-09-19 23:54 UTC, merged