加入设备树的dump命令
RT-Thread/rt-thread pull request #8078
Opened 2023-09-24 12:28 UTC by fangjianzhou

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)

加入设备树的dump命令

#### 你的解决方案是什么 (what is your solution)

通过设备树的root结点，打印出整个设备树

#### 在什么测试环境下测试通过 (what is the test environment)

qemu-virt64-aarch64可以使用该命令
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-24 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8078) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8078) before we can accept your contribution.<br/><hr/>**fang jianzhou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8078) it.</sub>

2023-09-25 00:29 UTC, BernardXiong commented
先认真仔细看代码规范

2023-09-25 05:41 UTC, Guozhanxin commented on components/drivers/ofw/dump_dts.c
> +        rt_ofw_node_dump_dts(ofw_node_root,RT_TRUE);
`,` 后面要加空格的。我看都每加

2023-09-25 06:31 UTC, fangjianzhou commented on components/drivers/ofw/dump_dts.c
> +        rt_ofw_node_dump_dts(ofw_node_root,RT_TRUE);
我加一下，谢谢提醒

2023-09-26 05:25 UTC, Guozhanxin approved these changes

2023-09-26 05:25 UTC, Guozhanxin commented on components/drivers/ofw/dump_dts.c
> +static void dump_dts(int argc,char** argv)
```suggestion
static void dump_dts(int argc, char** argv)
```

2023-09-27 05:21 UTC, BernardXiong commented
文件名更改成dump.c吧

2023-09-27 05:24 UTC, fangjianzhou commented
好

2023-09-27 15:36 UTC, BernardXiong requested changes

2023-09-27 15:36 UTC, BernardXiong commented on components/drivers/ofw/dump.c
> +        rt_kprintf("\"/\" path not found.");
或者`no device tree found.`

2023-09-28 01:29 UTC, fangjianzhou commented on components/drivers/ofw/dump.c
> +        rt_kprintf("\"/\" path not found.");
我改一下

2023-09-28 02:52 UTC, zmshahaha commented
![image](https://github.com/RT-Thread/rt-thread/assets/85141075/1abdd7f4-ac3f-4b55-9837-3b58adfd2d03)

ofw.c里有dump 设备树的命令了，看看是不是有重复

2023-09-28 13:35 UTC, closed without merging

2023-09-28 13:35 UTC, BernardXiong commented
> ![image](https://user-images.githubusercontent.com/85141075/271161745-1abdd7f4-ac3f-4b55-9837-3b58adfd2d03.png)
> 
> ofw.c里有dump 设备树的命令了，看看是不是有重复

那基本上是重复了，这个PR将不进行合并。