串口设备框架serial_v2在utest下的testcases补充
RT-Thread/rt-thread pull request #8079
Opened 2023-09-24 16:28 UTC by zan319

update testcases and description

## 拉取/合并请求描述：(PR description)

[

更新并补充serial_v2的testcases, 新的测试样例统计并输出了了诸如丢包信息, 传输数据所需要的时钟周期等对性能有所体现的相关指标, 可以更加简便快捷地帮助移植serial_v2的使用者评估自己的移植是否出现问题以及能否正常使用该版本串口设备框架的基本功能 

#### 为什么提交这份PR (why to submit this PR)

在开源之夏中. 通过查阅资料, 为了serial_v2的改进工作编写了一些有关框架性能的测试

#### 你的解决方案是什么 (what is your solution)

使用utest_测试框架, 编写测试样例对serial_v2在不同应用层模式与硬件工作模式下的收发稳定性和效率做出测试

#### 在什么测试环境下测试通过 (what is the test environment)

在STM32L475潘多拉开发板上进行了测试

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-25 02:45 UTC, zhkag requested changes

2023-09-25 02:45 UTC, zhkag commented on examples/utest/testcases/drivers/serial_v2/uart_blocking_rx.c
> +#endif
结束加个换行吧

2023-09-25 02:45 UTC, zhkag commented on examples/utest/testcases/drivers/serial_v2/uart_blocking_tx.c
> +#endif
还有这里，下面的几个都检查一下

2023-09-25 03:23 UTC, zan319 commented on examples/utest/testcases/drivers/serial_v2/uart_blocking_tx.c
> +#endif
好的好的

2023-10-23 06:05 UTC, Guozhanxin approved these changes

2023-10-27 01:25 UTC, merged