MPU抽象层
RT-Thread/rt-thread pull request #8080
Opened 2023-09-25 00:35 UTC by tangzz98

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
为RT-Thread设计MPU抽象层，支持ARMV7-M，ARMV8-M架构，让用户使用MPU检测栈溢出等内存问题，实现线程内存隔离

#### 你的解决方案是什么 (what is your solution)
在`components/mp`目录下提供通用的API，`libcpu`目录下提供各处理器架构的具体实现

#### 在什么测试环境下测试通过 (what is the test environment)
在STM32U575 NUCLEO， STM32H75 NUCLEO开发板测试通过
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-25 00:43 UTC, BernardXiong commented on include/rtdef.h
> +#include <mptype.h>
内核头文件反向包含组件中的头文件；这部分需要仔细考虑好的

2023-09-25 00:43 UTC, BernardXiong commented on components/mp/mp.h
> +#ifndef __MP_H__
看看RTT的代码风格

2023-09-25 23:10 UTC, tangzz98 commented on include/rtdef.h
> +#include <mptype.h>
好的，我这两天改一下这边

2023-09-27 03:18 UTC, Guozhanxin commented
我基于stm32f407星火1号，做了测试，gcc和mdk ac6 都好使，功能没问题。

2023-09-27 03:21 UTC, Guozhanxin commented on components/mp/mpu_example_exclusive_region.c
> +    rt_mem_protection_add_exclusive_region((void *)thread1_private_data, MPU_MIN_REGION_SIZE);
添加个hook函数，可以把异常信息打印出来。

2023-09-27 03:21 UTC, Guozhanxin commented on components/mp/mpu_example_exclusive_region.c
> +MSH_CMD_EXPORT(mpu_example_exclusive_region, MPU example (exclusive_region));
这个MPU是宏，需要换个其他的描述，避开这个关键词。

2023-09-27 03:22 UTC, Guozhanxin commented on components/mp/mpu_example_ro_data.c
> +MSH_CMD_EXPORT(mpu_example_ro_data, MPU example (read-only data));
这些示例，可以在Kconfig里加个配置项，默认开启。

2023-09-27 06:42 UTC, a1012112796 commented
偶然想到对于 cortex-a 的芯片而言，是否可以用类似的方式使用mmu, 或者说把 mmu 当作 mpu 使用？

2023-09-29 04:35 UTC, tangzz98 commented
> 偶然想到对于 cortex-a 的芯片而言，是否可以用类似的方式使用mmu, 或者说把 mmu 当作 mpu 使用？

Zephyr就是这么做的，配置虚拟地址=物理地址

2023-10-11 01:31 UTC, BernardXiong requested changes
👍 总体来说非常棒，很多层面的东西都考虑到了。对于新组件来说，合并进来会需要一定时间，包括：
* 新组件命名，设计等方面的考虑。
* 新组件对其他的影响情况是什么；
* 新组件的文档情况；
* 新组件的测试用例等。

具体到这个PR，还请考虑 & 完善：
* 文档。因为涉及的点会有一些，包括对内核，对thread结构体的修改，文档上需要说明详细些；
* 风格命名 - 力求意义清晰，同时简洁明了；

2023-10-11 01:31 UTC, BernardXiong commented on components/Kconfig
> +source "$RTT_DIR/components/mp/Kconfig"
目录上建议，`mprotect`。m - 表示mem，protect表示这个是和内存保护相关。

2023-10-11 01:31 UTC, BernardXiong commented on components/mp/SConscript
> +if not GetDepend("USE_MEM_PROTECTION_EXAMPLES"):
examples，建议使用单独的`examples`目录

2023-10-11 01:31 UTC, BernardXiong commented on components/mp/mp.c
> +rt_mem_region_t *rt_mem_protection_find_free_region(rt_thread_t thread)
API名称上，建议使用`rt_mprotect_**` 。但是注释，全称上一定是protection，它是名词。

2023-10-11 01:31 UTC, BernardXiong commented on components/mp/mp.c
> +int rt_mem_protection_init(void)
是否应该做成自动初始化？以及`rt_hw_mp_init`也有一个weak函数。

2023-10-11 01:31 UTC, BernardXiong commented on components/mp/mp.c
> +        thread->mem_regions = RT_KERNEL_MALLOC(NUM_DYNAMIC_REGIONS * sizeof(rt_mem_region_t));
对于mpu来说，是不是应该每个线程都带NUM_MEM_REGIONS的regions？一般MPU都会有限制（而且还是很大的限制，例如对齐，例如大小等的），既然启用MPU，改成固定数量的regions是否更合适（特别是一些安全要求高的场合需要使用纯静态的内存管理方式，即没有malloc）

2023-10-11 01:31 UTC, BernardXiong commented on components/mp/mp.c
> +    return (int)rt_hw_mp_init();
对于底层的接口，可以更直接些，`rt_hw_mpu_init`。

2023-10-11 01:31 UTC, BernardXiong commented on libcpu/arm/cortex-m33/mpport.c
> +rt_err_t rt_hw_mp_add_region(rt_thread_t thread, rt_mem_region_t *region)
动态的方式总感觉不是一个太好的模式。或者说，一个thread可以提供一份自己的mpu table，`hw mpu`层只管去切换这个mpu table就好了。当然还有很重要一点，`hw mpu`层需要能够check这个mpu table的合理性，因为mpu限制太多。

2023-10-11 01:31 UTC, BernardXiong commented on src/idle.c
> +#else
这个地方是说，stack_buf、stack_addr二选一？

2023-10-11 03:53 UTC, tangzz98 commented on components/mp/mp.c
> +int rt_mem_protection_init(void)
这个已经做成自动初始化了。我觉得`rt_hw_mp_init`不需要有一个weak函数。只要处理器架构相同这个函数的实现都是一样的，不同bsp不会有区别。

2023-10-11 03:56 UTC, tangzz98 commented on components/mp/mp.c
> +    return (int)rt_hw_mp_init();
ARM架构内存保护单元叫MPU，RISC-V叫PMP。如果都取名`rt_hw_mpu`，后续如果支持RISC-V是否容易让人困惑？

2023-10-11 04:16 UTC, tangzz98 commented on components/mp/mp.c
> +        thread->mem_regions = RT_KERNEL_MALLOC(NUM_DYNAMIC_REGIONS * sizeof(rt_mem_region_t));
NUM_DYNAMIC_REGIONS是用户用kconfig配置的，每个线程的区域数量都是一样的。有的时候用户要配置静态的，应用于所有线程的MPU区域，所以线程的MPU区域数量不一定等于MPU区域的总数。这里用malloc的目的是只需要在rt_thread_t里存放一个`void *rt_mem_region_t`指针。否则要在rt_thread_t定义`rt_mem_region_t[NUM_REGIONS]`，导致要在内核头文件里引用组件头文件。

2023-10-11 04:20 UTC, tangzz98 commented on libcpu/arm/cortex-m33/mpport.c
> +rt_err_t rt_hw_mp_add_region(rt_thread_t thread, rt_mem_region_t *region)
比如在线程创建的时候就提供一个mpu table，之后线程运行过程中再也不会改变自己的mpu table？

2023-10-11 04:39 UTC, tangzz98 commented on src/idle.c
> +#else
因为MPU栈溢出检测实现的方式是像[这张图](https://github.com/tangzz98/rt-thread/blob/picture/components/mp/stack_guard.png)里，在原先为栈分配的内存首尾配置两个MPU区域，修改`stack_addr`指向MPU区域后可以操作的内存，这样其他代码可以对栈做正常的操作。`stack_buf`指向原先为栈分配的内存，确保线程删除时会free正确的地址。

2023-10-25 01:21 UTC, Guozhanxin approved these changes

2023-10-27 01:29 UTC, Guozhanxin commented
@BernardXiong 熊大，记得再看一下这个pr

2023-10-30 12:23 UTC, mysterywolf approved these changes

2023-10-30 12:24 UTC, merged

2024-01-09 09:56 UTC, muaxiaohei commented
MemManage_Handler 在 context_rvds.S 也已经定义，会产生重定义错误。
![image](https://github.com/RT-Thread/rt-thread/assets/45762837/7638de59-0214-4eb5-9188-30c5f0f6fea2)
期待大佬的解决与更新。