【msh】新增msh自动补全子选项特性
RT-Thread/rt-thread pull request #8086
Opened 2023-09-25 14:20 UTC by HelloByeAll

## 拉取/合并请求描述：(PR description)

[
新增msh自动补全子选项特性 

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested. -->

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-26 01:35 UTC, Guozhanxin commented on components/finsh/cmd.c
> +        case 0x100:
这里怎么还有一个，magic code

2023-09-26 01:37 UTC, Guozhanxin commented on components/finsh/finsh.h
> +/* MSH_CMD_EXPORT(command, desc) or MSH_CMD_EXPORT(command, desc, opt) */
看起来和之前是兼容的是吗？

2023-09-26 01:53 UTC, BernardXiong requested changes

2023-09-26 01:53 UTC, BernardXiong commented on components/finsh/cmd.c
> +        case 0x100:
做个宏定义吧，不应该出现绝对数值的。

2023-09-26 01:53 UTC, BernardXiong commented on components/finsh/Kconfig
> +    config FINSH_OPTION_COMPLETION_ENABLED
风格不统一了，用`FINSH_USING_OPTION_COMPLETION`吧

2023-09-26 01:53 UTC, BernardXiong commented on components/finsh/cmd.c
> +#ifndef FINSH_OPTION_COMPLETION_ENABLED
下面部分代码是否也可以做到统一，而不是完全函数级的条件宏控制

2023-09-26 01:53 UTC, BernardXiong commented on components/finsh/finsh.h
> +extern void msh_opt_list_dump(void *options);
头文件中函数声明不需要使用`extern`

2023-09-26 01:53 UTC, BernardXiong commented on components/finsh/shell.c
> +    msh_opt_auto_complete(prefix);
也许未来在auto complete方面，可以用链表插件的方式，可以在msh中一级级的挂载多中自动完成

2023-09-26 02:04 UTC, Guozhanxin approved these changes

2023-09-26 02:04 UTC, HelloByeAll commented on components/finsh/finsh.h
> +/* MSH_CMD_EXPORT(command, desc) or MSH_CMD_EXPORT(command, desc, opt) */
完全兼容

2023-09-26 02:05 UTC, HelloByeAll commented on components/finsh/cmd.c
> +        case 0x100:
和1102行配合使用的， 我弄个宏定义替换掉

2023-09-26 02:08 UTC, HelloByeAll commented on components/finsh/cmd.c
> +#ifndef FINSH_OPTION_COMPLETION_ENABLED
下面的处理中使用到了MSH_OPT_ID_GET这个宏，参数处理上简单了很多，与之前的方式是不一样的，做不到统一

2023-09-26 02:10 UTC, HelloByeAll commented on components/finsh/shell.c
> +    msh_opt_auto_complete(prefix);
之前考虑过这个， 在这套上面加链表改动很小就能实现，目前暂时用不到，所以只支持了二级

2023-09-26 02:23 UTC, HelloByeAll commented on components/finsh/cmd.c
> +#ifndef FINSH_OPTION_COMPLETION_ENABLED
把之前的处理方式改掉可以做到统一

2023-09-27 04:33 UTC, BernardXiong approved these changes

2023-09-27 04:34 UTC, merged

2023-11-26 14:15 UTC, mysterywolf commented
此修改造成bsp:simulator  VS编译不过，仿真器无法运行。