[bsp] Optimize the kconfig structure of ART-PI board about serial port
RT-Thread/rt-thread pull request #8101
Opened 2023-09-27 12:21 UTC by kurisaW

## 拉取/合并请求描述：(PR description)

[
原本的串口缓冲区buffer定义放在board.h中，不太方便用户查找和修改，在menuconfig中用户可直接进行配置
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-09-28 08:06 UTC, mcuxthomas requested changes

2023-09-28 08:06 UTC, mcuxthomas commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> +		            config BSP_UART1_TX_BUFSIZE
格式调整一下

2023-09-28 08:06 UTC, mcuxthomas commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> +				endif
格式

2023-09-28 09:55 UTC, kurisaW commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> +		            config BSP_UART1_TX_BUFSIZE
这块格式有什么问题嘛

2023-09-28 14:49 UTC, supperthomas requested changes

2023-09-28 14:49 UTC, supperthomas commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> +					config BSP_UART1_RX_USING_DMA
这里缩进可以调整一下

2023-09-28 15:50 UTC, kurisaW commented on bsp/stm32/stm32h750-artpi/board/Kconfig
> +		            config BSP_UART1_TX_BUFSIZE
之前我这边从网页版查看是没问题的，这次换了个format工具试了下，看看还有这种问题吗

2023-09-29 01:49 UTC, supperthomas approved these changes

2023-10-02 08:28 UTC, supperthomas approved these changes

2023-10-02 08:28 UTC, merged