Fixed issues with timerfd
RT-Thread/rt-thread pull request #8102
Opened 2023-09-28 05:14 UTC by zmq810150896

#### 为什么提交这份PR (why to submit this PR)
修复在用户态获取当前时间之后，调用到内核态再次获取当前时间，两边差值为负数，定时器不会运行的问题、

#### 在什么测试环境下测试通过 (what is the test environment)
qemu-virt64-aarch64

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-08 05:49 UTC, BernardXiong requested changes
从名称上来说，`timerfd_create_do`可以更改成`timerfd_do_create`

2023-10-08 05:49 UTC, BernardXiong commented on components/libc/posix/io/timerfd/timerfd.c
> +            ret = rt_thread_suspend_with_flag(tfd->timerfd_thread, RT_INTERRUPTIBLE);
这里会需要关中断？

2023-10-08 05:49 UTC, BernardXiong commented on components/libc/posix/io/timerfd/timerfd.c
> +        tfd->ticks = 0;
这里有mutex的lock，也可以考虑atomic原子操作。

2023-10-08 05:50 UTC, BernardXiong commented
`rt_thread_t timerfd_thread;` 也可以考虑更改成`tid` 或 `owner_thread`。另外，对于fd操作需要多考虑到互斥性

2023-10-08 06:15 UTC, zhkag commented on components/libc/posix/io/timerfd/timerfd.c
> +    rt_thread_resume(tfd->timerfd_thread);
这块和上面一行代码貌似是重复的 rt_wqueue_wakeup 里边是有 rt_thread_resume 操作的 timerfd_thread 似乎是没有必要的，

2023-10-08 08:46 UTC, zmq810150896 commented on components/libc/posix/io/timerfd/timerfd.c
> +    rt_thread_resume(tfd->timerfd_thread);
这一部分如果不调用 rt_wqueue_add 添加 rt_wqueue_node， 就不会调到 rt_thread_resume 操作，我加个 rt_wqueue_node 吧！这样就可以了。

2023-10-08 09:21 UTC, zmq810150896 commented on components/libc/posix/io/timerfd/timerfd.c
> +        tfd->ticks = 0;
好，我加上原子操作

2023-10-08 09:22 UTC, zmq810150896 commented on components/libc/posix/io/timerfd/timerfd.c
> +            ret = rt_thread_suspend_with_flag(tfd->timerfd_thread, RT_INTERRUPTIBLE);
也不需要，我删掉

2023-10-09 00:29 UTC, BernardXiong commented
给出更多的测试用例吧

2023-10-09 01:23 UTC, zhkag commented
utest 那边有办法加这个的测试用例吗？ 有的话加上

2023-10-10 06:59 UTC, zmq810150896 commented
> 给出更多的测试用例吧
测试用例后面上传到测试仓库
> utest 那边有办法加这个的测试用例吗？ 有的话加上
应该是可以加的，后面看看能不能加上

2023-10-12 08:57 UTC, geniusgogo approved these changes

2023-10-13 11:20 UTC, BernardXiong approved these changes

2023-10-13 11:20 UTC, merged