Sync dfs lwp
RT-Thread/rt-thread pull request #8123
Opened 2023-10-12 03:56 UTC by geniusgogo

## 拉取/合并请求描述：(PR description)

[
    同步内核、文件系统等差异
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-12 08:52 UTC, BernardXiong requested changes
对于单核/多核，请做个反复确认。

2023-10-12 09:01 UTC, geniusgogo commented on include/rtdef.h
> +    struct rt_cpu_usage_stats cpu_stat;
关于cpu_stat以及下文的争对单核多核的考量，这部分无需严格区分，因为从某个角度来看的话，单核是多核的一个特例。
也就是说在这部分场景下，可以理解位1个核的SMP模式。

2023-10-12 09:01 UTC, geniusgogo commented on include/rtdef.h
> +    struct rt_cpu_usage_stats cpu_stat;
关于cpu_stat以及下文的针对单核多核的考量，这部分无需严格区分，因为从某个角度来看的话，单核是多核的一个特例。
也就是说在这部分场景下，可以理解位1个核的SMP模式。

2023-10-12 09:07 UTC, geniusgogo commented on src/cpu.c
> -#ifdef RT_USING_SMP
单核也需要_cpus的定义，例如top命令需要统计cpu的使用率等信息

2023-10-12 12:51 UTC, polarvid commented on src/thread.c
> +#endif
放到 268 行是否会规整一点

2023-10-13 11:43 UTC, BernardXiong commented on include/rtdef.h
> +    struct rt_cpu_usage_stats cpu_stat;
不会的，MCU单核上还不是走的这样的情况

2023-10-16 03:03 UTC, polarvid approved these changes

2023-10-16 03:10 UTC, Guozhanxin commented on components/dfs/dfs_v1/include/dfs_file.h
> +    struct rt_lwp *lwp;
这里要有宏隔离吧，如果不开启lwp，这里会不会报错。

2023-10-16 03:15 UTC, Guozhanxin commented on components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
> +    rt_mutex_take(&file->vnode->lock, RT_WAITING_FOREVER);
这种锁是不是由框架提供个宏比较好，类似下面的。
```
DFS_VNODE_LOCK(&file);
DFS_VNODE_UNLOCK(&file);
```

2023-10-16 03:16 UTC, Guozhanxin commented on components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
> +    if(file->vnode->ref_count == 1)
这里是否会存在竞争啊

2023-10-16 03:16 UTC, Guozhanxin commented on components/dfs/dfs_v2/include/dfs_file.h
> +    struct rt_lwp *lwp;
这个也是，不一定所有的bsp都开启了lwp

2023-10-16 03:17 UTC, geniusgogo commented on components/dfs/dfs_v1/include/dfs_file.h
> +    struct rt_lwp *lwp;
CI没过？哈哈

2023-10-16 03:37 UTC, geniusgogo commented on components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
> +    if(file->vnode->ref_count == 1)
dfs层已经有锁了

2023-10-16 04:08 UTC, geniusgogo commented on components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
> +    rt_mutex_take(&file->vnode->lock, RT_WAITING_FOREVER);
当前dfs没这么做

2023-10-16 04:08 UTC, geniusgogo commented on components/dfs/dfs_v2/include/dfs_file.h
> +    struct rt_lwp *lwp;
已经加了

2023-10-16 04:08 UTC, geniusgogo commented on components/dfs/dfs_v1/include/dfs_file.h
> +    struct rt_lwp *lwp;
已经加了

2023-10-16 06:56 UTC, BernardXiong commented
PR做个拆分吧，把CPU数相关的从dfs、lwp的PR中拆分出来吧

2023-10-16 07:13 UTC, geniusgogo commented
> PR做个拆分吧，把CPU数相关的从dfs、lwp的PR中拆分出来吧

嗯，cpu.c 这部分已经还原了

2023-10-16 07:25 UTC, geniusgogo commented on include/rtdef.h
> +    struct rt_cpu_usage_stats cpu_stat;
已经还原

2023-10-16 07:25 UTC, geniusgogo commented on include/rtthread.h
> -#define rt_spin_lock_init(lock)                 /* nothing */
已经还原

2023-10-16 07:25 UTC, geniusgogo commented on src/cpu.c
> -#ifdef RT_USING_SMP
已经还原

2023-10-16 07:29 UTC, Guozhanxin approved these changes

2023-10-17 01:53 UTC, BernardXiong requested changes
对CPU代码细致些

2023-10-17 01:53 UTC, BernardXiong commented on components/dfs/Kconfig
> +            default 4096
这些名称不应该是这样的，可以是，
- `RT_USING_PAGECACHE` - 清晰明了
- `RT_PAGECACHE_ASPACE_COUNT` - 这个是一个整数配置，而不是一个是否使用的配置。
- `RT_PAGECACHE_GC_WATERLEVEL` - 触发GC的水位

2023-10-17 01:53 UTC, BernardXiong commented on components/mm/mm_page.c
> +        rt_kprintf("ok! ALLOC CNT %ld\n", _alloc_cnt);
这部分的打印是？如果有打印，也应该是LOG_D/E的方式。

2023-10-17 01:53 UTC, BernardXiong commented on src/cpu.c
> +#ifdef RT_USING_SMP
建议是`RT_USING_SMP`对整个文件进行框定，这样代码中就不会出现这么多的SMP相关的条件宏。然后spinlock相关的，在头文件中处理好即可。

2023-10-17 01:53 UTC, BernardXiong commented on src/idle.c
> +        pcpu->idle_thread = &idle_thread[i];
`rt_cpu_index(i)->idle_thread = &idle_thread[i];`

2023-10-17 01:55 UTC, polarvid commented on components/mm/mm_page.c
> +        rt_kprintf("ok! ALLOC CNT %ld\n", _alloc_cnt);
这个是个 msh 的调试命令，所以用了 rt_kprintf

2023-10-17 02:12 UTC, geniusgogo commented on components/mm/mm_page.c
> +        rt_kprintf("ok! ALLOC CNT %ld\n", _alloc_cnt);
MSH命令的打印，改成LOG_RAW

2023-10-17 02:15 UTC, geniusgogo commented on components/dfs/Kconfig
> +            default 4096
RT_USING_PCACHE_ASPACE_COUNT->RT_PAGECACHE_ASPACE_COUNT 是整数配置

2023-10-17 05:07 UTC, BernardXiong approved these changes

2023-10-17 05:08 UTC, merged