add sys_utimensat
RT-Thread/rt-thread pull request #8124
Opened 2023-10-12 06:16 UTC by xiao-mang

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

The lack of sys_utimensat implementation results in an error in the 'touch' command

#### 你的解决方案是什么 (what is your solution)

add sys_utimensat

#### 在什么测试环境下测试通过 (what is the test environment)

qemu aarch64
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-12 06:51 UTC, xqyjlj commented
需要对接tv_nsec ，参考标准 https://man7.org/linux/man-pages/man2/utimensat.2.html

```
If the tv_nsec field of one of the timespec structures has the
special value UTIME_NOW, then the corresponding file timestamp is
set to the current time.  If the tv_nsec field of one of the
timespec structures has the special value UTIME_OMIT, then the
corresponding file timestamp is left unchanged.  In both of these
cases, the value of the corresponding tv_sec field is ignored.
```

2023-10-12 08:29 UTC, geniusgogo commented on components/dfs/dfs_v2/include/dfs_fs.h
> +	struct timespec ia_mtime;
tab健

2023-10-12 08:33 UTC, geniusgogo commented on components/lwp/lwp_syscall.c
> +    SYSCALL_SIGN(sys_utimensat),
这个系统调用号，没办法和工具链对应起来啊，工具链那边少了个sys_setitimer?

2023-10-12 08:55 UTC, geniusgogo requested changes

2023-10-12 08:55 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs_posix.c
> +#ifndef GET_ERRNO
GET_ERRNO、SYS_WARP都是属于syscall的wrapper层负责的事情，不应该出现在其它地方。

2023-10-12 09:45 UTC, geniusgogo approved these changes

2023-10-12 09:51 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs_posix.c
> +    attr.ia_valid = ATTR_ATIME_SET | ATTR_MTIME_SET;
这种flag会在什么地方解析判断呢？

2023-10-12 11:23 UTC, xiao-mang commented on components/dfs/dfs_v2/src/dfs_posix.c
> +    attr.ia_valid = ATTR_ATIME_SET | ATTR_MTIME_SET;
ext4/ports/rtthread/dfs_ext.c的dfs_ext_setattr函数

2023-10-12 12:12 UTC, geniusgogo approved these changes

2023-10-13 11:21 UTC, BernardXiong approved these changes

2023-10-13 11:21 UTC, merged