fix ash echo
RT-Thread/rt-thread pull request #8150
Opened 2023-10-18 03:50 UTC by xiao-mang

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

The return value of ioctl for F_DUPFD_CLOEXEC has an error.

#### 你的解决方案是什么 (what is your solution)

Add case F_DUPFD_CLOEXEC, and return correct value.

#### 在什么测试环境下测试通过 (what is the test environment)

qemu aarch64
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-18 09:16 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs_file.c
> +#define F_DUPFD_CLOEXEC 1030
不应该出现在这个地方

2023-10-19 01:37 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs_file.c
>          case F_SETLKW:
参照这些宏定义的地方

2023-10-19 01:38 UTC, geniusgogo commented on components/libc/compilers/musl/fcntl.h
> +#ifndef F_DUPFD_CLOEXEC
musl库里本身就有无需重新定义

2023-10-19 03:14 UTC, geniusgogo requested changes

2023-10-19 03:14 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs_file.c
> +        case F_DUPFD_CLOEXEC:
只对SMART生效就好了

2023-10-20 05:59 UTC, geniusgogo approved these changes

2023-10-21 00:41 UTC, BernardXiong approved these changes

2023-10-21 00:41 UTC, merged