[smart] Support of KASAN
RT-Thread/rt-thread pull request #8160
Opened 2023-10-19 10:10 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-20 03:38 UTC, geniusgogo approved these changes

2023-10-24 07:08 UTC, polarvid commented
我把宏定义从这个 PR 去掉吧

2023-10-28 04:59 UTC, polarvid commented
这个 PR 已经是 READY 的状态了哈。

2023-10-30 15:22 UTC, BernardXiong requested changes
把代码写的精致也是一份十分关键的能力、手段，干预，涉及的面越少越好，这样也能保持代码的清晰化。

2023-10-30 15:22 UTC, BernardXiong commented on src/kservice.c
> +void rt_malloc_set_rc_hook(void (*hook)(void **ptr, rt_size_t size))
rc的意思是？需要注释中说明，同时也包括尽可能减少hook量。

2023-10-30 15:22 UTC, BernardXiong commented on src/Kconfig
> +config RT_USING_KASAN
并没看到KASAN的功能

2023-10-30 15:22 UTC, BernardXiong commented on libcpu/aarch64/common/cpuport.h
> +    __asm__ volatile (
这部分的意义是什么？这种情况下是为了支持哪类编译器？

2023-10-30 15:22 UTC, BernardXiong commented on libcpu/aarch64/common/backtrace.c
> +    PTR_NORMALIZE(fp);
是否也应该是hook？

2023-10-30 15:22 UTC, BernardXiong commented on include/rtdef.h
> +#define rt_optimize(level)          __attribute__((optimize("O"#level)))
这类方式就变成仅GCC有效，不建议以这样方式处理。或者这类应该在有限的，单独的地方来使用。例如和自己工程相关的地方，而不是扩散到整个系统

2023-10-30 15:22 UTC, BernardXiong commented on tools/building.py
> +    if GetDepend('RT_USING_KASAN'):
应该还是在需要使用KASAN的地方来使用。例如可以存在一个软件包，这个软件是和KASAN相关的，那么使用这个软件包的时候，则加入相关编译选项，参数

2023-12-22 07:22 UTC, polarvid commented on libcpu/aarch64/common/backtrace.c
> +    PTR_NORMALIZE(fp);
改为条件编译的宏了

2023-12-22 07:24 UTC, polarvid commented on libcpu/aarch64/common/cpuport.h
> +    __asm__ volatile (
下面的汇编是通用的。GCC 下交给编译器生成会合适一些。因为 armv8 几个版本 (8.1, 8.2 ……) ，支持的指令集是不同的。编译器可以根据具体的 cpu 特性，生成优化后的机器指令。

2023-12-22 09:34 UTC, polarvid commented
CI 本地循环跑了好久，没发现有啥问题。

![image](https://github.com/RT-Thread/rt-thread/assets/65584760/c94e128d-096b-4345-b00b-0c418e2701f1)

2023-12-30 08:03 UTC, BernardXiong approved these changes

2023-12-30 08:04 UTC, BernardXiong commented
Please resolve conflicts:

> Conflicting files
> src/kservice.c

Thanks.

2023-12-30 10:59 UTC, mysterywolf approved these changes

2024-01-02 11:42 UTC, merged