update elmfat from r14b to r15
RT-Thread/rt-thread pull request #8179
Opened 2023-10-24 12:33 UTC by xiao-mang

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

update elmfat from r14b to r15

#### 你的解决方案是什么 (what is your solution)

update elmfat from r14b to r15

#### 在什么测试环境下测试通过 (what is the test environment)

A1000
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-24 13:13 UTC, mysterywolf commented
我记得之前对fatfs 的ff.c有过一点修改 不知道更新的时候是否也一同带过来了

2023-10-25 01:19 UTC, Guozhanxin approved these changes

2023-10-25 01:19 UTC, Guozhanxin commented
> 我记得之前对fatfs 的ff.c有过一点修改 不知道更新的时候是否也一同带过来了

我大体过了遍，感觉没啥问题

2023-10-25 02:45 UTC, geniusgogo requested changes

2023-10-25 02:45 UTC, geniusgogo commented on components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
> +    mutex = rt_mutex_create("mmutex", RT_IPC_FLAG_PRIO);
这里的名字，如果讲究一点的话，也可以类似与像上面这样手动拼一个名字，在较多实例的时候可以方便清楚看到对象的目标。如果这样的话，会看到多个对象都是相同的名字

2023-10-25 02:45 UTC, geniusgogo commented on components/dfs/dfs_v2/filesystems/elmfat/ff.c
> +				fno->fattrib = AM_DIR;//miao
这个注释是啥意思？

2023-10-25 02:58 UTC, xiao-mang commented on components/dfs/dfs_v2/filesystems/elmfat/ff.c
> +				fno->fattrib = AM_DIR;//miao
升级过程中，疑问点的一个标记，忘记删掉了。在f_stat函数中，官方的FATFS R14b，R15，这里都是赋值的FR_INVALID_NAME，只有我们的R14b版本是AM_DIR。
#define AM_DIR	0x10	/* Directory */
FR_INVALID_NAME,		/* (6) The path name format is invalid */

2023-10-25 05:58 UTC, geniusgogo requested changes

2023-10-25 05:58 UTC, geniusgogo commented on components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
> +    mutex = rt_mutex_create("name", RT_IPC_FLAG_PRIO);
这里name写错了吧？

2023-10-25 06:00 UTC, geniusgogo commented on components/dfs/dfs_v2/filesystems/elmfat/ff.c
> +				fno->fattrib = AM_DIR;//miao
> 升级过程中，疑问点的一个标记，忘记删掉了。在f_stat函数中，官方的FATFS R14b，R15，这里都是赋值的FR_INVALID_NAME，只有我们的R14b版本是AM_DIR。 #define AM_DIR 0x10 /* Directory _/ FR_INVALID_NAME, /_ (6) The path name format is invalid */

可以看git的提交记录谁修改的

2023-10-26 02:06 UTC, geniusgogo approved these changes

2023-10-26 09:26 UTC, merged