[ctime] fixup of data racing
RT-Thread/rt-thread pull request #8187
Opened 2023-10-25 11:19 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-25 12:03 UTC, geniusgogo requested changes

2023-10-25 12:03 UTC, geniusgogo commented on components/libc/compilers/common/ctime.c
>          return -1; /* todo:memory leak */
返回之前没释放锁

2023-10-25 12:03 UTC, geniusgogo commented on components/libc/compilers/common/ctime.c
>      if (_g_timerid[ktimerid] == NULL)
判断之前加锁

2023-10-25 12:03 UTC, geniusgogo commented on include/rthw.h
> +#ifndef RT_HW_SPIN_LOCK_INIT
这个宏是否与__RT_HW_SPIN_LOCK_INITIALIZER重叠？

2023-10-25 12:03 UTC, geniusgogo commented on include/rtthread.h
> +rt_inline void rt_spin_lock_init(lock)                  {RT_UNUSED(lock);}
貌似这一块代码要这么改的话都可以改成do while(0)

2023-10-25 12:10 UTC, polarvid commented on include/rthw.h
> +#ifndef RT_HW_SPIN_LOCK_INIT
不重叠，那边是 rt_hw_spin_lock_t

2023-10-25 12:11 UTC, polarvid commented on include/rtthread.h
> +rt_inline void rt_spin_lock_init(lock)                  {RT_UNUSED(lock);}
有些 API 需要返回值，内嵌函数是比较合理的。宏的话需要 GNU C。

2023-10-25 12:15 UTC, polarvid commented on components/libc/compilers/common/ctime.c
>      if (_g_timerid[ktimerid] == NULL)
这里本质上不是冲突区。这个锁保护的冲突区是 resource id 的数组。所以这里加锁没有意义。另外它这里还有 return，加锁又得多加一行 unlock，平白无故增加了不必要的代码。

2023-10-25 12:22 UTC, polarvid commented on include/rthw.h
> +#ifndef RT_HW_SPIN_LOCK_INIT
spin_lock_t 估计得整理一下。现在太乱了，rt_hw_spin_lock_t、rt_spin_lock_t、多核、单核……

2023-10-25 12:37 UTC, polarvid commented on include/rtthread.h
> +rt_inline void rt_spin_lock_init(lock)                  {RT_UNUSED(lock);}
这种就是 GNU C 语法。显然对于 RTT 的内核是不合适的。因为内核使用的是 C99 语法。

https://github.com/RT-Thread/rt-thread/blob/3283f54c7a0444b2e51ec79a4da57e7871528f05/include/rtthread.h#L559

2023-10-25 13:08 UTC, polarvid commented
现在定义更乱了……

https://github.com/RT-Thread/rt-thread/blob/3283f54c7a0444b2e51ec79a4da57e7871528f05/include/rtdef.h#L495-L514

一下是

```h
typedef struct rt_spinlock rt_spinlock_t; 
```

非 SMP 又是

```h
typedef struct rt_spinlock rt_spinlock_t; 
```

让人摸不着头脑

2023-10-25 14:11 UTC, geniusgogo commented on include/rthw.h
> +#ifndef RT_HW_SPIN_LOCK_INIT
关键你两个宏的名字几乎没有差异，就是多了几个下划线

2023-10-25 14:12 UTC, geniusgogo commented on components/libc/compilers/common/ctime.c
>      if (_g_timerid[ktimerid] == NULL)
从上下文来看是有冲突的，比如并发走到这里，两个核都同时判断遇到不等NULL往下走，处理。 如果判断加了锁，只有一个核会拿锁成功往下走，另一个核等拿到锁，再判断就等于NULl了返回。

2023-10-25 14:14 UTC, geniusgogo commented on include/rtthread.h
> +rt_inline void rt_spin_lock_init(lock)                  {RT_UNUSED(lock);}
在这里明显可以这样：
#define rt_spin_unlock_irqrestore(lock, level)  do{ rt_hw_interrupt_enable(level); }while(0)

需要返回值就内联函数

2023-10-26 02:09 UTC, polarvid commented on components/libc/compilers/common/ctime.c
>      if (_g_timerid[ktimerid] == NULL)
这里对 _g_timerid 只是执行了一个只读操作。只读操作是多线程安全的，所以不需要加锁。

然后看接下来的逻辑。

```c
    rt_spin_lock(&_timer_id_lock);
    timer = _g_timerid[ktimerid];
    _g_timerid[ktimerid] = RT_NULL;
    resource_id_put(&id_timer, ktimerid);
    rt_spin_unlock(&_timer_id_lock);

    if (timer == RT_NULL)
    {
        rt_set_errno(EINVAL);
        return -1;
    }
```

简单来说，干了两件事。第一个获取 timer，并且将对应的数据置空，然后判断是否为空，为空则退出例程。第二个释放 resource_id，注意这里没有任何条件分支。

这里修改了timer，会不会破坏程序的正确性呢？答案是否定的。因为多个观察者向 timer 数组写入的都是零，因此多次写入并不会导致上一个线程写入后，观察到的数据丢失。所以这段程序是时间无关的，参考 bernstein 条件对并发程序无关性的定义。总之，判断是否为空，写入0，再次判断是否为空。这一个操作，本质上是不会导致程序结果不唯一的，也就不需要加锁保护。

接下来看第二部分逻辑，resource_id_put。 

```c
void resource_id_put(resource_id_t *mgr, int no)
{
    rt_base_t level;
    void **cur;

    if (no >= 0 && no < mgr->size)
    {
        level = rt_spin_lock_irqsave(&(mgr->spinlock));
        cur = &mgr->_res[no];
        *cur = (void *)mgr->_free;
        mgr->_free = cur;
        rt_spin_unlock_irqrestore(&(mgr->spinlock), level);
    }
}
```

观察这个 API 的实现，可以发现它并不具有幂等性。多次释放同一个 id 不能保证程序的正确性。因此这个 API 只能调用一次。

总结以上分析，可以将代码重新整理如下。

```c
    rt_spin_lock(&_timer_id_lock);
    timer = _g_timerid[ktimerid];
    if (timer != NULL)
    {
        _g_timerid[ktimerid] = RT_NULL;
        resource_id_put(&id_timer, ktimerid);
    }
    rt_spin_unlock(&_timer_id_lock);

    if (timer == RT_NULL)
    {
        rt_set_errno(EINVAL);
        LOG_D("can not find timer %ld", ktimerid);
        return -1;
    }
```

另外这里发现 `resource_id_put` 自己是有锁来保护多线程安全的，所以之前再外部加的锁就去掉了。

2023-10-26 02:09 UTC, polarvid commented on include/rthw.h
> +#ifndef RT_HW_SPIN_LOCK_INIT
换成 RT_SPIN_LOCK_INIT 了

2023-10-26 02:10 UTC, polarvid commented on include/rtthread.h
> +rt_inline void rt_spin_lock_init(lock)                  {RT_UNUSED(lock);}
个人感觉都用内联工整些

2023-10-26 02:40 UTC, xqyjlj commented
非smp时， rt_spinlock_t 的值就会通过定义传到rt_hw_interrupt_enable（level）里面去，所以非smp的rt_spinlock_t 就得是个常量

2023-10-26 02:43 UTC, xqyjlj commented
很久以前就是这种用法了，我尝试改过，结果非smp上面根本行不通

![image](https://github.com/RT-Thread/rt-thread/assets/51477609/5fcc0747-fb8a-45df-9c96-85ed56a8c035)

2023-10-26 02:45 UTC, geniusgogo approved these changes

2023-10-26 02:56 UTC, polarvid commented
> 非smp时， rt_spinlock_t 的值就会通过宏传到rt_hw_interrupt_enable（level）里面去，所以非smp的rt_spinlock_t 就得是个常量

先不讨论具体怎么改。从原则来说，如果改 rt_spinlock_t 为结构体在非 SMP 遇到使用的问题，也得是纠正错误的用法呀。非 SMP 的时候当作整型来用，这种设计不是很合理。这样搞下去，代码会越来越乱，到处是莫名其妙的兼容逻辑。

2023-10-26 05:55 UTC, Guozhanxin approved these changes

2023-10-26 05:56 UTC, merged