Add comments to the .c source file under rt-thread\components\libc #7426
RT-Thread/rt-thread pull request #8201
Opened 2023-10-30 16:30 UTC by shu-qian

## 拉取/合并请求描述：(PR description)

[
The purpose of this PR is to submit the first compliant PR to complete the novice task and add comments in the source code to improve the readability and understandability of the code and contribute to the project.

I have added detailed comments to the functions, structures and variables in the .c source code under rt-thread\components\libc, explaining their functions, usage and precautions.

This PR is mainly for comments on the source code and does not involve specific functional changes, so there is no specific testing environment.
]

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [×] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [×] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [×] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [×] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [×] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [×] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [×] 代码是高质量的 Code in this PR is of high quality
- [×] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-30 16:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8201) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: strongYourSister<br/>:x: shu-qian<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8201) it.</sub>

2023-10-31 13:29 UTC, mysterywolf requested changes
Hi, Thanks for submit the PR! there are too many code in this PR, so that it will be painful to review it. Could you split to several PRs? the first PR I think is  you can add some comments of functions for the sources files. Once you've already been familar with rt-thread's code format style, then you may submit a banch of code in one PR. I just review part of them.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> - */
Please don't delete it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> - */
Please don't delete it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> - */
Please don't delete it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> - */
Please don't delete it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> -/* This function writes a character to the console. */
Please don't delete it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> -/* for exit() and abort() */
Please don't delete it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> +        ;
don't need to change for this

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> - */
Please don't delete it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> +    return 0;     /* error */
don't need to change

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/armlibc/syscalls.c
> -
need a empty line, don't need to change

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/common/cstring.c
> +        ;
let the ';' stay with the same line with for loop

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/common/cstring.c
> +        ;
one line

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/common/cstring.c
> +        ;
one line

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +        (31 + 28 + 31 + 30 + 31 + 30),
this format is good, don't need to change it

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/common/ctime.c
> +        ;
one line

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/common/cwchar.c
> -        { 0x0B4D, 0x0B4D }, { 0x0B56, 0x0B56 }, { 0x0B82, 0x0B82 },
this format is good , don't need to change it.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/common/cwchar.c
> +             ));
please make sure the format.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/dlib/syscall_close.c
> -
please don't delte the space.

2023-10-31 13:29 UTC, mysterywolf commented on components/libc/compilers/dlib/syscall_lseek.c
> +#define DBG_LVL DBG_INFO
don't need to change

2023-10-31 14:02 UTC, shu-qian commented
ok, I will divide it into several PR submissions, thank you for your review. I am sorry that there were some unintentional inappropriate modifications due to too many files.

2023-10-31 14:23 UTC, closed without merging