Add comments to the rt-thread\components\libc\compilers\common\cstdlib.c
RT-Thread/rt-thread pull request #8209
Opened 2023-10-31 15:01 UTC by shu-qian

[
The purpose of this PR is to submit the  PR to Fixes #7426 
and add comments in the source code to improve the readability and understandability of the code and contribute to the project.

I have added detailed comments to rt-thread\components\libc\compilers\common\cstdlib.c

This PR is mainly for comments on the source code and does not involve specific functional changes, so there is no specific testing environment.
]

 - [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-10-31 22:11 UTC, BernardXiong approved these changes

2023-11-01 00:26 UTC, mysterywolf requested changes

2023-11-01 00:26 UTC, mysterywolf commented on components/libc/compilers/common/cstdlib.c
> +#define DBG_LVL DBG_INFO
此处无需修改

2023-11-01 01:48 UTC, shu-qian commented
Sorry, I've corrected the indentation problem you pointed out.

2023-11-01 06:17 UTC, supperthomas approved these changes

2023-11-01 09:31 UTC, mysterywolf approved these changes

2023-11-01 09:31 UTC, merged

2023-11-01 09:32 UTC, mysterywolf commented
Thanks for your PR!