Hc32f460
RT-Thread/rt-thread pull request #8217
Opened 2023-11-02 02:49 UTC by lianghongquan

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
1. hc32驱动函数和rtt函数声明之间的参数类型不一致，在mdk编译时产生警告。
2. hc32的can设备，在注册时就把can中断使能了。导致can设备在打开前，就会产生中断。
3. hc32的pwm驱动，不支持PWM_CMD_SET_PERIOD和PWM_CMD_SET_PULSE指令，导致rt_pwm_set_pulse()函数返回失败。

#### 你的解决方案是什么 (what is your solution)
1. 修改hc32驱动函数参数类型和声明一致。
2. 注册can设备时主动禁止can中断，因为打开设备时会主动打开中断。
3. 修改pwm驱动，增加PWM_CMD_SET_PERIOD和PWM_CMD_SET_PULSE指令支持。

#### 在什么测试环境下测试通过 (what is the test environment)
硬件MCU为HC32F460.
rt-thread studio 2.2.6, GNU 10.2.1, 编译通过。
MDK 5.31.0.0, ArmClang V6.14, 编译通过。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-11-02 08:52 UTC, lianghongquan commented
CI错误需要处理吗？要怎么做呢？

2023-11-02 15:22 UTC, mysterywolf requested changes

2023-11-02 15:22 UTC, mysterywolf commented on bsp/hc32/libraries/hc32_drivers/drv_pwm_tmra.c
> +        //
请去掉这个无用注释

2023-11-02 15:22 UTC, mysterywolf commented on bsp/hc32/libraries/hc32_drivers/drv_pwm_tmra.c
> +    //
请去掉这个无用注释

2023-11-02 15:22 UTC, mysterywolf commented on bsp/hc32/libraries/hc32_drivers/drv_pwm_tmra.c
> +        // clk not match, need change div
请使用/**/

2023-11-02 15:22 UTC, mysterywolf commented on bsp/hc32/libraries/hc32_drivers/drv_pwm_tmra.c
> +    //
请去掉这个无用注释

2023-11-02 15:26 UTC, mysterywolf commented
格式检查不通过，麻烦用formatting脚本扫描一下不通过的文件吧  谢谢 https://github.com/mysterywolf/formatting

2023-11-08 09:43 UTC, lianghongquan commented
用formatting工具检查了文件并提交了，现在出现cppcheck错误，这个我找不到问题原因。

2023-11-08 10:34 UTC, lianghongquan commented on bsp/hc32/libraries/hc32_drivers/drv_pwm_tmra.c
> +        //
我的formatting脚本找不到这个无用注释，难道我们的检查有差异吗？
![2023-11-08_183302](https://github.com/RT-Thread/rt-thread/assets/37073099/32909830-83dd-40bb-99dc-15ee6a529b09)

2023-11-08 11:12 UTC, mysterywolf commented
cppcheck 无需理会，这个只是给出一些知道建议

2023-11-08 11:12 UTC, mysterywolf commented
formatting脚本不会处理无用注释的 这些无用注释需要麻烦手动删除掉

2023-11-14 14:17 UTC, mysterywolf approved these changes

2023-11-14 14:18 UTC, merged

2023-11-14 14:18 UTC, mysterywolf commented
感谢提交PR！