[libc][picolibc] improve gcc picolibc support
RT-Thread/rt-thread pull request #8220
Opened 2023-11-03 07:55 UTC by iDings

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
现阶段的绝大部分的gcc编译工具链默认都是使用newlibc，crosstool-ng可以制作
带picolibc的gcc编译工具链, 使用该工具链接rt-thread无法编译编译

#### 你的解决方案是什么 (what is your solution)
增加部分缺失的picolibc依赖接口:https://github.com/picolibc/picolibc/blob/main/doc/os.md

#### 在什么测试环境下测试通过 (what is the test environment)
- 使用crosstool-ng生成的gcc(picolibc)工具链编译，qemu-vexpress-a9 正常启动运行
- llvm-arm能正常编译stm32f407-rt-spark 

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-11-03 07:57 UTC, iDings commented
zephyr-sdk的gcc编译工具链包含newlibc跟picolibc，可以通过gcc的`--specs=`参数指定picolibc,
现阶段的[tools/gcc.py](https://github.com/RT-Thread/rt-thread/blob/5ad6a6f2c59737b54f41b79b6d1e0d6a9ba08da1/tools/gcc.py#L42C9-L42C9
)查找头文件include路径是固定的，改成自动获取搜索路径的方式https://stackoverflow.com/questions/4980819/what-are-the-gcc-default-include-directories， 这样兼容性应该会更好点

2023-11-03 08:09 UTC, Guozhanxin commented
@iDings  可以帮忙用 llvm-arm 试一下这个bsp吗：https://github.com/RT-Thread/rt-thread/tree/master/bsp/renesas/ra8m1-ek

他这个 bsp 好像依赖了 picolibc 的 tls 功能。但是我知道该怎么处理。

2023-11-03 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8220) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8220) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8220) it.</sub>

2023-11-03 12:33 UTC, iDings commented
@Guozhanxin 使用picolibc需要对TLS做些初始化，链接脚本里面需要定义TLS存储信息跟符号
https://github.com/picolibc/picolibc/blob/main/doc/tls.md而且线程里面也需要配合使用这些信息， 
之前gcc+newlibc的编译工具链都是`--disable-tls` 使用的是emulated TLS(https://bugs.launchpad.net/gcc-arm-embedded/+bug/1842725).

TLS的话GCC+PICOLIBC应该也是有问题，这个我要看下怎么处理. 
picolibc的作者在RIOT上有增加TLS改动: https://github.com/RIOT-OS/RIOT/commits?author=keith-packard 可以做点参考

PICOLIBC参考的链接脚本还需要增对不同的ld还需要设置不同的align
https://github.com/picolibc/picolibc/blob/75273b12bba66bbe7633514a2c43690a724458fe/picolibc.ld.in#L183

2023-11-03 15:58 UTC, mysterywolf commented
感谢提交PR PR准备就绪之后请@我review

2023-11-06 02:15 UTC, Guozhanxin commented
> 感谢提交PR PR准备就绪之后请@我review

我感觉现在这个pr就可以review了，tls相关的，下个pr再说吧。

2023-11-06 02:21 UTC, mysterywolf requested changes

2023-11-06 02:21 UTC, mysterywolf commented on components/libc/compilers/picolibc/SConscript
> +else:
elif 条件需要写的更明确
else picolibc doesn't support this PLATFORM

2023-11-06 05:57 UTC, iDings commented on components/libc/compilers/picolibc/SConscript
> +else:
恩我改下

2023-11-06 06:06 UTC, iDings commented
我先把这个https://github.com/RT-Thread/rt-thread/pull/8220#issuecomment-1792008489实现了，然后tls的话后面单独再提交一个PR

2023-11-07 13:11 UTC, iDings commented
@mysterywolf  帮忙review下改动，我这边现在只在ubuntu下做了验证.

验证方法:
[zephyr-sdk toolchain ](https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/toolchain_linux-x86_64_arm-zephyr-eabi.tar.xz) 可以使用用来验证同时验证gcc+newlibc与gcc+picolibc.
对于使用gcc+picolibc需要打上如下patch，
```diff
diff --git a/bsp/qemu-vexpress-a9/rtconfig.py b/bsp/qemu-vexpress-a9/rtconfig.py
index 77cc9dfb4..391e13f2f 100644
--- a/bsp/qemu-vexpress-a9/rtconfig.py
+++ b/bsp/qemu-vexpress-a9/rtconfig.py
@@ -49,7 +49,9 @@ if PLATFORM == 'gcc':
     STRIP   = PREFIX + 'strip'
     CFPFLAGS = ' -msoft-float'
     AFPFLAGS = ' -mfloat-abi=softfp -mfpu=neon'
-    DEVICE   = ' -march=armv7-a -mtune=cortex-a7 -ftree-vectorize -ffast-math -funwind-tables -fno-strict-aliasing'
+    DEVICE = ''
+    DEVICE += ' --specs=picolibc.specs --picolibc-prefix=' + EXEC_PATH + '/../'
+    DEVICE += ' -march=armv7-a -mtune=cortex-a7 -ftree-vectorize -ffast-math -funwind-tables -fno-strict-aliasing'
 
     CXXFLAGS= DEVICE + CFPFLAGS + ' -Wall -fdiagnostics-color=always'
     CFLAGS  = DEVICE + CFPFLAGS + ' -Wall -Wno-cpp -std=gnu99 -D_POSIX_SOURCE -fdiagnostics-color=always'
```

按理说可以不使用`--picolibc-prefix`，但是没有指定的话发现会提示找不到crt0，查找的路径很奇怪，暂时不确定什么原因.

2023-11-08 07:08 UTC, mysterywolf approved these changes

2023-11-08 07:08 UTC, mysterywolf commented on components/libc/compilers/picolibc/SConscript
> +  print('ignore picolibc: not supported on ' + rtconfig.PLATFORM)
```suggestion
else:
```

2023-11-08 07:09 UTC, merged

2023-11-08 07:12 UTC, mysterywolf commented
感谢提交PR！

2023-11-10 10:34 UTC, mysterywolf commented
你好 这个PR改出问题了 

复现方法 进入任何一个bsp 例如stm32 直接menuconfig刷新一下配置 然后scons 编译即可发现编译报错

![image](https://github.com/RT-Thread/rt-thread/assets/34888354/7d949469-9509-435d-8945-2cee767cc828)

麻烦修复一下 谢谢！

2023-11-16 09:49 UTC, Guozhanxin commented
> 你好 这个PR改出问题了 https://club.rt-thread.org/ask/question/dfc88acb52dfbaba.html
> 
> 复现方法 进入任何一个bsp 例如stm32 直接menuconfig刷新一下配置 然后scons 编译即可发现编译报错
> 
> ![image](https://user-images.githubusercontent.com/34888354/282033409-7d949469-9509-435d-8945-2cee767cc828.png)
> 
> 麻烦修复一下 谢谢！

@iDings  麻烦看一下这个问题，好像是 run 在 python2.x 的版本不支持

2023-11-22 03:28 UTC, iDings commented
@mysterywolf @Guozhanxin 抱歉刚看到， 我看下

2023-11-22 03:35 UTC, iDings commented
如果python支持2.0的话， 建议现在CI检查的时候也是python2.0的版本

2023-11-22 03:36 UTC, mysterywolf commented
你好&nbsp; 这个问题已经修复



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 22, 2023 11:35 AM
To: ***@***.***&gt;;
Cc: "Meco ***@***.******@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] [libc][picolibc] improve gcc picolibcsupport (PR #8220)




 
如果python支持2.0的话， 建议现在CI检查的时候也是python2.0的版本
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2023-11-22 04:15 UTC, iDings commented
@mysterywolf  :handshake:  抱歉哈

2024-01-21 07:22 UTC, mysterywolf commented
你好 之前提交了个PR并没有彻底解决这个问题 https://github.com/RT-Thread/rt-thread/pull/8254

请最好确认一下Python2环境可以正常执行，不要用.run这个方法，这个方法只在python3里有，或者采用try的方式
https://club.rt-thread.org/ask/question/dfc88acb52dfbaba.html

![1705821625482](https://github.com/RT-Thread/rt-thread/assets/34888354/8dfba7a5-1183-4675-92db-1caa5d86492c)

2024-01-25 02:48 UTC, iDings commented
好的， 我确认下