[libcpu][aarch64] 使用设备树对CPU进行初始化
RT-Thread/rt-thread pull request #8221
Opened 2023-11-03 11:22 UTC by fangjianzhou

## 拉取/合并请求描述：(PR description)
[
#### 为什么提交这份PR (why to submit this PR)
- 使用设备树对CPU进行初始化，并修复qemu-virt64-aarch64多核无法启动的问题

#### 你的解决方案是什么 (what is your solution)
- 重构libcpu/aarch64CPU部分的代码，将RT_USING_FDT接口的代码改为RT_USING_OFW的

#### 在什么测试环境下测试通过 (what is the test environment)
- 在使用时需要开启 RT_USING_DM，RT_USING_OFW，RT_USING_FIRMWARE，RT_FIRMWARE_PSCI
- 在qemu-virt64-aarch64中测试通过

]
### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-11-06 05:24 UTC, BernardXiong commented on components/drivers/firmware/Kconfig
> +menuconfig RT_USING_FIRMWARE
这个不能这么写的，因为独立来看`RT_USING_FIRMWARE`，不明所以。

2023-11-06 05:25 UTC, BernardXiong commented on components/drivers/firmware/SConscript
> +for d in list:
```python
if GetDepend('RT_USING_XXX'):
    list = os.listdir(cwd)
    for d in list:
        ...

Return('objs')
```

2023-11-06 05:49 UTC, fangjianzhou commented on components/drivers/firmware/Kconfig
> +menuconfig RT_USING_FIRMWARE
把这个改成RT_USING_DRV_FIRMWARE可以吗，还是删去，只留PSCI的选项

2023-11-06 05:56 UTC, fangjianzhou commented on components/drivers/firmware/SConscript
> +for d in list:
我这么写是为了减少构建时间，是否可以保留该写法

2023-11-07 11:06 UTC, polarvid commented on components/drivers/ofw/base.c
> +extern char* strchrnul(const char* s, int c);
引入函数原型应该优先使用头文件。

2023-11-07 11:07 UTC, polarvid commented on components/drivers/ofw/fdt.c
> +extern char* strchrnul(const char* s, int c);
同理

2023-11-07 11:10 UTC, polarvid commented on components/drivers/pm/pm.c
> +        mode = (rt_uint32_t)(rt_ubase_t)args;
这里也要修改局部变量的类型。前面这个 cast 毫无逻辑。

2023-11-07 11:13 UTC, polarvid commented on libcpu/aarch64/common/cpuport.h
> +#define sysreg_write(sysreg, val) \
这里定义的 API 不符合命名规范，也不符合 cpuport.h 头文件的语义。

2023-11-07 11:29 UTC, polarvid commented on libcpu/aarch64/common/cpu.c
>      {
弱实现在 rtservice.c 里面已经存在。

2023-11-07 11:30 UTC, polarvid commented on libcpu/aarch64/common/cpu.c
> +MSH_CMD_EXPORT_ALIAS(rt_hw_cpu_reset, reset, reset...);
弱实现需要移至 rtservice.c

2023-11-13 14:26 UTC, BernardXiong commented on components/drivers/firmware/Kconfig
> +menuconfig RT_USING_DM_FIRMWARE
本身这个目录名就显得比较奇怪了。名称上一定是清晰易懂并无二意的。

2023-11-13 14:27 UTC, BernardXiong commented on components/drivers/ofw/ofw_internal.h
> +extern char* strchrnul(const char* s, int c);
这部分是需要在此处做`extern`声明吗？

2023-11-13 14:35 UTC, BernardXiong requested changes
是否可以把整体关系先理清？关系不清，最终是越来越乱……

2023-11-13 14:35 UTC, BernardXiong commented on components/drivers/include/drivers/pm.h
> +extern void (*rt_pm_machine_shutdown)(void);
这两个又是从哪里来，到哪里去的？

2023-11-13 14:35 UTC, BernardXiong commented on components/drivers/include/drivers/psci.h
> +#define PSCI_0_2_FN_BASE                    0x84000000
psci提到这里，是说所有的架构都支持PSCI方式？

2023-11-14 02:33 UTC, fangjianzhou commented on components/drivers/ofw/ofw_internal.h
> +extern char* strchrnul(const char* s, int c);
这部分原因是内核没处理到libc依赖问题，同时引入函数原型应该优先使用头文件，所以放在此处

2023-11-14 02:35 UTC, fangjianzhou commented on components/drivers/include/drivers/pm.h
> +extern void (*rt_pm_machine_shutdown)(void);
![图片](https://github.com/RT-Thread/rt-thread/assets/73834245/752e927e-6981-4121-896a-e208481a1c6c)

2023-11-14 02:39 UTC, fangjianzhou commented on components/drivers/include/drivers/pm.h
> +extern void (*rt_pm_machine_shutdown)(void);
这是个全局函数指针，用于驱动绑定机器开关机函数的，在pm.c中对该这两个变量进行了定义，在rk3568的board.c中进行了使用

2023-11-14 02:40 UTC, fangjianzhou commented on components/drivers/include/drivers/pm.h
> +extern void (*rt_pm_machine_shutdown)(void);
![Uploading 图片.png…]()

2023-11-14 02:41 UTC, fangjianzhou commented on components/drivers/include/drivers/pm.h
> +extern void (*rt_pm_machine_shutdown)(void);
![Uploading 图片.png…]()

2023-11-14 02:47 UTC, fangjianzhou commented on components/drivers/include/drivers/pm.h
> +extern void (*rt_pm_machine_shutdown)(void);
![Uploading 图片.png…]()

2023-11-14 02:51 UTC, fangjianzhou commented on components/drivers/include/drivers/pm.h
> +extern void (*rt_pm_machine_shutdown)(void);
![Uploading 图片.png…]()

2023-11-15 05:38 UTC, BernardXiong commented on components/drivers/ofw/ofw_internal.h
> +extern char* strchrnul(const char* s, int c);
Linux下man strchrnul，是这样显示的：
```c
       #include <string.h>

       char *strchr(const char *s, int c);

       char *strrchr(const char *s, int c);

       #define _GNU_SOURCE         /* See feature_test_macros(7) */
       #include <string.h>

       char *strchrnul(const char *s, int c);
```

2023-11-15 05:38 UTC, BernardXiong commented on components/drivers/pm/pm.c
> +void (*rt_pm_machine_shutdown)(void) = RT_NULL;
这地方依然是需要说明的，为什么是采用这样的方式？这部分对整体的PM子系统的影响又是什么样的。

2023-11-15 05:56 UTC, fangjianzhou commented on components/drivers/ofw/ofw_internal.h
> +extern char* strchrnul(const char* s, int c);
https://github.com/RT-Thread/rt-thread/actions/runs/6744554960/job/18334625110?pr=8221原先是采用此方法，但是rtos的ci无法编译通过，为解决这个问题，所以采用extern的方式 @BernardXiong

2023-11-15 06:14 UTC, fangjianzhou commented on components/drivers/ofw/ofw_internal.h
> +extern char* strchrnul(const char* s, int c);
![Uploading 图片.png…]()

2023-11-15 06:24 UTC, fangjianzhou commented on components/drivers/ofw/ofw_internal.h
> +extern char* strchrnul(const char* s, int c);
gcc-aarch64-none-elf的libc也没有提供strchnul这个函数

2023-11-15 09:42 UTC, fangjianzhou commented on components/drivers/pm/pm.c
> +void (*rt_pm_machine_shutdown)(void) = RT_NULL;
这个地方我加一下注释说明以下，文档里面我也会说明，比如Callbacks for platform drivers to implement. This is a function called at the end of the SoC power down procedure，只是一般由pm类型的设备驱动实现，所以放在这里

2023-11-17 12:45 UTC, fangjianzhou commented on components/drivers/pm/pm.c
> +void (*rt_pm_machine_shutdown)(void) = RT_NULL;
这个pr先解决smp无法启动的问题，在dm里面实现power相关ops之后进行更改

2023-11-27 01:52 UTC, fangjianzhou commented on bsp/phytium/board/board.c
> -    #include <psci.h>
这个bsp使用的是自己实现的psci,已经#include <fpsci.h>，不会用到libcpu/aarch64/里面的psci，所以将这个#include <psci.h>删去 @BernardXiong

2023-11-28 06:20 UTC, BernardXiong approved these changes

2023-11-28 06:20 UTC, merged