fix aarch64 backtrace print.
RT-Thread/rt-thread pull request #8238
Opened 2023-11-07 03:23 UTC by geniusgogo

## 拉取/合并请求描述：(PR description)

[
修复aarch64上backtrace打印接口，LOG_X接口在异步ulog环境下不能正常看到trace信息，所以修改为rt_kprintf直接输出。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-11-07 04:24 UTC, mysterywolf requested changes

2023-11-07 04:24 UTC, mysterywolf commented on src/kservice.c
> +    rt_kprintf("%s: not implemented");
这个保留为LOG_W

2023-11-07 08:55 UTC, geniusgogo commented on src/kservice.c
> +    rt_kprintf("%s: not implemented");
LOG_W不一定能输出啊，一般出现fault了之后，还没等ulog那边刷出来就重启了。

2023-11-08 01:39 UTC, xqyjlj commented on src/kservice.c
> +    rt_kprintf("%s: not implemented");
异常有关的建议都走kprintf，log系列的函数不一定能把数据送出来

2023-11-08 01:42 UTC, mysterywolf requested changes

2023-11-08 01:42 UTC, mysterywolf commented on src/kservice.c
> +    LOG_W("not implemented");
处理成这样吧，否则用户并不知道哪个函数未实现

```suggestion
    LOG_W("%s is not implemented", __func__);
```

2023-11-08 01:42 UTC, mysterywolf commented on src/kservice.c
> +    rt_kprintf("not implemented\n");
```suggestion
   /* LOG_W cannot work under this environment */
    rt_kprintf("%s is not implemented\n", __func__);
```

2023-11-08 01:42 UTC, mysterywolf commented on src/kservice.c
> +    rt_kprintf("%s: not implemented");
有道理！

2023-11-08 11:10 UTC, mysterywolf approved these changes

2023-11-08 11:10 UTC, mysterywolf commented on src/kservice.c
> +    LOG_W("not implemented");
```suggestion
    LOG_W("%s is not implemented", __func__);
```

2023-11-08 11:10 UTC, mysterywolf commented on src/kservice.c
> +    rt_kprintf("please use: addr2line -e rtthread.elf -a -f");
```suggestion
    rt_kprintf("please use: addr2line -e rtthread.elf -a -f\n");
```

2023-11-08 11:11 UTC, merged