[bsp] add nano-stm32f103 bsp with nano configs
RT-Thread/rt-thread pull request #8266
Opened 2023-11-20 10:41 UTC by Guozhanxin

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

请填写验证bsp目录下面的目录比如bsp/stm32/stm32l496-st-nucleo

Please provide the path of verfied bsp. Like bsp/stm32/stm32l496-st-nucleo  bsp/ESP32_C3

- BSP:

请填写.config 文件中需要改动的config

Please provide the changed config of .config file to how to verify the PR file like CONFIG_BSP_USING_I2C CONFIG_BSP_USING_WDT

- .config:

请提供自己仓库的PR branch的action的编译链接相关PR文件成功的链接：

Please provide the link of action triggered by your own repo's action  

https://github.com/RT-Thread/rt-thread/actions/workflows/manual_dist.yml

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-11-21 03:36 UTC, Guozhanxin commented
pico 好像没过，不知道这里哪里影响到了 pico

2023-11-21 06:26 UTC, supperthomas commented
@Z8MAN8 

```
     File "/home/runner/work/rt-thread/rt-thread/bsp/raspberry-pico/packages/raspberrypi-pico-sdk-latest/lib/SConscript", line 22:
```

2023-11-21 06:43 UTC, Z8MAN8 commented
> @Z8MAN8
> 
> ```
>  NameError: name 'src' is not defined:
>      File "/home/runner/work/rt-thread/rt-thread/bsp/raspberry-pico/packages/raspberrypi-pico-sdk-latest/lib/SConscript", line 22:
> ```

https://github.com/RT-Thread-packages/raspberrypi-pico-sdk/pull/7 已修改

2023-11-21 14:54 UTC, mysterywolf commented
> > @Z8MAN8
> > ```
> >  NameError: name 'src' is not defined:
> >      File "/home/runner/work/rt-thread/rt-thread/bsp/raspberry-pico/packages/raspberrypi-pico-sdk-latest/lib/SConscript", line 22:
> > ```
> 
> [RT-Thread-packages/raspberrypi-pico-sdk#7](https://github.com/RT-Thread-packages/raspberrypi-pico-sdk/pull/7) 已修改

已合并

2023-11-25 07:38 UTC, supperthomas requested changes

2023-11-25 07:38 UTC, supperthomas commented on bsp/stm32/nano-stm32f103/applications/main.c
> +{
是不是可以用HAL写个GPIO亮灯程序？有个演示效果？

2023-11-26 07:27 UTC, mysterywolf commented
以新的bsp方式合入 我看了一下 没啥问题，但是有几点需要改进：
1. Kconfig是否需要做出裁剪，删除掉所有ADC PWM这些东西
2. CubeMX ADC PWM TIMER这些都应该关闭掉
3. README需要重新编写一下 不能直接用bluepill的README 否则用户会困惑 这个和bluepill bsp有什么区别

2023-11-26 16:05 UTC, mysterywolf commented
郭老师 我这里有一个更好的方案 你看一下吧 https://github.com/RT-Thread/rt-thread/pull/8303

2023-11-30 03:41 UTC, closed without merging