sync update dfs v2.
RT-Thread/rt-thread pull request #8336
Opened 2023-12-04 07:50 UTC by geniusgogo

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-12-05 08:30 UTC, BernardXiong requested changes

2023-12-05 08:30 UTC, BernardXiong commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
这个没地方使用，不需要这部分的代码。

2023-12-05 08:30 UTC, BernardXiong commented on components/dfs/dfs_v2/src/dfs_pcache.c
> +                                //rt_hw_cpu_dcache_ops(RT_HW_CACHE_FLUSH, vaddr, ARCH_PAGE_SIZE);
rt_hw_cpu_dcache_ops的操作不需要吗？如果确实不需要的，那么就把代码移除吧

2023-12-05 10:38 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
这个原本是给uds或类似需要跨进程传递fd的时候用的，然后uds那边又自己把这个函数copy rename了一份。严格上来讲应该用这一份共用的才是吧？

2023-12-05 15:07 UTC, BernardXiong commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
如果是这样，那应该对这两个API进行比较好的命名，以反应出意义。

2023-12-06 06:13 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
https://github.com/RT-Thread/rt-thread/commit/ddb4bde9f4fb6f7a2cf0cf7086afeced7708f609

dfs_dup_to_fdtab：将A进程的私有fd dup到fdtab中，如果fdtab没有指定则使用内核全局的fdtab.
dfs_dum_from_tdtab：进程B将进程A通过dfs_dup_to_fdtab dup得到的fd，从原fdtab中再dup一个属于自己进程的fd出来。
dfs_fdtab_drop_fd：从fdtab中释放一个fd。

2023-12-10 11:30 UTC, BernardXiong commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
`int dfs_fdtab_drop_fd(int fd, struct dfs_fdtable *fdtab)` 看起来并不是那么合规，包括这个文件前面还有`dfs_fdtable_`类型的API。如果是`dfs_fdtable_`类型的，那么这个api应该以fdtable为中心，即`int dfs_fdtable_drop_fd(struct dfs_fdtable* fdt, int fd);`。

2023-12-10 12:08 UTC, BernardXiong commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
如果是dup，总体来说，是不是也只有一种情况：
`int dfs_fdtable_dup(struct dfs_fdtable *fdt, struct dfs_fdtable *fdt_src, int fd_src);`

把源fdt_src中对应的fd_src，复制到fdt中。

源fdt可以是NULL，则代表当前的进程；如果fdt_dst是NULL，则代表当前的进程。

2023-12-11 03:53 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
> 如果是dup，总体来说，是不是也只有一种情况

大致原理相同，不过有点差异的考量：
原dfs_dup_to_fdtab是浅拷贝，不会正真去分配fds，只是讲fds指向同一个源fd，并应用计数+1.等到dfs_dum_from_tdtab的时候才会深拷贝一次fds。

合并成一种情况来看的话，就不能使用浅拷贝了。

2023-12-11 09:32 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs.c
> +int dfs_dup_to(int oldfd, struct dfs_fdtable *fdtab)
@BernardXiong 改了，look look again.

@XYZ-20240101 也帮忙review一下。

2023-12-12 10:05 UTC, BernardXiong approved these changes

2023-12-12 10:05 UTC, merged