[drivers][core] 完善设备模型
RT-Thread/rt-thread pull request #8384
Opened 2023-12-19 03:21 UTC by fangjianzhou

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
- 完善设备模型，并修复部分设备驱动注册之后，无法进入 probe 函数问题

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 
- BSP: 
- .config:
- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2023-12-30 07:55 UTC, BernardXiong commented
@geniusgogo please help to review this PR, thanks.

2024-01-03 02:25 UTC, geniusgogo commented
@zhangsz0516

2024-01-05 04:08 UTC, geniusgogo requested changes

2024-01-05 04:11 UTC, geniusgogo commented on components/drivers/core/bus.c
> +rt_inline void spin_lock(struct rt_spinlock *spinlock)
为什么bus需要单独重定义自旋锁接口？而其它文件又没有单独定义？如果需要单独定义，最好是在接口名字上附加模块的名字例如_dm_bus_lock?

2024-01-05 04:14 UTC, geniusgogo requested changes

2024-01-05 04:14 UTC, geniusgogo commented on components/drivers/core/dm.c
> +    RT_ASSERT(dev->ofw_node != RT_NULL);
在代码中如果是非致命性错误，能不用assert就尽量当成错误来处理。assert势必是在故障发生时整个系统无法再处理任何其它动作了。

2024-01-07 12:34 UTC, geniusgogo approved these changes

2024-01-09 15:10 UTC, merged