[libcpu/arm/cortex-a]修改arm/cortex-a启动方式，解决cortex-a开启SMP工作异常问题
RT-Thread/rt-thread pull request #8517
Opened 2024-01-31 02:18 UTC by messigogogo

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
在进行cortex-a cpu 测试的时候，当开启smp 功能，在 rt_hw_init_mmu_table ---> rt_aspace_init ---> _init_lock ---> rt_object_init 中会调用 rt-thread\libcpu\arm\cortex-a\cpuport.c 中的 rt_hw_spin_lock 函数，此时cortex-a cpu 中的 SCTLR 中关闭了dcache 与 mmu bit ，对于某些cortex-a的cpu 来说此时memory type 为 Strongly Ordered ， 这可能会导致rt_hw_spin_lock 函数中的ldrex、strex失效，导致异常的产生 .目前RT-Thread 、smart 由于此问题导致cortex-a 对应的bsp无法使用。

#### 你的解决方案是什么 (what is your solution)
对cortex-a cpu的启动步骤仿照aarch64的风格进行了整理，使逻辑更加清晰，并解决了上述问题。已在qemu-vexpress-a9，raspi4-32，phytium开发板上进行测试，目前可以正常启动

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:
![360866a0b7bc56143fc1e44d5ee778a](https://github.com/RT-Thread/rt-thread/assets/103986797/18b84111-3201-42bc-ad26-dd6162890a3d)
![f40ff977c306726581486ea388fb356](https://github.com/RT-Thread/rt-thread/assets/103986797/976e3b06-f5a0-4473-922d-c91757be1836)

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-01-31 23:05 UTC, BernardXiong commented
Good Job!

2024-01-31 23:07 UTC, BernardXiong commented
> [cpp_check.py 28 INFO] libcpu/arm/cortex-a/mmu.c:211:30: error: Overflow in pointer arithmetic, NULL pointer is subtracted. [nullPointerArithmetic]
    rt_mpr_start = (void *)0 - rt_mpr_size;

这里也帮忙做个调整吧，原来的代码有些不太规范

2024-02-01 02:41 UTC, messigogogo commented
> > [cpp_check.py 28 INFO] libcpu/arm/cortex-a/mmu.c:211:30: error: Overflow in pointer arithmetic, NULL pointer is subtracted. [nullPointerArithmetic]
> > rt_mpr_start = (void *)0 - rt_mpr_size;
> 
> 这里也帮忙做个调整吧，原来的代码有些不太规范

已修改 rt_mpr_start = (void *)((rt_size_t)0 - rt_mpr_size);

2024-02-20 03:07 UTC, mysterywolf commented
你好 这份代码先挂在这里 等https://github.com/RT-Thread/rt-thread/pull/8537 合并之后再麻烦您重新rebase和测试一下~

2024-02-20 03:11 UTC, messigogogo commented
> 你好 这份代码先挂在这里 等#8537 合并之后再麻烦您重新rebase和测试一下~
好的，这份代码和刚才合入的有一些冲突，我只是重新修改提交一下

2024-02-20 03:11 UTC, messigogogo commented
> 你好 这份代码先挂在这里 等#8537 合并之后再麻烦您重新rebase和测试一下~

好的，这份代码和刚才合入的有一些冲突，我只是重新修改提交一下

2024-02-21 11:41 UTC, messigogogo commented
> 你好 这份代码先挂在这里 等#8537 合并之后再麻烦您重新rebase和测试一下~

你们近期会对#8537 进行合入吗？那边改动比较大？

2024-02-21 11:48 UTC, messigogogo commented
> 你好 这份代码先挂在这里 等#8537 合并之后再麻烦您重新rebase和测试一下~

现在的版本测试感觉有一些问题，会不会是那边提到的issure导致的#8537？

2024-02-24 01:06 UTC, mysterywolf commented
https://github.com/RT-Thread/rt-thread/pull/8537 已经合并 麻烦重新rebase到最新基线并测试一下把~

2024-02-26 05:40 UTC, messigogogo commented
> #8537 已经合并 麻烦重新rebase到最新基线并测试一下把~

重新测试了qemu-vexpress-a9，和phytium开发板。可以正常启动

2024-02-28 02:16 UTC, polarvid requested changes

2024-02-28 02:16 UTC, polarvid commented on bsp/phytium/board/board.c
> +extern void rt_hw_mmu_init(void) ;
最好是放到头文件里面。否则后续原型修改很容易不一致，而且发现不了。

2024-02-28 02:16 UTC, polarvid commented on bsp/raspberry-pi/raspi4-32/driver/board.c
> +extern void rt_hw_mmu_init(void);
同理，应该是引用个头文件。

2024-02-28 02:16 UTC, polarvid commented on libcpu/arm/cortex-a/start_gcc.S
> +rt_asm_cpu_id:
这个命名得改成 `rt_hw_cpu_id`

2024-02-28 03:37 UTC, polarvid requested changes

2024-02-28 03:37 UTC, polarvid commented on libcpu/arm/cortex-a/start_gcc.S
> +    add \reg, pv_off
这个 pv_off 最好是个参数，否则用这个宏的时候，就依赖于 pv_off 这个寄存器的初始化。后面加代码，或者维护起来容易疏忽。

```suggestion
.macro get_phy, reg, symbol, _pvoff
    ldr \reg, =\symbol
    add \reg, \_pvoff
```

2024-02-28 03:37 UTC, polarvid commented on libcpu/arm/cortex-a/start_gcc.S
> +    sub pv_off, pv_off, r0
如果修改了，这个就可以用 `get_pvoff` 宏替换。

2024-02-28 03:37 UTC, polarvid commented on libcpu/arm/cortex-a/start_gcc.S
> +.endm
而且，按照现在的参数设计， get_pvoff 依赖了 get_phy，get_phy 依赖了 pv_off。虽然 pv_off 可以单独先初始化，结果上也对。但是逻辑上很奇怪。

2024-02-28 03:37 UTC, polarvid commented on libcpu/arm/cortex-a/start_gcc.S
> +    get_pvoff r2,r1
这里就是 `get_phy` 的参数设计很容易造成混乱的例子。get_phy 依赖于 pvoff 的，但是这里又先计算了 get_phy，然后计算一个新的 pvoff。看的时候就很别扭。

如果给 get_phy 加入 pvoff 作为第三个参数，修改后个人感觉是更清晰可读的。

```suggestion
    get_phy r0, init_mtbl, pv_off
    mov r1, pv_off
```

2024-03-01 07:21 UTC, messigogogo commented on bsp/phytium/board/board.c
> +extern void rt_hw_mmu_init(void) ;
放在mmu.h里了

2024-03-01 07:21 UTC, messigogogo commented on libcpu/arm/cortex-a/start_gcc.S
> +rt_asm_cpu_id:
已修改

2024-03-01 07:22 UTC, messigogogo commented on libcpu/arm/cortex-a/start_gcc.S
> +    add \reg, pv_off
.macro get_phy, reg, symbol, _pvoff
    ldr \reg, =\symbol
    add \reg, \_pvoff
.endm
/*Calculate the offset between the physical address and the virtual address of the "_reset".*/
.macro get_pvoff, tmp, out
    ldr     \tmp, =_reset
    adr     \out, _reset
    sub     \out, \out, \tmp
.endm

2024-03-01 07:22 UTC, messigogogo commented on libcpu/arm/cortex-a/start_gcc.S
> +    add \reg, pv_off
这两个函数修改成这样可以吗？

2024-03-01 07:23 UTC, messigogogo commented on libcpu/arm/cortex-a/start_gcc.S
> +    get_pvoff r2,r1
您有时间再检查一下

2024-03-01 07:26 UTC, messigogogo commented on libcpu/arm/cortex-a/start_gcc.S
> +.endm
.macro get_pvoff, tmp, out
ldr \tmp, =_reset
adr \out, _reset
sub \out, \out, \tmp
.endm

2024-03-01 07:27 UTC, messigogogo commented on libcpu/arm/cortex-a/start_gcc.S
> +    get_pvoff r2,r1
请您再检查一下

2024-03-01 07:37 UTC, polarvid approved these changes

2024-03-01 07:40 UTC, polarvid commented on libcpu/arm/cortex-a/start_gcc.S
> +    get_pvoff r2,r1
我没别的建议了 👍

2024-03-02 08:06 UTC, BernardXiong approved these changes

2024-03-02 08:06 UTC, merged