[bsp][hmi-board] Optimize hardware hardware driver configuration, add attach check
RT-Thread/rt-thread pull request #8520
Opened 2024-02-01 08:30 UTC by kurisaW

## 拉取/合并请求描述：(PR description)

[
1.优化Kconfig文件中的功能归类
2.为hmi-board添加attaching检查
3.修复env下无法使用startup_check.py脚本问题
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-02-01 23:07 UTC, mysterywolf requested changes

2024-02-01 23:07 UTC, mysterywolf commented on bsp/renesas/ra6m3-hmi-board/.ci/attachconfig/online-packages/lvgl_demo.attach
> +CONFIG_BSP_USING_LVGL_VIDEO_DEMO=y
这种红圆圈的要加个回车

2024-02-02 01:54 UTC, kurisaW commented on bsp/renesas/ra6m3-hmi-board/.ci/attachconfig/online-packages/lvgl_demo.attach
> +CONFIG_BSP_USING_LVGL_VIDEO_DEMO=y
好的，下次会注意的

2024-02-03 03:25 UTC, mysterywolf commented on bsp/renesas/ra6m3-hmi-board/rtconfig.h
> +#define RT_USING_DFS_DEVFS
这些为啥都默认使能了呀

2024-02-03 03:31 UTC, kurisaW commented on bsp/renesas/ra6m3-hmi-board/rtconfig.h
> +#define RT_USING_DFS_DEVFS
这个是我不小心提交上去的，不应该修改

然后刚刚我也测试了，现在就默认瑞萨只保留最基本的配置（串口和io），用户只需要打开fsp生成一下代码就可以了

2024-02-03 03:48 UTC, mysterywolf approved these changes

2024-02-03 06:38 UTC, Rbb666 commented
@kurisaW 压扁成一个commit吧，我看好多commits

2024-02-03 06:49 UTC, kurisaW commented
@Rbb666 欧克了

2024-02-03 08:47 UTC, merged