[bsp][cvitek]: add c906_little i2c driver
RT-Thread/rt-thread pull request #8535
Opened 2024-02-14 13:37 UTC by Z8MAN8

## 拉取/合并请求描述：(PR description)

[

通过逻辑分析仪测试波形
#### 为什么提交这份PR (why to submit this PR)
为milkv-duo小核c906添加硬件i2c驱动

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-02-14 13:41 UTC, Z8MAN8 commented
![Uploading 2024-02-14 21-40-15屏幕截图.png…]()

2024-02-14 14:04 UTC, Z8MAN8 commented
![image](https://github.com/RT-Thread/rt-thread/assets/95859513/fafa5cde-53be-45f7-8b7b-cc54a02eb480)

2024-02-14 23:02 UTC, mysterywolf commented on bsp/cvitek/c906_little/board/Kconfig
> +            int
这个没有写描述，是故意不暴露给用户的嘛？

2024-02-15 03:00 UTC, Z8MAN8 commented on bsp/cvitek/c906_little/board/Kconfig
> +            int
不暴露给用户，仅便于应对大小核中断不一致的情况

2024-02-15 04:11 UTC, mysterywolf commented on bsp/cvitek/c906_little/board/Kconfig
> +            int
OK~

2024-02-15 04:13 UTC, mysterywolf requested changes

2024-02-15 04:13 UTC, mysterywolf commented on bsp/cvitek/drivers/drv_hw_i2c.c
> +            printf("len=%d, ic status is not TFNF\n", len);
这里不要用printf 这个函数太要命了，换成LOG_E，参考STM32

2024-02-15 04:13 UTC, mysterywolf commented on bsp/cvitek/drivers/drv_hw_i2c.h
> +#include "rtdevice.h"
```suggestion
#include <rtdevice.h>
```
只需要rtdevice.h即可 里边包含了rtthread.h

2024-02-15 04:27 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_hw_i2c.c
> +            printf("len=%d, ic status is not TFNF\n", len);
`#define printf LOG_I` 因为该驱动主要基于官方sdk，我想尽可能保持一致，printf 通过局部宏定义替换为 LOG_I

2024-02-15 04:29 UTC, mysterywolf commented on bsp/cvitek/drivers/drv_hw_i2c.c
> +            printf("len=%d, ic status is not TFNF\n", len);
这块还是用LOG_I吧 SDk是SDK 底层驱动是底层驱动。

2024-02-15 23:05 UTC, mysterywolf approved these changes

2024-02-15 23:05 UTC, merged