Sync smart & scheduler codes
RT-Thread/rt-thread pull request #8537
Opened 2024-02-18 02:46 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-02-19 02:11 UTC, Guozhanxin commented on include/rtdef.h
> +    struct {
有些编译器是不支持匿名结构体的，比如keil

2024-02-19 02:23 UTC, Guozhanxin commented
改动这么大，是不是有些测试结果给出来，是不是确实优化了，性能提高了多少😂

2024-02-19 07:18 UTC, geniusgogo commented on components/drivers/ipc/completion.c
> +#define COMPLETION_NEW_STAT(thread, flag) (((flag) & 1) | (((rt_base_t)thread) & ~1))
这里是用线程对象地址的地位做状态，高位是用来存线程对象地址？ 最好给出相应的注释？

2024-02-19 09:39 UTC, geniusgogo commented on src/kservice.c
> +            critical_level = rt_enter_critical();
不开RT_USING_DEBUG这个变量每啥用？会有警告

2024-02-19 09:39 UTC, geniusgogo commented on components/drivers/ipc/dataqueue.c
> +    rt_hw_interrupt_enable(level);
这个中断使能太突然了，看起来很奇葩。 虽然可能是想提前释放上面自旋锁关闭的中断，但看起来真怪啊。

2024-02-19 09:39 UTC, geniusgogo commented on include/rtdef.h
> -#if defined(__ARMCC_VERSION)        /* ARM Compiler */
现在rtdef.h和rttypes.h如何区分的？

2024-02-19 10:06 UTC, polarvid commented on src/kservice.c
> +            critical_level = rt_enter_critical();
已加入 RT_UNUSED

2024-02-20 02:51 UTC, mysterywolf requested changes
我阻塞一下合入按钮，这个准备好了麻烦让我review一下

2024-02-20 02:57 UTC, mysterywolf commented on components/drivers/ipc/SConscript
> +group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_DEVICE_IPC'], CPPPATH = CPPPATH, LOCAL_CPPDEFINES=['__RTT_IPC_SOURCE__'])
1. 不要在正式场合用RTT这个缩写，这是个私下称呼
2. 最好用Kconfig RT_USINGxxx 

只是建议，我不清楚你实际遇到了什么问题，可以反驳

2024-02-20 13:35 UTC, polarvid commented
# 新增 UTEST 结果

| 测试项目 | 配置 | 状态 (patch 后) | 状态 (patch 前) |
| -------- | ---- | ------------- | ------------- |
| scheduler.mtx | qemu aa64, RT_USING_SMP, RT_CPUS_NR=4 | PASSED | 内核崩溃 |
| scheduler.sem | qemu aa64, RT_USING_SMP, RT_CPUS_NR=4 | PASSED ||
| scheduler.sem | qemu a9, RT_USING_SMP, RT_CPUS_NR=2 | PASSED ||
| scheduler.sem | qemu a9, RT_USING_SMP, RT_CPUS_NR=1 | PASSED ||
| scheduler.sem | qemu a9, RT_CPUS_NR=1 | PASSED ||
| scheduler.sem | qemu rv64, RT_CPUS_NR=1 | PASSED ||
| scheduler.timed_mtx | qemu aa64, RT_USING_SMP, RT_CPUS_NR=4 | PASSED | 内核崩溃 |
| scheduler.timed_sem | qemu aa64, RT_USING_SMP, RT_CPUS_NR=4 | PASSED ||
| scheduler.thread | qemu aa64, RT_USING_SMP, RT_CPUS_NR=4 | PASSED ||

2024-02-21 05:18 UTC, mysterywolf commented
麻烦基于最新基线重新rebase一下 并通过CI

2024-02-21 09:33 UTC, polarvid commented on components/drivers/ipc/SConscript
> +group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_DEVICE_IPC'], CPPPATH = CPPPATH, LOCAL_CPPDEFINES=['__RTT_IPC_SOURCE__'])
`__RTT_IPC_SOURCE__` 这个宏是放在 `/src/` 目录下所有编译文件的预定义宏。目的是有一个宏区分源码的来源仓库，并通过这个区分隔离 API，起到类似命名空间的效果。

比如 `rt_sched` 开头的 API 就只能在特定的命名空间下可见。

2024-02-21 09:37 UTC, polarvid commented on include/rtdef.h
> -#if defined(__ARMCC_VERSION)        /* ARM Compiler */
这个从应用代码应该都是引用 `rtthread.h` 的吧。区分开来主要是 `rtthread.h` 本身容易触发交叉引用。比如 `cpuport.h` 这种只想引入最基本的编译器宏。尽量可以减轻粒度。

大部分时候，在 `.c` 还是直接 include rtthread.h。

2024-02-21 14:32 UTC, BernardXiong commented on components/drivers/ipc/SConscript
> +group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_DEVICE_IPC'], CPPPATH = CPPPATH, LOCAL_CPPDEFINES=['__RTT_IPC_SOURCE__'])
`__RTT_`方式也可以，或者简单些 `__RT_`也行

2024-02-21 14:33 UTC, BernardXiong commented on components/drivers/ipc/completion.c
> +    if (COMPLETION_FLAG(completion) != RT_COMPLETED)
这类的宏定义建议还是加`RT_` -> `RT_COMPLETION_FLAG`，否则担心可能会出现重复定义的问题？

2024-02-21 14:36 UTC, BernardXiong commented on components/drivers/ipc/dataqueue.c
> +    level = rt_spin_lock_irqsave(&(queue->spinlock));
这样做有些类似于对整个链表的操作都处于关irq的状态下进行，这个时候这个链表有多长，则关闭irq的时间也就有多长，变成了O(n)

2024-02-21 14:56 UTC, BernardXiong commented on components/vbus/prio_queue.c
>          rt_base_t level = rt_hw_interrupt_disable();
vbus已经用处不大了，可以推出历史舞台了。

2024-02-21 15:01 UTC, BernardXiong commented on src/scheduler_comm.c
> +rt_err_t rt_sched_thread_bind_cpu(struct rt_thread *thread, int cpu)
感觉这个_mp.c中更好，然后_up.c可以加个空函数保持兼容。

2024-02-21 22:20 UTC, mysterywolf commented on components/drivers/ipc/SConscript
> +group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_DEVICE_IPC'], CPPPATH = CPPPATH, LOCAL_CPPDEFINES=['__RTT_IPC_SOURCE__'])
感觉__RT_xx更好

2024-02-21 23:00 UTC, mysterywolf requested changes

2024-02-22 10:02 UTC, polarvid commented on src/cpu.c
> +#ifdef RT_USING_DEBUG
有两个不同的 debug。一个是 spinlock 的安全检查。另一个是 `rt_enter_critical` 的安全检查。分别通过 `RT_USING_DEBUG` 和 `RT_DEBUGING_SPINLOCK` 开启。

```c
#if defined(RT_DEBUGING_SPINLOCK)
            _cpus_lock_owner = __OWNER_MAGIC;
            _cpus_lock_pc = RT_NULL;
#endif /* RT_DEBUGING_SPINLOCK */
#ifdef RT_USING_DEBUG
            critical_level = _cpus_critical_level;
            _cpus_critical_level = 0;
#endif /* RT_USING_DEBUG */
```

2024-02-22 17:30 UTC, mysterywolf commented on src/cpu.c
> +#ifdef RT_USING_DEBUG
RT_USING_DEBUG 是个总开关，这个确认是总开关就开启就行~

2024-02-22 17:30 UTC, mysterywolf commented on components/vbus/prio_queue.c
>          rt_base_t level = rt_hw_interrupt_disable();
那就直接把这个vbus文件夹删了吧？

2024-02-23 01:35 UTC, polarvid commented on components/vbus/prio_queue.c
>          rt_base_t level = rt_hw_interrupt_disable();
这个 PR 里面就不动了吧。原本修改的就挺多了。

2024-02-23 01:37 UTC, mysterywolf commented on components/vbus/prio_queue.c
>          rt_base_t level = rt_hw_interrupt_disable();
OK

2024-02-23 01:38 UTC, mysterywolf approved these changes
我关心的问题已经都解决。

2024-02-23 01:43 UTC, BernardXiong approved these changes

2024-02-23 01:48 UTC, geniusgogo commented on bsp/qemu-vexpress-a9/applications/main.c
> +    rt_kprintf("Hello RT-Thread!\n");
现在内核里用printf和rt_kprintf的讲究是啥？

2024-02-23 01:49 UTC, mysterywolf commented on bsp/qemu-vexpress-a9/applications/main.c
> +    rt_kprintf("Hello RT-Thread!\n");
尽量用rt_kprintf吧 这个只是编程习惯~ printf里边乱七八糟一堆东西不可控

2024-02-23 01:49 UTC, polarvid commented on bsp/qemu-vexpress-a9/applications/main.c
> +    rt_kprintf("Hello RT-Thread!\n");
musl 工具链会串到 stdio 那个地方，然后跑飞了。

2024-02-23 01:50 UTC, mysterywolf commented on bsp/qemu-vexpress-a9/applications/main.c
> +    rt_kprintf("Hello RT-Thread!\n");
如果是我 我也不用printf，这玩意完全依赖第三方libc。

2024-02-23 01:52 UTC, BernardXiong commented on bsp/qemu-vexpress-a9/applications/main.c
> +    rt_kprintf("Hello RT-Thread!\n");
后面mlibc需要提上日程了，smart最终还得依赖于mlibc的

2024-02-23 01:53 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs_pcache.c
> +        RT_ASSERT(0);
不如将RT_ASSERT在不开debug的选项的时候让他求表达式，例如:
```c
#define RT_ASSERT(EX)                                                         \
do { \
     rt_base_t val; \
     val = (exp); \
} while (0)
```
因为ASSERT是对值进行断言，如果调用者使用了复合表达式，那应该要执行他的符合表达式。

2024-02-23 01:55 UTC, polarvid commented on components/dfs/dfs_v2/src/dfs_pcache.c
> +        RT_ASSERT(0);
这个变量不使用的话，编译器还是可以优化掉的吧

2024-02-23 01:58 UTC, polarvid commented on bsp/qemu-vexpress-a9/applications/main.c
> +    rt_kprintf("Hello RT-Thread!\n");
现在还有个头文件的问题。仓库里面不同的 BSP 用的工具链自带的头文件，因为跨架构，有些甚至是直接拿的 x86 Linux ，存在很多不兼容的定义。比如 `time.h` 里面的 `struct timeval`。

2024-02-23 01:59 UTC, geniusgogo commented on components/dfs/dfs_v2/src/dfs_pcache.c
> +        RT_ASSERT(0);
不过感觉这样改会有兼容性问题，还是先别动了，可以做为一个讨论。

2024-02-23 01:59 UTC, BernardXiong commented on components/dfs/dfs_v2/src/dfs_pcache.c
> +        RT_ASSERT(0);
还是建议不要在ASSERT内写太复杂的计算，而更多是判断。所以，最好也用不ASSERT的方式编译过代码，运行过代码。

未来也可以加入，RT_ASSERT_RET(condition, ret)的方式来处理condition不满足时应该返回，跳出函数的处理。

2024-02-23 02:04 UTC, geniusgogo commented on components/lwp/lwp_internal.h
> +#define DEF_RETURN_CODE(name)   rt_err_t name;RT_UNUSED(name)
这类宏都可以加前缀来标识使用范围，例如LWP_RET_CODE

2024-02-23 02:11 UTC, geniusgogo commented on include/rtsched.h
> +#define SCHED_PRIV(thread) ((thread)->sched_thread_ctx.sched_thread_priv)
建议对所有宏定义进行排查一下，命名上准寻规范：
1. 全局公共的建议用RT_开头
2. 模块公共的建议用 模块名开头，例如 LWP、MM，容易冲突的建议也可加上RT_前缀，例如RT_LWP_, RT_MM_,RT_SCHED_。
3. 私有的宏定义建议下划线开头

2024-02-23 02:13 UTC, geniusgogo commented on src/SConscript
> +group = DefineGroup('Kernel', src, depend=[''], CPPPATH=inc, CPPDEFINES=['__RTTHREAD__'], LOCAL_CFLAGS=LOCAL_CFLAGS, LOCAL_CPPDEFINES=['__RTTHREAD_SOURCE__'])
既然要用__RTTHREAD_SOURCE__，可以斟酌一下，是否可以用__RT_KERNEL_SOURCE__

2024-02-23 02:14 UTC, mysterywolf commented on src/SConscript
> +group = DefineGroup('Kernel', src, depend=[''], CPPPATH=inc, CPPDEFINES=['__RTTHREAD__'], LOCAL_CFLAGS=LOCAL_CFLAGS, LOCAL_CPPDEFINES=['__RTTHREAD_SOURCE__'])
我觉得这个建议可以的~

2024-02-23 02:14 UTC, mysterywolf commented on include/rtsched.h
> +#define SCHED_PRIV(thread) ((thread)->sched_thread_ctx.sched_thread_priv)
赞同！

2024-02-23 02:30 UTC, geniusgogo commented on components/drivers/ipc/completion.c
> +            LOG_D("%s: failed to resume thread", __func__);
在调试等级变化的时候，这是一条空语句？error变得没啥意义，会有编译警告吗？

2024-02-23 02:32 UTC, polarvid commented on components/drivers/ipc/completion.c
> +            LOG_D("%s: failed to resume thread", __func__);
这种不会的，空语句就是空了，直接优化掉。像无副作用的表达式才会警告。

2024-02-23 03:41 UTC, mysterywolf commented on components/dfs/dfs_v2/src/dfs_pcache.c
> +        RT_ASSERT(0);
RT_ASSERT_RET(condition, ret) 好建议~

2024-02-23 09:24 UTC, polarvid commented
> 改动这么大，是不是有些测试结果给出来，是不是确实优化了，性能提高了多少😂

这个 PR 主要是功能修复和 smart 的 IPC 研发分支同步。功能在 qemu aa64, a9, rv64 以及星火一号，rpi4b 64 平台上面测试过所有的内核 UTEST。新加入的 UTEST 结果参考 https://github.com/RT-Thread/rt-thread/pull/8537#issuecomment-1954231378 。

性能方面，cyclictest 的 MIN/AVG 指标分别有 42.31%/41.94% 的优化，MAX 降低了 50.77%； iperf 在多核平台下测试，带宽抖动明显减小。

2024-02-23 09:32 UTC, geniusgogo approved these changes

2024-02-23 09:49 UTC, merged