[components/driver] update serial
RT-Thread/rt-thread pull request #8567
Opened 2024-02-29 04:53 UTC by fangjianzhou

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-02-29 06:15 UTC, geniusgogo requested changes

2024-02-29 06:15 UTC, geniusgogo commented on components/drivers/serial/serial_dm.c
> +            cfg.data_bits = *str;
这里应该是*str - '0'??

2024-02-29 06:15 UTC, geniusgogo commented on components/drivers/serial/serial_dm.c
> +    while (*str && *str != ',' && *str != ' ')
这个while体可能要改良成下面这样：
```c
    while (*str)
    {
        if ((*str >= 'a' && *str <= 'f') || (*str >= 'A' && *str <= 'F'))
        {
            base = (base << 4) | (((*str | ' ') - 'a') + 10);
        }
        else if (*str >= '0' && *str <= '9')
        {
            base = (base << 4) | (*str - '0');
        }
        else break;

        ++str;
    }
```

2024-02-29 09:15 UTC, geniusgogo approved these changes

2024-03-01 00:24 UTC, mysterywolf commented
可以稍微增加一下描述吗 这个PR的主要目的是什么，在这么BSP上测试过

2024-03-01 02:29 UTC, merged