Add GCC generalized atomic operation function
RT-Thread/rt-thread pull request #8648
Opened 2024-03-20 20:46 UTC by atwwww

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
Add GCC generalized atomic operation function

#### 你的解决方案是什么 (what is your solution)
override four gcc built-in functions as follows:
void __atomic_load (size_t size, void *mem, void *return, int model);
void __atomic_store (size_t size, void *mem, void *val, int model);
void __atomic_exchange (size_t size, void *mem, void *val, void *return, int model);
bool __atomic_compare_exchange (size_t size, void *obj, void *expected, void *desired, int success, int failure);

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:
bsp\stm32\stm32f407-atk-explorer

- .config:
#define RT_USING_CPLUSPLUS
#define RT_USING_CPLUSPLUS11

- action:
![image](https://github.com/RT-Thread/rt-thread/assets/81611821/3c6baded-54fe-47af-84f0-e3f8fb743916)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-03-20 20:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8648) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8648) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8648) it.</sub>

2024-03-20 22:20 UTC, mysterywolf requested changes
please use rt_memcpy to replace memcpy

2024-03-20 22:20 UTC, mysterywolf commented on components/libc/cplusplus/cpp11/atomic_8.c
> +    memcpy(_return, mem, size);
```suggestion
    rt_memcpy(_return, mem, size);
```

2024-03-20 22:20 UTC, mysterywolf commented on components/libc/cplusplus/cpp11/atomic_8.c
> +    memcpy(mem, val, size);
```suggestion
    rt_memcpy(mem, val, size);
```

2024-03-22 06:10 UTC, atwwww commented on components/libc/cplusplus/cpp11/atomic_8.c
> +    memcpy(_return, mem, size);
already corrected

2024-03-22 06:11 UTC, atwwww commented on components/libc/cplusplus/cpp11/atomic_8.c
> +    memcpy(mem, val, size);
already corrected in newest status

2024-03-25 03:00 UTC, mysterywolf approved these changes

2024-03-25 03:01 UTC, merged