Add some comments
RT-Thread/rt-thread pull request #8694
Opened 2024-03-29 10:47 UTC by TroyMitchell911

## 拉取/合并请求描述：(PR description)

[
modified:   components/libc/posix/io/mman/mman.c           Add all function comments
modified:   components/libc/posix/io/mman/sys/mman.h    Add comments for all macros
modified:   components/libc/posix/io/poll/poll.c                   Add all function comments and comments to structure members
modified:   components/libc/posix/io/poll/poll.h                  Add all macro comments and comments to structure members
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-03-29 16:18 UTC, mysterywolf requested changes

2024-03-29 16:18 UTC, mysterywolf commented on components/libc/posix/io/poll/poll.h
> + * 2024/03/29     TroyMitchelle     Add all macro comments and comments to structure members
```suggestion
 * 2024-03-29     TroyMitchelle     Add all macro comments and comments to structure members
```

2024-03-29 16:18 UTC, mysterywolf commented on components/libc/posix/io/poll/poll.h
> +
```suggestion
```

2024-03-29 16:18 UTC, mysterywolf commented on components/libc/posix/io/poll/poll.c
> +struct rt_poll_node {
```suggestion
struct rt_poll_node
{
```

2024-03-30 04:48 UTC, mysterywolf commented
你好，请修改以上问题，我是每个问题各列举了一个

2024-03-30 10:12 UTC, TroyMitchell911 commented
我明天将会修改

2024-04-01 02:52 UTC, mysterywolf requested changes

2024-04-01 02:52 UTC, mysterywolf commented on components/libc/posix/io/poll/poll.h
> +
这里多加了一个空行请删掉

2024-04-01 02:52 UTC, mysterywolf commented on components/libc/posix/io/mman/mman.c
> +}
这里不需要修改，请多按一个回车保持留出**一个**空行

2024-04-02 03:17 UTC, mysterywolf approved these changes

2024-04-02 03:17 UTC, mysterywolf approved these changes

2024-04-02 03:18 UTC, merged