Update SConscript
RT-Thread/rt-thread pull request #8705
Opened 2024-03-31 11:00 UTC by zealsoftstudio

添加编译 drv_eth.c 的选项

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
即使在.config中选择了CONFIG_RT_USING_PHY=y，drv_eth.c文件也不会被编译，从而导致网络驱动程序无法加载。

#### 你的解决方案是什么 (what is your solution)

修改SConscript文件，添加两行代码以保证drv_eth.c文件会被编译。已经在FRDM-MCXN947开发板上进行了验证。

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp\nxp\mcx\mcxn\frdm-mcxn947

- .config: CONFIG_RT_USING_PHY=y

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [X] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [X] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [X] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [X] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [X] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [X] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [X] 代码是高质量的 Code in this PR is of high quality
- [X] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-03-31 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8705) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8705) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8705) it.</sub>

2024-04-01 02:50 UTC, mysterywolf requested changes

2024-04-01 02:50 UTC, mysterywolf commented on bsp/nxp/mcx/mcxn/Libraries/drivers/SConscript
> +if  GetDepend('RT_USING_PHY'):
这个位置应该用BSP_USING_ETH ，并在对应的BSP Kconfig里定义BSP_USING_ETH 并select RT_USING_PHY https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f407-atk-explorer/board/Kconfig#L107

2024-04-01 13:02 UTC, zealsoftstudio commented on bsp/nxp/mcx/mcxn/Libraries/drivers/SConscript
> +if  GetDepend('RT_USING_PHY'):
我已经按照你的建议使用了BSP_USING_ETH

2024-04-01 22:43 UTC, mysterywolf approved these changes

2024-04-01 22:44 UTC, merged