[bsp][ch32v307v]添加了硬件iic驱动
RT-Thread/rt-thread pull request #8707
Opened 2024-03-31 13:25 UTC by IceBear003

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

添加了CH32V30系列适配RT-Thread的硬件I2C驱动。
Added hardware I2C driver for CH32V30 series adapted to RT-Thread.

#### 你的解决方案是什么 (what is your solution)

根据CH32V30数据手册、I2C总线协议和RT-Thread提供的I2C总线接口实现适配
Implement adaptation based on the CH32V30 datasheet, I2C bus protocol and the I2C bus interface provided by RT-Thread.

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

bsp/wch/risc-v/ch32v307v-r1

- .config:

添加了 drv_i2c.h 和 drv_i2c.c 文件；
修改了 rt-thread/bsp/wch/risc-v/ch32v307v-r1/board 目录下的 Kconfig 文件；
修改了 rt-thread/bsp/wch/risc-v/Libraries/ch32_drivers 目录下的 SConscript 文件。

- action:

https://github.com/IceBear003/rt-thread/actions/runs/8498460155

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-03-31 13:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8707) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8707) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8707) it.</sub>

2024-04-01 02:51 UTC, mysterywolf requested changes

2024-04-01 02:51 UTC, mysterywolf commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_i2c.c
> +
注释头请参见其他驱动文件，请使用标准注释头

2024-04-01 04:32 UTC, IceBear003 commented on bsp/wch/risc-v/Libraries/ch32_drivers/drv_i2c.c
> +
已修正

2024-04-01 04:40 UTC, mysterywolf approved these changes

2024-04-01 04:40 UTC, merged