improve phy interface driver
RT-Thread/rt-thread pull request #8731
Opened 2024-04-07 01:24 UTC by jiadingxu

Current issue:
The current rt_phy_ops API can not specify phy in multi-phy case

Solution:
Add one parameter phy to specify phy instance

2024-04-07 01:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8731) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8731) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8731) it.</sub>

2024-04-07 01:51 UTC, Rbb666 approved these changes

2024-04-07 03:33 UTC, BernardXiong commented on components/drivers/include/drivers/phy.h
> +   rt_phy_status (*init)(void *object, rt_uint32_t phy_addr, rt_uint32_t src_clock_hz);
3 空格缩进？

2024-04-07 03:33 UTC, BernardXiong requested changes
注意代码风格

2024-04-07 03:36 UTC, Rbb666 commented
可以使用这个python脚本格式化下：https://github.com/mysterywolf/formatting

2024-04-07 05:37 UTC, jiadingxu commented on components/drivers/include/drivers/phy.h
> +   rt_phy_status (*init)(void *object, rt_uint32_t phy_addr, rt_uint32_t src_clock_hz);
好的，已修改！谢谢熊总指出问题。

2024-04-07 05:38 UTC, jiadingxu commented
> @jiadingxu 可以使用这个python脚本格式化下：https://github.com/mysterywolf/formatting

谢谢，后面如果有提交，会预先执行一次。

2024-04-16 23:57 UTC, mysterywolf requested changes

2024-04-16 23:57 UTC, mysterywolf commented on components/drivers/include/drivers/phy.h
> +    rt_uint8_t *reg_list;
这个变量哪里用到了吗

2024-04-16 23:57 UTC, mysterywolf commented on components/drivers/include/drivers/phy.h
> +    rt_phy_status (*get_link_speed_duplex)(rt_phy_t *phy, rt_uint32_t *speed, rt_uint32_t *duplex);
这么改了之后 驱动也需要更改呀

2024-04-18 01:46 UTC, jiadingxu commented on components/drivers/include/drivers/phy.h
> +    rt_uint8_t *reg_list;
原本用于引用不同厂家PHY register的，现在已经删除了（重新提交了PR）

2024-04-18 01:47 UTC, jiadingxu commented on components/drivers/include/drivers/phy.h
> +    rt_phy_status (*get_link_speed_duplex)(rt_phy_t *phy, rt_uint32_t *speed, rt_uint32_t *duplex);
好的，我检查一下其他家的使用情况

2024-04-18 03:38 UTC, jiadingxu commented on components/drivers/include/drivers/phy.h
> +    rt_phy_status (*get_link_speed_duplex)(rt_phy_t *phy, rt_uint32_t *speed, rt_uint32_t *duplex);
已修改涉及到相关API的调用入参

2024-04-30 22:53 UTC, mysterywolf commented
我没有看懂 这个PR的代码在哪里使用了 增加了一个参数，然后全都赋值为NULL

2024-05-14 07:25 UTC, jiadingxu commented
> 我没有看懂 这个PR的代码在哪里使用了 增加了一个参数，然后全都赋值为NULL

我来自HPMicro，当前的改动是为了我们后续口/双以太网PHY的支持做准备，所以在当前的main line上看不来在哪里使用。等这个PR合入后，其余代码也会跟随 PR。

2024-05-14 07:40 UTC, jiadingxu commented
> 我没有看懂 这个PR的代码在哪里使用了 增加了一个参数，然后全都赋值为NULL
您好！我来自HPMicro,这次PR的主要目的是为双网口/双以太网PHY做准备，待此次PR合入后，HPMirco 最新BSP的demo(包含双网口)也即将提交PR至RTThread。

2024-05-26 03:21 UTC, jiadingxu commented
@Rbb666 @mysterywolf @BernardXiong 各位好！我们HPM后面的基于双网口的PR会依赖的当前这个PR。

2024-05-26 05:45 UTC, Rbb666 approved these changes

2024-05-28 05:09 UTC, Rbb666 commented
@BernardXiong 熊大你看下这个PR，没问题就合并了吧

2024-05-29 14:22 UTC, merged