Increased the limit on the number of messages
RT-Thread/rt-thread pull request #8796
Opened 2024-04-15 02:41 UTC by zmq810150896

## 拉取/合并请求描述：(PR description)
添加AF_UNIX协议的消息数量限制(类似于网络滑动窗口大小)

#### 你的解决方案是什么 (what is your solution)
添加一个计数器对消息读写计数

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-04-16 23:58 UTC, mysterywolf requested changes

2024-04-16 23:58 UTC, mysterywolf commented on components/net/sal/include/sal_msg.h
> +    rt_atomic_t msg_count;
在哪里用到了呢？

2024-04-17 10:51 UTC, zmq810150896 commented on components/net/sal/include/sal_msg.h
> +    rt_atomic_t msg_count;
socket中的AF_UNIX协议中

2024-04-17 12:56 UTC, geniusgogo approved these changes

2024-04-18 01:33 UTC, mysterywolf commented on components/net/sal/include/sal_msg.h
> +    rt_atomic_t msg_count;
使用源码的链接贴一下？我搜了半天没搜到

2024-04-18 08:34 UTC, zmq810150896 commented on components/net/sal/include/sal_msg.h
> +    rt_atomic_t msg_count;
这是ukernel里面的，还需要粘贴吗

2024-04-18 22:16 UTC, mysterywolf commented on components/net/sal/include/sal_msg.h
> +    rt_atomic_t msg_count;
是的贴出来。链接发出来一下。

2024-04-19 00:40 UTC, BernardXiong approved these changes

2024-04-19 01:51 UTC, mysterywolf approved these changes

2024-04-19 01:51 UTC, merged

2024-04-19 02:29 UTC, zmq810150896 commented on components/net/sal/include/sal_msg.h
> +    rt_atomic_t msg_count;
[mr链接](https://git.rt-thread.com/packages/ukernel/-/merge_requests/95/diffs)