refactor(drivers/usb):replace rtt usb stack with cherryusb
RT-Thread/rt-thread pull request #8799
Opened 2024-04-15 14:22 UTC by sakumisu

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-04-15 15:11 UTC, BernardXiong commented
目录结构上没问题，不过代码头的版权协议建议仔细捋捋

2024-04-15 15:18 UTC, sakumisu commented
> 目录结构上没问题，不过代码头的版权协议建议仔细捋捋

指的是文件里缺失license的地方吗

2024-04-16 01:48 UTC, BernardXiong commented
> > 目录结构上没问题，不过代码头的版权协议建议仔细捋捋
> 
> 指的是文件里缺失license的地方吗

是的，一些文件是没有版权信息的，这样容易引起纠纷

2024-04-22 13:56 UTC, BernardXiong requested changes
keep the old if as a package

2024-04-23 00:34 UTC, mysterywolf requested changes

2024-04-23 00:34 UTC, mysterywolf commented on components/drivers/usb/cherryusb/Kconfig
> +       default "v0.10.2"   if RT_USING_CHERRYUSB_V001002
版本这个还是放在软件包里吧，这里都删掉 从267-290

2024-04-23 00:34 UTC, mysterywolf commented on components/drivers/usb/cherryusb/Kconfig
> +    bool "CherryUSB: tiny and portable USB host/device stack for embedded system with USB IP"
```suggestion
    bool "CherryUSB: tiny and portable USB host/device stack for embedded system with USB IP"
    select PKG_USING_CHERRYUSB
```

2024-04-23 00:35 UTC, mysterywolf commented
> keep the old if as a package

啥意思 没懂

2024-04-23 01:58 UTC, mysterywolf approved these changes

2024-04-25 11:46 UTC, yangpengya commented
能不能开放支持不带dma功能的ip做主机使用？

2024-04-25 11:49 UTC, sakumisu commented
> 能不能开放支持不带dma功能的ip做主机使用？

不带dma的ip，功能太弱，中断太频繁，处理太麻烦，很容易出问题，所以不考虑做，我只支持全功能的 IP，多谢

2024-06-02 03:20 UTC, BernardXiong approved these changes

2024-06-02 03:20 UTC, merged