修复C++11 thread_local对象析构函数与实际内存释放动作顺序相反问题
RT-Thread/rt-thread pull request #8802
Opened 2024-04-16 04:02 UTC by atwwww

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
修复C++11 thread_local对象析构函数与实际内存释放动作顺序相反问题
原实现方案缺陷：顺序遍历_pthread_key数组，调用TLS析构函数，这导致可能首先遍历到emutls_key_destructor清除实际分配内存，后续才遍历到对象析构函数，造成use after free内存安全隐患

#### 你的解决方案是什么 (what is your solution)
使用emutls_pthread_key作为标志，从emutls_pthread_key标志前一个index开始倒序遍历

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-04-16 05:19 UTC, atwwww commented
static code analysis似乎误报，提交中未修改对应代码片段：
![image](https://github.com/RT-Thread/rt-thread/assets/81611821/ad6306a3-d40f-4a36-adf8-cdd0597581a4)

![image](https://github.com/RT-Thread/rt-thread/assets/81611821/9b421ea9-63e3-49d2-be24-ed86c041eb02)

RT-Thread BSP Static Build Check / others_at32_hc32和提交也无关联。
![image](https://github.com/RT-Thread/rt-thread/assets/81611821/589905ce-4dff-4a79-a84f-95101d6276ba)

2024-04-18 03:46 UTC, mysterywolf commented
static code analysis 报错请忽略

2024-04-18 03:47 UTC, mysterywolf requested changes

2024-04-18 03:47 UTC, mysterywolf commented on components/libc/posix/pthreads/pthread.c
> +        if (data && _thread_keys[index].destructor)
一句话的条件语句或者for循环也需要用大括号

2024-04-18 03:47 UTC, mysterywolf commented on components/libc/posix/pthreads/pthread.c
> +                    _destroy_item(index, ptd);
大括号

2024-04-18 03:47 UTC, mysterywolf commented on components/libc/posix/pthreads/pthread.c
> +                    _destroy_item(index, ptd);
大括号

2024-04-18 03:47 UTC, mysterywolf commented on components/libc/posix/pthreads/pthread.c
> +
多加了一个无用的空行

2024-04-18 06:06 UTC, atwwww commented on components/libc/posix/pthreads/pthread.c
> +        if (data && _thread_keys[index].destructor)
已修改

2024-04-18 06:06 UTC, atwwww commented on components/libc/posix/pthreads/pthread.c
> +                    _destroy_item(index, ptd);
已修改

2024-04-18 06:06 UTC, atwwww commented on components/libc/posix/pthreads/pthread.c
> +                    _destroy_item(index, ptd);
已修改

2024-04-18 06:07 UTC, atwwww commented on components/libc/posix/pthreads/pthread.c
> +
已删除无用空行

2024-04-18 15:36 UTC, BernardXiong commented on components/libc/cplusplus/cpp11/emutls.c
> +pthread_key_t get_emutls_pthread_key(void)
不是这样命名的， -> `emutls_get_pthread_key`

2024-04-19 10:57 UTC, atwwww commented on components/libc/cplusplus/cpp11/emutls.c
> +pthread_key_t get_emutls_pthread_key(void)
已修改对应函数名和注释

2024-04-24 04:44 UTC, mysterywolf commented
RT-Thread BSP Static Build Check / others_at32_hc32 (pull_request)  这个CI有报错 麻烦修一下

2024-04-24 09:17 UTC, atwwww commented
> RT-Thread BSP Static Build Check / others_at32_hc32 (pull_request) 这个CI有报错 麻烦修一下

这个报错是不开启C++支持时，emutls.c文件没有被编译，新增加的emutls_get_pthread_key找不到。

做了以下修改：
1. 使用“RT_USING_CPLUSPLUS11”宏控制，使得C++11支持打开时，才会进行emutls_get_pthread_key符号的查找。同时精简了不启用C++特性时的目标文件大小。
2. 考虑到C中_Thread_local也会使用emutls，将emutls.c文件移动到posix中，因为emutls依赖于RT_USING_PTHREADS。移动文件后，无论是C还是C++都能够正确使用emutls。

2024-04-27 06:00 UTC, atwwww commented
static code analysis原因：
修改了emutls.c文件位置，ci调用的tools/ci/cpp_check.py脚本找不到移动后的emutls.c文件的位置。

2024-05-11 08:07 UTC, BernardXiong approved these changes

2024-05-11 17:49 UTC, mysterywolf approved these changes

2024-05-11 17:50 UTC, merged