解决LOG_RAW异步输出多条文本的时候会被截断BUG
RT-Thread/rt-thread pull request #8821
Opened 2024-04-19 04:22 UTC by Later-Comer

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

解决LOG_RAW异步输出多条文本的时候会被截断，原因是rt_vsnprintf会在字符串最后添加\0，ulog.c中的do_output()将\0也压入到ulog.async_rb，当LOG_RAW没有及时输出，那么rb中的字符串被\0截断了，导致没法正确输出LOG_RAW信息

#### 你的解决方案是什么 (what is your solution)

修该ulog.c文件，不要将\0压入ulog.async_rb，也就是log_buf_size和fmt_result两个长度不要统计\0

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:  STM32H753，STM32F765

- .config: 没有修改

- action: https://github.com/Later-Comer/rt-thread/actions/runs/8748306763/job/24008140926

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-04-19 04:48 UTC, mysterywolf requested changes

2024-04-19 04:48 UTC, mysterywolf commented on components/utilities/ulog/ulog.c
> +            rt_ringbuffer_put(ulog.async_rb, (const rt_uint8_t *)log_buf, (rt_uint16_t)log_buf_size - 1);
这块直接改成用rt_strnlen来统计会更方便一些

2024-04-19 05:36 UTC, Later-Comer commented on components/utilities/ulog/ulog.c
> +            rt_ringbuffer_put(ulog.async_rb, (const rt_uint8_t *)log_buf, (rt_uint16_t)log_buf_size - 1);
使用rt_strlen的确更方便和直观一些，但是do_output()已经将rt_vsnprintf输出长度传递进来的，从嵌入式资源使用角度来说，更建议直接使用log_buf_size

2024-04-20 02:26 UTC, armink approved these changes

2024-04-20 02:27 UTC, mysterywolf approved these changes

2024-04-20 02:27 UTC, merged