Add an API to get the netdev list
RT-Thread/rt-thread pull request #8860
Opened 2024-04-25 05:05 UTC by zmq810150896

## 拉取/合并请求描述：(PR description)

#### 为什么提交这份PR (why to submit this PR)
主线代码使用ukernel时编译问题

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-04-25 11:30 UTC, BernardXiong commented on components/net/netdev/src/netdev.c
> +    level = rt_spin_lock_irqsave(&_spinlock);
可以想想，怎么来降低spin_lock_irqsave的时间吗？

2024-04-25 11:39 UTC, zmq810150896 commented on components/net/netdev/src/netdev.c
> +    level = rt_spin_lock_irqsave(&_spinlock);
如果只是计算netdev_list的长度，可以的，只需要定义一个原子类型的变量，在每次注册或者删除netdev的时候进行原子操作+1或者-1就可以了

2024-06-04 08:17 UTC, polarvid requested changes

2024-06-04 08:17 UTC, polarvid commented on components/net/netdev/src/netdev.c
> +    err = cb(msg, &nd, nd_num, index, ROUTE_IPV4_TRUE);
没开 NETLINK 的时应该没有这个宏定义，这么处理会编译失败。

2024-06-24 01:58 UTC, zmq810150896 commented on components/net/netdev/src/netdev.c
> +    err = cb(msg, &nd, nd_num, index, ROUTE_IPV4_TRUE);
这个函数加了宏控，不会编译失败的，并且cb是传过来的回调函数，即使没有宏控，编译也不应该会失败的才对

2024-06-24 02:16 UTC, polarvid commented on components/net/netdev/src/netdev.c
> +    err = cb(msg, &nd, nd_num, index, ROUTE_IPV4_TRUE);
是指 `ROUTE_IPV4_TRUE`

2024-09-10 09:01 UTC, zmshahaha commented
使用netdev在链表中的位置作为if_index是不是会导致链表插入或删除时if_index的大幅变动

2024-10-24 03:51 UTC, closed without merging