fix baudrate error
RT-Thread/rt-thread pull request #8873
Opened 2024-04-28 07:01 UTC by xiao-mang

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

When the ART-Pi Smart device is stuck during boot up and cannot access the ash.

#### 你的解决方案是什么 (what is your solution)

fix baudrate error

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:rt-thread/bsp/nxp/imx/imx6ull-smart

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-04-28 07:11 UTC, mysterywolf commented on components/lwp/terminal/linux_ioctl.h
> +/*-
新建一个linux文件夹放进去，include <linux/ioctl.h> 这样会不会更好一些？

2024-04-28 07:15 UTC, BernardXiong commented on components/drivers/serial/serial_tty.c
> +extern speed_t _get_speed(int baudrate);
不能这样干的，或者把它独立出来变成一个API，同时在头文件中进行声明。

2024-04-28 07:18 UTC, BernardXiong commented on components/lwp/terminal/linux_ioctl.h
> + * SPDX-License-Identifier: BSD-2-Clause
这段代码出自linux吗？这个是BSD-2-Clause的许可协议，又有些类似出自BSD。

2024-04-28 09:00 UTC, xiao-mang commented on components/lwp/terminal/linux_ioctl.h
> +/*-
不用这个文件了

2024-04-28 09:01 UTC, xiao-mang commented on components/drivers/serial/serial_tty.c
> +extern speed_t _get_speed(int baudrate);
改掉了

2024-04-28 09:01 UTC, xiao-mang commented on components/lwp/terminal/linux_ioctl.h
> + * SPDX-License-Identifier: BSD-2-Clause
BSD的，不用这个文件了

2024-04-28 15:09 UTC, BernardXiong commented on components/libc/posix/io/termios/termios.h
> +speed_t _get_speed(int baudrate);
代码太随意了

2024-04-28 15:09 UTC, BernardXiong requested changes
处理好`_get_speed`的问题

2024-04-29 09:59 UTC, BernardXiong approved these changes

2024-04-29 10:00 UTC, merged