[timer] With macro compilation, some code is no longer executed when RT_TIMER_SKIP_LIST_LEVEL= 1
RT-Thread/rt-thread pull request #8884
Opened 2024-04-29 14:49 UTC by wdfk-prog

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)

- https://club.rt-thread.org/ask/question/d5c013f9637a6fda.html

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-04-30 14:02 UTC, wdfk-prog commented
- 第二次推送解决如下问题

https://github.com/RT-Thread/rt-thread/issues/8883

2024-04-30 14:08 UTC, wdfk-prog commented
` current_tick = rt_tick_get();` 在软件定时器检测和硬件定时器检测中的调用顺序不同;按我理解没有差别,放入前面运行更为合适

```c
    while (!rt_list_isempty(&timer_list[RT_TIMER_SKIP_LIST_LEVEL - 1]))
    {
        t = rt_list_entry(timer_list[RT_TIMER_SKIP_LIST_LEVEL - 1].next,
                          struct rt_timer, row[RT_TIMER_SKIP_LIST_LEVEL - 1]);

        /* re-get tick */
        current_tick = rt_tick_get();
```

2024-04-30 14:09 UTC, wdfk-prog commented
- 在硬件定时器检测中的该段代码,我认为可以放入外部判断既可;但是没有实际环境测试;这个地方需要检测一下是否合理

```c
#ifdef RT_USING_SMP
    /* Running on core 0 only */
    if (rt_hw_cpu_id() != 0)
    {
        rt_spin_unlock_irqrestore(&_htimer_lock, level);
        return;
    }
#endif
```

2024-04-30 15:02 UTC, polarvid requested changes

2024-05-01 15:16 UTC, BernardXiong commented on src/timer.c
> +#if (RT_TIMER_SKIP_LIST_LEVEL > 1)
这里，如果`RT_TIMER_SKIP_LIST_LEVEL = 1`，下面应该也不执行的。也可以确认下，如果`-O3`编译，下面代码是否会自动移除。如果都是自动的，那么建议不增加条件宏判断。代码中条件宏太多也不太好

2024-05-03 12:14 UTC, wdfk-prog commented on src/timer.c
> +#if (RT_TIMER_SKIP_LIST_LEVEL > 1)
- KEIL AC6 -O3编译后,`RT_TIMER_SKIP_LIST_LEVEL = 1` debug调试下是无法在这两处断点的;
![image](https://github.com/RT-Thread/rt-thread/assets/66928464/0ac23913-1032-499c-a3c5-225deacff24b)
- KEIL AC6 -O3编译后,`RT_TIMER_SKIP_LIST_LEVEL = 3` debug调试下是可以在这两处断点的;
![image](https://github.com/RT-Thread/rt-thread/assets/66928464/23f193c5-d38e-40de-acac-e153bd5316cc)
- 是会自动移除;那我把条件判断去除;

2024-05-04 00:22 UTC, mysterywolf commented on src/timer.c
> +        LOG_D("software timer check enter");
这两个LOG_D要不删了吧 感觉放在这里debug的意义不是很大 确认可以工作之后就可以删除啦？

2024-05-06 02:01 UTC, polarvid approved these changes

2024-05-08 01:27 UTC, BernardXiong approved these changes

2024-05-08 01:27 UTC, BernardXiong commented on src/timer.c
> +        LOG_D("software timer check enter");
应该和调试相关，可以留着方便调试

2024-05-08 01:27 UTC, merged

2024-05-08 01:37 UTC, mysterywolf commented on src/timer.c
> +        LOG_D("software timer check enter");
这几个log是嵌套在一起的 而且会刷屏，应该是历史遗留问题 https://github.com/RT-Thread/rt-thread/pull/8915