add support for thread usage
RT-Thread/rt-thread pull request #8918
Opened 2024-05-08 09:14 UTC by Dyyt587

## 拉取/合并请求描述：(PR description)

#### 为什么提交这份PR (why to submit this PR)
对调度器添加虚函数以支持cpu线程占用率测量，已有软件包仅提供总的cpu占用测量，且占用钩子函数，不满足实际需要

#### 你的解决方案是什么 (what is your solution)
添加两个虚函数实现对每个线程cpu占用率的测量，且保留钩子函数并不占用，以提高扩展性。采用钩子链表可解决钩子函数占用问题但是将导致量钩子相关函数被重写，对内核文件改动过大过于复杂

#### 请提供验证的bsp和config (provide the config and bsp) 

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [X] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [X] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [X 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [X] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [X] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [X] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [X] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-05-08 11:45 UTC, BernardXiong requested changes
需要支持到多核，同时相关代码放`components/utils/cpuusage`中

2024-09-29 08:32 UTC, a1012112796 commented on components/utilities/cpuusage/cpuusage.c
> +    to->last_start_tick = rt_tick_get();
建议参考 FMT 的算法设计，用更高精度的时间戳去计算时间间隔 

https://github.com/Firmament-Autopilot/FMT-Firmware/blob/9de2ddb736ceaea09b4ecc36a6b5bb151436404a/src/module/system/statistic.c#L65

rt-thread 最新添加的 ktme 就挺合适的。
https://github.com/RT-Thread/rt-thread/blob/d0cf64631a6011c07f1d19f1b8eae96e84a5bf5c/components/drivers/ktime/inc/ktime.h#L37-L44

2024-09-29 08:36 UTC, Dyyt587 commented on components/utilities/cpuusage/cpuusage.c
> +    to->last_start_tick = rt_tick_get();
感谢提供的建议，我会采纳并修改

2025-01-02 09:20 UTC, Rbb666 commented on components/utilities/cpuusage/cpuusage.c
> +    to->last_start_tick = rt_tick_get();
@Dyyt587 这个PR还在跟进吗？

2025-01-02 09:38 UTC, Dyyt587 commented on components/utilities/cpuusage/cpuusage.c
> +    to->last_start_tick = rt_tick_get();
目前没有更进了

2025-03-26 08:44 UTC, a1012112796 commented
话说这个 PR 是不是和已经合并的 https://github.com/RT-Thread/rt-thread/pull/8947 重复了？

2025-08-30 05:11 UTC, Rbb666 commented
https://github.com/RT-Thread/rt-thread/pull/10644

2025-08-30 05:11 UTC, closed without merging