fix specified network card not taking effect with msh's ping error
RT-Thread/rt-thread pull request #8937
Opened 2024-05-11 09:09 UTC by xiao-mang

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

Specified network card not taking effect with msh's ping.

#### 你的解决方案是什么 (what is your solution)

When isbind is TRUE, use lwip_setsockopt's SO_BINDTODEVICE option to set.

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:rt-thread/bsp/nxp/imx/imx6ull-smart

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-05-11 17:43 UTC, mysterywolf requested changes

2024-05-11 17:43 UTC, mysterywolf commented on bsp/nxp/imx/imx6ull-smart/drivers/board.c
> +    #ifdef RT_DEBUGING_ASSERT
```suggestion
#ifdef RT_DEBUGING_ASSERT
```

2024-05-11 17:43 UTC, mysterywolf commented on bsp/nxp/imx/imx6ull-smart/drivers/board.c
> +    #endif
```suggestion
#endif
```

2024-05-13 07:48 UTC, BernardXiong approved these changes

2024-05-13 11:34 UTC, geniusgogo commented on components/net/netdev/src/netdev.c
> -        netdev = netdev_get_first_by_flags(NETDEV_FLAG_LINK_UP);
这里需要注意和讨论一下：当指定网卡的情况下，指定的网卡不能ping通（非UP状态），那需不需要选用一个UP状态的网卡来ping?

2024-05-15 02:46 UTC, mysterywolf approved these changes

2024-05-16 07:43 UTC, merged