[fix]fixtmpfs bug
RT-Thread/rt-thread pull request #8970
Opened 2024-05-21 01:59 UTC by zhuzhuzhus

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
在测试文件系统时发现在将/etc下的文件拷贝到/tmp下时：
能够正常读出文件，但是写入的时候就会有问题
在将/tmp下的文件拷贝至/tmp文件夹下时，读写都会出现问题，所以推断出tmpfs下读写都会出现问题，所以用qemu跟了一下读写该文件系统的过程。

#### 你的解决方案是什么 (what is your solution)

tmp文件系统读写过程中，执行dfs_tmpfs_read时，由于file->vnode->size是无符号类型，所以在进行if(count < file->vnode->size - *ops)这一步时会导致如果size小于*ops时，减出来的数不是负数，而是一个非常大的正数，这样会导致即使文件没有内容读了。也会执行memcpy(buf, &(d_file->data[*pos]), length);这个函数，进而导致内存报错，所以在该函数中强制转换了一部分数据类型，目前运行正常，我编写了一个utest在rt-thread/examples/utest/testcases/dfs/tmpfs目录下，目前已经可以正常通过测试。

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:bsp/qenu-vir64-aarch64

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-05-21 01:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8970) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=8970) before we can accept your contribution.<br/><hr/>**zhujiale** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=8970) it.</sub>

2024-05-23 12:21 UTC, polarvid requested changes

2024-05-23 12:21 UTC, polarvid commented on components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
>      rt_mutex_take(&file->vnode->lock, RT_WAITING_FOREVER);
`size = (ssize_t)file->vnode->size` 应该是冲突区的操作，需要在获取互斥锁后进行。

2024-06-11 03:31 UTC, polarvid requested changes

2024-06-11 03:31 UTC, polarvid commented on examples/utest/testcases/tmpfs/tmpfs.c
> +            uassert_false(1);
很多缩进有问题。建议装个 clangd 之类的，提交之前自动调整一下。

2024-06-11 06:42 UTC, zhuzhuzhus commented on examples/utest/testcases/tmpfs/tmpfs.c
> +            uassert_false(1);
已重新在vscode中修改

2024-06-12 02:03 UTC, polarvid approved these changes

2024-06-13 00:53 UTC, BernardXiong approved these changes

2024-06-13 00:54 UTC, merged