[bsp][stm32][uart V1]优化驱动实现
RT-Thread/rt-thread pull request #9057
Opened 2024-06-12 14:23 UTC by wdfk-prog

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
stm32 uart V1 优化驱动实现
* 增加putc超时处理机制,防止死循环
* 优化TX中断初始化与卸载
* 添加TX中断方式实现

[serial V1]poll tx
* 增加异常退出机制

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-06-13 01:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9057) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9057) before we can accept your contribution.<br/><hr/>**huangly** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=9057) it.</sub>

2024-06-16 07:48 UTC, mysterywolf commented
CI 检查有一个错误

2024-06-16 11:18 UTC, wdfk-prog commented
> CI 检查有一个错误

- 这ROM不够编译不过去....
- 还有这个`ERROR`不够显眼,我得看原始log才找到报错原因

![image](https://github.com/RT-Thread/rt-thread/assets/66928464/f17e7c5c-6cdd-465f-92a6-78b6936ab313)

2024-06-17 14:07 UTC, Rbb666 commented
> > CI 检查有一个错误
> 
> * 这ROM不够编译不过去....,我觉得不需要管他,这个工程得看一下干啥了,剩得ROM也太少了吧
> * 还有这个`ERROR`不够显眼,我得看原始log才找到报错原因
> 
> ![image](https://private-user-images.githubusercontent.com/66928464/340088359-f17e7c5c-6cdd-465f-92a6-78b6936ab313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzM0NzUsIm5iZiI6MTcxODYzMzE3NSwicGF0aCI6Ii82NjkyODQ2NC8zNDAwODgzNTktZjE3ZTdjNWMtNmNkZC00NjVmLTkyYTYtNzhiNjkzNmFiMzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE0MDYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MTM4ZDA2ZDMwYzAwNjYyYmZlY2UzNTA2ZDZiZGQzMjY4NTk4YmQ4MzJhMjQ4MjRiZGI0MDE3NGY5OWU1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1WDypQwYRlmWm8WNPNJY0RDbEyMq5xbzI7wfW_tS3ME)

是的，我也感觉不太好找报错的地方 @mysterywolf 满老师，这块有啥方便查看的方式吗

2024-06-24 17:31 UTC, mysterywolf requested changes

2024-06-24 17:31 UTC, mysterywolf commented on components/drivers/serial/serial.c
> +        if(serial->ops->putc(serial, *data) == -1) {
```suggestion
        if(serial->ops->putc(serial, *data) < 0) {
```

2024-06-26 15:53 UTC, mysterywolf approved these changes

2024-06-26 16:11 UTC, merged