[lwp] aarch64 vdso
RT-Thread/rt-thread pull request #9158
Opened 2024-07-09 02:45 UTC by rcitachi

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-09 06:28 UTC, polarvid requested changes
提交记录 rebase 一下吧，把 commit message 改成有意义的内容。

然后架构相关的应该放到 lwp/arch/$ARCH 目录下。

2024-07-09 06:28 UTC, polarvid commented on src/clock.c
> +#endif
这个里面的数据不是 percpu 的吧？一个核来处理就够了。

2024-07-09 08:20 UTC, polarvid requested changes

2024-07-09 08:20 UTC, polarvid commented on components/lwp/SConscript
> +        group = group + SConscript(os.path.join(item, 'SConscript'))
这个脚本不用遍历 all 的。SConscript('./vdso/SConscript') 就好

2024-07-09 09:21 UTC, rcitachi commented on components/lwp/SConscript
> +        group = group + SConscript(os.path.join(item, 'SConscript'))
已完成修改

2024-07-09 09:22 UTC, rcitachi commented on src/clock.c
> +#endif
已完成修改

2024-07-09 12:43 UTC, BernardXiong commented on components/lwp/vdso/kernel/vdso.h
> +#ifdef __cplusplus
这里的不需要这样写吧，更多是，
```c
#ifdef __cplusplus
extern "C" {
#endif
```

2024-07-09 12:43 UTC, BernardXiong commented on components/lwp/vdso/user/vdso.lds.S
> +	.hash		: { *(.hash) }			:text
对齐都是乱的

2024-07-10 02:23 UTC, polarvid requested changes

2024-07-10 02:23 UTC, polarvid commented on components/lwp/arch/aarch64/common/vdso.c
> +int rt_arch_setup_additional_pages(struct rt_lwp *lwp)
lwp 里面的用 arch 前缀就够了

2024-07-10 02:23 UTC, polarvid commented on components/lwp/arch/aarch64/common/vdso.c
> +INIT_BOARD_EXPORT(rt_vdso_init);
纯软件的功能没必要放到板子初始化里面。否则会拖慢启动速度...

2024-07-10 02:23 UTC, polarvid commented on components/lwp/arch/aarch64/common/vdso.c
> +int rt_vdso_init(void)
命名也可以修改一下

2024-07-11 05:23 UTC, polarvid approved these changes

2024-07-11 10:04 UTC, BernardXiong requested changes

2024-07-11 10:04 UTC, BernardXiong commented on components/lwp/vdso/vdso_weak.c
> +#include <rtthread.h>
缺乏文件头

2024-07-11 10:04 UTC, BernardXiong commented on components/lwp/vdso/user/vdso_sys.h
> +#define arch_counter_enforce_ordering(val) do {             \
可以调下对齐

2024-07-11 10:04 UTC, BernardXiong commented on components/lwp/vdso/kernel/vdso_text.S
> +	.balign VDSO_PAGE_SIZE
对齐

2024-07-11 10:04 UTC, BernardXiong commented on components/lwp/vdso/kernel/vdso_data.h
> +#if __cplusplus
这个写法很怪，建议通篇检查下

2024-07-11 10:04 UTC, BernardXiong commented on components/lwp/vdso/kernel/vdso_data.h
> +static inline
`static inline`，推荐使用`rt_inline`

2024-07-11 10:04 UTC, BernardXiong commented on components/lwp/vdso/kernel/vdso_data.h
> +#define VDSO_PRECISION_MASK ~(0xFF00ULL<<48)
48是什么意思？是否应该定义成宏，具备更多的语义

2024-07-11 10:04 UTC, BernardXiong commented on components/lwp/vdso/SConscript
> +src     = Glob('kernel/*.c')
检查下对齐

2024-07-11 10:16 UTC, rcitachi commented on components/lwp/vdso/kernel/vdso_data.h
> +#if __cplusplus
这个是之前版本遗留下来的，已删除

2024-07-11 10:17 UTC, rcitachi commented on components/lwp/vdso/kernel/vdso_data.h
> +#define VDSO_PRECISION_MASK ~(0xFF00ULL<<48)
这个是之前版本遗留的，已删除

2024-07-11 11:09 UTC, closed without merging