Dev new pinmux
RT-Thread/rt-thread pull request #9188
Opened 2024-07-15 08:48 UTC by unicornx

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

原先的管脚复用配置机制设计不好，现修改为新的配置方式。具体见 commit 的描述。

**注意，这个 PR 包含了两个 commit，merge 时请务必保留两个 commit，不要压缩。设计为两个 commit 也是为了方便以后回溯。**

#### 你的解决方案是什么 (what is your solution)

具体见 commit 的描述。

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config: 默认

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-15 09:10 UTC, heyuanjie87 approved these changes

2024-07-16 00:13 UTC, unicornx commented
注意，这个 PR 包含了两个 commit，merge 时请务必保留两个 commit，不要压缩。设计为两个 commit 也是为了方便以后回溯。

2024-07-16 00:19 UTC, unicornx commented
fixed #8934

2024-07-16 01:37 UTC, polarvid requested changes

2024-07-16 01:37 UTC, polarvid commented on bsp/cvitek/drivers/drv_pinmux.c
这个文件缺少版权头吧？这个应该是源文件强制的。

2024-07-16 01:37 UTC, polarvid commented on bsp/cvitek/drivers/drv_pinmux.h
> + */
建议与 src 目录代码保持一致，使用 `doxygen` 语法注释 API。这样也可以自动生成文档。

2024-07-16 01:56 UTC, unicornx commented on bsp/cvitek/drivers/drv_pinmux.h
> + */
> 建议与 src 目录代码保持一致，使用 `doxygen` 语法注释 API。这样也可以自动生成文档。

accept

2024-07-16 01:57 UTC, unicornx commented on bsp/cvitek/drivers/drv_pinmux.c
> 这个文件缺少版权头吧？这个应该是源文件强制的。

accept

2024-07-16 03:19 UTC, polarvid approved these changes

2024-07-16 03:36 UTC, Rbb666 approved these changes

2024-07-16 03:37 UTC, merged