adapt to rv64ilp32 toolchain
RT-Thread/rt-thread pull request #9194
Opened 2024-07-16 03:18 UTC by Yaochenger

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
qemu-virt64-riscv 适配 rv64ilp32新32位工具链
#### 你的解决方案是什么 (what is your solution)
修改数据类型以支持rv64ilp32
#### 请提供验证的bsp和config (provide the config and bsp) 
bsp:qemu-virt64-riscv
#### rv64ilp32工具链地址
https://github.com/ruyisdk/riscv-gnu-toolchain-rv64ilp32/tags
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-16 03:28 UTC, polarvid requested changes

2024-07-16 03:28 UTC, polarvid commented on libcpu/risc-v/virt64/regtypes.h
> +typedef unsigned long long rt_uintreg_t;
RTT 已经存在同样语义的类型 `rt_ubase_t`。

2024-07-16 03:31 UTC, polarvid requested changes

2024-07-16 03:31 UTC, polarvid commented on bsp/qemu-virt64-riscv/rtconfig.h
不推荐这么处理。用户用得更多的还是常规配置。也包括那个 qemu.sh 脚本。这个特殊配置做成此 bsp 默认等于强迫原先的用户普通的验证时每次都要修改。倒不如另外起一个目录来做。

2024-07-16 03:48 UTC, Yaochenger commented on libcpu/risc-v/virt64/regtypes.h
> +typedef unsigned long long rt_uintreg_t;
这块是这样的虽然跑的64位机器但是指针 长整型等编出来都是32位的 所以需要这么做一下

2024-07-16 03:50 UTC, polarvid commented on libcpu/risc-v/virt64/regtypes.h
> +typedef unsigned long long rt_uintreg_t;
`rt_base_t` 的语义就是机器字长。64 bits 核心肯定是 64 bits。

2024-07-16 03:57 UTC, Yaochenger commented on bsp/qemu-virt64-riscv/rtconfig.h
这里确实得考虑一下

2024-07-16 03:57 UTC, polarvid commented on libcpu/risc-v/virt64/regtypes.h
> +typedef unsigned long long rt_uintreg_t;
跟随指针长度的变量在标准 C 里面是 `intptr_t`。

https://github.com/RT-Thread/rt-thread/blob/d8d0af9143bc40c017aa7d9833b6a87e5d843968/include/rttypes.h#L36-L37

2024-07-16 05:12 UTC, polarvid commented on libcpu/risc-v/virt64/regtypes.h
> +typedef unsigned long long rt_uintreg_t;
`rt_ubase_t` 定义没考虑到不同 ABI 的问题。这个是单独 issue，建议是另外起一个 PR 修复。否则使用 rv64ilp32 的 ABI 时很多组件都跑不起来。单独加入一个新类型并不能从根源解决问题。

2024-07-16 05:28 UTC, Liaoshihua commented on libcpu/risc-v/virt64/cpuport.h
> +#define FLOAD                   flw
这里关于浮点指令的设置不合理。RISC-V架构中，浮点寄存器的长度由ABI_FLEN决定，与指针长度无关。当ABI_FLEN == 32时，abi 为 ilp32f 或 lp64f，当 ABI_FLEN == 64 时，abi 为 ilp32d 或 lp64d。
区分 rv32 和 rv64应该使用 if __riscv_xlen == 64，区分 ptr 的长度应该使用 __SIZEOF_POINTER__，区分浮点寄存器的长度应该使用 if __riscv_flen == 64 判断，示例如下
`
    #if defined(__riscv_flen) && __riscv_flen == 64

    #  define FPR_L fld

    #  define FPR_S fsd

    #  define SZ_FPR 8

    #elif defined(__riscv_flen) && __riscv_flen == 32

    #  define FPR_L flw

    #  define FPR_S fsw

    #  define SZ_FPR 4

    #elif defined(__riscv_flen)

    #  error Q-extension unsupported

    #else

    #  define SZ_FPR 0

    #endif

`

2024-07-16 08:29 UTC, Yaochenger commented on libcpu/risc-v/virt64/cpuport.h
> +#define FLOAD                   flw
在构造线程栈时 代码这里为了统一 将浮点的宽度与整数的宽度做了统一 ；这里引入的宏去区别确实不太恰当；取消了这这里使用宏区别的方式，修改了构造栈函数中的数据类型来适配，相应调整在cpuport.c文件

2024-07-18 07:45 UTC, Rbb666 approved these changes

2024-07-18 07:59 UTC, merged