[bsp][cvitek]: 将adc wdt驱动的局部函数移至源文件
RT-Thread/rt-thread pull request #9216
Opened 2024-07-19 02:39 UTC by Z8MAN8

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
Fixed https://github.com/RT-Thread/rt-thread/issues/9198

#### 你的解决方案是什么 (what is your solution)
把 static 函数从头文件移到对应的源文件中

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-20 07:31 UTC, mysterywolf requested changes

2024-07-20 07:31 UTC, mysterywolf commented on bsp/cvitek/drivers/drv_wdt.c
> +rt_inline void cvi_wdt_feed_en(unsigned long reg_base)
放到.c就没有必要用inline了

2024-07-20 09:04 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_wdt.c
> +rt_inline void cvi_wdt_feed_en(unsigned long reg_base)
虽然其他文件不会调用这些函数，但用inline修饰也能优化这类对寄存器的操作吧

2024-07-21 08:41 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_wdt.c
> +rt_inline void cvi_wdt_feed_en(unsigned long reg_base)
是的

2024-07-21 09:37 UTC, mysterywolf approved these changes

2024-07-21 09:37 UTC, merged