[bsp][cvitek] 修复 cv18xx_aarch64 uart 驱动相关宏配置
RT-Thread/rt-thread pull request #9221
Opened 2024-07-20 09:20 UTC by Z8MAN8

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
Fixed https://github.com/RT-Thread/rt-thread/issues/9220

#### 你的解决方案是什么 (what is your solution)
参照 cv18xx_risc-v 调整对应 Kconfig 配置

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-22 03:13 UTC, unicornx commented on bsp/cvitek/cv18xx_aarch64/Kconfig
> -
需要保留空行

2024-07-22 03:25 UTC, unicornx commented on bsp/cvitek/cv18xx_aarch64/Kconfig
我发现你对这个 Kconfig 的改动，即增加 `SOC_TYPE_SG2002` 的改动实际上也解决了 #9211 。你在 commit 里也一并描述一下吧。

2024-07-22 09:18 UTC, unicornx commented
代码改动没什么问题，主要是 commit 的描述有几点注意一下：

- 注意一行 75 个字符的限制
- 出错信息如果太长就不要全部贴了，可以文字简单描述一下也行，或者摘录一点关键的出错信息。
- 如果能定位到引入问题的 patch，我们一般会在 commit 中写成下面这样：

```
......

Fixes: e21d2170f366 ("video: remove unnecessary platform_set_drvdata()")
Signed-off-by: xxxx
```

- 建议将 commit 的 title 改为：`bsp: cvitek: add missing soc type for aarch64`

2024-07-22 09:29 UTC, unicornx requested changes
代码改动没什么问题，主要是 commit 的描述有几点注意一下：

- 注意一行 75 个字符的限制
- 出错信息如果太长就不要全部贴了，可以文字简单描述一下也行，或者摘录一点关键的出错信息。
- 如果能定位到引入问题的 patch，我们一般会在 commit 中写成下面这样：

```
......

Fixes: e21d2170f366 ("video: remove unnecessary platform_set_drvdata()")
Signed-off-by: xxxx
```

- 建议将 commit 的 title 改为：`bsp: cvitek: add missing soc type for aarch64`

bte: 如果你再改，方便的话，可以加一下我的 review 签名,加在你的签名下面即可，谢谢
```
Reviewed-by: Chen Wang <unicorn_wang@outlook.com>
```

2024-07-22 09:32 UTC, unicornx commented
另外请基于这个 pr，验证一下 arm 的 bsp 能不能跑起来，至少 uart 能 work 就行。当然编译要 no warnings， no errors

2024-07-25 01:14 UTC, unicornx commented
我看 master 最近有不少更新，请确保一下你的 .config 和 rtconfig.h 的更改是基于最新的 master 的就好。确认没问题后请在 pr 中答复我，我就 approve 了。

2024-07-25 01:18 UTC, unicornx commented
> 另外请基于这个 pr，验证一下 arm 的 bsp 能不能跑起来，至少 uart 能 work 就行。当然编译要 no warnings， no errors

目前 arm bsp 启动不了，导致原因和设备树以及文件系统 mnt 处理有关，已经另外提 #9243 跟踪。我们这里只保证编译问题即可。

2024-07-25 03:34 UTC, Z8MAN8 commented
> 我看 master 最近有不少更新，请确保一下你的 .config 和 rtconfig.h 的更改是基于最新的 master 的就好。确认没问题后请在 pr 中答复我，我就 approve 了。

已确认config 和 rtconfig.h 的更改是基于最新的 master

2024-07-25 05:30 UTC, unicornx approved these changes

2024-07-25 10:58 UTC, BernardXiong approved these changes

2024-07-25 10:58 UTC, merged