feat: use ARCH_REMAP_KERNEL in cv18xx_risc-v
RT-Thread/rt-thread pull request #9229
Opened 2024-07-22 05:32 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-25 02:07 UTC, unicornx commented
PR 的标题是 “feat: use ARCH_REMAP_KERNEL in cv18xx_risc-v”

三个 commit 中只有第一个看上去和 PR 的主题有关，其他两个为啥要加进来，请问和这个 title 是什么关系？
以及第一个 commit 中对 d1s 的改动看上去也是没有关系，这个应该是顺便改的打印？还是什么考虑？

pr 的commit 中感觉还是写得比较少，对于 feature 开发，至少要解释一下需求的来源。

抱歉我对 ARCH_REMAP_KERNEL 的理解不够，如果能解释一下或许对我 review 会有更大帮助，谢谢。

2024-07-25 02:53 UTC, unicornx commented
“[bsp: feat: add config of bootfs](https://github.com/RT-Thread/rt-thread/pull/9229/commits/6eff3b84feb05c86f59c9e6aeb2987ca5b7b3cbe)”

这个 commit 如何和主题无关，建议拿出来单独提个 pr

2024-07-25 02:55 UTC, unicornx commented
[feat: only select vDSO for arm64](https://github.com/RT-Thread/rt-thread/pull/9229/commits/26f819caf014c1802b305cc01b3d8a1facd31cac)

这个 commit 的 message 中建议说明一下改动的原因，前提是开了 smart 才会出现编译告警，目前 master 默认没有开 smart 所以编译看不到这个问题的。

2024-07-25 02:55 UTC, unicornx requested changes
见上 comments

2024-07-26 02:16 UTC, polarvid commented
@unicornx 

感谢 Review。我把部分修改拆分出了单独的 commits。以及一个独立的 PR #9252 .

2024-07-29 00:20 UTC, unicornx approved these changes

2024-07-29 12:18 UTC, merged