bsp: cvitek: fixed stacksize issue
RT-Thread/rt-thread pull request #9238
Opened 2024-07-23 06:04 UTC by unicornx

In the original Sconstruct script, `GetDepend('__STACKSIZE__')` is placed before the call to `PrepareBuilding()`, which causes the value of `GetDepend('__STACKSIZE__')` to always be False, and the value of `__STACKSIZE__` in `link_stacksize.lds` will not be updated.

Solution: move the call if `PrepareBuilding()` ahead.

Also sync and update the .config and rtconfig.h, plus the link_stacksize.lds.

Fixed #9237 

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-23 15:35 UTC, mysterywolf requested changes

2024-07-23 15:35 UTC, mysterywolf commented on bsp/cvitek/cv18xx_risc-v/SConstruct
> +if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
```suggestion
if GetDepend('__STACKSIZE__'):
    stack_size = GetDepend('__STACKSIZE__')
```

2024-07-24 00:32 UTC, unicornx commented on bsp/cvitek/cv18xx_risc-v/SConstruct
> +if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
ok

2024-07-24 02:35 UTC, polarvid approved these changes

2024-07-24 15:18 UTC, mysterywolf approved these changes

2024-07-24 15:18 UTC, mysterywolf commented
感谢提交PR~

2024-07-24 15:18 UTC, merged