[bsp/cvitek]pinmux驱动在smart模式下使用ioremap后的基地址
RT-Thread/rt-thread pull request #9244
Opened 2024-07-24 09:33 UTC by heyuanjie87

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
适应smart的运行要求

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-25 01:20 UTC, unicornx commented
你测试过或者考虑过 arm 吗？

ARM 大核默认的配置并没有开启 `RT_USING_SMART`，所以原来的逻辑是针对 ARM 大核，启用 ioremap，对 RISC-V 不启用 ioremap。而且 ARM 大核启用 ioremap 无关是否是 smart。

你现在的修改后的行为是：只有 smart 才会启用 ioremap

这看上去对原有的逻辑是有影响的。

我觉得还不如直接定义一个配置快关用于决定是否启用 ioremap，因为目前来看 ioremap 是一个独立的功能开关，和是否 smart 并无直接关系。

2024-07-25 01:22 UTC, unicornx commented
目前的代码看上去有点套娃的感觉。

`bsp/cvitek/drivers/drv_ioremap.h` 里 `DRV_IOREMAP` 用 `RT_USING_SMART` 进行了控制

```c
#ifdef RT_USING_SMART
#include <ioremap.h>

#define DRV_IOREMAP(addr, size) rt_ioremap(addr, size)
#define DRV_IOUNMAP(addr) rt_iounmap(addr)
#else
#define DRV_IOREMAP(addr, size) (addr)
#define DRV_IOUNMAP(addr)
#endif
```

`bsp/cvitek/drivers/drv_pinmux.c` 里同样用相同的宏 `RT_USING_SMART` 控制

```c
#if defined(RT_USING_SMART)
static rt_ubase_t pinmux_base = RT_NULL;

rt_ubase_t pinmux_base_ioremap(void)
{
    if (pinmux_base == RT_NULL)
    {
        pinmux_base = (rt_size_t)DRV_IOREMAP((void*)0x03001000, 0x1000);
    }

    return pinmux_base;
}
#endif
```

`bsp/cvitek/drivers/libraries/cv181x/pinctrl.h` 里继续用 `RT_USING_SMART` 控制

```c
#if defined(RT_USING_SMART)
extern rt_ubase_t pinmux_base_ioremap(void);
#define PINMUX_BASE pinmux_base_ioremap()
#else
#define PINMUX_BASE 0x03001000
#endif /* defined(ARCH_ARM) */
```

看上去最终影响的就是 `PINMUX_BASE`， 所以合并这三重宏控制，我理解就是如下的逻辑

这里我新定义了 `BSP_USING_IOREMAP` 这个开关，而不是用 `RT_USING_SMART`，原因在上面说了。
```c
#ifdef BSP_USING_IOREMAP
#include <ioremap.h>

static rt_ubase_t pinmux_base = RT_NULL;

#define PINMUX_BASE	(pinmux_base ? pinmux_base : rt_ioremap(0x03001000, 0x1000))

#else

#define PINMUX_BASE 0x03001000

#endif
```

2024-07-25 01:24 UTC, unicornx commented
`PINMUX_BASE` 会被很多地方调用，如果在启用 ioremap 下每次都要判断 `pinmux_base` 感觉有点浪费。

在启用 ioremap 的情况下，是否可以找个地方对 `pinmux_base` 进行初始化一次，然后 `PINMUX_BASE` 就直接定义为 `pinmux_base`，也就是说：

下面这段代码找个 board 初始化的地方尽早初始化，在 pinmux_config 被使用之前，或者在 pinmux_config 中只确保调用一次

```c
static rt_ubase_t pinmux_base = RT_NULL;

#ifdef BSP_USING_IOREMAP
#include <ioremap.h>
pinmux_base = rt_ioremap(0x03001000, 0x1000);
#endif
```

在 `pinmux_config()` 中只确保调用一次可能不太好，因为我搜了一下代码中涉及 `PINMUX_BASE` 的地方，还有 sdmmc 的地方 `bsp/cvitek/drivers/libraries/sdif/dw_sdmmc.h`，但感觉这段代码可能可以统一为调用 `pinmux_config()`，你可以考虑是否可以优化一下。


然后 `PINMUX_BASE` 就简化为下面这个了
```c
#ifdef BSP_USING_IOREMAP
#define PINMUX_BASE	pinmux_base
#else
#define PINMUX_BASE 0x03001000
#endif
```

2024-07-25 01:30 UTC, unicornx commented
> 目前的代码看上去有点套娃的感觉。
> 
> `bsp/cvitek/drivers/drv_ioremap.h` 里 `DRV_IOREMAP` 用 `RT_USING_SMART` 进行了控制
> 
> ```c
> #ifdef RT_USING_SMART
> #include <ioremap.h>
> 
> #define DRV_IOREMAP(addr, size) rt_ioremap(addr, size)
> #define DRV_IOUNMAP(addr) rt_iounmap(addr)
> #else
> #define DRV_IOREMAP(addr, size) (addr)
> #define DRV_IOUNMAP(addr)
> #endif
> ```
> 
> `bsp/cvitek/drivers/drv_pinmux.c` 里同样用相同的宏 `RT_USING_SMART` 控制
> 
> ```c
> #if defined(RT_USING_SMART)
> static rt_ubase_t pinmux_base = RT_NULL;
> 
> rt_ubase_t pinmux_base_ioremap(void)
> {
>     if (pinmux_base == RT_NULL)
>     {
>         pinmux_base = (rt_size_t)DRV_IOREMAP((void*)0x03001000, 0x1000);
>     }
> 
>     return pinmux_base;
> }
> #endif
> ```
> 
> `bsp/cvitek/drivers/libraries/cv181x/pinctrl.h` 里继续用 `RT_USING_SMART` 控制
> 
> ```c
> #if defined(RT_USING_SMART)
> extern rt_ubase_t pinmux_base_ioremap(void);
> #define PINMUX_BASE pinmux_base_ioremap()
> #else
> #define PINMUX_BASE 0x03001000
> #endif /* defined(ARCH_ARM) */
> ```
> 
> 看上去最终影响的就是 `PINMUX_BASE`， 所以合并这三重宏控制，我理解就是如下的逻辑
> 
> 这里我新定义了 `BSP_USING_IOREMAP` 这个开关，而不是用 `RT_USING_SMART`，原因在上面说了。
> 
> ```c
> #ifdef BSP_USING_IOREMAP
> #include <ioremap.h>
> 
> static rt_ubase_t pinmux_base = RT_NULL;
> 
> #define PINMUX_BASE	(pinmux_base ? pinmux_base : rt_ioremap(0x03001000, 0x1000))
> 
> #else
> 
> #define PINMUX_BASE 0x03001000
> 
> #endif
> ```

如果你觉得这个方案可行的话，可以考虑 revert #9242 

其实建议对 ioremap 的改动，最好都通过一个 pr 提交，只是这个 pr 中可以包括多个 commit。你现在的改动等于是吧一个大 feature 的改动分成多个 pr 提交了。

一个feature 的改动的所有 commit 放在一个 pr 中提交可以方便 review 时了解完整的解决方案。只是需要你提前将补丁划分好，这是设计和表达的问题。

基本的要求就是每个 commit 都是完整原子的，可以编译，并尽量保证功能完善。

2024-07-25 01:31 UTC, unicornx commented
Also， 你的 commit 信息一如既往地简单，只有一句话，该怎么写我建议你读一下 https://gist.github.com/finalfantasia/bd0070673ca27e5f7473。 

不用怕麻烦，这种工作只要做好一次，后面就很简单了。

2024-07-25 01:40 UTC, unicornx requested changes
详细见上面的 comments

2024-07-25 01:44 UTC, heyuanjie87 commented
> 你测试过或者考虑过 arm 吗？
> 
> ARM 大核默认的配置并没有开启 `RT_USING_SMART`，所以原来的逻辑是针对 ARM 大核，启用 ioremap，对 RISC-V 不启用 ioremap。而且 ARM 大核启用 ioremap 无关是否是 smart。
> 
> 你现在的修改后的行为是：只有 smart 才会启用 ioremap
> 
> 这看上去对原有的逻辑是有影响的。
> 
> 我觉得还不如直接定义一个配置快关用于决定是否启用 ioremap，因为目前来看 ioremap 是一个独立的功能开关，和是否 smart 并无直接关系。

我看过arm board.c对非smart而且没用OFW的情况下 对外设区建立了一对一映射，用了OFW没看是咋搞但也是可以增加一对一映射的，我的看法是RTOS模式就当MCU看待可以在bsp建立一对一映射就可以了

2024-07-25 01:49 UTC, polarvid commented
> 我看过arm board.c对非smart而且没用OFW的情况下 对外设区建立了一对一映射，用了OFW没看是咋搞但也是可以增加一对一映射的，我的看法是RTOS模式就当MCU看待可以在bsp建立一对一映射就可以了

不建议这么处理。如果是这样的话，肯定需要把 ARM 也在这个 PR 测试通过了再提交 PR。否则就是非常不负责任的行为。

之前也提了，提个单独的 USING_IOREMAP 就可以解决这个问题了。

```kconfig
config USING_IOREMAP
    bool
    default y if RT_USING_SMART || RT_USING_DM
    default n
```

2024-07-25 01:56 UTC, heyuanjie87 commented
> `PINMUX_BASE` 会被很多地方调用，如果在启用 ioremap 下每次都要判断 `pinmux_base` 感觉有点浪费。
> 
> 在启用 ioremap 的情况下，是否可以找个地方对 `pinmux_base` 进行初始化一次，然后 `PINMUX_BASE` 就直接定义为 `pinmux_base`，也就是说：
> 
> 下面这段代码找个 board 初始化的地方尽早初始化，在 pinmux_config 被使用之前，或者在 pinmux_config 中只确保调用一次
> 
> ```c
> static rt_ubase_t pinmux_base = RT_NULL;
> 
> #ifdef BSP_USING_IOREMAP
> #include <ioremap.h>
> pinmux_base = rt_ioremap(0x03001000, 0x1000);
> #endif
> ```
> 
> 在 `pinmux_config()` 中只确保调用一次可能不太好，因为我搜了一下代码中涉及 `PINMUX_BASE` 的地方，还有 sdmmc 的地方 `bsp/cvitek/drivers/libraries/sdif/dw_sdmmc.h`，但感觉这段代码可能可以统一为调用 `pinmux_config()`，你可以考虑是否可以优化一下。
> 
> 然后 `PINMUX_BASE` 就简化为下面这个了
> 
> ```c
> #ifdef BSP_USING_IOREMAP
> #define PINMUX_BASE	pinmux_base
> #else
> #define PINMUX_BASE 0x03001000
> #endif
> ```

ioremap一般只用在初始化阶段，目前我只想在不大改的前提下把smart运行起来，效率可以后面考虑

2024-07-25 02:02 UTC, heyuanjie87 commented
> > 我看过arm board.c对非smart而且没用OFW的情况下 对外设区建立了一对一映射，用了OFW没看是咋搞但也是可以增加一对一映射的，我的看法是RTOS模式就当MCU看待可以在bsp建立一对一映射就可以了
> 
> 不建议这么处理。如果是这样的话，肯定需要把 ARM 也在这个 PR 测试通过了再提交 PR。否则就是非常不负责任的行为。
> 
> 关于 DM 的问题，之前也解释过了，对于动态的设备模型，根本就建立不了静态的 1：1 映射。已经不想再重复这个事实了。你如果想要评论这个设计，请至少亲自尝试过它，对它了解过了以后再来修改。
> 
> 之前也提了，提个单独的 USING_IOREMAP 就可以解决这个问题了。
> 
> ```
> config USING_IOREMAP
>     bool
>     default y if RT_USING_SMART || RT_USING_DM
>     default n
> ```

我以为用DM也可以建立静态映射，那这个config USING_IOREMAP放bsp里的kconfig吗

2024-07-25 02:05 UTC, polarvid commented
> 我以为用DM也可以建立静态映射，那这个config USING_IOREMAP放bsp里的kconfig吗

@heyuanjie87 赞同。毕竟现在 `drv_ioremap.h` 也在 bsp 下。宏倒是可以加个 BSP_ 的前缀。

2024-07-25 02:10 UTC, heyuanjie87 commented
> > 我看过arm board.c对非smart而且没用OFW的情况下 对外设区建立了一对一映射，用了OFW没看是咋搞但也是可以增加一对一映射的，我的看法是RTOS模式就当MCU看待可以在bsp建立一对一映射就可以了
> 
> 不建议这么处理。如果是这样的话，肯定需要把 ARM 也在这个 PR 测试通过了再提交 PR。否则就是非常不负责任的行为。
> 
> 关于 DM 的问题，之前也解释过了，对于动态的设备模型，根本就建立不了静态的 1：1 映射。已经不想再重复这个事实了。你如果想要评论这个设计，请至少亲自尝试过它，对它了解过了以后再来修改。
> 
> 之前也提了，提个单独的 USING_IOREMAP 就可以解决这个问题了。
> 
> ```
> config USING_IOREMAP
>     bool
>     default y if RT_USING_SMART || RT_USING_DM
>     default n
> ```

在内核里加了这个开关后有些bsp编译不过我就放弃了

2024-07-25 07:51 UTC, unicornx commented
我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。

2024-07-25 07:56 UTC, unicornx commented
commit 文字中的 “添加理由” 和 “使用建议” 都是属于解决方案的内容，但是作为一个 new feature 开发，设计上缺少需求描述

建议对于 new feature 开发，commit 文字中至少含有以下几部分：

- 为什么要做这个 PR
- 你的修改思路是什么
- 其他注意事项，譬如测试上是否有什么需要注意等

另外作为完整性，请在 commit 中注明，对于 c906L, 因为是 RTOS，不考虑 ioremap。

2024-07-25 07:58 UTC, unicornx requested changes
第二次 review comments：
https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249686796
https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249695632

2024-07-25 08:24 UTC, heyuanjie87 commented
> 我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。

给过答复了：我这只是把以前的代码移动了个位置，本次提交我还不想解决效率问题只想让smart运行起来，而且ioremap一般只用在初始化阶段对效率影响不大

2024-07-25 09:22 UTC, unicornx commented
> > 我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。
> 
> 给过答复了：我这只是把以前的代码移动了个位置，本次提交我还不想解决效率问题只想让smart运行起来，而且ioremap一般只用在初始化阶段对效率影响不大

你没理解我说的 套娃 问题。
套娃问题和效率问题我是分两个 comments 提的

- 套娃问题：https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799
- 效率问题：https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837

效率问题可以先不管，但是套娃问题是我觉得你的代码可读性不好，没有必要写成这样的，解开套娃代码会很简单，而且根本就不需要引入 #9242.  这也是我为啥说当初应该把 #9242 和这个 pr 放一起 review 的原因。

@polarvid 要不请 shell 也看一下吧，我觉得已经没什么好解释的了。

2024-07-25 09:44 UTC, polarvid commented
> `PINMUX_BASE` 会被很多地方调用，如果在启用 ioremap 下每次都要判断 `pinmux_base` 感觉有点浪费。
> 
> 在启用 ioremap 的情况下，是否可以找个地方对 `pinmux_base` 进行初始化一次，然后 `PINMUX_BASE` 就直接定义为 `pinmux_base`，也就是说：
> 
> 下面这段代码找个 board 初始化的地方尽早初始化，在 pinmux_config 被使用之前，或者在 pinmux_config 中只确保调用一次
> 
> ```c
> static rt_ubase_t pinmux_base = RT_NULL;
> 
> #ifdef BSP_USING_IOREMAP
> #include <ioremap.h>
> pinmux_base = rt_ioremap(0x03001000, 0x1000);
> #endif
> ```
> 
> 在 `pinmux_config()` 中只确保调用一次可能不太好，因为我搜了一下代码中涉及 `PINMUX_BASE` 的地方，还有 sdmmc 的地方 `bsp/cvitek/drivers/libraries/sdif/dw_sdmmc.h`，但感觉这段代码可能可以统一为调用 `pinmux_config()`，你可以考虑是否可以优化一下。
> 
> 然后 `PINMUX_BASE` 就简化为下面这个了
> 
> ```c
> #ifdef BSP_USING_IOREMAP
> #define PINMUX_BASE	pinmux_base
> #else
> #define PINMUX_BASE 0x03001000
> #endif
> ```

这个方案挺好的呀，而且也不用引入特别大的修改吧。就是多加一个变量赋值初始化。

arm64 没有上 DM 之前，兼容 smart/RTOS 的代码基本都是这么处理的，比如现在的 `raspi4b-64` 的 BSP。

2024-07-25 10:08 UTC, heyuanjie87 commented
> > `PINMUX_BASE` 会被很多地方调用，如果在启用 ioremap 下每次都要判断 `pinmux_base` 感觉有点浪费。
> > 在启用 ioremap 的情况下，是否可以找个地方对 `pinmux_base` 进行初始化一次，然后 `PINMUX_BASE` 就直接定义为 `pinmux_base`，也就是说：
> > 下面这段代码找个 board 初始化的地方尽早初始化，在 pinmux_config 被使用之前，或者在 pinmux_config 中只确保调用一次
> > ```c
> > static rt_ubase_t pinmux_base = RT_NULL;
> > 
> > #ifdef BSP_USING_IOREMAP
> > #include <ioremap.h>
> > pinmux_base = rt_ioremap(0x03001000, 0x1000);
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在 `pinmux_config()` 中只确保调用一次可能不太好，因为我搜了一下代码中涉及 `PINMUX_BASE` 的地方，还有 sdmmc 的地方 `bsp/cvitek/drivers/libraries/sdif/dw_sdmmc.h`，但感觉这段代码可能可以统一为调用 `pinmux_config()`，你可以考虑是否可以优化一下。
> > 然后 `PINMUX_BASE` 就简化为下面这个了
> > ```c
> > #ifdef BSP_USING_IOREMAP
> > #define PINMUX_BASE	pinmux_base
> > #else
> > #define PINMUX_BASE 0x03001000
> > #endif
> > ```
> 
> 这个方案挺好的呀，而且也不用引入特别大的修改吧。就是多加一个变量赋值初始化。
> 
> arm64 没有上 DM 之前，兼容 smart/RTOS 的代码基本都是这么处理的，比如现在的 `raspi4b-64` 的 BSP。

那我还是加个初始化吧

2024-07-25 10:23 UTC, heyuanjie87 commented
> > `PINMUX_BASE` 会被很多地方调用，如果在启用 ioremap 下每次都要判断 `pinmux_base` 感觉有点浪费。
> > 在启用 ioremap 的情况下，是否可以找个地方对 `pinmux_base` 进行初始化一次，然后 `PINMUX_BASE` 就直接定义为 `pinmux_base`，也就是说：
> > 下面这段代码找个 board 初始化的地方尽早初始化，在 pinmux_config 被使用之前，或者在 pinmux_config 中只确保调用一次
> > ```c
> > static rt_ubase_t pinmux_base = RT_NULL;
> > 
> > #ifdef BSP_USING_IOREMAP
> > #include <ioremap.h>
> > pinmux_base = rt_ioremap(0x03001000, 0x1000);
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在 `pinmux_config()` 中只确保调用一次可能不太好，因为我搜了一下代码中涉及 `PINMUX_BASE` 的地方，还有 sdmmc 的地方 `bsp/cvitek/drivers/libraries/sdif/dw_sdmmc.h`，但感觉这段代码可能可以统一为调用 `pinmux_config()`，你可以考虑是否可以优化一下。
> > 然后 `PINMUX_BASE` 就简化为下面这个了
> > ```c
> > #ifdef BSP_USING_IOREMAP
> > #define PINMUX_BASE	pinmux_base
> > #else
> > #define PINMUX_BASE 0x03001000
> > #endif
> > ```
> 
> 这个方案挺好的呀，而且也不用引入特别大的修改吧。就是多加一个变量赋值初始化。
> 
> arm64 没有上 DM 之前，兼容 smart/RTOS 的代码基本都是这么处理的，比如现在的 `raspi4b-64` 的 BSP。

看了arm那边的代码没法用初始化的方式，arm用DM的情况下调用了rt_hw_common_setup

2024-07-25 10:29 UTC, heyuanjie87 commented
> > > 我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。
> > 
> > 
> > 给过答复了：我这只是把以前的代码移动了个位置，本次提交我还不想解决效率问题只想让smart运行起来，而且ioremap一般只用在初始化阶段对效率影响不大
> 
> 你没理解我说的 套娃 问题。 套娃问题和效率问题我是分两个 comments 提的
> 
> * 套娃问题：[[bsp/cvitek]pinmux驱动在smart模式下使用ioremap后的基地址 #9244 (comment)](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799)
> * 效率问题：[https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837，](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837%EF%BC%8C) 当然我这里提效率问题是基于解决了套娃问题的基础之上。
> 
> 效率问题可以先不管，但是套娃问题是我觉得你的代码可读性不好，没有必要写成这样的，解开套娃代码会很简单，而且根本就不需要引入 #9242. 这也是我为啥说当初应该把 #9242 和这个 pr 放一起 review 的原因。
> 
> @polarvid 要不请 shell 也看一下吧，我觉得已经没什么好解释的了。

这个套娃的操作是个无耐之举，arm bsp那边用DM的情况下在libcpu\aarch64\common\setup.c::rt_hw_common_setup()里初始化了外设，这导致pinmux基地址没机会初始化了，除非arm libcpu层把这个接口拆成两部分

2024-07-25 10:34 UTC, polarvid commented
或者考虑单独建个 issue ？后续再来追踪优化。

2024-07-25 10:35 UTC, heyuanjie87 commented
> > > 我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。
> > 
> > 
> > 给过答复了：我这只是把以前的代码移动了个位置，本次提交我还不想解决效率问题只想让smart运行起来，而且ioremap一般只用在初始化阶段对效率影响不大
> 
> 你没理解我说的 套娃 问题。 套娃问题和效率问题我是分两个 comments 提的
> 
> * 套娃问题：[[bsp/cvitek]pinmux驱动在smart模式下使用ioremap后的基地址 #9244 (comment)](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799)
> * 效率问题：[https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837，](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837%EF%BC%8C) 当然我这里提效率问题是基于解决了套娃问题的基础之上。
> 
> 效率问题可以先不管，但是套娃问题是我觉得你的代码可读性不好，没有必要写成这样的，解开套娃代码会很简单，而且根本就不需要引入 #9242. 这也是我为啥说当初应该把 #9242 和这个 pr 放一起 review 的原因。
> 
> @polarvid 要不请 shell 也看一下吧，我觉得已经没什么好解释的了。

或者把void pinmux_init(void)放pinmux_config里调用，
以前旧的代码删除，如下：
```
#define PINMUX_CONFIG(PIN_NAME, FUNC_NAME) \
        mmio_clrsetbits_32(PINMUX_BASE + FMUX_GPIO_FUNCSEL_##PIN_NAME, \
        PINMUX_MASK(PIN_NAME) << PINMUX_OFFSET(PIN_NAME), \
        PINMUX_VALUE(PIN_NAME, FUNC_NAME))

```
用了新的pinmux_config旧的就用不到了

2024-07-25 10:50 UTC, unicornx commented
> > > > 我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。
> > > 
> > > 
> > > 给过答复了：我这只是把以前的代码移动了个位置，本次提交我还不想解决效率问题只想让smart运行起来，而且ioremap一般只用在初始化阶段对效率影响不大
> > 
> > 
> > 你没理解我说的 套娃 问题。 套娃问题和效率问题我是分两个 comments 提的
> > 
> > * 套娃问题：[[bsp/cvitek]pinmux驱动在smart模式下使用ioremap后的基地址 #9244 (comment)](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799)
> > * 效率问题：[https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837，](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837%EF%BC%8C) 当然我这里提效率问题是基于解决了套娃问题的基础之上。
> > 
> > 效率问题可以先不管，但是套娃问题是我觉得你的代码可读性不好，没有必要写成这样的，解开套娃代码会很简单，而且根本就不需要引入 #9242. 这也是我为啥说当初应该把 #9242 和这个 pr 放一起 review 的原因。
> > @polarvid 要不请 shell 也看一下吧，我觉得已经没什么好解释的了。
> 
> 或者把void pinmux_init(void)放pinmux_config里调用， 以前旧的代码删除，如下：
> 
> ```
> #define PINMUX_CONFIG(PIN_NAME, FUNC_NAME) \
>         mmio_clrsetbits_32(PINMUX_BASE + FMUX_GPIO_FUNCSEL_##PIN_NAME, \
>         PINMUX_MASK(PIN_NAME) << PINMUX_OFFSET(PIN_NAME), \
>         PINMUX_VALUE(PIN_NAME, FUNC_NAME))
> ```
> 
> 用了新的pinmux_config旧的就用不到了

旧的现在有人用吗？没有人用我觉得先保留也没关系，但是不建议用

2024-07-25 10:56 UTC, unicornx commented
> > > > 我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。
> > > 
> > > 
> > > 给过答复了：我这只是把以前的代码移动了个位置，本次提交我还不想解决效率问题只想让smart运行起来，而且ioremap一般只用在初始化阶段对效率影响不大
> > 
> > 
> > 你没理解我说的 套娃 问题。 套娃问题和效率问题我是分两个 comments 提的
> > 
> > * 套娃问题：[[bsp/cvitek]pinmux驱动在smart模式下使用ioremap后的基地址 #9244 (comment)](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799)
> > * 效率问题：[https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837，](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837%EF%BC%8C) 当然我这里提效率问题是基于解决了套娃问题的基础之上。
> > 
> > 效率问题可以先不管，但是套娃问题是我觉得你的代码可读性不好，没有必要写成这样的，解开套娃代码会很简单，而且根本就不需要引入 #9242. 这也是我为啥说当初应该把 #9242 和这个 pr 放一起 review 的原因。
> > @polarvid 要不请 shell 也看一下吧，我觉得已经没什么好解释的了。
> 
> 这个套娃的操作是个无耐之举，arm bsp那边用DM的情况下在libcpu\aarch64\common\setup.c::rt_hw_common_setup()里初始化了外设，这导致pinmux基地址没机会初始化了，除非arm libcpu层把这个接口拆成两部分

我觉得你是不是又把 ”套娃“问题 和 "优化” 问题两个混淆了。

我说的套娃问题，不涉及初始化函数的处理，就是把这个补丁的代码改成如下方式

```c
#ifdef BSP_USING_IOREMAP
#include <ioremap.h>

static rt_ubase_t pinmux_base = RT_NULL;

#define PINMUX_BASE	(pinmux_base ? pinmux_base : rt_ioremap(0x03001000, 0x1000))

#else

#define PINMUX_BASE 0x03001000

#endif
```

这么做解决了补丁里多层宏处理的问题。但是存在效率问题，就是 BSP_USING_IOREMAP 下 PINMUX_BASE 都有可能展开为判断处理。

然后才是第二个我说的效率问题怎么解决。也就是我说可不可以提取一个 init 函数出来的问题。

所以我理解你这里说的 “rt_hw_common_setup()” 问题还是在说第二个效率问题，是不是？我再强调一次这个和第一个套娃问题不是一个问题。

2024-07-25 11:48 UTC, heyuanjie87 commented
> > > > > 我在第一次 review 中提出的 [套娃 问题](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799) 没有答复，也没有解决。
> > > > 
> > > > 
> > > > 给过答复了：我这只是把以前的代码移动了个位置，本次提交我还不想解决效率问题只想让smart运行起来，而且ioremap一般只用在初始化阶段对效率影响不大
> > > 
> > > 
> > > 你没理解我说的 套娃 问题。 套娃问题和效率问题我是分两个 comments 提的
> > > 
> > > * 套娃问题：[[bsp/cvitek]pinmux驱动在smart模式下使用ioremap后的基地址 #9244 (comment)](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249182799)
> > > * 效率问题：[https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837，](https://github.com/RT-Thread/rt-thread/pull/9244#issuecomment-2249184837%EF%BC%8C) 当然我这里提效率问题是基于解决了套娃问题的基础之上。
> > > 
> > > 效率问题可以先不管，但是套娃问题是我觉得你的代码可读性不好，没有必要写成这样的，解开套娃代码会很简单，而且根本就不需要引入 #9242. 这也是我为啥说当初应该把 #9242 和这个 pr 放一起 review 的原因。
> > > @polarvid 要不请 shell 也看一下吧，我觉得已经没什么好解释的了。
> > 
> > 
> > 或者把void pinmux_init(void)放pinmux_config里调用， 以前旧的代码删除，如下：
> > ```
> > #define PINMUX_CONFIG(PIN_NAME, FUNC_NAME) \
> >         mmio_clrsetbits_32(PINMUX_BASE + FMUX_GPIO_FUNCSEL_##PIN_NAME, \
> >         PINMUX_MASK(PIN_NAME) << PINMUX_OFFSET(PIN_NAME), \
> >         PINMUX_VALUE(PIN_NAME, FUNC_NAME))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用了新的pinmux_config旧的就用不到了
> 
> 旧的现在有人用吗？没有人用我觉得先保留也没关系，但是不建议用

搜过代码里没地方用了，有新的就用新的吧

2024-09-04 02:15 UTC, mysterywolf commented
@heyuanjie87 @unicornx @polarvid 这个PR有啥结论没有呀？是还要继续修改嘛？

2024-09-12 06:43 UTC, closed without merging