bsp: feat: add config of bootfs
RT-Thread/rt-thread pull request #9252
Opened 2024-07-26 02:03 UTC by polarvid

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

To support more choice on bootfs. romfs, cromfs are now supported on risc_v_big platform.

#### 你的解决方案是什么 (what is your solution)

Changes:
- added mount operations under port
- added prototypes for cromfs init APIs

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-28 16:02 UTC, BernardXiong approved these changes

2024-07-29 06:16 UTC, unicornx commented
建议在 https://github.com/RT-Thread/rt-thread/pull/9229#issuecomment-2249261622 里回复一下并说明为此新提了一个 pr。方便我们了解 pr 之间的关联，
不过还好我想起来了。

2024-07-29 06:16 UTC, unicornx approved these changes

2024-07-29 06:18 UTC, unicornx requested changes
建议修改 commit 的 title，加上 “bsp: cvitek: c906B" 的前缀。这个改动应该是针对的这个 BSP。

2024-07-29 07:10 UTC, polarvid commented
> 建议在 [#9229 (comment)](https://github.com/RT-Thread/rt-thread/pull/9229#issuecomment-2249261622) 里回复一下并说明为此新提了一个 pr。方便我们了解 pr 之间的关联， 不过还好我想起来了。:)

@unicornx commit 已重新提交。里面关联的 PR 中，我在 Comment 提及了一下 https://github.com/RT-Thread/rt-thread/pull/9229#issuecomment-2251838641

2024-07-29 07:14 UTC, unicornx commented
![image](https://github.com/user-attachments/assets/cf11f7a5-f311-4e6d-9bf3-95ef053738a2)

写错了？

2024-07-29 07:15 UTC, polarvid commented
> ![image](https://private-user-images.githubusercontent.com/2476165/352949543-cf11f7a5-f311-4e6d-9bf3-95ef053738a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzc1NzMsIm5iZiI6MTcyMjIzNzI3MywicGF0aCI6Ii8yNDc2MTY1LzM1Mjk0OTU0My1jZjExZjdhNS1mMzExLTRlNmQtOWJmMy05NWVmMDUzNzM4YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDcxNDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg2NmUxZTA5YjVhNzI1MDU3M2I3NDJkMjQ1MDMyNzYwZjA3M2MyMWEyMTgzOTRkNTY1ZmY4MjY1ZjdlNWNhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._r-ALuhocr953x8V_z6CaxjGcJwLf2_-jyKHghLooos)
> 
> 写错了？

这个应该是两个 REVIEW。#9252 没有源码修改就没写上去了。

2024-07-29 07:32 UTC, unicornx commented
> > ![image](https://private-user-images.githubusercontent.com/2476165/352949543-cf11f7a5-f311-4e6d-9bf3-95ef053738a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzc1NzMsIm5iZiI6MTcyMjIzNzI3MywicGF0aCI6Ii8yNDc2MTY1LzM1Mjk0OTU0My1jZjExZjdhNS1mMzExLTRlNmQtOWJmMy05NWVmMDUzNzM4YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDcxNDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg2NmUxZTA5YjVhNzI1MDU3M2I3NDJkMjQ1MDMyNzYwZjA3M2MyMWEyMTgzOTRkNTY1ZmY4MjY1ZjdlNWNhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._r-ALuhocr953x8V_z6CaxjGcJwLf2_-jyKHghLooos)
> > 写错了？
> 
> 这个应该是两个 REVIEW。#9252 没有源码修改就没写上去了。



> > ![image](https://private-user-images.githubusercontent.com/2476165/352949543-cf11f7a5-f311-4e6d-9bf3-95ef053738a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzc1NzMsIm5iZiI6MTcyMjIzNzI3MywicGF0aCI6Ii8yNDc2MTY1LzM1Mjk0OTU0My1jZjExZjdhNS1mMzExLTRlNmQtOWJmMy05NWVmMDUzNzM4YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDcxNDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg2NmUxZTA5YjVhNzI1MDU3M2I3NDJkMjQ1MDMyNzYwZjA3M2MyMWEyMTgzOTRkNTY1ZmY4MjY1ZjdlNWNhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._r-ALuhocr953x8V_z6CaxjGcJwLf2_-jyKHghLooos)
> > 写错了？
> 
> 这个应该是两个 REVIEW。#9252 没有源码修改就没写上去了。

好吧，其实两个 review 都写上也没啥吧
anyway，I have approved this pr.

2024-07-29 12:16 UTC, merged