bsp: cvitek: fix cvitek uart driver can not repeat configure
RT-Thread/rt-thread pull request #9257
Opened 2024-07-27 09:12 UTC by Z8MAN8

After first called from uart open, the dw8250_uart_configure API cannot be called again. Otherwise, this will mess up the device, and uart will not act properly to interrupt again.

Analysis: Configure uart device will close recive interrupte, causing uart device to malfunction.

Solution: After configure uart device, enable the device's recive interrupte.

Reviewed-by: Chen Wang <unicorn_wang@outlook.com>

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
Fixed https://github.com/RT-Thread/rt-thread/issues/9150

#### 你的解决方案是什么 (what is your solution)
After configure uart device, enable the device's recive interrupte.

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-27 09:13 UTC, Z8MAN8 commented
@unicornx

2024-07-28 12:19 UTC, BernardXiong commented on bsp/cvitek/drivers/drv_uart.c
> +    dw8250_write32(base, UART_IER, UART_IER_RDI);
这里应该不是这么来操作。如果涉及到中断，可以先行判断之前的状态是什么样的。

2024-07-28 15:30 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_uart.c
> +    dw8250_write32(base, UART_IER, UART_IER_RDI);
已修改

2024-07-29 05:47 UTC, unicornx commented
@Z8MAN8 请在 #9150 里 AT 我一下，这样我就可以 assign 那个 issue 给你了。

2024-07-29 06:04 UTC, unicornx commented on bsp/cvitek/drivers/drv_uart.c
> +    if(last_ier_state == UART_IER_RDI)
`if` 和 `(` 之间应该有空格，这个 formating 检查不出来吗？

2024-07-29 06:07 UTC, unicornx requested changes
comments 见上。

2024-07-29 06:24 UTC, unicornx commented on bsp/cvitek/drivers/drv_uart.c
> +    if(last_ier_state == UART_IER_RDI)
> `if` 和 `(` 之间应该有空格，这个 formating 检查不出来吗？
> 
> 另外，直接判断 `last_ier_state == UART_IER_RDI` 不妥，而是要判断 `IER[0]` 这一位以前是否是 1，IER 其他位也可能会是 1。

其他的 bit 位是不是也应该恢复？所以这个 issue 的完整 fix 应该就是一个完整的 backup -> restore 的操作。

2024-07-29 06:42 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_uart.c
> +    if(last_ier_state == UART_IER_RDI)
formating没检查出来，已手动更改，位判断也已解决

2024-07-29 06:49 UTC, unicornx commented on bsp/cvitek/drivers/drv_uart.c
> +    if(last_ier_state == UART_IER_RDI)
> formating没检查出来，已手动更改，位判断也已解决

只恢复 UART_IER_RDI 这个位是不够的，其他 bit 的值也需要恢复。

我不知道 github 是否有机制重新发起下一次 review，你可以研究一下。
最土的方法，你下次每一次改好重新 push 后，可以在 PR 里明确 AT 所有的 reviewer 然后请求第 N 次 review。有时候 review 的 PR 多了我也不知道你是否改过了，以及是否重新 push 过。

2024-07-29 07:50 UTC, unicornx commented on bsp/cvitek/drivers/drv_uart.c
> +    if(last_ier_state == UART_IER_RDI)
> > formating没检查出来，已手动更改，位判断也已解决
> 
> 只恢复 UART_IER_RDI 这个位是不够的，其他 bit 的值也需要恢复。
> 
> BTW：我不知道 github 是否有机制重新发起下一次 review，你可以研究一下。 最土的方法，你下次每一次改好重新 push 后，可以在 PR 里明确 AT 所有的 reviewer 然后请求第 N 次 review。有时候 review 的 PR 多了我也不知道你是否改过了，以及是否重新 push 过。

追加一个问题：

为啥当初代码里是直接将 UART_IER 置 0？这个 dw8250_uart_configure 为什么用不到 cfg 这个参数？请研究一下。

2024-07-29 10:12 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_uart.c
> +    if(last_ier_state == UART_IER_RDI)
没有保持其他位确实是有问题的，根据 cfg 传参进行配置这部分确实缺少了，需要补上

2024-08-16 08:00 UTC, unicornx commented
这个 PR 先解决  #9150 的问题吧，cfg 传参进行配置这部分缺少的问题后面再单独修改吧。

2024-08-16 08:36 UTC, Z8MAN8 commented
> 这个 PR 先解决 #9150 的问题吧，cfg 传参进行配置这部分缺少的问题后面再单独修改吧。

好的 明白

2024-08-23 14:24 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_uart.c
> +    if(last_ier_state == UART_IER_RDI)
已重新修改，请重新review

2024-08-25 00:44 UTC, unicornx approved these changes

2024-08-28 22:47 UTC, mysterywolf commented
@unicornx 请确认这个PR是否可以合并？

2024-08-29 00:03 UTC, unicornx commented
> @unicornx 请确认这个PR是否可以合并？

我这里没有问题了，也 approve 了。但我看熊大还没有 approve。

2024-08-29 00:52 UTC, mysterywolf approved these changes

2024-08-29 01:07 UTC, unicornx commented
@BernardXiong hi, 请 review & commnet，谢谢。

2024-09-04 00:38 UTC, BernardXiong approved these changes

2024-09-04 00:50 UTC, merged