bsp: cvitek: add support for RTCSYS_SARADC
RT-Thread/rt-thread pull request #9258
Opened 2024-07-28 04:23 UTC by Z8MAN8

The cvitek adc dirver now only support one adc controller, but missing another adc controller RTCSYS_SARADC

Reviewed-by: Chen Wang <unicorn_wang@outlook.com>

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
Fixed https://github.com/RT-Thread/rt-thread/issues/9025

#### 你的解决方案是什么 (what is your solution)
添加 RTCSYS_SARADC

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-28 04:24 UTC, Z8MAN8 commented
@unicornx

2024-07-29 03:08 UTC, unicornx commented
你这里理解错了吧，参考 trm 上的说明：

![image](https://github.com/user-attachments/assets/eb765ccf-6d5e-4c3f-b85a-a48fbdc501c5)

所以原来的 Kconfig 配置是正确的，问题是驱动代码中只支持了 active domain 下那个 adc controller，代码中叫 “adc1”，但是no-die domain 下的那个驱动代码中没有做。#9025 实际上是说的这个。

我看你这个 pr 的做法变成实现了总共4 个 adc controller 了。

请再确认一下，还是我理解错了？

2024-07-29 03:08 UTC, unicornx requested changes
你这里理解错了吧，参考 trm 上的说明：

![image](https://github.com/user-attachments/assets/eb765ccf-6d5e-4c3f-b85a-a48fbdc501c5)

所以原来的 Kconfig 配置是正确的，问题是驱动代码中只支持了 active domain 下那个 adc controller，代码中叫 “adc1”，但是no-die domain 下的那个驱动代码中没有做。#9025 实际上是说的这个。

我看你这个 pr 的做法变成实现了总共4 个 adc controller 了。

请再确认一下，还是我理解错了？

2024-07-30 10:15 UTC, Z8MAN8 commented
@unicornx 之前理解错了，已根据datasheet重新更改，请review

2024-07-31 06:54 UTC, unicornx commented
commit 里的英文感觉不对

> The cvitek adc dirver now only support one adc controller, but missing another adc controller RTCSYS_SARADC.

可以用机翻。

我把这段文字先翻译成中文，然后再翻译成英文后得到如下：

cvitek adc dirver only supports one adc controller now, but the other adc controller RTCSYS_SARADC is missing.

你可以对比一下差别在哪里？ ：）

其他我看了没有啥问题。请改一下 commit 文字，我就 approve 了。

2024-08-01 07:29 UTC, Z8MAN8 commented
> commit 里的英文感觉不对
> 
> > The cvitek adc dirver now only support one adc controller, but missing another adc controller RTCSYS_SARADC.
> 
> 可以用机翻。
> 
> 我把这段文字先翻译成中文，然后再翻译成英文后得到如下：
> 
> cvitek adc dirver only supports one adc controller now, but the other adc controller RTCSYS_SARADC is missing.
> 
> 你可以对比一下差别在哪里？ ：）
> 
> 其他我看了没有啥问题。请改一下 commit 文字，我就 approve 了。

commit 已修改

2024-08-01 08:31 UTC, unicornx commented
> > commit 里的英文感觉不对
> > > The cvitek adc dirver now only support one adc controller, but missing another adc controller RTCSYS_SARADC.
> > 
> > 
> > 可以用机翻。
> > 我把这段文字先翻译成中文，然后再翻译成英文后得到如下：
> > cvitek adc dirver only supports one adc controller now, but the other adc controller RTCSYS_SARADC is missing.
> > 你可以对比一下差别在哪里？ ：）
> > 其他我看了没有啥问题。请改一下 commit 文字，我就 approve 了。
> 
> commit 已修改

一行太长了，不要超过 75 个字符

2024-08-05 01:24 UTC, unicornx commented
代码注释中有两处 FIXME 这次改动后应该删除了，请清理。

请仔细。

2024-08-05 07:51 UTC, Z8MAN8 commented
> 代码注释中有两处 FIXME 这次改动后应该删除了，请清理。
> 
> 请仔细。

抱歉，已重新完善

2024-08-05 08:57 UTC, unicornx approved these changes

2024-08-06 00:31 UTC, unicornx approved these changes
已 review

2024-08-06 00:32 UTC, unicornx approved these changes

2024-08-06 00:40 UTC, unicornx approved these changes

2024-08-07 03:15 UTC, Rbb666 approved these changes

2024-08-07 03:15 UTC, merged