bsp: cvitek: fix cv18xx_risc-v and c906_little IRQ_MAX_NR error num
RT-Thread/rt-thread pull request #9261
Opened 2024-07-29 06:16 UTC by Z8MAN8

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
Fixed https://github.com/RT-Thread/rt-thread/issues/9259

#### 你的解决方案是什么 (what is your solution)
参照datasheet将cv18xx_risc-v和c906_little的IRQ_MAX_NR值分别改为101和61

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-07-29 06:41 UTC, unicornx commented on bsp/cvitek/c906_little/board/interrupt.h
> +#define IRQ_MAX_NR          61
既然是作为 Kconfig 配置了，为啥还要在头文件中定义？请继续研究。

2024-07-29 06:42 UTC, unicornx requested changes
见上面 comments。

2024-07-29 06:49 UTC, Z8MAN8 commented on bsp/cvitek/c906_little/board/interrupt.h
> +#define IRQ_MAX_NR          61
这里只有在没有定义 IRQ_MAX_NR 的情况下才会启用。且该文件没有统一使用 libcpu 中的文件，继续推进可能涉及到 https://github.com/RT-Thread/rt-thread/issues/8977

2024-07-29 07:06 UTC, unicornx commented on bsp/cvitek/c906_little/board/interrupt.h
> +#define IRQ_MAX_NR          61
> 这里只有在没有定义 IRQ_MAX_NR 的情况下才会启用。且该文件没有统一使用 libcpu 中的文件，继续推进可能涉及到 #8977

我没深入看 #8977 

但是这里一个工程里出现两个 IRQ_MAX_NR 肯定不合适的。

是否可以去掉 `bsp/cvitek/c906_little/board/interrupt.h` 里的 `IRQ_MAX_NR`，然后在 `bsp/cvitek/c906_little/board/interrupt.h` 里 `#include <rtconfig.h>`。也就是说我们以 `rtconfig.h` 也就是我们 Kconfig 配置的值为准。

2024-08-06 00:38 UTC, unicornx approved these changes

2024-08-06 00:39 UTC, unicornx requested changes
需要继续修改

2024-08-07 01:28 UTC, unicornx requested changes
请将 commit 压缩成一个后再提交 review。

review request 前请仔细检查。

2024-08-07 01:31 UTC, Z8MAN8 commented
> 请将 commit 压缩成一个后再提交 review。
> 
> review request 前请仔细检查。

是因为 https://github.com/RT-Thread/rt-thread/issues/9259 建议大小核分成两个 commit

2024-08-07 01:36 UTC, unicornx commented
> > 请将 commit 压缩成一个后再提交 review。
> > review request 前请仔细检查。
> 
> 是因为 #9259 建议大小核分成两个 commit

sorry, 我忘记了，我收回我的话。

2024-08-07 01:37 UTC, unicornx approved these changes
已 review。

2024-08-07 03:28 UTC, Rbb666 approved these changes

2024-08-07 03:35 UTC, merged