bsp: cvitek: Canonically rename some macro definitions
RT-Thread/rt-thread pull request #9298
Opened 2024-08-12 11:34 UTC by Z8MAN8

Analysis: Some macro definition names are not standardized and lack prefixes.

Solution: Add BSP_ prefix to GPIO_IRQ_BASE and
SYS_GPIO_IRQ_BASE.  Refer to libcpu/risc-v/t-head/c906 to rename PLIC_PHY_ADDR to C906_PLIC_PHY_ADDR, enable RT_USING_CPUTIME and delete redundant TIMER_CLK_FREQ

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
Fixed https://github.com/RT-Thread/rt-thread/issues/9239

#### 你的解决方案是什么 (what is your solution)
详细见commit

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-12 11:35 UTC, Z8MAN8 commented
@unicornx

2024-08-16 08:07 UTC, unicornx commented
@polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？

2024-08-16 08:28 UTC, polarvid commented
> @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？

这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。

2024-08-16 08:33 UTC, polarvid approved these changes

2024-08-16 08:33 UTC, unicornx commented
> > @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？
> 
> 这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。

OK。 @Z8MAN8 请检查一下 bsp/cvitek 下的 Kconfig 中 BSP 自己定义的配置选项，都加上 "BSP_“ 的前缀，我看了一下，应该还有其他的也需要改。

2024-08-16 08:43 UTC, unicornx commented
@Z8MAN8 我看你这个 PR 中针对 c906_little 将 `TIMER_CLK_FREQ` 改为 `CONFIG_RT_USING_CPUTIME`， 这个我感觉有点不妥。
原来 c906_little 中是不启用 ”components/drivers/cputime“ 这个模块的。你这么做仅仅为了借用 `CONFIG_RT_USING_CPUTIME` 这个宏就对 c906_little 开启了 ”components/drivers/cputime“ 这个模块会导致该模块参与编译的。

我猜你这么做是看到 cv18xx_riscv 中用到了 ”components/drivers/cputime“ 这个模块，所以针对大核我们用  `CONFIG_RT_USING_CPUTIME` 代替 `TIMER_CLK_FREQ` 是可以的。但是对于小核，目前小核和大核的项目构建是不统一的，在 tick 和 cputime 上的处理也不同。

所以我建议对小核我们不要这么做，还是保留原来的 `TIMER_CLK_FREQ`，只要将 `TIMER_CLK_FREQ` 加上 `BSP_` 前缀即可。

2024-08-16 09:02 UTC, unicornx commented
@Z8MAN8 另外你对小核中 `PLIC_PHY_ADDR` 的修改我觉得也要仔细考虑一下。

因为你如果搜索过 RTT 源码的话，你会发现 libcpu/risc-v/t-head/c906/plic.c` 中会用到这个宏。你的初衷我猜测是想和大核的处理统一。但是还是那个原因，小核和大核的构建完全没有遵循同一个体系（大核用到了 plic.c, 小核完全没有），所以我不建议你这里将 `PLIC_PHY_ADDR` 和大核的 `C906_PLIC_PHY_ADDR` 混起来用。虽然小核编译时应该是没有用到 plic.c 这个文件，这里只是感觉不要进一步引入任何可能耦合的可能性。

简单加上 ”BSP_" 前缀即可。

2024-08-16 09:03 UTC, unicornx commented
大核和小核的构建现在完全自己搞一套我觉得真的很麻烦，是否可以统一？据我了解 duo 上大核和小核其实都有mmu，区别仅仅是一些中断号不同而已。

@polarvid 当初小核和大核分开做工程的原因是什么，我们是否以后可以将两者合并统一？

2024-08-16 09:03 UTC, unicornx requested changes
原因见上面的评论。

2024-08-16 09:29 UTC, unicornx commented
> > 大核和小核的构建现在完全自己搞一套我觉得真的很麻烦，是否可以统一？据我了解 duo 上大核和小核其实都有mmu，区别仅仅是一些中断号不同而已。
> > 当初小核和大核分开做工程的原因是什么，我们是否以后可以将两者合并统一？
> 
> @unicornx 这个得找第一个支持 cvitek 的人问问了。好像第一版就是这样的。我平常其实也不怎么编译小核。
> 
> 不过我觉得大小核区分配置就好了。没必要连构建过程都隔离出来。

我当时问过 @flyingcys , 好像现在做成这样，一方面是历史原因，一方面是因为当时以为 小核没有 mmu，所以就奔着 RT-thread standard 的方式去构建了。

2024-08-16 09:31 UTC, unicornx commented
> > > @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？
> > 
> > 
> > 这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。
> 
> OK。 @Z8MAN8 请检查一下 bsp/cvitek 下的 Kconfig 中 BSP 自己定义的配置选项，都加上 "BSP_“ 的前缀，我看了一下，应该还有其他的也需要改。

@Z8MAN8 你先总结一下有哪些要加前缀的吧，总结一下列出来看看。如果比较多，我建议分批改，否则一个pr没法 review :(

2024-08-16 10:20 UTC, Z8MAN8 commented
> @Z8MAN8 另外你对小核中 `PLIC_PHY_ADDR` 的修改我觉得也要仔细考虑一下。
> 
> 因为你如果搜索过 RTT 源码的话，你会发现 libcpu/risc-v/t-head/c906/plic.c`中会用到这个宏。你的初衷我猜测是想和大核的处理统一。但是还是那个原因，小核和大核的构建完全没有遵循同一个体系（大核用到了 plic.c, 小核完全没有），所以我不建议你这里将`PLIC_PHY_ADDR`和大核的`C906_PLIC_PHY_ADDR` 混起来用。虽然小核编译时应该是没有用到 plic.c 这个文件，这里只是感觉不要进一步引入任何可能耦合的可能性。
> 
> 简单加上 ”BSP_" 前缀即可。

是的，CONFIG_RT_USING_CPUTIME 和 C906_PLIC_PHY_ADDR 主要是参考了大核的，那我改成简单的加上”BSP_" 前缀

2024-08-16 10:27 UTC, Z8MAN8 commented
> > > > @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？
> > > 
> > > 
> > > 这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。
> > 
> > 
> > OK。 @Z8MAN8 请检查一下 bsp/cvitek 下的 Kconfig 中 BSP 自己定义的配置选项，都加上 "BSP_“ 的前缀，我看了一下，应该还有其他的也需要改。
> 
> @Z8MAN8 你先总结一下有哪些要加前缀的吧，总结一下列出来看看。如果比较多，我建议分批改，否则一个pr没法 review :(

bsp/cvitek 中的应该除了我这次改动的，只有 IRQ_MAX_NR 没有改动了。这部分是因为参考了其他的bsp使用的也没有添加前缀，例如 aarch64 系列 使用的 MAX_HANDLERS。而且改动 IRQ_MAX_NR 涉及范围较大，还包含 bouffalo_lab 中的 bsp 以及 libcpu，因此对 IRQ_MAX_NR 进行了保留。

2024-08-17 08:11 UTC, unicornx commented
> > > > > @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？
> > > > 
> > > > 
> > > > 这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。
> > > 
> > > 
> > > OK。 @Z8MAN8 请检查一下 bsp/cvitek 下的 Kconfig 中 BSP 自己定义的配置选项，都加上 "BSP_“ 的前缀，我看了一下，应该还有其他的也需要改。
> > 
> > 
> > @Z8MAN8 你先总结一下有哪些要加前缀的吧，总结一下列出来看看。如果比较多，我建议分批改，否则一个pr没法 review :(
> 
> bsp/cvitek 中的应该除了我这次改动的，只有 IRQ_MAX_NR 没有改动了。这部分是因为参考了其他的bsp使用的也没有添加前缀，例如 aarch64 系列 使用的 MAX_HANDLERS。而且改动 IRQ_MAX_NR 涉及范围较大，还包含 bouffalo_lab 中的 bsp 以及 libcpu，因此对 IRQ_MAX_NR 进行了保留。

`IRQ_MAX_NR` 先不改了吧

我看了一下还有下面这些需要加 BSP 前缀， 你再把 bsp/cvitek 下的 Kconfig 文件再过一下呢：
- `SOC_TYPE_XXXX`
-`BOARD_TYPE_XXXX`
- `I2C_IRQ_BASE`
- `UART_IRQ_BASE`
- `SOC_CV18XX_AARCH64`

2024-08-17 08:25 UTC, Z8MAN8 commented
> > > > > > @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？
> > > > > 
> > > > > 
> > > > > 这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。
> > > > 
> > > > 
> > > > OK。 @Z8MAN8 请检查一下 bsp/cvitek 下的 Kconfig 中 BSP 自己定义的配置选项，都加上 "BSP_“ 的前缀，我看了一下，应该还有其他的也需要改。
> > > 
> > > 
> > > @Z8MAN8 你先总结一下有哪些要加前缀的吧，总结一下列出来看看。如果比较多，我建议分批改，否则一个pr没法 review :(
> > 
> > 
> > bsp/cvitek 中的应该除了我这次改动的，只有 IRQ_MAX_NR 没有改动了。这部分是因为参考了其他的bsp使用的也没有添加前缀，例如 aarch64 系列 使用的 MAX_HANDLERS。而且改动 IRQ_MAX_NR 涉及范围较大，还包含 bouffalo_lab 中的 bsp 以及 libcpu，因此对 IRQ_MAX_NR 进行了保留。
> 
> `IRQ_MAX_NR` 先不改了吧
> 
> 我看了一下还有下面这些需要加 BSP 前缀， 你再把 bsp/cvitek 下的 Kconfig 文件再过一下呢：
> 
> * `SOC_TYPE_XXXX`
> * `BOARD_TYPE_XXXX`
> * `I2C_IRQ_BASE`
> * `UART_IRQ_BASE`
> * `SOC_CV18XX_AARCH64`

SOS_ 和 BOARD_ 前缀的应该不用改了吧，我把 I2C_IRQ_BASE 和 UART_IRQ_BASE 也加上 BSP_ 前缀

2024-08-17 08:42 UTC, unicornx commented
> > > > > > > @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？
> > > > > > 
> > > > > > 
> > > > > > 这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。
> > > > > 
> > > > > 
> > > > > OK。 @Z8MAN8 请检查一下 bsp/cvitek 下的 Kconfig 中 BSP 自己定义的配置选项，都加上 "BSP_“ 的前缀，我看了一下，应该还有其他的也需要改。
> > > > 
> > > > 
> > > > @Z8MAN8 你先总结一下有哪些要加前缀的吧，总结一下列出来看看。如果比较多，我建议分批改，否则一个pr没法 review :(
> > > 
> > > 
> > > bsp/cvitek 中的应该除了我这次改动的，只有 IRQ_MAX_NR 没有改动了。这部分是因为参考了其他的bsp使用的也没有添加前缀，例如 aarch64 系列 使用的 MAX_HANDLERS。而且改动 IRQ_MAX_NR 涉及范围较大，还包含 bouffalo_lab 中的 bsp 以及 libcpu，因此对 IRQ_MAX_NR 进行了保留。
> > 
> > 
> > `IRQ_MAX_NR` 先不改了吧
> > 我看了一下还有下面这些需要加 BSP 前缀， 你再把 bsp/cvitek 下的 Kconfig 文件再过一下呢：
> > 
> > * `SOC_TYPE_XXXX`
> > * `BOARD_TYPE_XXXX`
> > * `I2C_IRQ_BASE`
> > * `UART_IRQ_BASE`
> > * `SOC_CV18XX_AARCH64`
> 
> SOC_ 和 BOARD_ 前缀的应该不用改了吧，我把 I2C_IRQ_BASE 和 UART_IRQ_BASE 也加上 BSP_ 前缀

ok， 其他你再仔细检查一下，不要再漏了什么

2024-08-17 08:46 UTC, Z8MAN8 commented
> > > > > > > > @polarvid 请问一下 RTT 这边配置宏的命名规则是什么？是不是说 BSP 级别的配置宏都要统一加上 "BSP_" 的前缀？
> > > > > > > 
> > > > > > > 
> > > > > > > 这个好像没有强制要求。不过统一起来是最好的，这样方便找到配置来源。
> > > > > > 
> > > > > > 
> > > > > > OK。 @Z8MAN8 请检查一下 bsp/cvitek 下的 Kconfig 中 BSP 自己定义的配置选项，都加上 "BSP_“ 的前缀，我看了一下，应该还有其他的也需要改。
> > > > > 
> > > > > 
> > > > > @Z8MAN8 你先总结一下有哪些要加前缀的吧，总结一下列出来看看。如果比较多，我建议分批改，否则一个pr没法 review :(
> > > > 
> > > > 
> > > > bsp/cvitek 中的应该除了我这次改动的，只有 IRQ_MAX_NR 没有改动了。这部分是因为参考了其他的bsp使用的也没有添加前缀，例如 aarch64 系列 使用的 MAX_HANDLERS。而且改动 IRQ_MAX_NR 涉及范围较大，还包含 bouffalo_lab 中的 bsp 以及 libcpu，因此对 IRQ_MAX_NR 进行了保留。
> > > 
> > > 
> > > `IRQ_MAX_NR` 先不改了吧
> > > 我看了一下还有下面这些需要加 BSP 前缀， 你再把 bsp/cvitek 下的 Kconfig 文件再过一下呢：
> > > 
> > > * `SOC_TYPE_XXXX`
> > > * `BOARD_TYPE_XXXX`
> > > * `I2C_IRQ_BASE`
> > > * `UART_IRQ_BASE`
> > > * `SOC_CV18XX_AARCH64`
> > 
> > 
> > SOC_ 和 BOARD_ 前缀的应该不用改了吧，我把 I2C_IRQ_BASE 和 UART_IRQ_BASE 也加上 BSP_ 前缀
> 
> ok， 其他你再仔细检查一下，不要再漏了什么

好的

2024-08-18 08:29 UTC, Z8MAN8 commented
已更新，请review

2024-08-19 00:57 UTC, unicornx approved these changes

2024-08-20 01:51 UTC, Rbb666 approved these changes

2024-08-20 01:52 UTC, merged