bsp: cvitek: Add timer driver
RT-Thread/rt-thread pull request #9299
Opened 2024-08-12 14:00 UTC by Solonix-Chu

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
添加 timer 驱动

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-12 14:00 UTC, Z8MAN8 commented
@unicornx

2024-08-16 09:34 UTC, unicornx commented on bsp/cvitek/c906_little/board/Kconfig
> +    menuconfig BSP_USING_HWTIMER
为啥只有 4 ~ 7? 我看 TRM 第十二章节 定时器部分有 8 个 Timer 模块呢？

2024-08-16 09:34 UTC, unicornx commented on bsp/cvitek/c906_little/board/Kconfig
> +            config TIMER_IRQ_BASE
配置宏要加 BSP 前缀

2024-08-16 09:42 UTC, unicornx commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +                    default 80
CV800b 也是从 79 开始的吧，你看的是什么文档？

我看的是 https://github.com/milkv-duo/duo-files/tree/main/duo/datasheet

2024-08-16 09:44 UTC, unicornx commented on bsp/cvitek/c906_little/board/Kconfig
> +                default 51
小核是 55 吧？你这个 51 哪里来的？

2024-08-16 09:53 UTC, unicornx requested changes
建议修改，意见见上

2024-08-16 10:03 UTC, Z8MAN8 commented on bsp/cvitek/c906_little/board/Kconfig
> +                default 51
小核55是Timer4中断，Timer0~3是不支持的，定时器驱动中中断号计算方式为TIMER_IRQ_BASE + x

2024-08-16 10:13 UTC, Z8MAN8 commented
> 建议代码中不要叫 hwtimer，官方文档就叫 timer，而且目前代码中有时候叫 HWTIMER 有时候又叫 TIMER，还有 “hal_” 的前缀。建议统一为 timer。
> 
> 包括文件名和各种函数，宏名，都建议统一为 timer。
> 
> 而且代码中都带有 DW_ 前缀，不知道想表达什么，是不是因为用了 Synopsis 的 DW ip？

因为主要参照了算能的cvi_alios_open

2024-08-17 08:36 UTC, unicornx commented on bsp/cvitek/c906_little/board/Kconfig
> +                default 51
你这么做属于 hack 的做法，在 TRM 上 51 号中断在小核上明确是属于 RTC WDG 的。

![image](https://github.com/user-attachments/assets/b9223cb2-db33-4ecf-9f12-3866968cee44)

请修改你的代码，不要这么做。

2024-08-17 08:38 UTC, unicornx commented
> > 建议代码中不要叫 hwtimer，官方文档就叫 timer，而且目前代码中有时候叫 HWTIMER 有时候又叫 TIMER，还有 “hal_” 的前缀。建议统一为 timer。
> > 包括文件名和各种函数，宏名，都建议统一为 timer。
> > 而且代码中都带有 DW_ 前缀，不知道想表达什么，是不是因为用了 Synopsis 的 DW ip？
> 
> 因为主要参照了算能的cvi_alios_open

你的回答让我不知道是接受还是拒绝。感觉上是拒绝。

我不是说提的 comments 都要无条件接受，只要有合理的理由当然可以拒绝。但是希望在回复上明确指出。

2024-08-17 08:43 UTC, Z8MAN8 commented on bsp/cvitek/c906_little/board/Kconfig
> +                default 51
好的，这部分会重新修改代码，避免hack

2024-08-17 08:45 UTC, Z8MAN8 commented
> > > 建议代码中不要叫 hwtimer，官方文档就叫 timer，而且目前代码中有时候叫 HWTIMER 有时候又叫 TIMER，还有 “hal_” 的前缀。建议统一为 timer。
> > > 包括文件名和各种函数，宏名，都建议统一为 timer。
> > > 而且代码中都带有 DW_ 前缀，不知道想表达什么，是不是因为用了 Synopsis 的 DW ip？
> > 
> > 
> > 因为主要参照了算能的cvi_alios_open
> 
> 你的回答让我不知道是接受还是拒绝。感觉上是拒绝。
> 
> 我不是说提的 comments 都要无条件接受，只要有合理的理由当然可以拒绝。但是希望在回复上明确指出。

好的，同意将HWTIMER统一改为timer，但保留 hal_ 和 DW_ 前缀

2024-08-17 08:48 UTC, unicornx commented
> > > > 建议代码中不要叫 hwtimer，官方文档就叫 timer，而且目前代码中有时候叫 HWTIMER 有时候又叫 TIMER，还有 “hal_” 的前缀。建议统一为 timer。
> > > > 包括文件名和各种函数，宏名，都建议统一为 timer。
> > > > 而且代码中都带有 DW_ 前缀，不知道想表达什么，是不是因为用了 Synopsis 的 DW ip？
> > > 
> > > 
> > > 因为主要参照了算能的cvi_alios_open
> > 
> > 
> > 你的回答让我不知道是接受还是拒绝。感觉上是拒绝。
> > 我不是说提的 comments 都要无条件接受，只要有合理的理由当然可以拒绝。但是希望在回复上明确指出。
> 
> 好的，同意将HWTIMER统一改为timer，但保留 hal_ 和 DW_ 前缀

好吧，要不先这样

2024-08-18 08:58 UTC, Z8MAN8 commented
已修改，请review

2024-08-19 00:29 UTC, unicornx commented
oops，我第一眼看到的 commit titile 里还是 hwtimer， 你再检查一下?

2024-08-19 00:58 UTC, unicornx commented on bsp/cvitek/c906_little/board/Kconfig
> +            config TIMER_IRQ_BASE
> 配置宏要加 BSP 前缀

no ack yet

2024-08-19 00:59 UTC, unicornx commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +                    default 80
> CV800b 也是从 79 开始的吧，你看的是什么文档？
> 
> 我看的是 https://github.com/milkv-duo/duo-files/tree/main/duo/datasheet

no ack yet

2024-08-19 03:13 UTC, Z8MAN8 commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +                    default 80
已更正为79

2024-08-19 03:13 UTC, Z8MAN8 commented on bsp/cvitek/c906_little/board/Kconfig
> +            config TIMER_IRQ_BASE
已添加 BSP 前缀

2024-08-20 01:25 UTC, unicornx commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +    menuconfig BSP_USING_HWTIMER
HWTIMER ?

2024-08-20 01:25 UTC, unicornx commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +                bool "Enable HWTIMER0"
HWTIMER0 ?

2024-08-20 01:25 UTC, unicornx commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +        bool "Enable HWTIMER"
HWTIMER?

2024-08-20 01:32 UTC, unicornx commented on bsp/cvitek/drivers/drv_timer.c
> +    /*FIXME: no less than 10*/
这个 FIXME 是什么意思？是一个遗留问题还是已经解决了？

注释中的 "no less than 10" 是什么原因？请在注释中说明原因，而不是解释下面代码的行为，代码的行为直接看代码就可以了，但是为什么这么做才是需要解释的。

2024-08-20 01:38 UTC, unicornx commented on bsp/cvitek/drivers/drv_timer.c
> +#else
驱动应该是对 riscv 和 arm 都适用的，你这么做没有考虑 arm64 的 bsp

2024-08-20 01:41 UTC, unicornx commented on bsp/cvitek/drivers/drv_timer.c
> +#error "Unsupported CPU type!"
驱动应该是对 riscv 和 arm 都适用的，你这么做没有考虑 arm64 的 bsp

2024-08-20 01:43 UTC, unicornx commented on bsp/cvitek/drivers/drv_timer.c
> +    }
其他情况如果不支持应该返回失败

2024-08-20 01:46 UTC, unicornx commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +                bool "Enable HWTIMER0"
Kconfig 中全都需要改一下，请注意 HWTIMER 在 RTT 中的已经被 `components/drivers/hwtimer/` 使用了，所以我们要尽量避开。

2024-08-20 01:47 UTC, unicornx requested changes
还有些问题，请继续修改。

代码修改还是需要更仔细一些。

2024-08-20 05:46 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_timer.c
> +    /*FIXME: no less than 10*/
这个是从算能的cvi_alios_open中保留的

2024-08-20 05:53 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_timer.c
> +#error "Unsupported CPU type!"
之前确实没考虑arm64，马上完善

2024-08-20 05:53 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_timer.c
> +    }
好的

2024-08-20 05:54 UTC, Z8MAN8 commented on bsp/cvitek/cv18xx_risc-v/board/Kconfig
> +                bool "Enable HWTIMER0"
好的，马上更改

2024-08-20 13:57 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_timer.c
> +    }
已添加错误返回

2024-08-21 21:33 UTC, unicornx commented on bsp/cvitek/cv18xx_aarch64/board/Kconfig
> +                default 95
不是 79 吗，你有测试过提交的代码吗？

2024-08-21 21:36 UTC, unicornx commented on bsp/cvitek/cv18xx_aarch64/board/Kconfig
> +
arm bsp 部分我们就不增加配置内容了吧，我们目前针对 arm 部分的原则是只保证现有代码编译ok, 以及最小 uart 工作即可。

2024-08-21 21:44 UTC, unicornx commented
这一版差不多了，我提了一个comment，见上，你改一下，我就 approve 了。

2024-08-23 04:12 UTC, Z8MAN8 commented on bsp/cvitek/cv18xx_aarch64/board/Kconfig
> +
好的，已修改，已去除arm bsp 部分配置内容

2024-08-24 00:21 UTC, unicornx approved these changes

2024-08-25 00:50 UTC, BernardXiong approved these changes

2024-08-25 16:11 UTC, merged