[bsp/cvitek] eth driver support phy link detect
RT-Thread/rt-thread pull request #9317
Opened 2024-08-18 05:33 UTC by flyingcys

Signed-off-by: flyingcys <flyingcys@163.com>

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
修改drv_eth 驱动，支持phy自动检测

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:
bsp/cvitek/cv18xx_risc-v

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-28 00:23 UTC, unicornx commented on bsp/cvitek/drivers/drv_eth.c
> +    while(1)
`while` 和 `(` 之间加空格

2024-08-28 00:24 UTC, unicornx commented on bsp/cvitek/drivers/drv_eth.c
> +        if(link_status_old != link_status)
`if` 和 `(` 之间加空格

2024-08-28 00:26 UTC, unicornx commented on bsp/cvitek/drivers/drv_eth.c
> +    }
缺少失败处理

2024-08-28 00:26 UTC, unicornx commented on bsp/cvitek/drivers/libraries/eth/cvi_eth_phy.c
> +}
该函数缩进格式不正常。有没有用 formating 检查？

2024-08-28 00:32 UTC, unicornx commented on bsp/cvitek/drivers/libraries/eth/dw_eth_mac.h
> +  \return      error code
建议与 src 目录代码保持一致，使用 doxygen 语法注释 API。这样也可以自动生成文档。
具体 doxygen 语法使用参考 https://blog.csdn.net/qq_41204464/article/details/102458103

2024-08-28 00:34 UTC, unicornx requested changes
请参考上面的 review 意见。

2024-09-02 15:33 UTC, flyingcys commented on bsp/cvitek/drivers/libraries/eth/dw_eth_mac.h
> +  \return      error code
其他地方已经修改，libraries下是从原厂copy代码，暂不做修改

2024-09-02 23:54 UTC, unicornx approved these changes

2024-09-03 22:17 UTC, mysterywolf approved these changes

2024-09-03 22:17 UTC, merged