【修复】 修复dup系统调用对用户态的返回值问题
RT-Thread/rt-thread pull request #9324
Opened 2024-08-21 05:54 UTC by zhuzhuzhus

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
 修复dup系统调用对用户态的返回值问题，对于超出fd范围的errno没有被设置吗，使得用户传入错误的fd后读取errno无法获得预期结果
#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-24 06:45 UTC, BernardXiong approved these changes

2024-08-24 19:45 UTC, mysterywolf requested changes

2024-08-24 19:45 UTC, mysterywolf commented on components/dfs/dfs_v2/src/dfs.c
> +    return err < 0?err : newfd;
```suggestion
    return err < 0 ? err : newfd;
```

2024-08-24 19:45 UTC, mysterywolf commented on components/dfs/dfs_v2/src/dfs.c
> +    return err < 0?err : newfd;
```suggestion
    return err < 0 ? err : newfd;
```

2024-08-24 19:45 UTC, mysterywolf commented on components/dfs/dfs_v2/src/dfs.c
> +        rt_set_errno(-EBADF);
rt_set_errno是正值 return是负值

2024-08-25 08:13 UTC, zhuzhuzhus commented on components/dfs/dfs_v2/src/dfs.c
> +        rt_set_errno(-EBADF);
文件系统和很多系统调用里面都是set_erron设置为负值，就根据他这样写了

2024-08-25 08:13 UTC, zhuzhuzhus commented on components/dfs/dfs_v2/src/dfs.c
> +        rt_set_errno(-EBADF);
感觉这个问题可以提一个单独的pr全部修改过来

2024-08-25 14:56 UTC, mysterywolf approved these changes

2024-08-25 14:56 UTC, merged