bsp: cvitek: Add support for duos_sd
RT-Thread/rt-thread pull request #9339
Opened 2024-08-24 15:18 UTC by Z8MAN8

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
添加对 milkv duos sd 的支持

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/cvitek

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-24 15:19 UTC, Z8MAN8 commented
@unicornx

2024-08-26 02:42 UTC, unicornx commented on bsp/cvitek/drivers/drv_uart.c
> +static const char *pinname_whitelist_uart2_rx[] = {
我看 https://milkv.io/docs/duo/getting-started/duos 上 UART2 引出的引脚好像没这么多吧？你确定 UART2 的 TX 核 RX 各有 8 个？

2024-08-26 02:52 UTC, unicornx commented on bsp/cvitek/README.md
> +- milk-v duos: [https://milkv.io/duos](https://milkv.io/docs/duo/getting-started/duos)，SoC 采用 SG2000。
请在文档里说明一下，SG2002 相当于 CV181xC， SG2000 对应 CV181xH，方便大家理解。
你可以在 SG2002 和 SG2000 后面加个括号里写上 CV 的代号。譬如 “SG2002（原 CV181xC）” 这样子的。

2024-08-26 02:53 UTC, unicornx commented
我看你目前只支持了 UART 部分，请在 commit 的 文字中说明一下。

2024-08-26 02:53 UTC, unicornx requested changes
评论见上。

2024-08-26 15:00 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_uart.c
> +static const char *pinname_whitelist_uart2_rx[] = {
抱歉，引脚复用根据 datasheet 全添上去了，没有根据板子信息，已修改

2024-08-26 15:01 UTC, Z8MAN8 commented on bsp/cvitek/README.md
> +- milk-v duos: [https://milkv.io/duos](https://milkv.io/docs/duo/getting-started/duos)，SoC 采用 SG2000。
已添加说明

2024-08-26 15:01 UTC, Z8MAN8 commented
> Contributor

已添加说明

2024-08-26 15:01 UTC, Z8MAN8 commented
> 评论见上。



> 我看你目前只支持了 UART 部分，请在 commit 的 文字中说明一下。
> 
> 以及该 PR 也没有支持 ARM 的 bsp，请也说明一下。

已添加说明

2024-08-26 22:46 UTC, unicornx commented on bsp/cvitek/drivers/drv_uart.c
> +static const char *pinname_whitelist_uart2_rx[] = {
现在你理解代码中 whitelist（白名单）的意思了吧，就是虽然 soc 上有那么多signal 支持，但是由于 board level 的引脚限制，其实我们用不了那么多的。Kconfig 菜单上允许用户随便配置（字符串），在 bsp 驱动层加了白名单限制。

2024-08-26 23:03 UTC, unicornx requested changes
其他我都 ok 啦。

只是 commit 上的英文我感觉写得有点让人看不懂。

> The RISC-V C906 large and small cores are adapted,
> but the ARM cores are not yet adapted. Only the UART
> driver is interconnected.

直接拿百度翻译了一下：

```
RISC-V C906大大小小的内核都进行了调整，
但ARM内核尚未适应。只有UART
驱动器是相互关联的。
```
这个 adapt 和  interconnected 用了感觉好怪，直接用 support 不好么？

我尝试改了一下，你看看如何？

```
支持了 RISC-V C906 的大核和小核，但没有支持 ARM 核。
在外设上目前只支持了 UART 驱动。
```
百度翻译如下：
```
Supports both large and small cores of RISC-V C906, but does not support ARM cores.
Currently, only UART drivers are supported on the peripherals.
```

2024-08-26 23:04 UTC, unicornx commented
请改一下 commit，我就直接 approve 了

2024-08-27 01:29 UTC, BernardXiong commented
big and little cores

2024-08-27 02:17 UTC, Z8MAN8 commented on bsp/cvitek/drivers/drv_uart.c
> +static const char *pinname_whitelist_uart2_rx[] = {
现在明白了

2024-08-27 02:18 UTC, Z8MAN8 commented
> 请改一下 commit，我就直接 approve 了

已修改

2024-08-27 02:18 UTC, Z8MAN8 commented
> big and little cores

已修改

2024-08-27 02:58 UTC, unicornx approved these changes

2024-08-27 04:53 UTC, mysterywolf approved these changes

2024-08-27 04:53 UTC, merged