[bsp][ht32] 修复编译问题
RT-Thread/rt-thread pull request #9346
Opened 2024-08-25 19:46 UTC by CYFS3

## 拉取/合并请求描述：(PR description)

[
#7764 
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-25 19:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9346) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9346) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=9346) it.</sub>

2024-08-25 19:55 UTC, supperthomas requested changes

2024-08-25 19:55 UTC, supperthomas commented on bsp/ht32/libraries/HT32_STD_1xxxx_FWLib/SConscript
> +    'USE_HT32_DRIVER'
感谢提交PR。
这些配置放到menuconfig里面，会保护更好一些。试试看。

2024-08-25 19:55 UTC, supperthomas commented on bsp/ht32/libraries/HT32_STD_5xxxx_FWLib/SConscript
>  group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
请尝试再CI中添加对应的测试bsp。，参考.github/workflow/bsp_building.yml

2024-08-25 20:42 UTC, CYFS3 commented on bsp/ht32/libraries/HT32_STD_1xxxx_FWLib/SConscript
> +    'USE_HT32_DRIVER'
请问是在Kconfig中修改吗

2024-08-26 00:43 UTC, supperthomas approved these changes

2024-08-26 00:43 UTC, supperthomas commented on bsp/ht32/libraries/HT32_STD_1xxxx_FWLib/SConscript
> +    'USE_HT32_DRIVER'
可以参考其他bsp/nrf5x

2024-08-26 08:35 UTC, CYFS3 commented on bsp/ht32/libraries/HT32_STD_1xxxx_FWLib/SConscript
> +    'USE_HT32_DRIVER'
我不是很明白这个bsp/nrf5x是怎么做的，您能给我点信息吗

2024-08-26 14:19 UTC, CYFS3 commented
我在本地测试是可以的，然后看了ci也没有问题。
<command-line>: warning: ISO C99 requires whitespace after the macro name这个警告貌似是他们本身的sdk有问题。
然后使用scons --dist打包的时候会出现不能把[sdk_dist.py](https://github.com/RT-Thread/rt-thread/blob/master/bsp/ht32/tools/sdk_dist.py)一起打包进tools下，这个问题我不清楚是咋回事

2024-08-26 19:27 UTC, supperthomas commented
> 我在本地测试是可以的，然后看了ci也没有问题。
> <command-line>: warning: ISO C99 requires whitespace after the macro name这个警告貌似是他们本身的sdk有问题。
> 然后使用scons --dist打包的时候会出现不能把[sdk_dist.py](https://github.com/RT-Thread/rt-thread/blob/master/bsp/ht32/tools/sdk_dist.py)一起打包进tools下，这个问题我不清楚是咋回事
> 

看下这个

https://supperthomas-wiki.readthedocs.io/10_jiy/04_bsp_support_dist/bsp_support_dist.html

2024-08-26 21:59 UTC, supperthomas commented
> > 我在本地测试是可以的，然后看了ci也没有问题。
> > <command-line>: warning: ISO C99 requires whitespace after the macro name这个警告貌似是他们本身的sdk有问题。
> > 然后使用scons --dist打包的时候会出现不能把[sdk_dist.py](https://github.com/RT-Thread/rt-thread/blob/master/bsp/ht32/tools/sdk_dist.py)一起打包进tools下，这个问题我不清楚是咋回事
> > 
> 
> 看下这个
> 
> https://supperthomas-wiki.readthedocs.io/10_jiy/04_bsp_support_dist/bsp_support_dist.html

tools也不一定需要加进去吧？dist出来之后的bsp还需要吗？

2024-08-27 01:43 UTC, Rbb666 commented on bsp/ht32/libraries/HT32_STD_1xxxx_FWLib/SConscript
> +    '__RTTHREAD__',
'__RTTHREAD__、RT_USING_LIBC、RT_USING_ARMLIBC、RT_TICK_PER_SECOND'这种系统相关的宏不用添加

2024-08-27 01:48 UTC, Rbb666 commented on bsp/ht32/libraries/HT32_STD_1xxxx_FWLib/SConscript
> +    '__RTTHREAD__',
RT_USING_LIBC和RT_USING_ARMLIBC是编译器决定的，可以看这里的定义：https://github.com/RT-Thread/rt-thread/blob/dec34f91bf702dda436bca618f47482d3e49f986/components/libc/compilers/armlibc/SConscript#L8

2024-08-27 03:00 UTC, CYFS3 commented
> > > 我在本地测试是可以的，然后看了ci也没有问题。
> > > : warning: ISO C99 requires whitespace after the macro name这个警告貌似是他们本身的sdk有问题。
> > > 然后使用scons --dist打包的时候会出现不能把[sdk_dist.py](https://github.com/RT-Thread/rt-thread/blob/master/bsp/ht32/tools/sdk_dist.py)一起打包进tools下，这个问题我不清楚是咋回事
> > 
> > 
> > 看下这个
> > https://supperthomas-wiki.readthedocs.io/10_jiy/04_bsp_support_dist/bsp_support_dist.html
> 
> tools也不一定需要加进去吧？dist出来之后的bsp还需要吗？

![屏幕截图 2024-08-27 105717](https://github.com/user-attachments/assets/0ca9df74-1c1b-4f06-84e2-3177ccd42b6d)
他的SConstruct中好像有用的sdk_dist中的方法

2024-08-27 03:56 UTC, supperthomas commented
再理一下nrf5x和这里的差别看看

2024-08-28 08:15 UTC, closed without merging