[utest] add smp testcases
RT-Thread/rt-thread pull request #9356
Opened 2024-08-27 09:19 UTC by Yaochenger

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
添加testcases\kernel\smp测试用例

#### 你的解决方案是什么 (what is your solution)
1.smp spinlock测试用例
2.smp 绑核亲和力与线程优先级的测试用例
3.smp 线程抢占测试用例
4.smp 将线程分配至空闲核测试用例
5.smp 中断优先级设置测试用例

#### 请提供验证的bsp和config (provide the config and bsp) 
bsp\qemu-vexpress-a9

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-28 01:46 UTC, Rbb666 commented
@polarvid SMP相关的测试用例，麻烦帮忙review下

2024-08-29 03:56 UTC, polarvid requested changes

2024-08-29 03:56 UTC, polarvid commented on examples/utest/testcases/kernel/smp/smp_bind_affinity_tc.c
> +#define THREAD_STACK_SIZE 1024
建议用 Kconfig 里的 UTEST stack size，而不是测试用例里面又定义一个。跨架构的时候这些定义基本跑不通。

2024-08-29 05:13 UTC, Rbb666 commented on examples/utest/testcases/kernel/smp/smp_bind_affinity_tc.c
> +#define THREAD_STACK_SIZE 1024
@Yaochenger

2024-09-02 03:26 UTC, Yaochenger commented on examples/utest/testcases/kernel/smp/smp_bind_affinity_tc.c
> +#define THREAD_STACK_SIZE 1024
> 建议用 Kconfig 里的 UTEST stack size，而不是测试用例里面又定义一个。跨架构的时候这些定义基本跑不通。

已采纳

2024-09-02 03:27 UTC, Yaochenger commented on examples/utest/testcases/kernel/smp/smp_bind_affinity_tc.c
> +#define THREAD_STACK_SIZE 1024
> @Yaochenger 

> @Yaochenger

已修正

2024-09-02 03:49 UTC, Rbb666 approved these changes

2024-09-03 06:03 UTC, merged