[libcpu/aarch64]atomic实现修改
RT-Thread/rt-thread pull request #9364
Opened 2024-08-29 01:43 UTC by messigogogo

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

在https://github.com/RT-Thread/rt-thread/commit/e9b683d0b338b4c92190702d151e5180d0b10ca0的提交中规范了atomic的实现方式，原本phytium bsp的默认配置同时打开了RT_USING_STDC_ATOMIC/RT_USING_HW_ATOMIC, 关闭后RT_USING_STDC_ATOMIC发现内核不能正常启动，查明原因是libcpu\aarch64\common\atomic_aarch64.c 中rt_hw_atomic_compare_exchange_strong函数逻辑有误

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-29 01:51 UTC, messigogogo commented
在rt_soft_atomic_compare_exchange_strong（ptr, v, des）的实现逻辑中，比较了ptr与v是否相同，若相同则将des赋值给ptr，并返回1；若不同则将ptr赋值给v，并返回0
![b3edad256a75f9c2e7dcd85a6a2aead](https://github.com/user-attachments/assets/4fc2e250-7ddb-42a7-b781-ed28784ef604)

但是在原本的rt_hw_atomic_compare_exchange_strong（ptr, v, des）中，并没有做不同则将ptr赋值给v，并返回0的操作，导致在IPC模块调用该原子操作时有误
![5dd00975e11afe1914518048fa83b26](https://github.com/user-attachments/assets/6a76625a-597f-4d69-b8cf-9e3b67e1f838)

新增了str %0, [%5] ->mov %w1, #0来实现该逻辑
![d02d2a170d9dc4ab3ba8885ad1df8e6](https://github.com/user-attachments/assets/08b9e056-430b-49d6-b5c7-13da0a8ee73d)

2024-08-29 02:12 UTC, messigogogo commented
@polarvid

2024-08-29 03:52 UTC, polarvid commented
> @polarvid

这个挺早好像就有反馈说有问题了。不过 arm64 hw_atomic 不是我这维护的，平时也不用，所以没关注。

关于 PR 修复，建议是使能 HW_ATOMIC 关闭 STDC，然后通过 unittest case 验证一下。这部分的用例是有的。

2024-08-30 03:54 UTC, polarvid commented
配置的修改能拆出来吗？在这个 PR 下好像无关，有点乱了。

2024-09-03 07:59 UTC, polarvid requested changes
![image](https://github.com/user-attachments/assets/498827b2-3340-483d-9169-544bee01b913)

格式检查也请处理一下呢

2024-09-03 11:11 UTC, messigogogo commented
> ![image](https://private-user-images.githubusercontent.com/65584760/363892139-498827b2-3340-483d-9169-544bee01b913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjE4MDksIm5iZiI6MTcyNTM2MTUwOSwicGF0aCI6Ii82NTU4NDc2MC8zNjM4OTIxMzktNDk4ODI3YjItMzM0MC00ODNkLTkxNjktNTQ0YmVlMDFiOTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDExMDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OTU3ZWJmMDE4NGFjNDUxNWIzZmQ5YmYxNzc0NTUxMjBjYzQxMWNhNzhhMzE4M2ZiMDVhNDE2NDE5OTJmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9470FHNHZpWPcsuQnDSgNG2N7ueU8KqEPjSCo0Hf-R8)
> 
> 格式检查也请处理一下呢

修改了

2024-09-03 13:44 UTC, polarvid approved these changes

2024-09-03 22:13 UTC, mysterywolf approved these changes

2024-09-03 22:14 UTC, merged