update(cherryusb): update bl616/hpm6750/mcxn947 cherryusb demo
RT-Thread/rt-thread pull request #9370
Opened 2024-08-31 09:50 UTC by sakumisu

Update cherryusb demo for bl616,hpm6750, mcxn947, enable usb host dfs and lwip as default

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-08-31 09:50 UTC, sakumisu commented
@helloeagleyang @yandld

2024-08-31 12:00 UTC, yandld commented
nxp mcx: 请帮忙合并

2024-08-31 14:52 UTC, BernardXiong commented
这些PR最好是分开来提交，不同的bsp，不同的maintainer来review。

2024-08-31 16:27 UTC, sakumisu commented
> 这些PR最好是分开来提交，不同的bsp，不同的maintainer来review。

 已修改

2024-09-01 02:04 UTC, mysterywolf requested changes

2024-09-01 02:04 UTC, mysterywolf commented on bsp/bouffalo_lab/bl61x/rtconfig.h
> +/* Static IPv4 Address */
不要把这些选项都开开 ，可以设置一个一键开启开关 类似于 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/board/Kconfig#L132

2024-09-01 02:04 UTC, mysterywolf commented on bsp/bouffalo_lab/bl61x/rtconfig.h
> +/* Static IPv4 Address */
一个BSP 默认只开启GPIO 和 UART

2024-09-01 02:31 UTC, sakumisu commented on bsp/bouffalo_lab/bl61x/rtconfig.h
> +/* Static IPv4 Address */
> 一个BSP 默认只开启GPIO 和 UART

测试时发现，kconfig 中select 内容，有些选中的不对，或者 没有选中，需要手动选中

2024-09-01 02:56 UTC, sakumisu commented
重新分开提交pr，此pr关闭

2024-09-01 02:56 UTC, closed without merging