【增加】增加smp_ipi_call
RT-Thread/rt-thread pull request #9427
Opened 2024-09-12 05:20 UTC by zhuzhuzhus

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
在内核中会有需要call其他某个cpu做一些事情的场景，因此可以单独复用一个ipi号专门用来做一些回调函数。

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/qemu-virt64-aarch64

- .config:

- action:utest/smp下有相关测试用例

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-09-12 09:37 UTC, polarvid requested changes
整体来说，这些东西感觉没有庞大到变成独立的模块级别。放在 `components/driver` 下是不是更加合适呢？

2024-09-13 06:11 UTC, polarvid requested changes

2024-09-13 06:11 UTC, polarvid commented on examples/utest/testcases/smp/smp.c
> +void test1()
同理，不需要外部访问的符号尽可能地限制访问域在文件局部即可。

2024-09-13 06:11 UTC, polarvid commented on examples/utest/testcases/smp/smp.c
> +struct rt_spinlock lock;
这类符号限制为 static 是不是更好呢？

2024-09-13 08:55 UTC, polarvid requested changes

2024-09-13 08:55 UTC, polarvid commented on components/drivers/smp/smp.c
> +                rt_spin_lock(&rt_smp_work[tmp_id].lock);
中断场景下需要考虑使用 irq 系列spinlock 接口。

2024-09-13 08:55 UTC, polarvid commented on components/drivers/smp/smp.c
> +    rt_spin_lock(&rt_smp_work[cur_cpu].lock);
对应此处的竞争场景。

2024-09-19 07:11 UTC, polarvid approved these changes

2024-09-19 13:12 UTC, Rbb666 approved these changes

2024-09-19 13:13 UTC, Rbb666 commented on examples/utest/testcases/smp/smp.c
这个文件放在这里是不是好一些？https://github.com/RT-Thread/rt-thread/tree/master/examples/utest/testcases/kernel/smp

2024-09-20 05:02 UTC, zhuzhuzhus commented on examples/utest/testcases/smp/smp.c
我改个名字，最好是单独隔离出来吧，后续还有跟多回调调用这个（例如sysrq）要写测试用例的

2024-09-24 01:56 UTC, Rbb666 approved these changes

2024-09-24 01:56 UTC, merged