[bsp][fm33lc026][rsoc] Fix compilation issues with bsp of fm33lc026
RT-Thread/rt-thread pull request #9485
Opened 2024-09-28 13:52 UTC by hydevcode

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
由于少了link.lds导致无法编译
#### 你的解决方案是什么 (what is your solution)
将link.lds代替为官方的fm33lc02x_flash.ld

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:bsp/fm33lc026

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-09-28 23:10 UTC, supperthomas requested changes
几个编译错误问题类似，，可以考虑放一个pr里面

2024-09-29 01:40 UTC, kurisaW commented
和 https://github.com/RT-Thread/rt-thread/pull/9486 问题类似，gcc需要走entry完成RTOS的一系列初始化，并同步修改fm33lc02x_flash.ld文件

2024-09-29 02:38 UTC, supperthomas requested changes

2024-09-29 02:38 UTC, supperthomas commented on bsp/fm33lc026/rtconfig.py
> +    LFLAGS = DEVICE + ' -Wl,--gc-sections,-Map=rt-thread.map,-cref,-u,Reset_Handler -T libraries/FM/FM33xx/Source/Templates/gcc/linker/fm33lc02x_flash.ld'
ld可以拷贝到board中

2024-09-29 02:49 UTC, milo-9 commented
复旦微这个BSP做得很潦草，我这里在用复旦微系列的mcu，目前我在做lc le lg的BSP，已经做了rtc uart gpio adc dac spi wdt等驱动，等我这边再完善完善，测试完毕后我整个打包提一个pr上来

2024-09-29 02:53 UTC, kurisaW commented on bsp/fm33lc026/rtconfig.py
> +    LFLAGS = DEVICE + ' -Wl,--gc-sections,-Map=rt-thread.map,-cref,-u,Reset_Handler -T libraries/FM/FM33xx/Source/Templates/gcc/linker/fm33lc02x_flash.ld'
这个放在library里是不是更合适一些，看样子是支持同系列的，后续如果想要把官方库抽离成软件包也更加容易维护

2024-09-29 03:10 UTC, supperthomas commented on bsp/fm33lc026/rtconfig.py
> +    LFLAGS = DEVICE + ' -Wl,--gc-sections,-Map=rt-thread.map,-cref,-u,Reset_Handler -T libraries/FM/FM33xx/Source/Templates/gcc/linker/fm33lc02x_flash.ld'
> 这个放在library里是不是更合适一些，看样子是支持同系列的，后续如果想要把官方库抽离成软件包也更加容易维护

放board里面更合适些。每个开发板最好自己单独管理lds，方便后续修改。这个文件会比较频繁的需要修改。

2024-09-29 03:58 UTC, kurisaW commented on bsp/fm33lc026/rtconfig.py
> +    LFLAGS = DEVICE + ' -Wl,--gc-sections,-Map=rt-thread.map,-cref,-u,Reset_Handler -T libraries/FM/FM33xx/Source/Templates/gcc/linker/fm33lc02x_flash.ld'
我们更多的是不是应该只提供一份bsp示例工程，如果说用户有自己的需求想要添加进去一些字段，应该在自己开发的工程下做修改，像一些关于RTT这边定义的一些字段比如ulog之类的，直接放在这里面应该也是合理的吧，只是一些建议哈

2024-09-29 07:03 UTC, hydevcode commented
> 复旦微这个BSP做得很潦草，我这里在用复旦微系列的mcu，目前我在做lc le lg的BSP，已经做了rtc uart gpio adc dac spi wdt等驱动，等我这边再完善完善，测试完毕后我整个打包提一个pr上来

好的，那我这个pr先撤了

2024-09-29 07:04 UTC, closed without merging