[bsp][airm2m/air105][rsoc] Fix compilation issues with bsp of airm2m/air105
RT-Thread/rt-thread pull request #9489
Opened 2024-09-29 09:29 UTC by hydevcode

…air105

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
发现airm2m/air105在编译最后一步会出错

#### 你的解决方案是什么 (what is your solution)
修改makesoc.py

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:bsp/airm2m/air105

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-09-29 16:35 UTC, mysterywolf commented
@Dozingfiretruck 帮忙review一下这个PR呗

2024-09-29 21:04 UTC, supperthomas approved these changes

2024-09-30 00:46 UTC, mysterywolf commented on bsp/airm2m/air105/board/board.c
> +    extern void rt_hw_systick_init(void);
这个函数的头文件在哪里呀 可否直接引用头文件呀

2024-09-30 00:46 UTC, mysterywolf commented on bsp/airm2m/air105/makesoc.py
> +    print('end')
多敲一个换行

2024-09-30 00:46 UTC, mysterywolf requested changes

2024-09-30 00:46 UTC, mysterywolf commented on bsp/airm2m/air105/libraries/HAL_Driver/Src/core_dma.c
> +                hwDMAChannal[i].CB(hwDMAChannal[i].pData,(void *)0xffffffff);
```suggestion
                hwDMAChannal[i].CB(hwDMAChannal[i].pData, (void *)0xffffffff);
```

2024-09-30 05:36 UTC, hydevcode commented on bsp/airm2m/air105/board/board.c
> +    extern void rt_hw_systick_init(void);
已手动声明函数在对应的头文件，修改好了

2024-09-30 05:36 UTC, hydevcode commented on bsp/airm2m/air105/makesoc.py
> +    print('end')
已修改

2024-09-30 05:41 UTC, hydevcode commented on bsp/airm2m/air105/libraries/HAL_Driver/Src/core_dma.c
> +                hwDMAChannal[i].CB(hwDMAChannal[i].pData,(void *)0xffffffff);
已合并

2024-09-30 05:45 UTC, Dozingfiretruck commented
因为会网络下载bl所以ci 是否添加评估一下
另外 合宙已经放弃mcu业务，此bsp是否删除也请评估下 
@mysterywolf

2024-09-30 22:49 UTC, mysterywolf approved these changes

2024-09-30 22:49 UTC, mysterywolf commented
先保留吧

2024-09-30 22:50 UTC, merged