[libcpu][risc-v] fix the bug when using ASID in the RV64 MMU.
RT-Thread/rt-thread pull request #9511
Opened 2024-10-08 08:10 UTC by zhangjing0303

Corrected the SATP register to ensure it uses the correct 64-bit format as required by the system architecture.

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
For the qemu-virt64-riscv BSP, when running the smart version, the system fails to boot properly if ARCH_USING_ASID=y.

#### 你的解决方案是什么 (what is your solution)
Change the type of the variable satp_reg in rt_hw_asid_init to rt_uint64_t.

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/qemu-virt64-riscv

- .config: CONFIG_ARCH_USING_ASID=y

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-10-08 08:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9511) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=9511) it.</sub>

2024-10-09 11:39 UTC, Rbb666 approved these changes

2024-10-11 02:20 UTC, polarvid requested changes

2024-10-11 02:20 UTC, polarvid commented on libcpu/risc-v/common64/asid.c
> +    asm volatile("sfence.vma x0, x0");
建议使用 `__asm__`，对非 GNU 的 C compiler 更友好一些。

```suggestion
    __asm__ volatile("sfence.vma x0, x0");
```

另外感觉这里立即重置 satp 怪怪的。因为正常是两个启动阶段，做两次 satp 设置。第一次是初始映射，使用大粒度 pte，为了在初始化中设置最基础的虚存属性，并进入线性地址空间。第二次是按照虚存配置的映射，可能从静态/动态配置中读取运行时虚存布局，按照应用、驱动的需求配置内核地址空间。

这里在中间又重置了一次 satp，并不是特别必要。或许是可以把 ASID 初始化操作合并到 `rt_hw_mem_setup_early` 中。

2024-10-11 02:31 UTC, zhangjing0303 commented on libcpu/risc-v/common64/asid.c
> +    asm volatile("sfence.vma x0, x0");
这里主要是为了获取mmu asid的信息，因为涉及到写satp寄存器，确实合并到rt_hw_mem_setup_early 中会更合理些

2024-10-11 03:25 UTC, polarvid approved these changes

2024-10-11 04:10 UTC, mysterywolf approved these changes

2024-10-11 04:10 UTC, merged