Dev
RT-Thread/rt-thread pull request #9513
Opened 2024-10-08 08:47 UTC by 1078249029

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
[issuse/5941](https://github.com/RT-Thread/rt-thread/issues/5941)

#### 你的解决方案是什么 (what is your solution)
add the spi driver for esp32c3

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/ESP32_C3

- .config: RT_USING_SPI、BSP_USING_SPI、BSP_USING_SPI2

- action:
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-10-08 08:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9513) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9513) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=9513) it.</sub>

2024-10-08 08:59 UTC, 1078249029 commented
请问我在想我自己的仓库提交commit的时候没有触发workflow，需要我做什么？这是我第一次提交PR，有错误的地方希望前辈们多多担待

2024-10-08 09:01 UTC, 1078249029 commented
还有个问题是我提交的文件更改里有个rtconfig.py文件，这个文件配置了环境变量，但我的位置与主线的默认配置不同。我需要修改.gitignore再重新提交PR么

2024-10-08 09:21 UTC, supperthomas requested changes

2024-10-08 09:21 UTC, supperthomas commented on bsp/ESP32_C3/drivers/drv_spi.c
> + * 2021-12-20     BruceOu      first implementation
感谢提交，这里可以写上自己的github名

2024-10-08 09:21 UTC, supperthomas commented on bsp/ESP32_C3/drivers/drv_spi.h
> + * 2021-12-20     BruceOu      first implementation
同上

2024-10-08 09:21 UTC, supperthomas commented on bsp/ESP32_C3/main/main.c
> +    rt_hw_spi_device_attach(SPI_BUS_NAME, W25Q_SPI_DEVICE_NAME, GPIO_NUM_10 );
测试代码不用提交

2024-10-08 09:21 UTC, supperthomas commented on bsp/ESP32_C3/rtconfig.h
> +#define BSP_USING_SPI
这个默认要开吗？可以不用开。

2024-10-08 09:21 UTC, supperthomas commented on bsp/ESP32_C3/.config
> +# CONFIG_PKG_USING_ARDUINO_RUNNINGMEDIAN is not set
.config rtconfig.h  rtconfig.py 如果没有特别修改，不用提交。

2024-10-08 09:26 UTC, supperthomas commented
> 请问我在想我自己的仓库提交commit的时候没有触发workflow，需要我做什么？这是我第一次提交PR，有错误的地方希望前辈们多多担待

如果你想在你的branch触发workflow，你需要PR到你自己的repo的master上，并且改下action中的限制，action有限制。
你可以尝试手动触发，
到自己的repo下面打开action tab。 然后选择需要触发的workflow，然后选择自己的branch，可以参考下面的图片，手动触发测试。
![image](https://github.com/user-attachments/assets/2ac19c4f-ee2d-4622-a826-7182ed084d2d)

2024-10-08 11:36 UTC, 1078249029 commented on bsp/ESP32_C3/main/main.c
> +    rt_hw_spi_device_attach(SPI_BUS_NAME, W25Q_SPI_DEVICE_NAME, GPIO_NUM_10 );
请问这里如何取消提交测试代码？是需要提交一个新的pr么？

2024-10-08 14:04 UTC, supperthomas requested changes

2024-10-08 14:04 UTC, supperthomas commented on bsp/ESP32_C3/main/main.c
> +#include "rttypes.h"
?

2024-10-08 14:04 UTC, supperthomas commented on bsp/ESP32_C3/main/main.c
> +#include "rttypes.h"
这个文件没有特别修改，不用提交

2024-10-08 14:05 UTC, supperthomas requested changes

2024-10-08 14:05 UTC, supperthomas commented on bsp/ESP32_C3/drivers/Kconfig
> +#include "rtconfig.h"
？？？

2024-10-08 14:35 UTC, supperthomas approved these changes

2024-10-08 22:34 UTC, merged

2024-10-09 00:10 UTC, supperthomas commented
@mysterywolf CI 有报错
build stm32/stm32f407-rt-spark online-packages/multimedia/lvgl/lvgl-latest.attach failed.

2024-10-09 00:15 UTC, mysterywolf commented
我注意到了 LVGL上游主线新改了什么东西导致的，我在给他们提交PR