Fixed an issue that caused spi bus deadlock in the spi configuration
RT-Thread/rt-thread pull request #9517
Opened 2024-10-09 07:41 UTC by kurisaW

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

修复因spi配置中检测重复配置的互斥锁释放问题

#### 你的解决方案是什么 (what is your solution)

当检测到spi bus已经完成配置后，会返回-RT_EBUSY，需要在此之前释放该bus持有的互斥锁

#### 请提供验证的bsp和config (provide the config and bsp) 

修复前：
![image](https://github.com/user-attachments/assets/ee755a40-4647-4805-b6ff-4103d35bf916)

修复后：
![image](https://github.com/user-attachments/assets/d8460b5b-0ccb-49ae-84eb-29004d4cc08e)

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-10-09 21:07 UTC, mysterywolf requested changes

2024-10-09 21:07 UTC, mysterywolf commented on components/drivers/spi/dev_spi_core.c
>                  return -RT_EBUSY;
看看这样行不行？

```suggestion
                result = -RT_EBUSY;
```

2024-10-10 01:26 UTC, kurisaW commented on components/drivers/spi/dev_spi_core.c
>                  return -RT_EBUSY;
可以的，已修改

2024-10-10 01:31 UTC, mysterywolf approved these changes

2024-10-10 01:32 UTC, merged