[components][driver]add phy and mdio bus
RT-Thread/rt-thread pull request #9524
Opened 2024-10-11 08:23 UTC by zhuzhuzhus

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

add mdio bus and phy bus to kernel,the phy bus use rt_bus frame ,driver writer can write phy_driver first .when mac driver need to use phy they can register phy_device and pjhy_devie will serach for driver which match by uid and mask,if no driver match with the device that you register,phy_bus will return the genphy to you device,the genphy driver is the general driver for phy,so you can use it but it can not support the capcity of chip it may be cause performance is not up to peak

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: rk3568

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-10-11 08:40 UTC, zhuzhuzhus commented
https://github.com/RT-Thread/rt-thread/pull/9470#issue-2547447682
依赖于该pr

2024-10-11 14:27 UTC, zmshahaha commented on components/drivers/phy/phy.c
> -rt_err_t rt_hw_phy_register(struct rt_phy_device *phy, const char *name)
<img width="981" alt="123" src="https://github.com/user-attachments/assets/10dc1c2a-596f-46de-bec5-9b47e00e4796">

2024-10-12 02:03 UTC, zhuzhuzhus commented on components/drivers/phy/phy.c
> -rt_err_t rt_hw_phy_register(struct rt_phy_device *phy, const char *name)
没想到有bsp用到了这玩意，那我看看怎么修改

2024-10-12 03:39 UTC, zmshahaha commented on components/drivers/phy/general_phy.h
> +struct rt_phy_device;
?

2024-10-12 06:06 UTC, zmshahaha commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
19这个数字咋来的，最好别出现纯数字

2024-10-12 06:23 UTC, zhuzhuzhus commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
![image](https://github.com/user-attachments/assets/35b52bd3-88af-4ef5-b488-2fc86ed00f03)
phy节点固定的，这样没什么问题，也不会变

2024-10-12 06:36 UTC, zmshahaha commented
不要乱标resolved

2024-10-12 06:42 UTC, zmshahaha commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
这个还没有resolved

2024-10-12 07:39 UTC, zhuzhuzhus commented
> 请不要随意标resolved，上面问题还没解决

哪个

2024-10-12 09:11 UTC, zmshahaha requested changes

2024-10-12 09:11 UTC, zmshahaha commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
改成sizeof("ethernet-phy.....")吧

2024-10-12 09:13 UTC, zmshahaha commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
换成sizeof("ether.....")吧

2024-10-12 09:25 UTC, zhuzhuzhus commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
这个感觉没必要吧，用19反而更直观？

2024-10-12 09:50 UTC, zmshahaha commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
> s[sizeof(ethernet-phy-idVVVV.)/sizeof(s[0])]

?

2024-10-12 09:52 UTC, zmshahaha commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
s[sizeof(ethernet-phy-idVVVV.)]

2024-10-14 02:35 UTC, zhuzhuzhus commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
我改了一种配对方式，用sscanf了

2024-10-14 02:45 UTC, zmshahaha commented on components/drivers/phy/ofw.c
> +            if (s && s[19] == '.')
🆗

2024-11-18 05:56 UTC, Rbb666 commented
@zhuzhuzhus PR有冲突了，帮忙解决下

2024-11-18 06:08 UTC, zhuzhuzhus commented
> @zhuzhuzhus PR有冲突了，帮忙解决下

ok啦

2024-11-18 06:41 UTC, Rbb666 commented on components/drivers/phy/phy.c
> +#include <drivers/phy.h>
13、14行统一 #include rtdevice.h 就行

2024-11-18 06:46 UTC, Rbb666 commented on components/drivers/phy/ofw.c
> +#include <drivers/phy.h>
这块也是，引用rtdevice.h就行

2024-11-18 06:46 UTC, Rbb666 commented on components/drivers/phy/mdio.h
> +#define RT_MDIO_DEVAD_NONE          (-1)
注释看着乱乱的，可以格式化下吗？

2024-11-18 06:46 UTC, Rbb666 commented on components/drivers/phy/mdio.h
> +#include <drivers/phy.h>
#include rtdevice.h

2024-11-18 06:46 UTC, Rbb666 commented on components/drivers/phy/general_phy.h
> +#define SPEED_10        10
这个文件的注释也格式化下吧

2024-11-19 13:10 UTC, Rbb666 approved these changes

2024-11-20 01:44 UTC, zhuzhuzhus commented
> @zhuzhuzhus 还有冲突，麻烦解下谢谢

我这里没有看到有冲突呀
![image](https://github.com/user-attachments/assets/368d6e25-9c02-4b12-bc1b-3a95695fc6f3)

2024-11-20 02:34 UTC, merged