[components][finsh]在RT_USING_POSIX_STDIO时，使用get_console获取当前console描述符
RT-Thread/rt-thread pull request #9581
Opened 2024-10-25 09:13 UTC by judecumt

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
使用telnet，并打开RT_USING_POSIX_STDIO时，需使用get_console来get_char，否则不能正确获取输入

#### 你的解决方案是什么 (what is your solution)
get_char时使用get_console获取console描述符

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

2024-10-25 09:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9581) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9581) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=9581) it.</sub>

2024-10-25 21:46 UTC, mysterywolf requested changes

2024-10-25 21:46 UTC, mysterywolf commented on components/finsh/shell.c
> +#if RT_VER_NUM >= 0x50100
主线不需要区分版本号呀
直接保留最新版本的代码段即可

2024-10-26 02:28 UTC, judecumt commented on components/finsh/shell.c
> +#if RT_VER_NUM >= 0x50100
嗯  搜了下确实master里边没有这种宏  
如果有个bug，master v5.1.x等多个分支都需要修复，应该怎么操作呢？每个分支都提交修复commit？

2024-10-26 23:37 UTC, mysterywolf commented on components/finsh/shell.c
> +#if RT_VER_NUM >= 0x50100
没关系 合并之后我来cherrypick到其他分支

2024-10-27 08:21 UTC, judecumt commented on components/finsh/shell.c
> +#if RT_VER_NUM >= 0x50100
但是这里的`libc.h`以及`get_console`接口在 https://github.com/RT-Thread/rt-thread/commit/b08d8672d258b029edc4d2c45543c3af9e595830 这个commit被重构了，作者是你，如果不加版本宏区分是不能直接cherrypick的

2024-10-30 00:57 UTC, mysterywolf commented on components/finsh/shell.c
> +    if(read(rt_posix_stdio_get_console(), &ch, 1) > 0)
这块有问题呀，为什么直接使用STDIN_FILENO标准文件描述符不可以呢？

2024-10-30 14:41 UTC, judecumt commented on components/finsh/shell.c
> +    if(read(rt_posix_stdio_get_console(), &ch, 1) > 0)
实测打开telnet时，调用set_console的api后，STDIN_FILENO不起作用，无法获取输入，telnet我也有修改 https://github.com/RT-Thread-packages/netutils/pull/105

2024-11-04 01:15 UTC, mysterywolf commented on components/finsh/shell.c
> +    if(read(rt_posix_stdio_get_console(), &ch, 1) > 0)
请麻烦单独提一个PR 至保留针对当前版本的代码 无需考虑之前版本的兼容，后续我会根据这个PR重新cherry-pick到其他分支

2024-11-04 10:02 UTC, judecumt commented on components/finsh/shell.c
> +    if(read(rt_posix_stdio_get_console(), &ch, 1) > 0)
已修改

2024-11-05 03:02 UTC, mysterywolf approved these changes

2024-11-05 03:03 UTC, merged