[action] yml file adds the depends parameter
RT-Thread/rt-thread pull request #9627
Opened 2024-11-06 19:36 UTC by hydevcode

## 拉取/合并请求描述：(PR description)

[
#### 为什么提交这份PR (why to submit this PR)
yml file 添加depends参数
另外支持depends的循环嵌套，如果发生depends之间的死循环会报提示
按照yml开启配置顺序来对应.config的开启配置顺序
添加depend_scons_arg参数支持，当父配置开启，子配置一同开启

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [x] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

2024-11-06 20:26 UTC, supperthomas requested changes

2024-11-06 20:26 UTC, supperthomas commented on tools/ci/bsp_buildings.py
> +                        detail_temp,scons_arg_temp=get_details_and_dependencies(dep_details.get('depends'), projects, seen)
可否添加example YML 文件展示一下

2024-11-06 20:43 UTC, hydevcode commented on tools/ci/bsp_buildings.py
> +                        detail_temp,scons_arg_temp=get_details_and_dependencies(dep_details.get('depends'), projects, seen)
已添加

2024-11-06 23:20 UTC, supperthomas approved these changes

2024-11-07 01:47 UTC, merged

2024-11-07 06:35 UTC, supperthomas commented on bsp/nrf5x/nrf52840/.ci/attachconfig/ci.attachconfig.yml
> +    depend_scons_arg:
```
devices.strict: &scons
    scons_arg: 
      - '--strict'
nimble: 
    kconfig: 
      - CONFIG_BSP_USING_NIMBLE=y
      - CONFIG_PKG_USING_NIMBLE_V100=y
nimble.advertiser:
    <<: *scons
    kconfig: 
      - CONFIG_BSP_USING_NIMBLE=y
```
strict 参考这个修改一下