support milkv-duo rt-smart
RT-Thread/rt-thread pull request #9657
Opened 2024-11-17 04:23 UTC by flyingcys

1. switches memory management to SLA

2. use ioremap modification driver

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
cvitek/cv18xx_risc-v 支持rt-smart

#### 你的解决方案是什么 (what is your solution)
1. switches memory management to SLA

2. use ioremap modification driver

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [ ] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

2024-11-17 10:44 UTC, BernardXiong commented on bsp/cvitek/drivers/drv_sdhci.c
> +#ifdef RT_USING_SMART
`mmu.h` 并不是smart这边特有的，所有这里可以不用区分是否是smart。

2024-11-17 22:33 UTC, BernardXiong approved these changes

2024-11-19 08:33 UTC, unicornx requested changes

2024-11-19 08:33 UTC, unicornx commented on bsp/cvitek/drivers/drv_uart.c
> +    uart->hw_base = (rt_ubase_t)DRV_IOREMAP((void*)uart->hw_base, 0x10000);
你这么改确定 ARM 没有问题？

2024-11-19 08:33 UTC, unicornx commented on bsp/cvitek/drivers/libraries/eth/dw_eth_mac.c
> +#endif
这种类似的 V2P 的操作能不能用类似 DRV_IOREMAP 那样做一个通用的宏，目前代码中类似的地方改了很多。

2024-11-20 03:39 UTC, unicornx commented
基于这个 PR 测试了一下 duo 256，发现大核启动正常，进入 Smart 控制台，但是小核无显示。

目前 master 上 （f5aca55a26）我验证了大小核（都是标准版）启动是正常的。

2024-11-20 04:02 UTC, unicornx commented on bsp/cvitek/drivers/libraries/cv180x/pinctrl.h
> +#define PINMUX_BASE (uintptr_t)DRV_IOREMAP((void *)0x3002000, 0x1000)
duo/cv180b 的 PINMUX_BAS 也应该是 0x03001000， 不是 0x03002000

2024-11-23 12:08 UTC, flyingcys commented on bsp/cvitek/drivers/drv_eth.c
> +    mmio_write_32(ETH_PHY_BASE + 0x804, 0x0001);
PHY相关寄存器在手册里面没有提供相关资料

2024-11-24 03:01 UTC, unicornx commented
第二轮 review 的 comment：

## COMMENT 1：

`bsp/cvitek/cv18xx_risc-v/rtconfig.py`

```c
if PLATFORM == 'gcc':
    # toolchains
    #PREFIX  = 'riscv64-unknown-elf-'  // 这行注释建议删掉
```

## COMMENT 2

`bsp/cvitek/drivers/drv_adc.c`

```c
for (i = 0; i < sizeof(adc_dev_config) / sizeof(adc_dev_config[0]); i++)
    {
        adc_dev_config[i].base = (rt_ubase_t)DRV_IOREMAP((void *)adc_dev_config[i].base, 0x1000); // 这行多余的，又覆盖了前面的 ioremap 裸机，而且这里 size 的 0x1000 对 “adc1” 是不对的。
```

## COMMENT 3

这个补丁改动了一些和 ARM 相关的逻辑，是否测试过 ARM 可以编译运行吗？

2024-11-24 07:04 UTC, flyingcys commented
> 第二轮 review 的 comment：
> 
> ## COMMENT 1：
> `bsp/cvitek/cv18xx_risc-v/rtconfig.py`
> 
> ```c
> if PLATFORM == 'gcc':
>     # toolchains
>     #PREFIX  = 'riscv64-unknown-elf-'  // 这行注释建议删掉
> ```
> 
> ## COMMENT 2
> `bsp/cvitek/drivers/drv_adc.c`
> 
> ```c
> for (i = 0; i < sizeof(adc_dev_config) / sizeof(adc_dev_config[0]); i++)
>     {
>         adc_dev_config[i].base = (rt_ubase_t)DRV_IOREMAP((void *)adc_dev_config[i].base, 0x1000); // 这行多余的，又覆盖了前面的 ioremap 裸机，而且这里 size 的 0x1000 对 “adc1” 是不对的。
> ```
> 
> ## COMMENT 3
> 这个补丁改动了一些和 ARM 相关的逻辑，是否测试过 ARM 可以编译运行吗？

1-2. 已修改
3. 未测试arm相关内容，理论上只是取消了arm的宏对arm没有影响

2024-11-24 13:42 UTC, BernardXiong commented
> >   
> > ## COMMENT 3
> > 这个补丁改动了一些和 ARM 相关的逻辑，是否测试过 ARM 可以编译运行吗？
> 
> 1-2. 已修改 3. 未测试arm相关内容，理论上只是取消了arm的宏对arm没有影响

感觉关于arm部分可以先不管，或者等后续arm那边维护人来修（PR不可能总是等人的）

2024-11-25 02:43 UTC, unicornx commented
第三轮 review pass

测试了 duo 和 duo256m， 默认只 enable 了 uart
- 小核 （标准版）+ 大核（标准版）：pass，console 显示正常
- 小核 （标准版）+ 大核（smart版）：pass，console 显示正常

duoS 没有测试

2024-11-25 02:47 UTC, unicornx approved these changes

2024-11-25 02:48 UTC, merged