[serial] add bypass for serial
RT-Thread/rt-thread pull request #9713
Opened 2024-11-27 07:14 UTC by zhuzhuzhus

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
add bypass for serial ,when irq coming the irq will read a byte and get it for bypass upper list if upper list do not need it ,the byte will put in serial fifo .

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [ ] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

2024-11-28 03:27 UTC, Ryan-CW-Code commented
现在楼主给V1贡献这么好的PR👍

RTT在2022年V4.1.0版本就推出了V2版本的串口驱动，但又没有引导开发者优先使用维护那个版本。
现在已经马上V5.2.0版本了，V1版本依然是大部分BSP的首选项。
同时维护V1和V2是资源浪费，对V1版本很多优质PR，V2版本都没有进行同步吸收。关于V1的PR比V2还要多😑
如果V2是RTT串口驱动以后的方向，新版本要兼容V1的API也应该通过V2封装一层V1的兼容层。
@Rbb666

2024-11-28 09:46 UTC, polarvid requested changes

2024-11-28 09:46 UTC, polarvid commented on components/drivers/include/drivers/dev_serial.h
>      struct rt_device_notify rx_notify;
rx_notify 是 v5.0.0 同步 smart 引入的成员。引入这个框架之后，这些代码就不需要了。包括 Smart TTY 框架，都默认以 Bypass 的方式实现即可。旧的包袱没有必要一直背着的。

2024-11-28 09:59 UTC, zhuzhuzhus commented on components/drivers/include/drivers/dev_serial.h
>      struct rt_device_notify rx_notify;
已删除notify相关代码，只保留了bypass部分

2024-12-08 03:23 UTC, Rbb666 commented
> 现在楼主给V1贡献这么好的PR👍
> 
> RTT在2022年V4.1.0版本就推出了V2版本的串口驱动，但又没有引导开发者优先使用维护那个版本。 现在已经马上V5.2.0版本了，V1版本依然是大部分BSP的首选项。 同时维护V1和V2是资源浪费，对V1版本很多优质PR，V2版本都没有进行同步吸收。关于V1的PR比V2还要多😑 如果V2是RTT串口驱动以后的方向，新版本要兼容V1的API也应该通过V2封装一层V1的兼容层。 @Rbb666

感谢建议，这类问题建议您这边先提一个ISSUE先记录下来，我们下次例会一起讨论下~

2024-12-17 03:08 UTC, Rbb666 approved these changes

2024-12-17 03:08 UTC, merged