[bsp][cvitek] update the arm core project
RT-Thread/rt-thread pull request #9749
Opened 2024-12-07 17:09 UTC by liYony

## 拉取/合并请求描述：(PR description)

[

更新 cvitek bsp 的ARM核相关工程文件。

#### 为什么提交这份PR (why to submit this PR)

- 解决编译报错问题。
- 解决固件无法成功运行的问题。

#### 你的解决方案是什么 (what is your solution)

- 编译报错主要是因为对于cvitek单核包含`#include <smp_call.h>`导致找不到rt_hw_spinlock_t数据类型。
- 固件无法运行主要是因为，aarch64相关的bsp无论是在运行标准版核Smart对于外设的访问都需要做ioremap。

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [ ] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

2024-12-08 15:24 UTC, BernardXiong commented on bsp/cvitek/drivers/drv_ioremap.h
> +#include <ioremap.h>
前面 `#ifdef RT_USING_SMART` 的时候已经包含了这个头文件

2024-12-08 15:27 UTC, BernardXiong commented on bsp/cvitek/drivers/drv_ioremap.h
> +#include <ioremap.h>
这里感觉似乎不那么对的样子。是说， 非smart环境下，aarch64下也需要做ioremap吗？如果是这样，似乎riscv64下也应该做ioremap啊

2024-12-08 15:32 UTC, liYony commented on bsp/cvitek/drivers/drv_ioremap.h
> +#include <ioremap.h>
![image](https://github.com/user-attachments/assets/cb8b6ff6-4552-4092-981a-7980c8a9fd11)
 rv 非smart没开mmu  但是 arm 是否是smart都开mmu了

2024-12-08 15:33 UTC, liYony commented on bsp/cvitek/drivers/drv_ioremap.h
> +#include <ioremap.h>
所以没开smart rv这边可以不用做ioremap

2024-12-08 15:35 UTC, liYony commented on bsp/cvitek/drivers/drv_ioremap.h
> +#include <ioremap.h>
![image](https://github.com/user-attachments/assets/5f83b093-f1e8-49d1-ab21-cfb5b873c8f9)

2024-12-09 00:16 UTC, unicornx commented
@liYony 请问你这个 pr 是不是为了修改 https://github.com/RT-Thread/rt-thread/issues/9694 这个 issue？
如果是的，请将 PR 和 issue 关联起来，方法很简单，就是在 PR 的描述中加上 `Fixed #9696`， 具体参考 <https://github.com/RT-Thread/rt-thread/pull/9705> 的写法如下：

2024-12-09 13:45 UTC, liYony commented
> @liYony 请问你这个 pr 是不是为了修改 #9694 这个 issue？ 如果是的，请将 PR 和 issue 关联起来，方法很简单，就是在 PR 的描述中加上 `Fixed #9696`， 具体参考 #9705 的写法如下： ![image](https://private-user-images.githubusercontent.com/2476165/393655882-8156c7f6-39b5-409c-8055-b9dae8deb2f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTIwNzksIm5iZiI6MTczMzc1MTc3OSwicGF0aCI6Ii8yNDc2MTY1LzM5MzY1NTg4Mi04MTU2YzdmNi0zOWI1LTQwOWMtODA1NS1iOWRhZThkZWIyZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTM0MjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZjZjIwOGZiZWMxMDMzNWE5NGYzNzRiOGNhNmY3NjhhNWZjMTM4Mjc0ZTdmNjdhNjA0YzA5ODhjNjI2ZTk3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gDaxIIRQJvDVfTgIPygqyz7idgekn0wtOQsNmjgepn0)
> 
> BTW： 如果你这个 pr 就是 fix 了 #9694，我就 reassign 给你吧，原来是 assign 给 @Z8MAN8， 但是一直没动静。

ok

2024-12-10 02:53 UTC, unicornx commented
请补全 commit 信息。具体要求参考：<https://github.com/plctlab/plct-rt-thread/tree/notes/0.notes#%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4-git-commit>

2024-12-10 03:03 UTC, unicornx commented on libcpu/aarch64/common/setup.c
这个修改影响了 common 的逻辑，不适合和这个 duo 特定的 pr 一起合入，请另外提一个 pr 并详细说明修改的理由。

2024-12-10 05:54 UTC, unicornx commented on bsp/cvitek/drivers/drv_ioremap.h
> +#endif /* ARCH_ARM */
你是想表达对于 ARCH_ARM， 无论是否 smart 都要 ioremap 么？是否可以写成下面这个样子更清楚点：

```c
#if defined RT_USING_SMART || defined ARCH_ARM
#include <ioremap.h>

#define DRV_IOREMAP(addr, size) rt_ioremap(addr, size)
#define DRV_IOUNMAP(addr) rt_iounmap(addr)
#else
#define DRV_IOREMAP(addr, size) (addr)
#define DRV_IOUNMAP(addr)
#endif
```

2024-12-10 05:56 UTC, unicornx requested changes
见上面的 comments

2024-12-10 14:09 UTC, liYony commented on bsp/cvitek/drivers/drv_ioremap.h
> +#endif /* ARCH_ARM */
Accept

2024-12-10 14:19 UTC, liYony commented on libcpu/aarch64/common/setup.c
https://github.com/RT-Thread/rt-thread/pull/9771 Accept and Done!

2024-12-10 14:20 UTC, liYony commented
此 pr 合并前须先合并https://github.com/RT-Thread/rt-thread/pull/9771，否则还是会存在编译报错

2024-12-12 01:06 UTC, unicornx commented
3 个问题：
1）PR 中的 commit 不要保留开发历史，如果要 review，除非特别情况下需要将本次 PR 分多个 commit 提交，否则请 squash

2） 请补全 commit 信息。具体要求参考：<https://github.com/plctlab/plct-rt-thread/tree/notes/0.notes#%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4-git-commit>

3） 修改完后如果需要提请第二次 review，请点击 re-request review
![image](https://github.com/user-attachments/assets/fe791dbd-bf71-4178-9819-24aa73dd92a0)

2024-12-30 13:06 UTC, closed without merging

2024-12-30 13:06 UTC, unicornx commented
已经在 #9835 中解决了，关闭这个 PR