[bsp][ESP32C3] support soft i2c and rt_hw_us_delay
RT-Thread/rt-thread pull request #9751
Opened 2024-12-08 05:02 UTC by 1078249029

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

https://github.com/RT-Thread/rt-thread/issues/5941

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [ ] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

2024-12-08 09:15 UTC, supperthomas commented
yml加一下配置

2024-12-08 12:31 UTC, supperthomas approved these changes

2024-12-08 12:37 UTC, supperthomas requested changes

2024-12-08 12:37 UTC, supperthomas commented on bsp/ESP32_C3/.ci/attachconfig/ci.attachconfig.yml
> +      - CONFIG_BSP_USING_HW_I2C=y
为什么这里选HWI2c？

2024-12-08 13:31 UTC, 1078249029 commented on bsp/ESP32_C3/.ci/attachconfig/ci.attachconfig.yml
> +      - CONFIG_BSP_USING_HW_I2C=y
> 为什么这里选HWI2c？

之前在https://github.com/RT-Thread/rt-thread/pull/9643#issuecomment-2475406186问过模块冲突是否分别写ci，但是一起写是允许的，既然这样那就把软件硬件i2c都测一遍吧

2024-12-08 21:26 UTC, supperthomas commented on bsp/ESP32_C3/.ci/attachconfig/ci.attachconfig.yml
> +      - CONFIG_BSP_USING_HW_I2C=y
分开写比较合理一些。检查一下ci是否测试到该.c文件

2024-12-08 21:33 UTC, supperthomas commented on bsp/ESP32_C3/.ci/attachconfig/ci.attachconfig.yml
> +      - CONFIG_BSP_USING_HW_I2C=y
如果确实应用中需要组合场景，可以再加个配置

2024-12-08 21:35 UTC, supperthomas requested changes

2024-12-08 21:35 UTC, supperthomas commented on bsp/ESP32_C3/drivers/SConscript
>  if GetDepend('BSP_USING_I2C'):
这里BSP USING I2C有kconfig对应吗？

2024-12-09 01:39 UTC, 1078249029 commented on bsp/ESP32_C3/drivers/SConscript
>  if GetDepend('BSP_USING_I2C'):
> 这里BSP USING I2C有kconfig对应吗？我看到上面BSP_USING_I2C0 已经删掉了。

有的
```c
menuconfig BSP_USING_I2C
        bool "Enable I2C"
        default n
        select RT_USING_I2C
        if BSP_USING_I2C
            config BSP_USING_HW_I2C
                bool "Enable HardWare I2C"
                default n
```

2024-12-09 01:47 UTC, supperthomas commented
感谢提交PR，
  添加yml相关配置的时候用一个yml文件，
参考文档https://mp.weixin.qq.com/s/_NnsRlQliF2STD2FelR-Bw

2024-12-09 01:54 UTC, supperthomas requested changes

2024-12-09 01:54 UTC, supperthomas commented on bsp/ESP32_C3/drivers/SConscript
>  if GetDepend('BSP_USING_I2C'):
那选择BSP_USING_I2C  默认添加drv_hw_i2c.c ？

2024-12-09 01:57 UTC, supperthomas requested changes

2024-12-09 01:57 UTC, supperthomas commented on bsp/ESP32_C3/.ci/attachconfig/ci.attachconfig.yml
> +      - CONFIG_BSP_USING_HW_I2C=y
这里缺个BSP_USING_I2C配置。

2024-12-09 02:38 UTC, 1078249029 commented
这里为什么不能quote replay了？🤔

> 那选择BSP_USING_I2C 默认添加drv_hw_i2c.c ？

我是将i2c的总开关用menuconfig定义的，内部两个配置项分别使用BSP_USING_HW_I2C和BSP_USING_SW_I2C定义，公共依赖项目放到menuconfig中

2024-12-09 02:59 UTC, supperthomas commented
![image](https://github.com/user-attachments/assets/281cb4da-a73e-4515-a32c-5d17af253b3d)

2024-12-09 03:02 UTC, 1078249029 commented
> ![image](https://private-user-images.githubusercontent.com/60349489/393685081-281cb4da-a73e-4515-a32c-5d17af253b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTM1MTYsIm5iZiI6MTczMzcxMzIxNiwicGF0aCI6Ii82MDM0OTQ4OS8zOTM2ODUwODEtMjgxY2I0ZGEtYTczZS00NTE1LWEzMmMtNWQxN2FmMjUzYjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAzMDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzM1NDVmZWQ1YTE3MzJlODEyZTUyMmQ1YzQ2NjYwMGUxMzZjNTc5ZmJiMmYzNzQxMjkwYTdjOTg3YjMxYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nvBrPgslL9uWb8EtP0cFUv9r4haXHHYo_HIWkh0ptUk)



> ![image](https://private-user-images.githubusercontent.com/60349489/393685081-281cb4da-a73e-4515-a32c-5d17af253b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTM1MTYsIm5iZiI6MTczMzcxMzIxNiwicGF0aCI6Ii82MDM0OTQ4OS8zOTM2ODUwODEtMjgxY2I0ZGEtYTczZS00NTE1LWEzMmMtNWQxN2FmMjUzYjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAzMDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzM1NDVmZWQ1YTE3MzJlODEyZTUyMmQ1YzQ2NjYwMGUxMzZjNTc5ZmJiMmYzNzQxMjkwYTdjOTg3YjMxYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nvBrPgslL9uWb8EtP0cFUv9r4haXHHYo_HIWkh0ptUk)

这个hw_i2c代码在我机器上也报warning，我之前曾经尝试过修改，但貌似会破坏原有功能（我不清楚时什么情况）。没改之前会传输7个bit，改之后就收不到任何消息了

2024-12-09 06:04 UTC, supperthomas approved these changes

2024-12-09 09:53 UTC, supperthomas commented
commit 建议用命令`git rebase -i HEAD~n`
n代表多少个

2024-12-10 00:44 UTC, mysterywolf approved these changes

2024-12-10 00:44 UTC, merged