[bsp][stm32] hardware i2c driver add support for STM32F1 series
RT-Thread/rt-thread pull request #9768
Opened 2024-12-10 05:59 UTC by zzk597

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

- 我正在尝试使用rt-thread进行项目开发，发现硬件I2C驱动并没有支持我使用的STM32F1系列芯片。

#### 你的解决方案是什么 (what is your solution)

- 基于现有驱动完善对STM32F1系列的支持
- 完善的过程中发现了现有驱动的通用bug，并进行了修复

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: 没有官方BSP列表中的开发板，使用的是基于模板修改而来的BSP。
- 使用scons --dist命令将BSP导出，因文件上传大小限制，已剔除rt-thread文件夹：[project.zip](https://github.com/user-attachments/files/18072648/project.zip)

- .config: bsp工程中board文件夹下的Kconfig文件，添加以下定义：

```
menu "On-chip Peripheral Drivers"
...
...
...
    menuconfig BSP_USING_I2C
        bool "Enable I2C1 BUS (hardware)"
        default n
        select RT_USING_I2C
        if BSP_USING_I2C
            config BSP_USING_HARD_I2C1
                bool "Enable I2C1 BUS"
                default n
				
            config BSP_I2C1_TX_USING_DMA
                bool "Enable I2C1 TX DMA"
                depends on BSP_USING_HARD_I2C1
                default n
				
            config BSP_I2C1_RX_USING_DMA
                bool "Enable I2C1 RX DMA"
                depends on BSP_USING_HARD_I2C1
                default n
        endif
...
...
...
```

- action: null

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [x] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

2024-12-10 05:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9768) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9768) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=9768) it.</sub>

2024-12-10 23:38 UTC, mysterywolf requested changes

2024-12-10 23:38 UTC, mysterywolf commented on bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.h
> -#endif
为什么把这个删除了

2024-12-13 12:16 UTC, Rbb666 approved these changes

2024-12-13 14:16 UTC, supperthomas commented
感谢pr，可否用stm32f103_bulepill添加yml文件提供相关的配置？参考链接https://mp.weixin.qq.com/s/_NnsRlQliF2STD2FelR-Bw

2024-12-13 22:45 UTC, mysterywolf approved these changes

2024-12-13 22:46 UTC, merged