rt_hw_spinlock_t cannot be found on single core include smp_call.h
RT-Thread/rt-thread pull request #9771
Opened 2024-12-10 14:18 UTC by liYony

## 拉取/合并请求描述：(PR description)

[

单核在setup.c 文件中#include <smp_call.h> 会找不到rt_hw_spinlock_t定义，必须要打开RT_USING_SMP宏才能include此文件。

#### 为什么提交这份PR (why to submit this PR)

#### 你的解决方案是什么 (what is your solution)

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [ ] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

2024-12-10 23:38 UTC, mysterywolf approved these changes

2024-12-12 00:52 UTC, unicornx commented
我查了一下代码，造成编译不过的原因在于 `./libcpu/aarch64/common/include/cpuport.h` 中 `rt_hw_spinlock_t` 的定义依赖于 `RT_USING_SMP` 的定义：

```c
#ifdef RT_USING_SMP

/**
 * Spinlock
 */

typedef struct
{
    rt_uint32_t value;
} rt_hw_spinlock_t;

#endif /* RT_USING_SMP */
```

包含的路径大致如下：假设 -> 表示 `#include`
rtthread.h -> rtdef.h -> rttypes.h -> cpuport.h

以上是备忘。

但是目前的解法我觉得并不是最好的，如果搜索 `smp_call.h` 被 include 的地方：

```shell
$ find -name "*.c" | xargs grep -wn "smp_call.h"
./examples/utest/testcases/smp_call/smp_003_tc.c:14:#include <smp_call.h>
./examples/utest/testcases/smp_call/smp_002_tc.c:14:#include <smp_call.h>
./examples/utest/testcases/smp_call/smp_001_tc.c:15:#include <smp_call.h>
./examples/utest/testcases/smp_call/smp_004_tc.c:14:#include <smp_call.h>
./libcpu/aarch64/common/setup.c:16:#include <smp_call.h>
./components/drivers/smp_call/smp_call.c:13:#include "smp_call.h"
```

那么目前按照目前的做法只改动 `./libcpu/aarch64/common/setup.c:16` 我觉得是不够的。

所以既然 `smp_call.h` 本身的内容和 `RT_USING_SMP` 强相关，是否可以直接在 `smp_call.h` 中直接将内容用 `RT_USING_SMP` 括起来。

```c
#ifndef __SMP_IPI_H__
#define __SMP_IPI_H__
#include <rtthread.h>

#ifdef RT_USING_SMP
/* callback of smp call */
......
#endif // RT_USING_SMP

#endif // __SMP_IPI_H__
```

2024-12-12 01:02 UTC, unicornx requested changes
请参考 comments

2024-12-30 13:05 UTC, unicornx commented
已经在 #9835 中解决了，关闭这个 PR

2024-12-30 13:05 UTC, closed without merging